### PR TITLE
StudentHomePageUiTest: fix state leak #8524

### LINKED ISSUE #8524: StudentHomePageUiTest: fix state leak
v6.3.0, live server
StudentHomePageUiTest is failing due to a state leak from another test, most likely from StudentProfilePageUiTest.
Specifically, the course below is showing up in StudentHomePageUiTest

Taken from `StudentProfilePageUiTest.json`
```json
"SHomeUiT.CS2103": {
      "id": "SHomeUiT.CS2103",
      "name": "Software Engineering",
      "timeZone": "UTC"
    }
```
Location of the failure:
```
java.lang.AssertionError:  

	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:95)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:63)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:865)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:917)
	at teammates.test.cases.browsertests.StudentHomePageUiTest.testContentAndLogin(StudentHomePageUiTest.java:86)
	at teammates.test.cases.browsertests.StudentHomePageUiTest.allTests(StudentHomePageUiTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

image

Probably the same student is used in both tests. May be delete courses of the student in concern during the setup phase?

On a related note, should not use the prefix `SHomeUiT.` in test data of `StudentProfilePageUiTest.json`. Instead, it should use something like `SProfileUiT.`

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8524

**Outline of Solution**

- Corrected test data for SHomePageUiT[ Added googleID and hence the godmode changes]
- Refactored SProfilePageUiT to avoid unstable tests due to `localdb.bin` [`SHomeUiT` -> `SProfileUiT` to preent clash in data]
- GodMode changes

### CODE REVIEW

**Comment by tshradheya** [comment]
Proof: [StudentHomepageUiTest.java now passing in 1st attempt](https://travis-ci.org/TEAMMATES/teammates/builds/388095518#L2429)

File: src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java [hunk 1]
```diff
@@ -28,6 +28,7 @@ protected void prepareTestData() {
         String student1Email = student1GoogleId + "@gmail.com";
         testData.accounts.get("alice.tmms").googleId = student1GoogleId;
         testData.accounts.get("alice.tmms").email = student1Email;
+        testData.students.get("alice.tmms@SHomeUiT.CS2104").googleId = student1GoogleId;
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java]: Okay. Understood 👍

**Comment by tshradheya** [comment]
@LiHaoTan I have given this various tries and even on CI of this PR, all the three times the 2 tests passed in one go. Initially, even SHomePageUiT would fail(frequently) if run before anything else, now it doesn't, which I guess provides more stability to SProfilePageUiT

I investigated to find that the problem of extra course in SHomeUiT was happening when my `localdb.bin` was present. After deleting the file, the tests would pass. Now after this PR even after the `localdb.bin` was present the test passes in all possible combination of runs.

File: src/test/resources/data/StudentHomePageUiTest.json [hunk 2]
```diff
@@ -190,6 +190,7 @@
   },
   "students": {
     "alice.tmms@SHomeUiT.CS2104": {
+      "googleId": "${value.injected.in.testfile}",
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/resources/data/StudentHomePageUiTest.json]: If I am going to remove the initialization of `googleId` then there is no point of having this key value pair itself. I can add the comment in java file in `processTestData()`

**Comment by LiHaoTan** [comment]
@tshradheya I'm not catching why you are saying this works.

Because the account is shared, if `StudentProfilePageUiTest` runs before `StudentHomePageUiTest`, then `StudentHomePageUiTest` will fail.

This doesn't happen on the CI because a new instance is always spin up and `StudentProfilePageUiTest` always runs before `StudentHomePageUiTest`.

This also has the implication that even if all the CI tests passes once, it will fail if you run the CI tests again?

Whether the server is local or remote we would have to clear the courses for the shared account otherwise when we re-run CI tests it will fail.

File: src/test/resources/data/StudentHomePageUiTest.json (hunk 2 above)
[the remark this answers is not in the document]
Comment (LiHaoTan) [reply src/test/resources/data/StudentHomePageUiTest.json]: We still need this isn't it?

**Comment by tshradheya** [comment]
@LiHaoTan I understood your point. Made the necessary changes, please review

File: src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java [hunk 3]
```diff
@@ -196,4 +198,9 @@ private void loginWithPersistenceProblem() {
 
     }
 
+    @AfterClass
+    public void classTearDown() {
+        BackDoor.removeDataBundle(testData);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java]: We should document something like this:
``` Java
// The data associated with the test accounts have to be removed when the test ends because
// the test accounts are shared across tests. In particular, the courses of test student1 account is not the same as
// `StudentHomePageUiTest` so it has to be cleared before running that test. This also implies that other tests that
// runs at the same time may retrieve data created from this test.
//
// Thus, another test running at the same time may read data that was created in this test. This means if the data
// in this test would interfere with another test must run after this test.

// Another implication is that it means that test data is never cleared after. This is to save datastore costs
// as we already remove and restore the data bundle when the test runs.
//
// This raises the question of why we do not remove the data bundle when the class ends then we do not have to remove
// it from startup. The reason is that in the case a test fails to tear down (fail to remove data bundle),
// another test should have no reason to fail.
//
// Lastly, this means that removing the data bundle on startup is not always sufficient because a test only knows how
// to remove its associated data. This is the reason why `StudentHomePageUiTest` would fail if we don't remove the
// data bundle in this test.
// 
// Extending removeDataBundle to remove data outside its associated data would introduce unnecessary complications.
// For example, we don't know really know how much more extra data to remove. Removing too much data would not just
// incur higher datastore costs but we can make tests unexpectedly pass/fail when the data is expected to be
// not present/present in another test.
```

But not all of the comments here should be documented here. Can you extract the relevant parts to more appropriate locations?

**Comment by tshradheya** [comment]
Added comments. Ready for review

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 4]
```diff
@@ -349,6 +349,9 @@ public void classTearDown() {
         // data bundle in this test.
         // Extending removeDataBundle to remove data outside its associated data would introduce unnecessary complications
         // like extra cost and now knowing exactly how much data to remove.
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: cost**s**.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 5]
```diff
@@ -332,4 +333,26 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
...
+
+        // This means that removing the data bundle on startup is not always sufficient because a test only knows how
+        // to remove its associated data. This is the reason why `StudentHomePageUiTest` would fail if we don't remove the
+        // data bundle in this test.
+        // Extending removeDataBundle to remove data outside its associated data would introduce unnecessary complications
+        // like extra cost and now knowing exactly how much data to remove.
+
+        // Hence, since the account of user being logged in is shared in this test and `StudentHomepageUiTest` we need to
+        // explicitly remove the data bundle in both tests to avoid instability of tests
+        BackDoor.removeDataBundle(testData);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: What problem does removing the data bundle prevent here actually?

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 6]
```diff
@@ -332,4 +333,26 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
...
 
+    @AfterClass
+    public void classTearDown() {
+        // The data associated with the test accounts have to be removed when the test ends because
+        // the test accounts are shared across tests. In particular, the courses of test student1 account is not the same as
+        // `StudentHomePageUiTest` so it has to be cleared before running that test.
+
+        // Test data is never cleared after test in order to save datastore costs as we already remove and restore the data
+        // bundle when the test runs. This raises the question of why we do not remove the data bundle when the class
+        // ends then we do not have to remove it from startup. The reason is that in the case a test fails to tear down
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: Sorry, I think we missed out an important point here.

`The reason is that if a test's data is never accessed in another test, there is no need to clear the test's data to prevent incurring additional datastore costs. Also although unlikely in normal conditions, when a test fails to tear down (fail to remove data bundle), another test should have no reason to fail.`

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 5 above)
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: Yes, removing the databundle at the end of a test is an unnecessary cost. Another reason not to remove associated data after a test is that in case of test failures, it helps to have the associated data in the datastore to debug the failure. If a test case X fails due to data created by another test Y, this is usually a problem of how test case X is designed; it is the responsibility of X to create a clean context for it to succeed. `StudentHomePageUiTest` should use  test user that is not used in any other test so that other tests cannot affect it.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 7]
```diff
@@ -332,4 +333,26 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
...
+        // (fail to remove data bundle), another test should have no reason to fail.
```
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: A general note: code comments should explain the current state of the code. Someone reading this code need not know  that this line is _being added_ at some point; rather, the comment should explain why the line _is_ there as if it was there from the very beginning. The history of how the code came to be like that should be in commit messages and issue/PR discussions.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 8]
```diff
@@ -332,4 +333,26 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
...
+
+        // This means that removing the data bundle on startup is not always sufficient because a test only knows how
+        // to remove its associated data. This is the reason why `StudentHomePageUiTest` would fail if we don't remove the
```
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: I think a test should know how to create a 'clean slate' for itself at the start.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 5 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: There are only 2 actual student accounts we can use so I don't think there's much we can do. Are you suggesting that we can use masqueraded accounts here?

Comment (damithc) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: From what I remember, this test should not use masqueraded accounts as this is one of the few tests that verifies an actual login by a student.
If we do something here due to that constraint, then the explanation should mention the actual constraint. If there is no other option, I suppose even a direct coupling to another test is OK (e.g., delete data created by another test) if the reason is explained clearly(?). 
BTW, I haven't followed this PR closely; my comments may not be applicable to this context :-p

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 6 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: Let's also add the relevant information https://github.com/TEAMMATES/teammates/pull/8875#discussion_r200800204 @damithc mentioned.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 5 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: @tshradheya I suppose we should document that we want to test an actual login here too.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 7 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: @tshradheya I forgot to mention that we should also document this in `removeAndRestoreDataBundle`.

I guess why the explanation here is a little strange because this really belongs there but we need to link it from here too. Maybe it's fine to duplicate the details in both places or you can link it from `removeAndRestoreDataBundle`.

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 8 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: Agreed, so it seems we have a constraint here.

- If it deletes too much data, it may affect other tests.
- If we delete more aggressively then we will probably lose some benefits of saving costs when deleting on startup.
- If we only delete more aggressively in the context of this test, then this test is treated as a special case.

If we expand the part on deleting more aggressively in the context of this test, we can generalize it to only when accounts are actual accounts we delete all their associated data. In that case, I think it's better but it seems like we are adding more magic to behind the scenes which hide the coupling of data.

On the other hand, I currently prefer @tshradheya's approach because it explicitly shows there's a coupling between tests and the data bundle has to be removed elsewhere because of the broken test design.

Although this won't be a problem if the data is not shared as you mentioned. For example, in the context of this test if we don't use shared accounts a test should be able to create a clean slate for itself.

---

Would you prefer instead of another test removing the data bundle that we add additional logic to delete all associated data if the accounts are actual accounts?

Comment (damithc) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: How about we have a `deleteSharedTestData()` method that is called at the start of any test using shared data (i.e., test data related to actual accounts)? We have to ensure that such tests are run sequentially though.

Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: > How about we have a deleteSharedTestData() method that is called at the start of any test using shared data 

Some current tests actually do that. Like if some course is being used with same name in two places, in `processTestData()` there is a `Backdoor.deleteCourse()` but this isnt really ideal cause at times this will give a NullPOinterException cause maybe that course from another test data is not even created yet.

**Comment by tshradheya** [comment]
@LiHaoTan Ready for review

**Comment by tshradheya** [comment]
@LiHaoTan Reminder to review

File: src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java]: Let's revert this?

File: src/test/resources/data/StudentHomePageUiTest.json (hunk 2 above)
[the remark this answers is not in the document]
Comment (LiHaoTan) [reply src/test/resources/data/StudentHomePageUiTest.json]: Let's address this?

File: src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java [hunk 9]
```diff
@@ -196,4 +198,9 @@ private void loginWithPersistenceProblem() {
 
     }
 
+    @AfterClass
+    public void classTearDown() {
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java]: No comments here?

File: src/test/java/teammates/test/driver/BackDoor.java [hunk 10]
```diff
@@ -69,6 +69,32 @@ public static String removeDataBundle(DataBundle dataBundle) {
      * Removes and restores given data into the datastore.
      */
     public static String removeAndRestoreDataBundle(DataBundle dataBundle) {
+
+        // The data associated with the test accounts have to be removed when the test ends because
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/driver/BackDoor.java]: Some of these really don't belong here?

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 11]
```diff
@@ -332,4 +333,12 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
         return loginAdminToPage(profileUrl, StudentProfilePage.class);
     }
 
+    /**
+     * Test data removed due to {@link BackDoor#removeAndRestoreDataBundle(DataBundle)}}.
+     */
+    @AfterClass
+    public void classTearDown() {
+        BackDoor.removeDataBundle(testData);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: We need to explain a little more that because one test can run before another we need to remove both of them.

Also, it might be simpler that we instead place this test in sequential tests. However, it doesn't seem like listeners is working properly in IntelliJ. Does it work for you?

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java (hunk 8 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: I think `deleteSharedTestData()` is something possible to consider (maybe can do some checking) but we don't have to do it in this PR because we would have to address the other tests doing the same thing and we are not be solving some of the related issues. Let's keep this in view for the follow-up issue?

**Comment by tshradheya** [comment]
@LiHaoTan Reminder for review

File: src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java [hunk 12]
```diff
@@ -338,6 +338,14 @@ private StudentProfilePage getProfilePageForStudent(String studentId) {
...
     @AfterClass
     public void classTearDown() {
+        // The courses of test student1 account is not the same as `StudentHomePageUiTest`
+        // so it has to be cleared before running that test. This is the reason why `StudentHomePageUiTest`
+        // would fail if we don't remove the data bundle in this test.
+
+        // Since the account of user being logged in is shared in this test and `StudentHomepageUiTest`,
+        // we need to explicitly remove the data bundle of tests.
+        // The test data needs to be removed for both `StudentHomePageUiTest` and `StudentProfilePageUiTest`
+        // as the tests can run in any order.
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java]: Let's add this line: ``See `BaseTestCaseWithDatastoreAccess#removeAndRestoreDataBundle(DataBundle))` for more details.``

File: src/test/java/teammates/test/driver/BackDoor.java [hunk 13]
```diff
@@ -69,6 +69,29 @@ public static String removeDataBundle(DataBundle dataBundle) {
      * Removes and restores given data into the datastore.
      */
     public static String removeAndRestoreDataBundle(DataBundle dataBundle) {
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/driver/BackDoor.java]: We should use Javadoc, let's change it to something like this:

```Java
/**
 * Removes and restores given data in the datastore. This method is to be called on test startup.
 *
 * <p>Note:  The data associated with the test accounts have to be <strong>manually</strong> removed by removing the data
 * bundle when a test ends because the test accounts are shared across tests.
 *
 * Test data should never be cleared after test in order to prevent incurring additional datastore costs because the
 * test's data may not be accessed in another test. Also although unlikely in normal conditions, when a test fail to
 * remove data bundle on teardown, another test should have no reason to fail.
 *
 * Another reason not to remove associated data after a test is that in case of test failures, it helps to have the
 * associated data in the datastore to debug the failure.
 *
 * This means that removing the data bundle on startup is not always sufficient because a test only knows how
 * to remove its associated data. Extending this method to remove data outside its associated data would introduce
 * unnecessary complications such as extra costs and knowing exactly how much data to remove. Removing too much data
 * would not just incur higher datastore costs but we can make tests unexpectedly pass(fail) when the data is expected to
 * be* not present(present) in another test.
 *
 * Hence, we need to explicitly remove the data bundle in tests on teardown to avoid instability of tests. However,
 * removing the data bundle on teardown manually is not a perfect solution because two tests can concurrently access the
 * same account and their data may get mixed up in the process. This is a major problem we need to address.
 */
```

File: src/test/resources/data/StudentHomePageUiTest.json [hunk 14]
```diff
@@ -190,7 +190,7 @@
   },
   "students": {
     "alice.tmms@SHomeUiT.CS2104": {
-      "googleId": "${value.injected.in.testfile}",
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/resources/data/StudentHomePageUiTest.json]: This and the above change was just reverting the changes that I made previously in this PR which werent needed

File: src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java [hunk 15]
```diff
@@ -29,8 +29,10 @@ protected void prepareTestData() {
         String student1Email = student1GoogleId + "@gmail.com";
         testData.accounts.get("alice.tmms").googleId = student1GoogleId;
         testData.accounts.get("alice.tmms").email = student1Email;
-        testData.students.get("alice.tmms@SHomeUiT.CS2104").googleId = student1GoogleId;
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java]: This  change was just reverting the changes that I made previously in this PR which werent needed

**Comment by tshradheya** [comment]
Ready for Review

File: src/test/java/teammates/test/driver/BackDoor.java [hunk 16]
```diff
@@ -66,32 +66,30 @@ public static String removeDataBundle(DataBundle dataBundle) {
...
+     *
+     * <p>Another reason not to remove associated data after a test is that in case of test failures, it helps to have the
+     * associated data in the datastore to debug the failure.
+     *
+     * <p>This means that removing the data bundle on startup is not always sufficient because a test only knows how
+     * to remove its associated data. This is why some tests would fail when they use the same account and use different data.
+     * Extending this method to remove data outside its associated data would introduce
+     * unnecessary complications such as extra costs and knowing exactly how much data to remove. Removing too much data
+     * would not just incur higher datastore costs but we can make tests unexpectedly pass(fail) when the data is expected to
+     * be* not present(present) in another test.
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/driver/BackDoor.java]: be* -> be

File: src/test/resources/data/StudentHomePageUiTest.json [hunk 17]
```diff
@@ -190,6 +190,7 @@
   },
   "students": {
     "alice.tmms@SHomeUiT.CS2104": {
+      "googleId": "",
```
Comment (LiHaoTan) [inline src/test/resources/data/StudentHomePageUiTest.json]: Just making a note that we should address the inconsistencies in `googleId` for other `.json` files too. Not that important for now I suppose.

File: src/test/java/teammates/test/driver/BackDoor.java [hunk 18]
```diff
@@ -66,7 +66,29 @@ public static String removeDataBundle(DataBundle dataBundle) {
...
+     * to remove its associated data.
+     * This is why some tests would fail when they use the same account and use different data.
+     * Extending this method to remove data outside its associated data would introduce
+     * unnecessary complications such as extra costs and knowing exactly how much data to remove. Removing too much data
+     * would not just incur higher datastore costs but we can make tests unexpectedly pass(fail) when the data is expected to
+     * be not present(present) in another test.
+     *
+     * <p>Hence, we need to explicitly remove the data bundle in tests on teardown to avoid instability of tests. However,
+     * removing the data bundle on teardown manually is not a perfect solution because two tests can concurrently access the
+     * same account and their data may get mixed up in the process. This is a major problem we need to address.
```
Comment (damithc) [inline src/test/java/teammates/test/driver/BackDoor.java]: This is meant to be a note for future, right? Perhaps mention that upfront? Otherwise it looks like a description of the method.

File: src/test/resources/data/StudentHomePageUiTest.json (hunk 17 above)
Comment (xpdavid) [reply src/test/resources/data/StudentHomePageUiTest.json]: I don't think we should add an empty string here.

In doing this, we are saying the googleID of the student is an empty string but not null. This breaks the assumption that students who don't register should not have googleID attribute (may cause "bug" in the future even it is test data). There are differences between null and empty string in the datastore.

Comment (LiHaoTan) [reply src/test/resources/data/StudentHomePageUiTest.json]: I agree with you but due to our broken design of `AccountAttributes` in the first place, we are stuck with this until we change it appropriately.

In fact, an empty string and null are conflated in several locations throughout the TEAMMATES codebase.

The unfortunate thing is we can't write comments in JSON files but an empty string is a more accurate representation of how our codebase initializes students at the current point.

Do you have any suggestions or anything you are particularly against because of this empty string because I think it's rather more accurate at this point (except being inconsistent with all the other test data).

Comment (xpdavid) [reply src/test/resources/data/StudentHomePageUiTest.json]: It's OK. We can leave it there. We already take care of both cases.
https://github.com/TEAMMATES/teammates/blob/c5e80a997c8848977d77d9c695b8751597090739/src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java#L101-L103
