### PR TITLE
[#6519] Add more checkstyle rules

### LINKED ISSUE #6519: Add more checkstyle rules
[Checkstyle](http://checkstyle.sourceforge.net/index.html) is a powerful tool for static analysis. Most of the rules in the [java coding standard](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html) are reflected in the configuration. There are still several rules that can be applied and I want to bring them here for discussion.

For existing checkstyle rule: 

Rules appear in java coding standard (Format : Checkstyle rule name : Summary in the java coding standard)
- `VisibilityModifier` : Class variables should never be declared public
- `FallThrough` : For fall through in `switch` statement, there is a need to write `// fall through` as comment
- `VarableDeclarationUsageDistance` : Variables should be initialized where they are declared and they should be declared in the smallest scope possible. 
- `ImportOrder` : The import statements must follow the package statement. import statements should be sorted with the most fundamental packages first, and grouped with associated packages together and one blank line between groups.
- `JavaDocStyle` : Enforce the java docs style specified in the coding standard
- `CommentsIndentation` : Comments should be indented relative to their position in the code.

Rules that can be considered:
- `MissingOverride` : forcing annotation `@override` for method overriding.
- `DesignForExtension` : if the class is designed for extension, there are several rules to follow.
- `HideUtilityClassConstructor` : enforce private constructor for utility class
- `EqualHashCode` : when `equal` method is there, there must be `hashCode` method
- `IllegalCatch` : to prohibit illegal catch of some exception.
- `IllegalInstantiation` : to prohibit illegal instantiation of class
- `HiddenField` : checks that a local variable or a parameter does not shadow a field that is defined in the same class.
- `MissingSwitchDefault` : force `default:` in switch statement
- `MultipleStringLiterals` : same string literals should be extract to common variable
- `NestedForDepth` : force max depth of nested `for` loop (related to SLAP)
- `NestedIfDepth` : force max depth of nested `if` (related to SLAP)
- `NestedTryDepth` : force max depth of nested `try` statement (related to SLAP)
- `OverloadMethodDeclarationOrder` : The overloading method should be grouped toghther
- `ReturnCount` : Force the number of `return` statement in one method
- `ImportControl` : Force constrain on imported class (e.g. `AccountLogic` should only access `AccountStorage`) 
- `ImportOrder` : The order of import.
- `SummaryJavadoc` : Checks that Javadoc summary sentence does not contain phrases that are not recommended to use.
- `ClassDataAbstractionCoupling` : force the number of instantiations of other classes within the given class. 
- `ClassFanOutComplexity` : force the number of dependency of a class.
- `UniqueProperties` : check the uniqueness of properties in `.properties` files

For none existing checkstyle rule (appear in the coding standard) (could write our own check):
- Naming conversion: boolean variables should be prefixed with `is` .
- Naming conversion: plural form should be used on names representing a collection of objects.
- The missing of `break` in `switch` statement
- Naming conversion: underscores may be used in test method, but not in normal method name (`MethodName`)
- Method length : a method should do only thing and do that well (e.g. the length of one method cannot excess 40 lines)

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6519 for good.

- Removed many technical debts by addressing a large number of CS suppressions.
- Also upgraded PMD to 6.11.0 because it comes with two new good rules: `UseDiamondOperator` and `AvoidReassigningLoopVariables`. Arguably, it is not under CS, but the spirit of the issue is to enforce more code quality checks.

### CODE REVIEW

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 1]
```diff
@@ -256,20 +277,23 @@ public void verifyAccessible(InstructorAttributes instructor, FeedbackSessionAtt
         }
     }
 
-    public void verifyAccessible(InstructorAttributes instructor, FeedbackSessionAttributes feedbacksession,
+    /**
+     * Verifies that the specified instructor can access the specified feedback session.
```
Comment (xpdavid) [inline src/main/java/teammates/logic/api/GateKeeper.java]: `Verifies that the specified instructor has certain privilege for a section in the specified feedback session.`?

File: src/test/java/teammates/test/driver/MockEmailSender.java [hunk 2]
```diff
@@ -17,8 +18,9 @@
     private List<EmailWrapper> sentEmails = new ArrayList<>();
 
     @Override
-    public void sendEmail(EmailWrapper email) {
+    public EmailSendingStatus sendEmail(EmailWrapper email) {
         sentEmails.add(email);
+        return new EmailSendingStatus(200, null);
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/MockEmailSender.java]: `200` -> `HttpStatus.SC_OK`?

**Comment by wkurniawan07** [comment]
@xpdavid Also, the entire storage layer has only 52 missing Javadocs (method + variable + type). You should be able to resolve all of them.
