### PR TITLE
Entities not removed after testing in StudentsDbTest #4646

### LINKED ISSUE #4646: Entities not removed after testing in StudentsDbTest
Individual tests in StudentsDbTest do not clean up after creating entities, and would fail if they were not running in alphabetical order. The order they are run should be explicitly defined and any entities created should be removed after testing.

We should also look into which other tests do the same thing...

### PR DESCRIPTION
**Pull request by jkt001**
Fixes #4646

### CODE REVIEW

File: src/test/java/teammates/test/cases/storage/StudentsDbTest.java [hunk 1]
```diff
@@ -320,6 +327,8 @@ public void testDeleteStudent() throws InvalidParametersException, EntityDoesNot
         
       //Untested case: The deletion is not persisted immediately (i.e. persistence delay) 
       //       Reason: Difficult to reproduce a persistence delay during testing
+        
+        studentsDb.deleteStudent(s.course, s.email);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/storage/StudentsDbTest.java]: Move this to before the comment up there; now it looks like "because there is an untested case, we need to delete something".

**Comment by wkurniawan07** [comment]
One minor comment and it's good to go.

**Comment by jkt001** [comment]
@wkurniawan07 done
