### PR TITLE
Bug: Display of Admin Email subject in logs is not sanitized #6698

### LINKED ISSUE #6698: Bug: Display of Admin Email subject in logs is not sanitized
**Environment**
`master` branch at commit a8eb37e

**Steps to reproduce**

1. Go to Admin page and send an email with tags in the subject.
eg.
image

1. Go to Activity Log Page.
1. Go to Email Log Page.

**Expected behaviour**

1. Activity Log Page should properly display subject of email (ie. after sanitization)
1. Email Log Page should properly display subject of email (ie. after sanitization)

**Actual behaviour**

Tags in subject are rendered.
image
image

### PR DESCRIPTION
**Pull request by leeyimin**
Fixes #6698

**Outline of Solution**

1. Sanitize subject when logging through statusToAdmin
1. Sanitize subject when displaying in emailLogTable.tag

WIP

- [x] Sanitize subject in logs
- [x] Sanitize subject in email logs
- [x] Add test for logging of AdminEmailCompose-related Actions
~~Add test for Admin Email Log Page~~ (to avoid conflict with #6755)

### CODE REVIEW

File: src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+        data = (AdminEmailComposePageData) pageResult.data;
+        assertNotNull(data.emailToEdit);
+
+        ______TS("case: edit non-existing email");
+        String emailId = "nonexistingEmailId";
+        action = getAction(Const.ParamsNames.ADMIN_EMAIL_ID, emailId);
+        pageResult = getShowPageResult(action);
+        assertEquals(Const.ViewURIs.ADMIN_EMAIL + "?error=true&user=admin.user",
+                pageResult.getDestinationWithParams());
```
Comment (samsontmr) [inline src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java]: Break line at highest level possible.
```
assertEquals(
        Const.ViewURIs.ADMIN_EMAIL + "?error=true&user=admin.user", pageResult.getDestinationWithParams());
```

**Comment by wkurniawan07** [comment]
@leeyimin let's not forget to continue on this? 😛

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+        data = (AdminEmailComposePageData) pageResult.data;
+        assertEquals(subject, data.emailToEdit.subject);
+        assertEquals(email.emailId, data.emailToEdit.emailId);
+
+        ______TS("case: save non-existing email success");
+        String emailId = "nonExisitingId";
+        content = "valid content";
+        subject = "valid subject <b>To check sanitization</b>";
+        receiver = "test@example.tmt";
+        action = getAction(Const.ParamsNames.ADMIN_EMAIL_CONTENT, content,
```
Comment (samsontmr) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: Consider moving `Const.ParamsNames.ADMIN_EMAIL_CONTENT, content,` to the line below (in line with the other parameters).

File: src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    }
+
+    @Override
+    @Test
+    public void testExecuteAndPostProcess() throws Exception {
+
+        final String adminUserId = "admin.user";
+        gaeSimulation.loginAsAdmin(adminUserId);
+
+        ______TS("case: compose new email");
```
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java]: It seems `case:` doesn't add value. Perhaps you can use a format such as `scenario : expected behavior` instead?

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java [hunk 4]
```diff
@@ -0,0 +1,240 @@
...
+        content = "";
+        subject = "valid subject";
+        receiver = "test@example.tmt";
+        action = getAction(
+                Const.ParamsNames.ADMIN_EMAIL_CONTENT, content,
+                Const.ParamsNames.ADMIN_EMAIL_SUBJECT, subject,
+                Const.ParamsNames.ADMIN_EMAIL_ADDRESS_RECEIVERS, receiver);
+        pageResult = getShowPageResult(action);
+        assertEquals(
+                Const.ViewURIs.ADMIN_EMAIL + "?error=true&user=admin.user", pageResult.getDestinationWithParams());
```
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: These few lines seem to be repeated a few times. Can extract as a util method?

File: src/main/java/teammates/logic/backdoor/BackDoorLogic.java [hunk 5]
```diff
@@ -427,6 +435,9 @@ public void removeDataBundle(DataBundle dataBundle) {
             }
         }
         accountsDb.deleteAccounts(dataBundle.accounts.values());
+
+        // Delete all admin emails
```
Comment (damithc) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: start with lower case letter, for consistency?

File: src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java (hunk 3 above)
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminEmailComposePageActionTest.java]: Or we can use the same `sut : scenario : expected behavior` format we use for test case method names.

e.g. `compose new email : typical values given : succeeds`

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java (hunk 4 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: I'll answer. This routine is repeated in ALL action tests.

File: src/main/java/teammates/logic/backdoor/BackDoorLogic.java (hunk 5 above)
Comment (wkurniawan07) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: Isn't our standard for comments to start with an upper case?

[Not explicitly stated here](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html) but all the examples suggest so.

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java (hunk 4 above)
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: Is there a better way? If there is, let's start here and slowly propagate back to existing tests (FirstTimer issues?)

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: With all due respect, "slowly propagating" is a very good reason for inconsistency to occur in a code base. Wholesale change (i.e. a refactoring just to change this and only this) is a better way.

And also, I know of at least two other routines in the action test that are repeated everywhere.

File: src/main/java/teammates/logic/backdoor/BackDoorLogic.java (hunk 5 above)
Comment (damithc) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: I suggested lower case because there's another comment in this commit that starts with a lower case. Yes, seems our coding standard uses upper case. So can keep this as it is.
I checked [Google coding standard](https://google.github.io/styleguide/javaguide.html#s7-javadoc) and even they are not consistent 😛 
Always starting with an upper case letter seems like an easier rule to follow (as opposed to `lower case for phrases, upper case for sentences`)

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java (hunk 4 above)
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: Agree. If it is can be done in one shot, sure.

File: src/main/java/teammates/logic/backdoor/BackDoorLogic.java (hunk 5 above)
Comment (leeyimin) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: Comments on lines 427, 428 in the same method start with an upper case, so I simply followed for this line.

File: src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java (hunk 4 above)
Comment (leeyimin) [inline src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java]: Added as a new issue #6909

**Comment by leeyimin** [comment]
@damithc is this merge approved?

**Comment by damithc** [comment]
> @damithc is this merge approved?

Yes. Sorry, forgot to update the label.

**Comment by leeyimin** [comment]
@damithc I'll assume this is merge approved again?

**Comment by damithc** [comment]
> @damithc I'll assume this is merge approved again?

Yes @leeyimin

File: src/main/java/teammates/logic/backdoor/BackDoorLogic.java [hunk 6]
```diff
@@ -430,6 +438,9 @@ public void removeDataBundle(DataBundle dataBundle) {
...
+        adminEmailsDb.deleteEntities(adminEmailsDb.getAllAdminEmails());
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: @leeyimin I just realized what this line entails. If run on an actual server, this will effectively wipe out all admin emails?

I may be wrong, but perhaps you're thinking of:
```java
adminEmailsDb.deleteEntities(dataBundle.adminEmails.values());
```

Comment (leeyimin) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: Sorry! I forgot that the tests are also ran on the server. Should the commit be reverted?

Comment (wkurniawan07) [inline src/main/java/teammates/logic/backdoor/BackDoorLogic.java]: There's no need to. Just fix this line.
