### PR TITLE
[#10058] Fix inconsistent exception thrown in BasicFeedbackSubmissionAction#checkAccessControl*

### LINKED ISSUE #10058: Inconsistent exception between checkAccessControlForStudentFeedbackSubmission and checkAccessControlForInstructorFeedbackSubmission
`BasicFeedbackSubmissionAction#checkAccessControlForStudentFeedbackSubmission` throws `EntityNotFoundException` when the provided `student` is null. However, `BasicFeedbackSubmissionAction#checkAccessControlForInstructorFeedbackSubmission` throws `UnauthorizedAccessException` when the provided `instructor` is null, even though their behavior is expected to be similar.

I feel that changing `BasicFeedbackSubmissionAction#checkAccessControlForStudentFeedbackSubmission` to throw `UnauthorizedAccessException` would make it more consistent, and make more sense.

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10058

**Outline of Solution**
Change null check in `BasicFeedbackSubmissionAction#checkAccessControlForStudentFeedbackSubmission` to throw `UnauthorizedAccessException` instead of `EntityNotFoundException`

### CODE REVIEW

**Comment by madanalogy** [comment]
You need to run `./gradlew lint` (or your OS equivalent) to lint your java files and ensure they adhere to our checkstyle :)

**Comment by ccyccyccy** [comment]
> You need to run `./gradlew lint` (or your OS equivalent) to lint your java files and ensure they adhere to our checkstyle :)

Okay done :)

File: src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java [hunk 1]
```diff
@@ -67,10 +65,6 @@ protected StudentAttributes getStudentOfCourseFromRequest(String courseId) {
      */
     protected void checkAccessControlForStudentFeedbackSubmission(
             StudentAttributes student, FeedbackSessionAttributes feedbackSession) {
-        if (student == null) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java:70]: If we remove the null check, will it results in NPE? (Line 74)

Comment (ccyccyccy) [reply src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java:70]: I believe so. Now I see why there is a need for the null check to be there.

In that case, I will change the exception thrown by the null check to be `UnauthorizedAccessException` instead of `EntityNotFoundException`
