### PR TITLE
[#10110] Updated CommentOutput to hide commentGiverName in JSON

### LINKED ISSUE #10110: Hide certain fields in CommentOutput for participant comments
- **Environment**: master

**Steps to reproduce**
- Set a MCQ/MSQ question to only show responses.
image
- Fill in dummy responses **with participant comment** as a student **using a different account**.
(The above steps can be also replaced with: Setting an everyone-can-view question -> moderate responses (submit dummy responses **with participant comment**) -> Setting the question back to anonymous question)
image
- Go to result page

**Expected behaviour**

The JSON data returned from the backend shall not expose giver name

**Actual behaviour**

The JSON data returned from the backend exposes the giver name in participant comment.
```json
{
          "responseId": "aglub19hcHBfaWRyHQsSEEZlZWRiYWNrUXVlc3Rpb24YgICAgICAyAoM%benny.c.tmms@gmail.tmt%benny.c.tmms@gmail.tmt",
          "giver": "Anonymous student 1086443366",
          "relatedGiverEmail": "Anonymous student 1086443366@@Anonymous student 1086443366.com",
          "giverTeam": "Anonymous student 1086443366's Team",
          "giverSection": "Tutorial Group 1",
          "recipient": "Anonymous student 1086443366",
          "recipientTeam": "Anonymous student 1086443366's Team",
          "recipientSection": "None",
          "responseDetails": {
            "answer": "<p>b</p>",
            "isOther": false,
            "otherFieldContent": "",
            "questionType": "MCQ"
          },
          "participantComment": {
            "commentGiverName": "Benny Charles",
            "lastEditorName": "Benny Charles",
            "feedbackResponseCommentId": 4679521487814656,
            "commentText": "<p>abc</p>",
            "commentGiver": "benny.c.tmms@gmail.tmt",
            "createdAt": 1590361609611,
            "lastEditorEmail": "benny.c.tmms@gmail.tmt",
            "lastEditedAt": 1590361609611,
            "isVisibilityFollowingFeedbackQuestion": true,
            "showGiverNameTo": [],
            "showCommentTo": []
          },
          "instructorComments": []
        },
```

**Additional info**
Hint:
- We should hide this fields (by setting them to `null`) in the API layers. It is OK to do this as the frontend is not supposed to use the fields. If it get used, we will also get bugs/errors which are good indicators of wrong logic.
- You can do this easily by modifying `CommentOutput`.

### PR DESCRIPTION
**Pull request by Derek-Hardy**
Fixes #10110 

**Outline of Solution**
In the constructor of CommentOutput class, we hide the attributes: `commentGiver`, `commentGiverName`, `lastEditorEmail`, `lastEditorName` for participantComment.

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/output/SessionResultsData.java [hunk 1]
```diff
@@ -352,7 +352,10 @@ public CommentOutput getParticipantComment() {
 
         public CommentOutput(FeedbackResponseCommentAttributes frc, String commentGiverName, String lastEditorName) {
             super(frc);
-            this.commentGiverName = commentGiverName;
+
+            // If response is anonymous to everyone, then comment giver's name is also hidden.
+            this.commentGiverName = (frc.showGiverNameTo.isEmpty()) ? null : commentGiverName;
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/output/SessionResultsData.java:357]: There are multiple things here:
- You should hide not only the giver name but also the `giver` itself.
- You should also hide lastEditorName and lastEditor
- We only want to do so for `participantComment`. I think you can just blindly hiding the field without looking at the visibility for participant comment as the fields should not be used in the frontend.
- If you want to follow the visibility, it should be the comment visibility not the response visibility.

 Maybe create a method here and call it when `participantComment` get constructed?

**Comment by Derek-Hardy** [comment]
**Update**:

- current PR kept all checks within `CommentOutput` class. 
- `commentGiver` and `lastEditorEmail` access modifier are changed to `protected` in `FeedbackResponseCommentData` class for access in sub-class (CommentOutput)

**Look for suggestion**:
- we can probably pass in null for participant comment in `buildComments` method in `SessionResultsData` class, so as to remove `commentGiverName` and `lastEditorName` from if-else in `CommentOutput` constructor?

File: src/main/java/teammates/ui/webapi/output/SessionResultsData.java (hunk 1 above)
Comment (Derek-Hardy) [reply src/main/java/teammates/ui/webapi/output/SessionResultsData.java]: Updated to hide `commentGiver`, `commentGiverName`, `lastEditorEmail`, `lastEditorName` for participantComment.
