### PR TITLE
Instructor: Session Results: Comment box shrinks when canceling and adding comment again #8723

### LINKED ISSUE #8723: Instructor: Session Results: Comment box shrinks when canceling and adding comment again
In the session result page, the comment box for a response shrinks to a much smaller size when canceling and clicking on `Add comment` button again.

- **Environment**: 
`master` branch

**Steps to reproduce:**
1. Login as Instructor
2. In the session table, click on `Results` to view the results of a session which has existing responses.
3. Click on `Add comment`, and close the modal window
4. Click on `Add comment` again
**Or,**
3. Change view to a view which allows comments. (e.g. ` Group by - Recipient > Giver > Question
`)
4. Click the comment button for a response and then click `cancel`
5. click on comment button again.

**Expected behaviour:** The comment box should maintain a consistent look.

**Actual behaviour:** Comment box shrinks to a much smaller size. Though when we start typing the comment, it returns to its normal size, but it does not look visually appealing.

**Screenshot:**
screenshot 469

**Additional info:**

This issue also surfaced a while back in https://github.com/TEAMMATES/teammates/pull/7817#pullrequestreview-51644096 but apparently got overlooked.

### PR DESCRIPTION
**Pull request by nashmia-riaz**
Fixes #8723 

**Outline of Solution**
A `<br >` tag is added to the input box. This gets removed when the comment box is hidden and viewed again. Commenting out that line of code fixes this for now but have I have to test.

### CODE REVIEW

**Comment by nashmia-riaz** [comment]
This is ready for review from my side

File: src/main/webapp/dev/js/common/feedbackResponseComments.js [hunk 1]
```diff
@@ -169,7 +169,7 @@ function showResponseCommentAddForm(recipientIndex, giverIndex, qnIndex, section
     }
     $(`#showResponseCommentAddForm${id}`).show();
 
-    $(`#responseCommentAddForm${id}`).empty();
+    $(`#responseCommentAddForm${id}`).html('<br data-mc-bogus="1">');
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/common/feedbackResponseComments.js]: Maybe something like this: ``tinymce.get(`#responseCommentAddForm${id}`).setContent('');``?

**Comment by LiHaoTan** [comment]
@nashmia-riaz In case you aren't aware, one of the tests are failing because the code isn't working correctly (the tinyMCE editor is not yet initialized).

**Comment by nashmia-riaz** [comment]
@LiHaoTan Apologies for the delay and thanks for pointing out my mistake. This is ready for review.

File: src/main/webapp/dev/js/common/feedbackResponseComments.js [hunk 2]
```diff
@@ -169,8 +169,6 @@ function showResponseCommentAddForm(recipientIndex, giverIndex, qnIndex, section
     }
     $(`#showResponseCommentAddForm${id}`).show();
 
-    $(`#responseCommentAddForm${id}`).empty();
-
     if (typeof richTextEditorBuilder !== 'undefined') {
         /* eslint-disable camelcase */ // The property names are determined by external library (tinymce)
         richTextEditorBuilder.initEditor(`#responseCommentAddForm${id}`, {
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/common/feedbackResponseComments.js]: So a possible solution is mentioned below, there is some changes in behavior but I doubt it will break anything 
 though we can't be sure without comprehensively tracing the usage. In any case, we do have tests and this is not going to cause a major problem if it breaks. Let's clean the code up.

```Javascript
const responseCommentAddFormId = `responseCommentAddForm${id}`;
const responseCommentEditor = tinymce.get(responseCommentAddFormId);
if (responseCommentEditor === null) {
    richTextEditorBuilder.initEditor(responseCommentAddFormId, {
        inline: true,
    });
} else {
    responseCommentEditor.setContent('');
}
```

**Comment by nashmia-riaz** [comment]
@LiHaoTan the reason I removed consts was because `InstructorFeedbackResultsPageUiTest.testBackEndActions ` fails as the comment box is not properly initialized. I think the reason though for this is that `richTextEditorBuilder.initEditor` requires that I pass it the string `responseCommentAddForm${id}` (it doesn't recognize the const for some reason). My proposed solution for this is:
```
const responseCommentEditor = tinymce.get(`responseCommentAddForm${id}`);
    if (responseCommentEditor === null) {
        /* eslint-disable camelcase */ // The property names are determined by external library (tinymce)
        richTextEditorBuilder.initEditor(`responseCommentAddForm${id}`, {
            inline: true,
        });
        /* eslint-enable camelcase */
    } else {
        responseCommentEditor.setContent('');
    }
```

I've tested this and it works. Please let me know if I should go with this.

File: src/main/webapp/dev/js/common/feedbackResponseComments.js [hunk 3]
```diff
@@ -169,14 +169,16 @@ function showResponseCommentAddForm(recipientIndex, giverIndex, qnIndex, section
     }
     $(`#showResponseCommentAddForm${id}`).show();
 
-    $(`#responseCommentAddForm${id}`).empty();
-
-    if (typeof richTextEditorBuilder !== 'undefined') {
+    const responseCommentAddFormId = `responseCommentAddForm${id}`;
+    const responseCommentEditor = tinymce.get(responseCommentAddFormId);
+    if (responseCommentEditor === null) {
         /* eslint-disable camelcase */ // The property names are determined by external library (tinymce)
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/common/feedbackResponseComments.js]: Is this necessary?

**Comment by nashmia-riaz** [comment]
@LiHaoTan Thank you for pointing that out. I didn't realize that the eslint commands serve no purpose because I saw them being used elsewhere in the code as well.
This is ready for review. :)
