### PR TITLE
AdminEmailComposeSendAction has no log message on success #6699

### LINKED ISSUE #6699: Bug: AdminEmailComposeSendAction has no log message on success
**Environment**
 `master` branch at commit a8eb37e

**Steps to reproduce**
1. Go to Admin Page and send an email
1. Go to Activity Log Page.

**Expected behaviour**
Activity Log should display information of the email send action.

**Actual behaviour**

image

### PR DESCRIPTION
**Pull request by Mynk96**
Fixes #6699 

**Outline of Solution**

Displays a message, after successfully sending the email in the page and also logs the info
as "Email sent to receiver" in activityLog page.

### CODE REVIEW

**Comment by Mynk96** [comment]
Ready for review

**Comment by Mynk96** [comment]
ready for review

File: .gitignore [hunk 1]
```diff
@@ -48,3 +48,5 @@ gradle-app.setting
 .idea/
 *.iml
 out/
+/bin/
+
```
Comment (Neurrone) [inline .gitignore]: Why the change to .gitignore?

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 2]
```diff
@@ -98,6 +98,16 @@ protected ActionResult execute() {
...
+            if (addressModeOn) {
+                statusToAdmin = "Email sent to " + addressReceiverListString;
+                statusToUser.add(new StatusMessage("Email sent to "
+                        + addressReceiverListString, StatusMessageColor.SUCCESS));
+            }
+            if (groupModeOn) {
+                statusToAdmin = "Email sent to " + groupReceiverListFileKey;
+                statusToUser.add(new StatusMessage("Email sent to " + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
+            }
         }
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Would be good to add tests to verify this behaviour.

File: .gitignore (hunk 1 above)
Comment (Mynk96) [inline .gitignore]: I didn't get why it was added, but when I'm removing it the build is getting failed.Any suggestions how to fix that?

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 2 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Added a test in AdminEmailPageUiTest o test this behaviour.

File: .gitignore (hunk 1 above)
Comment (whipermr5) [inline .gitignore]: The build failed due to a temporary network error - I've helped you restart it. You can check the build log to see the cause of failure; it isn't always your fault haha :)

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 3]
```diff
@@ -98,6 +98,16 @@ protected ActionResult execute() {
                                                         new Text(emailContent),
                                                         null);
             data.emailToEdit.emailId = emailId;
+        } else {
+            if (addressModeOn) {
+                statusToAdmin = "Email sent to " + addressReceiverListString;
+                statusToUser.add(new StatusMessage("Email sent to "
+                        + addressReceiverListString, StatusMessageColor.SUCCESS));
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Reuse the statusToAdmin variable, or create an intermediate one to hold the message? Since these 2 lines use an identical message

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 4]
```diff
@@ -98,6 +98,16 @@ protected ActionResult execute() {
...
+            }
+            if (groupModeOn) {
+                statusToAdmin = "Email sent to " + groupReceiverListFileKey;
+                statusToUser.add(new StatusMessage("Email sent to " + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Similarly

File: src/test/java/teammates/test/pageobjects/AdminEmailPage.java [hunk 5]
```diff
@@ -17,6 +17,7 @@ protected boolean containsExpectedPageContents() {
 
     public void inputRecipient(String recipient) {
         WebElement recipientBox = this.getRecipientBox();
+        recipientBox.clear();
```
Comment (Neurrone) [inline src/test/java/teammates/test/pageobjects/AdminEmailPage.java]: Why is this needed?

Comment (Mynk96) [inline src/test/java/teammates/test/pageobjects/AdminEmailPage.java]: ` emailPage.inputRecipient("recipient@email.tmt");` 
because the statement appends to the previous input in the field (`emailPage.inputRecipient("recipient");`) and the input becomes 'recipientrecipient@email.tmt'

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 3 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: `statusToUser.add(new StatusMessage(statusToAdmin, StatusMessageColor.SUCCESS));`
will this be fine?

Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Sorry, best to leave it best way. Looking more closely, the surrounding code in that file also does it this way; I think its to avoid problems caused by the statusToAdmin variable changing further down in the code, therefore causing the status message to change, since it doesn't do a deep copy of the string during construction.

File: src/test/java/teammates/test/pageobjects/AdminEmailPage.java (hunk 5 above)
Comment (Neurrone) [inline src/test/java/teammates/test/pageobjects/AdminEmailPage.java]: Understood. Recommend creating a new method for doing this, like the `clearSubjectBox()` method. The input* methods all do not clear their element, so changing this one to clear current input causes surprising behaviour.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 3 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Okay @Neurrone.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 6]
```diff
@@ -98,6 +98,16 @@ protected ActionResult execute() {
...
+            }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Are the two branches mutually exclusive? i.e. should they be `if-else`?

Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: yes they are mutually exclusive. I am pushing the required changes.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 7]
```diff
@@ -98,6 +98,15 @@ protected ActionResult execute() {
...
             data.emailToEdit.emailId = emailId;
+        } else {
+            if (addressModeOn) {
+                statusToAdmin = "Email sent to " + addressReceiverListString;
+                statusToUser.add(new StatusMessage("Email sent to "
+                        + addressReceiverListString, StatusMessageColor.SUCCESS));
+            } else {
+                statusToAdmin = "Email sent to " + groupReceiverListFileKey;
+                statusToUser.add(new StatusMessage("Email sent to " + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
+            }
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @damithc pretty sure one of each mode can be on, or both at the same time. Will get confirmation from someone more familiar with this system.

@Mynk96 will check on whether both can be on at the same time. If they can't be, there is a logic error now, since that else block gets executed regardless of whether group mode is on or not.

Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid is going to look after the admin side of things. May be he can weigh in here?

Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @Neurrone how about this?
`if (addressModeOn && groupModeOn) {
                statusToAdmin = "Email sent to " + addressReceiverListString + "," + groupReceiverListFileKey;
                statusToUser.add(new StatusMessage("Email sent to "
                        + addressReceiverListString + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
            } else if (addressModeOn) {
                statusToAdmin = "Email sent to " + addressReceiverListString;
                statusToUser.add(new StatusMessage("Email sent to " + addressReceiverListString,
                        StatusMessageColor.SUCCESS));
            } else {
                statusToAdmin = "Email sent to " + groupReceiverListFileKey;
                statusToUser.add(new StatusMessage("Email sent to " + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
            }`
takes care of all the three cases.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 8]
```diff
@@ -98,6 +98,15 @@ protected ActionResult execute() {
                                                         new Text(emailContent),
                                                         null);
             data.emailToEdit.emailId = emailId;
+        } else {
+            if (addressModeOn) {
+                statusToAdmin = "Email sent to " + addressReceiverListString;
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Technically, this is not the place where the email is sent as it just sends the job to the email sending queue.
The log message is not correct.
I would suggest to put the log message things inside `recordNewSentEmail` rather than having multiple if else to see whether it is `addressMode` or `groupMode`.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 9]
```diff
@@ -98,6 +98,15 @@ protected ActionResult execute() {
...
+                statusToUser.add(new StatusMessage("Email sent to "
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: The email is not sent instantly. Should say something like the email will be sent within an hour.

Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: `Email queued:`?

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 8 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid Got it!

**Comment by Mynk96** [comment]
The last commit works for all the cases and generates the corresponding log messages

**Comment by Mynk96** [comment]
The last commit had problem with the output i.e. it was printing ", " even when there was only one of the  Receipient (addressReceiverListString or groupReceiverListString) ,so to avoid that, I had to stick with the previous approach.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 10]
```diff
@@ -153,6 +153,23 @@ private void recordNewSentEmail(String subject,
...
         moveJobToAddressModeTaskQueue();
+
+        if (addressModeOn && groupModeOn) {
+            statusToAdmin = "Email will be sent within an hour to "
+                            + addressReceiverListString + "," + groupReceiverListFileKey;
+            statusToUser.add(new StatusMessage("Email will be sent within an hour to "
+                    + addressReceiverListString + ", " + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
+
+        } else if (addressModeOn) {
+            statusToAdmin = "Email wll be sent within an hour to " + addressReceiverListString;
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: wll -> will

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 11]
```diff
@@ -153,6 +153,23 @@ private void recordNewSentEmail(String subject,
 
         moveJobToGroupModeTaskQueue();
         moveJobToAddressModeTaskQueue();
+
+        if (addressModeOn && groupModeOn) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]:
``` java
    private void moveJobToGroupModeTaskQueue() {
        if (!groupModeOn) {
            return;
        }
        taskQueuer.scheduleAdminEmailPreparationInGroupMode(emailId, groupReceiverListFileKey, 0, 0);
    }

    private void moveJobToAddressModeTaskQueue() {
        if (!addressModeOn) {
            return;
        }
        taskQueuer.scheduleAdminEmailPreparationInAddressMode(emailId, addressReceiverListString);
    }
```
Here, you actually get the `if-else` for free

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 12]
```diff
@@ -153,6 +153,23 @@ private void recordNewSentEmail(String subject,
...
+            statusToAdmin = "Email will be sent within an hour to "
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: `statusToAdmin` will be the log message. Log message is for us to debug when something bad happens. Thus, we need to put something useful like `Email Queued: ...` (So we could know the email is queued.)

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 13]
```diff
@@ -153,6 +153,23 @@ private void recordNewSentEmail(String subject,
...
+
+        } else if (addressModeOn) {
+            statusToAdmin = "Email wll be sent within an hour to " + addressReceiverListString;
+            statusToUser.add(new StatusMessage("Email will be sent within an hour to " + addressReceiverListString,
+                         StatusMessageColor.SUCCESS));
+
+        } else {
+            statusToAdmin = "Email will be sent within an hour to " + groupReceiverListFileKey;
+            statusToUser.add(new StatusMessage("Email will be sent within an hour to "
+                        + groupReceiverListFileKey, StatusMessageColor.SUCCESS));
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Like earlier, this code gets triggered if group mode is not on, or if address mode isn't on. Why not something like this instead?

```java
if (addressModeOn) {
    // Set appropriate admin and add a status message
}

if (groupModeOn) {
    // append message to statusToAdmin variable, and add another status message
}
```

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 14]
```diff
@@ -153,6 +153,23 @@ private void recordNewSentEmail(String subject,
 
         moveJobToGroupModeTaskQueue();
         moveJobToAddressModeTaskQueue();
+
+        if (addressModeOn && groupModeOn) {
+            statusToAdmin = "Email will be sent within an hour to "
+                            + addressReceiverListString + "," + groupReceiverListFileKey;
+            statusToUser.add(new StatusMessage("Email will be sent within an hour to "
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: I suggest to put the `statusToUser` thing in the `execute` method. It is not `recordNewSentEmail`'s responsibility to notify the user. Also, you can use ternary operator `? ... : ...` to get rid of `if-else` branch as your `if-else` branch is almost the same.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 13 above)
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @Mynk96 Also, in `moveJobToGroupModeTaskQueue` and `moveJobToAddressModeTaskQueue`, you get the `if-else` for free

File: src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java [hunk 15]
```diff
@@ -59,6 +59,7 @@ private void testCompose() throws Exception {
 
         ______TS("send email - no subject");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java]: We could create an issue for this. Maybe you could help us.
There is no test case for sending email using `groupMode`.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 16]
```diff
@@ -100,6 +100,16 @@ protected ActionResult execute() {
             data.emailToEdit.emailId = emailId;
         }
 
+        if (addressModeOn && groupModeOn) {
+            statusToAdmin = "Email queued for sending." + "<br/>" + "Receipient: " + addressReceiverListString
+                            + "<br/>" + "Group receiver's list " + groupReceiverListFileKey;
+            statusToUser.clear();
+
+            statusToUser.add(new StatusMessage("Email will be sent within an hour to "
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Actually, I am ok with showing two status messages (one for groupMode, one for addressMode) @Neurrone What do you think?

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 17]
```diff
@@ -100,6 +100,16 @@ protected ActionResult execute() {
             data.emailToEdit.emailId = emailId;
         }
 
+        if (addressModeOn && groupModeOn) {
+            statusToAdmin = "Email queued for sending." + "<br/>" + "Receipient: " + addressReceiverListString
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Maybe before the `moveJobToGroupModeTaskQueue ` and `moveJobToAddressModeTaskQueue `, we initialise `statusToAdmin` as `"Email queued:"` first. And then, in `moveJobToAddressModeTaskQueue`, we use `statusToAdmin += "Receipient: " ...`

Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid I did think of doing this way, but then statusToAdmin will have "Email queued: " when group mode and address mode both are not on, as said by @Neurrone in the previous review, this may create confusion for admin as the log will only have "Email queued:" without any recipient.

Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Also, I have made a small mistake, will correct that after this review (Receipient -> Recipient)

File: src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java (hunk 15 above)
Comment (Mynk96) [inline src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java]: @xpdavid have already started working on it, just waiting for the issue to be created.
There is a small typo in AdminEmailComposeSendAction.java which needs to be corrected i.e reciver->receiver, should  I correct that in this pr only or create a new issue for that?

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 17 above)
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Take a look at https://github.com/TEAMMATES/teammates/pull/7051/files#diff-fced2f82a76e423b56927175d900ca9aR70. 
"..group mode and address mode both are not on.." won't happen.

File: src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java (hunk 15 above)
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java]: Go ahead and create the issues.
These works should be done in a separated PR.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 17 above)
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Thanks @xpdavid. Was more concerned about the logic errors in if-else, moving it into those functions is a nice way of avoiding all that.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 16 above)
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid agreed, sounds like a good idea. On a sidenote, what do you think about having statusToAdmin changed from a String into an ArrayList<String>? Since in some methods like this once, multiple statuses to admin needs to be sent.

Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Exactly. There is an `//TODO` in `Action.class` talking about this, but this is not a trivial work :P

Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Good point. I can open this as a new contributor issue (if it doesn't already exist), maybe someone would be willing to help.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 17 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid Got it, will change accordingly.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java (hunk 16 above)
Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid @Neurrone Then should I make the changes, so that it shows two messages to the user.
Just a suggestion showing only one message feels to me like a more mature UI
emaill
email-2

Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: Let's wait @damithc inputs :)

Comment (Mynk96) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @xpdavid status?

Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: @damithc Wait for your inputs :)

**Comment by Mynk96** [comment]
@xpdavid ready for review

**Comment by Mynk96** [comment]
@xpdavid yes created the issue and working on it.

File: src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java [hunk 18]
```diff
@@ -145,7 +135,7 @@ private void moveJobToAddressModeTaskQueue() {
         }
         taskQueuer.scheduleAdminEmailPreparationInAddressMode(emailId, addressReceiverListString);
 
-        statusToAdmin = "Email queued for sending." + "<br/>" + "Receipient: " + addressReceiverListString;
+        statusToAdmin += "<br/>" + "Receipient: " + addressReceiverListString;
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: * Receipient -> recipient?
* Might not be safe to do a +=. @xpddavid correct me if I'm wrong, but don't think statusToAdmin is default initialized with an empty String in Action; its just declared as String statusToAdmin without being initialized before Action.execute()

Comment (xpdavid) [inline src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java]: The `statusToAdmin` is initialised to `Email queued for sending.` in this case (by default, it is not). Good catch to the typo. :P
