### PR TITLE
[#10691] Weighted rubric question missing statistics 

### LINKED ISSUE #10691: Weighted rubric question missing statistics
- **Environment**: `master` branch at commit cddee18d57a428181b245bbd703cd0e6b9bb44e3

**Steps to reproduce**
1) Create rubric question with weights
2) Submit some responses
3) Per recipient statistics in student result page only shows data for current student as recipient.

V6 statistics:
weighted-rubric

V7 statistics:
weighted-rubric-v7

### PR DESCRIPTION
**Pull request by jtankw3**
Fixes #10691

**PR Checklist**

**Outline of Solution**
- fill up `allResponses` field in `SessionResultsData` for students as well
- add team info for all responses instead of only when student is the giver and/or recipient 
- use `allResponses` instead of `responsesToSelf` for calculating statistics. This makes it more flexible as we can choose which responses to filter.
- filter responses for previous statistics that used `responsesToSelf` 

Screenshot:
fixed-statistics

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/output/SessionResultsData.java [hunk 1]
```diff
@@ -144,15 +147,14 @@ private static ResponseOutput buildSingleResponseForStudent(
...
+            recipientTeam = bundle.getRoster().getInfoForIdentifier(response.getRecipient()).getTeamName();
         }
 
         // process comments
         List<FeedbackResponseCommentAttributes> feedbackResponseComments =
                 bundle.getResponseCommentsMap().getOrDefault(response.getId(), Collections.emptyList());
         Queue<CommentOutput> comments = buildComments(feedbackResponseComments, bundle);
 
-        // Student does not need to know the teams for giver and/or recipient
-        // unless the student him/herself is the giver and/or recipient
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/output/SessionResultsData.java:155]: This might need some reviews as it might leak information

File: src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.ts [hunk 2]
```diff
@@ -48,6 +48,9 @@ export class NumScaleQuestionStatisticsComponent extends NumScaleQuestionStatist
     this.rowsData = [];
     for (const team of Object.keys(this.teamToRecipientToScores)) {
       for (const recipient of Object.keys(this.teamToRecipientToScores[team])) {
+        if (this.isStudent && recipient !== 'You') {
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.ts:51]: I don't think the filtering should happen here as the statistics component's responsibility is just display stats based on provided responses. It essentially should not do the filtering.

File: src/web/app/pages-session/session-result-page/session-result-page.component.html [hunk 3]
```diff
@@ -41,7 +41,7 @@ <h1>
       <div class="card-body">
         <tm-question-text-with-info [questionNumber]="question.feedbackQuestion.questionNumber" [questionDetails]="question.feedbackQuestion.questionDetails" class="question-text"></tm-question-text-with-info>
         <tm-single-statistics [question]="question.feedbackQuestion.questionDetails"
-                              [responses]="question.responsesToSelf"
+                              [responses]="question.allResponses"
```
Comment (xpdavid) [inline src/web/app/pages-session/session-result-page/session-result-page.component.html:44]: At least the filtering should happen here.

File: src/main/java/teammates/ui/webapi/output/SessionResultsData.java (hunk 1 above)
Comment (jtankw3) [reply src/main/java/teammates/ui/webapi/output/SessionResultsData.java]: Added a check that the recipient is not anonymous before adding the team name. Thus, there should not be any leaks as if the recipient is not anonymous there should not be any problem with knowing his team.

File: src/web/app/pages-session/session-result-page/session-result-page.component.html (hunk 3 above)
Comment (jtankw3) [reply src/web/app/pages-session/session-result-page/session-result-page.component.html:50]: Shifted the filtering into single-statistics

**Review by xpdavid — APPROVED** [review]
Just have one business logic related question.

File: src/main/java/teammates/ui/output/SessionResultsData.java [hunk 4]
```diff
@@ -144,15 +146,16 @@ private static ResponseOutput buildSingleResponseForStudent(
         } else {
             // we don't want student to figure out who is who by using the hash
             recipientName = removeAnonymousHash(getRecipientNameOfResponse(response, bundle).getName());
+            if (!recipientName.contains(Const.DISPLAYED_NAME_FOR_ANONYMOUS_PARTICIPANT)) {
```
[the remark this answers is not in the document]
Comment (damithc) [reply src/main/java/teammates/ui/output/SessionResultsData.java:149]: Yes,  I think so. If  the student name is known, no point hiding the team name as a student can only belong to one team and the instructor know which team that is.

[the remark this answers is not in the document]
Comment (jtankw3) [reply src/main/java/teammates/ui/output/SessionResultsData.java:149]: @xpdavid Should I proceed to merge?

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/output/SessionResultsData.java:149]: Sure 👍
