### PR TITLE
FeedbackRubricQuestionUiTest: fix cannot focus element error on Chrome #7861

### LINKED ISSUE #7861: FeedbackRubricQuestionUiTest: fix cannot focus element error on Chrome
Our AppVeyor builds (which run Chrome) have been failing since 3ad37ca65e299f0cc7b3499c2d50ff2d81499564:
```
org.gradle.internal.serialize.PlaceholderException: unknown error: cannot focus element
  (Session info: chrome=59.0.3071.86)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 41 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'APPVYR-WIN', ip: '172.24.18.153', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Session ID: 268ecd7fff0a8505486743aed63bd8d3
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=WIN8_1, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\appveyor\AppData\Local\Temp\1\scoped_dir6956_16631, chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41)}, networkConnectionEnabled=false, unexpectedAlertBehaviour=, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=59.0.3071.86, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
	at teammates.test.cases.browsertests.FeedbackRubricQuestionUiTest.testEditQuestionAction(FeedbackRubricQuestionUiTest.java:381)
	at teammates.test.cases.browsertests.FeedbackRubricQuestionUiTest.testEditPage(FeedbackRubricQuestionUiTest.java:179)
	at teammates.test.cases.browsertests.FeedbackRubricQuestionUiTest.allTests(FeedbackRubricQuestionUiTest.java:44)
	...
Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.FeedbackRubricQuestionUiTest.allTests FAILED
    org.openqa.selenium.WebDriverException at FeedbackRubricQuestionUiTest.java:381
```

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7861 

The issue had two parts:

1. **Test failing locally using Firefox**: fixed in daa701b by adding a `waitForElementToBeClickable()` and changing the click method from `WebElement.click()` to our own `AppPage.click(WebElement)`
2. **Test failing both locally and on AppVeyor using Chrome:** fixed by removing the unnecessary `sendKeys()` call in 6d5494b. @VamsiSangam commented  _"move column buttons must be visible, otherwise, the test fails"_ before the line in question. I have left this comment in on purpose so that we can discuss whether or not the line I removed was actually necessary (as that comment implies), but the test passed on both chrome and firefox without this line and the "move column" buttons seemed to be visible anyway when I tried it out using `Thread.sleep()`.

### CODE REVIEW

**Comment by VamsiSangam** [comment]
Sorry for the mess :sweat: 

Without those `sendKeys()` the test never passed in my system, so I had to add it. `sendKeys()` was meant to scroll the page so that the move column buttons would be visible. But if there's a solution without that, then I believe we should surely take it.

@HirdayGupta please fix the style errors. You have unused imports. Just want to confirm that the Travis CI build passes. After which, I will have a closer look at your fix :+1:

**Comment by HirdayGupta** [comment]
> sendKeys() was meant to scroll the page so that the move column buttons would be visible.

@VamsiSangam I figured that that was the intention. However, chromedriver doesn't seem to allow key inputs on non-input HTML elements. If you see the discussion for issues [59](https://bugs.chromium.org/p/chromedriver/issues/detail?id=59), [144](https://bugs.chromium.org/p/chromedriver/issues/detail?id=144) and [145 ](https://bugs.chromium.org/p/chromedriver/issues/detail?id=145) on the chromedriver issue tracker, you will see that these problems have been there since a long time. The devs even say they have fixed it in some comments but the users' problems persisted even after that and no one seemed to take it up.

> But if there's a solution without that, then I believe we should surely take it.

I don't think the `sendKeys` is necessary at all. The test passed on both firefox and chrome on my local system without it. The test initially failed on firefox locally because the changes I introduced in daa701b were missing. I'm quite surprised you weren't also met with the same error.


> please fix the style errors. You have unused imports. Just want to confirm that the Travis CI build passes.

Sorry about that, Eclipse usually points out checkstyle errors 😅. Have committed the fix, lets see what Travis says :)

**Comment by HirdayGupta** [comment]
@VamsiSangam [Travis has passed](https://travis-ci.org/TEAMMATES/teammates/builds/258137723#L1964) the `FeedbackRubricQuestionUiTest`. Can you check if these changes also pass the test on your computer?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java [hunk 1]
```diff
@@ -398,7 +398,8 @@ private boolean moveRubricCol(int qnNumber, int colNumber, boolean isMoveLeft) {
         WebElement moveColButton = browser.driver.findElement(By.id(elemId));
 
         if (moveColButton.getAttribute("disabled") == null) {
-            moveColButton.click();
+            waitForElementToBeClickable(moveColButton);
```
Comment (VamsiSangam) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: I think this can be removed. I commented it out and the tests still passed :smile: . Moreover, if the buttons isn't disabled, then I think it should be clickable.

Comment (HirdayGupta) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: In my opinion, It's always better to add a wait before the clicks, I think it improves the success rate of the tests. It's also there before most clicks in the tests haha. 

@whipermr5 Is this also defensive coding? And would you recommend keeping it or removing it?

**Comment by whipermr5** [comment]
> I don't think the sendKeys is necessary at all. The test passed on both firefox and chrome on my local system without it. The test initially failed on firefox locally because the changes I introduced in daa701b were missing. I'm quite surprised you weren't also met with the same error.

Did this happen consistently? The current test on `master` passes completely for me on Firefox.

**Comment by HirdayGupta** [comment]
> Did this happen consistently? The current test on master passes completely for me on Firefox. Edit: after a few rounds, now I'm getting the same error you posted; strange

@whipermr5 Like you said in https://github.com/TEAMMATES/teammates/issues/7861#issuecomment-318291738, the `click(WebElement)` method is more reliable because it uses the JS Executor.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java (hunk 1 above)
Comment (HirdayGupta) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: @whipermr5 Requesting your opinion on this.

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: I think it's only required if the buttons dynamically change state and might be expected to not be clickable at that point in the test. Since the non-disabled buttons are always clickable, I feel it can be removed.

Defensive coding is more about using assertions and checking for null, and is more relevant in production code. For UI tests, we shouldn't introduce too many waits. It's good to quickly fail the test if the button is somehow not clickable at this point.

Also, according to Selenium code comments for `ExpectedConditions.elementToBeClickable`, an element is clickable if it is both visible and enabled. The code for determining visibility and enablement calls `isDisplayed()` and `isEnabled()` on the element. Taking cue from their code, we can replace the condition `moveColButton.getAttribute("disabled") == null` with `moveColButton.isEnabled()` for more readable code.

**Comment by whipermr5** [comment]
@HirdayGupta Yup! Anyway, the comment can be deleted now that we've ascertained that `sendKeys` is not needed. Perhaps it was only needed for `.click()`.

**Comment by HirdayGupta** [comment]
@whipermr5 @VamsiSangam Ready for review :)
