### PR TITLE
[#11309] Drop downs for further actions in tables expands by adding scrolling to table

### LINKED ISSUE #11309: Drop downs for further actions in tables expands by adding scrolling to table
- **Environment**: master branch at commit 2416bc5807b8400f78cf67d9246256bbc486379d

**Steps to reproduce**
1. Create a new course and a new feedback session for that course.
2. Go to courses page
3. Resize page such that the row of the table spans a height of 2
4. Click results on the lowest row on the table, of the first course  (the 2nd course doesn't have this issue)

**Actual behaviour**
The drop down created through results is blocked and hidden.
Screen Shot 2021-07-26 at 12 20 00 AM
They're actually expanding properly, not being clipped, but the user needs to scroll within the table to select the options.
Screen Shot 2021-07-26 at 12 20 17 AM
(It is not shown in the screenshot, but there's actually a scroll bar on the right, on only the table)

**Expected behaviour**
The drop down should either clip through the bottom
Screen Shot 2021-07-26 at 12 20 50 AM
Or display towards the top
Screen Shot 2021-07-26 at 12 20 30 AM

**Additional info**

The issue doesn't occur if this is the last course in the list. (In which case, it displays towards the top). 
The issue also doesn't occur if the table row only spans one light (in which case, it clips through the bottom).  
This issue affects other pages too, such as the feedback sessions page.

### PR DESCRIPTION
**Pull request by samuelfangjw**
Fixes #11309 

**Outline of Solution**

Add `container="body"` to dropdown. Fixes issue in instructors home and sessions page.

Link to docs on container attribute [here](https://ng-bootstrap.github.io/#/components/dropdown/examples#container). It appends the dropdown to the `<body>` element (direct child of html root element) instead of the table cell where the button is so that it is no longer affected by the `overflow: auto` property of the table (because it is no longer a child element of the table).

Before:
Screenshot 2021-07-29 at 2 53 53 PM

After:
Screenshot 2021-07-29 at 2 54 14 PM

**Additional Information**
I've checked the other dropdowns and was unable to replicate this issue with them. In particular, I was unable to replicate this with the `Other Actions` dropdown menu in the instructor courses page, which I had expected to have the same bug.

### CODE REVIEW

**Comment by samuelfangjw** [comment]
Slightly unrelated to the current PR, but I found two other anomalies while checking the dropdowns and was unsure whether or not they were issues or intended.
* In the instructor help page, under the question "How do I add questions to a session?", seems like the add new question button was supposed to be a dropdown.

Screenshot 2021-07-29 at 3 07 38 PM

* `ngbDropdown` attribute in line 107 of  `sessions-table.component.html` doesn't seem to change anything when removed, might be redundant.
  
```html
<div ngbDropdown class="d-inline-block" ngbTooltip="Send e-mails to remind students and instructors who have not submitted their feedbacks to do so">
    <button id="btn-remind-{{ idx }}" class="btn btn-light btn-sm" (click)="sendRemindersToStudents(idx)"
    [disabled]="sessionsTableRowModel.feedbackSession.submissionStatus !== FeedbackSessionSubmissionStatus.OPEN ||
              !sessionsTableRowModel.instructorPrivilege.canModifySession">Remind</button>
</div>
```

**Comment by ChooJeremy** [comment]
Hi, trying to understand here, how does this solve the issue? Do you have any links to docs on what the `container` attribute does? I couldn't find anything from google.

I'm also unable to reproduce the issue on the instructor courses page.

**Comment by samuelfangjw** [comment]
> Hi, trying to understand here, how does this solve the issue? Do you have any links to docs on what the `container` attribute does? I couldn't find anything from google.
> 
> I'm also unable to reproduce the issue on the instructor courses page.

Link to docs [here](https://ng-bootstrap.github.io/#/components/dropdown/examples#container). It appends the dropdown to the `<body>` element (direct child of html root element) instead of the table cell where the button is so that it is no longer affected by the `overflow: auto` property of the table (because it is no longer a child element of the table).

Hope this explanation helps! Also updated the description to make it clearer.

File: src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java [hunk 1]
```diff
@@ -64,13 +64,15 @@ public void copySession(int courseTabIndex, int sessionIndex, CourseAttributes c
...
+        List<WebElement> publishButtons = browser.driver.findElements(By.id("btn-publish-" + sessionIndex));
+        clickAndConfirm(publishButtons.get(publishButtons.size() - 1));
     }
 
     public void unpublishSessionResults(int courseTabIndex, int sessionIndex) {
         WebElement courseTab = getCourseTab(courseTabIndex);
         click(courseTab.findElement(By.id("btn-results-" + sessionIndex)));
-        clickAndConfirm(courseTab.findElement(By.id("btn-unpublish-" + sessionIndex)));
+        List<WebElement> unpublishButtons = browser.driver.findElements(By.id("btn-unpublish-" + sessionIndex));
+        clickAndConfirm(unpublishButtons.get(unpublishButtons.size() - 1));
```
Comment (ChooJeremy) [inline src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java:75]: Is this change required? Seems like it does the same thing.

**Review by ChooJeremy — COMMENTED** [review]
Thanks for the explanation! That solution looks good.

File: src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java (hunk 1 above)
Comment (samuelfangjw) [reply src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java:75]: Yes, I believe it is necessary. e2e tests [fail](https://github.com/TEAMMATES/teammates/runs/3189369963) without the change.

Previously, the unpublish button was attached to the courseTab, so we can simply use `courseTab.findElement(By.id("btn-unpublish-" + sessionIndex))` to find the correct button.

After the change, the unpublish button is now attached to the html body,  so we have to use `browser.driver.findElements(By.id("btn-unpublish-" + sessionIndex))` to search for the button instead. However, there may be multiple buttons with the same id (in different course tabs), so we have to take the last button in the list (since the dropdown menu is now appended to the end of the html body).

**Review by ChooJeremy — APPROVED** [review]

**Review by ccyccyccy — APPROVED** [review]
Clean fix!
