### PR TITLE
Fix assertion error in instructorCourseJoinEmail on live server #8452

### LINKED ISSUE #8452: Fix assertion error in instructorCourseJoinEmail on live server
v6.1
Found many of these in log.
On a related note, these are logged as 'warning' rather than 'severe'. Shouldn't they be severe?
```
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /worker/instructorCourseJoinEmail (JettyLogger.java:29)
java.lang.AssertionError: null
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:272)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:263)
	at teammates.ui.automated.InstructorCourseJoinEmailWorkerAction.execute(InstructorCourseJoinEmailWorkerAction.java:37)
	at teammates.ui.automated.AutomatedServlet.doPost(AutomatedServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:202)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:108)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
```

### LINKED ISSUE #8911: Fix assertion error in studentCourseJoinEmail
v6.6.0

Got a few of these today

Error Message: teammates.common.util.Logger severe: Exception occured while performing http://teammatesv4.appspot.com/worker/studentCourseJoinEmail|||
java.lang.AssertionError: null
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
at teammates.common.util.Assumption.assertNotNull(Assumption.java:272)
at teammates.common.util.Assumption.assertNotNull(Assumption.java:263)
at teammates.ui.automated.StudentCourseJoinEmailWorkerAction.execute(StudentCourseJoinEmailWorkerAction.java:39)

at teammates.ui.automated.AutomatedServlet.doPost(AutomatedServlet.java:46)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:120)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:171)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle(Server.java:534)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:202)
at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:123)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:693)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:655)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:625)
at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:819)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8452 
Fixes #8911

**Outline of Solution**

- @xpdavid has mentioned the reason for the error and the way to fix here https://github.com/TEAMMATES/teammates/issues/8452#issuecomment-400995832 🎉 
- Refactored `InstructorDb` and `StudentDb` to use `id` for querying

Note: I am not sure of how we can test this method works and solves the problem. However, I have tested and ensured that this doesn't break any existing functionality

### CODE REVIEW

**Comment by tshradheya** [comment]
I think there are some regressions due to these changes. Working on fixing them

File: src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java [hunk 1]
```diff
@@ -39,7 +39,7 @@ public void execute() {
         CourseAttributes course = logic.getCourse(courseId);
         Assumption.assertNotNull(course);
 
-        InstructorAttributes instructor = logic.getInstructorForEmail(courseId, instructorEmail);
+        InstructorAttributes instructor = logic.getInstructorById(courseId, instructorEmail);
```
Comment (xpdavid) [inline src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: What if instructor A invites instructor B and A finds that B's email is wrong while the instructor account is already created. A changes the email accordingly and resend the invitation email. In this case, I believe B will never receive the email.

Actually, if it is not to complicated, we can implement the re-creation logic same as the student DB.

Comment (tshradheya) [reply src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: > A changes the email accordingly and resends the invitation email. 

This is not possible. Once B is added by A, A can only edit B's email address once B has joined using a Google account.

screen shot 2018-07-01 at 1 46 54 pm


> Actually, if it is not to complicated, we can implement the re-creation logic same as the student DB.

I will still investigate this as in future its better to adopt this strategy cause currently our database is flawed as there will be many cases where `emaild` in the `id` is not same as `emailId` feild.

Comment (xpdavid) [reply src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: Okay, please add some comment in InstructorCourseJoinEmailWorkerAction.java to explain the situation.

Comment (tshradheya) [reply src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: Added. Ready for review @xpdavid

File: src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java [hunk 2]
```diff
@@ -39,7 +39,10 @@ public void execute() {
         CourseAttributes course = logic.getCourse(courseId);
         Assumption.assertNotNull(course);
 
-        InstructorAttributes instructor = logic.getInstructorForEmail(courseId, instructorEmail);
+        // The instructor is queried using the `id` (email%courseId) as it ensures that the
+        // instructor is retrieved (and not null) even if the index building for
+        // saving the new instructor takes more time in GAE.
+        InstructorAttributes instructor = logic.getInstructorById(courseId, instructorEmail);
```
Comment (xpdavid) [inline src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: I actually want to explicitly say that instructor ID can be constructed back by courseID + instructorEmail here (because instructors' email cannot be changed before joining the course).

Comment (tshradheya) [reply src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java]: Updated. Also corrected the typo in `Instructor` entity

File: src/main/webapp/dev/js/common/richTextEditor.js [hunk 3]
```diff
@@ -53,6 +53,7 @@ const richTextEditorBuilder = {
 /* eslint-enable camelcase */
 
 function setPlaceholderText(editor) {
+    console.log(editor.getContent());
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/main/webapp/dev/js/common/richTextEditor.js]: Looks like changes from other branch got mixed up

**Comment by damithc** [comment]
@tshradheya use the `request review` feature to request for the final review (not `assignee` feature)
