### PR TITLE
[#10305] CollapseAnim causing elements to be cut off 

### LINKED ISSUE #10305: CollapseAnim causing elements to be cut off
Children elements of elements with CollapseAnim attached are cut off when they overflow.

- **Environment**: `master` branch at commit a5f15f9f634d1b988b3f6f50a85959365da48b1b

**Steps to reproduce**
Interact with elements that exceeds height of parent element (eg. feedback edit page visibility date picker)

**Expected behaviour**
Dropdown/tooltip should be visible even if they overflow

**Actual behaviour**
The elements are cut off

**Additional info**
Example, date picker is not completely visible
datepicker

### PR DESCRIPTION
**Pull request by jtankw3**
Fixes #10305

**Outline of Solution**

Set overflow to be set back to visible after animation ends instead of remaining as hidden in all states
Animation remains smooth and cut off problem is solved

**Screenshot**
datepicker-fixed

### CODE REVIEW

File: src/web/app/components/teammates-common/collapse-anim.ts [hunk 1]
```diff
@@ -1,17 +1,15 @@
...
   transition(':leave', [
-    style({ height: '*' }),
+    style({ height: '*', overflow: 'hidden' }),
     animate('300ms ease-in-out', style({ height: 0, opacity: 0 })),
   ]),
   transition(':enter', [
-    style({ height: '0' }),
-    animate('300ms ease-in-out', style({ height: '*', opacity: 1 })),
+    style({ height: '0', overflow: 'hidden' }),
+    animate('300ms ease-in-out', style({ height: '*', opacity: 1, overflow: 'visible' })),
```
Comment (ccyccyccy) [inline src/web/app/components/teammates-common/collapse-anim.ts:13]: Dont think `overflow: 'visible'` does anything, since `style` within `animate` gets removed after the transition.
If the aim is to be explicit, you could add `state('*', style({ overflow: 'visible' }))` instead.
Refer:  https://stackoverflow.com/a/47351870

Comment (jtankw3) [reply src/web/app/components/teammates-common/collapse-anim.ts]: Thanks for the link! I think it is not necessary to be explicit so I have removed it.
