### PR TITLE
[#10467] Instructor courses page: Fix courses default sorting not working as intended

### LINKED ISSUE #10467: Instructor courses page: sort course list by descending creation time
Sort the course list by creation time by default, in descending order, so that newly created courses appear at the top of the list whenever a new course is added.

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #10467 

#### Fix for some existing problems with sorting

- Fix active courses sort order getting reversed every time a new course is added
- Set default sort order to be descending when column to be sorted is changed
- Fix default sort order for archived and deleted courses falsely shown to be sorted but not actually sorted.
- Change default sort order for archived and deleted courses to be COURSE_CREATION_DATE and COURSE_DELETION_DATE respectively

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts [hunk 1]
```diff
@@ -378,32 +380,68 @@ export class InstructorCoursesPageComponent implements OnInit {
...
     this.activeTableSortBy = by;
-    this.activeTableSortOrder =
-        this.activeTableSortOrder === SortOrder.DESC ? SortOrder.ASC : SortOrder.DESC;
     this.activeCourses.sort(this.sortBy(by, this.activeTableSortOrder));
   }
 
+  /**
+   * Active courses default sort on page load
+   */
+  coursesDefaultSort(): void {
```
Comment (t-cheepeng) [inline src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:395]: Let's be consistent with naming and change to `activeCoursesDefaultSort`

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts [hunk 2]
```diff
@@ -378,32 +380,68 @@ export class InstructorCoursesPageComponent implements OnInit {
    * Sorts the active courses table
    */
   sortCoursesEvent(by: SortBy): void {
```
Comment (t-cheepeng) [inline src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:382]: same here. `sortActiveCoursesEvent`

**Comment by madanalogy** [comment]
@ccyccyccy I think there might be a problem with how the `InstructorCoursesPageE2ETest` runs with the new default sorting order. Can ask @jtankw3 for help if you can't resolve it
