### PR TITLE
*FeedbackSubmitPageUiTest: Fix dependency on current time #7808

### LINKED ISSUE #7808: *FeedbackSubmitPageUiTest: Fix dependency on current time
StudentFeedbackSubmitPageUiTest may fail due to test case "Grace period session", as the `endTime` of "Grace period session" is not set with respect to the time zone of the session, but to UTC.

InstructorFeedbackSubmitPageUiTest may fail due to test case "Private session", as it contains a `null` endTime and the `getEndTimeString` fails to handle it properly.

### PR DESCRIPTION
**Pull request by HirdayGupta**
Fixes #7808 

Fixes the recent slew of Travis build errors between UTC 1600 and UTC 0000. The builds were failing due to some aspects being overlooked in #7740. The exact causes are explained by @leeyimin in the Issue Description.

**Outline of solution**
- Handle null end time in a44db4e. This prevents the build error for InstructorFeedbackSubmitPageUiTest.
- Set the session end time to current time in the session's time zone instead of UTC in 5916ccc. This prevents the build error for StudentFeedbackSubmitPageUiTest.

Sorry for taking so long to push these changes. As I explained in https://github.com/TEAMMATES/teammates/issues/7808#issuecomment-317053489, I missed [this line](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/HtmlHelper.java#L394) in HtmlHelper which converts the current time to the time zone it sees on the page. Because I missed that, I thought that only the current time in UTC would be replaced and was confused about why the current behaviour was then, not working. Sincere apologies once again for the oversight.

Side note: Perhaps as a result of this issue, we could make it a rule for all time-related changes to be run on Travis at least twice over a 24 hour period with at least a 12-hour gap between the two test runs? This suggestion is based on the current behaviour of HtmlHelper which replaces current time only depending on DD/MM/YYYY.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
Dropping a note that the ONLY failing test is `AdminActivityLogPageActionTest.statusMessageAndContinueSearch_withManyLogs_searchCorrectly` (This test often fails a lot on the first few tries and then ultimately passes).  Requesting a dev to please restart the Travis build as the build error from that test seems to go away on repeated attempts.

The tests whose build this PR set out to correct seem to have passed.

**Comment by HirdayGupta** [comment]
Ready for review

**Comment by amarlearning** [comment]
@HirdayGupta Test `AdminActivityLogPageActionTest.statusMessageAndContinueSearch_withManyLogs_searchCorrectly` fails for everyone and I guess an issue is also open.

And there is no setting that restarts the build automatically, I did :stuck_out_tongue_closed_eyes:

**Comment by HirdayGupta** [comment]
> And there is no setting that restarts the build automatically, I did 😝

I only just discovered that we can restart builds too 😂 (Thanks for that btw)

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 1]
```diff
@@ -173,6 +173,9 @@ public static Calendar convertToUserTimeZone(Calendar time, double timeZone) {
      */
     @Deprecated
     public static Date convertLocalDateToUtc(Date localDate, double localTimeZone) {
+        if (localDate == null) {
+            return null;
+        }
```
Comment (leeyimin) [inline src/main/java/teammates/common/util/TimeHelper.java]: Instead of doing the null check here, I think it would be better suited to do it in `getStartTimeString` and `getEndTimeString` so that it is clearer that the behaviour is different when the value is null.

Comment (HirdayGupta) [inline src/main/java/teammates/common/util/TimeHelper.java]: @leeyimin How about we do both? I could leave this here as a general case for any future calls to this helper method and I could also handle it in the getter methods in fsAttributes as the special case.

Comment (leeyimin) [inline src/main/java/teammates/common/util/TimeHelper.java]: @HirdayGupta Sure :)

Comment (HirdayGupta) [inline src/main/java/teammates/common/util/TimeHelper.java]: Done :)

**Comment by HirdayGupta** [comment]
@leeyimin Ready for further review :)

File: src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java [hunk 2]
```diff
@@ -148,11 +148,17 @@ public String getFeedbackSessionName() {
...
+        if (startTime == null) {
+            return "";
+        }
         Date startTimeInUtc = TimeHelper.convertLocalDateToUtc(startTime, timeZone);
         return TimeHelper.formatDateTimeForSessions(startTimeInUtc, timeZone);
     }
 
     public String getEndTimeString() {
+        if (endTime == null) {
+            return "";
```
Comment (leeyimin) [inline src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java]: Maybe return `"-"` instead?
image
 Leaving a blank space there seems odd to me.

Comment (HirdayGupta) [inline src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java]: Done
