### PR TITLE
InstructorFeedbackResultsPageUiTest: Fix false positive assertion #7723

### LINKED ISSUE #7723: InstructorFeedbackResultsPageUiTest: Fix false positive assertion
In `testDownloadAction()`, there is a line: `assertFalse(reportUrl.equals(afterReportDownloadUrl));`. However, `reportUrl` is an AppUrl, `afterReportDownloadUrl` is a String, `equals` for AppUrl is not overridden. Thus, the expression is always false, even if both string expression could be the same.

### PR DESCRIPTION
**Pull request by AlexM9200**
Fixes #7723 

**Outline of Solution**

Call toString on AppUrl object before calling the equals method so that 2 strings are compared.

### CODE REVIEW

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 1]
```diff
@@ -702,7 +702,7 @@ private void testDownloadAction() {
                                               .withUserId("CFResultsUiT.instr");
         browser.driver.get(reportUrl.toAbsoluteString());
         String afterReportDownloadUrl = browser.driver.getCurrentUrl();
-        assertFalse(reportUrl.equals(afterReportDownloadUrl));
+        assertFalse(reportUrl.toString().equals(afterReportDownloadUrl));
```
Comment (LimeTheCoder) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Hi @AlexM9200 , nice work! I know it's not related to your issue, but you still can improve this line to use assertEquals instead of assertFalse here:
`assertEquals(reportUrl.toString(), afterReportDownloadUrl)`

Comment (LimeTheCoder) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Hi @AlexM9200 , nice work! I know it's not related to your issue, but you still can improve this line to use assertEquals instead of assertFalse here:
`assertEquals(reportUrl.toString(), afterReportDownloadUrl)`

Comment (AlexM9200) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Thanks! I'll do that now.

Comment (AlexM9200) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: @LimeTheCoder, changing to assertEquals caused the CI tests to fail. Should I change it back to use assertFalse?

Comment (LimeTheCoder) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Currently,  we don't have assertNotEquals method, so you can revert the last commit. Sorry for confusion.

Comment (AlexM9200) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: @LimeTheCode Done.

Comment (LimeTheCoder) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Congrats with first pull request))

Comment (AlexM9200) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Thanks a lot!

**Comment by whipermr5** [comment]
@AlexM9200 Thanks for your contribution! Take note of our PR title naming conventions as specified in our guidelines for your future PRs - I've helped you fix it this time as it's your first PR :)

**Comment by AlexM9200** [comment]
@whipermr5 No problem, it's my pleasure. Sorry about that. I'll take more care for future PR's. Thank you ☺
