### PR TITLE
CoursesLogicTest sometimes fails due to wrong ordering #5439

### LINKED ISSUE #5439: CoursesLogicTest: fix occasional test failure due to wrong ordering
In testGetCoursesForStudentAccount(),

```
// For some reason, index 0 is Course2 and index 1 is Course1
// Anyway in DataStore which follows a HashMap structure,
// there is no guarantee on the order of Entities' storage
```

Test should not assume the order of values in a hashmap.

### PR DESCRIPTION
**Pull request by sujeet14108**
Fixes #5439

### CODE REVIEW

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 1]
```diff
@@ -438,12 +438,24 @@ private void testGetCoursesForStudentAccount() throws Exception {
         assertEquals(2, courseList.size());
 
         CourseAttributes course1 = dataBundle.courses.get("typicalCourse1");
-        assertEquals(course1.getId(), courseList.get(0).getId());
-        assertEquals(course1.getName(), courseList.get(0).getName());
+        int temp = 0;
+        for (CourseAttributes course : courseList) {
+            if (course.compareTo(course1) == 0) {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Why not just use `course.equals(course1)`?

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 2]
```diff
@@ -438,12 +438,24 @@ private void testGetCoursesForStudentAccount() throws Exception {
         assertEquals(2, courseList.size());
 
         CourseAttributes course1 = dataBundle.courses.get("typicalCourse1");
-        assertEquals(course1.getId(), courseList.get(0).getId());
-        assertEquals(course1.getName(), courseList.get(0).getName());
+        int temp = 0;
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: `temp` is not a good variable name, and not suggestive of what it is about. Something like `boolean isCourse1Present = false;` which will be set to `true` later is better.
That way you also do not need to loop twice; simply keep two boolean checkers.

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java (hunk 1 above)
Comment (sujeet14108) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: @wkurniawan07  I don't know why but `equals` is not working here but `compareTo` is working fine.

**Comment by sujeet14108** [comment]
@wkurniawan07 Ready for review :)

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 3]
```diff
@@ -438,12 +438,22 @@ private void testGetCoursesForStudentAccount() throws Exception {
...
 
         CourseAttributes course2 = dataBundle.courses.get("typicalCourse2");
-        assertEquals(course2.getId(), courseList.get(1).getId());
-        assertEquals(course2.getName(), courseList.get(1).getName());
+
+        boolean isCourse1Present = false;
+        boolean isCourse2Present = false;
+
+        for (CourseAttributes course : courseList) {
+            if (course.compareTo(course1) == 0) {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: `compareTo` does not replace `equals`. Take this analogy: when you're sorting a deck of poker cards numerically (disregarding the suits), a 5 of hearts and a 5 of diamonds will have the same value, but they are not the same card.
If `equals` is not defined for this class (seems like it is the case), just use the way it is done before, i.e. comparing the ID and the name.

**Comment by sujeet14108** [comment]
@wkurniawan07 why test failed?

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 4]
```diff
@@ -438,12 +438,22 @@ private void testGetCoursesForStudentAccount() throws Exception {
...
+
+        boolean isCourse1Present = false;
+        boolean isCourse2Present = false;
+
+        for (CourseAttributes course : courseList) {
+            if (course.getId().equals(course1.getId()) && course.getName().equals(course1.getName())) {
+                isCourse1Present = true;
+            } else if (course.getId().equals(course2.getId()) && course.getName().equals(course2.getName())) {
+                isCourse2Present = true;
+            }
```
Comment (damithc) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Should there be a ` } else { fail(); } ` here?

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 5]
```diff
@@ -438,12 +438,22 @@ private void testGetCoursesForStudentAccount() throws Exception {
...
+        }
+
+        assertTrue(isCourse1Present);
+        assertTrue(isCourse2Present);
```
Comment (damithc) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Which one of these are we doing here?
1. Given list1 and list2, confirm both has the same objects irrespective of the order
2. Given list1 and list2, confirm list1 contains all objects in list2?
In either case, may be write a general utility method is the better approach? e.g. `areSameElements(List<T>, List<T>)`. The current one is just a stop gap solution that does not scale well when the number of objects involved are higher.

Another approach to consider is to avoid the problem altogether by getting rid of the non-determinism. e.g. modify the API to return the values in a specified sort order.

What do you guys think?

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java (hunk 4 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Unnecessary; the list size is checked and the list content is checked via the two boolean vars.

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java (hunk 5 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: More like 2. We have one such method, but it requires `equals` to be defined which is not the case for any of the `*Attributes` class.

> The current one is just a stop gap solution that does not scale well when the number of objects involved are higher.

I will not say this is a problem. Unscalable as it may, we do not need it to be scalable at this point of time.

> Another approach to consider is to avoid the problem altogether by getting rid of the non-determinism. e.g. modify the API to return the values in a specified sort order.

I won't object to this solution.

Comment (damithc) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: @sujeet14108 can you explore the alternative of sorting the list at the method being tested or inside the test itself? `CourseAttributes` class has some static methods for sorting.

Comment (sujeet14108) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Cannot we solve this like this by creating another List and of courses and sorting both the list by Id 

        List<CourseAttributes> courseList = coursesLogic
                .getCoursesForStudentAccount(studentInTwoCourses.googleId);
        CourseAttributes.sortById(courseList);
        assertEquals(2, courseList.size());
        
        CourseAttributes course1 = dataBundle.courses.get("typicalCourse1");

        CourseAttributes course2 = dataBundle.courses.get("typicalCourse2");

        List<CourseAttributes> courses= new  ArrayList<CourseAttributes>();
        courses.add(course1);
        courses.add(course2);
       
        CourseAttributes.sortById(courses);
       
        assertEquals(courses.get(0).getId(), courseList.get(0).getId());
        assertEquals(courses.get(0).getName(), courseList.get(0).getName());

        assertEquals(courses.get(1).getId(), courseList.get(1).getId());
        assertEquals(courses.get(1).getName(), courseList.get(1).getName());`

Comment (damithc) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: > Cannot we solve this like this by creating another List and of courses and sorting both the list by Id

Yes, that's what I was thinking too.

**Comment by sujeet14108** [comment]
@damithc I think we need to sort both the list by Id and that what i am doing.

**Comment by damithc** [comment]
> I think we need to sort both the list by Id and that what i am doing.

@sujeet14108 I suspect `courseList` is the one that needs sorting because it is retrieved using a call to the datastore and therefore the order is not fixed. I can't see your code sorting that list. 

But I could be wrong, so I'll wait for @wkurniawan07's or @leeyimin 's confirmation.

**Comment by sujeet14108** [comment]
@damithc    On Line 438
`       CourseAttributes.sortById(courseList);`
It is getting sorted

**Comment by damithc** [comment]
> It is getting sorted

If that list was sorted from the beginning (which means the list order is always the same), this test case should always pass or always fail because the value of `course1` and `course2` are always the same too. What am I missing here?

**Comment by leeyimin** [comment]
It seems like the issue was already fixed in #5886 when sorting to `courseList` was added.

**Comment by leeyimin** [comment]
But there is still value in this PR as this makes the test less dependent on the actual course id values in the testing data.

**Comment by damithc** [comment]
> But there is still value in this PR as this makes the test less dependent on the actual course id values in the testing data.

Ok, let's go ahead then.
