### PR TITLE
[#10594] Fixed instructor page course edit spinner

### LINKED ISSUE #10594: Instructor edit course details page: loading spinner for edit does not disappear
**Steps to reproduce**

Go to edit course details page, edit an instructor, click save changes. Then click edit again and choose cancel this time.

**Expected behaviour**

The spinner next to edit should not be shown.

**Actual behaviour**

The spinner next to edit appears and stays there. Also, the spinner is inconsistent with editing course details: when saving course details, spinner appears next to save changes button:
image

However, when saving instructor details, spinner appears next to edit button:
image

May be better to standardise the two.

### PR DESCRIPTION
**Pull request by brandedcow**
Fixes #10594 

fix

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts [hunk 1]
```diff
@@ -403,6 +405,7 @@ export class InstructorCourseEditPageComponent implements OnInit {
       courseId: panelDetail.originalInstructor.courseId,
       requestBody: reqBody,
     }).pipe(finalize(() => panelDetail.editPanel.isSavingInstructorEdit = false)).subscribe((resp: Instructor) => {
+      panelDetail.editPanel.isEditing = false;
```
Comment (niqiukun) [inline src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts:408]: Just a suggestion, you can put this line inside the `finalize` clause so that it is consistent with the loading spinner.

**Review by niqiukun — APPROVED** [review]
LGTM besides one small suggestion.

File: src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts [hunk 2]
```diff
@@ -417,7 +420,6 @@ export class InstructorCourseEditPageComponent implements OnInit {
       this.statusMessageService.showErrorToast(resp.error.message);
     });
 
-    panelDetail.editPanel.isEditing = false;
     panelDetail.originalPanel = JSON.parse(JSON.stringify(panelDetail.editPanel));
```
Comment (niqiukun) [inline src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts:423]: Actually while it is not directly related to this bug, you can also move this line into `subscribe` to prevent invalid response from overwriting the original.
