### PR TITLE
Instructor: download results: multiple repetition of header bug #7707

### LINKED ISSUE #7707: Instructor: download results: multiple repetition of header bug
In CSV results file, header repeats before each row with response instead of appearing only once at the beginning.

image

### PR DESCRIPTION
**Pull request by LimeTheCoder**
Fixes #7707 

**Outline of Solution**
Removed header generation from the loop, what was exactly the root cause of the bug.
Also, before generation of the header, I find a maximum number of comments per response and according to that number I generate the appropriate header.
For example, If in response lists exist response with a maximum number of comments as 2, then to default header will be added following: "Comment From, Comment, Comment From, Comment"

Header repetition fixed:
image

### CODE REVIEW

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 1]
```diff
@@ -945,6 +941,23 @@ private StringBuilder getFeedbackSessionResultsForQuestionInCsvFormat(
         return exportBuilder;
     }
 
+    private int getMaxNumberOfResponseComments(List<FeedbackResponseAttributes> allResponses,
+                                               Map<String, List<FeedbackResponseCommentAttributes>> responseComments) {
```
Comment (LimeTheCoder) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Hi, @chowyb Thanks for the review. Checkstyle forced me to use 12 spaces instead of 8.

Comment (chowyb) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Hi @LimeTheCoder, yep that should be fine. Usually, when we say "use 8 spaces", it tends to mean "use an additional 8 spaces as compared to the previous line". The general idea is just to avoid custom indentation.
