### PR TITLE
[#9059] Testing: Use correct EXPECTED_SNIPPET_SIGN_IN in GoogleLoginPage

### LINKED ISSUE #9059: Testing: Use correct EXPECTED_SNIPPET_SIGN_IN in GoogleLoginPage
<strike>It seems like the google login page sometimes has `Sign in - Google accounts` instead of expected `Sign in - Google Accounts` (Typo in Google Side :P)

image

Our automated test will fail if the title is not matched. 

Maybe should do case-insensitive comparison between expected and actual?</strike>

image

It seems that Google has changed the title and the behaviour become consistent. 

The title should be `Sign in – Google accounts`.

### PR DESCRIPTION
**Pull request by carsonshoupe**
Fixes #9059 

Ready for review

**Outline of Solution**
I added both variants of the EXPECTED_SNIPPET_SIGN_IN string and updated containsExpectedPageContents to check if either of them are contained in the page source.

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/GoogleLoginPage.java [hunk 1]
```diff
@@ -12,7 +12,8 @@
 
 public class GoogleLoginPage extends LoginPage {
 
-    private static final String EXPECTED_SNIPPET_SIGN_IN = "Sign in - Google Accounts";
+    private static final String EXPECTED_SNIPPET_SIGN_IN_VARIANT_ONE = "Sign in - Google Accounts";
+    private static final String EXPECTED_SNIPPET_SIGN_IN_VARIANT_TWO = "Sign in - Google accounts";
```
Comment (tanhengyeow) [inline src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: Since this is the current variant Google uses, I suggest naming this line as `EXPECTED_SNIPPET_SIGN_IN_CURRENT_VARIANT` and the one on line 15 as `EXPECTED_SNIPPET_SIGN_IN_BACKUP_VARIANT`. Your thoughts on this? @xpdavid

Comment (xpdavid) [reply src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: @carsonshoupe I just want to point out this. Actually, the original issue is updated 18 days ago. 

> It seems that Google has changed the title and the behaviour become consistent.

The new title should be `Sign in – Google accounts`.

Comment (carsonshoupe) [reply src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: Ah.  That makes sense.  I'll make the updates and push the branch.

File: src/test/java/teammates/test/pageobjects/GoogleLoginPage.java [hunk 2]
```diff
@@ -12,7 +12,7 @@
 
 public class GoogleLoginPage extends LoginPage {
 
-    private static final String EXPECTED_SNIPPET_SIGN_IN = "Sign in - Google Accounts";
+    private static final String EXPECTED_SNIPPET_SIGN_IN = "Sign in - Google accounts";
```
Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: `-` should be changed to `–` :P

After that, @tanhengyeow you may want to help to try the fix with your own staging server.

**Comment by xpdavid** [comment]
@carsonshoupe In addition, the title of your PR is not correct. Please correct it.
