### PR TITLE
Fix some violations reported by FindBugs #6646

### LINKED ISSUE #6646: Fix some violations reported by FindBugs
We're unlikely to integrate FindBugs because of two reasons:
- It's extremely slow; running FindBugs on the entire code base takes 2+ minutes.
- It has no option to print lint failures to console; for a CI environment, this is a must-have.

But we still can fix as many violations it reported as possible.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6646 

**Outline of Solution**

Ran FindBugs analysis locally with maximum effort and maximum report level, and fixed about 70% of the reported violations. They can be identified by the commit messages.

@xpdavid here's to introduce FindBugs!

### CODE REVIEW

File: src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackPageAction.java [hunk 1]
```diff
@@ -34,15 +34,9 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
-        Assumption.assertNotNull(String.format(Const.StatusMessages.NULL_POST_PARAMETER_MESSAGE,
-                                               Const.ParamsNames.COURSE_ID),
-                                 courseId);
-        Assumption.assertNotNull(String.format(Const.StatusMessages.NULL_POST_PARAMETER_MESSAGE,
-                                               Const.ParamsNames.FEEDBACK_SESSION_NAME),
-                                 feedbackSessionName);
-        Assumption.assertNotNull(String.format(Const.StatusMessages.NULL_POST_PARAMETER_MESSAGE,
-                                               Const.ParamsNames.FEEDBACK_SESSION_MODERATED_PERSON),
-                                 instructorUnderModerationEmail);
+        Assumption.assertNotNull(Const.StatusMessages.NULL_POST_PARAMETER_MESSAGE, courseId);
```
Comment (xpdavid) [inline src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackPageAction.java]: So we are going to find the NPE by looking at the stack trace instead of looking at the error message. XD

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java [hunk 2]
```diff
@@ -277,8 +278,6 @@ public void testGetCourseSummaryWithoutStats() throws Exception {
         assertEquals(course.getId(), courseSummary.course.getId());
         assertEquals(course.getName(), courseSummary.course.getName());
 
-        assertEquals(0, courseSummary.sections.size());
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Why we need to remove this?

File: src/client/java/teammates/client/scripts/DataGenerator.java [hunk 3]
```diff
@@ -127,8 +121,8 @@ public static String generateData() {
     public static void generateDataForCourse(String courseName) {
         //number of courses for this particular instructor
         long numOfInstr =
-                Math.round(random.nextInt(MAX_NUM_OF_INSTRUCTOR_PER_COURSES - MIN_NUM_OF_INSTRUCTOR_PER_COURSES + 1)
-                           + MIN_NUM_OF_INSTRUCTOR_PER_COURSES);
+                random.nextInt(MAX_NUM_OF_INSTRUCTOR_PER_COURSES - MIN_NUM_OF_INSTRUCTOR_PER_COURSES + 1)
+                + MIN_NUM_OF_INSTRUCTOR_PER_COURSES;
```
Comment (wkurniawan07) [inline src/client/java/teammates/client/scripts/DataGenerator.java]: How is this messed up? :thinking:

File: src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackPageAction.java (hunk 1 above)
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackPageAction.java]: Well the previous one doesn't help either. There's _no_ `%s` in the said variable to be replaced with the parameter name.

File: src/test/java/teammates/test/cases/logic/CoursesLogicTest.java (hunk 2 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/CoursesLogicTest.java]: Or else it's compile error?

File: src/client/java/teammates/client/scripts/DataGenerator.java (hunk 3 above)
Comment (xpdavid) [inline src/client/java/teammates/client/scripts/DataGenerator.java]: Should be at the same indentation level as `MAX_NUM_OF_INSTRUCTOR...` right?

Comment (wkurniawan07) [inline src/client/java/teammates/client/scripts/DataGenerator.java]: Take a look at where the bracket ends...

File: src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java [hunk 4]
```diff
@@ -13,61 +13,21 @@
...
-                createdTime, startTime, endTime,
-                sessionVisibleFromTime, resultsVisibleFromTime,
-                timeZone, gracePeriod, feedbackSessionType,
-                sentOpenEmail, sentClosingEmail, sentClosedEmail, sentPublishedEmail,
-                isOpeningEmailEnabled, isClosingEmailEnabled, isPublishedEmailEnabled
-                );
+        fsa = new FeedbackSessionAttributes(null,
+                null, null, null, null, startTime, endTime,
+                null, null, 8, 15, FeedbackSessionType.STANDARD,
+                false, false, false, false, false, false, false);
```
Comment (damithc) [inline src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java]: This significantly reduces human readability. But may be ok since we are moving to Intellij which can show the parameter name in method calls so that's easy to see which parameter is being assigned which value.

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java]: But Eclipse can do the same? `CTRL + SHIFT + SPACE`.

Comment (damithc) [inline src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java]: Yes, but that doesn't help much in a case like this when there are many parameters. Intellij has taken it to a whole new level:
image
