### PR TITLE
instructor edit student email: Give an option to resend emails when editing student email #5577

### LINKED ISSUE #5577: instructor edit student email: Give an option to resend emails when editing student email
When editing student email, it can be helpful to give an option to resend the pending emails that were sent to the wrong address before.

### PR DESCRIPTION
**Pull request by tarun14110**
Fixes #5577 

**Email content**

Hello student1 In Course1</td></div>,<br> <br> Instructor updated your new email address. It seems you are missing the updates for the course : [idOfTypicalCourse1]Typical Course 1 with 2 Evals. Therefore we have sent you the summary of all feedback sessions for this course.<br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> Closed Session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Sat, 01 Jun 2013, 11:59 PM {Passed}
<br>
To submit feedback for the above session, please go to this Web address: <a href="{Feedback session is closed}">{Feedback session is closed}</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
<br>
<br><br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> Empty session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Sun, 28 Apr 2013, 11:57 PM {Passed}
<br>
To submit feedback for the above session, please go to this Web address: <a href="{Feedback session is closed}">{Feedback session is closed}</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="${app.url}/page/studentFeedbackResultsPage?courseid=idOfTypicalCourse1&fsname=Empty+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt">${app.url}/page/studentFeedbackResultsPage?courseid=idOfTypicalCourse1&fsname=Empty+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt</a>
<br>
<br><br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> First feedback session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Fri, 30 Apr 2027, 11:59 PM
<br>
To submit feedback for the above session, please go to this Web address: <a href="${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=First+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt">${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=First+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
<br>
<br><br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> Grace Period Session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Tue, 28 Apr 2026, 11:59 PM
<br>
To submit feedback for the above session, please go to this Web address: <a href="${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=Grace+Period+Session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt">${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=Grace+Period+Session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
<br>
<br><br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> Second feedback session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Tue, 28 Apr 2026, 11:59 PM
<br>
To submit feedback for the above session, please go to this Web address: <a href="${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=Second+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt">${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=Second+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
<br>
<br><br>
<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> non visible session
<br>&nbsp;&nbsp; <strong>Deadline:</strong> Tue, 28 Apr 2026, 11:00 PM
<br>
To submit feedback for the above session, please go to this Web address: <a href="{Feedback session is closed}">{Feedback session is closed}</a>
<br>
<br>
To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
<br>
<br><br> If you need any help or clarifications regarding TEAMMATES, please email us at ${support.email}<p/>Regards,<br>TEAMMATES Team.

### CODE REVIEW

**Comment by tarun14110** [comment]
screenshot from 2016-07-28 01 30 51

**Comment by damithc** [comment]
`An instructor has updated your email address in the course [Course name:{{course name}}][Course ID: {{courseId}}]. Given below are the relevant links for the course, updated to work with your new email address {{email}}.`

Also include the join link.

**Comment by damithc** [comment]
Note that this option should not be given to the instructor if there are no open/closed sessions in the course. i.e. students haven't been sent an email yet, so there is no need to resend.

**Comment by tarun14110** [comment]
@chowyb please have a look. Ready for review.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 1]
```diff
@@ -86,6 +88,87 @@
...
+        String reportUrl = null;
+        
+        StringBuffer emailBody = new StringBuffer(1000);
+        
+        emailBody.append("Hello " + student.name
+                        + ",<br> <br> An instructor has updated your email address in the course [Course name: "
+                        + course.getName() + "] [Course ID: " + course.getId() + "]. "
+                        + "Given below are the relevant links for the course, updated to work with your new email address "
+                        + student.email);
+
```
Comment (tarun14110) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: @chowyb should I create a new template for this also, instead of doing like this ?

Comment (chowyb) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Yep, putting this in a template would be better.

**Comment by chowyb** [comment]
Is this feature working? The following modal appears when I attempt to save after editing a student's email, but regardless of choice it appears that nothing is done (no saving etc), I'm testing this on the dev server by the way.
popup

**Comment by damithc** [comment]
And the modal dialog looks messed up. Need to adjust alignment spacing etc. :-p

**Comment by damithc** [comment]
Dialog title: `Resend past links to the new email?`
Text: `Do you want to resend past session links of this course to the new email {email}?` 
Buttons: `Yes, save changes and resend links` `No, just save the changes`, `Cancel`

**Comment by tarun14110** [comment]
@chowyb updated, have a look.

**Comment by chowyb** [comment]
Modal looks mostly okay now, but I'm thinking about whether the colours should be different. Although both buttons do save the changes, they are still different in terms of whether an email is sent or not, but I'm concerned if adding different colours may influence the user towards choosing a specific option over the other. @damithc any suggestions here? 

modal

I'll proceed to review for code quality after this has been clarified (and changed if necessary).

File: src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+<p/>
+An instructor has updated your email address in the course [Course name: ${courseName}] [Course ID: ${courseId}].
+Given below are the relevant links for the course, updated to work with your new email address ${userEmail}.
+
+<p/>
+${joinFragment}
+
+<br>
+Below are the Feedback sessions of the course.
```
Comment (chowyb) [inline src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html]: Use "feedback" instead of "Feedback" here.

File: src/main/java/teammates/common/util/Const.java [hunk 3]
```diff
@@ -1172,6 +1172,8 @@ public static final String getjQueryUiFilePath(boolean isDevServer) {
                 + "try again in a few more minutes as the student may still be being saved.";
         
         public static final String STUDENT_EDITED = "The student has been edited successfully";
+        public static final String STUDENT_EDITED_AND_EMAIL_SENT = "The student has been edited successfully."
+                + "And summary of the course has been sent to the new email.";
```
Comment (chowyb) [inline src/main/java/teammates/common/util/Const.java]: Change this to:
```
public static final String STUDENT_EDITED_AND_EMAIL_SENT = "The student has been edited successfully. "
        + "A summary of the course has been sent to the new email.";
```

**Comment by chowyb** [comment]
Some wording changes requested as well.

**Comment by tarun14110** [comment]
@chowyb updated, please have a look.

File: src/main/java/teammates/common/util/Const.java [hunk 4]
```diff
@@ -1210,6 +1210,8 @@ public static final String getjQueryUiFilePath(boolean isDevServer) {
                 + "try again in a few more minutes as the student may still be being saved.";
         
         public static final String STUDENT_EDITED = "The student has been edited successfully";
+        public static final String STUDENT_EDITED_AND_EMAIL_SENT = "The student has been edited successfully. "
+                + "And summary of the course has been sent to the new email.";
```
Comment (chowyb) [inline src/main/java/teammates/common/util/Const.java]: Change this to `"A summary of the course has been sent to the new email."`

**Comment by chowyb** [comment]
Wording change requested.

I also edited the title of this PR (and the related issue) to fix a typo.

**Comment by chowyb** [comment]
@damithc, I'd just like to confirm that the current colouring (as given previously [here](https://github.com/TEAMMATES/teammates/pull/5930#issuecomment-237464847)) is okay.

**Comment by damithc** [comment]
Sorry, missed it earlier. Yes, the colors are ok.  Why do we use light blue (info) instead of dark blue (primary)?

**Comment by tarun14110** [comment]
As we are not only showing some info. We are giving an option, so primate button seems better. Updated to Primary button. Can have a look ?
screenshot from 2016-08-16 14 28 26

**Comment by damithc** [comment]
Let's use the primary color then.

**Comment by wkurniawan07** [comment]
Some info: the status message types (or colors) are designed based on usage, which is why there is no "primary" (what's a primary status?), so we may need to put more thought if we want to introduce this type. Not to mention that it has to be synced with the Java counterpart, `StatusMessageColor`.

@tarun14110 also, typo `Canel` -> `Cancel`, and that `alert` which I think you used for debugging.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 5]
```diff
@@ -87,6 +89,87 @@
...
+                        .toAbsoluteString();
+            } else {
+                reportUrl = "{Feedback session is unpublished}";
+            }
+            
+            linksFragmentValue.append(Templates.populateTemplate(
+                    EmailTemplates.USER_FEEDBACK_SESSION_FRAGMENT_RESEND_ALL_LINKS,
+                    "${feedbackSessionName}", fsa.getFeedbackSessionName(),
+                    "${deadline}", fsa.isClosed() ? TimeHelper.formatTime12H(fsa.getEndTime())
+                                                  + " {Passed}"
```
Comment (chowyb) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Indent this line another 10 spaces to the right (so that it is 8 spaces to the right of `TimeHelper` in the line above)

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 6]
```diff
@@ -87,6 +89,87 @@
     }
     
     /**
+     * Generates the summary of the feedback sessions (in which atleast one
```
Comment (chowyb) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Change `atleast` to `at least`

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 7]
```diff
@@ -57,14 +58,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
             if (isSectionChanged) {
                 logic.validateSectionsAndTeams(Arrays.asList(student), courseId);
             } else if (isTeamChanged) {
                 logic.validateTeams(Arrays.asList(student), courseId);
             }
             
             logic.updateStudent(studentEmail, student);
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            
+            boolean isSendEmail = Boolean.parseBoolean(getRequestParamValue("isSendEmail"));
```
Comment (chowyb) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Can we extract this (and the name used in the JSP files) into a constant in `Const.ParamsNames`?

File: src/main/webapp/js/instructorStudentEdit.js [hunk 8]
```diff
@@ -12,20 +12,45 @@ function readyInstructorStudentEditPage() {
...
         if ($(INSTRUCTOR_STUDENT_EDIT_FORM).attr('editStatus') === 'mustDeleteResponses') {
+            isSubmitFormForEditingTeamName = false;
             event.preventDefault();
 
             var messageText = 'Editing these fields will result in some existing responses from this student '
                               + 'to be deleted. You may download the data before you make the changes. Are '
                               + 'you sure you want to continue?';
             var okCallback = function() {
-                event.target.submit();
+                if ($('#newstudentemail').val() !== $('#studentemail').val() && $('#isAnyEmailSentForTheCourse').val()) {
```
Comment (chowyb) [inline src/main/webapp/js/instructorStudentEdit.js]: Consider extracting this into an explaining variable

File: src/main/webapp/js/instructorStudentEdit.js [hunk 9]
```diff
@@ -12,20 +12,45 @@ function readyInstructorStudentEditPage() {
...
+                    sendEmailToNewEmailOption(event);
+                } else {
+                    event.target.submit();
+                }
             };
 
             BootboxWrapper.showModalConfirmation('Confirm Deletion', messageText, okCallback, null,
                     BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
+        } else if ($('#newstudentemail').val() !== $('#studentemail').val() && $('#isAnyEmailSentForTheCourse').val()) {
```
Comment (chowyb) [inline src/main/webapp/js/instructorStudentEdit.js]: Use an explaining variable here as well

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 10]
```diff
@@ -203,14 +203,31 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
         
+        ______TS("send summary of all feedback sessions of course email");
+        
+        EmailWrapper email = new EmailGenerator().generateFeedbackSessionResendAllLinksEmail(
+                session.getCourseId(), student1);
+
+        subject = String.format(EmailType.STUDENT_EMAIL_CHANGED.getSubject(), course.getName());
+        
+        hasStudent1ReceivedEmail = false;
+        hasInstructor1ReceivedEmail = false;
```
Comment (chowyb) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: No need to set this to false if it's not being used; if other tests are added later which use the same variable name, it can be set to false there instead.

**Comment by tarun14110** [comment]
@chowyb updated. please review.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 11]
```diff
@@ -4,11 +4,14 @@
...
 <%@ attribute name="studentInfoTable" type="teammates.ui.template.StudentInfoTable" required="true" %>
 <%@ attribute name="newEmail" required="true" %>
+<%@ attribute name="anyEmailSentForTheCourse" required="true" %>
 <%@ tag import="teammates.common.util.Const" %>
 <div class="panel panel-primary">
     <div class="panel-body fill-plain">
         <form action="<%=Const.ActionURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_SAVE%>" method="post" id="instructor-student-edit-form" class="form form-horizontal">
             <input type="hidden" name="<%=Const.ParamsNames.COURSE_ID%>" value="${studentInfoTable.course}">
+            <input type="hidden" id = "<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" name="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" value="false">
+            <input type="hidden" id = "isAnyEmailSentForTheCourse" name="isAnyEmailSentForTheCourse" value="${anyEmailSentForTheCourse}">
```
Comment (chowyb) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: Missed this one :( there shouldn't be spaces present in `id = "...`

File: src/main/webapp/js/instructorStudentEdit.js [hunk 12]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
...
+        } else if (isEmailFieldChanged && isAnyEmailSentInThisCourse) {
+            sendEmailToNewEmailOption(event);
         }
     });
     
+    function sendEmailToNewEmailOption(event) {
+        isSubmitFormForEditingEmail = false;
+        event.preventDefault();
+        var messageText = 'Do you want to resend past session links of this course to the new email '
+            + $('#newstudentemail').val() + '?';
```
Comment (chowyb) [inline src/main/webapp/js/instructorStudentEdit.js]: Should be indented 8 spaces here instead of 4

**Comment by tarun14110** [comment]
@chowyb updated.

**Comment by wkurniawan07** [comment]
There are some design/architecture-related improvements needed, so setting the status to `s.Ongoing` first.

File: src/main/java/teammates/common/util/Const.java [hunk 13]
```diff
@@ -800,6 +800,7 @@ public static final String getjQueryUiFilePath(boolean isDevServer) {
         public static final String EMAIL_COURSE = "course";
         public static final String EMAIL_FEEDBACK = "feedback";
         public static final String EMAIL_TYPE = "type";
+        public static final String EMAIL_SEND_CHECK = "isSendEmail";
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Const.java]: Similar to the other PR, drop the `is-` prefix and use all lowercase, i.e `sendemail`. Also, what `sendemail` is an ambiguous parameter; what "email" are we talking about here?

File: src/main/java/teammates/common/util/EmailType.java [hunk 14]
```diff
@@ -13,6 +13,7 @@
     FEEDBACK_CLOSED("TEAMMATES: Feedback session closed [Course: %s][Feedback Session: %s]"),
     FEEDBACK_PUBLISHED("TEAMMATES: Feedback session results published [Course: %s][Feedback Session: %s]"),
     FEEDBACK_UNPUBLISHED("TEAMMATES: Feedback session results unpublished [Course: %s][Feedback Session: %s]"),
+    STUDENT_EMAIL_CHANGED("TEAMMATES: Summary of all Feedback Sessions [Course: %s]"),
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/EmailType.java]: `Summary of course [%s][Course ID: %s]` is more like it, because the course join link is included and it certainly does not fit into the "all feedback sessions" category.

File: src/main/java/teammates/common/util/Templates.java [hunk 15]
```diff
@@ -51,6 +51,10 @@ public static String populateTemplate(String template, String... values) {
                 FileHelper.readResourceFile("userEmailTemplate-feedbackSessionUnpublished.html");
         public static final String USER_PENDING_COMMENTS_CLEARED =
                 FileHelper.readResourceFile("userEmailTemplate-pendingCommentsCleared.html");
+        public static final String USER_FEEDBACK_SESSION_FRAGMENT_RESEND_ALL_LINKS =
+                FileHelper.readResourceFile("userEmailTemplateFragment-feedbackSessionResendAllLinks.html");
+        public static final String USER_FEEDBACK_SESSION_RESEND_ALL_LINKS =
+                FileHelper.readResourceFile("userEmailTemplate-feedbackSessionResendAllLinks.html");
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Templates.java]: The difference between this one and the one above is not immediately clear. Likely the first one should be `FRAGMENT_SINGLE_FEEDBACK_SESSION_LINKS` or alike to depict that it involves the links of one and only one feedback session.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 16]
```diff
@@ -87,6 +89,87 @@
...
+     * Generates the summary of the feedback sessions (in which at least one
+     * email has been sent to students) email for the given {@code courseId} for {@code student}
+     */
+    public EmailWrapper generateFeedbackSessionResendAllLinksEmail(String courseId,
+            StudentAttributes student) {
+        
+        CourseAttributes course = coursesLogic.getCourse(courseId);
+        
+        List<FeedbackSessionAttributes> sessions = new ArrayList<FeedbackSessionAttributes>();
+        List<FeedbackSessionAttributes> fsInCourse = fsDb.getFeedbackSessionsForCourse(courseId);
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Do not communicate with `*Db` directly. Use `fsLogic` which is already defined for this purpose.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 17]
```diff
@@ -87,6 +89,87 @@
     }
     
     /**
+     * Generates the summary of the feedback sessions (in which at least one
+     * email has been sent to students) email for the given {@code courseId} for {@code student}
+     */
+    public EmailWrapper generateFeedbackSessionResendAllLinksEmail(String courseId,
+            StudentAttributes student) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Similar to the one of the previous comments, since this goes beyond all feedback session links (i.e course join link may also be involved), you may want to rename the method and also its header comment.

On a more minor note, `StudentAttributes student` should be fine on the previous line, but this may or may not be relevant once you rename the method.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 18]
```diff
@@ -87,6 +89,87 @@
...
+            }
+        }
+        
+        String submitUrl = null;
+        String reportUrl = null;
+        
+        StringBuffer linksFragmentValue = new StringBuffer(1000);
+        String joinUrl = Config.getAppUrl(student.getRegistrationUrl()).toAbsoluteString();
+        
+        String joinFragmentValue = "";
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: This can be simplified to:
```java
String joinFragmentValue = isYetToJoinCourse(student)
                           ? Templates.populateTemplate(...)
                           : "";
```

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 19]
```diff
@@ -87,6 +89,87 @@
...
+        for (FeedbackSessionAttributes fsa : sessions) {
+            if (fsa.isOpened()) {
+                submitUrl = Config.getAppUrl(Const.ActionURIs.STUDENT_FEEDBACK_SUBMISSION_EDIT_PAGE)
+                        .withCourseId(course.getId())
+                        .withSessionName(fsa.getFeedbackSessionName())
+                        .withRegistrationKey(StringHelper.encrypt(student.key))
+                        .withStudentEmail(student.email)
+                        .toAbsoluteString();
+            } else {
+                submitUrl = "{Feedback session is closed}";
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Similarly here:
```java
String submitUrl = fsa.isOpened()
                   ? Config.getAppUrl(...)
                   : "{Feedback session is closed}";
```

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 20]
```diff
@@ -87,6 +89,87 @@
...
+
+            if (fsa.isPublished()) {
+                reportUrl = Config.getAppUrl(Const.ActionURIs.STUDENT_FEEDBACK_RESULTS_PAGE)
+                        .withCourseId(course.getId())
+                        .withSessionName(fsa.getFeedbackSessionName())
+                        .withRegistrationKey(StringHelper.encrypt(student.key))
+                        .withStudentEmail(student.email)
+                        .toAbsoluteString();
+            } else {
+                reportUrl = "{Feedback session is unpublished}";
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Similarly here:
```java
String reportUrl = fsa.isPublished()
                   ? Config.getAppUrl(...)
                   : "{Feedback session is not yet published}";
```
In addition, do not use "unpublish" because we use it to refer to an action.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 21]
```diff
@@ -87,6 +89,87 @@
...
+        List<FeedbackSessionAttributes> fsInCourse = fsDb.getFeedbackSessionsForCourse(courseId);
+        
+        for (FeedbackSessionAttributes fsa : fsInCourse) {
+            if (!fsa.isPrivateSession() && (fsa.isSentOpenEmail() || fsa.isSentPublishedEmail())) {
+                sessions.add(fsa);
+            }
+        }
+        
+        String submitUrl = null;
+        String reportUrl = null;
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: I believe you don't need to define these variables.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 22]
```diff
@@ -87,6 +89,87 @@
...
+                        .toAbsoluteString();
+            } else {
+                reportUrl = "{Feedback session is unpublished}";
+            }
+            
+            linksFragmentValue.append(Templates.populateTemplate(
+                    EmailTemplates.USER_FEEDBACK_SESSION_FRAGMENT_RESEND_ALL_LINKS,
+                    "${feedbackSessionName}", fsa.getFeedbackSessionName(),
+                    "${deadline}", fsa.isClosed() ? TimeHelper.formatTime12H(fsa.getEndTime())
+                                                            + " {Passed}"
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: This should be fine on the previous line.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 23]
```diff
@@ -1588,6 +1605,19 @@ public void unpublishFeedbackSession(String feedbackSessionName,
         }
     }
     
+    public EmailWrapper sendAllLinksToNewStudentEmail(String courseId,
+            StudentAttributes student) throws EntityDoesNotExistException {
+
+        try {
+            EmailWrapper email = new EmailGenerator().generateFeedbackSessionResendAllLinksEmail(
+                    courseId, student);
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: This should be fine on the previous line.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 24]
```diff
@@ -205,6 +205,23 @@ public FeedbackSessionAttributes copyFeedbackSession(String newFeedbackSessionNa
...
         return viewableSessions;
     }
+    
+    /**
+     * checks if there is any email sent from the course
+     * @param courseId
+     * @param userEmail
+     * @return true if there is any email sent from the course.
+     */
+    public boolean isAnyEmailSentForTheCourse(String courseId) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: is**Any**Email actually sounds misleading; it could well include closing/closed/unpublished email. You may want to rename the method to accurately represent what it does.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 25]
```diff
@@ -205,6 +205,23 @@ public FeedbackSessionAttributes copyFeedbackSession(String newFeedbackSessionNa
...
+        List<FeedbackSessionAttributes> sessions = getFeedbackSessionsForCourse(courseId);
+
+        for (FeedbackSessionAttributes session : sessions) {
+            if (session.isSentOpenEmail() || session.isSentPublishedEmail()) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: I saw this routine somewhere before. Can extract this to a small method in the `FeedbackSessionAttributes` class, like:
```java
public boolean isSentRelevantEmails() { // change the method name as needed
    return isSentOpenEmail() && isSentPublishedEmail();
}
```

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageAction.java [hunk 26]
```diff
@@ -34,9 +34,11 @@ public ActionResult execute() throws EntityDoesNotExistException {
         }
         
         boolean hasSection = logic.hasIndicatedSections(courseId);
+        boolean isAnyEmailSentForTheCourse = logic.isAnyEmailSentForTheCourse(courseId);
         
         InstructorCourseStudentDetailsEditPageData data =
-                new InstructorCourseStudentDetailsEditPageData(account, student, student.email, hasSection);
+                new InstructorCourseStudentDetailsEditPageData(account, student, student.email, hasSection,
+                        isAnyEmailSentForTheCourse);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageAction.java]: Align `[i]sAny...` with `[a]ccount`.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageData.java [hunk 27]
```diff
@@ -6,16 +6,24 @@
 public class InstructorCourseStudentDetailsEditPageData extends InstructorCourseStudentDetailsPageData {
     
     private String newEmail;
+    private boolean isAnyEmailSentForTheCourse;
 
     public InstructorCourseStudentDetailsEditPageData(
-            AccountAttributes account, StudentAttributes student, boolean hasSection) {
-        this(account, student, student.email, hasSection);
+            AccountAttributes account, StudentAttributes student, boolean hasSection,
+            boolean isAnyEmailSentForTheCourse) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageData.java]: This should be fine on the previous line.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 28]
```diff
@@ -57,14 +58,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
             } else if (isTeamChanged) {
                 logic.validateTeams(Arrays.asList(student), courseId);
             }
             
             logic.updateStudent(studentEmail, student);
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            
+            boolean isSendEmail = Boolean.parseBoolean(getRequestParamValue(Const.ParamsNames.EMAIL_SEND_CHECK));
+            if (isEmailChanged && isSendEmail) {
+                FeedbackSessionsLogic.inst().sendAllLinksToNewStudentEmail(courseId, student);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Do not call `FeedbackSessionsLogic` directly here. Action classes should communicate via the API class `Logic`, i.e `logic.sendAllLinks...`.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 29]
```diff
@@ -57,14 +58,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
+            }
+            if (isSendEmail) {
+                statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED_AND_EMAIL_SENT,
+                        StatusMessageColor.SUCCESS));
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Align `[S]tatusMessageColor` with `[C]onst.StatusMessages.*`

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 30]
```diff
@@ -78,8 +90,10 @@ public ActionResult execute() throws EntityDoesNotExistException {
             setStatusForException(e);
             String newEmail = student.email;
             student.email = studentEmail;
+            boolean isAnyEmailSentForTheCourse = logic.isAnyEmailSentForTheCourse(courseId);
             InstructorCourseStudentDetailsEditPageData data =
-                    new InstructorCourseStudentDetailsEditPageData(account, student, newEmail, hasSection);
+                    new InstructorCourseStudentDetailsEditPageData(account, student, newEmail, hasSection,
+                            isAnyEmailSentForTheCourse);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Align `[i]sAny...` with `[a]ccount`.

File: src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html [hunk 31]
```diff
@@ -0,0 +1,20 @@
...
+
+<br>
+Below are the feedback sessions of the course.
+<br>
+
+<p/>
+${linksFragment}
+
+<p/>
+If you need any help or clarifications regarding TEAMMATES, please email us at ${supportEmail}
```
Comment (wkurniawan07) [inline src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html]: Close this sentence with a period.

File: src/main/resources/userEmailTemplateFragment-feedbackSessionResendAllLinks.html [hunk 32]
```diff
@@ -0,0 +1,10 @@
+<br>
+<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> ${feedbackSessionName}
+<br>&nbsp;&nbsp; <strong>Deadline:</strong> ${deadline}
+<br>
+To submit feedback for the above session, please go to this Web address: <a href="${submitUrl}">${submitUrl}</a>
+<br>
+<br>
+To view the responses for this session, please go to this Web address: <a href="${reportUrl}">${reportUrl}</a>
```
Comment (wkurniawan07) [inline src/main/resources/userEmailTemplateFragment-feedbackSessionResendAllLinks.html]: (applies to both `submitUrl` and `reportUrl`) Here, if either one of the URLs are things like `(Feedback session is closed)`, then the anchor element will have that as the `href` attribute as well, which is not good because it leads nowhere. The wrapping anchor element should be moved to the Java code as well.

File: src/main/webapp/js/common.js [hunk 33]
```diff
@@ -928,7 +929,9 @@ function hideSingleCollapse(e) {
 var BootboxWrapper = {
     DEFAULT_OK_TEXT: 'OK',
     DEFAULT_CANCEL_TEXT: 'Cancel',
-
+    DEFAULT_YES_TEXT: 'YES',
+    DEFAULT_NO_TEXT: 'NO',
```
Comment (wkurniawan07) [inline src/main/webapp/js/common.js]: "Yes" and "No" need not be in all uppercase, right?

File: src/main/webapp/js/common.js [hunk 34]
```diff
@@ -92,8 +92,9 @@ var StatusType = {
     INFO: 'info',
     WARNING: 'warning',
     DANGER: 'danger',
+    PRIMARY: 'primary',
     isValidType: function(type) {
-        return type === StatusType.SUCCESS || type === StatusType.INFO
+        return type === StatusType.SUCCESS || type === StatusType.INFO || type === StatusType.PRIMARY
```
Comment (wkurniawan07) [inline src/main/webapp/js/common.js]: If you define a new status type here, define one similarly in `StatusMessageColor` enum in `Const` class.

File: src/main/webapp/js/instructorStudentEdit.js [hunk 35]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
 function readyInstructorStudentEditPage() {
     
     $(INSTRUCTOR_STUDENT_EDIT_FORM).on('submit', function(event) {
+        
+        var isEmailFieldChanged = $('#newstudentemail').val() !== $('#studentemail').val();
+        var isAnyEmailSentInThisCourse = $('#isAnyEmailSentForTheCourse').val();
+        
         if ($(INSTRUCTOR_STUDENT_EDIT_FORM).attr('editStatus') === 'mustDeleteResponses') {
+            isSubmitFormForEditingTeamName = false;
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: Two questions here:
- Where is this variable defined?
- Where is this variable used?

File: src/main/webapp/js/instructorStudentEdit.js [hunk 36]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
...
 
             BootboxWrapper.showModalConfirmation('Confirm Deletion', messageText, okCallback, null,
                     BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
+        } else if (isEmailFieldChanged && isAnyEmailSentInThisCourse) {
+            sendEmailToNewEmailOption(event);
         }
     });
     
+    function sendEmailToNewEmailOption(event) {
+        isSubmitFormForEditingEmail = false;
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: Similar two questions as before apply for this.

File: src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java [hunk 37]
```diff
@@ -73,10 +73,19 @@ private void fillStudentDetailsForm(String studentName, String teamName, String
...
+                clickAndConfirm(submitButton);
+            }
+            
         } else {
             // if team name is edited, the confirmation dialog will pop up
-            clickAndConfirm(submitButton);
+            if (studentEmail == null) {
+                clickAndConfirm(submitButton);
+            } else {
+                clickAndConfirmTwoTimes(submitButton);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java]: Rather than doing this, why not call `clickAndConfirm` similarly and handle the second modal separately? That way you can simplify the routine:
```java
clickAndConfirm(submitButton);
if (studentEmail != null) {
    clickCancelOnModal(); // implement accordingly
}
```

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 38]
```diff
@@ -4,11 +4,14 @@
...
 <%@ attribute name="studentInfoTable" type="teammates.ui.template.StudentInfoTable" required="true" %>
 <%@ attribute name="newEmail" required="true" %>
+<%@ attribute name="anyEmailSentForTheCourse" required="true" %>
 <%@ tag import="teammates.common.util.Const" %>
 <div class="panel panel-primary">
     <div class="panel-body fill-plain">
         <form action="<%=Const.ActionURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_SAVE%>" method="post" id="instructor-student-edit-form" class="form form-horizontal">
             <input type="hidden" name="<%=Const.ParamsNames.COURSE_ID%>" value="${studentInfoTable.course}">
+            <input type="hidden" id="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" name="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" value="false">
+            <input type="hidden" id="isAnyEmailSentForTheCourse" name="isAnyEmailSentForTheCourse" value="${anyEmailSentForTheCourse}">
```
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: Is this `input` used to pass the true/false value to the server? If not, whatever's stored here can be moved to javascript instead.

File: src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html [hunk 39]
```diff
@@ -0,0 +1,56 @@
...
+To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
+<br>
+<br><br>
+<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> First feedback session
+<br>&nbsp;&nbsp; <strong>Deadline:</strong> Fri, 30 Apr 2027, 11:59 PM
+<br>
+To submit feedback for the above session, please go to this Web address: <a href="${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=First+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt">${app.url}/page/studentFeedbackSubmissionEditPage?courseid=idOfTypicalCourse1&fsname=First+feedback+session&key=${regkey.enc}&studentemail=student1InCourse1%40gmail.tmt</a>
+<br>
+<br>
+To view the responses for this session, please go to this Web address: <a href="{Feedback session is unpublished}">{Feedback session is unpublished}</a>
```
Comment (wkurniawan07) [inline src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html]: Is it possible to have a not-yet-opened session and a published session as well so that we can have complete branch coverage?

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java (hunk 24 above)
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: This should also be propagated to all methods/parameters where is**Any**Email is part of the name.

**Comment by wkurniawan07** [comment]
@tarun14110 let's continue on this one?

**Comment by tarun14110** [comment]
@wkurniawan07 I am having mid-sem exams, Can I continue this after 2 days ?

**Comment by wkurniawan07** [comment]
Hi @tarun14110, any updates on this PR?

**Comment by wkurniawan07** [comment]
Hi @tarun14110, any updates on this PR?

**Comment by wkurniawan07** [comment]
@tarun14110 sorry for the delay, because this is one of the PRs that will take some time to review. I will now be continuing with the review.

File: .settings/com.google.appengine.eclipse.core.prefs [hunk 40]
```diff
@@ -3,6 +3,7 @@ filesCopiedToWebInfLib=appengine-api-1.0-sdk-1.9.27.jar|appengine-api-labs.jar|a
 gaeDatanucleusVersion=v1
 gaeDeployDialogSettings=
 gaeIsEclipseDefaultInstPath=true
+gaeLaunchAppInBrowser=true
```
Comment (wkurniawan07) [inline .settings/com.google.appengine.eclipse.core.prefs]: This should not be committed.

File: src/main/java/teammates/common/util/Const.java [hunk 41]
```diff
@@ -1250,6 +1251,8 @@ public static final String getjQueryUiFilePath(boolean isDevServer) {
                 + "try again in a few more minutes as the student may still be being saved.";
         
         public static final String STUDENT_EDITED = "The student has been edited successfully";
+        public static final String STUDENT_EDITED_AND_EMAIL_SENT = "The student has been edited successfully. "
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Const.java]: Make this `STUDENT_EDITED + " A summary ..."`? If you need the `STUDENT_EDIT` variable to contain period, go ahead and change it.

File: src/main/java/teammates/logic/api/Logic.java [hunk 42]
```diff
@@ -2487,6 +2492,15 @@ public void sendCommentNotification(String courseId) {
...
         commentsLogic.sendCommentNotification(courseId);
     }
+    
+    /**
+     * This method sends all links (sent previously in the course) to
+     * the new email address.
+     */
+    public EmailWrapper sendAllLinksToNewStudentEmail(String courseId,
+            StudentAttributes student) throws EntityDoesNotExistException {
+        return feedbackSessionsLogic.sendAllLinksToNewStudentEmail(courseId, student);
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/Logic.java]: Do non-null assertions for both parameters `courseId` and `student`.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 43]
```diff
@@ -205,6 +205,23 @@ public FeedbackSessionAttributes copyFeedbackSession(String newFeedbackSessionNa
 
         return viewableSessions;
     }
+    
+    /**
+     * checks if there is any email sent from the course
+     * @param courseId
+     * @param userEmail
+     * @return true if there is any email sent from the course.
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Update the javadoc as well. It is no longer **any** email, and the `userEmail` param is not used.

File: src/main/webapp/js/common.js [hunk 44]
```diff
@@ -959,9 +960,11 @@ function hideSingleCollapse(e) {
  *  Bootstrap modals"
  */
 var BootboxWrapper = {
-    DEFAULT_OK_TEXT: 'OK',
+    DEFAULT_OK_TEXT: 'Ok',
```
Comment (wkurniawan07) [inline src/main/webapp/js/common.js]: You do not need to change this. "OK" is commonly used in all variants "OK", "Ok", "ok".

File: src/main/webapp/js/instructorStudentEdit.js [hunk 45]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
 function readyInstructorStudentEditPage() {
     
     $(INSTRUCTOR_STUDENT_EDIT_FORM).on('submit', function(event) {
+        
+        var isEmailFieldChanged = $('#newstudentemail').val() !== $('#studentemail').val();
+        var isAnyEmailSentInThisCourse = $('#isOpenOrPublishedEmailSentForTheCourse').val();
+        
         if ($(INSTRUCTOR_STUDENT_EDIT_FORM).attr('editStatus') === 'mustDeleteResponses') {
+            isSubmitFormForEditingTeamName = false;
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: Is this variable defined/used anywhere?

File: src/main/webapp/js/instructorStudentEdit.js [hunk 46]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
...
 
             BootboxWrapper.showModalConfirmation('Confirm Deletion', messageText, okCallback, null,
                     BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
+        } else if (isEmailFieldChanged && isAnyEmailSentInThisCourse) {
+            sendEmailToNewEmailOption(event);
         }
     });
     
+    function sendEmailToNewEmailOption(event) {
+        isSubmitFormForEditingEmail = false;
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: Is this variable defined/used anywhere?

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 47]
```diff
@@ -87,6 +87,76 @@
...
+        
+        String joinFragmentValue = isYetToJoinCourse(student)
+                                   ? Templates.populateTemplate(EmailTemplates.FRAGMENT_STUDENT_COURSE_JOIN,
+                                           "${joinUrl}", joinUrl,
+                                           "${courseName}", course.getName())
+                                   : "";
+        
+        for (FeedbackSessionAttributes fsa : sessions) {
+            String submitUrl = fsa.isOpened()
+                        ? "<a href = \"" + Config.getAppUrl(Const.ActionURIs.STUDENT_FEEDBACK_SUBMISSION_EDIT_PAGE)
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: No space surrounding the `=` after `href`. Similarly for the one in `reportUrl`.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 48]
```diff
@@ -87,6 +87,76 @@
...
+                            .withCourseId(course.getId())
+                            .withSessionName(fsa.getFeedbackSessionName())
+                            .withRegistrationKey(StringHelper.encrypt(student.key))
+                            .withStudentEmail(student.email)
+                            .toAbsoluteString() + "\">link<//a>"
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: &lt;~~/~~/a&gt;, similarly for the one in `reportUrl`.

Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Also, "please go to this web address: link" is not how links are being treated in other emails. The "link" should be a carbon copy of the href attribute. Similarly for the one in `reportUrl`.

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 49]
```diff
@@ -87,6 +87,76 @@
...
+                                .withRegistrationKey(StringHelper.encrypt(student.key))
+                                .withStudentEmail(student.email)
+                                .toAbsoluteString() + "\">link<//a>"
+                        : "(Feedback session is not yet published)";
+            
+            linksFragmentValue.append(Templates.populateTemplate(
+                    EmailTemplates.FRAGMENT_SINGLE_FEEDBACK_SESSION_LINKS,
+                    "${feedbackSessionName}", fsa.getFeedbackSessionName(),
+                    "${deadline}", fsa.isClosed() ? TimeHelper.formatTime12H(fsa.getEndTime()) + " (Passed)"
+                                                  : TimeHelper.formatTime12H(fsa.getEndTime()),
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: To avoid repetition, `TimeHelper.formatTime12H(fsa.getEndTime()) + (fsa.isClosed() ? " (Passed)" : "")`

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 50]
```diff
@@ -87,6 +87,76 @@
     }
     
     /**
+     * Generates the summary of the feedback sessions (in which at least one
+     * email has been sent to students) email for the given {@code courseId} for {@code student}
+     */
+    public EmailWrapper generateFeedbackSessionResendSummaryOfCourse(String courseId, StudentAttributes student) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: `generateFeedbackSessionsSummaryOfCourse` is a more accurate name.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 51]
```diff
@@ -1587,6 +1604,18 @@ public void unpublishFeedbackSession(String feedbackSessionName,
         }
     }
     
+    public EmailWrapper sendAllLinksToNewStudentEmail(String courseId,
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: This method name is somewhat confusing. Something like "sendFeedbackSessionsSummaryOfCourseToNewStudentEmail" is better, albeit may be a bit too long.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 52]
```diff
@@ -57,14 +57,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
             if (isSectionChanged) {
                 logic.validateSectionsAndTeams(Arrays.asList(student), courseId);
             } else if (isTeamChanged) {
                 logic.validateTeams(Arrays.asList(student), courseId);
             }
             
             logic.updateStudent(studentEmail, student);
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            
+            boolean isSendEmail = Boolean.parseBoolean(getRequestParamValue(Const.ParamsNames.EMAIL_SEND_CHECK));
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: There is an abstraction for this: `getRequestParamAsBoolean`.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 53]
```diff
@@ -4,11 +4,14 @@
 <%@ taglib tagdir="/WEB-INF/tags" prefix="t" %>
 <%@ attribute name="studentInfoTable" type="teammates.ui.template.StudentInfoTable" required="true" %>
 <%@ attribute name="newEmail" required="true" %>
+<%@ attribute name="anyEmailSentForTheCourse" required="true" %>
```
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: Similarly here, no longer **any**Email.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 54]
```diff
@@ -4,11 +4,14 @@
...
 <%@ tag import="teammates.common.util.Const" %>
 <div class="panel panel-primary">
     <div class="panel-body fill-plain">
         <form action="<%=Const.ActionURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_SAVE%>" method="post" id="instructor-student-edit-form" class="form form-horizontal">
             <input type="hidden" name="<%=Const.ParamsNames.COURSE_ID%>" value="${studentInfoTable.course}">
+            <input type="hidden" id="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" name="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" value="false">
+            <input type="hidden" id="isOpenOrPublishedEmailSentForTheCourse" name="isOpenOrPublishedEmailSentForTheCourse" value="${openOrPublishedEmailSentForTheCourse}">
```
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: For both of these, are the IDs necessary?
For the second only: can `isOpenOrPublishedEmailSendForCourse` (1) be abstracted to `Const.ParamsNames`, (2) in lowercase, (3) shorter, e.g `openorpublishedemailsent`?

File: src/main/webapp/js/instructorStudentEdit.js [hunk 55]
```diff
@@ -11,21 +11,51 @@ $(document).ready(function() {
 function readyInstructorStudentEditPage() {
     
     $(INSTRUCTOR_STUDENT_EDIT_FORM).on('submit', function(event) {
+        
+        var isEmailFieldChanged = $('#newstudentemail').val() !== $('#studentemail').val();
+        var isAnyEmailSentInThisCourse = $('#isOpenOrPublishedEmailSentForTheCourse').val();
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: Similarly here, no longer **Any**Email.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 56]
```diff
@@ -644,6 +655,17 @@ public AppPage clickAndConfirm(WebElement elementToClick) {
     }
     
     /**
+     * Clicks the element and clicks 'Yes' in the follow up dialog box.
+     * Fails if there is no dialog box.
+     * @return the resulting page.
+     */
+    public AppPage clickNoOnModal() {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I may be wrong, but it looks like these two methods you added before are no longer used?

**Comment by damithc** [comment]
@tarun14110 shall we finish this one too?

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag (hunk 54 above)
Comment (tarun14110) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: Id is necessary for only second one, As we are using in js the second variable, we cannot abstract name ?

**Comment by tarun14110** [comment]
@damithc sorry for being so late. I will start working on pending PR's.

**Comment by damithc** [comment]
Let us know when ready to review.

**Comment by tarun14110** [comment]
@wkurniawan07 please review again. I updated changes.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 57]
```diff
@@ -9,6 +9,8 @@
     <div class="panel-body fill-plain">
         <form action="<%=Const.ActionURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_SAVE%>" method="post" id="instructor-student-edit-form" class="form form-horizontal">
             <input type="hidden" name="<%=Const.ParamsNames.COURSE_ID%>" value="${studentInfoTable.course}">
+            <input type="hidden" name="<%=Const.ParamsNames.EMAIL_SEND_CHECK%>" value="false">
+            <input type="hidden" id="openorpublishedemailsent" name="openorpublishedemailsent" value="${openOrPublishedEmailSentForTheCourse}">
```
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: I recall seeing `openorpublishedemailsent` somewhere in `Const.ParamsNames.*`. Let's reuse that constant.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 58]
```diff
@@ -205,6 +205,22 @@ public FeedbackSessionAttributes copyFeedbackSession(String newFeedbackSessionNa
 
         return viewableSessions;
     }
+    
+    /**
+     * checks if there is any email sent from the course
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Again, no longer **any** email.

File: src/main/java/teammates/logic/api/Logic.java [hunk 59]
```diff
@@ -2488,6 +2493,17 @@ public void sendCommentNotification(String courseId) {
         Assumption.assertNotNull(ERROR_NULL_PARAMETER, courseId);
         commentsLogic.sendCommentNotification(courseId);
     }
+    
+    /**
+     * This method sends all links (sent previously in the course) to
+     * the new email address.
+     */
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/Logic.java]: Move this documentation to the method in `feedbackSessionsLogic` instead. Also, some changes possible:
- Remove ~~This method~~
- Sends "all links": what is "all links"? Can be more specific here.
- Add `@param` documentation for all parameters used.
- This method (and the one in `FeedbackSessionsLogic` does not look like it need to return anything. If that is the case, make it a `void` method.

File: src/main/java/teammates/common/util/Const.java [hunk 60]
```diff
@@ -794,6 +794,8 @@ public static final String getjQueryUiFilePath(boolean isDevServer) {
         public static final String EMAIL_COURSE = "course";
         public static final String EMAIL_FEEDBACK = "feedback";
         public static final String EMAIL_TYPE = "type";
+        public static final String EMAIL_SEND_CHECK = "sessionsummarysendemail";
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Const.java]: `EMAIL_SEND_CHECK` is quite vague. If it is specifically about session summary, it should be reflected in the variable name.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 61]
```diff
@@ -57,14 +57,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
             if (isSectionChanged) {
                 logic.validateSectionsAndTeams(Arrays.asList(student), courseId);
             } else if (isTeamChanged) {
                 logic.validateTeams(Arrays.asList(student), courseId);
             }
             
             logic.updateStudent(studentEmail, student);
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            
+            boolean isSendEmail = getRequestParamAsBoolean(Const.ParamsNames.EMAIL_SEND_CHECK);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Similarly, `isSendEmail` is also vague. It is specifically about session summary and thus the variable name should capture it.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 62]
```diff
@@ -57,14 +57,25 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
+            if (isEmailChanged && isSendEmail) {
+                logic.sendFeedbackSessionsSummaryOfCourseToNewStudentEmail(courseId, student);
+            }
+            if (isSendEmail) {
+                statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED_AND_EMAIL_SENT,
+                                                   StatusMessageColor.SUCCESS));
+            } else {
+                statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            }
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: This if-else block can be simplified:
```java
statusToUser.add(new StatusMessage(isSendEmail ? ... : ... , StatusMessageColor.SUCCESS));
```
If the line becomes too long you can separate the `StatusMessage` variable out, or any other methods you can think of.

File: src/main/webapp/js/common.js [hunk 63]
```diff
@@ -997,7 +1000,7 @@ var BootboxWrapper = {
      * Custom confirmation dialog to replace default confirm() function
      * Required params: titleText, messageText and okCallback
      * Optional params: cancelCallBack (defaults to null)
-     *                  okButtonText (defaults to "OK")
+     *                  okButtonText (defaults to "Ok")
```
Comment (wkurniawan07) [inline src/main/webapp/js/common.js]: Revert this one as well.

File: src/main/webapp/js/instructorStudentEdit.js [hunk 64]
```diff
@@ -11,21 +11,49 @@ $(document).ready(function() {
...
                     BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
+        } else if (isEmailFieldChanged && isOpenOrPublishedEmailSentInThisCourse) {
+            sendEmailToNewEmailOption(event);
         }
     });
     
+    function sendEmailToNewEmailOption(event) {
+        event.preventDefault();
+        var messageText = 'Do you want to resend past session links of this course to the new email '
+                + $('#newstudentemail').val() + '?';
```
Comment (wkurniawan07) [inline src/main/webapp/js/instructorStudentEdit.js]: `$('#newstudentemail').val()` is called before; it can be a parameter of the function `sendEmailToNewEmailOption` instead.

File: src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html [hunk 65]
```diff
@@ -75,14 +75,6 @@
...
   </h1>
   <br>
-  <div id="student-motd-wrapper">
-    <script>
-      var motdUrl = window.location.origin + '/${studentmotd.url}';
-    </script>
-    <script defer="" src="/js/studentMotd.js" type="text/javascript">
-    </script>
-    ${studentmotd.container}
-  </div>
```
Comment (wkurniawan07) [inline src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html]: This removal should not happen. Is this done by God mode?

File: src/main/java/teammates/logic/core/EmailGenerator.java [hunk 66]
```diff
@@ -87,6 +87,79 @@
     }
     
     /**
+     * Generates the summary of the feedback sessions (in which at least one
+     * email has been sent to students) email for the given {@code courseId} for {@code student}
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailGenerator.java]: Some changes possible:
- Generates the email containing the summary of ...
- Remove ~~(in which at least ... students)~~ because this is the call-site condition, and the method should be independent of it.
- Add `@param` documentation for both the parameters.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag (hunk 57 above)
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: Also, `value="{openOrPublishedEmailSentForTheCourse}"` does not seem right. You would see in the HTML test file that this converts to `value=""` which should not be the case.

**Comment by wkurniawan07** [comment]
@tarun14110 please resolve the merge conflicts properly before pushing to GitHub. Eclipse should be able to tell if there are compile errors.

**Comment by tarun14110** [comment]
@wkurniawan07 please review again.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 67]
```diff
@@ -57,14 +57,24 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
             } else if (isTeamChanged) {
                 logic.validateTeams(Arrays.asList(student), courseId);
             }
             
             logic.updateStudent(studentEmail, student);
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            
+            boolean isSessionSummarySendEmail = getRequestParamAsBoolean(Const.ParamsNames.SESSION_SUMMARY_EMAIL_SEND_CHECK);
+            if (isEmailChanged && isSessionSummarySendEmail) {
+                logic.sendFeedbackSessionsSummaryOfCourseToNewStudentEmail(courseId, student);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Instead of having to connect to logic, simply write the functions to generate and send the email here:
```java
try {
    EmailWrapper email = new EmailGenerator().generateFeedbackSessionSummaryOfCourse(courseId, student);
    new EmailSender().sendEmail(email);
} catch (Exception e) {
    log.severe(...); // write an appropriate logging message
}
```
This way there is no need for `Logic` and `FeedbackSessionsLogic` to be bloated with email-sending functions.

File: src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag [hunk 68]
```diff
@@ -4,11 +4,14 @@
...
 <%@ attribute name="studentInfoTable" type="teammates.ui.template.StudentInfoTable" required="true" %>
 <%@ attribute name="newEmail" required="true" %>
+<%@ attribute name="openOrPublishedEmailSentForTheCourse" required="true" %>
 <%@ tag import="teammates.common.util.Const" %>
 <div class="panel panel-primary">
     <div class="panel-body fill-plain">
         <form action="<%=Const.ActionURIs.INSTRUCTOR_COURSE_STUDENT_DETAILS_EDIT_SAVE%>" method="post" id="instructor-student-edit-form" class="form form-horizontal">
             <input type="hidden" name="<%=Const.ParamsNames.COURSE_ID%>" value="${studentInfoTable.course}">
+            <input type="hidden" name="<%=Const.ParamsNames.SESSION_SUMMARY_EMAIL_SEND_CHECK %>" value="false">
+            <input type="hidden" id="openorpublishedemailsent" name="openorpublishedemailsent" value="${openOrPublishedEmailSentForTheCourse}">
```
Comment (wkurniawan07) [inline src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag]: `openorpublishedemailsent` has been defined in `Const.ParamsNames`. Re-use that constant instead.

File: src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java (hunk 37 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java]: Take a look at my previous comment. If anything, it is because this method looks hackish and too retrofitted for this specific purpose.

**Comment by wkurniawan07** [comment]
Hi @tarun14110 let's continue working on this?

**Comment by damithc** [comment]
@tarun14110 reminder

**Comment by tarun14110** [comment]
Apology for being so late. I will update the suggested changes by tomorrow.

**Comment by damithc** [comment]
@tarun14110 let us know when ready for review again

**Comment by damithc** [comment]
@tarun14110 we really need to finish this PR as it's blocking several other things. Would you like someone to take over the PR and continue?

**Comment by tarun14110** [comment]
@damithc PR is ready for review. I was just waiting for the wkurniawan response on my above comment. If above my comment seems fine then the PR is ready for review.

**Comment by tarun14110** [comment]
Instead of reply to his review comment, I by mistake put a new review comment, so may be that's why he didn't get notification. I am replying to his comment again. Please put this PR on review.

File: src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java (hunk 37 above)
Comment (tarun14110) [inline src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java]: `waitForModalToDisappear()` in `waitForConfirmationModalAndClickOk()` is causing the issue there. As whenever first modal disappears the second modal appear, that time `waitForModalToDisappear()` keep on waiting to disappear which will not gonna happen.

Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java]: I see what you mean. Then why don't we implement a variant of `clickAndConfirm` that does _not_ wait for that disappearance?
```java
clickAndConfirmWithoutWaitingForModalDisappearance(submitButton); // implement accordingly
if (studentEmail != null) {
    clickNoOnModal(); // implement accordingly
}
```

**Comment by tarun14110** [comment]
@wkurniawan07 ready for review

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 69]
```diff
@@ -199,6 +199,22 @@ public FeedbackSessionAttributes copyFeedbackSession(String newFeedbackSessionNa
 
         return viewableSessions;
     }
+    
+    /**
+     * checks if there is open or published email sent from the course
+     * @param courseId
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Two issues here:
- "Checks if ..." can be omitted as the `@return` param already explains it.
- Again, `@param courseId` has no value add. Add a description to the parameter.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 70]
```diff
@@ -67,11 +70,21 @@ public ActionResult execute() throws EntityDoesNotExistException {
             
             logic.updateStudent(studentEmail, student);
             
+            boolean isSessionSummarySendEmail = getRequestParamAsBoolean(Const.ParamsNames.SESSION_SUMMARY_EMAIL_SEND_CHECK);
             if (isEmailChanged) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Something is wrong here. It looks like the value `isSessionSummarySendEmail` is not used?

File: src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html [hunk 71]
```diff
@@ -0,0 +1,21 @@
+<p>Hello ${userName},</p>
+
+An instructor has updated your email address in the course [Course name: ${courseName}] [Course ID: ${courseId}].
+Given below are the relevant links for the course, updated to work with your new email address ${userEmail}.
+
+<p>
+	${joinFragment}
```
Comment (wkurniawan07) [inline src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html]: Use 4 spaces instead of tabs for indentation. Applies to this entire HTML file.

File: src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html [hunk 72]
```diff
@@ -0,0 +1,21 @@
+<p>Hello ${userName},</p>
+
+An instructor has updated your email address in the course [Course name: ${courseName}] [Course ID: ${courseId}].
+Given below are the relevant links for the course, updated to work with your new email address ${userEmail}.
```
Comment (wkurniawan07) [inline src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html]: These two lines should be wrapped with `<p>...</p>` as well.

Comment (wkurniawan07) [inline src/main/resources/userEmailTemplate-feedbackSessionResendAllLinks.html]: These two lines should be wrapped with `<p>...</p>` as well.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 73]
```diff
@@ -201,6 +201,22 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
         assertTrue(hasStudent1ReceivedEmail);
         assertTrue(hasInstructor1ReceivedEmail);
         
+        ______TS("send summary of all feedback sessions of course email");
+        
+        EmailWrapper email = new EmailGenerator().generateFeedbackSessionSummaryOfCourse(
+                session.getCourseId(), student1);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: This should be fine on the previous line.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 74]
```diff
@@ -209,7 +225,7 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
         time.set(Calendar.HOUR_OF_DAY, 5);
         time.set(Calendar.MINUTE, 30);
         time.set(Calendar.YEAR, 2016);
-        EmailWrapper email = new EmailGenerator()
+        email = new EmailGenerator()
                 .generateFeedbackSubmissionConfirmationEmailForStudent(session, student1, time);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: This one as well.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 75]
```diff
@@ -284,6 +284,27 @@ public void waitForConfirmationModalAndClickOk() {
...
+        WebElement noButton = browser.driver.findElement(By.cssSelector("[data-bb-handler='no']"));
+        waitForElementToBeClickable(noButton);
+        click(noButton);
+        waitForModalToDisappear();
+    }
+    
+    /**
+     * Waits for a confirmation modal to appear and click the confirm button, but doesn't wait for modal to disappear
+     */
+    public void waitForConfirmationModalAndClickOkWithoutWaitingForModalDisappearance() {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: This method is only called once in `clickAndConfirmWithoutWaitingForModalDisappearance`, right? Then there is no need to separate it; just move everything to `clickAndConfirmWithoutWaitingForModalDisappearance`.

**Comment by tarun14110** [comment]
@wkurniawan07 ready for review.

File: src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditSaveActionTest.java [hunk 76]
```diff
@@ -70,7 +71,9 @@ public void testExecuteAndPostProcess() throws Exception {
                      r.getDestinationWithParams());
         
         assertFalse(r.isError);
-        assertEquals(Const.StatusMessages.STUDENT_EDITED, r.getStatusMessage());
+        assertEquals(Const.StatusMessages.STUDENT_EDITED_AND_EMAIL_SENT, r.getStatusMessage());
+        
+        verifyNumberOfEmailsSent(a, 1);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditSaveActionTest.java]: Checking just the email amount is insufficient. Check also that the subject and the recipient is correct.

File: src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditSaveActionTest.java [hunk 77]
```diff
@@ -58,7 +58,8 @@ public void testExecuteAndPostProcess() throws Exception {
                 Const.ParamsNames.STUDENT_NAME, student1InCourse1.name,
                 Const.ParamsNames.NEW_STUDENT_EMAIL, newStudentEmail,
                 Const.ParamsNames.COMMENTS, newStudentComments,
-                Const.ParamsNames.TEAM_NAME, newStudentTeam
+                Const.ParamsNames.TEAM_NAME, newStudentTeam,
+                Const.ParamsNames.SESSION_SUMMARY_EMAIL_SEND_CHECK, "true"
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditSaveActionTest.java]: Check also that even with this parameter set to `true`, requests that do not change the student email will not end up sending the email.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 78]
```diff
@@ -659,6 +670,21 @@ public AppPage clickAndConfirm(WebElement elementToClick) {
...
+     * @return the resulting page.
+     */
+    public AppPage clickAndConfirmWithoutWaitingForModalDisappearance(WebElement elementToClick) {
+        click(elementToClick);
+        waitForModalPresence();
+        WebElement okayButton = browser.driver.findElement(By.className("modal-btn-ok"));
+        waitForElementToBeClickable(okayButton);
+        click(okayButton);
+        waitForPageToLoad();
+        return this;
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Is it necessary to return the page object?

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 79]
```diff
@@ -659,6 +670,21 @@ public AppPage clickAndConfirm(WebElement elementToClick) {
...
+     * Fails if there is no dialog box.
+     * @return the resulting page.
+     */
+    public AppPage clickAndConfirmWithoutWaitingForModalDisappearance(WebElement elementToClick) {
+        click(elementToClick);
+        waitForModalPresence();
+        WebElement okayButton = browser.driver.findElement(By.className("modal-btn-ok"));
+        waitForElementToBeClickable(okayButton);
+        click(okayButton);
+        waitForPageToLoad();
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: There should not be a new page load here, so this wait should not be necessary.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 80]
```diff
@@ -67,11 +70,24 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
+                        emailSender.sendEmail(email);
+                    } catch (Exception e) {
+                        log.severe("Error while sending session summary email"
+                                    + TeammatesException.toStringWithStackTrace(e));
+                    }
+                }
             }
             
-            statusToUser.add(new StatusMessage(Const.StatusMessages.STUDENT_EDITED, StatusMessageColor.SUCCESS));
+            statusToUser.add(new StatusMessage(isSessionSummarySendEmail
```
Comment (tarun14110) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: Yeah, you are right. I missed `isEmailChanged` condition. updated that now.

**Comment by tarun14110** [comment]
@wkurniawan07 updated

**Comment by damithc** [comment]
@tarun14110 can you confirm that the email contains only the following links?
* Submission links of only the sessions that are open/closed (but not awaiting)
* Results links of only the sessions that have been published

File: src/main/java/teammates/logic/api/EmailGenerator.java [hunk 81]
```diff
@@ -94,6 +94,81 @@
...
+            if (fsa.isOpened()) {
+                String submitUrl = Config.getAppUrl(Const.ActionURIs.STUDENT_FEEDBACK_SUBMISSION_EDIT_PAGE)
+                        .withCourseId(course.getId())
+                        .withSessionName(fsa.getFeedbackSessionName())
+                        .withRegistrationKey(StringHelper.encrypt(student.key))
+                        .withStudentEmail(student.email)
+                        .toAbsoluteString();
+                submitUrlHtml = "<a href=\"" + submitUrl + "\">" + submitUrl + "</a>";
+                
+                String reportUrl = Config.getAppUrl(Const.ActionURIs.STUDENT_FEEDBACK_RESULTS_PAGE)
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/EmailGenerator.java]: Looks like I missed one here.
An open session does not mean it is published. The correct check for this block should be `fsa.isPublished()`.

File: src/main/java/teammates/logic/api/EmailGenerator.java [hunk 82]
```diff
@@ -95,6 +95,81 @@
...
+                                           "${joinUrl}", joinUrl,
+                                           "${courseName}", course.getName())
+                                   : "";
+
+        for (FeedbackSessionAttributes fsa : sessions) {
+
+            String submitUrlHtml = "(Feedback session is " + (fsa.isClosed() ? "closed" : "not yet opened") + ")";
+            String reportUrlHtml = "(Feedback session is not yet published)";
+
+            if (fsa.isPublished()) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/EmailGenerator.java]: No, this is incorrect. `fsa.isOpened()` is the correct condition for `submitUrl` to be a valid URL. You do not need to wait for the session to be published to be able to submit, do you?

What needs to be done is:
```java
if (fsa.isOpened()) {
    String submitUrl = ...;
    submitUrlHtml = ...;
}
if (fsa.isPublished()) {
    String reportUrl = ...;
    reportUrlHtml = ...;
}
```

Comment (tarun14110) [inline src/main/java/teammates/logic/api/EmailGenerator.java]: Oh sorry, I misunderstood,

**Comment by wkurniawan07** [comment]
@damithc can review. I can confirm that submission links are included for only open sessions (not awaiting sessions, not even closed sessions), and results link are included for only published sessions.

**Comment by wkurniawan07** [comment]
@tarun14110 your latest code still gets a red X, but it should only be a minor fix away from a green tick.

File: src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html [hunk 83]
```diff
@@ -0,0 +1,57 @@
...
+
+
+
+<p>
+    Below are the feedback sessions of the course.
+    <br><br>
+<br>&nbsp;&nbsp; <strong>Feedback Session Name:</strong> Closed Session
+<br>&nbsp;&nbsp; <strong>Deadline:</strong> Sat, 01 Jun 2013, 11:59 PM (Passed)
+<br>
+To submit feedback for the above session, please go to this Web address: (Feedback session is closed)
```
Comment (damithc) [inline src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html]: Is this fixed? If not, can be done in a separate issue.

Comment (wkurniawan07) [inline src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html]: Not fixed yet. But it's not a "wrong behaviour" per se.

**Comment by wkurniawan07** [comment]
@tarun14110 can you update this branch with the latest `master`?

**Comment by tarun14110** [comment]
@wkurniawan07 updated the branch.
