### PR TITLE
AdminActivityLogPageAction: fix bug in generation of status message #6711

### LINKED ISSUE #6711: AdminActivityLogPageAction: fix bug in generation of status message
**Environment**
master branch at efad9e9dc1149779850773b323acaf2639b15c90

**Steps to reproduce**
Go to AdminActivityLog in admin console and type query to filter the log messages.
Currently when the `person:xxx` like query is present, status message is supposed to contain the time in that person's timezone (`xxx in Local Time Zone (8.0).`). But this function gets a huge bug: The query will be processed as lower case. If the person's google id contains upper case, the information could be lost.

Let's use `person:idOfInstructor1OfCourse1` as a example.

**Expected behaviour**
When query the person's timezone in the back-end, the google Id should be `idOfInstructor1OfCourse1`.

**Actual behaviour**
The google Id will become `idofinstructor1ofcourse1`.

**Notes**
The bug is found in #6655 and because of this, the behaviour cannot be tested as our test data got capital letter for googleID.

The bug is not so obvious and not so urgent as most of users' (I guess all?) google id will be in lower case.

If the issue is fixed, remeber to add back the test case in `AdminActivityLogPageActionTest`.
```
verifyLocalTimeInStatusMessage(statusMessage, yesterday, 2);
```

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #6711

**Outline of Solution**

- Explained in Commit messages

### CODE REVIEW

File: src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java [hunk 1]
```diff
@@ -248,9 +248,13 @@ private QueryParameters parseQuery(String query) throws ParseException, InvalidP
                 throw new InvalidParametersException("Invalid format");
             }
 
+            String label = pair[0].trim().toLowerCase();
             String[] values = pair[1].split(",", -1);
             values = StringHelper.trim(values);
-            String label = pair[0].trim();
+
+            if (!("person".equals(label))) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java]: Comment here?

GoogleID is case-sensitive?

File: src/main/java/teammates/common/util/StringHelper.java [hunk 2]
```diff
@@ -505,6 +505,15 @@ public static String removeEnclosingSquareBrackets(String str) {
                 .toArray(size -> new String[size]);
     }
 
+    /**
+     * Returns a String array after converting them to lower case.
+     */
+    public static String[] toLowerCase(String[] stringsToConvertToLowerCase) {
```
Comment (xpdavid) [inline src/main/java/teammates/common/util/StringHelper.java]: Don't forget the unit test for this method :D
