### PR TITLE
[#9757] Feedback Session Edit: Fix assigned weights not shown after clicking 'Choices are weighted' checkbox

### LINKED ISSUE #9757: Feedback Session Edit: Assigned weights not shown after clicking 'Choices are weighted' checkbox
- **Environment**: master

**Steps to reproduce**
1. Login as an instructor. 
2. Open a new feedback session.
3. Create a new mcq or msq question.
4. Check 'Choices are weighted' and uncheck 'generate options from the list of all'

**Expected behaviour**

There should be input boxes for weights.
image

**Actual behaviour**
The input boxes are not shown.
image

**Additional info**
The boolean variable  'hasAssignedWeights' should turn to be true after checking 'Choices are weighted', but actually it's not. Need to figure out the reason why the this variable doesn't change and fix it.

### PR DESCRIPTION
**Pull request by Pengyuz**
Fixes #9757 

image

Outline of Solution
Two-way binds the 'hasAssignedWeights' and the checkbox.

### CODE REVIEW

File: src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts [hunk 1]
```diff
@@ -112,9 +112,11 @@ export class McqQuestionEditDetailsFormComponent
   triggerWeightsColumn(event: any): void {
     const fieldsToUpdate: any = {};
     if (!event.target.checked) {
+      this.model.hasAssignedWeights = false;
       fieldsToUpdate.mcqWeights = [];
       fieldsToUpdate.mcqOtherWeight = 0;
     } else {
+      this.model.hasAssignedWeights = true;
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts]: By doing this, you are still changing the data that belongs to the parent in the child component.
