### PR TITLE
Fix typos in InstructorCourseEditPageUiTest and InstructorPrivilegesTest #6990

### LINKED ISSUE #6990: Fix typos in InstructorCourseEditPageUiTest and InstructorPrivilegesTest
Detail CheckStyle Report: https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/test.html

InstructorCourseEditPageUiTest
Insturctor is not a word according to provided dictionary
``` java
        int unregisteredInsturctorIndex = 4;
```

~~CommentAttributesTest.java~~ Edit: removed in #7334
Memssage is not a word according to provided dictionary
``` java
List<String> errorMemssage = comment.getInvalidityInfo();
```

InstructorPrivilegesTest.java
Privilges is not a word according to provided dictionary
``` java
        Map<String, Boolean> sectionPrivilges = privileges.getSectionLevelPrivileges().get(sectionId);
```

### PR DESCRIPTION
**Pull request by ParmaarK**
Fixes #6990

I couldn't find CommentAttributesTest.java class as mentioned in the reported issue. Please help with that.

### CODE REVIEW

**Comment by whipermr5** [comment]
@ParmaarK That file has been removed so it's fine :)

**Comment by whipermr5** [comment]
@ParmaarK The build failure is due to a simple style issue that is easy to fix; take a look at the log for details :)

**Comment by whipermr5** [comment]
@ParmaarK Do note that the `release` branch is only for tagging new releases, and is only updated by us once every release cycle. For development PRs like this one, the base branch should be `master`.

File: src/test/java/teammates/test/cases/datatransfer/InstructorPrivilegesTest.java [hunk 1]
```diff
@@ -214,8 +214,8 @@ public void testUpdatePrivilegeInSectionLevel() {
         assertFalse(sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS));
         assertEquals(null, sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_SESSION_IN_SECTIONS));
         assertEquals(null, sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_SUBMIT_SESSION_IN_SECTIONS));
-        assertEquals(null, sectionPrivileges.get(Const.ParamsNames.
-                                                     INSTRUCTOR_PERMISSION_MODIFY_SESSION_COMMENT_IN_SECTIONS));
+        assertEquals(null, sectionPrivileges.get(Const.ParamsNames
+                                                     .INSTRUCTOR_PERMISSION_MODIFY_SESSION_COMMENT_IN_SECTIONS));
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/InstructorPrivilegesTest.java]:
```
assertEquals(null,
        sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_SESSION_COMMENT_IN_SECTIONS));
```

File: src/test/java/teammates/test/cases/datatransfer/InstructorPrivilegesTest.java [hunk 2]
```diff
@@ -214,8 +214,8 @@ public void testUpdatePrivilegeInSectionLevel() {
         assertFalse(sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS));
         assertEquals(null, sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_SESSION_IN_SECTIONS));
         assertEquals(null, sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_SUBMIT_SESSION_IN_SECTIONS));
-        assertEquals(null, sectionPrivileges.get(Const.ParamsNames
-                                                     .INSTRUCTOR_PERMISSION_MODIFY_SESSION_COMMENT_IN_SECTIONS));
+        assertEquals(null,
+                     sectionPrivileges.get(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_SESSION_COMMENT_IN_SECTIONS));
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/InstructorPrivilegesTest.java]: We've switched to using 8-space indentation rather than aligning the arguments, so delete 5 spaces.

**Comment by whipermr5** [comment]
@ParmaarK Do note our PR title convention for future PRs. I've helped you fix it this time :)

**Comment by ParmaarK** [comment]
Will keep in mind all the changes from next time.
@whipermr5 thanks :)
