### PR TITLE
InstructorFeedbacks shows wrong date for new form due to UTC conversion rounding #5012

### LINKED ISSUE #5012: InstructorFeedbacks shows wrong date for new form due to UTC conversion rounding
When visiting new feedback session page before 7am UTC +8, yesterday's date will be shown as the submission opening date.

Similarly, when visiting after 4pm UTC -8, tomorrow's date will be shown.

Same for other timezones.

image

### PR DESCRIPTION
**Pull request by YongJieYongJie**
Fixes #5012

### CODE REVIEW

File: src/main/webapp/js/instructorFeedbacks.js [hunk 1]
```diff
@@ -88,12 +88,26 @@ function selectDefaultTimeOptions() {
...
+function isUtcDateDifferentFromCurrentDate(time, timeZone) {
+    var isUtcAhead = (timeZone - time) <= -24;
+    var isUtcBehind = (timeZone - time) >= 1; // this is not zero because we are using next nearest hour
+    return isUtcAhead || isUtcBehind;
+}
+
+function shiftDateToToday() {
+    var currentDate = new Date(new Date().getTime());
+    $('#startdate').val(convertDateToDDMMYYYY(currentDate));
+}
```
Comment (damithc) [inline src/main/webapp/js/instructorFeedbacks.js]: It would be nice if the logic can be separated out into a method that can be tested independently using QUnit tests.

File: src/main/webapp/js/instructorFeedbacks.js [hunk 2]
```diff
@@ -88,12 +88,26 @@ function selectDefaultTimeOptions() {
...
 }
 
+function isUtcDateDifferentFromCurrentDate(time, timeZone) {
+    var isUtcAhead = (timeZone - time) <= -24;
+    var isUtcBehind = (timeZone - time) >= 1; // this is not zero because we are using next nearest hour
+    return isUtcAhead || isUtcBehind;
+}
+
+function shiftDateToToday() {
+    var currentDate = new Date(new Date().getTime());
```
Comment (junhaoyap) [inline src/main/webapp/js/instructorFeedbacks.js]: ```new Date()``` defaults to today

**Comment by junhaoyap** [comment]
I'll let someone else look at the other stuff - I just dropped by for a quick note

**Comment by YongJieYongJie** [comment]
I have made the logic even more explicit.

**Comment by yj-soh** [comment]
Is there a reason why we can't just put a
`$('#' + FEEDBACK_SESSION_STARTDATE).val(convertDateToDDMMYYYY(now))`
in the `if (!isTimeZoneIntialized()) {` block? It seems to work fine as far as I can tell.

**Comment by YongJieYongJie** [comment]
@yj-soh You are right, actually there is no need to check for difference in date, we can just apply current date no matter what (I guess I started with that contrived algorithm and got fixated on it).

I've made the changes accordingly. Though I did introduce a new variable to be consistent with the existing code.

**Comment by yj-soh** [comment]
I wouldn't usually recommend this, but could you clean up the commits and do a force push to the branch?
I do think it would be preferable to not have 11 unnecessary commits in the history.

**Comment by YongJieYongJie** [comment]
@yj-soh All done!

**Comment by yj-soh** [comment]
The commit message isn't exactly accurate since you didn't add a function (but a function call), I'll set this to merge for now.

**Comment by YongJieYongJie** [comment]
@yj-soh Edited and pushed!

**Comment by thyageshm** [comment]
@yj-soh please merge this one :-)

**Comment by thyageshm** [comment]
@yj-soh please merge this soon
