### PR TITLE
Admin: home page: fix data row overflow #6900

### LINKED ISSUE #6900: Admin: home page: fix data row overflow
**Environment**
Local Dev Server

**Steps to reproduce**
When we add details of a new instructor and get response row is overflowed.
teammates

**Expected behaviour**
It should be inside the table.

**Actual behaviour**
Data is overflowing out of table.

I want to work on this issue.

### PR DESCRIPTION
**Pull request by bjrodrig**
Fixes #6900 

Changed results table on Admin add instructors page as follows:
admin add instructor overflow - join link

Updated tests in AdminHomePageUiTest.java

### CODE REVIEW

**Comment by amarlearning** [comment]
@bjrodrig Since you are new to this organization, I would suggest you start with a `d.FirstTimer` issue and then move to issues with label `d.Contributors`.

**Comment by bjrodrig** [comment]
Hi @amarlearning. I worked on the first timers issue concerning IDE documentation, but that issue was closed out since the documentation didn't need to be moved.

**Comment by bjrodrig** [comment]
Also, this is ready for review.

File: src/test/java/teammates/test/pageobjects/AdminHomePage.java [hunk 1]
```diff
@@ -95,4 +96,9 @@ public String getMessageFromResultTable(int index) {
         return getCellValueFromDataTable(index, 5);
     }
 
+    public String getJoinLink(String messageText) {
+        WebElement link = browser.driver.findElement(By.linkText("[Join Link]"));
```
Comment (chowyb) [inline src/test/java/teammates/test/pageobjects/AdminHomePage.java]: Is it possible to extract this string `"[Join Link]"` into a constant for use both here and in the code above? Otherwise, this test may be quite brittle: if the text for the code in `AdminInstructorAccountAddAction` changes in the future, this will result in failing test cases.

**Comment by bjrodrig** [comment]
Hi @chowyb . I changed the [Join Link] to a constant in the three files, as requested. This is ready for review again.
