### PR TITLE
InstructorFeedbackSessionsPageUiTest: remove dependency on browser time zone #7669

### LINKED ISSUE #7669: InstructorFeedbackSessionsPageUiTest: remove dependency on browser time zone
Part of the test involves HTML verification of the publish button, which has a `disabled=""` attribute whose presence depends on browser time zone. Hence, the test sometimes fails on non-UTC systems. See https://github.com/TEAMMATES/teammates/pull/7634#discussion_r124998599.

~~There must be some JavaScript that adds or removes the `disabled=""` attribute based on the status of the session (open/closed/published?); however it's using browser time zone to determine this status. Change this to use server time instead.~~
Edit: it seems that the problem doesn't lie with JavaScript, but with the way the test session data is prepared in `InstructorFeedbackSessionsPageUiTest`. The start time differs when the test is run on a different time zone.

### LINKED ISSUE #7789: InstructorFeedbackSessionsPageUiTest.testAddDeleteActions: fix failure on live server
v5.109

image
```
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:89)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:57)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:852)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:904)
	at teammates.test.cases.browsertests.InstructorFeedbackSessionsPageUiTest.testDeleteAction(InstructorFeedbackSessionsPageUiTest.java:569)
	at teammates.test.cases.browsertests.InstructorFeedbackSessionsPageUiTest.testAddDeleteActions(InstructorFeedbackSessionsPageUiTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7669, fixes #7789

**Outline of Solution**

The root issue is that the session start time of the session created via UI in the test is inconsistent across systems with different time zones. This results in inconsistent behaviour of the publish button, whose disabled state depends on whether or not the session is waiting to open (and subsequently has a dependency on the session start time).

It turns out that one of the test sessions created during the test had start time unspecified. The test was relying on the browser to fill in the correct start time, based on the default date picker behaviour (next hour from current time). This is fine, except that the same test also specified a time zone (5.75). Now this poses a problem. While start time is autodetected (next hour based on the original browser time zone), the selected time zone is hardcoded. Since start time is interpreted as local time based on the selected time zone, the discrepancy results in an interpretation that differs across systems on different time zones.

To fix, the hardcoded time zone was removed from the test case, allowing the browser to fill in the time zone, too. Different time zones are already tested through other test cases.

### CODE REVIEW

**Comment by LiHaoTan** [comment]
@whipermr5 not sure if we should do it but setting the environment variable `TZ` allows us to set Selenium's timezone for both Firefox and Chrome.

**Comment by whipermr5** [comment]
@LiHaoTan Is it possible to set that from within Java code? If not, asking the user to set an environment variable is almost as bad as asking them to set their system clock to UTC.

**Comment by LiHaoTan** [comment]
@whipermr5 yup its possible!

**Comment by whipermr5** [comment]
@LiHaoTan As discussed, the way to set it in Java is quite hackish. I feel it's not needed at this time, especially since only this one test is failing on non-UTC systems. If we need to add more tests that depend on browser time zone in future, can reconsider then.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 1]
```diff
@@ -276,7 +276,9 @@ private void testAddAction() throws Exception {
 
         feedbackPage.addFeedbackSessionWithTimeZone(
                 newSession.getFeedbackSessionName(), newSession.getCourseId(),
-                null, null, null, null,
+                // explicitly set start time as browser time zone varies;
+                // follow what a browser would pick (next hour from current time)
```
Comment (leeyimin) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: How about `next hour based on system time zone`? `current time` may be a little vague.
