### PR TITLE
[#10614][#10616] Fix session results page issues

### LINKED ISSUE #10614: Instructor view results: un-publishing results navigates to a different page
image

Publishing/unpublising from the results page (using the button) sends the user to a different page.
Suggestion: stay in the same page

### LINKED ISSUE #10616: Change icon for publish/unpublish
Current:
image

Perhaps use these instead?
image
image

### PR DESCRIPTION
**Pull request by niqiukun**
Fixes #10614 
Fixes #10616
image
Other fixes:
- Add "not applicable" for results visible from time for unpublished sessions
- Make the style of merge/expand all button consistent with edit session page

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts [hunk 1]
```diff
@@ -383,7 +402,13 @@ export class InstructorSessionResultPageComponent extends InstructorCommentsComp
       ;
 
       response.subscribe(() => {
-        this.router.navigateByUrl('/web/instructor/sessions');
+        this.loadFeedbackSessionVisibleFromTime(this.courseId, this.fsName);
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts:405]: I might be wrong, but I don't think you need this. Both `(unpublish|publish)FeedbackSession` endpoint should return the session object itself, which you can use straightaway to construct the new visible from time.

Comment (niqiukun) [reply src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts:405]: Yes you are right. Thanks for pointing out. I should have checked the response type from the endpoint. I think part of the reason for me to overlook this is because the type of the variable `response` is `Observable<any>` where it actually can be `Observable<FeedbackSession>`.

File: src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts [hunk 2]
```diff
@@ -109,6 +109,8 @@ export class InstructorSessionResultPageComponent extends InstructorCommentsComp
   FeedbackSessionPublishStatus: typeof FeedbackSessionPublishStatus = FeedbackSessionPublishStatus;
   isExpandAll: boolean = false;
 
+  readonly TIME_FORMAT: string = 'ddd, DD MMM, YYYY, hh:mm A zz';
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts:112]: If this variable is not read by the HTML file, you can move it to outside the `export class` definition. That way you don't need `this.TIME_FORMAT`.

File: src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts [hunk 3]
```diff
@@ -382,8 +384,20 @@ export class InstructorSessionResultPageComponent extends InstructorCommentsComp
...
-        this.router.navigateByUrl('/web/instructor/sessions');
+      response.subscribe((res: FeedbackSession) => {
+        this.session = res;
+        if (this.session.resultVisibleFromTimestamp) {
+          this.formattedResultVisibleFromTime = this.timezoneService
+            .formatToString(this.session.resultVisibleFromTimestamp, this.session.timeZone, this.TIME_FORMAT);
+        } else {
+          this.formattedResultVisibleFromTime = 'Not applicable';
+        }
+        if (isPublished) {
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts:395]: Are the conditionals `isPublished` and `this.session.resultVisibleFromTimestamp` equivalent?
