### PR TITLE
InstructorCourseJoinAuthenticatedActionr: No institute found for the course #4728

### LINKED ISSUE #4728: InstructorCourseJoinAuthenticatedActionr: No institute found for the course
No institute found for the course

Actual user abc
Request Method GET
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/537.86.2
Request Url https://teammatesv4.appspot.com/page/instructorCourseJoinAuthenticated
Request Path /page
Request Parameters {key::abc3CF7B189E1C603F59BD79FC7FC9D076B6C55940983641A3B18FA8825D6D34FF1A8B755D36D1A5B2A2F8EC79B03872C877BCDF8C780ACE5F9A2AB0FCC8EBD9}
Stack Trace

java.lang.AssertionError: No institute found for the course
	at teammates.common.util.Assumption.fail(Assumption.java:59)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
	at teammates.common.util.Assumption.assertFalse(Assumption.java:44)
	at teammates.common.util.Assumption.assertNotEmpty(Assumption.java:370)
	at teammates.logic.core.AccountsLogic.getCourseInstitute(AccountsLogic.java:100)
	at teammates.logic.core.AccountsLogic.joinCourseForInstructorWithInstitute(AccountsLogic.java:181)
	at teammates.logic.core.AccountsLogic.joinCourseForInstructor(AccountsLogic.java:162)
	at teammates.logic.api.Logic.joinCourseForInstructor(Logic.java:581)
	at teammates.ui.controller.InstructorCourseJoinAuthenticatedAction.execute(InstructorCourseJoinAuthenticatedAction.java:35)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by unyoungwax**
Fixes #4728

### CODE REVIEW

File: src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java [hunk 1]
```diff
@@ -27,20 +27,20 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
-        int numOfInstrCanModifyInstructor = 0;
-        InstructorAttributes instrCanModifyInstructor = null;
+        boolean hasInstrCanModifyInstructor = false;
         for (InstructorAttributes instr : instructors) {
-            if (instructor.isAllowedForPrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_INSTRUCTOR)) {
-                numOfInstrCanModifyInstructor++;
-                instrCanModifyInstructor = instr;
+            if (instr.isAllowedForPrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_INSTRUCTOR)
+                && !instr.getEmail().equals(instructorEmail)
+                && instr.isRegistered()) {
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java]: Introduce a local variable to explain the meaning of this long boolean condition.

**Comment by unyoungwax** [comment]
I have extracted a method called `hasAlternativeInstructor` and introduced a local variable for the condition of the if-statement in the method.

File: src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java [hunk 2]
```diff
@@ -27,20 +27,8 @@ protected ActionResult execute() throws EntityDoesNotExistException {
         new GateKeeper().verifyAccessible(
                 instructor, logic.getCourse(courseId), Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_INSTRUCTOR);
 
-        List<InstructorAttributes> instructors = logic.getInstructorsForCourse(courseId);
```
Comment (JosephineKwa) [inline src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java]: Hmm, the original algorithm looks like it should be able to prevent the last instructor from being deleted as well. Were you able to replicate the deletion of the last instructor using the original algorithm? Anyhow, the extracted method looks cleaner and more straightforward, good job on that :+1: !

Comment (unyoungwax) [inline src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java]: In the extracted method, it looks for another joined instructor that has the privilege of modifying instructors. Since there is no other instructor, the method returns false after checking the last instructor. This prevents the deletion of the last instructor.

**Comment by JosephineKwa** [comment]
Looks good to merge, @damithc pending approval

File: src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java [hunk 3]
```diff
@@ -66,4 +54,26 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
+     */
+    private boolean hasAlternativeInstructor(String courseId, String instructorToDeleteEmail) {
+
+        List<InstructorAttributes> instructors = logic.getInstructorsForCourse(courseId);
+
+        for (InstructorAttributes instr : instructors) {
+
+            boolean isAlternativeInstructor = instr.isRegistered()
+                                              && !instr.getEmail().equals(instructorToDeleteEmail)
+                                              && instr.isAllowedForPrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_INSTRUCTOR);
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java]: This line is a bit too long? Reduce indentation?

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java [hunk 4]
```diff
@@ -418,37 +420,61 @@ private void testDeleteInstructorAction() {
...
-        ______TS("deleted own instructor role and redirect to courses page");
+        ______TS("test the only registered instructor with the privilege to modify instructors cannot be deleted");
         
-        // Change login id to another instructor
+        // Create an registered instructor with all privileges except modifying instructors
+        InstructorPrivileges privilege = new InstructorPrivileges(Const.InstructorPermissionRoleNames.INSTRUCTOR_PERMISSION_ROLE_COOWNER);
+        privilege.updatePrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_INSTRUCTOR, false);
+        InstructorAttributes instructor = new InstructorAttributes("InsCrsEdit.reg", courseId, "Teammates Reg", "InsCrsEdit.reg@gmail.tmt", 
+                                        Const.InstructorPermissionRoleNames.INSTRUCTOR_PERMISSION_ROLE_CUSTOM, "Teammates Reg", privilege);
+        BackDoor.createInstructor(instructor);
```
Comment (damithc) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java]: A few lines in the block above can be shortened, to avoid horizontal scrolling in diff view.

**Comment by damithc** [comment]
Some cosmetic changes requested. Can merge after that.
