### PR TITLE
[#9519] Unable to serve profile picture

### LINKED ISSUE #9519: Unable to serve profile picture
- **Environment**
V7 at master , e5e97c4ddb5917dd065e363cd07cbeb36ca1dfc7

**Steps to reproduce**

1. Go to the student profile page.
2. Upload a profile picture.

**Expected behavior**

* Picture is uploaded successfully.

**Actual behaviour**
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #9519

Root cause: since we don't upload pictures to Blobstore anymore, there is no `BlobInfo` to be obtained.

There is no other Blobstore API that can be used to determine the content type, thus we hard-code the content type to `image/png` (there is little to no effect in setting wrong content type in header as long as it is image; in fact this was done in V6 without any apparent drawback).

The only true resolution is to ditch the Blobstore API altogether and use GCS API (which has an API to query content type) entirely, but this will require further design.

### CODE REVIEW

File: src/test/java/teammates/test/cases/webapi/GetStudentProfileActionTest.java [hunk 1]
```diff
@@ -65,21 +62,6 @@ private void testActionSuccess(AccountAttributes student, StudentProfileAttribut
         assertEquals(student.getName(), output.getName());
     }
 
-    private void testActionForbidden(AccountAttributes student1, AccountAttributes student2,
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/webapi/GetStudentProfileActionTest.java]: This test should be moved to testAccessControl?
