### PR TITLE
[#10397] Add frontend validation for feedback submission

### LINKED ISSUE #10397: Feedback submission propagates invalid question responses
Distribute points (among recipients) successfully submits results that don't distribute all the points.

**Steps to reproduce**
Create a feedback session with a question on distribute points (among recipients) and distribute points in a manner that does not adhere to the question constraints (e.g. do not distribute all points).

**Expected behaviour**
Invalid submission does not get propagated to backend.

**Actual behaviour**
Invalid submission is propagated to backend.

**Additional info**
This is a followup from #10396 and #10299. Frontend validation is necessary since each option in a distribute points question is treated as a separate response that is sent to the backend api endpoint. This means that backend validation is difficult to achieve as the API treats each response independently from each other.

### PR DESCRIPTION
**Pull request by madanalogy**
Fixes #10397 

Jul-29-2020 17-13-44

### CODE REVIEW

File: src/web/app/components/question-types/question-constraint/question-constraint.component.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { EventEmitter, Output } from '@angular/core';
+import { Observable } from 'rxjs';
+
+/**
+ * Base class for constraint components.
+ */
+export abstract class QuestionConstraintComponent {
+  @Output()
+  isValidEvent: EventEmitter<Observable<boolean>> = new EventEmitter();
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/question-constraint.component.ts:9]: Why can't we do?
```suggestion
  isValidEvent: EventEmitter<boolean> = new EventEmitter();
```

File: src/web/app/components/question-types/question-constraint/question-constraint.component.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+  abstract isValid(): Observable<boolean>;
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/question-constraint.component.ts:11]:
```suggestion
  abstract isValid(): boolean;
```

File: src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts [hunk 3]
```diff
@@ -20,17 +22,20 @@ import {
...
   styleUrls: ['./rank-recipients-question-constraint.component.scss'],
 })
-export class RankRecipientsQuestionConstraintComponent implements OnInit {
+export class RankRecipientsQuestionConstraintComponent extends QuestionConstraintComponent implements OnInit {
 
   @Input()
   questionDetails: FeedbackRankRecipientsQuestionDetails = DEFAULT_RANK_RECIPIENTS_QUESTION_DETAILS();
 
   @Input()
   recipientSubmissionForms: FeedbackResponseRecipientSubmissionFormModel[] = [];
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts:31]: Try to use setter method here.

File: src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts [hunk 4]
```diff
@@ -20,17 +22,20 @@ import {
   templateUrl: './rank-recipients-question-constraint.component.html',
   styleUrls: ['./rank-recipients-question-constraint.component.scss'],
 })
-export class RankRecipientsQuestionConstraintComponent implements OnInit {
+export class RankRecipientsQuestionConstraintComponent extends QuestionConstraintComponent implements OnInit {
 
   @Input()
   questionDetails: FeedbackRankRecipientsQuestionDetails = DEFAULT_RANK_RECIPIENTS_QUESTION_DETAILS();
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts:28]: The field can go to the parent class.

File: src/web/app/components/question-types/question-constraint/question-constraint.component.ts [hunk 5]
```diff
@@ -0,0 +1,12 @@
+import { EventEmitter, Output } from '@angular/core';
+import { Observable } from 'rxjs';
+
+/**
+ * Base class for constraint components.
+ */
+export abstract class QuestionConstraintComponent {
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/question-constraint.component.ts:7]: with the help of generic class
```suggestion
export abstract class QuestionConstraintComponent<Q extends FeedbackQuestionDetails> {
```

And therefore the `isValid` check can be here (The child component will only need care about whether the `isValid` or not. They don't need to fire event!).

File: src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.ts [hunk 6]
```diff
@@ -101,4 +106,74 @@ export class ConstsumRecipientsQuestionConstraintComponent implements OnInit {
...
+   */
+  get isCorrectlySomeUneven(): boolean {
+    return this.questionDetails.distributePointsFor === FeedbackConstantSumDistributePointsType.DISTRIBUTE_SOME_UNEVENLY
+        && this.isSomePointsUneven;
+  }
+
+  isValid(): Observable<boolean> {
+    return new Observable((observer: Subscriber<boolean>) => {
+      observer.next(
+          (this.questionDetails.distributePointsFor
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.ts:166]: Why we don't use `this. isAllPointsDistributed ` and so on?

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 7]
```diff
@@ -136,6 +139,9 @@ export class QuestionSubmissionFormComponent implements OnInit {
    * Triggers the change of the recipient submission form.
    */
   triggerRecipientSubmissionFormChange(index: number, field: string, data: any): void {
+    this.isQuestionValid.subscribe((isValid: boolean) => {
+      this.model.isValid = isValid;
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:143]: You should use `formModelChange` to fire event rather than change directly here.

**Comment by madanalogy** [comment]
@xpdavid The idea I had was that once a constraint component was initialised in a question component, it would emit an `Observable<boolean>` to be tracked by the question. The question will then update the model whenever there is any change in the form by polling the observable to retrieve the latest `isValid: boolean`.

This design approach was my answer to the question of "when should the constraint component emit the validity boolean?" because the constraint component doesn't have access to the parent question component's `formModelChange`.

File: src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts (hunk 3 above)
Comment (madanalogy) [reply src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts:31]: What do you mean by this? To set the form model as an alternative to `@Input`?

File: src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts [hunk 8]
```diff
@@ -20,17 +22,20 @@ import {
...
   @Input()
   recipientSubmissionForms: FeedbackResponseRecipientSubmissionFormModel[] = [];
 
-  constructor() { }
+  constructor() {
+    super();
+  }
 
   ngOnInit(): void {
+    this.isValidEvent.emit(this.isValid());
```
[the remark this answers is not in the document]
Comment (madanalogy) [reply src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts:38]: For this and your next 2 comments, see https://github.com/TEAMMATES/teammates/pull/10398#issuecomment-667189210

**Comment by xpdavid** [comment]
You can make `*-contrains` component emit `isValid` event and let `question-submission-form.component` to change the model.

I think we are also facing a new issue here: There are constraints targeted to a group of responses and also a single response. - If your `isValid` is only defined for `QuestionSubmissionFormModel`, how about the individual response?
- If your `isValid` is only defined for `FeedbackResponseRecipientSubmissionFormModel`, how about the group response?

**Comment by madanalogy** [comment]
> You can make `*-contrains` component emit `isValid` event and let `question-submission-form.component` to change the model.

Yes this is what I'm already doing, just that I'm using a single observable emit so the responsibility then becomes on the question component to poll the value whenever necessary, rather than the constraint component constantly emitting at some arbitrary benchmark.

> I think we are also facing a new issue here: There are constraints targeted to a group of responses and also a single response.
>
> * If your `isValid` is only defined for `QuestionSubmissionFormModel`, how about the individual response?
> * If your `isValid` is only defined for `FeedbackResponseRecipientSubmissionFormModel`, how about the group response?

`isValid` here is only define for `QuestionSubmissionFormModel` because constraints are only defined on a per question basis. Individual responses can easily be validated within their corresponding response component or even on a per response basis prior to sending to the backend and even easily validated at the backend. My only purpose here is to validate the group response (i.e. per-question basis). I do not see individual response validation within the scope of this PR.

**Comment by xpdavid** [comment]
> so the responsibility then becomes on the question component to poll the value whenever necessary

You don't need use `EventEmitter<Observable<boolean>>`  to separate the responsibility. If the constraint component use `EventEmitter<boolean>`, it is still up to the question component to "listen" to the event or not.

In addition, your end goal is to update `isValid` attribute in the questionModal which can be easily achieved by `EventEmitter<boolean>`.

> My only purpose here is to validate the group response (i.e. per-question basis). I do not see individual response validation within the scope of this PR.

I think this is not closed for modification. I think we can ask ourselves, how many lines of code shall we change if we want the logic (e.g., disable the submission button or pop up the status message when any response is invalid) for single response also?

**Comment by madanalogy** [comment]
> You don't need use `EventEmitter<Observable<boolean>>` to separate the responsibility. If the constraint component use `EventEmitter<boolean>`, it is still up to the question component to "listen" to the event or not.
> 
> In addition, your end goal is to update `isValid` attribute in the questionModal which can be easily achieved by `EventEmitter<boolean>`.

When should the constraint component emit the value then? It doesn't have access to the parent `formModelChange`. Unless I set up an emitter in the parent as well possibly?

> I think this is not closed for modification. I think we can ask ourselves, how many lines of code shall we change if we want the logic (e.g., disable the submission button or pop up the status message when any response is invalid) for single response also?

Okay noted on this, I will think it through and see how I can make this work for both grouped responses and individual responses

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 9]
```diff
@@ -136,6 +139,9 @@ export class QuestionSubmissionFormComponent implements OnInit {
    * Triggers the change of the recipient submission form.
    */
   triggerRecipientSubmissionFormChange(index: number, field: string, data: any): void {
+    this.isQuestionValid.subscribe((isValid: boolean) => {
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:142]: To answer your question:
- We don't need to do listen to validation event here. There are better places.
- Plus: This is wrong. You are subscribing the observable multiple times.

File: src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts (hunk 3 above)
Comment (xpdavid) [reply src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts:31]: And thus, if you use `setter` method (https://angular.io/guide/component-interaction#intercept-input-property-changes-with-a-setter) here:

This is where you should fire the event.

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 10]
```diff
@@ -531,7 +533,11 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
 
     this.questionSubmissionForms.forEach((questionSubmissionFormModel: QuestionSubmissionFormModel) => {
       let isQuestionFullyAnswered: boolean = true;
-
+      if (!questionSubmissionFormModel.isValid) {
+        failToSaveQuestions[questionSubmissionFormModel.questionNumber] =
```
[the remark this answers is not in the document]
Comment (madanalogy) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:537]: I think this might not be possible, since the validity of each question in a submission is independent of each other, and maybe they might still want to save the questions for which are already valid

File: src/web/app/components/question-submission-form/question-submission-form.component.ts (hunk 7 above)
Comment (madanalogy) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts]: Ideally since the model is being emitted in this method, I'd want to ensure that its `isValid` attribute is up to date

Comment (xpdavid) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts]: It's not about safe or not. It's violating the principle we want to enforce: child component should communicate with parent component by emitting events.

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 11]
```diff
@@ -93,6 +94,7 @@ export class QuestionSubmissionFormComponent implements OnInit {
 
   visibilityStateMachine: VisibilityStateMachine;
   allowedToHaveParticipantComment: boolean = false;
+  isQuestionValid: boolean = true;
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:97]: Why we need to create a new field and trigger the change indirectly?

File: src/web/app/components/question-types/question-constraint/question-constraint.component.ts [hunk 12]
```diff
@@ -0,0 +1,32 @@
+import { EventEmitter, Input, Output } from '@angular/core';
+import { FeedbackQuestionDetails } from '../../../../types/api-output';
+import { FeedbackResponseRecipientSubmissionFormModel } from '../../question-submission-form/question-submission-form-model';
+
+/**
+ * Base class for constraint components.
+ */
+export abstract class QuestionConstraintComponent<Q extends FeedbackQuestionDetails> {
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-constraint/question-constraint.component.ts:8]: 👍

**Comment by xpdavid** [comment]
> Also, questionSubmissionFormModel.isValid is only meaningful for questions like distribute points among recipients but not others, which can be misleading for subsequent maintainers.

Might want to do it per response.

**Comment by madanalogy** [comment]
> while invalid responses are no longer sent to backend for distribute points among recipients, they are still sent for other question types such as distribute points among options.

I realised that this happens because distribute points among options (`constsum-options`) does not have a constraint component. The constraints are manually displayed in the `tm-constsum-options-question-edit-answer-form` component html, so I missed it out. I'll be extracting it into it's own constraint component and review the other question forms for similar problems. Thanks for pointing that out.

>> Also, `questionSubmissionFormModel.isValid` is only meaningful for questions like distribute points among recipients but not others, which can be misleading for subsequent maintainers.
>
> Might want to do it per response.

I think an alternative here is to standardise all questions to use the constraint component for validation. There is already sufficient backend validation per response, and the real issue here is question validation not response validation. That most questions happen to only consist of one response shouldn't affect the validation approach.

The bottom line is that per-response validation just won't work for `constsum-recipients`. Or rather, I can't see how it could work (so if anyone has suggestions do let me know). With that in mind, rather than applying one type of validation (per question) on one question type and another type of validation (per response) for other question types, I'd rather apply per question validation for all question types. 

That being said, this goes back to the premise that  per-response validation cannot be used to validate `constsum-recipients` questions. I had assumed that if per-response validation were possible we wouldn't be having this issue, and looking at the code base currently I can't figure out how to implement pre-response validation for this question type since the constraints necessitate an overall view of individual responses in a question submission.

I will leave this here for a day in case anyone has comments, suggestions, or would like to volunteer picking up this PR. After that time, I will be proceeding with per-question validation with standardisation, i.e. review all question constraints and ensure that they're reflected in their respective constraint component.

File: src/web/app/components/question-submission-form/question-submission-form.component.ts (hunk 11 above)
Comment (madanalogy) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:97]: I didn't think we could do the model assignment directly in the html template? Or is that possible? i.e. `(isValidEvent)="model.isValid=$event"`

Comment (xpdavid) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:97]: You should create a new method and fire the event with newly updated model.

**Comment by xpdavid** [comment]
> I think an alternative here is to standardise all questions to use the constraint component for validation.

I do agree with the point and I am assuming this is what we are trying to do in the PR right (see benefits in option 2)?

I would like to reemphasis the situation and options we are facing now.

There are three options here and all of them have their tradeoff:

- Option 1: Use the implementation in the current PR
    - Pros
        - We can release V7 without breaking the promise
        - Easier to do
    - Cons
        - Not extensible when we want to extend to other question type (per response) (i.e. disable the submission button when responses are invalid).
        - Current changes will be useless after we change the API to accept response by questions.

- Option 2: Find a way to make the frontend validation work for both per-response and per-question (try the suggestion: put `isValid` in the `FeedbackResponseRecipientSubmissionFormModel`)
    - Pros
        - Very extensible and flexible for all types of question. We don't need to do it for every question type now. Just write the validation logic for constant-options/recipients and release it.
        - Follow OCP principle
        - Current changes will be reused even after the API changes to accept per question responses.
    - Cons
        - Need some time to explore and figure out how to get it works
        - V7 will have some times without proper validation check

- Option 3: Do the API changes now. Change the API to accept responses per question
    - Pros
        - Solve the problems all we have
        - We don't even need to write the frontend validation
    - Cons
        - Need some time to explore and change it.
       
Although right now I have a feeling that option 2 and option 3 share the same workload.

**Comment by madanalogy** [comment]
Actually, I spent more time trying to understand the code base and the different models, and I think there's an option 4, which is a per-response validation for `constsum-recipients`. Let me try it out and I'll update.

**Comment by madanalogy** [comment]
@niqiukun @xpdavid I've refactored the `isValid` check to be present per response instead of per question. I was mistaken that it could not be done for `constsum-recipients` (all I had to do was use a `forEach` on the response models in the question model). This should be extendable to other questions should we choose to proceed with frontend validation for them in future.

The only issue that remains unresolved is the consistency of the error message. Fixing this might require a new method in `feedbackQuestionsService` that can give you the correct error message for an invalid question. I would rather this be tackled in a separate PR however as it is quite involved (i.e. syncing error messages from the backend and the frontend).

**Comment by damithc** [comment]
> The only issue that remains unresolved is the consistency of the error message. Fixing this might require a new method in `feedbackQuestionsService` that can give you the correct error message for an invalid question. I would rather this be tackled in a separate PR however as it is quite involved (i.e. syncing error messages from the backend and the frontend).

Non-urgent improvements can be done later, in the interest of merging this sooner. I'm keen to add this validation before we go live.

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 13]
```diff
@@ -197,4 +196,13 @@ export class QuestionSubmissionFormComponent implements OnInit {
     return this.feedbackResponseService.isFeedbackResponseDetailsEmpty(
         this.model.questionType, responseDetails);
   }
+
+  /**
+   * Updates validity of all responses in a question.
+   */
+  updateValidity(isValid: boolean): void {
+    this.model.recipientSubmissionForms.forEach((model: FeedbackResponseRecipientSubmissionFormModel) => {
+      model.isValid = isValid;
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: I think I need to emphasize this again :(

This is not the correct way to change the value **passed** by the **parent** component. In other word, you do **NOT** own the model so you should not change it directly. Instead, please use event to emit the changes.

I think we need pass this knowledge down:
- All these efforts are to make the parent component who **own** the model to become a single point of truth
   - The parent component is free to make any change. It can also **ignore** the event omit by the child component.
   - Image that if child components make the change directly (like in this case and it works), how do you trace the control flow? In other word, you are breaking the contract that the `@Input()` annotation tells. It should be read-only and input property only.
   - (NOT relevant to this but useful to know)If you want to make the change to `@Input()` property, create a new variable and sync it between the input property when its value changes (see `StudentList` for example).

Comment (xpdavid) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: In case you are interested, using events might cause very deep passing of event handler from child all the way to root. Therefore, we have a more proper solution called [Redux](https://redux.js.org/ mostly used for React app) (or [NGRX](https://ngrx.io/) for Angular). We will see if we can leverage it in due course (we might not in that state yet, see below). 

> In general, use Redux when you have reasonable amounts of data changing over time, you need a single source of truth, and you find that approaches like keeping everything in a top-level React component's state are no longer sufficient.

> It's intended to help answer the question "When did a certain slice of state change, and where did the data come from?", with predictable behavior.

Comment (madanalogy) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: Could I use the `formModelChange` emitter to fire the event or should I create a new `@Output`?

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 14]
```diff
@@ -546,9 +550,13 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
 
     this.questionSubmissionForms.forEach((questionSubmissionFormModel: QuestionSubmissionFormModel) => {
       let isQuestionFullyAnswered: boolean = true;
-
       questionSubmissionFormModel.recipientSubmissionForms
           .forEach((recipientSubmissionFormModel: FeedbackResponseRecipientSubmissionFormModel) => {
+            if (!recipientSubmissionFormModel.isValid) {
+              failToSaveQuestions[questionSubmissionFormModel.questionNumber] =
+                  'Invalid responses provided. Please check question constraints.';
+              return;
```
[the remark this answers is not in the document]
Comment (madanalogy) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:558]: Yes, because the `isValid` check is in the `FeedbackResponseRecipientSubmissionFormModel` per-response, which is embedded in the `QuestionSubmissionFormModel`. This is the natural result of implementing per-response validation instead of per-question

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 15]
```diff
@@ -197,4 +196,19 @@ export class QuestionSubmissionFormComponent implements OnInit {
     return this.feedbackResponseService.isFeedbackResponseDetailsEmpty(
         this.model.questionType, responseDetails);
   }
+
+  /**
+   * Updates validity of all responses in a question.
+   */
+  updateValidity(isValid: boolean): void {
+    const recipientSubmissionForms: FeedbackResponseRecipientSubmissionFormModel[] =
+        this.model.recipientSubmissionForms.slice();
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: This is shallow copy actually.

Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:205]:
```suggestion
        this.model.recipientSubmissionForms.slice().map((model) => Object.assign({}, model, {isValid}))
```

This might be what you want.

Comment (madanalogy) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: I just took this from `triggerRecipientSubmissionFormChange()` haha, would you like me to change that method too?

Comment (xpdavid) [reply src/web/app/components/question-submission-form/question-submission-form.component.ts:205]: That method is actually doing thing correctly :P

This is the trick:
https://github.com/TEAMMATES/teammates/blob/f48c9579da351f9bc68edede51186e004208eb11/src/web/app/components/question-submission-form/question-submission-form.component.ts#L138-L141

File: src/web/app/components/question-submission-form/question-submission-form.component.ts [hunk 16]
```diff
@@ -197,4 +196,20 @@ export class QuestionSubmissionFormComponent implements OnInit {
...
   }
+
+  /**
+   * Updates validity of all responses in a question.
+   */
+  updateValidity(isValid: boolean): void {
+    const recipientSubmissionForms: FeedbackResponseRecipientSubmissionFormModel[] =
+        this.model.recipientSubmissionForms.slice().map(
+            (model: FeedbackResponseRecipientSubmissionFormModel) => Object.assign({}, model, { isValid }));
+    recipientSubmissionForms.forEach((model: FeedbackResponseRecipientSubmissionFormModel) => {
```
Comment (xpdavid) [inline src/web/app/components/question-submission-form/question-submission-form.component.ts:207]: So you should remove this line also? It is redundant as L206 already did the job?
