### PR TITLE
[#9751] Feedback Session Edit: Changes are not saved after clicking 'Done Editing' button

### LINKED ISSUE #9751: Feedback Session Edit: Changes are not saved after clicking 'Done Editing' button
- **Environment**: `master` branch at commit 4346f6f3d5ef8bf9570ab088a9835709f13ca99f

**Steps to reproduce**
1. log in as an instructor and go to session page
2. edit a session with existing questions
3. edit one or some questions without clicking any `Save` or `Save Changes` button after editing
4. finally click `Done Editing` button near the bottom

**Expected behaviour**
All changes to the edited questions are saved after clicking `Done Editing`

**Actual behaviour**
The changes are not saved

### PR DESCRIPTION
**Pull request by crizyli**
Fixes #9751

### CODE REVIEW

**Comment by crizyli** [comment]
I have changed to use **alert user that you have unsaved changes** way

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts [hunk 1]
```diff
@@ -796,8 +796,16 @@ export class InstructorSessionEditPageComponent extends InstructorSessionBasePag
   /**
    * Handles 'Done Editing' click event.
    */
-  doneEditingHandler(): void {
-    this.router.navigateByUrl('/web/instructor/sessions');
+  doneEditingHandler(modal: any): void {
+    if (this.questionEditFormModels.some((questionEditFormModel: QuestionEditFormModel): boolean => {
+      return questionEditFormModel.isEditable;
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts]: If there is just one return statement, you can omit the curly bracket. `.some(q => q.isEditable)`

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html [hunk 2]
```diff
@@ -59,3 +59,19 @@
     </div>
   </div>
 </div>
+<ng-template #fieldNotSavedModal let-modal>
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html]: pageNotSavedModal?
