### PR TITLE
[#9346] Use snackbar to show status message

### LINKED ISSUE #9346: Status messages and error messages can be missed by users
- **Environment**: `master` branch at commit ba91074b70129892364b3a6df8e0b3c15c75eae5

**Steps to reproduce**
* Login as instructor
* Go to edit a feedback session page. Sample URL: localhost:4200/web/instructor/sessions/edit?fsname=First%20team%20feedback%20session&courseid=_courseID_
* Click edit, then click save on the first question

**Expected behaviour**
* Any resulting status message appears nearby the question, where it is easily viewable for the user.

**Actual behaviour**
* The status message appears at the very top of the page instead.

**Additional info**

* You can retrieve course IDs from localhost:8080/_ah/admin/datastore?&kind=FeedbackSession&order=\_\_key\_\_

### PR DESCRIPTION
**Pull request by monmanuela**
Fixes #9346 

Status messages will be shown via snackbars (from angular material) so that it is visible to the users without them having to scroll up/down.

Success message:
image

Warning message:
image

Error message:
image

Long messages:
image

### CODE REVIEW

File: src/web/app/page.component.ts [hunk 1]
```diff
@@ -94,10 +89,6 @@ export class PageComponent implements OnInit {
     this.isCookieDisabled = !navigator.cookieEnabled;
   }
 
-  ngOnInit(): void {
-    this.statusMessageService.getAlertEvent().subscribe((result: StatusMessage) => {
-      this.messageList.push(result);
-    });
-  }
+  ngOnInit(): void { }
```
Comment (tanhengyeow) [inline src/web/app/page.component.ts]: Since we are not utilizing `ngOnInit()` at all, let us remove it. A [reference](https://stackoverflow.com/questions/35763730/difference-between-constructor-and-ngoninit) of the difference between `constructor` and `ngOnInit()`

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts [hunk 2]
```diff
@@ -177,18 +177,10 @@ export class InstructorCourseEnrollPageComponent implements OnInit {
...
-          });
+          this.statusMessageService.showSuccessMessage('Enrollment successful. Summary given below.');
           this.enrollResultPanelList = resp.enrollResultPanelList;
         }, (resp: ErrorMessageOutput) => {
-          this.statusMessage.pop(); // removes any existing status message
-          this.statusMessage.push({
-            message: resp.error.message,
-            color: 'danger',
-          });
+          this.statusMessageService.showErrorMessage(resp.error.message);
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: As discussed, let's not do this for the enroll page yet as the output might potentially be a huge chunk of messages.

On that note, can you replicate a huge chunk of error messages and show how it looks like on the snackbar?

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts [hunk 3]
```diff
@@ -177,18 +177,10 @@ export class InstructorCourseEnrollPageComponent implements OnInit {
     this.httpRequestService.post('/course/enrollSave', paramMap, this.enrollData)
         .subscribe((resp: EnrollResultPanelList) => {
           this.showEnrollResults = true;
-          this.statusMessage.pop(); // removes any existing status message
-          this.statusMessage.push({
-            message: 'Enrollment Successful. Summary given below',
-            color: 'success',
-          });
+          this.statusMessageService.showSuccessMessage('Enrollment successful. Summary given below.');
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: Same here.

File: src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts [hunk 4]
```diff
@@ -21,11 +21,13 @@ export class AddCourseFormComponent implements OnInit {
 
   @Input() isEnabled: boolean = true;
   @Output() courseAdded: EventEmitter<void> = new EventEmitter<void>();
+  @ViewChild('courseAddedMessageTemplate') courseAddedMessageTemplate!: TemplateRef<any>;
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts]: Perhaps `newCourseMessageTemplate` would sound better. What do you think?

File: src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts [hunk 5]
```diff
@@ -21,11 +21,13 @@ export class AddCourseFormComponent implements OnInit {
...
 
   timezones: string[] = [];
   timezone: string = '';
   newCourseId: string = '';
   newCourseName: string = '';
+  course: any = null;
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts]: We have `Course` type, let's use that :)

File: src/web/services/status-message.service.ts [hunk 6]
```diff
@@ -1,5 +1,5 @@
-import { Injectable } from '@angular/core';
-import { Observable, Subject } from 'rxjs';
+import { Injectable, TemplateRef } from '@angular/core';
+import { MatSnackBar } from '@angular/material';
 import { StatusMessage } from '../app/components/status-message/status-message';
```
Comment (tanhengyeow) [inline src/web/services/status-message.service.ts]: Do we still need this? Can remove `app/components/status-message/status-message` too.

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts (hunk 2 above)
Comment (monmanuela) [reply src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: It looks terrible 🤣 
image
Will change it back to the normal status message

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts (hunk 3 above)
Comment (monmanuela) [reply src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: Since this message is short, I think the snackbar is suitable. Should I just use the normal status message only for the long chunk of error message related to HOT?

File: src/web/services/status-message.service.ts (hunk 6 above)
Comment (monmanuela) [reply src/web/services/status-message.service.ts]: I'm just using it as the type of the parameter for `showMessage`. I suppose we can do away with it, but I think it looks neater this way.

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts (hunk 2 above)
Comment (monmanuela) [reply src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: Besides this one, I'm not sure which page has a long chunk of error message, seems that the ones I see are at most 1-2 lines long (like the screenshot in the PR description).

**Comment by monmanuela** [comment]
@tanhengyeow Thanks for the review, I made the requested changes!

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts (hunk 2 above)
Comment (tanhengyeow) [reply src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: As long as the places where you switched out status messages -> snackbar are tested with the error variant and don't have similar behavior shown above, it should be good :)

File: src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts (hunk 3 above)
Comment (tanhengyeow) [reply src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts]: Yup, that's fine 👍

File: src/web/services/status-message.service.ts [hunk 7]
```diff
@@ -47,12 +38,45 @@ export class StatusMessageService {
...
+   * Shows a success message containing HTML on the page
+   */
+  showSuccessMessageTemplate(template: TemplateRef<any>): void {
+    this.showTemplate(template, 'snackbar-success');
+  }
+
+  /**
+   * Shows a warning message containing HTML on the page
+   */
+  showWarningMessageTemplate(template: TemplateRef<any>): void {
```
Comment (tanhengyeow) [inline src/web/services/status-message.service.ts]: Although it makes sense to include this in the event we have a need in the future, I feel we should not include it at this point.

Reason: We might not ever need it and if we ever need it in the future, we can add it in easily.

File: src/web/services/status-message.service.ts [hunk 8]
```diff
@@ -47,12 +38,45 @@ export class StatusMessageService {
...
+    this.showTemplate(template, 'snackbar-warning');
+  }
+
+  /**
+   * Shows an error message containing HTML on the page
+   */
+  showErrorMessageTemplate(template: TemplateRef<any>): void {
```
Comment (tanhengyeow) [inline src/web/services/status-message.service.ts]: Same for this.

**Comment by monmanuela** [comment]
@tanhengyeow Thanks for the suggestions above, sounds good 👍 Made the requested changes
