### PR TITLE
[#11001] Migrate App Engine Text datastore type

### LINKED ISSUE #11001: Remove appengine.api.datastore usage after Objectify v6 upgrade
- **Environment**: `objectify-v6-migration` branch

After upgraded Objectify to v6, we should no longer rely on any `com.google.appengine.api.datastore.*` usage.

There are still some leftover code to be cleaned up:
```
import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/FeedbackQuestion.java

import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/FeedbackResponse.java

import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/FeedbackResponseComment.java

import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/FeedbackSession.java

import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/Instructor.java

import com.google.appengine.api.datastore.Text;
in src/main/java/teammates/storage/entity/StudentProfile.java

import com.google.appengine.api.datastore.DatastoreTimeoutException;
in src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java

import com.google.appengine.api.datastore.DatastoreTimeoutException;
in src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java

import com.google.appengine.api.datastore.DatastoreTimeoutException;
in src/main/java/teammates/ui/webapi/WebApiServlet.java

import com.google.appengine.api.datastore.DatastoreTimeoutException;
in src/test/java/teammates/ui/webapi/WebApiServletTest.java

.should().accessClassesThat().haveFullyQualifiedName("com.google.appengine.api.datastore.Text") line510
in src/test/java/teammates/architecture/ArchitectureTest.java
```

### PR DESCRIPTION
**Pull request by jianhandev**
Part of #11001

This PR cleans up existing code which still contain traces using the old `com.google.appengine.api` used before the Objectify 6 migration. 

In Objectify 6, there's no way to explicitly store a `Text` type with the Google-provided SDK. The alternative,`StringValue` does not support `null`. 
- Replace `Text` type from the `com.google.appengine.api.datastore` package used in Objectify 5 with unindexed `String`.

### CODE REVIEW

File: src/main/java/teammates/storage/entity/Instructor.java [hunk 1]
```diff
@@ -205,10 +205,10 @@ public String getInstructorPrivilegesAsText() {
         if (instructorPrivilegesAsText == null) {
             return null;
         }
-        return instructorPrivilegesAsText.getValue();
+        return instructorPrivilegesAsText.get();
     }
 
     public void setInstructorPrivilegeAsText(String instructorPrivilegesAsText) {
-        this.instructorPrivilegesAsText = new Text(instructorPrivilegesAsText);
+        this.instructorPrivilegesAsText = new StringValue(instructorPrivilegesAsText);
```
Comment (Derek-Hardy) [inline src/main/java/teammates/storage/entity/Instructor.java:212]: You probably need a null check here.

```java
if (instructorPrivilegesAsText == null) {
    this.instructorPrivilegesAsText = null;
} else {
    this.instructorPrivilegesAsText = new StringValue(instructorPrivilegesAsText);
}
```

**Review by Derek-Hardy — CHANGES_REQUESTED** [review]

File: src/main/java/teammates/storage/entity/Instructor.java (hunk 1 above)
Comment (Derek-Hardy) [inline src/main/java/teammates/storage/entity/Instructor.java:212]: Probably you need a null check here?

e.g.
```java
if (instructorPrivilegesAsText == null) {
    this.instructorPrivilegesAsText = null;
} else {
    this.instructorPrivilegesAsText = new StringValue(instructorPrivilegesAsText);
}
```

**Review by wkurniawan07 — COMMENTED** [review]
Also, is it possible to just use `String` type?

File: src/main/java/teammates/storage/entity/Instructor.java (hunk 1 above)
Comment (jianhandev) [reply src/main/java/teammates/storage/entity/Instructor.java:212]: Right, `StringValue` unlike `Text` does not support null value. I was thinking can construct `StringValue` using an empty string instead whenever `instructorPrivilegesAsText` is null, but this still results in many test failures. Also considering the use of `String` type as suggested by @wkurniawan07 without indexing, perhaps that would be a better solution.

File: src/main/java/teammates/storage/entity/Instructor.java [hunk 2]
```diff
@@ -52,7 +52,7 @@
     @Unindex
     private String displayedName;
 
-    private Text instructorPrivilegesAsText;
+    private StringValue instructorPrivilegesAsText;
```
[the remark this answers is not in the document]
Comment (jianhandev) [reply src/main/java/teammates/storage/entity/Instructor.java:55]: I was pondering over this for a while too! I read that for text strings longer than 1500 bytes (which are not indexed), we should use a `Text` instance but it is no longer available now. `@Unindex` can be added to overcome the 1500 bytes limit.

**Review by Derek-Hardy — APPROVED** [review]
LGTM

File: src/main/java/teammates/storage/entity/FeedbackQuestion.java [hunk 3]
```diff
@@ -145,19 +144,19 @@ public void setCourseId(String courseId) {
     }
 
     public String getQuestionMetaData() {
-        return questionText == null ? null : questionText.getValue();
+        return questionText == null ? null : questionText;
     }
 
     public void setQuestionText(String questionText) {
-        this.questionText = questionText == null ? null : new Text(questionText);
+        this.questionText = questionText == null ? null : questionText;
```
Comment (wkurniawan07) [inline src/main/java/teammates/storage/entity/FeedbackQuestion.java:151]: For all these getters and setter you can just return or set as is, because there is no object wrapper anymore

File: src/main/java/teammates/storage/entity/Instructor.java [hunk 4]
```diff
@@ -52,7 +51,8 @@
     @Unindex
     private String displayedName;
 
-    private Text instructorPrivilegesAsText;
+    @Unindex
+    private String instructorPrivileges;
```
Comment (wkurniawan07) [inline src/main/java/teammates/storage/entity/Instructor.java:55]: This is backward-incompatible and will require data migration. Let's not change the field name.

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]

**Review by wkurniawan07 — APPROVED** [review]

**Review by Derek-Hardy — APPROVED** [review]
