### PR TITLE
Wait until element appear / disappear as opposed to a fixed delay in InstructorFeedbackResultsPage #4720

### LINKED ISSUE #4720: Wait until element appear / disappear as opposed to a fixed delay in InstructorFeedbackResultsPage
Change the tests which toggle the visibility of elements to wait until the element appears / disappears as opposed to waiting for a fixed delay for the method verifyAllResultsPanelBodyVisibility in InstructorFeedbackResultsPage.

### PR DESCRIPTION
**Pull request by kennho**
Fixes #4720

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 1]
```diff
@@ -496,19 +496,21 @@ public void testPanelsCollapseExpand() {
...
-        assertTrue(resultsPage.verifyAllResultsPanelBodyVisibility(false));
+        assertTrue(resultsPage.areResultsHidden());
 
         resultsPage.clickCollapseExpand();
+        resultsPage.waitForPanelsToExpand();
         assertEquals("Collapse Questions", resultsPage.collapseExpandButton.getText());
         assertEquals("Collapse all panels. You can also click on the panel heading to toggle each one individually.",
                      resultsPage.collapseExpandButton.getAttribute("data-original-title"));
-        assertTrue(resultsPage.verifyAllResultsPanelBodyVisibility(true));
+        assertTrue(resultsPage.areResultsVisible());
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java]: If all the methods are wrapped with `assertTrue(...)`, consider renaming the method to `verifyResultsVisible/Hidden` instead and move the assertions to the respective methods.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 2]
```diff
@@ -210,20 +210,61 @@ public void clickVisibilityOptionForResponseCommentAndSave(String idString, int
...
 
-        for (WebElement e : browser.driver.findElements(By.cssSelector(".panel-heading+.panel-collapse"))) {
-            if (e.isDisplayed() != visible) {
+    /**
+     * Checks if the body of all the result panels are hidden
+     * @return true if all result panel body are hidden
+     */
+    public boolean areResultsHidden() {
+        return isAllResultsPanelBodyVisibilityEquals(false);
+    }
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Be careful here. The negation of "for all x, y applies" is "there exists x such that y does not apply". Your method name and javadoc imply "for all x, y does not apply" which is wrong.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 3]
```diff
@@ -210,20 +210,61 @@ public void clickVisibilityOptionForResponseCommentAndSave(String idString, int
...
                 return false;
             }
         }
+        
         return true;
     }
+    
+    /**
+     * Method to wait for all the panels to collapse.
+     */
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: You don't need to mention "Method to" in header comments. Typically header comment for methods starts with a verb (and, if you want to be strict about the grammar, in its -s form).

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java (hunk 2 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Oops ignore that, I just read the implementation of the extracted method.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 4]
```diff
@@ -210,20 +210,61 @@ public void clickVisibilityOptionForResponseCommentAndSave(String idString, int
...
         return true;
     }
+    
+    /**
+     * Method to wait for all the panels to collapse.
+     */    
+    public void waitForPanelsToCollapse() {
+        List<WebElement> panelBodies = browser.driver.findElements(By.cssSelector("div[id^='panelBodyCollapse-']"));
+        waitForElementsVisibility(panelBodies);
+        ThreadHelper.waitFor(1000);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Any idea what this wait is for?

**Comment by wkurniawan07** [comment]
Added some comments to work on. You can now change the status label to `s.ToReview` yourself when you're ready, or just mention me as per usual (or both :p)

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java (hunk 4 above)
Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: This wait makes the test slow down quite a lot, and can be improved. Can probably improve this method to check the visibility of the body content of the panel body, or wait for the panel to have the classes "collapse in", or something better. The panelBody becomes visible in the middle of expansion, and isn't necessarily fully expanded yet. The guy who originally implemented this definitely added the waitFor here just so the tests could pass, and meant for this to be fixed later, but then forgot to make an issue for it. :P

Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: And guess who that guy is...

Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: :D

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 1 above)
Comment (kennho) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java]: I have made this change as it was suggested in PR #4664 and the thing I am fixing here is to solve a similar problem face in PR #4664 @wkurniawan07 

Should I change it back to start with verify or keep this as it is?

**Comment by kennho** [comment]
Updated with suggested changes @wkurniawan07

**Comment by damithc** [comment]
@kennho remember to change the label too. Some of use label filters to identify action items.

**Comment by kennho** [comment]
Sorry keep forget to change the label! Will remember next time.

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 1 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java]: What I meant was:
```java
/**
 * Boolean-returning method, named is* or are* or ...
 */
public boolean isCondition() {
	return condition;
}

/**
 * Asserting method, named verify*
 */
public void verifyCondition() {
	assertTrue(condition);
}
```
I suggested 2 instead because all the usages of the boolean method involve `assertTrue(...)` only. If there are some `assertFalse(...)` usages then it's right that it has to be 1. You could consider doing the same for the other PR.

**Comment by kennho** [comment]
Updated with the suggested changes. As for the waitFor method, I didn't include it in another PR when I have to wait for the panels to collapse / expand. It is working fine without it. I have tested it here too. So far no problems yet. I think it's quite redundant to add the waitFor there as the method will already wait for the panel to appear / disappear. The waitFor will only increase the waiting time to be very very sure that the panels will appear / disappear. If it's really needed then maybe should I just reduce the waiting time from 1000 to say.. 500? @wkurniawan07

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 5]
```diff
@@ -209,21 +209,76 @@ public void clickVisibilityOptionForResponseCommentAndSave(String idString, int
...
 
-        for (WebElement e : browser.driver.findElements(By.cssSelector(".panel-heading+.panel-collapse"))) {
-            if (e.isDisplayed() != visible) {
+    /**
+     * Checks if the body of all the result panels are hidden
+     * @return true if all result panel body are hidden
+     */
+    public boolean areResultsHidden() {
+        return isAllResultsPanelBodyVisibilityEquals(false);
+    }
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: These two `areResults*` functions are called only by their respective `verifyResults*` counterparts here, so consider making them private.
Alternatively, you can move the entire condition to the `verifyResults*`, something like:
```java
public void verifyResultsVisible() {
    assertTrue(isAllResultsPanelBodyVisibilityEquals(true));
}
```

**Comment by wkurniawan07** [comment]
One minor improvement and it's good to go :+1:
As for the `waitFor` thing, I'll trust your judgment so we can remove it here, if it gives problems in the future we can revisit it in another issue.

**Comment by kennho** [comment]
Updated with the suggested changes @wkurniawan07

**Comment by wkurniawan07** [comment]
Looks good now :+1:

**Comment by wkurniawan07** [comment]
I got failures in `FeedbackRubricQuestionUiTest` and `FeedbackRankQuestionUiTest`. I think you'd have to change all the wait for collapses there to wait for expands, similar to what you've done here.

**Comment by kennho** [comment]
Ran the full test and changed the affected parts. Didn't notice that. Sorry for the trouble! @wkurniawan07

**Comment by wkurniawan07** [comment]
No worries there, in fact that only confirms my thoughts that #3554 needs to be done soon.
