### PR TITLE
InstructorStudentRecordsPageUiTest: improve stability #8059

### LINKED ISSUE #8059: InstructorStudentRecordsPageUiTest: improve stability
The value of the class attribute varies and is dependent on timing of clicks as well as browser. A Chrome-specific workaround was added in #7700 but broken in #7989, prompting development of another fix in #8043. However, this has proven [unstable](https://travis-ci.org/TEAMMATES/teammates/builds/279849671). Too much effort has been spent trying to keep the HTML verification consistent across systems for this particular test case. Let's ~~modify `HtmlHelper` to completely ignore the value instead~~ change the test case to avoid HTML verification after editing the comment to empty.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8059

**Outline of Solution**
Move edit-to-empty-comment test case after test cases involving HTML verification.

### CODE REVIEW

File: src/test/java/teammates/test/driver/HtmlHelper.java [hunk 1]
```diff
@@ -249,6 +257,10 @@ private static boolean isTinymceStyleAttribute(Node attribute) {
         return checkForAttributeWithSpecificValue(attribute, "id", "mceDefaultStyles");
     }
 
+    private static boolean isTinymceEditorAttribute(Node attribute) {
+        return checkForAttributeWithSpecificValue(attribute, "class", "content-editor");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/driver/HtmlHelper.java]: Maybe better if the selector is `mce-content-body`? The probability of us self-authoring something with class `mce-*` is close to zero, but `content-editor` sounds somewhat probable.

**Comment by wkurniawan07** [comment]
@whipermr5 we should get this one done as soon as possible.
