### PR TITLE
[#9707] Add New Feedback Session: Default selected course ID in the form is incorrect

### LINKED ISSUE #9707: Add New Feedback Session: Default selected course ID in the form is incorrect
- **Environment**: 
`master` branch at commit 18040a23ac6a5db5c0a251a7a0d7bfb19db468fb

**Steps to reproduce**

1. Log in as instructor
2. Under any course header that is not the first, click **Sessions** then **Add**
image

3. The selected course ID defaults to the first course.
image

**Expected behaviour**
The selected course ID should be the same as where the **Sessions** button was clicked from.

**Actual behaviour**
The selected course ID defaults to the first course alphabetically.

### PR DESCRIPTION
**Pull request by erjillsison**
Fixes #9707

**Outline of Solution**
Make use of the specified course id in the query param and set the form defaults to that course.

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts [hunk 1]
```diff
@@ -182,8 +184,14 @@ export class InstructorSessionsPageComponent extends InstructorSessionBasePageCo
    * Sets default values for the session edit form.
    */
   initDefaultValuesForSessionEditForm(): void {
-    // select the first course by default
-    if (this.courseCandidates.length !== 0) {
+    // if specified in the query and is valid, select that course
+    // otherwise, select the first course by default
+    const course: any = this.getCourseFromList(this.courseId);
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts]: I think you can inline the method `getCourseFromList`. It's more clear.

`any` -> `Course | undefined`

Comment (erjillsison) [reply src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts]: Makes sense. Updated.
