### PR TITLE
[#12551] Sessions page fix

### LINKED ISSUE #12551: Instructor Session Page: Failed copy feedback session causes page to load forever.
- **Environment**: 
`master` branch at commit `8633d4e`

**Problem**
The issue is similar/identical to the issue #12507. 
When we try to copy the feedback session, if it fails, it will lead to the page loading forever. The only way to stop it is through hard refresh or navigating to another page. 

**Steps to reproduce**
1. Go to instructor session page. 
2. Click on `Copy` for any available session.
3. Select the same course as the selected session.
image
4. Click `Copy`.

**Expected behaviour**
- Error toast to be shown
- Session table should be generated.

**Actual behaviour**
Page goes into a loading state forever. 

<ins>Video Demo of Actual Behaviour</ins>
https://github.com/TEAMMATES/teammates/assets/66376253/74e424cd-ef1c-4d02-9aef-7d0d9199277c

**Additional info**

As mentioned, this issue is similar to issue #12507. 
To resolve this issue, look at PR #12550

### PR DESCRIPTION
**Pull request by DamiGbs**
Fixes #12551

**Outline of Solution**
Did the same as in PR #12550. Only that i added a error Toast:
image

### CODE REVIEW

**Comment by weiquu** [comment]
Hi @DamiGbs, thanks for submitting this PR. I noted that there are a lot of formatting changes introduced. Do revert those changes in accordance to our [documentation](https://teammates.github.io/teammates/process.html#step-3-fix-the-issue), which states under point 3 that "no unrelated changes are [to be] introduced in the branch. This includes unnecessary formatting changes". As far as I can tell, the relevant changes are only to 5 lines.

Do also note that we typically align multi-line parameters to the first parameter (e.g. line 109), or add an additional tab to indicate that the parameter list is still ongoing. When we chain operations together on a variable, we also either align to the first operation or add an additional tab as a visual indicator (e.g. line 164).

We will proceed to review your PR after the changes have been made.

**Comment by DamiGbs** [comment]
Hi @weiquu, should be fixed now. Looks like i had a different formatter in VsCode that changed the whole formatting of the code.

File: src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts [hunk 1]
```diff
@@ -504,7 +504,12 @@ export class InstructorSessionsPageComponent extends InstructorSessionModalPageC
     const requestList: Observable<FeedbackSession>[] = this.createSessionCopyRequestsFromRowModel(
         this.sessionsTableRowModels[result.sessionToCopyRowIndex], result);
     if (requestList.length === 1) {
-      this.copySingleSession(requestList[0], this.modifiedTimestampsModal);
+      this.copySingleSession(requestList[0].pipe(finalize(() => {
+        this.isCopySessionLoading = false;
+        if (Object.keys(this.failedToCopySessions).length > 0) {
+          this.statusMessageService.showErrorToast(this.getCopyErrorMessage());
+        }
```
Comment (cedricongjh) [inline src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts:511]: This can be removed as the error toast already shows without it

**Review by cedricongjh — CHANGES_REQUESTED** [review]
Hi @DamiGbs, thank you for your PR, do make the requested changes and re-request for a review!

**Review by cedricongjh — APPROVED** [review]
LGTM! Thank you for your contribution to TEAMMATES

**Review by jasonqiu212 — APPROVED** [review]
LGTM!
