### PR TITLE
Feedback Session: Remove 'Never Publish' option #8468

### LINKED ISSUE #8468: Feedback Session: Remove 'Never Publish' option
**Environment:**
`master` branch.
Don't know if this is a bug or intentional. So, went along with the bug template.
**Steps to reproduce:**
- Login as `Instructor`
- Create a new session, set a Opening time so earlier than current time, to get a `Open` session
- Set the option `Responses visible from` to `Never`. 
- Now go back to `Home` or `Sessions`, and find the session you created in the session table
- Open the drop down button in `Results` action, or go to Results page and click `Publish Results`

**Expected behaviour:** There should be a error message that the session can not be published as the session is set to never get published. Or, the `Publish Results` button should be disabled.

**Actual behaviour:** The session gets successfully published.

I think the proper steps to publish results for these kind of sessions should be, `Edit` -> `Responses visible from` -> Any option other than `Never` -> `Save Changes`.

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8468 <br>
**Outline of Solution**
- Changed `Publish manually` -> `Not now (publish manually)` in the Feedback form UI
- Removed the option Never (`never`) and replaced with Publish manually (`later`)
- Changed the `InstructorHelpPage` to make it consistent with the current UI

UI change :
**Before :**
screenshot 358

**After:**
screenshot 377

**<s>Status: Ongoing</s>**

### CODE REVIEW

**Comment by sukanta-27** [comment]
@whipermr5 Ready for a review

**Comment by sukanta-27** [comment]
@whipermr5 Yes! There were three more constants in the `Const.java` related this issue, which I overlooked. :sweat_smile: Fixed now.

**Comment by sukanta-27** [comment]
@whipermr5 A gentle reminder. This is ready for review.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 1]
```diff
@@ -960,10 +960,12 @@ private void testValidationReload() throws Exception {
         newSession.setFeedbackSessionName("");
         newSession.setEndTime(Const.TIME_REPRESENTS_LATER);
         feedbackPage.clickEditUncommonSettingsButtons();
-        feedbackPage.clickNeverPublishTimeButton();
+        feedbackPage.clickCustomPublishTimeButton();
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Any problems setting this to manual instead?

File: src/test/java/teammates/test/cases/action/InstructorFeedbackEditSaveActionTest.java [hunk 2]
```diff
@@ -139,14 +139,14 @@ public void testExecuteAndPostProcess() {
                 + "<Text: instructions>|||/page/instructorFeedbackEditSave";
         AssertHelper.assertLogMessageEquals(expectedString, a.getLogMessage());
 
-        ______TS("success: Masquerade mode, never release results, invalid timezone and graceperiod");
+        ______TS("success: Masquerade mode, 'custom' release results, invalid timezone and graceperiod");
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackEditSaveActionTest.java]: Use `manual` instead of `'custom'`?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java (hunk 1 above)
Comment (sukanta-27) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: The test tests the functionality where the advance settings will still be visible even if the input is rejected. But the advance option is shown only when any of the options has a non-default value.
https://github.com/TEAMMATES/teammates/blob/49386feafec7ca2cb6fdeca32ad1112d4fda962f/src/main/webapp/dev/js/common/instructorFeedbacks.js#L51-L54

`later` is the default value for response visible time. That is why using manual here will cause this line to fail.
`assertTrue(feedbackPage.isVisible(By.id("responsesVisibleFromColumn")));`

https://github.com/TEAMMATES/teammates/blob/49386feafec7ca2cb6fdeca32ad1112d4fda962f/src/main/webapp/dev/js/common/instructorFeedbacks.js#L24-L27

File: src/test/java/teammates/test/cases/action/InstructorFeedbackEditSaveActionTest.java (hunk 2 above)
Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackEditSaveActionTest.java]: Sorry my bad. The actual test is set as manual only. Will fix it.

**Comment by sukanta-27** [comment]
@whipermr5 ready for review

**Comment by sukanta-27** [comment]
@whipermr5 A reminder :sweat_smile:

**Comment by sukanta-27** [comment]
@whipermr5 All conflicts have been resolved. This is ready for review.

**Comment by sukanta-27** [comment]
@damithc Sir I don't think this should affect the private session. It is removing never option from the `results visible time`. @whipermr5 can confirm this? 

The remove private session issue is #8447

**Comment by whipermr5** [comment]
Yup; @sukanta-27 is right. Though I also mixed the two issues up before haha: https://github.com/TEAMMATES/teammates/issues/8468#issuecomment-366637173

**Comment by sukanta-27** [comment]
@whipermr5 Done.

**Comment by whipermr5** [comment]
@sukanta-27 Oops, I just realised we didn't update the test data JSON files. Need to do a search and replace for the string `"resultsVisibleFromTime": "1970-11-27T00:00:00Z"`. Can you open an issue for it?

**Comment by sukanta-27** [comment]
@whipermr5 I should have thought about the JSON files. Sorry for that. :man_facepalming: 

>Can you open an issue for it?

Of course. Opening right now.
