### PR TITLE
AdminLogQueryTest : Fix PMD problem #8459

### LINKED ISSUE #8459: AdminLogQueryTest : Fix PMD problem
The following line in `AdminLogQueryTest.java` has a PMD problem.
https://github.com/TEAMMATES/teammates/blob/3e484a84ee695ce39e31f173ff7e674614fa3742/src/test/java/teammates/test/cases/util/AdminLogQueryTest.java#L35

The PMD problem is : 
`Use assertSame(x, y) instead of assertTrue(x==y), or assertNotSame(x,y) vs assertFalse(x==y)`

Use <s>`assertNotSame`</s> `assertNotEquals` instead of `assertTrue` to fix this.

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8459

### CODE REVIEW

File: src/test/java/teammates/test/cases/util/AdminLogQueryTest.java [hunk 1]
```diff
@@ -32,7 +33,7 @@ public void testAdminLogQuery() {
         ______TS("Test setTimePeriod");
         query = new AdminLogQuery(versionList, null, null);
         assertEquals(0, query.getStartTime());
-        assertTrue(endTime != query.getStartTime());
+        AssertJUnit.assertNotSame(endTime, query.getStartTime());
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/util/AdminLogQueryTest.java]: `assertNotSame` checks that the two objects don't refer to the same Object, not checking for inequality. If you want to fix this issue, the correct assertion to use is `assertNotEquals`, and you should define that method in `BaseTestCase` as what have been done for all the used assertion methods.

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/util/AdminLogQueryTest.java]: Okay.

**Comment by sukanta-27** [comment]
Ready for review.
