### PR TITLE
[#11551] Fix incorrect loading message (rework)

### LINKED ISSUE #11551: Tables showing incorrect message after loading
When loading the home page, after the spinner has disappeared, the course shows the standard "Currently, there is no open feedback/response.." briefly, before displaying the actual results.
The bug seems to affect other tables that need to be populated with data from the backend too (e.g Instructor's Students page)

https://user-images.githubusercontent.com/10182564/151970902-cf626287-0c2a-4411-8830-9edd5c0f068e.mp4

- **Environment**: 
Live server V8.6.0, able to replicate on both the latest versions of Firefox and Chrome.

**Steps to reproduce**
1. Log in as Instructor or Student
2. Go to / Reload the home page

**Expected behaviour**
The displaying of the table's data should be accurate the moment the spinner stops.

**Actual behaviour**
The table shows the equivalent of 'no entries' after the spinner stops briefly, then displays the correct data.

### PR DESCRIPTION
**Pull request by fsgmhoward**
Fixes #11551

The original PR #11563 did not fix the issue completely. It moved the assignment of value to `isCourseLoading` after the sessions are loaded. This works only the case when there is 1 course.

When there are multiple courses, the first course that finish loading sessions will set `isCourseLoading = false` and therefore all remaining courses will be displayed with the wrong message again.

This PR reworks the mechanism of this. It adds a `isFeedbackSessionLoading` and `hasFeedbackSessionLoadingFailed` to every single courses. Loading of sessions will be independent and will have their own spinner/retry button now. For more information, see the recording below.

Before:

11551-before

After:

11551-after

When it loads the courses successfully but failed to load the sessions:

11551-dedicated-fail

### CODE REVIEW

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts [hunk 1]
```diff
@@ -94,67 +96,81 @@ export class StudentHomePageComponent implements OnInit {
...
-                  this.statusMessageService.showErrorToast(this.allStudentFeedbackSessionsNotReturned);
-                  this.hasCoursesLoadingFailed = true;
-                  return;
-                }
+        this.feedbackSessionsService.hasStudentResponseForAllFeedbackSessionsInCourse(courseId)
+          .pipe(finalize(() => { courseRef.isFeedbackSessionsLoading = false; }))
+          .subscribe((hasRes: HasResponses) => {
+            if (!hasRes.hasResponsesBySession) {
+              this.statusMessageService.showErrorToast(this.allStudentFeedbackSessionsNotReturned);
+              this.hasCoursesLoadingFailed = true;
```
Comment (samuelfangjw) [inline src/web/app/pages-student/student-home-page/student-home-page.component.ts:138]: Should this be `hasFeedbackSessionsLoadingFailed` instead? At this point courses should already be loaded. There's one more on line 150 that should probably be changed as well.

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts [hunk 2]
```diff
@@ -94,67 +96,81 @@ export class StudentHomePageComponent implements OnInit {
...
+            courseRef.hasFeedbackSessionsLoadingFailed = true;
             this.statusMessageService.showErrorToast(error.error.message);
           });
-      }
-    }, (e: ErrorMessageOutput) => {
-      this.hasCoursesLoadingFailed = true;
-      this.statusMessageService.showErrorToast(e.error.message);
-    });
+      }, (error: ErrorMessageOutput) => {
+        courseRef.isFeedbackSessionsLoading = false;
```
Comment (samuelfangjw) [inline src/web/app/pages-student/student-home-page/student-home-page.component.ts:170]: Is changing this to false necessary? Default value is currently true.

**Review by samuelfangjw — CHANGES_REQUESTED** [review]

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts (hunk 1 above)
Comment (fsgmhoward) [reply src/web/app/pages-student/student-home-page/student-home-page.component.ts:138]: Thanks for pointing that out. I have changed them in the next commit.

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts (hunk 2 above)
Comment (fsgmhoward) [reply src/web/app/pages-student/student-home-page/student-home-page.component.ts:170]: Yes it is necessary (though not strictly). Because this is the outer subscription, it will not finalize with `isFeedbackSessionsLoading` set to false (that is set as the inner subscription's finalize method). Therefore, if the outer subscription encounters an error (so inner subscription is not executed), it needs to set the loading to false to indicate an end of the loading process.

Without this, the retry button will still be shown properly as that is the outer element of the loading spinner and probably the page will be the same, but with this set of value which is kind of weird to me:
```
courseRef.isFeedbackSessionsLoading == true;
courseRef.hasFeedbackSessionsLoadingFailed == true;
```

**Review by samuelfangjw — APPROVED** [review]

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts [hunk 3]
```diff
@@ -94,67 +96,81 @@ export class StudentHomePageComponent implements OnInit {
...
+      .pipe(finalize(() => { this.isCoursesLoading = false; }))
+      .subscribe((resp: Courses) => {
+        for (const course of resp.courses) {
+          this.courses.push({
+            course,
+            feedbackSessions: [],
+            isFeedbackSessionsLoading: true,
+            hasFeedbackSessionsLoadingFailed: false,
+          });
+          this.courses.sort((a: StudentCourse, b: StudentCourse) =>
```
Comment (FergusMok) [inline src/web/app/pages-student/student-home-page/student-home-page.component.ts:109]: Would it be possible to sort once outside the loop, instead of sorting after each push?

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts [hunk 4]
```diff
@@ -94,67 +96,81 @@ export class StudentHomePageComponent implements OnInit {
...
+   */
+  loadFeedbackSessionsForCourse(courseId: string): void {
+    // reference to the course within the this.courses array
+    const courseRef = this.courses.find((c) => c.course.courseId === courseId)!;
+    courseRef.isFeedbackSessionsLoading = true;
+    courseRef.hasFeedbackSessionsLoadingFailed = false;
+    this.feedbackSessionsService.getFeedbackSessionsForStudent('student', courseId)
+      .subscribe((fss: FeedbackSessions) => {
+        const sortedFss: FeedbackSession[] = this.sortFeedbackSessions(fss);
+        const studentSessions: StudentSession[] = courseRef.feedbackSessions;
```
Comment (FergusMok) [inline src/web/app/pages-student/student-home-page/student-home-page.component.ts:131]: Is this equivalent to `const studentSessions: StudentSession[] = []`? As the courseRef.feedbackSessions was just initialized

**Review by FergusMok — COMMENTED** [review]
Thanks for the quick fix, sorry for the delay in reviewing

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts (hunk 3 above)
Comment (fsgmhoward) [reply src/web/app/pages-student/student-home-page/student-home-page.component.ts:109]: Yep. I think that will be reasonable as well. Probably can sort it at the finalize method. Thanks for pointing it out.

File: src/web/app/pages-student/student-home-page/student-home-page.component.ts (hunk 4 above)
Comment (fsgmhoward) [reply src/web/app/pages-student/student-home-page/student-home-page.component.ts:131]: No it is not equivalent. This `studentSessions` store the **reference** to the `courseRef.feedbackSessions`. So adding sessions to it will be added to `courseRef.feedbackSessions` and therefore be reflected in the display.

**Review by FergusMok — APPROVED** [review]
LGTM thanks
