### PR TITLE
[#11079] Migrate remaining usages of internal App Engine APIs

### LINKED ISSUE #11079: Migrate remaining usages of internal App Engine APIs
As part of https://github.com/TEAMMATES/teammates/projects/8

After all bundled services are migrated, there are only a few usages of `com.google.appengine.api.*` and `com.google.apphosting.api.*` left that needs to be changed to equivalent implementations:
- `com.google.appengine.api.utils.SystemProperty` and `com.google.apphosting.api.ApiProxy` in `Config.java`.
- `com.google.appengine.api.appidentity.AppIdentityServiceFactory` in `DatastoreBackupAction.java`.
- `com.google.apphosting.api.DeadlineExceededException` in a few places. Note that this is an Exception to be handled and never thrown by our own code, and there is no equivalent exception outside of GAE SDK, so this can be a safe removal.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #11079 

After this PR it can be confirmed that there are no more references to `com.google.appengine.api.*` and `com.google.apphosting.api.*`, other than `com.google.appengine.api.users.*` (will be resolved in #11073) and `com.google.appengine.api.search.*` (will be resolved in #11064).

### CODE REVIEW

File: src/main/java/teammates/common/util/Config.java [hunk 1]
```diff
@@ -132,7 +131,22 @@ static String getBaseAppUrl() {
...
+        String version = System.getenv("GAE_VERSION");
+        String env = System.getenv("GAE_ENV");
+
+        if (appName == null || version == null || env == null) {
+            return true;
+        }
+
+        return !appName.endsWith(APP_ID)
+                || !version.replace("-", ".").equals(APP_VERSION)
+                || !"standard".equals(env);
```
Comment (Derek-Hardy) [inline src/main/java/teammates/common/util/Config.java:147]: `!env.equals("standard")` seems to be a more consistent style?

**Review by Derek-Hardy — APPROVED** [review]
LGTM

File: src/main/java/teammates/common/util/Config.java (hunk 1 above)
Comment (wkurniawan07) [reply src/main/java/teammates/common/util/Config.java:147]: Not really. Literals are usually placed on the left to prevent NPE. So in this case I modify the line just above this.
