### PR TITLE
Average Rank Excluding Self calculation not intuitive to users #8280

### LINKED ISSUE #8280: Average Rank Excluding Self calculation not intuitive to users
**Description of feature/enhancement**
The `Average Rank Excluding Self` is calculated from the normalized ranks of the ranks which have already excluded the self-ranks. However, in my opinion, it makes more sense to use the normalized ranks of ranks which haven't excluded the self-ranks to calculate the average.

The example below is formatted into excel sheet from the expected result of JUnit test testing method `getFeedbackSessionResultsSummaryAsCsv` in class `FeedbackSessionsLogicTest`. Inside the summary, the `Average Rank Excluding Self` in the selected line is calculated to be 1(Credit to @joanneong who discovered this unexpected number). We should expect the number to be calculated as `(the sum of the ranks received - self rank) / the number of non-self ranks received`, which results in 1.5, instead of 1.
image

The steps below outlines the calculation done in the current implementation:
1. extract the non-self-ranks from the raw data, which means, out of the 8 ranks given in the responses, the 4 self-ranks are ignored
2. normalize these 4 non-self-ranks. This means the unrated are ignored and ties are resolved.
E.g. given the two responses below (the arrays used below are only for illustration purpose),
`[giver=student3, recipient=student4, answer=4]`, and
`[giver=student3, recipient=student3, answer=3]`, 
if there is no removal of the self-rank, the normalized result will become
`[giver=student3, recipient=student4, answer=4, rankAfterNormalization=2]`, and
`[giver=student3, recipient=student3, answer=3, rankAfterNormalization=1]`.
Therefore, if the removal is done before the normalization, only the non-self-rank `[giver=student3, recipient=student4, answer=4]` will be normalized and resulting in `[giver=student3, recipient=student4, answer=4, rankAfterNormalization=1]`, which in turn leads to the `Average Rank Excluding Self = 1` instead of 1.5.

**Justification**

As explained above, the calculation for `Average Rank Excluding Self` is not intuitive enough for the users and there is no mention of it in documentation. Hence it will confuse the users and get inaccurate feedback results.

### PR DESCRIPTION
**Pull request by wenmogu**
Fixes #8280 

**Outline of Solution**
Revamped the system as described below:

- Logic: changed the `Average Rank` to `Overall Rank` which is essentially the rankings of the `Average Rank`s.  Reason for choosing not to adopt the "Olympiad Medal Ranking" way: If in the feedback session, recipient A received 1,4,4,4 and recipient B received 2, then recipient A will have a smaller overall ranking than B, despite that A received more ranks of large numbers (we can choose to interpret the large rank as "low opinion" and the small rank as "high opinion", or the other way round). 

-UI: changed the UI accordingly

-Test: changed the expected test data accordingly

-Documentation: Ongoing. Meanwhile @joanneong is in the process of migrating and updating the [detailed documentation](https://docs.google.com/document/d/1hjQQHYM3YId0EUSrGnJWG5AeFpDD_G7xg_d--7jg3vU/pub?embedded=true#h.n5u2xs6z9y0g) from google doc to a page in TEAMMATES. Brief explanations for the rank questions are given on `InstructorHelpPage`. 

The trivial issue #8334 is also fixed in this pr.

### CODE REVIEW

File: src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java [hunk 1]
```diff
@@ -144,6 +144,35 @@ protected double computeAverage(List<Integer> values) {
         return normalisedRankForSingleSetOfRankings;
     }
 
+    /**
+     * Generate the normalized overall ranking from the ranks of the recipients or options
+     * by comparing the average ranks of the recipients or options
+     * E.g. A and B received (1,2) and C received (1,2,3),
+     * so A and B have the average rank of 1.5 and C's average rank is 2
+     * After normalization, the overall rank of A, B and C will be 1, 1 and 3
+     * @param recipientRanks is a map
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java]: Give javadoc for the return value also :)

File: src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java [hunk 2]
```diff
@@ -254,23 +253,26 @@ public String getQuestionResultStatisticsHtml(
...
-            double average = computeAverage(ranks);
             String ranksReceived = getListOfRanksReceivedAsString(ranks);
-
+            String overallRank = Integer.toString(recipientOverallRank.get(participantIdentifier));
             String name = bundle.getNameForEmail(participantIdentifier);
             String teamName = bundle.getTeamNameForEmail(participantIdentifier);
-            String userAverageExcludingSelfText =
-                    getAverageExcludingSelfText(df, recipientRanksExcludingSelf, participantIdentifier);
+            String overallRankExceptSelf = recipientOverallRankExceptSelf.containsKey(participantIdentifier)
+                    ? Integer.toString(recipientOverallRankExceptSelf.get(participantIdentifier)) : "-";
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: Do we have test cases covered for this condition - Overall rank return `-` instead of a rank? Similar question for other place in your PR

Comment (wenmogu) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: Thx for the review! This case, namely the return of `-` in absence of data for `Overall Rank Except Self` is covered for a rank recipient question test in `FeedbackSessionsLogicTest`. The absence of data for `Overall Rank` of an option/ recipient will result in the absence of this option/recipient in the statistic summary shown, and I just edited one of the two test cases for `Rank Question` to include this scenario.

**Comment by xpdavid** [comment]
@wenmogu You have added the test data, but according to the changes, there still no expected `-` in the integration test or end-to-end test?

https://github.com/TEAMMATES/teammates/pull/8400/files/be1c476d4eeb2ed1519439986cabad34bd7edf58..d6553401ee215dad4af46e8206e769b355934b53

File: src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java (hunk 2 above)
Comment (xpdavid) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: I see. That means that `-` will never be shown right?

Comment (wenmogu) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: Emmmmm `-` for `Overall Rank Except Self` is shown when there is no other people ranking this recipient excluding himself. 
image

Comment (xpdavid) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: @wenmogu Then can u add that test cases?

Comment (wenmogu) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: oh the[ old test case at `FeedbackSessionLogicTest` line 1845](https://github.com/TEAMMATES/teammates/pull/8400/files#diff-9a00a8a9d3c36abb0f74c76ffe4946f3L1845) actually suffices :D

Comment (xpdavid) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java]: You are correct :)

File: src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java [hunk 3]
```diff
@@ -144,6 +144,36 @@ protected double computeAverage(List<Integer> values) {
         return normalisedRankForSingleSetOfRankings;
     }
 
+    /**
+     * Generate the normalized overall ranking from the ranks of the recipients or options
```
Comment (damithc) [inline src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java]: Generates
