### PR TITLE
Instructor: course details: fix broken auto-highlighting of table #8174

### LINKED ISSUE #8174: Instructor: course details: fix broken auto-highlighting of table
Same as #8128, but for the course details page. Delete these lines:
https://github.com/TEAMMATES/teammates/blob/f0dd51db12cedecc02fbf4149116165a45139a54/src/main/webapp/dev/js/main/instructorCourseDetails.js#L103-L106

Then add `selectElementContents(content.get(0));` after these lines: https://github.com/TEAMMATES/teammates/blob/f0dd51db12cedecc02fbf4149116165a45139a54/src/main/webapp/dev/js/main/instructorCourseDetails.js#L49-L50

### PR DESCRIPTION
**Pull request by jms5049**
Fixes #8174 

**Outline of Solution**

have deleted these lines in instructorCourseDetails.js

 $('#btn-select-element-contents').on('click', () => { 
     selectElementContents($('#detailsTable').get(0)); 
 }); 

11/27

reverted above and deleted  lines 104-106

have added

selectElementContents(content.get(0));

### CODE REVIEW

File: src/main/webapp/dev/js/main/instructorCourseDetails.js [hunk 1]
```diff
@@ -110,10 +111,6 @@ $(document).ready(() => {
     attachEventToDeleteStudentLink();
     attachEventToDeleteAllStudentLink();
 
-    $('#btn-select-element-contents').on('click', () => {
-        selectElementContents($('#detailsTable').get(0));
-    });
-
```
Comment (whipermr5) [inline src/main/webapp/dev/js/main/instructorCourseDetails.js]: Apologies; I showed the wrong code snippet on the original issue. It is lines 104-106 that should be deleted instead - can you revert this change and delete those lines? Have updated the issue.
