### PR TITLE
GateKeeper: Shorten verifyAccessibleForCurrentUserAsInstructorOrTeamMember(…) #7835

### LINKED ISSUE #7835: GateKeeper: Shorten verifyAccessibleForCurrentUserAsInstructorOrTeamMember(…)
Without comments or any sort of abstraction, it makes it hard for readers to understand the code. 

Let’s apply Single Level of Abstraction Principle (SLAP) on it to allow the code to be understood easily.

Resulting code can look something like this:

```
public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttributes account, String courseId,
        String section, String email) {
    if (!isValidInstructor(section, courseId, account) && !isValidStudent(email, courseId, account)) {
        throw new UnauthorizedAccessException("User is not in the course that student belongs to");
    }
}

private boolean isValidInstructor(String section, String courseId, AccountAttributes account) {
    InstructorAttributes instructor = instructorsLogic.getInstructorForGoogleId(courseId, account.googleId);
    if (instructor == null) {
        return false;
    }

    if (!instructor.isAllowedForPrivilege(section,
            Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
        throw new UnauthorizedAccessException("Instructor does not have enough privileges to view the photo");
    }

    return true;
}

private boolean isValidStudent(String email, String courseId, AccountAttributes account) {
    StudentAttributes student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId);
    if (student == null) {
        return false;
    }

    if (!studentsLogic.isStudentsInSameTeam(courseId, email, student.email)) {
        throw new UnauthorizedAccessException("Student does not have enough privileges to view the photo");
    }

    return true;
}
```

### PR DESCRIPTION
**Pull request by ParmaarK**
Fixes #7835

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@ParmaarK While I review this PR, have you followed the [Orientation Task List](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list) from our Contributor's orientation guide? I ask because I don't see your introduction in the Issue Tracker, as is recommended in [Phase D](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#phase-d-introduce-yourself-to-the-community) of the Task List.

**Comment by ParmaarK** [comment]
@HirdayGupta I haven't added my introduction. Will do that for sure. Thanks :)

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 1]
```diff
@@ -324,24 +324,34 @@ private boolean isStudent() {
     }
 
     public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttributes account, String courseId,
-            String section, String email) {
+                                                                       String section, String email) {
+        if (!isValidInstructor(section, courseId, account) && !isValidStudent(email, courseId, account)) {
+            throw new UnauthorizedAccessException("User is not in the course that student belongs to");
```
Comment (HirdayGupta) [inline src/main/java/teammates/logic/api/GateKeeper.java]: If we end up implementing all the changes I have suggested above, then we might have to change the error message to `"User does not have enough privileges to view the photo"`.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 2]
```diff
@@ -324,24 +324,34 @@ private boolean isStudent() {
...
-                throw new UnauthorizedAccessException("Instructor does not have enough privileges to view the photo");
-            }
-            return;
+        if (instructor == null) {
+            return false;
         }
 
+        if (!instructor.isAllowedForPrivilege(section,
+                                              Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
+            throw new UnauthorizedAccessException("Instructor does not have enough privileges to view the photo");
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Agree with the concept that boolean methods should not be throwing exceptions. However, this approach would cause errors due to null instructors becoming indistinguishable from errors due to insufficient privileges. I suggest that the null checks can remain in the original method instead:
```java
public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttributes account, String courseId,
        String section, String email) {
    InstructorAttributes instructor = instructorsLogic.getInstructorForGoogleId(courseId, account.googleId);
    if (instructor != null) {
        verifyInstructorCanViewPhoto(...);
        return;
    }

    StudentAttributes student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId);
    if (student != null) {
        verifyStudentCanViewPhoto(...);
        return;
    }

    throw new UnauthorizedAccessException("User is not in the course that student belongs to");
}
```

@Zhiyuan-Amos would this be concise enough?

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 3]
```diff
@@ -327,21 +327,29 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
-            if (!studentsLogic.isStudentsInSameTeam(courseId, email, student.email)) {
-                throw new UnauthorizedAccessException("Student does not have enough privileges to view the photo");
-            }
+            verifyStudentCanViewPhoto(student, email, courseId);
             return;
         }
+        throw new UnauthorizedAccessException("User does not have enough privileges to view the photo");
+    }
+
+    private boolean verifyInstructorCanViewPhoto(InstructorAttributes instructor, String section) {
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: This is supposed to be a void that does throwing, otherwise calling it has no effect.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 4]
```diff
@@ -327,21 +327,29 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
+        if (!instructor.isAllowedForPrivilege(section,
+                Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
+            return false;
+        }
+        return true;
+    }
 
-        throw new UnauthorizedAccessException("User is not in the course that student belongs to");
+    private boolean verifyStudentCanViewPhoto(StudentAttributes student, String courseId, String email) {
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Same here.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 5]
```diff
@@ -327,21 +327,29 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
-
         StudentAttributes student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId);
         if (student != null) {
-            if (!studentsLogic.isStudentsInSameTeam(courseId, email, student.email)) {
-                throw new UnauthorizedAccessException("Student does not have enough privileges to view the photo");
-            }
+            verifyStudentCanViewPhoto(student, email, courseId);
             return;
         }
+        throw new UnauthorizedAccessException("User does not have enough privileges to view the photo");
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Revert to the old message.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 6]
```diff
@@ -327,21 +327,27 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
         InstructorAttributes instructor = instructorsLogic.getInstructorForGoogleId(courseId, account.googleId);
         if (instructor != null) {
-            if (!instructor.isAllowedForPrivilege(section,
-                    Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
-                throw new UnauthorizedAccessException("Instructor does not have enough privileges to view the photo");
-            }
+            verifyInstructorCanViewPhoto(instructor, section);
             return;
         }
-
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Unrelated change; revert this (also, the blank line helps to separate blocks of code).

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 7]
```diff
@@ -327,21 +327,27 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
         StudentAttributes student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId);
         if (student != null) {
-            if (!studentsLogic.isStudentsInSameTeam(courseId, email, student.email)) {
-                throw new UnauthorizedAccessException("Student does not have enough privileges to view the photo");
-            }
+            verifyStudentCanViewPhoto(student, email, courseId);
             return;
         }
-
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Same here.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 8]
```diff
@@ -327,21 +327,27 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
         throw new UnauthorizedAccessException("User is not in the course that student belongs to");
     }
+
+    private void verifyInstructorCanViewPhoto(InstructorAttributes instructor, String section) {
+        if (!instructor.isAllowedForPrivilege(section,
+                Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: This can be combined with the previous line as the resulting line still fits the 125-character limit.

File: src/main/java/teammates/logic/api/GateKeeper.java (hunk 2 above)
Comment (Zhiyuan-Amos) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Yup, looks good! :) This method still looks big though, but I guess there's not much we can do about it for now.

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 9]
```diff
@@ -327,21 +327,28 @@ public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttrib
...
+            verifyInstructorCanViewPhoto(instructor, section);
             return;
         }
 
         StudentAttributes student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId);
         if (student != null) {
-            if (!studentsLogic.isStudentsInSameTeam(courseId, email, student.email)) {
-                throw new UnauthorizedAccessException("Student does not have enough privileges to view the photo");
-            }
+            verifyStudentCanViewPhoto(student, email, courseId);
```
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: The parameter order doesn't match the method signature.

File: src/main/java/teammates/logic/api/GateKeeper.java (hunk 2 above)
Comment (whipermr5) [inline src/main/java/teammates/logic/api/GateKeeper.java]: @Zhiyuan-Amos The only other alternative I can think of would require suppressing a Checkstyle rule (InnerAssignment) and a PMD rule (ConfusingTernary):

```java
@SuppressWarnings("PMD.ConfusingTernary")
public void verifyAccessibleForCurrentUserAsInstructorOrTeamMember(AccountAttributes account, String courseId,
        String section, String email) {
    InstructorAttributes instructor;
    StudentAttributes student;

    //CHECKSTYLE.OFF:InnerAssignment
    if ((instructor = instructorsLogic.getInstructorForGoogleId(courseId, account.googleId)) != null) {
        verifyInstructorCanViewPhoto(instructor, section);

    } else if ((student = studentsLogic.getStudentForCourseIdAndGoogleId(courseId, account.googleId)) != null) {
        verifyStudentCanViewPhoto(student, email, courseId);

    } else {
        throw new UnauthorizedAccessException("User is not in the course that student belongs to");
    }
    //CHECKSTYLE.ON:InnerAssignment
}
```

We can't do the assignment first as we do not want to call `studentsLogic` unnecessarily.

File: src/main/java/teammates/logic/api/GateKeeper.java (hunk 9 above)
Comment (ParmaarK) [inline src/main/java/teammates/logic/api/GateKeeper.java]: my bad. corrected now
