### PR TITLE
EmailGeneratorTest failing on live server #8908

### LINKED ISSUE #8908: EmailGeneratorTest failing on live server
v6.6.0

Some of the EmailGeneratorTest tests are failing on live server e.g, EmailGeneratorTest.testGenerateInstructorJoinEmail
image

All due to a cause similar to this one:
image

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8908

**Outline of Solution**

- Added method `setApplicationEnvironment()` which fixes the issue of `isDevServer()` not working properly.[Now gives correct http and https]
- Modified `getEnvironmentAttributesWithApplicationHostname` to remove the `6-6-0-dot-` part from URL while testing to correct the tests

### CODE REVIEW

File: src/test/java/teammates/test/driver/GaeSimulation.java [hunk 1]
```diff
@@ -240,12 +242,34 @@ private HttpServletRequest createWebRequest(String uri, String... parameters) {
     public static Map<String, Object> getEnvironmentAttributesWithApplicationHostname() {
         Map<String, Object> attributes = new HashMap<>();
         try {
+            if (!TestProperties.TEAMMATES_URL.contains("localhost")) {
+                attributes.put("com.google.appengine.runtime.default_version_hostname",
+                        new URL(TestProperties.TEAMMATES_URL).getAuthority().substring(10));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/driver/GaeSimulation.java]: Why `10`?

File: src/test/java/teammates/test/driver/GaeSimulation.java [hunk 2]
```diff
@@ -240,12 +242,34 @@ private HttpServletRequest createWebRequest(String uri, String... parameters) {
     public static Map<String, Object> getEnvironmentAttributesWithApplicationHostname() {
         Map<String, Object> attributes = new HashMap<>();
         try {
+            if (!TestProperties.TEAMMATES_URL.contains("localhost")) {
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/GaeSimulation.java]: Instead of changing this. I think we can change the `AdminHomePageUiTest` to only comparator param ignore hostname.

File: src/test/java/teammates/test/driver/GaeSimulation.java (hunk 1 above)
Comment (tshradheya) [reply src/test/java/teammates/test/driver/GaeSimulation.java]: To get rid of `6-6-0-dot-` part of hostname.

I think I will follow @xpdavid's suggestion and rather change the testing method to only check for params rather than the entire URL. So I will remove this code

File: src/test/java/teammates/test/driver/GaeSimulation.java [hunk 3]
```diff
@@ -240,12 +242,34 @@ private HttpServletRequest createWebRequest(String uri, String... parameters) {
...
             throw new RuntimeException(e);
         }
         return attributes;
     }
 
+    /**
+     * Sets the environment of SystemProperty based on the URL.
+     */
+    public static void setApplicationEnvironment() {
+        try {
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/java/teammates/test/driver/GaeSimulation.java]: This logic is being used for `BaseTestCaseWithMinimalGaeEnvironment` and for setting up BaseCaseTest for component tests, which is why I extracted into a function

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/test/java/teammates/test/driver/GaeSimulation.java]: It's OK. They are inherited.

**Comment by tshradheya** [comment]
@xpdavid made necessary changes

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 4]
```diff
@@ -83,15 +85,15 @@ private void testCreateInstructorAction() throws Exception {
...
-        String expectedjoinUrl = Config.getAppUrl(Const.ActionURIs.INSTRUCTOR_COURSE_JOIN)
-                                        .withRegistrationKey(encryptedKey)
-                                        .withInstructorInstitution(institute)
-                                        .toAbsoluteString();
         assertEquals("Instructor AHPUiT Instrúctör WithPlusInEmail has been successfully created " + Const.JOIN_LINK,
                 homePage.getMessageFromResultTable(2));
-        assertEquals(expectedjoinUrl, homePage.getJoinLink(homePage.getMessageFromResultTable(2)));
+
+        String encryptedKey = getKeyForInstructorWithRetry(demoCourseId, instructor.email);
+        String actualJoinLink = homePage.getJoinLink(homePage.getMessageFromResultTable(2));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Can we parse the acutalJoinLink and use `getQuery()` to get the parameters and compare `getQuery()` in `expectedjoinUrl`?

Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Good idea. The code looks much cleaner and has better checks

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 5]
```diff
@@ -83,15 +85,21 @@ private void testCreateInstructorAction() throws Exception {
...
                 homePage.getMessageFromResultTable(2));
-        assertEquals(expectedjoinUrl, homePage.getJoinLink(homePage.getMessageFromResultTable(2)));
+
+        String encryptedKey = getKeyForInstructorWithRetry(demoCourseId, instructor.email);
+
+        String expectedjoinUrl = Config.getAppUrl(Const.ActionURIs.INSTRUCTOR_COURSE_JOIN)
+                                                        .withRegistrationKey(encryptedKey)
+                                                        .withInstructorInstitution(institute)
+                                                        .toAbsoluteString();
+        String expectedJoinLinkQuery = new URL(expectedjoinUrl).getQuery();
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Can you try `getFile()`? According to the documentation, it has a combination of `filename` and `query`, in this case, `Const.ActionURIs.INSTRUCTOR_COURSE_JOIN` + `queryString`.

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 6]
```diff
@@ -83,15 +85,21 @@ private void testCreateInstructorAction() throws Exception {
...
-                                        .withRegistrationKey(encryptedKey)
-                                        .withInstructorInstitution(institute)
-                                        .toAbsoluteString();
         assertEquals("Instructor AHPUiT Instrúctör WithPlusInEmail has been successfully created " + Const.JOIN_LINK,
                 homePage.getMessageFromResultTable(2));
-        assertEquals(expectedjoinUrl, homePage.getJoinLink(homePage.getMessageFromResultTable(2)));
+
+        String encryptedKey = getKeyForInstructorWithRetry(demoCourseId, instructor.email);
+
+        String expectedjoinUrl = Config.getAppUrl(Const.ActionURIs.INSTRUCTOR_COURSE_JOIN)
```
[the remark this answers is not in the document]
Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Actually, I will have an `AppUrl` instance which is a subclass of `Url` (which actually uses the `java.net.URL`) so I won't be able to use the functions of URL directly( for e.g. getFile()).

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java [hunk 7]
```diff
@@ -14,6 +20,22 @@
 
     private LocalServiceTestHelper helper = new LocalServiceTestHelper();
 
+    /**
+     * Sets the environment of SystemProperty based on the URL.
+     */
+    @BeforeSuite
+    public void setUpEnvironment() {
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: Have you tried to change the link to your staging server address (start with `https`)? TDoes the tests pass?

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java [hunk 8]
```diff
@@ -14,6 +20,22 @@
...
+        try {
+            if (new URL(TestProperties.TEAMMATES_URL).getProtocol().equals("https")) {
+                SystemProperty.environment.set(SystemProperty.Environment.Value.Production);
+            } else {
+                SystemProperty.environment.set(SystemProperty.Environment.Value.Development);
+            }
+        } catch (MalformedURLException e) {
+            throw new RuntimeException(e);
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: If we are not going to say anything here, we can add `throws MalformedURLException` to the method signature. TestNG will catch the error (stop the test) and report.

**Comment by tshradheya** [comment]
`app.url` had been removed in #8801 from `build.template.properties`. I think running `gradlew createConfigs` again should create a new build.properties file without the `app.url`

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java (hunk 7 above)
Comment (tshradheya) [reply src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: Yes. Both the tests failing before now pass on the staging server

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java [hunk 9]
```diff
@@ -14,6 +20,18 @@
 
     private LocalServiceTestHelper helper = new LocalServiceTestHelper();
 
+    /**
+     * Sets the environment of SystemProperty based on the URL.
+     */
+    @BeforeSuite
+    public void setUpEnvironment() throws MalformedURLException {
+        if (new URL(TestProperties.TEAMMATES_URL).getProtocol().equals("https")) {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: I still don't like the idea of using `https` to determine if the app is in production mode or not. Why not check if there is an `.appspot.com`?

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 10]
```diff
@@ -83,15 +85,20 @@ private void testCreateInstructorAction() throws Exception {
...
+                                                        .withRegistrationKey(encryptedKey)
+                                                        .withInstructorInstitution(institute)
+                                                        .toAbsoluteString();
+        String expectedJoinLinkUrlFileName = new URL(expectedjoinUrl).getFile();
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Not really familiar; what does `URL#getFile()` return?

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java (hunk 9 above)
Comment (LiHaoTan) [reply src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: I agree with @wkurniawan07 mentioned which will also prevent the confusion in the environment value if someone sets the URL to say something like `http://teammates-john.appspot.com`.

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java (hunk 10 above)
Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Basically it returns getPath()+getQuery().

So for `https://teammates-john.appspot.com/page/adminPage?user=myself`, getFile() returns `/page/adminPage?user=myself`

File: src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java (hunk 9 above)
Comment (tshradheya) [reply src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java]: Makes more sense. Updated 👍
