### PR TITLE
[#13641] Hardcode application version number

### LINKED ISSUE #13641: Hardcode application version number
Currently, the application version is user-defined. This should be hardcoded into the codebase as a single source of truth.

**Rationale**
This prevents misconfiguration from incorrect user-supplied values. This will lay the groundwork for a future update-check utility.

Note: 
The current application version is displayed on the site footer. This is derived from a user configurable variable.

### PR DESCRIPTION
**Pull request by hyeonjijulialee**
Fixes #13641

Outline of Solution
The objective of this PR is to eliminate user-configurable application version inputs on both the frontend and backend, replacing them with hardcoded constants in code so that a single authoritative value flows through the system. This prevents misconfiguration from incorrect user-supplied values and lays the groundwork for a future update-check utility.

1. Backend: Hardcode `Config.APP_VERSION`

Removed the `app.version` entry and its surrounding comment from `src/main/resources/build.template.properties`, so no user-editable property file defines the version any more.
Changed `Config.APP_VERSION` in `src/main/java/teammates/common/util/Config.java` from a `getProperty` lookup into a hardcoded `public static final String APP_VERSION = "9.0.0-beta.6";`, matching the most recent release tag on the repository.
Updated the Javadoc for the constant to describe it as the single source of truth rather than the value of a property.

2. Backend: Hardcode the GAE deployment version

Replaced the dynamic `props['app.version']` lookup in `build.gradle`'s AppEngine `deploy` block with a literal `"9-0-0-beta-6"`, since GAE version IDs disallow dots and must use the dashed form. A single-line inline comment explains the relationship to `Config.APP_VERSION`.

3. Frontend: Hardcode `APPLICATION_VERSION`

Removed the `version: '8.0.0'` entry from `src/web/environments/config.template.ts`, so no user-editable config object defines the version any more.
Added `src/web/environments/application-version.ts` exporting a single `APPLICATION_VERSION` constant: `export const APPLICATION_VERSION = '9.0.0-beta.6';`.
Updated `page.component.ts` (footer display) and `http-request.service.ts` (`X-WEB-VERSION` header) to import `APPLICATION_VERSION` instead of `environment.version`.

4. Impact & Testing

Ran `./gradlew compileJava` and `./gradlew pmdMain` cleanly with the changes.
Ran `./gradlew unitTests --tests CompileLogsActionTest` (the test class that exercises `Config.APP_VERSION` via `EmailType.SEVERE_LOGS_COMPILATION`): all 4 tests pass.
Ran `ng test` for both modified frontend files: `http-request.service.spec.ts` (12 tests) and `page.component.spec.ts` (1 test) pass.
Ran `ng lint --cache --eslint-config static-analysis/teammates-eslint.yml`: no errors introduced by the modified files.
The footer display and `X-WEB-VERSION` HTTP header continue to render the same string, just sourced from a code constant instead of the runtime-loaded environment object.

### CODE REVIEW

File: src/main/java/teammates/common/util/Config.java [hunk 1]
```diff
@@ -28,8 +28,8 @@ public final class Config {
     /** Value of {@code app.region}. */
     public static final String APP_REGION;
 
-    /** Value of {@code app.version}. */
-    public static final String APP_VERSION;
+    /** Hardcoded application version, used as the single source of truth across the codebase. */
```
Comment (samuelfangjw) [inline src/main/java/teammates/common/util/Config.java]:
```suggestion
    /** Backend application version. */
```

File: src/web/services/http-request.service.ts [hunk 2]
```diff
@@ -41,7 +42,7 @@ export class HttpRequestService {
 
   private backendUrl: string = environment.backendUrl;
   private withCredentials: boolean = environment.withCredentials;
-  private version: string = environment.version;
```
Comment (samuelfangjw) [inline src/web/services/http-request.service.ts:44]: Keep `environment.version`. Import APPLICATION_VERSION in `environment.prod.ts` and `environment.ts` instead.

**Review by samuelfangjw — CHANGES_REQUESTED** [review]

**Review by samuelfangjw — APPROVED** [review]
