### PR TITLE
[#11911] Instructor copying course: Progress bar does not load when no feedback sessions are copied

### LINKED ISSUE #11911: Instructor copying course: Progress bar does not load when no feedback sessions are copied
Master Branch & V8.18.0 

**Steps to reproduce**

https://user-images.githubusercontent.com/10182564/180641338-93540c15-066f-4227-9e77-4d6ac50191db.mp4
1. Login as instructor
2. Attempt to copy course, but do not select any feedback sessions to copy

**Expected behaviour**
Loading bar to progress when copying, show the correct progress, and close when it is finished. Show the successful alert when it is done.

**Actual behaviour**
As shown in the video, the bar doesn't progress at all, and doesn't close when it is done.

### PR DESCRIPTION
**Pull request by domlimm**
Fixes #11911.

**Outline of Solution**

Previously, when an instructor creates a course by copying another course **without any feedback session** selected, user gets stuck on the copying and no progress is shown on the progress bar.

The fix is to check if there is any feedback session to copy, else we just need to resolve the `Promise` and this would update the progress bar as well.

Additionally, shifted out the `ProgressBarService` update lines as there are code duplications in the above fix and the current implementation (5e50c39).

https://user-images.githubusercontent.com/46486515/181818057-3c7f4922-5aa3-45eb-9c02-1035a08fdd27.mp4

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts [hunk 1]
```diff
@@ -353,6 +360,16 @@ export class InstructorCoursesPageComponent implements OnInit {
     });
   }
 
+  /**
+   * Updates progress bar using ProgressBarService.
+   * This is a helper function used by {@link InstructorCoursesPageComponent#createCourse()} to
+   * reduce code duplication.
+   */
+  private updateProgressBarHandler(copyProgressPercentage: number): void {
+    this.copyProgressPercentage = copyProgressPercentage;
```
Comment (FergusMok) [inline src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:369]: Actually are we able to just delete `this.copyProgressPercentage` entirely? It seems like it was made solely to be used in `createCourse`

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts [hunk 2]
```diff
@@ -319,13 +319,20 @@ export class InstructorCoursesPageComponent implements OnInit {
     .subscribe(() => {
       // Wrap in a Promise to wait for all feedback sessions to be copied
       const promise: Promise<void> = new Promise<void>((resolve: () => void) => {
+        if (result.selectedFeedbackSessionList.size < 1) {
```
Comment (FergusMok) [inline src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:322]: Small nit, might be clearer this way
```suggestion
        if (result.selectedFeedbackSessionList.size === 0) {
```

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts [hunk 3]
```diff
@@ -319,13 +319,20 @@ export class InstructorCoursesPageComponent implements OnInit {
...
+          this.updateProgressBarHandler(1);
```
Comment (FergusMok) [inline src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:323]: just curious, why is it 1? Are you taking into consideration #11876 ?

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts (hunk 1 above)
Comment (FergusMok) [reply src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:369]: Then following that, you can just this `this.progressBarService.updateProgress(this.copyProgressPercentage)` directly without creating `updateProgressBarHandler`

**Review by FergusMok — COMMENTED** [review]
Thank you for responding so quickly to the issue! Could you also add a video of the fix to your description? Here's also some small suggestions

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts (hunk 1 above)
Comment (domlimm) [reply src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:369]: Yes, agreed. Thanks! Will make the change.

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts (hunk 2 above)
Comment (domlimm) [reply src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:322]: I agree on this! Initially, wanted to use `0` but forgot what came to me to pick `< 1`. Thank you!

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts (hunk 3 above)
Comment (domlimm) [reply src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:323]: This was just an arbitrary choice, rather progress bar would be 100% filled so I thought to use 1. And I haven't seen #11876 before. Is `1` okay for this case?

**Comment by domlimm** [comment]
Hello @FergusMok! Thanks so much for reviewing this PR! I have added replies to your comments, and will wait for your reply before pushing out the changes.

As for the video, may I ask if there is an example of how the video should be filmed? Is it just how it looks like after fixing or there has to be some explanation/demo?

Thank you again! 😃

File: src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts (hunk 3 above)
Comment (FergusMok) [reply src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts:323]: Sorry I was initially confused. If you're updating the bar to 100%, I think the value here should be 100 instead, as the service takes a percentage value

**Comment by FergusMok** [comment]
@domlimm There's no particular format for the video, it's purpose is just for other reviewers / people referencing this PR again in the future to able to quickly understand what you're trying to do. An example would be #11881!

**Comment by domlimm** [comment]
@FergusMok I see! I understand. Have updated based on your suggestions and made the necessary changes for your review please. Thank you again!

**Review by FergusMok — APPROVED** [review]
@domlimm LGTM! Thanks for fixing this issue! :)

**Review by samuelfangjw — APPROVED** [review]
