### PR TITLE
Instructor view session results: numeric scale question: sorting is incorrect #6437

### LINKED ISSUE #6437: Instructor view session results: numeric scale question: sorting is incorrect
See screenshot

image

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #6437

Change `parseInt` to `parseFloat` in `getPointValue` (`common.js`)

[1/4] change parseInt to parseFloat
[2/4] make getPointValue() comments more clear
[3/4] add unit test for getPointValue()
[4/4] add test cases for sortByPoint

### CODE REVIEW

File: src/main/webapp/js/common.js [hunk 1]
```diff
@@ -457,7 +457,7 @@ function getPointValue(s, ditchZero) {
     
     if (s0.indexOf('/') !== -1) {
         if (s0.indexOf('S') !== -1) {
-            return 999; // Case N/S
+            return 999; // Case N/S (feedback contribution not sure)
```
Comment (li-kai) [inline src/main/webapp/js/common.js]: 999 and 1000 are arbitrary values that will encounter collisions. `Number.MAX_VALUE` and `Number.POSITIVE_INFINITY` should be used instead.

File: src/test/javascript/CommonJsTest.js [hunk 2]
```diff
@@ -78,6 +78,71 @@ QUnit.test('sortDate(x, y)', function(assert) {
         '25 April 1999 2:00PM - 25 April 1999 2:01PM');
 });
 
+QUnit.test('getPointValue(s, ditchZero)', function(assert) {
```
Comment (li-kai) [inline src/test/javascript/CommonJsTest.js]: Check for `<td>Value</td>` cases as well.

File: src/main/webapp/js/common.js (hunk 1 above)
Comment (xpdavid) [inline src/main/webapp/js/common.js]: Yes, that's true. But `N/S` and `N/A` will only appear together with `E +(-)X%` together (0 <= X <= 100).

File: src/test/javascript/CommonJsTest.js (hunk 2 above)
Comment (xpdavid) [inline src/test/javascript/CommonJsTest.js]: That is also my question.
There is a code segment in `getPointValue()`
``` javascript
    if (s0.lastIndexOf('<') !== -1) {
        s0 = s0.substring(0, s0.lastIndexOf('<'));
        s0 = s0.substring(s0.lastIndexOf('>') + 1);
    }
```
which seems like to get the text in `<html_tag>TEXT<html_tag>`, but seems that it never used. I even comment it out and pass the test cases. I am hesitating to remove it.

**Comment by xpdavid** [comment]
Waiting for #6389 :P

File: src/test/javascript/CommonJsTest.js (hunk 2 above)
Comment (li-kai) [inline src/test/javascript/CommonJsTest.js]: Table sorting is used in almost 100 classes. I'm hesitant too. There doesn't seem to be any harm keeping it.

File: src/main/webapp/js/common.js (hunk 1 above)
Comment (li-kai) [inline src/main/webapp/js/common.js]: Either way I'd still prefer making them less magic. :)

Comment (xpdavid) [inline src/main/webapp/js/common.js]: Thanks. Commit on the way. Waiting for the master branch to get dev green :P

File: src/main/webapp/js/common.js [hunk 3]
```diff
@@ -450,33 +450,37 @@ function sortByDiff(a, b) {
  */
 function getPointValue(s, ditchZero) {
     var s0 = s;
+    var baseValue = 100;
+    
     if (s0.lastIndexOf('<') !== -1) {
         s0 = s0.substring(0, s0.lastIndexOf('<'));
         s0 = s0.substring(s0.lastIndexOf('>') + 1);
     }
```
Comment (xpdavid) [inline src/main/webapp/js/common.js]: The above statements seems to get the text in `<html_tag>TEXT<html_tag>`. But I look through the project and there is no place that needs to skip html tag. So I didn't write test cases for this and plan to remove it. Can some senior developer confirm this. Even if there is a place that need to skip html tag, this method is not the sophisticated way to do it.

**Comment by xpdavid** [comment]
Ready for review.

File: src/main/webapp/js/common.js (hunk 3 above)
Comment (li-kai) [inline src/main/webapp/js/common.js]: Looked through all the files that used table sorting code.

Because of line 308 in `common.js`, all elements being compared are text and no where do other files using `sortByPoint` or similar functions directly. Hence it is safe to remove the html unwrapping code.

**Comment by xpdavid** [comment]
@li-kai You may want have another look :P

**Comment by wkurniawan07** [comment]
Weird that codecov's bot appears here. Seems like a sign that I have to integrate it soon :p

File: src/test/javascript/CommonJsTest.js [hunk 4]
```diff
@@ -78,6 +78,70 @@ QUnit.test('sortDate(x, y)', function(assert) {
...
+    assert.ok(sortByPoint('2', '-3') > 0, 'Case Integer 2 more than -3');
+    
+    assert.ok(sortByPoint('0.0', '1.0') < 0, 'Case Float 0.0 less than 1.0');
+    assert.ok(sortByPoint('0.3', '-1.1') > 0, 'Case Float 0.3 more than -1.1');
+    assert.ok(sortByPoint('0.3', '0.33338') < 0, 'Case Float 0.3 less than 0.33338');
+    assert.ok(sortByPoint('-4.33333', '-4.5') > 0, 'Case Float -4.33333 more than -4.5');
+    
+    assert.ok(sortByPoint('NotNumber', 'Random') === 0, 'Equality for NaN');
+});
+
```
Comment (damithc) [inline src/test/javascript/CommonJsTest.js]: Curios to know if we have higher level tests covering the sorting functionality. These seem to be a unit test even below the 'sort' function.

Comment (xpdavid) [inline src/test/javascript/CommonJsTest.js]: @damithc Yes. There are browser test cases for the sorting functionality, but not so comprehensive like this. I shall update it also.

**Comment by xpdavid** [comment]
@wkurniawan07 @damithc You may have another look on this. Browser test case updated.

File: src/test/java/teammates/test/cases/browsertests/TableSortTest.java [hunk 5]
```diff
@@ -132,6 +132,27 @@ public void testTableSortingPoint() {
...
+                "0",
+                "0.2",
+                "0.333",
+                "0.45",
+                "0.9",
+                "1",
+                "1.1",
+                "1.333",
+                "1.45");
+    }
```
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/TableSortTest.java]: Ensure this test case fails without the fix.

Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/TableSortTest.java]: I have checked for that. It will fail. :)
The test cases are selected for the purpose as if we use `parseInt` instead of `parseFloat`, both `1.333` and `1.45` will become `1` and there is no difference between them.

**Comment by wkurniawan07** [comment]
No further comments from me, @damithc for your review.
