### PR TITLE
AdminActivityLogPage: fix inconsistent StudentProfilePage Load message #8717

### LINKED ISSUE #8717: AdminActivityLogPage: fix inconsistent StudentProfilePage Load message
- **Environment**: 
`master` branch at commit cd9a536

**Steps to reproduce**
1. Log in as student and open profile page.
2. Log out and log in as admin.
3. View activity log.

**Expected behaviour**
A consistent message that perhaps says:

```
studentProfile Page Load 
Profile: test
```
where test is the googleid of the student.

**Actual behaviour**
Currently, it displays the entire json which is ugly and inconsistent with the rest of the messages.

actual

**Additional info**
This bug is similar to #8707 and #8695.

### PR DESCRIPTION
**Pull request by gthd**
Fixes #8717 by changing the file StudentProfilePageAction.java removing the SanitizationHelper.sanitizeForHtmlTag(account.studentProfile.toString());

### CODE REVIEW

File: src/main/java/teammates/ui/controller/StudentProfilePageAction.java [hunk 1]
```diff
@@ -26,8 +26,7 @@ protected ActionResult execute() {
         }
 
         StudentProfilePageData data = new StudentProfilePageData(account, sessionToken, isEditingPhoto);
-        statusToAdmin = "studentProfile Page Load <br> Profile: "
-                + SanitizationHelper.sanitizeForHtmlTag(account.studentProfile.toString());
+        statusToAdmin = "studentProfile Page Load <br> Profile: test";
```
Comment (tshradheya) [inline src/main/java/teammates/ui/controller/StudentProfilePageAction.java]: You cant just hardcode `test`.

In the #8717, `test` is mentioned because the google id in the screenshot is `test`.
So you need to display the `googleId`

**Comment by gthd** [comment]
Hi @tshradheya I will change my approach and implement the fix according to your suggestion. Thank you

**Comment by tshradheya** [comment]
@whipermr5 Can review this?
