### PR TITLE
[#9939] View Team on Student Page does not show teammates details

### LINKED ISSUE #9939: View Team on Student Page does not show teammates details
View Team on Student Page does not show all of the teammates details, even if they are registered

Nothing is shown until the student updates the details on the profile page. There is also a secondary bug because on the profile page, the long term contact email is only supposed to be shown to instructors, but the other students can also see it as well.

- **Environment**: 
Latest `master` at `07fa66b`

**Steps to reproduce**
Create a few new students in the course and get them to join
Go to one of the students in the team and click `View Team`

**Expected behaviour**
I should be able to see the person's name at least.

**Actual behaviour**
Nothing is shown unless I go to that student's profile page and update the details

Screen Shot 2020-02-01 at 12 20 33 PM

**Additional info**

### PR DESCRIPTION
**Pull request by hcwong**
Fixes #9939 

**PR Checklist**

**Outline of Solution**

Just add conditional check. Quick question, why are the student profiles seen by the student different from those seen by instructor? Is it because one has more info?

### CODE REVIEW

**Comment by xpdavid** [comment]
@joanneong Please help to check the behavior of V6 when reviewing this.

**Comment by hcwong** [comment]
> @hcwong
> 
> In V6 (current release), you see the following information:
> 
> image
> 
> i.e. student name and student email (their sign-up email). Even if the student updates their profile and adds a long-term email, this information is not shown to the students.
> 
> In contrast, the `master` branch have the two bugs which you pointed out in #9939 : (i) cannot see team details even after the team member has accepted the invitation and (ii) long-term email is shown to all students:
> 
> image
> 
> Based on what I've tested (and what I see of your code), your fix allows for this:
> 
> image
> 
> So the name is correctly displayed after a team member has accepted the invitation. However, it will still show the long-term email if someone's profile is updated. To be faithful to V6, can you also show the email for the student profile after they have accepted the invitation, and ensure that their long-term emails are not shown to other students?

Hello Joanne, its a `Student` vs `StudentProfile` issue. I've used the `Student`'s email instead, as thats the email they used to login (not the long term one in `StudentProfile`

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 1]
```diff
@@ -114,17 +114,18 @@ export class StudentCourseDetailsPageComponent implements OnInit {
             this.studentProfileService.getStudentProfile(student.email, courseId)
                   .subscribe((studentProfile: StudentProfile) => {
                     const newPhotoUrl: string =
-              `${environment.backendUrl}/webapi/student/profilePic?courseid=${courseId}&studentemail=${student.email}`;
+                      `${environment.backendUrl}/webapi/student/profilePic`
+                      + `?courseid=${courseId}&studentemail=${student.email}`;
 
                     const newTeammateProfile: StudentProfileWithPicture = {
-                      studentProfile,
+                      // Use student.email as studentProfile.email is the long term email which should not be shown
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Correct me if I am wrong. Looks like from your conversation history this is a potential security glitch says that "the long term email should not be shown to student". If this is the case, doing override in the frontend won't work. We need hide the field from the backend.

Comment (hcwong) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Yea you're right. Since this got larger in scale I'll KIV this first and return after the search migration API epic

**Comment by xpdavid** [comment]
@hcwong Let's continue on this?

**Comment by hcwong** [comment]
> @hcwong Let's continue on this?

sure ill take a look at it again

**Comment by hcwong** [comment]
@xpdavid @joanneong 
I've chosen to hide the long-term email and the shortName as according to the student profile update page, this should only be shown to instructors.

This is now what the student can see from backend:

Screen Shot 2020-02-24 at 11 12 11 AM

File: src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java [hunk 2]
```diff
@@ -72,6 +72,12 @@ public ActionResult execute() {
             studentProfile = StudentProfileAttributes.builder(studentId).build();
         }
 
+        // If student requesting and is not the student's own profile, hide some fields
+        if (userInfo.isStudent && studentId.equals(userInfo.id)) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java]: I think you should change `StudentProfileData` instead. See how `FeedbackSessionData` is done.

Comment (hcwong) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java]: Thanks, I've added a hide feature to `StudentProfileData`

Comment (hcwong) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java]: Hey @xpdavid, is the fix for this alright? Thanks!

**Comment by xpdavid** [comment]
@hcwong Looks like the linting is failing.

**Comment by joanneong** [comment]
@hcwong Reminder to fix this :)
