### PR TITLE
AdminSessionsPageUiTest fails frequently on line 66 on Travis #5171

### LINKED ISSUE #5171: AdminSessionsPageUiTest fails frequently on line 66 on Travis
Fails due to missing wait before checking if panel is visible. Usually not a problem due to browser speed but fails on Travis.

### PR DESCRIPTION
**Pull request by ashrayjain**
Fixes #5171

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java [hunk 1]
```diff
@@ -63,13 +63,21 @@ private void testContent() {
...
-        return sessionsPage.isElementVisible(By.id("timeFramePanel"));
+        By timeFramePanel = By.id("timeFramePanel");
+        sessionsPage.waitForElementPresence(timeFramePanel);
+        return sessionsPage.isElementVisible(timeFramePanel) == true;
+    }
+
+    private boolean isTimeFramePanelInvisible() {
+        By timeFramePanel = By.id("timeFramePanel");
+        sessionsPage.waitForElementToDisappear(timeFramePanel);
+        return sessionsPage.isElementVisible(timeFramePanel) == false;
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java]: You don't actually have to do the `isElementVisible` comparison anymore. If the element doesn't disappear in time, it will throw a `TimeoutException`.

Comment (ashrayjain) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java]: I see. will update the code.

File: src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java [hunk 2]
```diff
@@ -63,13 +63,21 @@ private void testContent() {
...
+        assertTrue(isTimeFramePanelInvisible());
         assertTrue(isSessionDataDisplayCorrect());
         
     }
     
     private boolean isTimeFramePanelVisible() {
-        return sessionsPage.isElementVisible(By.id("timeFramePanel"));
+        By timeFramePanel = By.id("timeFramePanel");
+        sessionsPage.waitForElementPresence(timeFramePanel);
+        return sessionsPage.isElementVisible(timeFramePanel) == true;
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java]: Strictly speaking, this is not correct. The flow of this method is "wait for something to exist, then verify that the thing is visible". `waitForElementVisibility` should be the one that's used?

Comment (ashrayjain) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java]: ok, will update it.

**Comment by ashrayjain** [comment]
@wkurniawan07 ready for you again.

**Comment by wkurniawan07** [comment]
Yup this is the way I did it in #5174 previously :+1:

**Comment by ashrayjain** [comment]
@wkurniawan07 Interestingly, the build for #5174 still shows the test failing at the same line.

**Comment by wkurniawan07** [comment]
@ashrayjain of course it will, I didn't include the fix I did anymore because it'll conflict with this PR :p

**Comment by ashrayjain** [comment]
Ah! I see.. :+1:
