### PR TITLE
[#9629] Fix instructor home sort by date inconsistency

### LINKED ISSUE #9629: Instructor Home Page: Inconsistent behaviour in sort by date action for courses
**Steps to reproduce**
Log in to Instructor Home Page.
Click on sort by Feedback Session or click sort by creation_date as highlighted in the attached image below.

**Current behaviour**
It does not populate the feedback sessions / courses in the correct order as shown below.
Screenshot 2019-04-01 at 1 39 09 AM

**Expected behaviour**
Supposed to populate according to descending or ascending order of the date correctly.

**Additional info**
I did a minor investigation. As the sorting is by string to string comparison, I think the current format of the date for comparison needs to be changed in order to have accurate string to string comparison

### PR DESCRIPTION
**Pull request by jacoblipech**
Fixes #9629 

**Outline of Solution**

Change `getCreateDate()` method in `CourseData` to return a long similar to feedback sessions instead of a string which consists of only the date.

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts [hunk 1]
```diff
@@ -265,8 +265,8 @@ export class InstructorHomePageComponent extends InstructorSessionBasePageCompon
           strB = b.course.courseId;
           break;
         case SortBy.COURSE_CREATION_DATE:
-          strA = a.course.creationDate;
-          strB = b.course.creationDate;
+          strA = String(a.course.creationDate);
+          strB = String(b.course.creationDate);
```
Comment (Adoby7) [inline src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts]: Perhaps you need to manually test that the date will not be displayed as a long number in all pages that use `Course` DTO, as I search and find toEpochMilli() will convert the time to a `number` instance

Comment (jacoblipech) [reply src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts]: Thanks for the fast review! I double checked with the pages and it does not affect as the `endpoint` to obtain `creationDate` is only used in `InstructorHome`

File: src/main/java/teammates/ui/webapi/output/CourseData.java [hunk 2]
```diff
@@ -9,16 +9,16 @@
 
     private final String courseId;
     private final String courseName;
-    private final String creationDate;
     private final String deletionDate;
     private final String timeZone;
+    private final long creationDate;
```
[the remark this answers is not in the document]
Comment (jacoblipech) [reply src/main/java/teammates/ui/webapi/output/CourseData.java]: I think the purpose of changing it to long is to ensure that it sorts correctly. Since `deletionDate` is not required for sorting so I thought that it should be fine. I guess we can see what @xpdavid thinks.

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/webapi/output/CourseData.java]: You can change deletionDate to make the DTO consistent. After all, date formatting should be done in the frontend rather than backend since we adopt client-rendering.

Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/output/CourseData.java]: Called is as `creationTimestamp`? If you are going to change deletionDate, it should also be called as `deletionTimestamp`.

File: src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java [hunk 3]
```diff
@@ -87,6 +87,9 @@ public Instant getCreatedAt() {
     }
 
     public Instant getDeletedAt() {
+        if (this.deletedAt == null) {
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java]: This conversion should be inside response DTO? Put it here will cause a lot of regression.

**Comment by xpdavid** [comment]
And don't forget to write a pipe or formatter to format the date in the frontend.

**Comment by jacoblipech** [comment]
Currently there is no instance of using course `creationTimeStamp` in the front end to show to the user, it is mainly used for backend sorting. Discussed with @xpdavid that pipe is not required for now.

@wkurniawan07 Ready for final review :)
