### PR TITLE
[#9734] Logic fix publish feedback session() method signature

### LINKED ISSUE #9734: Logic: Fix publishFeedbackSession() method signature
- **Environment**:
`master` branch at commit 5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4

If a `null` session is passed in to `logic.publishFeedbackSession()` it will throw an `AssertionError` instead of an `EntityDoesNotExistException`. This behaviour is problematic as it's not properly caught by the Action calling the method. The API also states that updating entities that are not found should throw an `EntityDoesNotExistException`.

As discussed in #9726, the method signature of `logic.publishFeedbackSession()` should accept courseId and sessionName instead of a feedbackSessionAttribute.  Likewise for `logic.unpublishFeedbackSession()`.

The respective *Action classes have to be updated as well.

Refer to the signature of other methods at the same level of abstraction:
https://github.com/TEAMMATES/teammates/blob/5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4/src/main/java/teammates/logic/api/Logic.java#L1412 https://github.com/TEAMMATES/teammates/blob/5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4/src/main/java/teammates/logic/api/Logic.java#L1423

### PR DESCRIPTION
**Pull request by erjillsison**
Fixes #9734 

**Outline of Solution**
Change method signature of `logic.publishFeedbackSession(FeedbackSessionAttributes sessionToPublish)` to `logic.publishFeedbackSession(String feedbackSessionName, String courseId)`. Likewise for `logic.unpublishFeedbackSession()`.

The method now returns a `FeedbackSessionAttributes` so that the Action calling it does not have to `get` the session from `Logic` again.

### CODE REVIEW

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 1]
```diff
@@ -1632,12 +1632,13 @@ private void testPublishUnpublishFeedbackSession() throws Exception {
         ______TS("failure: already published");
 
         InvalidParametersException ipe = assertThrows(InvalidParametersException.class,
-                () -> fsLogic.publishFeedbackSession(sessionUnderTest));
+                () -> fsLogic.publishFeedbackSession(sessionUnderTest.getFeedbackSessionName(),
+                        sessionUnderTest.getCourseId()));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: Break the line at higher level.
```
fsLogic.publishFeedbackSession(
        sessionUnderTest.getFeedbackSessionName(), sessionUnderTest.getCourseId()));
```

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 2]
```diff
@@ -1648,7 +1649,9 @@ private void testPublishUnpublishFeedbackSession() throws Exception {
 
         ______TS("failure: not published");
 
-        ipe = assertThrows(InvalidParametersException.class, () -> fsLogic.unpublishFeedbackSession(sessionUnderTest));
+        ipe = assertThrows(InvalidParametersException.class,
+                () -> fsLogic.unpublishFeedbackSession(sessionUnderTest.getFeedbackSessionName(),
+                        sessionUnderTest.getCourseId()));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: Same here.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 3]
```diff
@@ -1328,15 +1337,24 @@ public void publishFeedbackSession(FeedbackSessionAttributes sessionToPublish)
...
      * @throws InvalidParametersException if session is already unpublished
+     * @throws EntityDoesNotExistException if the feedback session cannot be found
      */
-    public void unpublishFeedbackSession(FeedbackSessionAttributes sessionToUnpublish)
+    public FeedbackSessionAttributes unpublishFeedbackSession(String feedbackSessionName, String courseId)
             throws EntityDoesNotExistException, InvalidParametersException {
+
+        FeedbackSessionAttributes sessionToUnpublish = getFeedbackSession(feedbackSessionName, courseId);
+
+        if (sessionToUnpublish == null) {
```
Comment (xpdavid) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Actually, I just find that there is no test case for non-existent session.

File: src/main/java/teammates/logic/core/FeedbackSessionsLogic.java [hunk 4]
```diff
@@ -1310,15 +1310,24 @@ public void deleteStudentFromRespondentList(String email, String feedbackSession
...
      * @throws InvalidParametersException if session is already published
+     * @throws EntityDoesNotExistException if the feedback session cannot be found
      */
-    public void publishFeedbackSession(FeedbackSessionAttributes sessionToPublish)
+    public FeedbackSessionAttributes publishFeedbackSession(String feedbackSessionName, String courseId)
             throws EntityDoesNotExistException, InvalidParametersException {
+
+        FeedbackSessionAttributes sessionToPublish = getFeedbackSession(feedbackSessionName, courseId);
+
+        if (sessionToPublish == null) {
```
Comment (xpdavid) [inline src/main/java/teammates/logic/core/FeedbackSessionsLogic.java]: Same here.
