### PR TITLE
Instructor: edit question: new question after cancel: fix discrepancy between visibility option button label and actual selected visibility option #6838

### LINKED ISSUE #6838: Instructor: edit question: new question after cancel: fix discrepancy between visibility option button label and actual selected visibility option
**Environment**

`master` branch at commit 9168d13

**Steps to reproduce**

1. Start to add a new question in an empty session (no previous existing questions).
1. Set visibility to "Visible to instructors only".
1. Cancel out of adding this question.
1. Attempt to add a new contribution question (without refreshing the page).

**Expected behaviour**

screen shot 2017-03-17 at 11 32 23 am

**Actual behaviour**

screen shot 2017-03-17 at 11 32 13 am

### PR DESCRIPTION
**Pull request by VamsiSangam**
Fixes #6838 

**Outline of Solution**

Source of bug - When creating a new question, `prepareQuestionForm()` in `instructorFeedbackEdit.es6` gets called. Then for the contribution question, `setDefaultContribQnVisibilityIfNeeded()` of `questionContrib.es6` is called. Inside that method the visibility option checkboxes is set to `Shown anonymously to recipient and team members, visible to instructors` as such (not visible to user, for demo only) -

But it doesn't update the visibility options dropdown button title. So, later when `getVisibilityMessage()` is called, the visibility messages reflect the values set as per `Shown anonymously to recipient and team members, visible to instructors` -

but the visibility options button title has the title as what it had before (`Visible to instructors only`). So in my implementation, I simply clicked that button, which changes the button title as well as sets the visibility option checkboxes accordingly.

So this means everytime a new team contribution is created, the visibility button will look like this -

So as per my new implementation, I had to update one assertion which expects a new team contribution question's visibility options button to be `Please select a visibility option`, because it will now always be `Shown anonymously to recipient and team members, visible to instructors` and the visibility message will correspond to the new title.

### CODE REVIEW

**Comment by VamsiSangam** [comment]
Ready for review.

File: src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java [hunk 1]
```diff
@@ -180,7 +180,7 @@ private void testCopyOptions() {
         feedbackEditPage.clickNewQuestionButton();
         feedbackEditPage.selectNewQuestionType("CONTRIB");
         feedbackEditPage.fillQuestionTextBoxForNewQuestion("q2, contribution qn");
-        assertEquals("Please select a visibility option",
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: The behaviour should follow that of other question types - when adding it as the first question in an empty session, it should show `Please select a visibility option` to emphasise the fact that the instructor should choose an option. Previous discussion [here](https://github.com/TEAMMATES/teammates/pull/6669#discussion_r105699337).

Comment (VamsiSangam) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: In that case, what is the expected message to be displayed in the visibility options?

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: Exactly what the test checks for now - `Please select a visibility option`. You can check out the current behaviour by seeing what happens when you add a new (non-contrib) question to an empty session.

Comment (VamsiSangam) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: Sorry, I meant the visibility hint. This is what I get when I create an new essay question, and this seems the same for any new non-contrib question -

capture

So should I change the code so that the above hint is displayed along with `Please select a visibility option` on the button?

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: Sorry for the misread! The visibility hint shown should correspond to the default visibility option for that question type (the one assumed when the user still does not select an option but submits anyway).

Comment (VamsiSangam) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: The default visibility for contrib question is `Shown anonymously to recipient and team members, visible to instructors`, which is what the code was doing. I removed it, but it was actually fine. The code just needed one line, setting the button text back to `Please select a visibility option`. Working on it.

**Comment by VamsiSangam** [comment]
Ready for review.

File: src/main/webapp/js/instructorFeedbackEdit/questionContrib.es6 [hunk 2]
```diff
@@ -23,6 +23,9 @@ function setDefaultContribQnVisibilityIfNeeded(questionNum) {
     $currentQuestionTable.find('input.visibilityCheckbox')
                          .filter('.recipientCheckbox')
                          .filter('[value="INSTRUCTORS"],[value="RECEIVER"]').prop('checked', true);
+    // Set dropdown button text
+    $currentQuestionTable.find('div.visibility-options-dropdown button.dropdown-toggle')
+                         .html('Please select a visibility option <span class="caret"></span>');
```
Comment (whipermr5) [inline src/main/webapp/js/instructorFeedbackEdit/questionContrib.es6]: Use the method `setVisibilityDropdownMenuText` in `visibilityOptions.es6` instead. But perhaps we should wait for #7522 to be merged first? Massive migration to webpack.

File: src/main/webapp/dev/js/common/questionContrib.es6 [hunk 3]
```diff
@@ -23,6 +25,9 @@ function setDefaultContribQnVisibilityIfNeeded(questionNum) {
     $currentQuestionTable.find('input.visibilityCheckbox')
                          .filter('.recipientCheckbox')
                          .filter('[value="INSTRUCTORS"],[value="RECEIVER"]').prop('checked', true);
+    // Set dropdown button text
+    setVisibilityDropdownMenuText('Please select a visibility option <span class="caret"></span>',
```
Comment (whipermr5) [inline src/main/webapp/dev/js/common/questionContrib.es6]: I'm a little hesitant to hardcode the message here, as it comes from a Java constant (what if the Java constant is updated next time, and not this)? However I'm not sure if there is a better solution though. Do you have any ideas?

Comment (VamsiSangam) [inline src/main/webapp/dev/js/common/questionContrib.es6]: Maybe a better design could be to put that string in `const.es6`?

And BTW that value doesn't seem to come from a Java constant either. It appears to be hardcoded in Java too. Maybe I am missing something? :thinking:

**Comment by VamsiSangam** [comment]
I don't think I can use `setVisibilityDropdownMenuText` in `visibilityOptions.es6`, because when I do, I get this -

capture

Which leads to failure of `FeedbackContributionQuestionUiTest`. Any ideas?

File: src/main/webapp/dev/js/common/questionContrib.es6 (hunk 3 above)
Comment (whipermr5) [inline src/main/webapp/dev/js/common/questionContrib.es6]: You're right; I was mistaken 😅 `const.es6` sounds good!

**Comment by whipermr5** [comment]
@VamsiSangam Apologies; I just realised that after selecting a visibility option, cancelling and adding a new question of a non-contrib type, the visibility option (together with the label) does get inherited from the previous selection. So I guess for contrib questions, the label can stay as `Shown anonymously to recipient and team members, visible to instructors`, as per your original approach (6966dac8330470f7535405e8187d29b60d5280e9). Could you revert to that approach? 😅
