### PR TITLE
Instructor: Feedback: View Results: fix the disappearing 'No specific recipient' panel bug #7633

### LINKED ISSUE #7633: Instructor: Feedback: View Results: fix the disappearing 'No specific recipient' panel bug
Noticed while investigating #4282 

**Steps to replicate:**
1. Login as instructor
2. View results for an FS in which there are no questions that do not have a specific recipient. 
3. Load any view EXCEPT for `Group by - Question`

**The problem:**
You will see a panel header with `No specific recipients` (even though there are no such responses). This panel then disappears on clicking.

GIF of isssue:
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by Crphang**
Fixes #7633

**Outline of Solution**

Show `No Specific Section` only if non-empty

As discussed in #7633, the solution can solved in front-end or back-end. But to solve it in front-end, it requires loading the data during `document.onLoad()` to determine if any section is empty or not, which breaks the purpose of using Ajax call and fetching the data on demand.

The solution employed currently is simple and the fixes the issue as shown below.

If there is `No Specific Section`. The data will be rendered accordingly:

no specific section

If `No Specific Section` is empty, then the panel will not be shown:

no-section

### CODE REVIEW

**Comment by Crphang** [comment]
Ready for review @tshradheya.

The non-godmode changes are in `src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java` and `src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java`.

The change in the first file is described in the outline of the solution. The change in the second file is because of removing the `No Specific Section` panel, which causes the numbering to be off in the current `InstructorFeedbackResultsUiTest` and it is required to be changed.

**Comment by tshradheya** [comment]
Thanks @Crphang for the details. Since this will require some manual testing, I will give a complete review by tomorrow 👍

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 1]
```diff
@@ -693,74 +691,74 @@ private void testFeedbackResponseCommentActions() throws Exception {
...
-        resultsPage.verifyCommentRowContent("-1-1-1-1-1", "edited test comment", "Teammates Test");
+        resultsPage.editFeedbackResponseComment("-2-1-0-1-1", "edited test comment");
+        resultsPage.verifyCommentRowContent("-2-1-0-1-1", "edited test comment", "Teammates Test");
         resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsEditComment.html");
 
         ______TS("Typical case: edit comment created by different instructor");
 
         resultsPage.editFeedbackResponseComment("-1-0-1-1-1", "Comment edited by different instructor");
-        resultsPage.verifyCommentRowContent("-1-1-1-1-1", "edited test comment", "Teammates Test");
+        resultsPage.verifyCommentRowContent("-1-0-1-1-1", "Comment edited by different instructor", "Teammates Test");
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Just curious, why is the comment also changing? Shouldn't only index of the id change?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 2]
```diff
@@ -408,61 +408,59 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
-        resultsPage.loadResultSectionPanel(1, 2);
+        resultsPage.loadResultSectionPanel(0, 1);
         resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsAjaxByRGQ.html");
 
         ______TS("Typical case: test view photo for view by recipient > giver > question");
 
         resultsPage.removeNavBar();
-        resultsPage.hoverClickAndViewStudentPhotoOnHeading("1-1",
-                "studentProfilePic?studentemail={*}&courseid={*}&user=CFResultsUiT.instr");
-        resultsPage.hoverAndViewStudentPhotoOnBody("1-1",
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Why is this removed instead of updating the index?

Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Can clarify the two queries?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 1 above)
Comment (Crphang) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: @tshradheya It corresponds to the above `editFeedbackResponseComment` comment edit. The original indexing does not seem to match the line above directly as well.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 2 above)
Comment (Crphang) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: @tshradheya My folly here, will investigate on this.

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 3]
```diff
@@ -698,7 +698,10 @@ private void buildSectionPanelsForForAjaxLoading(List<String> sections) {
 
         InstructorFeedbackResultsSectionPanel sectionPanel = new InstructorFeedbackResultsSectionPanel(
                 Const.DEFAULT_SECTION, Const.NO_SPECIFIC_SECTION, true);
-        sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel);
+
+        if (bundle.getTeamsInSectionFromRoster(Const.DEFAULT_SECTION).size() > 0) {
```
[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: In addition, this won't work for some cases. If you take a careful look at how `getTeamsInSectionFromRoster` is implemented. You will notice that only students are used to generate to map. That is, if we have instructors/general feedback as recipients, you won't display the default section while there is content in the default section.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Hmm, thanks a lot for pointing that out. My initial line of thought is that all sections have teams because teams are compulsory during course enrollment.

What other scenarios will there be no teams but there are content? Is there a good way to determine that using data from `bundle`?

[the remark this answers is not in the document]
Comment (tshradheya) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: What @xpdavid is saying is correct. If I add a question whose recipient is `Nobody specefic`, then in case of results by `RGQ` and `RQG`, the `No Section panel` is not empty.

But this arises another question, should the panel which shows the `responses to Nobody specefic` be called `No specefic Section` or `No specefic recipient`.
This is why the naming of panel has been changed before 
https://github.com/TEAMMATES/teammates/issues/7633#issuecomment-369217282

I think we need to figure out what was the original intention of that panel and it was meant for showing what exactly?
In the current release 6.3.0, it shows 
- all responses of students not belonging to any section
- responses given to recepient as `general`

I think its current behaviour is inconsistent with its naming, which is causing all the confusion

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Agree.
The description is correctly described the things that is display inside `No specific Section`:
> - all responses of students not belonging to any section
> - responses given to recepient as general

I would say it is just `responses given to recipient as general` doesn't fit the `No specific Section`. `No specific recipient` should be more suitable.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: @tshradheya thanks for giving your input as well. I think it is important to clarify what responses `No Specific Section` will have and when it will be non-empty. If not there might be cases where we remove the section but it should have responses.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Can I clarify what type of `responses` these are `responses given to recipient as general`?

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: @Crphang You can choose the feedback path as `xxxx -> Nobody specific (For general class feedback)`

[the remark this answers is not in the document]
Comment (damithc) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: 'No specific recipient' panels are at a inner level than 'No specific section' panels. That's because grouping based on section happen first before grouping by receiver.
It seems 'No specific recipient' panels are currently shown as a dash. I'm fine with that.
image

On an unrelated note, @Crphang the PR title should follow the issue title exactly, unless the PR is only a partial fix or has no matching issue.

[the remark this answers is not in the document]
Comment (tshradheya) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: @Crphang When there is no actual recipient of the response. If this is what you were asking? :P 
image

@xpdavid 
With the current logic of the panel, renaming it to any of the two `No specific section` or `No specific recepient` will be wrong.

- If renamed to `No specific recipient` it will still show responses which have an actual recipient [ this is when no sections are there, so **all** responses are shown in the panel]
- If kept as it is, it is wrong because it shows responses which have recepient as `general feedback` which is not what the name says

[the remark this answers is not in the document]
Comment (tshradheya) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Prof @damithc Thanks for the clarification.

Got one doubt though. 
Case: All students in some section. The feedback session has 1 question with Feedback path `students-> nobody specefic`

Now if Instructor views result in `RGQ` or `RQG` mode the results of this 1 question appear inside the panel `No specific section` when the students actually are in some section. 
This is inconsistent with what the panel says, right?

[the remark this answers is not in the document]
Comment (damithc) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Yes, that should not be the case. Probably a bug.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: @xpdavid After discussing with @tshradheya, there are a couple of solution to this, but each with it's own downside.

1. Include a new `No Specific Recipient` panel that is specifically for `RGQ` and `RQG`. And remove the `general` feedback for instructors from `No Specific Recipient`.
    - We do a frontend check to remove `No Specific Recipient` section `onDocumentLoad` instead of `onClick`, if the view type is *not* `RGQ` or `RQG`. This removes the possibility of the similar bug to occur.
    - This is clean because it creates a very clear separation of `No Specific Recipient` and `No Specific Section` but is a involved solution. Requires changing what goes into `No Specific Sections`, and adding a respective section and section handler.

1. We add another check to check whether there are any responses that is meant as `General Feedback`, and we remove the `No Specific Section` section if there is no such response. However, the bug still persists for view type that is `GQR` or `GRQ` if there are such responses. Because `No Specific Section` is empty for `GQR` and `GRQ` but is non-empty for `RQG` and `RGQ`.
    - Pros: This fix is faster. But doesn't solve the problem completely, but can mitigate it for most cases.

Please advice!

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: I think there are some misunderstanding here.

For @tshradheya question, the behaviour is correct to me. When you group the responses by `RGQ` or `RQG` mode. You would put recipient first, then question/givers blablabla. Therefore, the sections you are talking about are where the recipients should be put to. If the recipient is `No body specific` (general feedback), then it should belong to `No Specific Section` and then belong to `No Specific Recipient`.

@Crphang To me, the first solution is a "hacking" solution. The hidden section`<div>` will "kill" other contributors when they try to fix something >_<. We can do explicitly check (second method) when we add default panel. You can introduce viewType when you `buildSectionPanelsForForAjaxLoading` to see whether we want to add default panel or not.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: @xpdavid, will attempt that

**Comment by Crphang** [comment]
@xpdavid Changes are made. Ready for Review.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 4]
```diff
@@ -1704,4 +1704,14 @@ public String getTextFromComment(Text commentText) {
         }
         return SanitizationHelper.sanitizeForCsv(comment.toString());
     }
+
+    public boolean containsResponsesToInstructorOrGeneral() {
+        for (FeedbackResponseAttributes response : responses) {
+            String recipientIdentifier = response.recipient;
+            if (getSectionFromRoster(recipientIdentifier) == Const.NO_SPECIFIC_RECIPIENT) {
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Can u check the usage for `Const.NO_SPECIFIC_RECIPIENT`. I believe although the code is there, it not has been used (Tried to change `Const.NO_SPECIFIC_RECIPIENT ` to `Const.NO_SPECIFIC_SECTION` in `getSectionFromRoster ` on my CI https://travis-ci.org/xpdavid/teammates/builds/357798558?utm_source=github_status&utm_medium=notification). To me, the comparison is a bit confusing. You are getting the section from the roster but u are comparing it with `NO_SPECIFIC_RECIPIENT`

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 5]
```diff
@@ -693,15 +693,28 @@ private void buildMissingParticipantPanelsForTeam(
...
 
-        InstructorFeedbackResultsSectionPanel sectionPanel = new InstructorFeedbackResultsSectionPanel(
-                Const.DEFAULT_SECTION, Const.NO_SPECIFIC_SECTION, true);
-        sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel);
+        boolean hasGeneralFeedback = false;
+        boolean hasTeamsInNoSection = bundle.getTeamsInSectionFromRoster(Const.DEFAULT_SECTION).size() > 0;
+
+        if ((viewType == InstructorFeedbackResultsPageViewType.RECIPIENT_GIVER_QUESTION
+                || viewType == InstructorFeedbackResultsPageViewType.RECIPIENT_QUESTION_GIVER)
+                && bundle.containsResponsesToInstructorOrGeneral()) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: The if statement tells me that if the viewType is blablabla and the responses contain the feedback to instructors -> then it `hasGeneralFeedback`. A bit confusing.

I think your if statement should be separated into three condition with disjunction.
either feedbackToInstructor || generalFeedback || studentInNoSection.

**Comment by Crphang** [comment]
@xpdavid Ready for Review. Changes added.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 6]
```diff
@@ -465,6 +464,31 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
         resultsPage.hoverClickAndViewStudentPhotoOnHeading("1-2", Const.SystemParams.DEFAULT_PROFILE_PICTURE_PATH);
     }
 
+    @Test
+    public void testViewNoSpecificSection() {
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Since there is no unit test for `bundle` `data` and `action` (that means we need to depend on the system test --- which is no a good practice). Pls make sure that the `InstructorFeedbackResultsPageUiTest.json` contains responses to/from instructors and students in no section.

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 7]
```diff
@@ -1781,4 +1785,24 @@ private int generateIndexForUser(String name, int index, Map<String, Integer> us
...
+     * Checks if we should show No Specific Section panel.
+     *
+     * @return
+     * <ul>
+     * <li>true if the course has teams in Default Section</li>
+     * <li>true if view is RGQ or RQG and there is General Feedback or Feedback to or from Instructors</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
+    private boolean hasNoSpecificSectionPanel(InstructorFeedbackResultsPageViewType viewType) {
```
[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: I feel that this method can be left here, because it's about panel. It's clearer this way.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: We can let `getSectionFromRoster` return `Const.NO_SPECIFIC_SECTION`. But, in this specific case, wouldn't `NO_SPECIFIC_RECIPIENT` be clearer?

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: `NO_SPECIFIC_SECTION` can also refer to the case where students are not in any section, but in the default section.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 6 above)
Comment (Crphang) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: The Sessions I picked are chosen according to the responses it has. For example, `Sanitized Session` has no responses for `RGQ`. So `RGQ` has no `NO_SPECIFIC_SECTION` in that session, while `RGQ` will show `NO_SPECIFIC_SECTION` in `Open Session`.

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: `NO_SPECIFIC_SECTION` is different from `NO_SPECIFIC_RECIPIENT`. For a feedback to instructor, we can say that is should belong to `NO_SPECIFIC_SECTION` because instructor should be longs to no specific section. However, we cannot say it is no specific recipient because instructor is the recipient.

[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Hmm. Okay. Code wise it wouldn't make too much of a difference I think. Naming wise based on your chain of thought, it makes sense to change it to `NO_SPECIFIC_SECTION` then.

[the remark this answers is not in the document]
Comment (xpdavid) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: > I feel that this method can be left here, because it's about panel. It's clearer this way.
You can name it in different way like `hasEntitiesInNoSpecificSection`

**Comment by Crphang** [comment]
@xpdavid Changes Added. Ready for Review

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 8]
```diff
@@ -465,6 +464,31 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
+        ______TS("No Specific Section shown for recipient > question > giver with General Feedback");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: You miss the following scinareo.
1. `recipient > question > giver` with Feedback to instrucotor
1. `student in no section`

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 9]
```diff
@@ -465,6 +464,31 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
+        ______TS("No Specific Section shown giver > question > recipient with Feedback from Instructor");
+        resultsPage.displayByGiverQuestionRecipient();
+        assertTrue(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section not shown for recipient > question > giver with no General Feedback");
+        resultsPage = loginToInstructorFeedbackResultsPageWithViewType("CFResultsUiT.instr",
+                "Session with sanitized data", true, "recipient-question-giver");
+        assertFalse(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section not shown giver > question > recipient with no General Feedback");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Typo? General Feedback should not get involved with giver > question > recipient right?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 10]
```diff
@@ -585,9 +585,10 @@ public void verifySpecifiedPanelIdsAreCollapsed(String[] ids) {
     }
 
     public boolean isSectionPanelExist(String section) {
-        List<WebElement> panels = browser.driver.findElements(By.cssSelector("div[id^='panelHeading-']"));
```
Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Is this change relevant to his PR?

Comment (Crphang) [reply src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Yup. This function is buggy. It can only verify if its true. if its false it throws an exception. I fixed it to use assertFalse with it.

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 11]
```diff
@@ -1781,4 +1785,28 @@ private int generateIndexForUser(String name, int index, Map<String, Integer> us
...
     }
 
+    /**
+     * Checks if we should show No Specific Section panel.
+     *
+     * @return
+     * <ul>
+     * <li>true if the course has teams in Default Section</li>
+     * <li>true if view is GRQ or GQR and there is feedback from Instructors</li>
+     * <li>true if view is RGQ or RQG and there is General Feedback or Feedback to or from Instructors</li>
```
[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: :+1:

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 12]
```diff
@@ -1704,4 +1704,24 @@ public String getTextFromComment(Text commentText) {
...
+        for (FeedbackResponseAttributes response : responses) {
+            String giverIdentifier = response.giver;
+            if (isParticipantIdentifierInstructor(giverIdentifier) && !isParticipantIdentifierStudent(giverIdentifier)) {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    public boolean containsResponsesToInstructorOrGeneral() {
```
[the remark this answers is not in the document]
Comment (Crphang) [reply src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: The check is made in `getSectionFromRoster` which returns `NO_SPECIFIC_SECTION` if it is General Feedback or Feedback to Instructor

**Comment by Crphang** [comment]
@xpdavid Changes added. Ready for Review.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 13]
```diff
@@ -1704,4 +1704,43 @@ public String getTextFromComment(Text commentText) {
...
+     * @return
+     * <ul>
+     * <li>true if the bundle contains response from Instructor</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
+    public boolean containsResponseFromInstructor() {
+        for (FeedbackResponseAttributes response : responses) {
+            String giverIdentifier = response.giver;
+            // Some parts of the code handles a participant as a Student if participant is both Student and Instructor
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: If a instructor is also a student, the response should be considered as student's response.

I believe this comment is better :P

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 14]
```diff
@@ -1704,4 +1704,43 @@ public String getTextFromComment(Text commentText) {
...
+     * @return
+     * <ul>
+     * <li>true if the bundle contains response to Instructor or General</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
+    public boolean containsResponsesToInstructorOrGeneral() {
+        for (FeedbackResponseAttributes response : responses) {
+            String recipientIdentifier = response.recipient;
+            if (getSectionFromRoster(recipientIdentifier) == Const.NO_SPECIFIC_SECTION) {
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Add comment: `getSectionFromRoster` will return Const.NO_SPECIFIC_SECTION for recipient who is Instrutor or Nobody specific.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 9 above)
Comment (xpdavid) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Waiting for your comment :)

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 15]
```diff
@@ -465,6 +464,45 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
+
+        ______TS("No Specific Section shown for recipient > giver > recipient with General Feedback");
+        resultsPage.displayByRecipientGiverQuestion();
+        assertTrue(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section shown giver > question > recipient with Feedback from Instructor");
+        resultsPage.displayByGiverQuestionRecipient();
+        assertTrue(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section shown for recipient > question > giver with Instructor Feedback");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: with Feedback to Instructor?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 16]
```diff
@@ -465,6 +464,45 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
     }
 
+    @Test
+    public void testViewNoSpecificSection() {
+        ______TS("No Specific Section shown for recipient > question > giver with General Feedback");
+        resultsPage = loginToInstructorFeedbackResultsPageWithViewType("CFResultsUiT.instr", "Open Session", true,
+                "recipient-question-giver");
+        assertTrue(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section shown for recipient > giver > recipient with General Feedback");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: Can you group your test cases in w.r.t viewType? It would be more readable :)

Comment (Crphang) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: I can't. Because it depends on which session I signed into. Unless I keep signing in to different sessions for each assertions, but that will take longer for performance?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java (hunk 15 above)
Comment (Crphang) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: 👍

**Comment by Crphang** [comment]
@xpdavid Changes added. Ready for review.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 17]
```diff
@@ -1704,4 +1704,44 @@ public String getTextFromComment(Text commentText) {
         }
         return SanitizationHelper.sanitizeForCsv(comment.toString());
     }
+
+    /**
+     * Checks if bundle contains response from Instructor.
+     *
+     * @return
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Empty `@return` in Javadoc doesn't help. So you can either remove it or add something to it. I recommend u to remove it as u will find yourself writing the same thing as the javadoc summary.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 18]
```diff
@@ -1704,4 +1704,44 @@ public String getTextFromComment(Text commentText) {
...
+                return true;
+            }
+        }
+        return false;
+    }
+
+    /**
+     * Checks if bundle contains response to Instructor or General.
+     *
+     * @return
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Same here.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 19]
```diff
@@ -1704,4 +1704,44 @@ public String getTextFromComment(Text commentText) {
...
+    /**
+     * Checks if bundle contains response from Instructor.
+     *
+     * @return
+     * <ul>
+     * <li>true if the bundle contains response from Instructor</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
+    public boolean containsResponseFromInstructor() {
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: `hasResponseFromInstructor`?

> from Java Coding Standrad - Boolean name convention

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 20]
```diff
@@ -1704,4 +1704,44 @@ public String getTextFromComment(Text commentText) {
...
+    /**
+     * Checks if bundle contains response to Instructor or General.
+     *
+     * @return
+     * <ul>
+     * <li>true if the bundle contains response to Instructor or General</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
+    public boolean containsResponsesToInstructorOrGeneral() {
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: `hasResponseToInstructorOrGeneral` ?

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 21]
```diff
@@ -1781,4 +1785,28 @@ private int generateIndexForUser(String name, int index, Map<String, Integer> us
         return index + 1;
     }
 
+    /**
+     * Checks if we should show No Specific Section panel.
+     *
+     * @return
```
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Same here

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java [hunk 22]
```diff
@@ -1781,4 +1785,28 @@ private int generateIndexForUser(String name, int index, Map<String, Integer> us
         return index + 1;
     }
 
+    /**
+     * Checks if we should show No Specific Section panel.
```
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java]: Checks if any entity (student/instructor) belongs to no specific setion.

A side note: The method doesn't touch anything about panel and therefore the javadoc summary should not talk about panel also.

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 23]
```diff
@@ -465,6 +464,45 @@ public void testViewPhotoAndAjaxForLargeScaledSession() throws Exception {
...
+        resultsPage = loginToInstructorFeedbackResultsPageWithViewType("CFResultsUiT.instr", "Unpublished Session",
+                true, "recipient-question-giver");
+        assertTrue(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section not shown for recipient > question > giver with no General Feedback");
+        resultsPage = loginToInstructorFeedbackResultsPageWithViewType("CFResultsUiT.instr",
+                "Session with sanitized data", true, "recipient-question-giver");
+        assertFalse(resultsPage.isSectionPanelExist(Const.NO_SPECIFIC_SECTION));
+
+        ______TS("No Specific Section not shown giver > question > recipient with no Feedback from Instructor");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java]: `No Specific Section not shown for giver > question > recipient with no Feedback from Instructor`.
You miss word `for` :P

File: src/test/resources/data/InstructorFeedbackResultsPageUiTest.json [hunk 24]
```diff
@@ -1771,7 +1771,22 @@
...
+      },
+      "giverSection": "None",
+      "recipientSection": "None"
+    },
+    "Response to Instructors": {
+      "feedbackSessionName": "Second Session",
+      "courseId": "CFResultsUiT.CS2104",
+      "feedbackQuestionId": "1",
+      "feedbackQuestionType": "TEXT",
+      "giver": "CFResultsUiT.alice.b@gmail.tmt",
```
Comment (xpdavid) [inline src/test/resources/data/InstructorFeedbackResultsPageUiTest.json]: Is the giver a instructor?

Comment (Crphang) [reply src/test/resources/data/InstructorFeedbackResultsPageUiTest.json]: No. Giver is student. This response is to test for response to instructors for `RGQ` questions.  There are already `Instructor->Student` responses in the `json` file.

Comment (xpdavid) [reply src/test/resources/data/InstructorFeedbackResultsPageUiTest.json]: I am thinking whether this testing data will confuse other developers as currently we dosen't support giving feedback to instructor from student side.

**Comment by Crphang** [comment]
@xpdavid Changes added. Ready for review.

**Comment by Crphang** [comment]
@xpdavid Changes are made, ready for review.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 25]
```diff
@@ -1704,4 +1704,42 @@ public String getTextFromComment(Text commentText) {
...
         return SanitizationHelper.sanitizeForCsv(comment.toString());
     }
+
+    /**
+     * Checks if bundle contains response from Instructor.
+     *
+     * <ul>
+     * <li>true if the bundle contains response from Instructor</li>
+     * <li>false otherwise</li>
+     * </ul>
```
Comment (damithc) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Can be shortened as follows.
```java
/**
  * Returns true if bundle contains response from Instructor.
  */
```

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 26]
```diff
@@ -1704,4 +1704,42 @@ public String getTextFromComment(Text commentText) {
...
+    }
+
+    /**
+     * Checks if bundle contains response to Instructor or General.
+     *
+     * <ul>
+     * <li>true if the bundle contains response to Instructor or General</li>
+     * <li>false otherwise</li>
+     * </ul>
+     */
```
Comment (damithc) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: same here.
