### PR TITLE
[#9377] Fix unstable FeedbackSessionsLogicTest

### LINKED ISSUE #9377: Fix unstable FeedbackSessionsLogicTest
There is a chance that `getNewFeedbackSession` will generate invalid a feedback session whose `visible from time` is after `start time`.

```java
private FeedbackSessionAttributes getNewFeedbackSession() {
        return FeedbackSessionAttributes.builder("fsTest1", "testCourse", "valid@email.tmt")
                .withCreatedTime(Instant.now())
                .withStartTime(Instant.now())
                .withEndTime(Instant.now())
                .withSessionVisibleFromTime(Instant.now())
                .withResultsVisibleFromTime(Instant.now())
                .withGracePeriodMinutes(5)
                .withSentOpenEmail(true)
                .withSentPublishedEmail(true)
                .withInstructions("Give feedback.")
                .build();
    }
```

### PR DESCRIPTION
**Pull request by AkshitOstwal**
Fixes #9377 

**Outline of Solution**

As the issue states : 
There is a chance that `getNewFeedbackSession` will generate invalid a feedback session whose `visible` from `time` is after `start time`.

So it was needed that the we add `endTime` after the `session` and `result` both are `visible`.
So i just changed 
```java
private FeedbackSessionAttributes getNewFeedbackSession() {
        return FeedbackSessionAttributes.builder("fsTest1", "testCourse", "valid@email.tmt")
                .withCreatedTime(Instant.now())
                .withStartTime(Instant.now())
                .withEndTime(Instant.now())
                .withSessionVisibleFromTime(Instant.now())
                .withResultsVisibleFromTime(Instant.now())
                .withGracePeriodMinutes(5)
                .withSentOpenEmail(true)
                .withSentPublishedEmail(true)
                .withInstructions("Give feedback.")
                .build();
    }
```
to 
```java
private FeedbackSessionAttributes getNewFeedbackSession() {
        return FeedbackSessionAttributes.builder("fsTest1", "testCourse", "valid@email.tmt")
                .withCreatedTime(Instant.now())
                .withStartTime(Instant.now())
                .withSessionVisibleFromTime(Instant.now())
                .withResultsVisibleFromTime(Instant.now())
                .withEndTime(Instant.now())
                .withGracePeriodMinutes(5)
                .withSentOpenEmail(true)
                .withSentPublishedEmail(true)
                .withInstructions("Give feedback.")
                .build();
    }
```

changing the order in which  `bulider`  are generated will solve this issue.

### CODE REVIEW

**Comment by AkshitOstwal** [comment]
> LGTM! Can you remove the unnecessary changes in `package.json`?
ok i will update it

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 1]
```diff
@@ -1446,9 +1446,9 @@ private FeedbackSessionAttributes getNewFeedbackSession() {
         return FeedbackSessionAttributes.builder("fsTest1", "testCourse", "valid@email.tmt")
                 .withCreatedTime(Instant.now())
                 .withStartTime(Instant.now())
-                .withEndTime(Instant.now())
                 .withSessionVisibleFromTime(Instant.now())
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: Visible should before start?

Actually, why do we want to swap the order to make the session valid? It is totally fine to make use of methods inside `TimeHelperExtension` to make a valid session. e.g. Session visible from 3 hour ago, start from 2 hour ago, end 1 hour ago and visible now.

File: src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java [hunk 2]
```diff
@@ -359,9 +359,9 @@ private FeedbackSessionAttributes getNewFeedbackSession() {
         return FeedbackSessionAttributes.builder("fsTest1", "testCourse", "valid@email.com")
                 .withCreatedTime(Instant.now())
                 .withStartTime(Instant.now())
-                .withEndTime(Instant.now())
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java]: Same here.

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java (hunk 1 above)
Comment (AkshitOstwal) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: > Visible should before start?

that will also work as the session will be first visible than start.

```suggestion
                .withSessionVisibleFromTime(Instant.now())
                .withStartTime(Instant.now())
```
> why do we want to swap the order to make the session valid? It is totally fine to make use of methods inside `TimeHelperExtension` to make a valid session.

i am not sure what do you want to say here , do you mean to use methods like 
`public static Instant getInstantMinutesOffsetFromNow(long offsetInMinutes)` and `public static Instant getInstantHoursOffsetFromNow(long offsetInHours)`  from `TimeHelperExtension` to return an `Instant` and pass it to 
`withStartTime` and `visible` etc methods ?

Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: > that will also work as the session will be first visible than start.

This is a "must" condition. A session must be visible before it can be started.

> i am not sure what do you want to say here 

If we insist to use `Instant.now()`, we need to adjust the order carefully and it might be error-prone in the future. I am saying why not using

```java
...
.withSessionStartTime(TimeHelperExtension. getInstantHoursOffsetFromNow(-1))
.withSessionEndTime(TimeHelperExtension. getInstantHoursOffsetFromNow(0))
...
```
to construct a valid session. No definitive order is required and it will always be a valid session no matter how slow/fast the code is executed.

Comment (AkshitOstwal) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: i have one more idea , why don't We create an `Instant startingTime`  and assign it `Instant.now()` right before returning the `feedbackSessionAttribute`  and using that `startingTime`  as an parameter for all starting methods like  
``` java
     .withCreatedTime(startingTime)
     .withSessionStartTime(startingTime)
     .withStartTime(startingTime)
```
and in other we can simply use `Instant.now()` as a parameter,
this way session would be both valid and concise.

or otherwise we can do it your way
>...
.withSessionStartTime(TimeHelperExtension. getInstantHoursOffsetFromNow(-1))
.withSessionEndTime(TimeHelperExtension. getInstantHoursOffsetFromNow(0))
...

Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: > this way session would be both valid and concise.

Though I don't see concise it can be.

So how about other times? (`endTime`? `resultVisibleTime`? )

Comment (AkshitOstwal) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: > So how about other times?

we will simply use `Instant.now()` for other times ,this way we will get time when they are actually reached in code (no matter how slow/fast code works )

Comment (AkshitOstwal) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: should i do that or anything else ?

Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: You can push your changes first.

**Comment by AkshitOstwal** [comment]
updated , ready for review .

**Comment by jacoblipech** [comment]
hi @AkshitOstwal thanks for the contribution. Do re-look at the issue again. The purpose of this PR is to stagger the time of a feedback session being created so that the feedback session initialised will always be valid. 

While your idea of changing the sequence of `Instant.now()` may work but it is not a full proof solution. I think what @xpdavid wants is for you to stagger the time each attribute is created with a bigger range using existing methods in `TimeHelperExtension`.

>.withSessionStartTime(TimeHelperExtension. getInstantHoursOffsetFromNow(-1))
.withSessionEndTime(TimeHelperExtension. getInstantHoursOffsetFromNow(0))

For example, using the comments above, the start time and end time of the feedback session should differ by 1 hour. Then the session visible time can be a few minutes after the start time and the results only visible a few minutes after the end time. This allows the feedback session created to always be valid.

**Comment by AkshitOstwal** [comment]
hey @jacoblipech 
> Then the session visible time can be a few minutes after the start time

is contradicting with what @xpdavid  said
>This is a "must" condition. A session must be visible before it can be started.

however i understood what you want to say.
I have made changes according to it
for ex
```
time now 03:00
created time will show : 01:00
visible time : 01:58
start time : 02:00
end time : 03:00
result visible : 03:01
```

**Comment by jacoblipech** [comment]
LTGM but let's wait for @xpdavid inputs

**Comment by AkshitOstwal** [comment]
Wooohooo done my first contribution in TEAMMATES 
I can't tell how much happy i am now , @jacoblipech  @xpdavid  thanks a lot guys .
these is such an amazing community i am definitely applying in this community for GSoC 2019 hope i get selected. 👍
