### PR TITLE
[#9252] Fix Javadoc inspection results

### LINKED ISSUE #9252: Javadoc: Fix Inspection Results report by IntelliJ
image

image

### PR DESCRIPTION
**Pull request by jasper-vandemalle**
Fixes #9252 

Fixed Javadoc errors found by IntelliJ.

### CODE REVIEW

File: src/test/java/teammates/test/cases/browsertests/StudentCourseJoinConfirmationPageUiTest.java [hunk 1]
```diff
@@ -14,9 +14,8 @@
 import teammates.test.pageobjects.StudentHomePage;
 
 /**
- * SUT: {@link Const.ActionURIs#STUDENT_COURSE_JOIN},
- *      {@link Const.ActionURIs#STUDENT_COURSE_JOIN_AUTHENTICATED},
- *      {@link Const.ActionURIs#STUDENT_COURSE_JOIN_NEW}.
+ * SUT: {@link Const.WebPageURIs#JOIN_PAGE},
+ *      {@link Const.WebPageURIs#STUDENT_HOME_PAGE}.
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/StudentCourseJoinConfirmationPageUiTest.java]: I don't think `Const.WebPageURIs#STUDENT_HOME_PAGE` is relevant here.

Comment (jasper-vandemalle) [reply src/test/java/teammates/test/cases/browsertests/StudentCourseJoinConfirmationPageUiTest.java]: Removed it from the Javadoc.
