### PR TITLE
Instructors: sessions page: fix 'resend link to view results' #8822

### LINKED ISSUE #8822: Instructors: sessions page: fix 'resend link to view results'
v6.5.1, Chrome

Steps: Login as instructor, go to the 'sessions' page and try to resend links to a published session.

image

Expected: a modal opens up to select recipients

Actual: nothing happens

This feature seems to work on the instructor home page but on in the sessions page.

### PR DESCRIPTION
**Pull request by nidhi98gupta**
Fixes #8822

### CODE REVIEW

**Comment by nidhi98gupta** [comment]
@damithc Ready for review.

**Comment by tshradheya** [comment]
Hey, Totally missed this thread. 

@xpdavid If this PR is of high priority and needs to be merged soon, we can merge it first. I can start working on the tests as a part of different PR right away

**Comment by nidhi98gupta** [comment]
@xpdavid @tshradheya I have added the tests. Ready for review.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java [hunk 1]
```diff
@@ -563,4 +571,32 @@ public void reloadSessionsList() {
...
     }
+
+    public void verifyResendPublishedEmailButtonDoesNotExist(String courseId, String sessionName) {
+        int sessionRowId = getFeedbackSessionRowId(courseId, sessionName);
+        try {
+            getLinkAtTableRow("session-resend-published-email-for-test", sessionRowId);
+            fail("This element should be hidden.");
+        } catch (NoSuchElementException e) {
+            return;
+        }
```
Comment (tshradheya) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java]: This looks better: 

```java
try {
   getLinkAtTableRow("session-resend-published-email-for-test", sessionRowId);
   signalFailureToDetectException("This element should be hidden");
} catch (NoSuchElementException e) {
    ignoreExpectedException();
}
```

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 2]
```diff
@@ -620,6 +623,27 @@ private void testPublishAction() throws Exception {
         ______TS("PUBLISHED: publish link hidden");
         feedbackPage = getFeedbackPageForInstructor(idOfInstructorWithSessions);
         feedbackPage.verifyPublishLinkHidden(courseId, sessionName);
+
+        // Test that the resend published link button can be clicked and the form can be cancelled
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Use `______TS("Resend published link button can be clicked and the form can be cancelled")` instead of the comment

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 3]
```diff
@@ -620,6 +623,27 @@ private void testPublishAction() throws Exception {
...
+        feedbackPage.clickResendPublishedEmailLink(courseId, sessionName);
+        feedbackPage.cancelResendPublishedEmailForm();
+
+        // Test the status message when the form is submitted with empty recipient list
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Same here

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 4]
```diff
@@ -620,6 +623,27 @@ private void testPublishAction() throws Exception {
...
+        feedbackPage.clickResendPublishedEmailLink(courseId, sessionName);
+        feedbackPage.waitForAjaxLoaderGifToDisappear();
+        feedbackPage.submitResendPublishedEmailForm();
+        feedbackPage.waitForPageToLoad();
+        feedbackPage.waitForTextsForAllStatusMessagesToUserEquals(
+                Const.StatusMessages.FEEDBACK_SESSION_RESEND_EMAIL_EMPTY_RECIPIENT);
+
+        // Test the status message when the form is submitted with a recipient list
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Same here

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java (hunk 2 above)
Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Actually you can put one ` ______TS("resend link action: PUBLISHED feedback session");` and then leave the comments as they are

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 5]
```diff
@@ -612,6 +612,9 @@ private void testPublishAction() throws Exception {
         feedbackPage.clickAndCancel(feedbackPage.getPublishLink(courseId, sessionName));
         assertFalse(BackDoor.getFeedbackSession(courseId, sessionName).isPublished());
 
+        // Test that the resend published link button doesn't exist
+        feedbackPage.verifyResendPublishedEmailButtonDoesNotExist(courseId, sessionName);
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: How about refactoring the `verifyResendPublishedEmailButtonDoesNotExist()` function to `checkIfResendPublishedEmailButtonExists` and make it return true/false depending on the exception. Then you can also check later if button exists using `assertTrue/False()` functions

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java (hunk 1 above)
Comment (nidhi98gupta) [reply src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java]: In `../test/pageobjects`, we have used `fail()` everywhere to verify if particular web element exists. Why make two extra functions then?

Comment (tshradheya) [reply src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java]: These functions already exist and have been used in such cases of exceptions testing. 
However this discussion doesn't matter if you are gonna follow this discussion https://github.com/TEAMMATES/teammates/pull/8827#discussion_r195308565

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 6]
```diff
@@ -624,6 +624,7 @@ private void testPublishAndResendLinkAction() throws Exception {
         feedbackPage = getFeedbackPageForInstructor(idOfInstructorWithSessions);
         feedbackPage.verifyPublishLinkHidden(courseId, sessionName);
 
+        ______TS("resend link action: PUBLISHED feedback session");
         // Test that the resend published link button can be clicked and the form can be cancelled
         feedbackPage.clickResendPublishedEmailLink(courseId, sessionName);
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Add `assertTrue(feedbackPage.checkIfResendPublishedEmailButtonExists(courseId, sessionName));` here?

**Comment by nidhi98gupta** [comment]
Thank you for reviewing @xpdavid @tshradheya . :)
