### PR TITLE
ControllerServlet: do not sent email to admin upon error #6587

### LINKED ISSUE #6587: ControllerServlet: do not sent email to admin upon error
Currently, an email alert is sent to the admin if a request is terminated due to an exception. This code is in the ControllerServlet. However, sending an email can delay the termination of the request which can anger GAE into shutting down the entire instance. Simply logging the error is enough because errors logged at SEVERE level generate email alerts anyway.

image

### PR DESCRIPTION
**Pull request by LiHaoTan**
Fixes #6587 

**Outline of Solution**

1. Error report is no longer sent by email immediately.
2. Add comments to explain why an error report will not be sent.

**Additional Info**
I added the comments as I feel the code does not explain why an error report does not need to be sent through email. Not sure if this is appropriate.

I also worked on this issue because the person originally working on the issue [KYUUBI](https://github.com/KYUUBl) have went missing.

### CODE REVIEW

File: src/main/java/teammates/ui/controller/ControllerServlet.java [hunk 1]
```diff
@@ -133,9 +132,14 @@ public final void doPost(HttpServletRequest req, HttpServletResponse resp) throw
...
-            log.severe(ActivityLogEntry.generateSystemErrorReportLogMessage(req, errorReport, userType));
-
+            /*
+             * Error report is not sent immediately as it can delay termination of request which may result
+             * in GAE shutting down the instance. The error report will be sent by email in the cron job
+             * auto/compileLogs later
+             */
+            if (errorReport != null) {
+                log.severe(ActivityLogEntry.generateSystemErrorReportLogMessage(req, errorReport, userType));
+            }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/ControllerServlet.java]: As we are trying to save time here (we have less than 1 second to finish this part), perhaps just a simple `log.severe("Unexpected exception " + e.getMessage())` is enough, in which case we can avoid lines 126-134 too?

Comment (LiHaoTan) [inline src/main/java/teammates/ui/controller/ControllerServlet.java]: Ok I have removed the generating of error report.

File: src/main/java/teammates/ui/controller/ControllerServlet.java [hunk 2]
```diff
@@ -124,18 +121,12 @@ public final void doPost(HttpServletRequest req, HttpServletResponse resp) throw
...
-                                                                  requestUrl, requestParams, userType, t);
-            new EmailSender().sendReport(errorReport);
-            log.severe(ActivityLogEntry.generateSystemErrorReportLogMessage(req, errorReport, userType));
-
+            /*
+             * Log only basic info about the exception to prevent delay in termination of request which can result
+             * in GAE shutting down the instance.
+             * Note that severe logs are sent by email automatically in the cron job auto/compileLogs.
+             */
+            log.severe("Unexpected exception " + t.getMessage());
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/ControllerServlet.java]: Good work. While you are at it, see if there is a way to include the stack trace in the log message. Use `TeammatesException#toStringWithStackTrace(...)`?

File: src/main/java/teammates/ui/controller/ControllerServlet.java [hunk 3]
```diff
@@ -126,7 +127,7 @@ public final void doPost(HttpServletRequest req, HttpServletResponse resp) throw
              * in GAE shutting down the instance.
              * Note that severe logs are sent by email automatically in the cron job auto/compileLogs.
              */
-            log.severe("Unexpected exception " + t.getMessage());
+            log.severe(TeammatesException.toStringWithStackTrace(t));
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/ControllerServlet.java]: Better. Can you also include a`"Unexpected exception caught by ControllerServlet : "` ? I would like an easy way to identify log messages originating from this location.

Comment (LiHaoTan) [inline src/main/java/teammates/ui/controller/ControllerServlet.java]: Ok I have added that. However, there seems to be a failing test unrelated to what I have changed. I have added more details in the conversation.

**Comment by LiHaoTan** [comment]
Running the TestNG test for AccountsDbTest.java results in a failure if testGetAccount is run before testEditAccount.

The failed test can be seen here: https://gist.github.com/anonymous/65a51785dcc12cc9880f5ecfb364cdfd

**Comment by xpdavid** [comment]
@LiHaoTan Yes. The test cases for `*LogicTest` will fail randomly. Should be find after #6778.

**Comment by LiHaoTan** [comment]
@xpdavid Thanks for the info. The tests are now passing.

**Comment by wkurniawan07** [comment]
@damithc doing what is done right now will strip off all the information originally sent via email: request method, request user agent, request path, request URL, request parameters. I believe at least three of them are useful, if not critical, in troubleshooting.

**Comment by damithc** [comment]
> @damithc doing what is done right now will strip off all the information originally sent via email: request method, request user agent, request path, request URL, request parameters. I believe at least three of them are useful, if not critical, in troubleshooting.

This PR is doing what I have been doing for many months now. I've been applying this "fix" to live code before deploying ever since we started having many server crashes. This PR is just migrating my hot patch to the permanent code base. :-p 

Yes, it will strip off useful info from the log message, but those info are logged by GAE anyway, so they are not completely lost. It's just a bit harder to locate. I'm not sure how much we can do within 1 second under full load, so I don't want to risk entire server being killed in order to collect those info. 

Having said that, we'll try to add those things back after we've resolved some of our other performance issues and server crashes are no longer a big concern.

**Comment by wkurniawan07** [comment]
In that case, @LiHaoTan check if the following functions are still used somewhere else:
- `EmailGenerator#generateSystemErrorEmail`
- `ActivityLogEntry#generateSystemErrorReportLogMessage`

If they are not, remove them as well.

**Comment by LiHaoTan** [comment]
Ok I have removed them. I thought they might actually still be useful though.

**Comment by wkurniawan07** [comment]
@LiHaoTan useful as it may, retaining an unused method for that reason is a mindset that causes dead code to stay in a code base. Its effect is non-trivial; you can read about it [here](http://stackoverflow.com/questions/15699995/why-unused-code-should-be-deleted).

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 4]
```diff
@@ -331,49 +330,6 @@ public void testGenerateStudentCourseJoinEmail() throws IOException {
...
-        // As a workaround, after the last common line, change all the stack trace to "..."
-        String lastCommonLineRegex =
-                "(?s)(at org\\.testng\\.TestRunner\\.run\\(TestRunner\\.java:621\\)\\s*)at.*?(\\s*</code>)";
-        String modifiedContent = email.getContent().replaceAll(lastCommonLineRegex, "$1...$2");
-        email.setContent(modifiedContent);
-
-        String subject = String.format(EmailType.ADMIN_SYSTEM_ERROR.getSubject(),
-                                       Config.getAppVersion(), error.getMessage());
-
-        verifyEmail(email, Config.SUPPORT_EMAIL, subject, "/systemCrashReportEmail.html");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: This HTML file should be fine to be removed. It can be found in the folder `src/test/resources/emails`.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 5]
```diff
@@ -331,49 +330,6 @@ public void testGenerateStudentCourseJoinEmail() throws IOException {
...
-
-        error = new AssertionError();
-        email = new EmailGenerator().generateSystemErrorEmail(requestMethod, requestUserAgent, requestPath,
-                                                              requestUrl, requestParam, null, error);
-        subject = String.format(EmailType.ADMIN_SYSTEM_ERROR.getSubject(),
-                                Config.getAppVersion(), "java.lang.AssertionError");
-        modifiedContent = email.getContent().replaceAll(lastCommonLineRegex, "$1...$2");
-        email.setContent(modifiedContent);
-
-        verifyEmail(email, Config.SUPPORT_EMAIL, subject, "/systemCrashReportEmailLessInfo.html");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Similarly here.

**Comment by LiHaoTan** [comment]
@wkurniawan07 Ok I have removed the files, sorry for overlooking them.

Thanks for the link on the dead code. There seems to be one unused method lingering in the codebase though, `AddSectionsToLargeCourses#getResponsesForStudent`, correct me if I am wrong.

File: src/main/java/teammates/logic/api/EmailGenerator.java [hunk 6]
```diff
@@ -646,45 +644,6 @@ private String fillUpInstructorJoinFragment(InstructorAttributes instructor, Str
...
-                "${requestMethod}", requestMethod,
-                "${requestUserAgent}", requestUserAgent,
-                "${requestUrl}", requestUrl,
-                "${requestPath}", requestPath,
-                "${requestParameters}", requestParams,
-                "${errorMessage}", errorMessage,
-                "${stackTrace}", stackTrace);
-
-        EmailWrapper email = getEmptyEmailAddressedToEmail(Config.SUPPORT_EMAIL);
-        email.setSubject(String.format(EmailType.ADMIN_SYSTEM_ERROR.getSubject(), Config.getAppVersion(), errorMessage));
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/EmailGenerator.java]: Looks like I missed this. This enum `EmailType.ADMIN_SYSTEM_ERROR` should be fine to be removed as well.

File: src/main/java/teammates/logic/api/EmailGenerator.java [hunk 7]
```diff
@@ -646,45 +644,6 @@ private String fillUpInstructorJoinFragment(InstructorAttributes instructor, Str
...
-            if (msgTruncateIndex > 0) {
-                errorMessage = stackTrace.substring(0, msgTruncateIndex).trim();
-            } else {
-                errorMessage = "";
-            }
-        }
-
-        String actualUser = userType == null || userType.id == null ? "Not logged in" : userType.id;
-
-        String emailBody = Templates.populateTemplate(EmailTemplates.SYSTEM_ERROR,
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/EmailGenerator.java]: So is `EmailTemplates.SYSTEM_ERROR`, and by extension `src/main/resources/systemErrorEmailTemplate.html`.
