### PR TITLE
[#9758] Feedback Session Edit: Feedback path not set correctly using 'Other predefined combinations'

### LINKED ISSUE #9758: Feedback Session Edit: Feedback path not set correctly using 'Other predefined combinations'
- **Environment**: `master` branch at commit 4346f6f3d5ef8bf9570ab088a9835709f13ca99f.

**Steps to reproduce**
1. log in as an instructor and go to session page
2. edit a session and add a new question in it
3. for `Feedback Path` section, choose `Other predefined combinations...`. under `Who will give the feedback:`, change to `instructors in this course` and observe that `Who the feedback is about:` changes to `Giver (Self feedback)`, do not edit this field and
4. click `Save Changes`

**Expected behaviour**
feedback path should be set to `instructors in this course` will five feedbacks to `Giver (Self feedback)`

**Actual behaviour**
The feedback path is not set correctly, can verify it by previewing as one instructor and observe the question added not shown.

**Additional info**
This is due to the type for the recipient is not updated as giver type changes.

### PR DESCRIPTION
**Pull request by crizyli**
Fixes #9758 

**Outline of Solution**

The problem is if the user does not choose a recipient type, the current recipient type may not be allowed for the newly selected giver type, thus lead to an invalid feedback path.
Check if the current recipient type is allowed for the giver type, if it is not, set the recipient type to the first allowed type for that giver type as default.

### CODE REVIEW

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 1]
```diff
@@ -192,9 +192,16 @@ export class QuestionEditFormComponent implements OnInit {
...
+    // if not, set default recipientType to the first allowed type as default.
+    const allowedRecipientTypes: FeedbackParticipantType[] | undefined = this.allowedFeedbackPaths.get(giverType);
+    let newRecipientType: FeedbackParticipantType = recipientType;
+    if (allowedRecipientTypes && allowedRecipientTypes.indexOf(recipientType) === -1) {
+      newRecipientType = allowedRecipientTypes[0];
+    }
     this.triggerModelChangeBatch({
       giverType,
-      recipientType,
+      newRecipientType,
```
Comment (xpdavid) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts]: This won't work. Please take a look at https://www.sitepoint.com/es6-enhanced-object-literals/ `Object Initialization From Variables`

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 2]
```diff
@@ -192,9 +192,16 @@ export class QuestionEditFormComponent implements OnInit {
    * Change the {@code giverType} and {@code recipientType} and reset the visibility settings.
    */
   changeGiverRecipientType(giverType: FeedbackParticipantType, recipientType: FeedbackParticipantType): void {
+    // check if current recipientType is allowed for giverType,
+    // if not, set default recipientType to the first allowed type as default.
+    const allowedRecipientTypes: FeedbackParticipantType[] | undefined = this.allowedFeedbackPaths.get(giverType);
```
Comment (xpdavid) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts]: Can we be sure that `allowedRecipientTypes` will always be defined?

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 3]
```diff
@@ -192,9 +192,18 @@ export class QuestionEditFormComponent implements OnInit {
    * Change the {@code giverType} and {@code recipientType} and reset the visibility settings.
    */
   changeGiverRecipientType(giverType: FeedbackParticipantType, recipientType: FeedbackParticipantType): void {
+    // check if current recipientType is allowed for giverType,
+    // if not, set default recipientType to the first allowed type as default.
+    /* tslint:disable: no-non-null-assertion */
```
Comment (xpdavid) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts]: The is the technique to disable tslint for an entire block. It is more appropriate to disable **the current line** here.

**Comment by xpdavid** [comment]
Close and reopen to trigger CI.
