### PR TITLE
[#11093] UnauthorizedAccessException should be a checked exception

### LINKED ISSUE #11093: UnauthorizedAccessException should be a checked exception
Current: `UnauthorizedAccessException` is an unchecked exception.

Implication: It can be and has been wrongly thrown by methods that are not related to access control.

Suggestion: Make it a checked exception and make sure that all usages are correct.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #11093

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/Action.java [hunk 1]
```diff
@@ -89,7 +89,13 @@ public void setLogsProcessor(LogsProcessor logsProcessor) {
     /**
      * Checks if the requesting user has sufficient authority to access the resource.
      */
-    void checkAccessControl() {
+    void checkAccessControl() throws UnauthorizedAccessException {
+        String userParam = getRequestParamValue(Const.ParamsNames.USER_ID);
+        if (userInfo != null && userParam != null && !userInfo.isAdmin && !userInfo.id.equals(userParam)) {
+            throw new UnauthorizedAccessException("User " + userInfo.id
+                    + " is trying to masquerade as " + userParam + " without admin permission.");
```
Comment (jianhandev) [inline src/main/java/teammates/ui/webapi/Action.java:96]: Will it be better if we throw an `UnauthorizedAccessException` as long as either `!userInfo.isAdmin` _or_ `!userInfo.id.equals(userParam)`?

Comment (wkurniawan07) [reply src/main/java/teammates/ui/webapi/Action.java:96]: Both conditions imply `userInfo != null`. Non-existent `userParam` means no intention to masquerade, malicious or not.

**Review by rrtheonlyone — APPROVED** [review]
LGTM 💯
