### PR TITLE
session opening reminders timeout #6018

### LINKED ISSUE #6018: session opening reminders timeout
Getting a few of these. This is more critical than closing reminders. Possibly due to large courses?
```
08:02:01.058
teammates.logic.automated.AutomatedRemindersServlet logMessage: TEAMMATESLOG|||feedbackSessionOpeningReminders|||send opening reminders|||true|||Auto|||Unknown|||Unknown|||Unknown|||Generating reminders for opening feedback sessions.|||/feedbackSessionOpeningReminders|||Unknown%2016082108020158
08:02:23.150
com.google.appengine.api.datastore.BaseQueryResultsSource logChunkSizeWarning: This query does not have a chunk size set in FetchOptions and has returned over 1000 results.  If result sets of this size are common for this query, consider setting a chunk size to improve performance.
  To disable this warning set the following system property in appengine-web.xml (the value of the property doesn't matter): 'appengine.datastore.disableChunkSizeWarning'
08:03:12.046
/feedbackSessionOpeningReminders
org.datanucleus.store.appengine.query.QueryExceptionWrappers$JDOQueryTimeoutException
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$2.get(QueryExceptionWrappers.java:88)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator.hasNext(RuntimeExceptionWrappingIterator.java:105)
	at org.datanucleus.store.appengine.query.LazyResult$LazyAbstractListIterator.computeNext(LazyResult.java:210)
	at org.datanucleus.store.appengine.query.AbstractIterator.tryToComputeNext(AbstractIterator.java:132)
	at org.datanucleus.store.appengine.query.AbstractIterator.hasNext(AbstractIterator.java:127)
	at org.datanucleus.store.appengine.query.LazyResult$AbstractListIterator.hasNext(LazyResult.java:169)
	at teammates.storage.api.FeedbackSessionsDb.getFeedbackSessionsWithUnsentOpenEmail(FeedbackSessionsDb.java:182)
	at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsWhichNeedOpenEmailsToBeSent(FeedbackSessionsLogic.java:1117)
	at teammates.logic.core.FeedbackSessionsLogic.scheduleFeedbackSessionOpeningEmails(FeedbackSessionsLogic.java:1614)
	at teammates.logic.automated.FeedbackSessionOpeningRemindersServlet.doGet(FeedbackSessionOpeningRemindersServlet.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:504)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.datanucleus.store.appengine.DatastoreExceptionTranslator$1: The datastore operation timed out, or the data was temporarily unavailable.
	at org.datanucleus.store.appengine.DatastoreExceptionTranslator.wrapDatastoreTimeoutExceptionForQuery(DatastoreExceptionTranslator.java:65)
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$1.get(QueryExceptionWrappers.java:55)
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$2.get(QueryExceptionWrappers.java:86)
	... 45 more
Caused by: com.google.appengine.api.datastore.DatastoreTimeoutException: The datastore operation timed out, or the data was temporarily unavailable.
	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:64)
	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:129)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:197)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:171)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:148)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.hasNext(QueryResultIteratorImpl.java:64)
	at com.google.appengine.api.datastore.PreparedMultiQuery$FilteredMultiQueryIterator.computeNext(PreparedMultiQuery.java:249)
	at com.google.appengine.api.datastore.PreparedMultiQuery$FilteredMultiQueryIterator.computeNext(PreparedMultiQuery.java:185)
	at com.google.appengine.api.datastore.AbstractIterator.tryToComputeNext(AbstractIterator.java:46)
	at com.google.appengine.api.datastore.AbstractIterator.hasNext(AbstractIterator.java:41)
	at com.google.appengine.api.datastore.QueryResultIteratorDelegator.hasNext(QueryResultIteratorDelegator.java:38)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:50)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:46)
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$1.get(QueryExceptionWrappers.java:51)
	... 46 more

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #6018

Might break some tests, will let Travis run first.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Hmmm I met a roadblock: our testing routine is no longer suitable when the query time is narrowed down. This definitely needs to be resolved, but will take quite some time (and might need its own issue/PR if anything).

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 1]
```diff
@@ -542,41 +541,46 @@ public void deleteFeedbackSessionsForCourses(List<String> courseIds) {
     }
     
     @SuppressWarnings("unchecked")
-    private List<FeedbackSession> getFeedbackSessionEntitiesWithUnsentOpenEmail() {
+    private List<FeedbackSession> getFeedbackSessionEntitiesNeedingOpenEmail() {
         Query q = getPm().newQuery(FeedbackSession.class);
-        q.declareParameters("boolean sentParam, Enum notTypeParam");
-        q.setFilter("sentOpenEmail == sentParam && feedbackSessionType != notTypeParam");
+        q.declareParameters("java.util.Date yesterday, boolean sentParam");
+        q.setFilter("startTime > yesterday && sentOpenEmail == sentParam");
```
Comment (JosephineKwa) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Maybe `twoDaysAgo` instead of `yesterday`

Comment (wkurniawan07) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: @JosephineKwa changed to `startTimeParam`, so that it's changes-resistant.

**Comment by wkurniawan07** [comment]
@JosephineKwa can review again, the red "X" is caused by the failure fixed via #6008 (not part of the `release` branch).

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 2]
```diff
@@ -542,41 +541,46 @@ public void deleteFeedbackSessionsForCourses(List<String> courseIds) {
     }
     
     @SuppressWarnings("unchecked")
-    private List<FeedbackSession> getFeedbackSessionEntitiesWithUnsentOpenEmail() {
+    private List<FeedbackSession> getFeedbackSessionEntitiesNeedingOpenEmail() {
         Query q = getPm().newQuery(FeedbackSession.class);
-        q.declareParameters("boolean sentParam, Enum notTypeParam");
-        q.setFilter("sentOpenEmail == sentParam && feedbackSessionType != notTypeParam");
+        q.declareParameters("java.util.Date startTimeParam, boolean sentParam");
+        q.setFilter("startTime > startTimeParam && sentOpenEmail == sentParam");
```
Comment (JosephineKwa) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Hm won't this also get feedback sessions that have not yet been opened? To me that is somewhat unintuitive as the method name implies that it gets feedback sessions which have already opened.

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 3]
```diff
@@ -542,41 +541,46 @@ public void deleteFeedbackSessionsForCourses(List<String> courseIds) {
...
     }
     
     @SuppressWarnings("unchecked")
     private List<FeedbackSession> getFeedbackSessionEntitiesNeedingClosingEmail() {
         Query q = getPm().newQuery(FeedbackSession.class);
-        q.declareParameters("boolean sentParam, boolean enableParam, Enum notTypeParam");
-        q.setFilter("sentClosingEmail == sentParam && isClosingEmailEnabled == enableParam "
-                    + "&& feedbackSessionType != notTypeParam");
+        q.declareParameters("java.util.Date startTimeParam, boolean sentParam, boolean enableParam");
+        q.setFilter("endTime > startTimeParam && sentClosingEmail == sentParam && isClosingEmailEnabled == enableParam");
```
Comment (JosephineKwa) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Should this be `endTimeParam` instead of `startTimeParam`

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 4]
```diff
@@ -542,41 +541,46 @@ public void deleteFeedbackSessionsForCourses(List<String> courseIds) {
...
     }
     
     @SuppressWarnings("unchecked")
     private List<FeedbackSession> getFeedbackSessionEntitiesNeedingClosedEmail() {
         Query q = getPm().newQuery(FeedbackSession.class);
-        q.declareParameters("boolean sentParam, boolean enableParam, Enum notTypeParam");
-        q.setFilter("sentClosedEmail == sentParam && isClosingEmailEnabled == enableParam "
-                    + "&& feedbackSessionType != notTypeParam");
+        q.declareParameters("java.util.Date startTimeParam, boolean sentParam, boolean enableParam");
+        q.setFilter("endTime > startTimeParam && sentClosedEmail == sentParam && isClosingEmailEnabled == enableParam");
```
Comment (JosephineKwa) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: I think this should be `endTimeParam` too

Comment (JosephineKwa) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Won't this also get sessions which may not have closed yet?

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java (hunk 2 above)
Comment (damithc) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Yes, we should probably change the method name.

Comment (wkurniawan07) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Either method name is not 100% accurate:
- `getFeedbackSessionsWithUnsentOpenEmail()`: nowhere does it imply that date is part of the filter
- `getFeedbackSessionsNeedingOpenEmail()`: may be misleading because not-yet-opened sessions are included

Same problems apply for closing/closed email.

**Comment by JosephineKwa** [comment]
Just need a minor clarification regarding `startTimeParam` for `getFeedbackSessionEntitiesNeedingClosingEmail` and `getFeedbackSessionEntitiesNeedingClosedEmail`, changes look good otherwise!

**Comment by wkurniawan07** [comment]
@JosephineKwa change made, not sure why Travis did not build it (a fault on their side again?) but since the change is internal within method it should not affect the previous passing status. I keep the method name for now because like I said either one is not a 100% accurate representative.

**Comment by wkurniawan07** [comment]
@damithc can this be merged? I can push another hot-patch release afterwards.

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java (hunk 2 above)
Comment (damithc) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: `getSessionsPossiblyNeedingOpenEmail`? Add a header comment to explain which criteria is used exactly.

**Comment by damithc** [comment]
Ok, can merge.
