### PR TITLE
AccountAttributesTest: fix instability due to modified timestamp comparison #8709

### LINKED ISSUE #8709: AccountAttributesTest: fix instability due to modified timestamp comparison
- **Environment**:  [cd9a536](https://github.com/TEAMMATES/teammates/commit/cd9a5365cfed580bae5d1bf15f2994a921e31f03)

**Description of feature/enhancement**

This is an enhancement to the build process

As pointed out by @bqnguyen94 also, currently ```AccountAttributeTest::testSanitizeForSaving``` as shown below

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java#L114-L126

fails sometimes (CI tests) at line 125 during comparison of ```StudentProfileAttributes``` because ```modifiedDate``` parameter is created using ```Instant.now()``` as shown below:

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java#L36-L46

**Justification**

If we mock the system time we can bypass this which will be beneficial to developers in future.

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8709

**Outline of Solution**

- `Instant.now()` is unstable in tests
- So we need to hardcode the `modifiedDate` in tests to make it stable

Note:
As the migration to `java.time`  is still going on, there might be more such cases of unstable tests

### CODE REVIEW

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 1]
```diff
@@ -315,6 +315,7 @@ private AccountAttributes createAccountAttributesToSanitize() {
                     .withGender(gender)
                     .withMoreInfo(moreInfo)
                     .withPictureKey(pictureKey)
+                    .withModifiedDate(Instant.parse("2018-03-30T13:23:42.663Z"))
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Can use `Const#TIME_REPRESENTS_DEFAULT_TIMESTAMP` if you need an arbitrary `Instant`.
