### PR TITLE
Instuctor : Feedback Questions : MCQ/MSQ questions : Disable drop down menu by default #8576

### LINKED ISSUE #8576: Instuctor : Feedback Questions : MCQ/MSQ questions : Disable drop down menu by default
**Environment**
`master` branch

**Steps to reproduce:**
- Login as `Instructor`
- Create a new session or edit an existing one
- Click on `Add new questions`
- Select MCQ/MSQ question
- The checkbox for `Or, generate options from the list of all` is not be selected by default but the drop down menu will be enabled, where as the other options `Max number of *` and `Min number of *` will be disabled as usual (In case of MSQ question): 
screenshot 395
- Now select the checkbox and then deselect it 
- The drop down menu is now disabled (as it should be in the first place) : 
screenshot 396

**Expected behaviour:** The drop down menu should be disabled by default and only get enabled when that option is selected.

**Actual behaviour:** The menu is enabled immediately after adding the questions, and gets disabled after we select-deselect the checkbox. or when we `Edit` the question after saving it.

### LINKED ISSUE #8590: MCQ: MSQ: Give Different ID for generatedOptions
Regression noticed while working on #8584 

Currently, the id for the element used to denote from which choice are options generated is same for MCQ and MSQ.

Since it is `generatedOptions-questionNum` it is different for saved questions. However when new question is created, the NEW_QUESTION=-1 and id is same, hence they misbehave causing either mcq or msq generated from to change without reflecting on the UI.

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #8576 
Fixes #8590 

**Outline of Solution**

- Fixed brackets to prevent `undefine` `questionNum`
- Used `.prop('checked')` instead of `.checked` to avoid undefined case. https://github.com/TEAMMATES/teammates/issues/8576#issuecomment-370197963
- Gave different id for `generatedOptions` for MCQ ( `mcqGeneratedOptions`) and MSQ ( `msqGeneratedOptions`) to avoid conflict while adding new question{especially after cancelling a question}

### CODE REVIEW

**Comment by tshradheya** [comment]
@Crphang Ready for Review :)

File: src/main/java/teammates/common/util/Const.java [hunk 1]
```diff
@@ -743,7 +743,8 @@ private Const() {
         public static final String FEEDBACK_QUESTION_CONSTSUMPOINTSFOREACHRECIPIENT = "constSumPointsForEachRecipient";
         public static final String FEEDBACK_QUESTION_CONSTSUMDISTRIBUTEUNEVENLY = "constSumUnevenDistribution";
         public static final String FEEDBACK_QUESTION_CONTRIBISNOTSUREALLOWED = "isNotSureAllowedCheck";
-        public static final String FEEDBACK_QUESTION_GENERATEDOPTIONS = "generatedOptions";
+        public static final String FEEDBACK_QUESTION_MCQGENERATEDOPTIONS = "mcqGeneratedOptions";
```
Comment (Crphang) [inline src/main/java/teammates/common/util/Const.java]: As part of the discussion in #8373, we prefer to have `_` after every word to make it readable. As of the rest and consistency issue, we can probably have another code quality issue to fix it.

File: src/main/webapp/dev/js/common/questionMsq.js [hunk 2]
```diff
@@ -177,19 +177,19 @@ function toggleMsqMinSelectableChoices(questionNum) {
...
-        $(`#generatedOptions-${questionNum}`).attr('value',
+        $(`#msqGeneratedOptions-${questionNum}`).attr('value',
                 $(`#msqGenerateForSelect-${questionNum}`).prop('value'));
     } else {
         $(`#msqChoiceTable-${questionNum}`).find('input[type=text]').prop('disabled', false);
         $(`#msqChoiceTable-${questionNum}`).show();
         $(`#msqGenerateForSelect-${questionNum}`).prop('disabled', true);
         $(`#msqOtherOptionFlag-${questionNum}`).closest('.checkbox').show();
-        $(`#generatedOptions-${questionNum}`).attr('value', 'NONE');
+        $(`#msqGeneratedOptions-${questionNum}`).attr('value', 'NONE');
```
Comment (Crphang) [inline src/main/webapp/dev/js/common/questionMsq.js]: You might want to use `.val()` instead? Checkout this discussion https://stackoverflow.com/questions/8312820/jquery-val-vs-attrvalue

Most of the codebase uses .val() too anyway, would be good to be consistent

**Comment by tshradheya** [comment]
@Crphang Thanks for the review. 
Some good points suggested and I have made the necessary changes.

Let me know if the changes are okay

**Comment by tshradheya** [comment]
@Crphang Reminder for reviewing :)

File: src/main/webapp/dev/js/common/questionMcq.js [hunk 3]
```diff
@@ -54,19 +54,18 @@ function removeMcqOption(index, questionNum) {
...
 function toggleMcqGeneratedOptions(checkbox, questionNum) {
-    if (checkbox.checked) {
+    if ($(checkbox).prop('checked')) {
         $(`#mcqChoiceTable-${questionNum}`).find('input[type=text]').prop('disabled', true);
         $(`#mcqChoiceTable-${questionNum}`).hide();
         $(`#mcqGenerateForSelect-${questionNum}`).prop('disabled', false);
         $(`#mcqOtherOptionFlag-${questionNum}`).closest('.checkbox').hide();
-        $(`#generatedOptions-${questionNum}`).attr('value',
-                $(`#mcqGenerateForSelect-${questionNum}`).prop('value'));
+        $(`#mcqGeneratedOptions-${questionNum}`).val($(`#mcqGenerateForSelect-${questionNum}`).prop('value'));
```
Comment (xpdavid) [inline src/main/webapp/dev/js/common/questionMcq.js]: Reuse `changeMcqGenerateFor`?

File: src/main/webapp/dev/js/common/questionMsq.js [hunk 4]
```diff
@@ -177,19 +177,18 @@ function toggleMsqMinSelectableChoices(questionNum) {
...
 function toggleMsqGeneratedOptions(checkbox, questionNum) {
-    if (checkbox.checked) {
+    if ($(checkbox).prop('checked')) {
         $(`#msqChoiceTable-${questionNum}`).find('input[type=text]').prop('disabled', true);
         $(`#msqChoiceTable-${questionNum}`).hide();
         $(`#msqGenerateForSelect-${questionNum}`).prop('disabled', false);
         $(`#msqOtherOptionFlag-${questionNum}`).closest('.checkbox').hide();
-        $(`#generatedOptions-${questionNum}`).attr('value',
-                $(`#msqGenerateForSelect-${questionNum}`).prop('value'));
+        $(`#msqGeneratedOptions-${questionNum}`).val($(`#msqGenerateForSelect-${questionNum}`).prop('value'));
```
Comment (xpdavid) [inline src/main/webapp/dev/js/common/questionMsq.js]: Reuse `changeMsqGenerateFor`?
See if we need `adjustMinMaxSelectableChoices` or not (I think we need it).

File: src/main/webapp/dev/js/main/instructorFeedbackEdit.js [hunk 5]
```diff
@@ -537,8 +537,8 @@ function enableNewQuestion() {
 
     moveAssignWeightsCheckbox($newQuestionTable.find(`#rubricAssignWeights-${NEW_QUESTION}`));
 
-    toggleMcqGeneratedOptions($(`#generateMcqOptionsCheckbox-${NEW_QUESTION}`, NEW_QUESTION));
-    toggleMsqGeneratedOptions($(`#generateMsqOptionsCheckbox-${NEW_QUESTION}`, NEW_QUESTION));
+    toggleMcqGeneratedOptions($(`#generateMcqOptionsCheckbox-${NEW_QUESTION}`), NEW_QUESTION);
```
Comment (xpdavid) [inline src/main/webapp/dev/js/main/instructorFeedbackEdit.js]: :O :P

File: src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag [hunk 6]
```diff
@@ -137,8 +137,11 @@
   <input type="hidden" name="<%= Const.ParamsNames.FEEDBACK_QUESTION_SHOWGIVERTO %>" >
   <input type="hidden" name="<%= Const.ParamsNames.FEEDBACK_QUESTION_SHOWRECIPIENTTO %>" >
   <input type="hidden" name="<%= Const.ParamsNames.USER_ID %>" value="${data.account.googleId}">
-  <input type="hidden" name="<%= Const.ParamsNames.FEEDBACK_QUESTION_GENERATEDOPTIONS %>"
+  <input type="hidden" name="<%= Const.ParamsNames.FEEDBACK_QUESTION_MCQ_GENERATED_OPTIONS %>"
+         value="<%= FeedbackParticipantType.NONE.toString() %>"
+         id="<%= Const.ParamsNames.FEEDBACK_QUESTION_MCQ_GENERATED_OPTIONS %>">
```
Comment (xpdavid) [inline src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: Why we need `id` here? This could introduce possibility of duplicated id in the same HTML file.

File: src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag [hunk 7]
```diff
@@ -137,8 +137,11 @@
...
+  <input type="hidden" name="<%= Const.ParamsNames.FEEDBACK_QUESTION_MSQ_GENERATED_OPTIONS %>"
       value="<%= FeedbackParticipantType.NONE.toString() %>"
-      id="<%= Const.ParamsNames.FEEDBACK_QUESTION_GENERATEDOPTIONS %>">
+      id="<%= Const.ParamsNames.FEEDBACK_QUESTION_MSQ_GENERATED_OPTIONS %>">
```
Comment (xpdavid) [inline src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: Same here.

File: src/main/webapp/dev/js/common/questionMsq.js (hunk 4 above)
Comment (tshradheya) [reply src/main/webapp/dev/js/common/questionMsq.js]: Yes we need it.

But since I am now reusing `changeMsqGenerateFor(questionNum)`, it already has the `adjustMinMaxSelectableChoices(questionNum);` invoked inside the function.

File: src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag (hunk 6 above)
Comment (tshradheya) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: I don't understand how the duplicate id might happen?
Initially, there was `id` field which is being used in tests to get the element.

Comment (xpdavid) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: I feel a little bit strange here since there is not suffix for the id. (Yeah, I know, it's new question from, there won't be another new question form in the same page :P)

Further investigation tells me that this might be legacy code.
image
You can see we actually have two `name="generatedOptions"` here. I suspect we always get the first one and therefore there is no bug currently.

Comment (tshradheya) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: I can understand the part of not having the suffix for id, but the `mcqGeneratedOptions` id is actually used for sending the details of the question and as you said only one new question can be made at a time so it works as expected.

The thing is I need to have the `id` for the hidden input of the field as its used a lot of times in test to check for the value.

So should I go and put back the `id` for the hidden input of mcq and msq as before?

Comment (tshradheya) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: @xpdavid waiting for your input on this https://github.com/TEAMMATES/teammates/pull/8584#discussion_r175252240

Comment (xpdavid) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: Ok. I see some misunderstanding here. When u get parameters from the server side, u actually refer to the `name` attribute rather than `id` attribute.

Refer to my previous comment:
>>> I suspect we always get the first one and therefore there is no bug currently.

It looks like we could delete this line without break anything. I hope u can understand my concern here as we don't want to just make things work without knowing why it works.

Comment (tshradheya) [reply src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag]: Thanks. I understand better now.
Looking into it

**Comment by tshradheya** [comment]
@xpdavid You were right about the extra lines of input. I removed them and manually tested and it works.
I now understand why those lines could have potentially been buggy now that the change for generatedOptions has been made.

Ready for reviewing :)

**Comment by tshradheya** [comment]
All these bugs with MCQ/MSQ questions happen only when a new question is added after canceling the addition of question before.

Since the state of question is in a way[not sure if it was intended when designing it] stored , the #8472 test cases worked because the error only happened when `enableNewQuestion()` was called and the state was still stored by chance even after canceling the question **so we got lucky that the state stored after cancelling the question was as tested**. The code written before that was also wrong because it accessed an id which was not even a part of the HTML page.

Infact when I fixed the brackets error the #8472 test cases failed and thats why I realized that the problem was also in the same id for mcq and msq questions. Another issue was https://github.com/TEAMMATES/teammates/issues/8576#issuecomment-370197963 which has alse been resolved here.

I feel it makes sense to add the test case in this PR itself. I am assuming the only test case scenario that needs to be added is to check if the dropdown is disabled or not after canceling the question and adding it again[given checkbox was clicked on first time of adding the question]

**Comment by tshradheya** [comment]
@xpdavid I see that you have suggested to modify the test cases, but I am not quite sure as to how we can make it more proper.

I can only think of checking of the checkbox is selected and checking the disabled part and seeing if the choice from dropdown is as expected. Do you have any other suggestions to improve the test cases?

**Comment by xpdavid** [comment]
> I can only think of checking of the checkbox is selected and checking the disabled part and seeing if the choice from dropdown is as expected.

Checking whether the checkbox is disabled or not should be enough. We are not testing whether `toggleXXXX` works or not. We are testing whether it has been called or not.

**Comment by tshradheya** [comment]
@xpdavid Added tests as suggested.
Ready for Review
