### PR TITLE
StudentsDbTest failing due to wrong ordering #5444

### LINKED ISSUE #5444: StudentsDbTest failing due to wrong ordering
In testGetStudent(), also has bugs and redundant tests.

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #5444

### CODE REVIEW

File: src/test/java/teammates/test/cases/storage/StudentsDbTest.java [hunk 1]
```diff
@@ -175,14 +175,10 @@ public void testGetStudent() throws InvalidParametersException, EntityDoesNotExi
         s2 = createNewStudent("one.new@gmail.com");
         assertTrue(studentsDb.getUnregisteredStudentsForCourse(s2.course).get(0).isEnrollInfoSameAs(s2));
         
-        s2.googleId = null;
-        studentsDb.updateStudentWithoutSearchability(s2.course, s2.email, s2.name, s2.team, s2.section, s2.email, s2.googleId, s2.comments);
-        assertTrue(studentsDb.getUnregisteredStudentsForCourse(s2.course).get(0).isEnrollInfoSameAs(s2));
```
Comment (kanghj) [inline src/test/java/teammates/test/cases/storage/StudentsDbTest.java]: Explain here why this is removed

Comment (LowWeiLin) [inline src/test/java/teammates/test/cases/storage/StudentsDbTest.java]: These lines are not testing any functions that have not already been tested. Also, getAllStudents is deprecated and should not be used.

**Comment by wkurniawan07** [comment]
@damithc this one is ready for review as well.
