### PR TITLE
[#11760] Decouple deadline extension from feedback session update request

### LINKED ISSUE #11760: Instructor editing sessions and deadline extensions: Synchronize data between tabs
Steps to reproduce:
1. Open a tab as an instructor, and navigate to edit extension page.
2. Open up another tab, and navigate to edit sessions page.
3. At the edit extension page, add / delete some extensions.
4. At the edit sessions page, save the changes.

Saving the changes at the edit sessions page at step 4 will delete the extension changes that were made in step 3.
This is because the session loaded for the tab in step 3 does not contain the extension changes.
The bug can be repeated in the other order too. (Edit details, then edit extensions).

The problem is that the instructor is unaware of the bug, and may find the extensions of students to mysteriously be deleted. Furthermore, there will be no emails sent to the students of the deletion.

Some suggested solutions:
1. One of the contributing factors is that the extension page is on a separate page, and users may open 2 tabs for extension. Hence, refactor the extension page as a toggle on the edit sessions page. Users will do all the editing on one page. #11692 may be useful. 
2. Make the edit of extensions (and/or edit session details) to be PATCH requests instead.
3. Refresh the data for feedback session right before submitting the edit request. - May be costly in the long run. On average, currently there are about ~50 calls/day to update a feedback session.

Any other possible solutions are welcome too

### PR DESCRIPTION
**Pull request by TobyCyan**
Fixes #11760

**Outline of Solution**

* Separated deadline extensions update request and feedback session update request.
* Updating feedback session in one tab will not affect individual deadline extension updating on another tab.
* Added tests for `UpdateFeedbackSessionDeadlineExtensionsAction` and `UpdateFeedbackSessionActionTest`.
* Added a `userId` in `DeadlineExtension` sql entity to provide mapping with a list of fetched users in a course. This removes the need for lazy loading the `DeadlineExtension`'s `user` property which incurs an extra DB read.

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/UpdateFeedbackSessionDeadlineExtensionsAction.java [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+                && !sqlLogic.verifyStudentsExistInCourse(courseId, new ArrayList<>(studentDeadlines.keySet()));
+        if (hasInvalidStudentEmails) {
+            throw new EntityNotFoundException("There are students which do not exist in the course.");
+        }
+
+        Map<String, Instant> instructorDeadlines = updateRequest.getInstructorDeadlines();
+        boolean hasInvalidInstructorEmails = !oldInstructorDeadlines.keySet()
+                .containsAll(instructorDeadlines.keySet())
+                && !sqlLogic.verifyInstructorsExistInCourse(courseId, new ArrayList<>(instructorDeadlines.keySet()));
+        if (hasInvalidInstructorEmails) {
```
Comment (samuelfangjw) [inline src/main/java/teammates/ui/webapi/UpdateFeedbackSessionDeadlineExtensionsAction.java]: Checking existence here no longer necessary. Previously in the datastore model there was a real risk of data integrity issues, so this was done to minimise the risk. However in the new SQL model, the DB enforces the user non-null constraint so this check adds relatively little value.

**Review by samuelfangjw — CHANGES_REQUESTED** [review]

File: src/main/java/teammates/ui/output/FeedbackSessionDeadlineExtensionsData.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        studentDeadlines.clear();
+    }
+
+    /**
+     * Hides deadline information from an instructor without appropriate privilege.
+     */
+    public void hideInformationForInstructor(String instructorEmail) {
+        instructorDeadlines.keySet().removeIf(email -> !(email.equals(instructorEmail)));
+        studentDeadlines.clear();
+    }
```
Comment (samuelfangjw) [inline src/main/java/teammates/ui/output/FeedbackSessionDeadlineExtensionsData.java]: These shouldn't be here, unused.

**Review by samuelfangjw — APPROVED** [review]
