### PR TITLE
[#9666] Modal is not removed when going back to the previous browser page

### LINKED ISSUE #9666: Modal is not removed when going back to the previous browser page
- **Environment**: `master` branch at commit 87a87e9e

**Steps to reproduce**
1. Go to student home page (`/web/student/home`)
2. Click `View Submission` for a session that has been closed. This brings you to the session page and a modal pops up. Do NOT close it.
3. Go the the previous browser page, i.e., click the "back" button

**Expected behaviour**
The modal is removed when navigating back to the previous page.

**Actual behaviour**
The modal still remains on the screen. If you go "forward" to the feedback session page, and then go back and then go forward (and so on...), the number of modal boxes increases.

20190411_23h06_13

### PR DESCRIPTION
**Pull request by amrut-prabhu**
Fixes #9666

yws0dco4jLkFUZliqtNmPRdnfGXw954l

### CODE REVIEW

**Comment by amrut-prabhu** [comment]
@monmanuela Can you review this?

**Comment by amrut-prabhu** [comment]
@tanhengyeow requesting your review :)

File: src/web/app/page.component.ts [hunk 1]
```diff
@@ -87,6 +90,9 @@ export class PageComponent {
         fromEvent(window, 'online').pipe(mapTo(true)),
         fromEvent(window, 'offline').pipe(mapTo(false)),
     );
+
+    // Closes modals when the back or forward button is clicked in the browser
+    location.onPopState(() => this.modalService.dismissAll());
```
Comment (tanhengyeow) [inline src/web/app/page.component.ts]: Do we have > 1 modal at any point of time? If we can use `.close()` instead of `.dismissAll()`.

If so let's change the comment from, <s>modals</s> -> modal

Comment (amrut-prabhu) [reply src/web/app/page.component.ts]: > If we can use .close() instead of .dismissAll()

Wouldn't we have to implement this behaviour for every single modal in that case? `NgbModal` doesn't have a `.close()` function 😕 

Also, I think `.dismiss()` is better than `.close()` in our case. If you try to `.close()` the `tm-course-soft-deletion-confirm-modal` when going back to the previous page, the course ends up being deleted.

> If so let's change the comment from, modals -> modal

I've updated the comment 👍

**Comment by amrut-prabhu** [comment]
@xpdavid Ready for final review
