### PR TITLE
[#10584] [#10606] [#10607] Fix MSQ question settings and modal scroll

### LINKED ISSUE #10584: Remind all modal from session results page cannot scroll
The remind all modal from the session results page cannot be scrolled to select the `Submit` button when number of students in the session overflows past the page (see screenshot)

Screenshot 2020-08-13 at 1 30 50 PM

**Environment**: Deployed production environment on v7-0-2 on Safari, MacOS

**Steps to reproduce**
Have a course with lots of students (necessary size dependent on user screen resolution) and click "Remind All" from a session result page

**Expected behaviour**
Able to scroll down to select the "Submit" button

**Actual behaviour**
Cannot scroll down

### LINKED ISSUE #10606: MSQ Question: Wrong max and min options message
- **Environment**: `V7.0.2`

**Steps to reproduce**
Create MSQ question with max or min number of options selectable.

When max number is selected:
msq-question

When min number is selected:
msq-question-min

### LINKED ISSUE #10607: MSQ question: Other option counts as 2 selections
- **Environment**: `V7.0.2`

**Steps to reproduce**
Set max options for MSQ option as 2
Try to submit 2 options including other.

OR

Set min options for MSQ option as 2
Try to submit only other option.

**Expected behaviour**
Succeed for first case and fail for second case

**Actual behaviour**
Fails for first case and succeeds for second case

**Additional info**
When max is set to 3 and 2 options including other is picked, it succeeds.
All three scenarios lead me to believe other counts as 2 selections.

3 selected but fails when max is 3
other-option

1 selected but succeeds when min is 2
other-option-min

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #10584 
Fixes #10606 
Fixes #10607

### CODE REVIEW

File: src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public String getAnswerString() {
         boolean isOtherEnabled = msqQuestionDetails.isOtherEnabled();
 
         // number of Msq options selected including other option
-        int totalChoicesSelected = answers.size() + (isOther ? 1 : 0);
+        int totalChoicesSelected = answers.size();
```
Comment (xpdavid) [inline src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java:38]: We might want to cover the case with a test case.

File: src/web/styles.scss [hunk 2]
```diff
@@ -90,7 +90,6 @@ h6,
   max-height: 90vh;
   max-width: 70vw;
   min-width: 30vw;
-  overflow-y: scroll;
```
Comment (niqiukun) [inline src/web/styles.scss:93]: Maybe better to add `margin-bottom: 1.75rem` to `modal-content`  so that the modal does not stick to the bottom of the page.

File: src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java (hunk 1 above)
Comment (wkurniawan07) [reply src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java:38]: Leave it to #1501

File: src/web/styles.scss (hunk 2 above)
Comment (wkurniawan07) [reply src/web/styles.scss:93]: I actually have another PR to refine modals: #10550. Right now let's focus to fix the important issue (modal not scrolling in Safari) first.
