### PR TITLE
[#11157] Improve error message for mismatching google accounts

### LINKED ISSUE #11157: Student accessing link using wrong Google account: give a more specific error message
Context: 
1. A student has joined a course using a Google account earlier.
2. The student is logged into a different Google account.
2. The student clicks on an access link (either to submit or to view results)
3. Current: TEAMMATES gives a generic error `Not authorized to view this page`
   Suggested: Make the error message more explanatory e.g., `You joined TEAMMATES with the Google account johnd... [partial user name] but now trying to access using the account TimKook. Please try again after logging out from other Google accounts and logging into the account jonhd... If the account jonhd... doesn't belong to you, please contact TEAMMATES support.`

### PR DESCRIPTION
**Pull request by tjtanjin**
Fixes #11157 

**Outline of Solution**

Update the error message to prompt user to login with the correct google account (level of details to be included may be further discussed).

The currently proposed error message is as below:
Screenshot 2021-07-12 at 12 19 38 AM

### CODE REVIEW

**Comment by damithc** [comment]
How about this as the error message?
`You are trying to access TEAMMATES using the Google account JohnDoe, which is not linked to any TEAMMATES account. If you used a different Google account to join/access TEAMMATES before, please use that Google account to access TEAMMATES. If you cannot remember which Google account you used before, please email us at {support email} for help.`

**Comment by tjtanjin** [comment]
> How about this as the error message?
> `You are trying to access TEAMMATES using the Google account JohnDoe, which is not linked to any TEAMMATES account. If you used a different Google account to join/access TEAMMATES before, please use that Google account to access TEAMMATES. If you cannot remember which Google account you used before, please email us at {support email} for help.`

This sounds much more useful, I have updated the error message to follow the above.

**Comment by tjtanjin** [comment]
Hi Prof @damithc, seeing as there are no immediate discussions related to this issue, would the current message changes suffice?

**Comment by damithc** [comment]
> Hi Prof @damithc, seeing as there are no immediate discussions related to this issue, would the current message changes suffice?

Yes @tjtanjin

**Comment by damithc** [comment]
@tjtanjin let us know when ready for review.

**Comment by tjtanjin** [comment]
@damithc Yes it is ready for review!

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 1]
```diff
@@ -173,7 +173,11 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
               if (this.loggedInUser) {
                 // Registration key belongs to another user who is not the logged in user
                 this.navigationService.navigateWithErrorMessage(this.router, '/web/front',
-                    'You are not authorized to view this page.');
+                    `You are trying to access TEAMMATES using the Google account ${this.loggedInUser}, which
+                    is not linked to any TEAMMATES account. If you used a different Google account to
```
Comment (wkurniawan07) [inline src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:177]: "not linked to any TEAMMATES account" is not accurate. What's happening here is the logged in user doesn't match the google ID of the student entity linked by the registration key, but the logged in user might actually be linked to some other valid students (but we don't need to find out about this).

@damithc fyi

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]
Also, I believe the message in the results page should be similarly changed.

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts (hunk 1 above)
Comment (damithc) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:177]: Good point @wkurniawan07  
Rephrase as `not linked to this TEAMMATES course`?

However, if it will not fit if the user is trying to just login to TEAMMATES (not access a specific course).

**Comment by wkurniawan07** [comment]
@tjtanjin you need to apply the same change to the results page as well

**Comment by tjtanjin** [comment]
> @tjtanjin you need to apply the same change to the results page as well

Hi! I've updated the results page as well, kindly advise if the changes are ok.

**Comment by daongochieu2810** [comment]
@tjtanjin the tests are failing, could you fix them and let us know once the PR is ready? thanks

**Comment by damithc** [comment]
Guys, This PR seems to be stalling (no activities for the past 8 days). :snail: :cry:
Hope someone can get it to move forward again soon...

**Comment by hhdqirui** [comment]
@tjtanjin kind reminder on this PR.

**Comment by tjtanjin** [comment]
> @tjtanjin kind reminder on this PR.

Hello! Sorry for the late reply - I am having trouble resolving the test issues primarily because of line 486 inside `session-result-page.component.spec.ts`:
```
expect(navSpy.calls.mostRecent().args[2]).toEqual('You are not authorized to view this page.');
```

The above line needs to be changed to match the new error message. However, as the new error message contains variables, I am not sure how to pass the check at this line. I also noticed that this same check was not performed for the modification of the message in `session-submission-page.component.ts` which would seem inconsistent. Would it be alright then to remove this particular line or should this check be included in `session-submission-page.component.spec.ts` for consistency?

Currently, I have tried printing to console when running tests to see if I could possibly get the exact error message expected. However, even using flags such as `--watch` and `--verbose` are not showing any useful information. An online search seems to suggest that debugging in jest is rather difficult so any advice for approaching this would be greatly appreciated.

Thank you in advance!

**Comment by t-cheepeng** [comment]
@tjtanjin 
You could fix the return values returned by the spy and then check for those messages. Otherwise, jest has a extend method that you can use to write custom matchers: https://jestjs.io/docs/expect#expectextendmatchers

> Would it be alright then to remove this particular line or should this check be included in session-submission-page.component.spec.ts for consistency?

If you can include, that would be great.

**Comment by wkurniawan07** [comment]
@tjtanjin if you haven't realized yet, the test code at its state right now doesn't even compile. And no, it's not the variable that's causing the test failure.

> An online search seems to suggest that debugging in jest is rather difficult so any advice for approaching this would be greatly appreciated.

I'm not sure where you found this, because Jest has actually been quite helpful so far.

**Comment by halfwhole** [comment]
@tjtanjin kind reminder on this PR!

**Comment by daongochieu2810** [comment]
@tjtanjin any update on this PR?

**Comment by ypinhsuan** [comment]
Closing this PR for now due to inactivity. @tjtanjin feel free to open it up if you want to continue working on it :)

**Comment by wkurniawan07** [comment]
@tjtanjin just curious, but are you keen to continue on this PR now that (I assume) you have some bandwidth?

**Comment by tjtanjin** [comment]
> @tjtanjin just curious, but are you keen to continue on this PR now that (I assume) you have some bandwidth?

Yes! I'll sort this PR out by the end of next week if that is permissible.

**Comment by tjtanjin** [comment]
This PR is ready for review! That said, I am not sure why indentations caused the test cases to fail since the expected string vs actual string should not be affected by code indentation.

**Comment by wkurniawan07** [comment]
> should not be affected by code indentation

Those are not just "indentation"s. It's easy to miss why, but it's not difficult to see why either.

**Review by wkurniawan07 — APPROVED** [review]
LGTM

**Review by jianhandev — APPROVED** [review]
