### PR TITLE
[#9434] Fixed brittle asserts for time zone offsets in GetTimeZonesDataActionTest

### LINKED ISSUE #9434: GetTimeZonesDataActionTest: fix brittle asserts for time zone offsets
The asserts that use New York and Sydney's time zones are brittle as these two time zones observe daylight savings, meaning the absolute offset from UTC is not consistent throughout the year.

https://github.com/TEAMMATES/teammates/blob/82f8d4299515ce20bbbdf07296519d5f60e12f92/src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java#L42-L49

Change these asserts to use time zones in the `Etc` group (e.g. `Etc/GMT-5`) instead as these offsets cannot change by definition.

New York's clocks will spring forward by one hour on 10 March 2019, while Sydney's clocks will spring backward by one hour on 7 April 2019. This test will begin failing then.

### PR DESCRIPTION
**Pull request by tong72**
Fixes #9434

### CODE REVIEW

**Comment by tong72** [comment]
ready for review. thank you.

File: src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java [hunk 1]
```diff
@@ -1,13 +1,16 @@
 package teammates.test.cases.webapi;
 
 import org.apache.http.HttpStatus;
+import org.joda.time.DateTimeZone;
+import org.joda.time.Instant;
```
Comment (darrenwee) [inline src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: We no longer use jodatime for our datetime-related logic. You need to use the `java.time` equivalents of these objects, e.g. `java.time.Instant`.

File: src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java [hunk 2]
```diff
@@ -1,13 +1,16 @@
...
 import org.testng.annotations.Test;
 
 import teammates.common.util.Const;
 import teammates.ui.webapi.action.GetTimeZonesAction;
 import teammates.ui.webapi.action.JsonResult;
 import teammates.ui.webapi.output.TimeZonesData;
 
+
```
Comment (darrenwee) [inline src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: Extra whitespace is unnecessary.

File: src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java [hunk 3]
```diff
@@ -43,10 +56,23 @@ protected void testExecute() throws Exception {
...
          */
+
         assertEquals(8 * 60 * 60, output.getOffsets().get("Asia/Singapore").intValue());
-        assertEquals(-5 * 60 * 60, output.getOffsets().get("America/New_York").intValue());
-        assertEquals(11 * 60 * 60, output.getOffsets().get("Australia/Sydney").intValue());
-        assertEquals(0, output.getOffsets().get("Europe/London").intValue());
+        if (daylightSavingNewYork) {
+            assertEquals(-4 * 60 * 60, output.getOffsets().get("America/New_York").intValue());
+        } else {
+            assertEquals(-5 * 60 * 60, output.getOffsets().get("America/New_York").intValue());
```
Comment (darrenwee) [inline src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: I understand what you're trying to do, but this is not the most elegant way to get around brittleness due to daylight savings. This will also cause problems in the future if `America/New_York` or any other time zone in this test decides to not observe daylight savings or change their time zone rules.

Instead, as I suggested in the issue, you can use a fixed offset time zone. For example:
```java
assertEquals(-5 * 60 * 60, output.getOffsets().get("Etc/GMT-5").intValue());
```

This can be guaranteed to never be brittle, because `Etc/GMT-5` is by definition five hours slower than GMT.

Please do this for the remaining test cases. We shouldn't rely on checking whether daylight savings is in effect, just use something that isn't affected by daylight savings instead.

Comment (tong72) [reply src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: Thanks for helping me out! I have a question in regards to your example:
`assertEquals(-5 * 60 * 60, `output.getOffsets().get("Etc/GMT-5").intValue());`
If I am not mistaken, I think the argument of the get function should be "Etc/GMT+5" since the tz database has the signs reversed. I just wanted to check with you to make sure if this is correct.

Comment (darrenwee) [reply src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: Yes, you are correct. My bad! Your current changes are correct.

For anyone following, this is the reason why. From inside the tzdb tables:
```
# We use POSIX-style signs in the Zone names and the output abbreviations,
# even though this is the opposite of what many people expect.
# POSIX has positive signs west of Greenwich, but many people expect
# positive signs east of Greenwich.  For example, TZ='Etc/GMT+4' uses
# the abbreviation "GMT+4" and corresponds to 4 hours behind UTC
# (i.e. west of Greenwich) even though many people would expect it to
# mean 4 hours ahead of UTC (i.e. east of Greenwich).
...
Zone	Etc/GMT-14	14	-	GMT-14	# 14 hours ahead of GMT
Zone	Etc/GMT-13	13	-	GMT-13
```

File: src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java [hunk 4]
```diff
@@ -42,10 +42,10 @@ protected void testExecute() throws Exception {
          * e.g. New York observes DST, so the offset is not always UTC-05:00 the entire year.
          * e.g. timezones can change, like Caracas modifying their timezone. This affects the offset as well.
          */
-        assertEquals(8 * 60 * 60, output.getOffsets().get("Asia/Singapore").intValue());
-        assertEquals(-5 * 60 * 60, output.getOffsets().get("America/New_York").intValue());
-        assertEquals(11 * 60 * 60, output.getOffsets().get("Australia/Sydney").intValue());
-        assertEquals(0, output.getOffsets().get("Europe/London").intValue());
+        assertEquals(8 * 60 * 60, output.getOffsets().get("Etc/GMT-8").intValue());
```
Comment (darrenwee) [inline src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: Could you add the following javadoc above the asserts to explain the funky zone IDs?

> There is a quirk in the ETC/GMT time zones due to the tzdb using POSIX-style signs in the zone names and the output abbreviations.
> POSIX has positive signs west of Greenwich, while we are used to positive signs east of Greenwich in practice.
> For example, TZ='Etc/GMT+8' uses the abbreviation "GMT+8" and corresponds to 8 hours behind UTC (i.e. west of Greenwich) even though many people would expect it to mean 8 hours ahead of UTC (i.e. east of Greenwich; like Singapore or China).
> (adapted from tzdb table comments)

Comment (tong72) [reply src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: Got it.

File: src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java [hunk 5]
```diff
@@ -38,14 +38,18 @@ protected void testExecute() throws Exception {
         // Only check that the version number is returned, and some sample values for timezone offset
         assertNotNull(output.getVersion());
 
-        /* TODO the asserts below are brittle as the expected values are not guaranteed to be correct
-         * e.g. New York observes DST, so the offset is not always UTC-05:00 the entire year.
-         * e.g. timezones can change, like Caracas modifying their timezone. This affects the offset as well.
+        /**
+         * There is a quirk in the ETC/GMT time zones due to the tzdb using POSIX-style signs in the zone names and the
+         * output abbreviations POSIX has positive signs west of Greenwich, while we are used to positive signs east of
```
Comment (darrenwee) [inline src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java]: `abbreviations.`

**Comment by damithc** [comment]
I'll leave this to @xpdavid for final approval.
