### PR TITLE
Some students cannot access profile pic #6067

### LINKED ISSUE #6067: Some students cannot access profile pic
Some students seem to encounter this error when they try to view team.

```
ervlet Action failure in page<br>class teammates.common.exception.UnauthorizedAccessException:  (ControllerServlet.java:91)
teammates.common.exception.UnauthorizedAccessException: User is not instructor of the course that student belongs to
    at teammates.logic.api.GateKeeper.verifyAccessibleForCurrentUserAsInstructor(GateKeeper.java:353)
    at teammates.ui.controller.StudentProfilePictureAction.handleRequestWithEmailAndCourse(StudentProfilePictureAction.java:51)
    at teammates.ui.controller.StudentProfilePictureAction.execute(StudentProfilePictureAction.java:31)
    at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
    at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
    at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:504)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by tarun14110**
Fixes #6067

### CODE REVIEW

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 1]
```diff
@@ -346,14 +346,17 @@ private boolean isStudent() {
...
-        } else if (!instructor.isAllowedForPrivilege(section,
-                                                     Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)) {
+        StudentAttributes student = StudentsLogic.inst().getStudentForCourseIdAndGoogleId(courseId, account.googleId);
+        if (instructor == null && student == null) {
+            throw new UnauthorizedAccessException("User is not in the course that student belongs to");
+        } else if (instructor != null && !instructor.isAllowedForPrivilege(section,
+                Const.ParamsNames.INSTRUCTOR_PERMISSION_VIEW_STUDENT_IN_SECTIONS)
+                || student != null && !StudentsLogic.inst().isStudentsInSameTeam(courseId, email, student.email)) {
             throw new UnauthorizedAccessException("User does not have enough privileges to view the photo");
+
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/api/GateKeeper.java]: Let's do it this way:
```java
if (instructor != null) {
    if (...) {
        throw new UnauthorizedAccessException(...);
    }
    return;
}

StudentAttributes student = ...;

if (student != null) {
    if (...) {
        throw new UnauthorizedAccessException(...);
    }
    return;
}

throw new UnauthorizedAccessException(...);
```
This way we can see the hierarchy more clearly, suppresses the need to query for extra student entity if the instructor entity is non-null, and also allows for different exception messages for instructor and student (they should not be the same).

**Comment by wkurniawan07** [comment]
Also, check for masquerading case. This can be done by adding `USER_ID` parameter on `String[] submissionParams`. Unless the user is admin, this should not be allowed.

**Comment by wkurniawan07** [comment]
Hi @tarun14110, any updates on this PR?

**Comment by tarun14110** [comment]
@wkurniawan07 I didn't get the masquerading one. Can an instructor do masquerade login as a student ? I thought instructor can only masquerade as a student for `preview feedback session`  and `view profile`only ?

**Comment by damithc** [comment]
No, instructors cannot masquerade but the admin can masquerade as an instructor/student.

**Comment by tarun14110** [comment]
@wkurniawan07  sorry, but what exactly to do for masquerading case in this PR? Can you please explain ?

**Comment by wkurniawan07** [comment]
@tarun14110 sorry for the delay, because this is one of the PRs that will take some time to review. I will now be continuing with the review.

**Comment by wkurniawan07** [comment]
@tarun14110 on the masquerading issue: by right the picture is accessible only to the instructors of the course and students in the same team. Check if (1) a student from another team, (2) a student from another course, (3) an instructor from another course, trying to masquerade as either one of the above are denied access to the profile picture, which should be the case.

**Comment by damithc** [comment]
@tarun14110 can we finish this one?

**Comment by tarun14110** [comment]
@wkurniawan07 please review.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java [hunk 2]
```diff
@@ -189,22 +190,85 @@ private void testActionForStudentWithEmptyGoogleId() {
...
         AccountAttributes unauthInstructor = dataBundle.accounts.get("instructor1OfCourse2");
         gaeSimulation.loginAsInstructor(unauthInstructor.googleId);
 
+        action = getAction(submissionParams);
+        try {
+            action.executeAndPostProcess();
+            signalFailureToDetectException("Unauthorised Access");
+        } catch (UnauthorizedAccessException uae) {
+            assertEquals("User is not in the course that student belongs to", uae.getMessage());
+        }
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: Is there an instructor from this course that has no "viewing student" privilege? If yes, you should test that as well, to account for the "Instructor does not have enough privileges to view the photo" case.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java [hunk 3]
```diff
@@ -189,22 +190,85 @@ private void testActionForStudentWithEmptyGoogleId() {
...
+        try {
+            action.executeAndPostProcess();
+            signalFailureToDetectException("Unauthorised Access");
+        } catch (UnauthorizedAccessException uae) {
+            assertEquals("Student does not have enough privileges to view the photo", uae.getMessage());
+        }
+    }
+    
+    protected void testActionWithEmailAndCourseUnauthorisedInstructorOrStudentMasquerade() {
+        gaeSimulation.loginAsAdmin("admin.user");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: I think you're getting it mixed up. The idea is not someone who _has_ access masquerading as someone who _does not have_ access (although it's good to test this too). The more important case for access control purpose is that someone who _does not have_ access masquerading as someone who _has_ access should still be denied. Quoting my previous comment:
> Check if (1) a student from another team, (2) a student from another course, (3) an instructor from another course, trying to masquerade as either one of the above [the instructors of the course and students in the same team] are denied access to the profile picture.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java [hunk 4]
```diff
@@ -233,5 +297,6 @@ private void verifyLogMessageForActionWithBlobKey(boolean isMasquerade) {
     private StudentProfilePictureAction getAction(String... params) {
         return (StudentProfilePictureAction) gaeSimulation.getActionObject(uri, params);
     }
-
 }
+
+
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: These whitespace changes should not occur?

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java (hunk 2 above)
Comment (tarun14110) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: No, all the instructors of the course have "viewing privilege".

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java (hunk 3 above)
Comment (tarun14110) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: sorry, I am confusing here. As only admin is allowed to masquerade, so instructors or students trying to masquerade are already tested in BaseActionTest ? Is it required to test it here again? I added some changes, please have a look.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java (hunk 2 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: In that case, is it too much work to modify one instructor and remove its "viewing student" privilege? I am not entirely sure on the details, but this should be doable via some BackDoor methods. Do not change the typical data bundle since it will have widespread effect.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java (hunk 4 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: This is not addressed.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java [hunk 5]
```diff
@@ -189,22 +190,104 @@ private void testActionForStudentWithEmptyGoogleId() {
...
-        action = getAction(submissionParams);
+        
+        ______TS("Failure case: unauthorised student masqueraded as a student from same team");
+        AccountAttributes unauthStudent = dataBundle.accounts.get("student1InArchivedCourse");
+        gaeSimulation.loginAsStudent(unauthStudent.googleId);
+        try {
+            action = getAction(addUserIdToParams(student.googleId, submissionParams));
+            signalFailureToDetectException();
+        } catch (UnauthorizedAccessException uae) {
+            ignoreExpectedException();
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: Is there an error message that can be used for assertion here? Similarly for the one after this.

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java [hunk 6]
```diff
@@ -189,22 +190,104 @@ private void testActionForStudentWithEmptyGoogleId() {
...
+        }
+        
+        ______TS("Failure case: unauthorised instructor masqueraded as a authorised instructor");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: ...masqueraded as a**n** authorised instructor

File: src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java (hunk 2 above)
Comment (tarun14110) [inline src/test/java/teammates/test/cases/ui/StudentProfilePictureActionTest.java]: @wkurniawan07 Sorry, I missed that. There was already an instructor with no "viewing student" privilege. I added test for that case.

**Comment by tarun14110** [comment]
@wkurniawan07 please review again.
