### PR TITLE
Rubric question add/edit action test: Add missing parameter and additional tests #8855

### LINKED ISSUE #8855: Rubric question add/edit action test: Add missing parameter and additional tests
- **Environment**: 
`master` branch

**Steps to reproduce**
In `InstructorFeedbackQuestionAddActionTest.testExecuteAndPostProcessRubricQuestion()` test, while passing the request parameters for `Typical case` test, the `rubricAssignWeights` parameter has not been assigned.

https://github.com/TEAMMATES/teammates/blob/ed1ea9c502db8a30e64d10f3b96e14c8428a124e/src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java#L650-L676

As a result, `hasAssignedWeights` in `FeedbackRubricQuestionDetails` remians false, leaving the weights in the request parameters useless as `getRubricWeights()` method returns an empty list in this case.

https://github.com/TEAMMATES/teammates/blob/ed1ea9c502db8a30e64d10f3b96e14c8428a124e/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L107-L114

Besides fixing this, I guess it will be better if we add additional tests here. 
We can divide the current test into two test 
- Typical case without weights attached
- Typical case with weights attached

We can add another test, where `numOfRubricChoices != numOfRubricWeights` to test this condition. Currently in the existing test, due to the missing parameter, if we remove one of the weights in the above request parameter, the test will still pass, where it should fail.

**Additionally:**
This is also repeated in `InstructorFeedbackQuestionEditActionTest` where the tests concerning rubric weights does not have `rubricAssignWeights` set as `on`, which means these tests are not testing anything.

To test this, change any of the following weight values to a non-numeric character, (e.g. `kk`), the test should fail as this can not be parsed as a valid double value, but the test passes. 

https://github.com/TEAMMATES/teammates/blob/ed1ea9c502db8a30e64d10f3b96e14c8428a124e/src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java#L1323-L1324

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8855

**Outline of Solution**

Added the following three tests in `InstructorFeedbackQuestionAddActionTest`:
- Typical case with weights attached
- Rubric choices without weights attached
- Number of weights is less than number of choices

Added `rubricAssignWeights` parameter in `InstructorFeedbackQuestionAddActionTest` for `Edit rubric weights` test.

Modified the `getRubricWeights()` method to handle the case where `weight == null`, weight can be `null` if the weight for the rubric choice is not assigned. In that case, here weight becomes null.

```java
             String weight = HttpRequestHelper.getValueFromParamMap(
                     requestParameters, Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHT + "-" + i);
```
And `NullPointerException` is thrown. This is not correct as, we do a validation for `numOfRubricChoices == rubricWeights.size()` in `validateQuestionDetails()` anyway, and the actual error that should be shown is an `AssertionError` but the code breaks before that.

### CODE REVIEW

**Comment by sukanta-27** [comment]
@bqnguyen94 @xpdavid Ready for review.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java [hunk 1]
```diff
@@ -697,6 +698,111 @@ public void testExecuteAndPostProcessRubricQuestion() {
...
+                // Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHT + "-0", "-1",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_SUBQUESTION + "-1", "SubQn-2",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_CHOICE + "-1", "Choice-2",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHT + "-1", "2",
+                Const.ParamsNames.FEEDBACK_QUESTION_NUMBEROFENTITIESTYPE, "max",
+                Const.ParamsNames.FEEDBACK_QUESTION_NUMBEROFENTITIES, "1",
+                Const.ParamsNames.FEEDBACK_QUESTION_SHOWRESPONSESTO, FeedbackParticipantType.INSTRUCTORS.toString(),
+                Const.ParamsNames.FEEDBACK_QUESTION_SHOWGIVERTO, FeedbackParticipantType.INSTRUCTORS.toString(),
+                Const.ParamsNames.FEEDBACK_QUESTION_SHOWRECIPIENTTO, FeedbackParticipantType.INSTRUCTORS.toString(),
+                Const.ParamsNames.FEEDBACK_QUESTION_EDITTYPE, "edit",
```
Comment (bqnguyen94) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: Can the repeated params be extracted? I think it would be easier to read and discern the test cases.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java [hunk 2]
```diff
@@ -1320,6 +1320,7 @@ public void testExecuteAndPostProcessRubricQuestion() {
                 Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_SUBQUESTION + "-1", "This student has tried his/her best.",
                 Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_CHOICE + "-0", "Yes",
                 Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_CHOICE + "-1", "No",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHTS_ASSIGNED, "on",
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: Take a look at other rubric test case. If `FEEDBACK_QUESTION_RUBRIC_WEIGHTS_ASSIGNED` is no there. There should be no `FEEDBACK_QUESTION_RUBRIC_WEIGHT` at all.

**Comment by sukanta-27** [comment]
Ready for review

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java [hunk 3]
```diff
@@ -1209,24 +1209,12 @@ public void testExecuteAndPostProcessRubricQuestion() {
                 Const.ParamsNames.FEEDBACK_QUESTION_NUMBER, Integer.toString(fq.questionNumber),
                 Const.ParamsNames.FEEDBACK_QUESTION_TYPE, "RUBRIC",
                 Const.ParamsNames.FEEDBACK_QUESTION_TEXT, fqd.getQuestionText() + "(edited)",
-                Const.ParamsNames.FEEDBACK_QUESTION_DESCRIPTION, "more details",
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: Why there are changes others beside `FEEDBACK_QUESTION_RUBRIC_WEIGHT`?

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: As @bqnguyen94 asked in https://github.com/TEAMMATES/teammates/pull/8856#discussion_r192153525 if repeated params can be extracted, I did that only. So that, it is a easier to read the test cases.

Comment (xpdavid) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: Where do you extract to?

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: Oops! I misinterpreted the comment!

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: @bqnguyen94 @xpdavid Do we need to extract the repeated params?
This is what I came up with:

```java
String[] requiredParams = { ....}; // The required fields that will be added in every test
String[] testRelatedParams = {......};

List<String> params = new ArrayList<>(Arrays.asList(requiredParams));
Collections.addAll(params, editTextParams);

InstructorFeedbackQuestionEditAction a = getAction(params.toArray(new String[params.size()]));
// Rest of the code
```
Is this worth the added advantage?

Comment (xpdavid) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: This works. I have no preference on whether you should do this in your PR or not.

Comment (bqnguyen94) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java]: Yes, I think if the extraction makes the code significantly cleaner then it's worthwhile, unless it takes considerable amount of work to do. The decision is yours 👍

**Comment by sukanta-27** [comment]
@xpdavid @bqnguyen94 Ready for review.

**Comment by sukanta-27** [comment]
@bqnguyen94 Done.

**Comment by sukanta-27** [comment]
@xpdavid Ready for review.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java [hunk 4]
```diff
@@ -697,6 +706,78 @@ public void testExecuteAndPostProcessRubricQuestion() {
                                     + "Please choose the most appropriate choices for the sub-questions below."
                                     + "|||/page/instructorFeedbackQuestionAdd";
         AssertHelper.assertLogMessageEquals(expectedLogMessage, action.getLogMessage());
+        // Clear requestedParams list
+        requestedParams.clear();
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: This line is redundant? There are multiple places of this redundancy in your PR.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java [hunk 5]
```diff
@@ -697,6 +706,78 @@ public void testExecuteAndPostProcessRubricQuestion() {
...
+
+        ______TS("Rubric choices without weights attached");
+
+        params = new String[] {
+                Const.ParamsNames.FEEDBACK_QUESTION_NUMBER, "2",
+        };
+
+        requestedParams = new ArrayList<>(Arrays.asList(requiredParams));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: As u have assigned a new object to it?

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java [hunk 6]
```diff
@@ -674,7 +669,21 @@ public void testExecuteAndPostProcessRubricQuestion() {
                 Const.ParamsNames.FEEDBACK_QUESTION_EDITTYPE, "edit",
         };
 
-        InstructorFeedbackQuestionAddAction action = getAction(params);
+        ______TS("Typical case with attached weights");
+
+        // tests when descriptions are missing as well.
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: What is the comment for?
If it doesn't fit here, we can delete it.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java [hunk 7]
```diff
@@ -674,7 +669,21 @@ public void testExecuteAndPostProcessRubricQuestion() {
...
+                Const.ParamsNames.FEEDBACK_QUESTION_NUMBER, "1",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHTS_ASSIGNED, "on",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHT + "-0", "-1",
+                Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_WEIGHT + "-1", "2",
+        };
+
+        List<String> requestedParams = new ArrayList<>(Arrays.asList(requiredParams));
+        Collections.addAll(requestedParams, params);
+
+        InstructorFeedbackQuestionAddAction action = getAction(requestedParams.toArray(new String[0]));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: Why not just `requestedParams.toArray()`? There are multiple places of this problem in your PR.

> Note that toArray(new Object[0]) is identical in function to toArray(). -- from java8 doc

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java (hunk 6 above)
Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: It was there before, so I didn't delete it. I guess, as the rubric question in the test has no description for the choices, this line has been added for that.

Okay, will delete it.

File: src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java (hunk 7 above)
Comment (sukanta-27) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: `.toArray()` returns an `object[]`, and `getAction` method takes `String...` as arguments. It throws an error if I just use `requestedParams.toArray()`

screenshot 497

Comment (xpdavid) [reply src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java]: I see

**Comment by sukanta-27** [comment]
@xpdavid Made the changes.
