### PR TITLE
AdminHomePageUiTest: fix failure against live server #5866

### LINKED ISSUE #5866: AdminHomePageUiTest: fix failure against live server
Happened during live server testing. Confirmed after multiple runs.

```
java.lang.AssertionError: expected:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=dsdsdsds127CAAD2437093B7618C9BBABC12BA67285F585424365A64D7988430BB14C548C6038E135B1734B0BCF7BD236D8F7D77464C5C3718E062531EA7FD&instructorinstitution=TEAMMATES+Test+Institute+1> but was:<Instructor AHPUiT Instrúctör has been successfully created with join link:
https://teammatesv4.appspot.com/page/instructorCourseJoin?key=fdfsdfdfsdfsd437093B7618C9BBABC12BA67285F585424365A64D79884BEBBF31301DA5DA6B0F4D5676C9875B059EACECD374619CCEDED2A50DC673D51&instructorinstitution=TEAMMATES+Test+Institute+1>
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
    at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
    at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:172)
    at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:102)
    at teammates.test.cases.ui.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #5866

**Outline of Solution**

Make `AdminHomePageUiTest` more tolerant to eventual consistency

- bc763fb: Reload and retry if newly updated feedback session is not reflecting changes yet
  - Fixes assertion error due to `updated instructions` not appearing
- bd23101: Wait and retry upon getting unexpected/empty results through various BackDoor get methods
  - Fixes `NullPointerException`
  - Fixes assertion error due to `BACKDOOR_STATUS_FAILURE` in join link
- 52f365c: Handle case when confirmation page redirects to entity not found page (can be safely ignored as it is temporary and subsequent checks do the waiting)
  - Fixes `InvocationTargetException` due to unexpected page content

**Other changes**
- Implement `RetryManager` framework to avoid repeating retry code
- Extract direct calls to `BackDoor.get*` from `AdminHomePageUiTest` into `BaseTestCaseWithBackDoorApiAccess` (related to changes made via bd23101 in keeping with e587b4300bf06afe8c4eb322381f3eb29636683c)

### CODE REVIEW

**Comment by damithc** [comment]
Now failing at
```
java.lang.AssertionError:  <Click to see difference>


	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:85)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:53)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:845)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:898)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:231)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

teammates.test.cases.browsertests.AdminHomePageUiTest completed
```
image

**Comment by damithc** [comment]
Also see if it's possible to break the test into multiple tests. Rerunning the whole test takes quite long.

**Comment by whipermr5** [comment]
> Now failing at
> 
> java.lang.AssertionError:  <Click to see difference>

The expected HTML seems to be an outdated version of `newlyJoinedInstructorFeedbackResultsPage.html` - it was updated in 8d2307d1c422d20b30485b194cf00b0109f3cc55.

**Comment by damithc** [comment]
> The expected HTML seems to be an outdated version of newlyJoinedInstructorFeedbackResultsPage.html

Ah ok, that commit is not deployed yet. I'll have to test it at v5.103

**Comment by whipermr5** [comment]
> Also see if it's possible to break the test into multiple tests.

Can this be in a separate issue/PR?

**Comment by damithc** [comment]
> Can this be in a separate issue/PR?

Sure

**Comment by xpdavid** [comment]
@whipermr5 I am OK with the code, but I am thinking if we can make the case more general. As far as I know, the issue I used to work on (#6382) also have datastore persistence issue (and I use a trick to get rid of it). I propose a new solution here and let's discuss if we can do this. I haven't tried out this by myself, but it seems doable.

Every time when we want to retry something, we call `RetryManager`.
``` java
RetryManager.run(new Retry {
  @Overribe
  public void try() {
    page.refresh();
    assertTrue(expected, getCourse("sampleCourse"));
    verifyHTML();
  }
});
```
``` java
public class RetryManager {
  public static run(Retry retry) {
    for(int i = 0; i < DEFAULT_RETRY_COUNT; i++) {
      Thread.wait(DEFAULT_RETURY_DELAY);
      retry.run();
    }
  }
}
```
``` java
Interface Retry { // similar to Runnable interface, but that is for thread.
  public void try();
}
```
If we do this, we can put multiple verifications or necessary actions along with the assertions (e.g you may first want to refresh the page before doing html verification). Also, we could get rid of duplicating method and naming it as `get*WithRetry `

**Comment by whipermr5** [comment]
@xpdavid Thank you; that's a really great suggestion!! I was cringing when I had to duplicate code for the `get*WithRetry` methods. However I think I'll tackle it in a separate PR, as this PR is primarily about fixing the failing test.

File: src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java [hunk 1]
```diff
@@ -10,26 +10,50 @@
...
+import teammates.common.util.Const;
+import teammates.common.util.ThreadHelper;
 import teammates.test.driver.BackDoor;
 
 /**
  * Base class for all test cases which are allowed to access the Datastore via {@link BackDoor}.
  */
 public abstract class BaseTestCaseWithBackDoorApiAccess extends BaseTestCaseWithDatastoreAccess {
 
+    private static final int BACKDOOR_GET_RETRY_COUNT = 100;
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: `retry_count` too high? I was thinking just 3-5 times. :P

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 2]
```diff
@@ -167,10 +167,17 @@ private void testCreateInstructorAction() throws Exception {
         confirmationPage = AppPage.createCorrectLoginPageType(browser)
                            .loginAsJoiningInstructor(TestProperties.TEST_INSTRUCTOR_ACCOUNT,
                                                      TestProperties.TEST_INSTRUCTOR_PASSWORD);
-        confirmationPage.clickConfirmButton();
+        try {
+            confirmationPage.clickConfirmButton();
+        } catch (Exception e) {
+            if (!confirmationPage.getPageSource().contains("TEAMMATES could not locate what you were trying to access.")) {
```
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Is this string literal defined somewhere in the code base? It's better to refer to that to reduce the brittleness of this code.

Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Also, may be extract as `confirmationPage.isEntityNotFoundErrorPage()` ?

File: src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java (hunk 1 above)
Comment (whipermr5) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: I can get up to 20 retries while testing on my staging server haha. I think the live server would suffer even more.

**Comment by whipermr5** [comment]
@damithc Ready for review :)

**Comment by whipermr5** [comment]
@xpdavid I decided to.tackle `RetryManager` after all. Ready for your review :)

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 3]
```diff
@@ -86,12 +86,12 @@ private void testCreateInstructorAction() throws Exception {
         BackDoor.deleteCourse(demoCourseId);
         BackDoor.deleteInstructor(demoCourseId, instructor.email);
         homePage.createInstructorByInstructorDetailsSingleLineForm(instructorDetails);
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: I think there is some misunderstanding here.
My idea is to include the verification inside the retry method rather then retrying to get data.
For example, here we could write.
``` java
// comment here e.g. Instructor entity need time to be updated in GAE
RetryManager.run(new Retry {
  @Overribe
  public void try() {
    homePage.refresh();
    InstructorAttributes instructorInBackend = BackDoor.getInstructorByEmail(instructor.email, demoCourseId);
    assertEquals(String.format(Const.StatusMessages.INSTRUCTOR_DETAILS_LENGTH_INVALID,
                                     Const.LENGTH_FOR_NAME_EMAIL_INSTITUTION),
                       homePage.getMessageFromResultTable(1));
  }
});
```
Then, the interval could be 2-3 seconds, and the maxium attemp could be 4-5 times.

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: How does the manager know whether the try succeeded?

Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: It doesn't need to know. If the test cases still fail, it means either your are unlucky or there are errors.

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Also, usually the retry is different from the first try (e.g. I only want the page to refresh if the first try fails).

Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: You don't mind to refresh again right? Just kidding. That the point I want to find out. Is it possible to do this? Also, if we successfully break down the test cases, we could write our own `TestRunner` to retry the specific test cases. (similar to what the gradle script does currently)

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: How does the manager know whether to run the try again? It should only run it again if it failed.

Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: More on the retry things : http://stackoverflow.com/questions/8295100/how-to-re-run-failed-junit-tests-immediately

Can catch the AssertionError throw by Junit ?

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: If the retry manager just blindly runs tries whether they succeed or fail, then it's only a glorified for loop, right? I don't quite understand the `TestRunner` 😅

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Sorry just saw your reply! My current implementation of `RetryManager` is something like the `TestRule` example given haha; take a look :)

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: The thing is, the retries we're doing are too small (just a few statements, like a page refresh) and heavily dependent on the current state; it's not ideal to extract them into small tests of their own just to retry them.

Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Ok. I am not sure whether this is the best solution (and best design). (You can create your own AppVeyor instance and try run the test case, the retry time for `AdminHomePageUiTest` should not exist in gradle script).

So we still don't get rid of renaming methods (`getInstructor` -> `getInstructorWithRetry` etc). @wkurniawan07 Your inputs here ?

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: The calls to `RetryManager` can always be written in the test itself; just that I felt these few methods should be extracted into `BaseTestCaseWithBackDoorApiAccess` as they can be reused.

As for having to create multiple `*WithRetry` variants for methods, I feel that it's fine, as code reuse is already quite substantial. Have a look at this example:

```
InstructorAttributes instructor = RetryManager.runWithRetry(
new RetryableTaskWithResult<InstructorAttributes>("getInstructor") {
    @Override
    public boolean run() {
        setResult(getInstructor(courseId, instructorEmail));
        return getResult() != null;
    }
});
```

This anonymous class, in just a few lines, contains code specifying how to

1. Run the task
1. Check whether the task succeeded
1. Return the result

These 3 things are unique to the task being retried, and have to be specified for every single task. The success condition for `getInstructor` is that the return value is not null, whereas that for `getKeyForInstructor` is that the returned string starts with `[BACKDOOR_STATUS_FAILURE]` - one cannot write a general method that works for both `getInstructor` and `getKeyForInstructor` without specifying the success condition for each.

Having said that, I realise we can make retry declarations even cleaner and more readable by building in a library of common success conditions (not null, true, no assertion errors caught etc.), and by setting the result through the return value of the run code (instead of calling setResult). The same task above can possibly be written like this:

```
InstructorAttributes instructor = RetryManager.runUntilNotNull(
new RetryableTaskWithResult<InstructorAttributes>("getInstructor") {
    @Override
    public InstructorAttributes run() {
        return getInstructor(courseId, instructorEmail);
    }
});
```

More complex conditions can continue to be specified within the code, like this:

```
String key = RetryManager.runUntilSuccessful(
new RetryableTaskWithResult<String>("getKeyForInstructor") {
    @Override
    public String run() {
        return getKeyForInstructor(courseId, instructorEmail);
    }
    @Override
    public boolean isSuccessful(String result) {
        return !result.startsWith(Const.StatusCodes.BACKDOOR_STATUS_FAILURE);
    }
});
```

For tasks without a result, it could look like this:

```
RetryManager.runUntilNoException(
new RetryableTaskThrows<AssertionError>("HTML verification") {
    @Override
    public void run() throws AssertionError {
        verifyHtmlPart(MAIN_CONTENT, filePath);
    }
});
```

Let me know what you think of this idea! :)

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: I've implemented the new `RetryManager` :)

File: src/test/java/teammates/test/driver/Retryable.java [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+     * Runs the task once and returns the result.
+     */
+    // CHECKSTYLE.OFF:MethodName internal variable underscore naming convention applied to abstract methods
+    protected abstract T run_() throws E;
+
+    /**
+     * Checks whether the task succeeded.
+     */
+    protected abstract boolean isSuccessful_() throws E;
+    // CHECKSTYLE.OFF:MethodName
```
Comment (damithc) [inline src/test/java/teammates/test/driver/Retryable.java]: Do we use this convention of trailing underscore anywhere else in the code?

Comment (whipermr5) [inline src/test/java/teammates/test/driver/Retryable.java]: Looks like we don't - at first I was under the impression that it's used in private variables as this convention is mentioned in our [Java style guide](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html), but after trying, even private variables named with a trailing underscore fail checkstyle. I guess it's not acceptable then?

Comment (damithc) [inline src/test/java/teammates/test/driver/Retryable.java]: I'd rather avoid it if possible. It's an old convention that doesn't seem to be used these days among Java users.  :-p

File: src/test/java/teammates/test/driver/RetryManager.java [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+            ThreadHelper.waitFor(delay * 1000);
+            task.beforeRetry();
+        }
+        return task.runExec();
+    }
+
+    private static <T, E extends Throwable> boolean isSuccessful(Retryable<T, E> task, SuccessCondition condition)
+            throws E {
+        if (condition.equals(SuccessCondition.NOT_NULL)) {
+            return task != null;
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/RetryManager.java]: Why `task` can be `null`?
I thought `NOT_NULL` means the returns value is not null.

Comment (whipermr5) [inline src/test/java/teammates/test/driver/RetryManager.java]: Oops!! 😅😅 Good catch!

**Comment by whipermr5** [comment]
@xpdavid Thanks! Ready for review :)

**Comment by xpdavid** [comment]
Will review now.

File: src/test/java/teammates/test/driver/RetryManager.java [hunk 6]
```diff
@@ -0,0 +1,100 @@
+package teammates.test.driver;
+
+import teammates.common.util.Assumption;
+import teammates.common.util.ThreadHelper;
+
+/**
+ * Handles running and retrying of {@code Retryable} tasks.
+ */
+public final class RetryManager {
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/RetryManager.java]: Can we put RetryManager and its class to a new package? (To make it well-organized, also we could enforce architectural rule here)

File: src/test/java/teammates/test/driver/RetryManager.java [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+            logFailure(task, delay);
+            ThreadHelper.waitFor(delay * 1000);
+            task.beforeRetry();
+        }
+        return task.runExec();
+    }
+
+    private static <T, E extends Throwable> boolean isSuccessful(Retryable<T, E> task, SuccessCondition condition)
+            throws E {
+        if (condition.equals(SuccessCondition.NOT_NULL)) {
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/RetryManager.java]: Can we put the logic into the enum class? So we can practice OCP here.

File: src/test/java/teammates/test/driver/Retryable.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
+package teammates.test.driver;
+
+/**
+ * Represents a task that can be retried.
+ * @param <T> Result type.
+ * @param <E> Throwable type.
+ */
+public abstract class Retryable<T, E extends Throwable> {
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/Retryable.java]: Can we update the class diagram of `Retryable`, `RetryableTask ` etc some where?

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 9]
```diff
@@ -903,6 +918,20 @@ public AppPage verifyHtmlMainContent(String filePath) throws IOException {
         return verifyHtmlPart(MAIN_CONTENT, filePath);
     }
 
+    public AppPage verifyHtmlMainContentWithReloadRetry(final String filePath) throws IOException {
+        return RetryManager.runUntilNoException(new RetryableTaskReturnsThrows<AppPage, IOException>("HTML verification") {
+            @Override
+            public AppPage run() throws IOException {
```
Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: The `Assertion` exception is more appropriate here. You can catch the IOException inside the method and rethrow assertion error.

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I think it's not supposed to retry if it encounters IOException?

Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: What I means is the generic parameter should correspond to the exception that is going to be thrown. This makes more sense. But what if there are multiples exceptions that are going to be thrown?

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: The task is supposed to halt immediately and throw the exception upwards (this is the original behaviour). IOException will only happen if the wrong filename was specified (or other such errors out of our control), so no point retrying. The purpose of the Throws parameter is to indicate what kind of exception should immediately halt the task and be thrown upwards.

Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Okie, a bit weird.

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I think the weirdness is because the `AssertionError` is written at the end (second parameter of the `runUntilNoException` method), and isn't very visible. It'd look less weird if the user saves the task into a variable `task`; the call would then look like `RetryManager.runUntilNoException(task, AssertionError)`.

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Especially for multiple exception types that the user wants to catch, the only way to pass would be through the (normal non-generic) parameter. A method `runUntilNoExceptions(task, listOfExceptions)` can be implemented.

File: src/test/java/teammates/test/driver/RetryManager.java (hunk 7 above)
Comment (whipermr5) [inline src/test/java/teammates/test/driver/RetryManager.java]: Cool! I didn't know enums can contain logic before today.

File: src/test/java/teammates/test/driver/Retryable.java (hunk 8 above)
Comment (whipermr5) [inline src/test/java/teammates/test/driver/Retryable.java]: Can this be done in another issue/PR 😅

File: src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java [hunk 10]
```diff
@@ -228,14 +228,13 @@ private void testCreateInstructorAction() throws Exception {
 
         feedbackEditPage.clickEditSessionButton();
 
-        FeedbackSessionAttributes feedbackSession = BackDoor.getFeedbackSession(demoCourseId,
-                                                                                "Second team feedback session");
+        FeedbackSessionAttributes feedbackSession = getFeedbackSession(demoCourseId, "Second team feedback session");
         feedbackEditPage.editFeedbackSession(feedbackSession.getStartTime(),
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: According to the CI, this test still needs around 2-3 rounds to pass. There error is here.
``` shell
ci-tests > sequential-ui-tests > teammates.test.cases.browsertests.AdminHomePageUiTest.testAll FAILED
    java.lang.NullPointerException at AdminHomePageUiTest.java:232 
```
Can you examine what is happening?

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Thanks for the catch! Will investigate

Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java]: Should be fixed now! Ready for review :)

File: src/test/java/teammates/test/driver/retry/RetryManager.java [hunk 11]
```diff
@@ -0,0 +1,110 @@
...
+        return doRetry(task, SuccessCondition.NOT_NULL);
+    }
+
+    /**
+     * Runs {@code task}, retrying if needed using exponential backoff, until no exceptions of class
+     * {@code exceptionType} are caught.
+     * Returns {@code task} result or null if none.
+     */
+    public static <T, E extends Throwable, C extends Throwable> T runUntilNoException(
+            Retryable<T, E> task, Class<C> exceptionType) throws E {
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/retry/RetryManager.java]: Use varargs here?

File: src/test/java/teammates/test/driver/retry/RetryManager.java [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+    private static <T, E extends Throwable> T doRetry(Retryable<T, E> task, SuccessCondition condition)
+            throws E {
+        T result = task.runExec();
+        for (int delay = 1; !condition.isSuccessful(task) && delay <= MAX_DELAY_IN_S; delay *= 2) {
+            logFailure(task, delay);
+            ThreadHelper.waitFor(delay * 1000);
+            task.beforeRetry();
+            result = task.runExec();
+        }
+        return result;
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/retry/RetryManager.java]: Why not just do assertion fail if it has reached the maximum delay? We shall not do this silently, right?

File: src/test/java/teammates/test/driver/retry/RetryManager.java [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+                if (!exceptionType.isInstance(e)) {
+                    throw e;
+                }
+                // continue retry process
+            }
+            logFailure(task, delay);
+            ThreadHelper.waitFor(delay * 1000);
+            task.beforeRetry();
+        }
+        return task.runExec();
```
Comment (xpdavid) [inline src/test/java/teammates/test/driver/retry/RetryManager.java]: Same here.

File: src/test/java/teammates/test/driver/retry/RetryManager.java (hunk 12 above)
Comment (whipermr5) [inline src/test/java/teammates/test/driver/retry/RetryManager.java]: We want to do one last retry after waiting for the maximum delay (total time is still less than the maximum period allowed, as maximum delay is maximum period / 2). However I do get your point that after waiting for the maximum delay and trying one last time, we should not just blindly return the result, but check whether the final retry was successful.

File: src/test/java/teammates/test/driver/retry/RetryManager.java (hunk 13 above)
Comment (whipermr5) [inline src/test/java/teammates/test/driver/retry/RetryManager.java]: For this one, the last retry will throw an exception if it is not successful, as the final `task.runExec()` is no longer in a try block. If it fails, it will not do so silently.

**Comment by whipermr5** [comment]
@xpdavid Ready for review! No worries at all. Thank you for keeping the standards of TEAMMATES up through giving high quality reviews even though you're not doing this full time! Really appreciate it 👍👍

File: src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java [hunk 14]
```diff
@@ -10,26 +10,55 @@
...
 import teammates.test.driver.BackDoor;
+import teammates.test.driver.retry.RetryManager;
+import teammates.test.driver.retry.RetryableTaskReturns;
 
 /**
  * Base class for all test cases which are allowed to access the Datastore via {@link BackDoor}.
  */
 public abstract class BaseTestCaseWithBackDoorApiAccess extends BaseTestCaseWithDatastoreAccess {
 
+    protected AccountAttributes getAccount(String googleId) {
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: I was thinking to push the trying logic to the abstract class `BaseTestCaseWithDatastoreAccess`. `BaseTestCaseWithDatastoreAccess` is functioned like an interface (It doesn't care whether you use `BackDoor` http request with a secret key or `BackDoor` logic to access datastore directly). I think there is also need for component tests to have retry (I think it is already there, in `BaseTestCaseWithDatastoreAccess#verifyPresentInDatastore()`).

BTW, is it necessary to write a new method `protected AccountAttributes getAccount(String googleId)`?

**Comment by whipermr5** [comment]
> BTW, is it necessary to write a new method protected AccountAttributes getAccount(String googleId)?

In the tests, we hardly deal with full Attributes objects - most of the time, we deal with fields. I find it pretty counter-intuitive to have to construct an entire Attributes object just to use the various methods. To use a method that takes in an Attributes object, I'd need to open the method code to determine which fields of the object it is using, then construct an Attributes object with those fields populated just to pass the data over, only for the method to deconstruct the object again to get the correct fields.

File: src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java (hunk 14 above)
Comment (whipermr5) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: > BTW, is it necessary to write a new method protected AccountAttributes getAccount(String googleId)?

In the tests, we hardly deal with full Attributes objects - most of the time, we deal with fields. I find it pretty counter-intuitive to have to construct an entire Attributes object just to use the various methods. To use a method that takes in an Attributes object, I'd need to open the method code to determine which fields of the object it is using, then construct an Attributes object with those fields populated just to pass the data over, only for the method to deconstruct the object again to get the correct fields.

There is no easy way to create an AccountAttributes object when only the account Google ID is known, as there is no AccountAttributes constructor which takes in just a Google ID.

Comment (whipermr5) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: I feel that the existing abstract methods aren't very useable as they overgeneralise, and do not tell me which fields and which corresponding BackDoor (or BackDoorLogic) method they are using. Some of the entity types have multiple ways of lookup. For example, `getInstructor(InstructorAttributes instructor)` might use `BackDoor.getInstructorByEmail(instructor.email, instructor.courseId)` or `BackDoor.getInstructorByGoogleId(instructor.googleId, instructor.courseId)`.

Instead, I feel that `BaseTestCaseWithBackDoorApiAccess` should mirror the backdoor methods. The specific tests utilising these methods will know which lookup method they need, and call the correct one with the correct fields.

Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: I see. Yes, the design of abstract class `BaseTestCaseWithDatastoreAccess.java` may not be that good. It require us to pass an object (a bit weird) to retrieve data. (e.g. `protected abstract AccountAttributes getAccount(AccountAttributes account);`) All the implementation actually only make use of some fields (in this case, only `googleId` is used).

Comment (whipermr5) [inline src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java]: I guess I'll leave those methods there first, then refactor in another issue and PR?
