### PR TITLE
[#10804] [Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items 

### LINKED ISSUE #10804: [Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items
[Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items

LIVE TEAMMATES V7.3.1

Steps to reproduce:
1. Go to this page - https://teammatesv4.appspot.com/web/front/help/instructor
2. Enter "course" in the search field
3. Click on the enter button once
4. First time you will see - 31 results found
5. Now click on the enter button again
6. Search results will be now 0 results found

Expected results:
The search results must same

Actual results:
The search results vary when clicking on the enter button twice

### PR DESCRIPTION
**Pull request by sjkadali**
Fixes #10804 

**Outline of Solution**
In the search function, this.matchFound was set to 0. on removing that line of code, it shows the correct count now.

### CODE REVIEW

**Review by rrtheonlyone — CHANGES_REQUESTED** [review]
Yes, almost there. 

Unfortunately your current change opens another issue:
1. search for "course"
2. you will see 31 found
3. now search for "course1" and hit enter
4. it will still say 31 found (when in fact there is 0)

This is an easy fix though!

**Comment by sjkadali** [comment]
@rrtheonlyone  have made the requested changes. Please review. Thanks!

File: src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts [hunk 1]
```diff
@@ -78,8 +78,10 @@ export class InstructorHelpPageComponent implements OnInit, AfterViewInit {
    * Filters the help contents and displays only those that matches the filter.
    */
   search(): void {
-    this.matchFound = 0;
     if (this.searchTerm !== '') {
```
Comment (rrtheonlyone) [inline src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts:81]: Let's try to reduce the indentation from the if statements:
```
    if (this.searchTerm === '') {
      this.clear();
      return;
    }

    const nxtKey = this.searchTerm.toLowerCase();
    if (nxtKey !== this.key) {
      this.matchFound = 0;
    }

    this.key = nxtKey;
```

**Review by rrtheonlyone — CHANGES_REQUESTED** [review]
Looks good! I have a very suggestion on code - good to go once you fix that.

File: src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts (hunk 1 above)
Comment (sjkadali) [reply src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts]: @rrtheonlyone have made the requested changes. Please review. Thanks!

**Review by rrtheonlyone — APPROVED** [review]
LGTM 👍
