### PR TITLE
[#10322] Rich text editor breaks when moved during reorder 

### LINKED ISSUE #10322: Rich text editor breaks when moved during reorder
- **Environment**: `master` branch at commit dd9977ec150a49c93040004c4eb034a43fe0180a

**Steps to reproduce**
1) Have two questions in feedback sessions edit page.
2) Reorder question with description (Only happens when the description is reordered to a earlier position)
3) Try to edit again and type something in the description section.

**Expected behaviour**
1) Description should be displayed
2) Should be able to type and edit the description

**Actual behaviour**
After reorder, all content in the rich text editor disappears and it cannot be clicked.

**Additional info**
Before reorder:
Description-before

After reorder:
Description-after

### PR DESCRIPTION
**Pull request by jtankw3**
Fixes #10322

This issue is talked about here: https://stackoverflow.com/questions/2535569/tinymce-editor-dislikes-being-moved-around
I believe the only solution is to remove the TinyMCE before moving the elements and adding it back after.

However, I do not think it is possible to have a listener for the editor is called during when the editor is moved. 
It is also difficult for `instructor-session-edit-page.component` to interact with the  editor directly.

Hence, I believe the best solution is to reload all the questions,  thus reloading the editor as well.

**Outline of Solution**
- Change from moving `questionForms` to reloading on reorder

### CODE REVIEW

**Comment by ccyccyccy** [comment]
LGTM. I don't see a cleaner way.

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts [hunk 1]
```diff
@@ -538,24 +538,21 @@ export class InstructorSessionEditPageComponent extends InstructorSessionBasePag
...
+            this.reloadQuestionForms();
           }
 
           this.statusMessageService.showSuccessToast('The changes to the question have been updated.');
         }, (resp: ErrorMessageOutput) => { this.statusMessageService.showErrorToast(resp.error.message); });
   }
 
   /**
-   * Moves question edit form from the original position to the new position.
+   * Reloads feedback questions.
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:551]: I think we need to explain the workaround a bit as this violate our design in frontend where we want to minimize the unnecessary communication.

**Comment by wkurniawan07** [comment]
@jtankw3 good job for noticing this behaviour. However, there is a better solution:
- Add `ChangeDetectorRef` to the session edit page's component
- After re-ordering, the question at the new position needs to have `isCollapsed = true`. This will, on paper, destroy the edit components including the rich text editor.
- Trigger the `ChangeDetectorRef` manually (using `detectChanges`) so that the previously mentioned action will take place
- Change back the `isCollapsed = false`

**Comment by jtankw3** [comment]
> @jtankw3 good job for noticing this behaviour. However, there is a better solution:
> 
> * Add `ChangeDetectorRef` to the session edit page's component
> * After re-ordering, the question at the new position needs to have `isCollapsed = true`. This will, on paper, destroy the edit components including the rich text editor.
> * Trigger the `ChangeDetectorRef` manually (using `detectChanges`) so that the previously mentioned action will take place
> * Change back the `isCollapsed = false`

Thank you for the direction for solving this problem.
- I realized that if a question is moved down the form, all the question forms that are pushed up will also be affected by this problem. Hence I have implemented the above for all question models that are shifted up after any reorder.
- I also added a check to prevent originally collapsed questions from being expanded.

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts [hunk 2]
```diff
@@ -556,6 +557,15 @@ export class InstructorSessionEditPageComponent extends InstructorSessionBasePag
...
         this.questionEditFormModels.splice(originalPosition, 1)[0]);
+
+    // all expanded questions that were moved upwards must be re-expanded to reload rich text editor
+    const start: number = Math.min(originalPosition, newPosition);
+    const movedExpandedQuestions: QuestionEditFormModel[] = this.questionEditFormModels
+      .slice(start, newPosition + 1)
+      .filter((model: QuestionEditFormModel) => !model.isCollapsed);
+    movedExpandedQuestions.forEach((model: QuestionEditFormModel) => model.isCollapsed = true);
+    this.changeDetectorRef.detectChanges();
+    movedExpandedQuestions.forEach((model: QuestionEditFormModel) => model.isCollapsed = false);
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:568]: This will make all modals previously collapsed to be expanded. Only those which are previously expanded should be re-expanded.

Comment (jtankw3) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:568]: @wkurniawan07  I have filtered to only those that are not collapsed so those that are originally collapsed will not be affected. (line 565)

Comment (wkurniawan07) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:568]: Ah right, I missed that.
