### PR TITLE
[#9119] FeedbackResponseCommentsLogicTest: Fix verification for test

### LINKED ISSUE #9119: FeedbackResponseCommentsLogicTest: Fix verification for test
https://github.com/TEAMMATES/teammates/blob/51e4279ad8e098ed25d01b5a332a7d5b514d858a/src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java#L71-L96

The test uses a existing comment in DB and create a new duplicate comment with the same `commentText` in the DB. It then tries to verify whether the creation is successful or not. However, the verification will always pass as there is a existing comment (the comment which the test is copied) in DB (we check existence of comment by using `commentText`. (In test case, we make sure the `commentText` is unique)).

### PR DESCRIPTION
**Pull request by rrtheonlyone**
Fixes #9119

The initial testing code did not verify the case where a duplicate comment is added.

When a duplicate comment is added,  the expected behaviour is:
1. Check database and retrieve the ID of the existing comment
2. Set ID of the existing comment to the duplicate comment
3. Update this comment if needed

As such, in the test, I do a verification of whether the ID has been set correctly. I also change the `commentText` and check if the update works.

### CODE REVIEW

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java [hunk 1]
```diff
@@ -85,19 +85,22 @@ public void testCreateFeedbackResponseComment() throws Exception {
         verifyPresentInDatastore(frComment);
 
         ______TS("typical successful case: frComment already exists");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: Describe the behaviour when frComment already exists.

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java [hunk 2]
```diff
@@ -85,19 +85,22 @@ public void testCreateFeedbackResponseComment() throws Exception {
...
+
+        FeedbackResponseCommentAttributes actualComment =
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: I believe you are trying to verify that the comment exist in the database before the test.

```java
assertNotNull(frcLogic.getFeedbackResponseComment(frComment.getId()))
```

The above can already do the job?

Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: No, this is to fetch the existing comment from the database. I use this to verify that the duplicate comment has the same ID as the existing one.

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java (hunk 1 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: okay will do

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java (hunk 2 above)
Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: Then put it together with L97.

Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: L97? That would defeat the purpose, since after this I create a duplicate feedback response comment in the database. The variable `frcomment` will then be assigned the id. 

If I fetch `frcomment` from the database following that, it would always pass. I need to be able to fetch the original comment and verify that its ID is the same as the one given to `frcomment`

Unless, there is a better way to do this.

Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: > since after this I create a duplicate feedback response comment in the database.

Wait, we are not creating duplicate feedback response right? If the id is the same, the creation will be come update.

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java [hunk 3]
```diff
@@ -85,19 +85,22 @@ public void testCreateFeedbackResponseComment() throws Exception {
...
-                frcLogic.getFeedbackResponseCommentForSession(frComment.courseId, frComment.feedbackSessionName);
 
-        FeedbackResponseCommentAttributes actualFrComment = null;
-        for (FeedbackResponseCommentAttributes comment : actualFrComments) {
-            if (comment.commentText.equals(frComment.commentText)) {
-                actualFrComment = comment;
-                break;
-            }
-        }
+        // check that it uses existing ID from database
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: okay will update the comment 👍

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java (hunk 2 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: Updated the documentation! Do see if its more clear now

File: src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (xpdavid) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: BTW, will the test fail if you remove the .setId() in `createFeedbackResponseComment` (i.e. make sure `frComment` has empty id before the test).

[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java]: Yup it will fail: the `.getId()` method will return `null` and an exception will be thrown. 

This is the current behaviour of the test even before the PR. The `deleteFeedbackResponseCommentById` method in the cleanup portion relies on the ID being set.
