### PR TITLE
[#9474] Change Email Validation to Enforce TLD

### LINKED ISSUE #9474: No proper checks on email while adding an instructor to a course
**Email address added is not being checked on front-end while adding an instructor to a course**

 **Environment**: 
commit sha: 9e3b496dec9462f498d38159860a51ed602cf9e6
OS: Ubuntu 18.04 lts

**Steps to reproduce** 

1. Login and add any course
2. Add instructor by providing the name, email and university.

**Expected behaviour**
Email validation should be done on front-end. If I provide a broken email like test@example, A promt message should be shown to correct my details on front-end

**Actual behaviour**
The email has been saved for further actions.
screenshot from 2019-02-20 14-20-18

**Additional info**

I am not sure if this the decided workflow but it might lead to some extra work by the server.

### PR DESCRIPTION
**Pull request by madanalogy**
Fixes #9474

I found a good [stackoverflow discussion](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript) that includes the downfalls of using regex for email validation if anyone's interested.

### CODE REVIEW

File: src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java [hunk 1]
```diff
@@ -42,7 +43,7 @@ public void testExecute() throws Exception {
     public void testExecute_withNewStudent_shouldBeAddedToDatabase() {
         String courseId = typicalBundle.students.get("student1InCourse1").getCourse();
         StudentAttributes newStudent = getTypicalNewStudent(courseId);
-        StudentsEnrollRequest req = prepareRequest(Arrays.asList(newStudent));
+        StudentsEnrollRequest req = prepareRequest(Collections.singletonList(newStudent));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java:46]: This is unrelated change

File: src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java [hunk 2]
```diff
@@ -218,18 +219,18 @@ public void testExecute_withNumberOfStudentsMoreThanSectionLimit_shouldThrowInva
...
                 .withComment("cmt")
                 .build();
 
-        req = prepareRequest(Arrays.asList(oneMoreStudentToGoBeyondLimit));
+        req = prepareRequest(Collections.singletonList(oneMoreStudentToGoBeyondLimit));
         EnrollStudentsAction action = getAction(req, params);
 
         InvalidHttpRequestBodyException ee = assertThrows(InvalidHttpRequestBodyException.class,
-                () -> action.execute());
+                action::execute);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java:233]: This is unrelated change
