### PR TITLE
USER_IS_TEAM is wrongly used in FeedbackSessionResultsBundle #4018

### LINKED ISSUE #4018: USER_IS_TEAM is wrongly used in FeedbackSessionResultsBundle
Currently in FeedbackSessionResultsBundle, the constant Const.USER_IS_TEAM, %TEAM%, and Const.USER_IS_NOBODY, %NOBODY%, is checked for in a few branches related to names. %TEAM% appears to be related to handling orphaned responses in FeedbackSessionsLogic, this seems wrong. We can check if these constants are actually used, and remove/rename them if neccessary.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4018 
Not entirely sure that this is the best way, but this works and is more representative of what's happening, rather than `USER_IS_TEAM`.

### CODE REVIEW

**Comment by kanghj** [comment]
@wkurniawan07, I think we can modify the issue title then? The modifications look fine to me

**Comment by wkurniawan07** [comment]
@kanghj updated the issue and PR title.

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java [hunk 1]
```diff
@@ -902,7 +902,7 @@ public FeedbackResponseAttributes getActualResponse(FeedbackResponseAttributes r
 
     public String getNameForEmail(String email) {
         String name = emailNameTable.get(email);
-        if (name == null) {
+        if (name == null || name.equals(Const.USER_IS_MISSING)) {
```
Comment (damithc) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: Extract into a small util method? Not sure where to put it though.

**Comment by damithc** [comment]
Waiting for clarifiction

File: src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java (hunk 1 above)
Comment (wkurniawan07) [inline src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java]: If needed, it can be done in the same class as it's not used anywhere. But if the idea is to reduce duplications, the methods `getNameForEmail`, `getLastNameForEmail`, `getRecipientNameForResponse`, and `getGiverNameForResponse` (essentially all methods that has that condition check) are all ~95% duplications, not just this condition check.

**Comment by thyageshm** [comment]
@wkurniawan07 please merge this one too
