### PR TITLE
Instructor: search comments: migrate legacy search documents #7591

### LINKED ISSUE #7591: Instructor: search comments: migrate legacy search documents
Feedback response comments created before V5.93 have search documents containing timestamps in the wrong format. These need to be migrated to use the new format defined in `Const.SystemParams.DEFAULT_DATE_TIME_FORMAT`. See https://github.com/TEAMMATES/teammates/issues/7569#issuecomment-310823161.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7591

### CODE REVIEW

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+        }
+
+        print("Batch updating " + documentsToUpdate.size() + " documents...");
+
+        if (!isPreview) {
+            try {
+                SearchManager.putDocuments(Const.SearchIndex.FEEDBACK_RESPONSE_COMMENT, documentsToUpdate);
+            } catch (Exception e) {
+                throw new RuntimeException("Failed to update one or more documents. Please rerun this script.", e);
+            }
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Relevant exceptions seem to be handled on `SearchManager.putDocuments` side but it does not seem to report if the final put was successful. You might to write your own method to do `putDocuments`.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+        }
+        println(" done.");
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Is the space deliberate?

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 1 above)
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: It may be not good to throw RuntimeException if one put operation was not successful. Maybe just log any exception and continue putting other documents first?

**Comment by leeyimin** [comment]
Placed onHold until issue with putDocuments in SearchManager is fixed.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 1 above)
Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: On second thoughts, I don't think `SearchManager.putDocuments` throws any foreseeable `Exception`; I'm thinking of dropping the try-catch.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 2 above)
Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: For the purpose of recording our discussion: this was to be printed on the same line after the `Batch updating x documents...`. However you pointed out that any exceptions logged would cause the output to be messy, so I've decided to revert the whole commit.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+
+        int numberOfDocuments = 0;
+        int numberOfUnaffectedDocuments = 0;
+        LoopHelper loopHelper = new LoopHelper(batchSize, "comments analyzed.");
+
+        for (FeedbackResponseCommentAttributes comment : allComments) {
+            loopHelper.recordLoop();
+
+            Document document = getDocument(comment);
+            if (document == null) {
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Should such cases be logged?

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+            }
+        }
+        updateAndClearDocuments(documentsToUpdate);
+
+        println("\nComplete! If there are any errors shown above, please rerun this script.");
+    }
+
+    private void queueDocumentUpdate(FeedbackResponseCommentAttributes comment, List<Document> documentsToUpdate) {
+        documentsToUpdate.add(new FeedbackResponseCommentSearchDocument(comment).build());
+    }
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: I feel that it would be better to inline this method, since it is relatively simple. What do you think?

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+    private void updateAndClearDocuments(List<Document> documentsToUpdate) {
+        if (documentsToUpdate.isEmpty()) {
+            return;
+        }
+
+        println("Batch updating " + documentsToUpdate.size() + " documents...");
+
+        if (!isPreview) {
+            SearchManager.putDocuments(Const.SearchIndex.FEEDBACK_RESPONSE_COMMENT, documentsToUpdate);
+        }
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: A bit worried here that the logging will be quite excessive and difficult to navigate if exceptions do occur. What do you think of loosening the visibility of methods in SearchManager in order to use `putDocumentsWithRetry` directly since the access is already restricted by macker?

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+    private Document getDocument(FeedbackResponseCommentAttributes comment) {
+        return index.get(comment.getId().toString());
+    }
+
+    private String extractSampleDateString(Document document) {
+        String frcaJson = document.getOnlyField(Const.SearchDocumentField.FEEDBACK_RESPONSE_COMMENT_ATTRIBUTE).getText();
+        return jsonParser.parse(frcaJson).getAsJsonObject().getAsJsonPrimitive("createdAt").getAsString();
+    }
+
+    private synchronized boolean isInDateFormat(String dateString, DateFormat dateFormat) {
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: `synchronized` can be removed.

Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Oh yea this was only needed previously for accessing the `DateFormat`s directly in private helper methods, before the current iteration of `isInDateFormat` was implemented 😅

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 3 above)
Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: It might be pretty common (resulting in lots of output), and outside the scope of this issue? If we realise there's a huge discrepancy in the reported numbers of comments vs documents on the live server, a new issue and admin script can be written for it.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 4 above)
Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: I'd still like to keep it as it improves readability in the for loop from which it is called.

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java (hunk 5 above)
Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: In using the method directly, is it your intention to quit upon encountering an exception (rather than printing and continuing)?

Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: SearchManager prints out each failed document entirely, which may cause difficulty in scrolling through the output. It would be possible to fine tune the system output if you catch the exceptions yourself.

Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: I know; we can use reflection to bypass the visibility. After all this is just an admin script :)

Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Done :)

File: src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java [hunk 7]
```diff
@@ -0,0 +1,205 @@
...
+        try {
+            Method method = SearchManager.class.getDeclaredMethod("putDocumentsWithRetry", String.class, List.class);
+            method.setAccessible(true);
+            method.invoke(null, indexName, documents);
+        } catch (NoSuchMethodException | IllegalAccessException e) {
+            throw new RuntimeException(e);
+        } catch (InvocationTargetException e) {
+            Throwable originalException = e.getCause();
+            if (originalException instanceof PutException) {
+                throw (PutException) originalException;
```
Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Why not print here directly?

Comment (whipermr5) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: Outside the scope of `invokePutDocumentsWithRetry`, which is only to invoke the private method?

Comment (leeyimin) [inline src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java]: I would think it's better to print here directly to keep the code easier to follow, no other comments otherwise.

**Comment by damithc** [comment]
@whipermr5 I'm getting an error for this setting; Related? Probably I never ran the migration script? Can I run it for the liver server now?

image

**Comment by damithc** [comment]
Stack trace:
```
teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :  (Logger.java:52)
java.lang.NullPointerException
	at teammates.storage.search.FeedbackResponseCommentSearchDocument.fromResults(FeedbackResponseCommentSearchDocument.java:326)
	at teammates.storage.api.FeedbackResponseCommentsDb.search(FeedbackResponseCommentsDb.java:325)
	at teammates.logic.core.FeedbackResponseCommentsLogic.searchFeedbackResponseComments(FeedbackResponseCommentsLogic.java:160)
	at teammates.logic.api.Logic.searchFeedbackResponseComments(Logic.java:1993)
	at teammates.ui.controller.InstructorSearchPageAction.execute(InstructorSearchPageAction.java:51)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:76)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by whipermr5** [comment]
Should be related to #7909 instead. There's a data migration script to be run there.

**Comment by damithc** [comment]
The error went away after running the migration script. Thanks @whipermr5
