### PR TITLE
AdminSessionsPage: fix parse failure for dates selected via datepicker #8733

### LINKED ISSUE #8733: AdminSessionsPage: fix parse failure for dates selected via datepicker
When changing start date and end date to filter feedback sessions, accepted date format in input field is `dd/mm/yyyy` but datepicker format is `D, dd MMM, yyyy` which on selecting results in redirection to error page.
- **Environment**: `master` branch 

**Steps to reproduce**
Login as admin.
Go to Sessions Tab.
Change dates from filter.

**Expected behaviour**
Input field should parse same date as datepicker.

**Actual behaviour**
Input field and datepicker have different date formats.

**Additional info**
This bug was most probably introduced in #1701. 
Can be solved by changing the parsing of input field of start date and end date.

### PR DESCRIPTION
**Pull request by nidhi98gupta**
Fixes #8733

### CODE REVIEW

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 1]
```diff
@@ -502,14 +502,14 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
      * Parses a `LocalDateTime` object from separated date, hour and minute strings.
      *
      * <p>required parameter format:
-     * date: dd/MM/yyyy  hour: H   min:m
+     * date: EEE, dd MMM, yyyy  hour: H   min:m
      * Example: If date is 01/04/2014, hour is 23, min is 59.
```
Comment (darrenwee) [inline src/main/java/teammates/common/util/TimeHelper.java]: You should also update the `Example` line to reflect the new expected format since we cannot accept `01/04/2014` anymore :smile:

Since you're touching the javadoc anyway, you can update this javadoc to meet our [conventions](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html#comments) and use the `@param` annotations for the javadoc, e.g.
```
@param date  date in format "EEE, dd MMM, yyy"
@param hour  hour-of-day (0-23)
@param min   minute-of-hour (0-59)
```

You can use the patterns table from the [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) docs to help you write this.

You can also update the description of the method since it's specifically for a sessions-related page.

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 2]
```diff
@@ -502,14 +502,14 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
...
      */
     public static LocalDateTime parseLocalDateTime(String date, String hour, String min) {
```
Comment (darrenwee) [inline src/main/java/teammates/common/util/TimeHelper.java]: This method needs to be renamed to something more descriptive since it is now for a specific use case. Maybe something like `parseLocalDateTimeForSessionsForm` to match `formatDateForSessionsForm`.

**Comment by darrenwee** [comment]
@tran-tien-dat This may break your PR #8732. I saw some usage of `parseLocalDateTime` inside #8732, can you double check and request changes as necessary?

**Comment by tran-tien-dat** [comment]
@darrenwee Yep it will break. If the time format in this PR is preferred, then I will change my PR.

**Comment by nidhi98gupta** [comment]
@whipermr5 @darrenwee CI Test is failing with error 
```The command "curl -fsS -o $HOME/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz" failed and exited with 22 during .```
Is there anything that I need to do to resolve this?

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 3]
```diff
@@ -485,7 +485,7 @@ public static String convertToStandardDuration(Long timeInMilliseconds) {
      * @param pattern           the pattern of the date and time string
      * @return                  the parsed {@code LocalDateTime} object, or {@code null} if there are errors
      */
-    public static LocalDateTime parseLocalDateTime(String dateTimeString, String pattern) {
+    public static LocalDateTime parseLocalDateTimeForSessionsForm(String dateTimeString, String pattern) {
```
Comment (darrenwee) [inline src/main/java/teammates/common/util/TimeHelper.java]: Sorry, I think you took my previous comment a little too seriously! `parseLocalDateTimeForSessionsForm(String, String, String)` is a facade for `parseLocalDateTime(String, String)`, which is the method that does the actual datetime parsing. You'll have to rename this method back to `parseLocalDateTime` (but not the other one!)

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 4]
```diff
@@ -499,17 +499,20 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
     }
 
     /**
-     * Parses a `LocalDateTime` object from separated date, hour and minute strings.
+     * Parses a {@code LocalDateTime} object for session form from separated date, hour and minute strings.
+     * Example: If date is Tue, 01 Apr, 2014, hour is 23, min is 59.
+     * Returns {@code null} on error.
```
Comment (darrenwee) [inline src/main/java/teammates/common/util/TimeHelper.java]: You can delete this `Returns` line, there's already a `@return` annotation below that covers this.

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 5]
```diff
@@ -499,17 +499,20 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
     }
 
     /**
-     * Parses a `LocalDateTime` object from separated date, hour and minute strings.
+     * Parses a {@code LocalDateTime} object for session form from separated date, hour and minute strings.
+     * Example: If date is Tue, 01 Apr, 2014, hour is 23, min is 59.
```
Comment (darrenwee) [inline src/main/java/teammates/common/util/TimeHelper.java]: `Example: date "Tue, 01 Apr, 2014", hour "23", min "59"`

**Comment by darrenwee** [comment]
@nidhi98gupta Stuff like that happens sometimes, like jcenter being down the other day. You can just wait a while and restart the build.

**Comment by darrenwee** [comment]
> @darrenwee Yep it will break. If the time format in this PR is preferred, then I will change my PR.

Maybe refactor your PR to call `parseLocalDateTime` and specify the pattern string by hard coding it? It's only used twice in that test.

**Comment by tran-tien-dat** [comment]
Yep

File: src/main/java/teammates/common/util/TimeHelper.java (hunk 3 above)
Comment (nidhi98gupta) [reply src/main/java/teammates/common/util/TimeHelper.java]: Oops, Sorry. I misunderstood. :sweat_smile:

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 6]
```diff
@@ -499,17 +499,19 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
...
 
     /**
-     * Parses a `LocalDateTime` object from separated date, hour and minute strings.
+     * Parses a {@code LocalDateTime} object for session form from separated date, hour and minute strings.
+     * Example: date "Tue, 01 Apr, 2014", hour "23", min "59"
      *
-     * <p>required parameter format:
-     * date: dd/MM/yyyy  hour: H   min:m
-     * Example: If date is 01/04/2014, hour is 23, min is 59.
+     * @param date  date in format "EEE, dd MMM, yyy"
```
Comment (whipermr5) [inline src/main/java/teammates/common/util/TimeHelper.java]: Missing a y

Comment (nidhi98gupta) [reply src/main/java/teammates/common/util/TimeHelper.java]: Oops Sorry! :sweat_smile:

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 7]
```diff
@@ -499,17 +499,19 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
     }
 
     /**
-     * Parses a `LocalDateTime` object from separated date, hour and minute strings.
+     * Parses a {@code LocalDateTime} object for session form from separated date, hour and minute strings.
```
Comment (whipermr5) [inline src/main/java/teammates/common/util/TimeHelper.java]: I don't think `for session form` is necessary in this description?

Comment (whipermr5) [reply src/main/java/teammates/common/util/TimeHelper.java]: Oh I just read @darrenwee's comment. I think methods should not know where they are being called from. The format methods are slightly different; the location they are called from is used to indicate the format that is returned, i.e. "return this date in a format that is suitable for the sessions form", and not "this method is only to be called from the sessions form".

Comment (whipermr5) [reply src/main/java/teammates/common/util/TimeHelper.java]: Hence I'd also like to propose renaming the method back to its original name. @darrenwee thoughts?

**Comment by whipermr5** [comment]
Need to fix compilation errors after merging the latest master.

File: src/main/java/teammates/common/util/TimeHelper.java (hunk 7 above)
Comment (darrenwee) [reply src/main/java/teammates/common/util/TimeHelper.java]: I think renaming it back to the original is not a good idea because the formatter string is hard coded into the method and acts as a facade for the actual `parseLocalDateTime(String, String)` method.

The `EEE, dd MMM...` format is only used in sessions-related forms, like the admin's sessions page, hence the original request to change the method name. If you had a method of name like `parseLocalDateTime(String date, String hour, String minute)`, the name would not tell you about what format it expects for each date/hour/minute field even though the pattern has been hard coded. The `format..` methods' names dictate what format the output will be suitable for, so the `parse...` methods (the inverse of the format methods) should also dictate what format type the input will be.

Comment (whipermr5) [reply src/main/java/teammates/common/util/TimeHelper.java]: That makes sense. I think the `For` should be changed to `From` though.

File: src/main/java/teammates/common/util/TimeHelper.java [hunk 8]
```diff
@@ -553,17 +553,19 @@ public static LocalDateTime parseLocalDateTime(String dateTimeString, String pat
...
-     * <p>required parameter format:
-     * date: dd/MM/yyyy  hour: H   min:m
-     * Example: If date is 01/04/2014, hour is 23, min is 59.
+     * @param date  date in format "EEE, dd MMM, yyyy"
+     * @param hour  hour-of-day (0-23)
+     * @param min   minute-of-hour (0-59)
+     * @return      the parsed {@code LocalDateTime} object, or {@code null} if there are errors
      */
-    public static LocalDateTime parseLocalDateTime(String date, String hour, String min) {
+    public static LocalDateTime parseLocalDateTimeForSessionsForm(String date, String hour, String min) {
```
Comment (whipermr5) [inline src/main/java/teammates/common/util/TimeHelper.java]: How about `parseLocalDateTimeFromSessionsFormInputs`?

Comment (darrenwee) [reply src/main/java/teammates/common/util/TimeHelper.java]: I think `parseLocalDateTimeFromSessionsForm` is okay. I tried to look to the formatting methods (their inverses) for guidance, but right now they're not consistent; we have `formatDateForSessionsForm` and `formatDateTimeForSessions`. I will standardize the method names when addressing #8645. We should probably standardize each formatting string and their purpose at some point in the future for consistency's sake.

**Comment by nidhi98gupta** [comment]
@whipermr5 Build is failing with the error
```
java.lang.AssertionError: expected:<[The start time, Fri, 30 Dec 2011, 07:00 AM, falls within the gap period when clocks spring forward at the start of DST. It was resolved to Sat, 31 Dec 2011, 07:00 AM WSDT (UTC+1400)., The feedback session has been added. Click the "Add New Question" button below to begin adding questions for the feedback session.]> but was:<[The feedback session has been added. Click the "Add New Question" button below to begin adding questions for the feedback session.]>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at teammates.test.pageobjects.AppPage.waitForTextsForAllStatusMessagesToUserEquals(AppPage.java:1001)
	at teammates.test.cases.browsertests.InstructorFeedbackSessionsPageUiTest.testAddAction(InstructorFeedbackSessionsPageUiTest.java:251)
	at teammates.test.cases.browsertests.InstructorFeedbackSessionsPageUiTest.testAddDeleteActions(InstructorFeedbackSessionsPageUiTest.java:100)
```
Does this have something to do with DST issue?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java [hunk 9]
```diff
@@ -238,7 +238,7 @@ private void testAddAction() throws Exception {
 
         String dstSessionName = "DST Session";
         ZoneId dstTimeZone = ZoneId.of("Pacific/Apia");
-        LocalDateTime gapStart = TimeHelper.parseLocalDateTime("30/12/2011", "7", "0");
+        LocalDateTime gapStart = TimeHelper.parseLocalDateTimeForSessionsForm("30/12/2011", "7", "0");
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java]: Wrong format

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 10]
```diff
@@ -237,8 +237,8 @@ private void testEditSessionAction() throws Exception {
 
         ______TS("test ambiguous date times");
         ZoneId dstTimeZone = ZoneId.of("Australia/Victoria");
-        LocalDateTime overlapStartTime = TimeHelper.parseLocalDateTime("05/04/2015", "2", "0");
-        LocalDateTime gapEndTime = TimeHelper.parseLocalDateTime("01/10/2017", "2", "0");
+        LocalDateTime overlapStartTime = TimeHelper.parseLocalDateTimeForSessionsForm("05/04/2015", "2", "0");
+        LocalDateTime gapEndTime = TimeHelper.parseLocalDateTimeForSessionsForm("01/10/2017", "2", "0");
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Wrong format

File: src/main/java/teammates/common/util/TimeHelper.java (hunk 8 above)
Comment (whipermr5) [reply src/main/java/teammates/common/util/TimeHelper.java]: I guess `parseLocalDateTimeForSessionsForm` is fine too.

> I will standardize the method names when addressing #8645. We should probably standardize each formatting string and their purpose at some point in the future for consistency's sake.

Sounds good 👍

File: src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java [hunk 11]
```diff
@@ -185,8 +185,8 @@ public String getSessionStatusForShow(FeedbackSessionAttributes fs) {
     }
 
     private void setFilter() {
-        filter = new AdminFilter(TimeHelper.formatDate(rangeStart), getHourOptionsAsHtml(rangeStart),
-                                 getMinuteOptionsAsHtml(rangeStart), TimeHelper.formatDate(rangeEnd),
+        filter = new AdminFilter(TimeHelper.formatDateForSessionsForm(rangeStart), getHourOptionsAsHtml(rangeStart),
+                                 getMinuteOptionsAsHtml(rangeStart), TimeHelper.formatDateForSessionsForm(rangeEnd),
                                  getHourOptionsAsHtml(rangeEnd), getMinuteOptionsAsHtml(rangeEnd),
                                  getTimeZoneOptionsAsHtml());
```
Comment (whipermr5) [inline src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java]: Can switch to 8-space indentation

File: src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java [hunk 12]
```diff
@@ -185,10 +185,9 @@ public String getSessionStatusForShow(FeedbackSessionAttributes fs) {
     }
 
     private void setFilter() {
-        filter = new AdminFilter(TimeHelper.formatDate(rangeStart), getHourOptionsAsHtml(rangeStart),
-                                 getMinuteOptionsAsHtml(rangeStart), TimeHelper.formatDate(rangeEnd),
-                                 getHourOptionsAsHtml(rangeEnd), getMinuteOptionsAsHtml(rangeEnd),
-                                 getTimeZoneOptionsAsHtml());
+        filter = new AdminFilter(TimeHelper.formatDateForSessionsForm(rangeStart), getHourOptionsAsHtml(rangeStart),
+                         getMinuteOptionsAsHtml(rangeStart), TimeHelper.formatDateForSessionsForm(rangeEnd),
+                         getHourOptionsAsHtml(rangeEnd), getMinuteOptionsAsHtml(rangeEnd), getTimeZoneOptionsAsHtml());
```
Comment (whipermr5) [inline src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java]: Should be 8 spaces from the start of `filter`. Might look better if the first two parameters are on the next line from the constructor call, aligned with the rest of the parameters.

Comment (nidhi98gupta) [reply src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java]: Is it possible to add these indentation rules in checkstyle test?

Comment (whipermr5) [reply src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java]: Probably possible. You are free to open an issue :)
