### PR TITLE
[#9823] Fix feedback made on behalf of team showing as anonymous 

### LINKED ISSUE #9823: Student result: Feedback made on behalf of team showing as anonymous
...even with the visibility set to `Visible to recipient and instructors`

- **Environment**: 
`master` branch at commit a3e909210ccd21c653ae09f04e618cb06c36c418

**Steps to reproduce**
1. As an instructor, create a feedback session with a question set with feedback path: `Teams in this course -> Other students in the course` and visibility option: `Visible to recipient and instructors`
2. As a student, submit feedback for the above question.
3. As an instructor, publish the session.
4. Log in again as a student and view the results.

**Expected behaviour**
Since the visibility is not set to anonymous, the giver(which should be the student's team name) and recipient name should be shown for the student.

**Actual behaviour**
Giver and recipient showing as anonymous

### PR DESCRIPTION
**Pull request by madanalogy**
Fixes #9823 , Closes #9826 

Original credits to @erjillsison for design and implementation

### CODE REVIEW

**Comment by xpdavid** [comment]
First thing first, it the original issue valid after the refactor of session result logic?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 1]
```diff
@@ -201,7 +201,7 @@ public boolean isNameVisibleToUser(
         // Early return if user is giver
         if (question.giverType == FeedbackParticipantType.TEAMS) {
             // if response is given by team, then anyone in the team can see the response
-            if (roster.isStudentsInSameTeam(response.giver, userEmail)) {
+            if (roster.isStudentInTeam(userEmail, response.giver)) {
```
Comment (xpdavid) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: Some context here:
- Sadly, we do not manage to migrate the database for team response. There are still entries in the database where `giver` is one of the team member's email.

File: src/test/resources/data/FeedbackSessionResultsTest.json [hunk 2]
```diff
@@ -594,7 +594,7 @@
       "feedbackSessionName": "Standard feedback session",
       "courseId": "FSRTest.idOfTypicalCourse1",
       "feedbackQuestionId": "7",
-      "giver": "FSRTest.student2InCourse1@gmail.tmt",
+      "giver": "Team 1.1",
```
Comment (xpdavid) [inline src/test/resources/data/FeedbackSessionResultsTest.json:597]: And therefore, let's make sure we have test data that cover the legacy data. We should remove it only after we have migrated the database.

**Comment by madanalogy** [comment]
> First thing first, it the original issue valid after the refactor of session result logic?

I can confirm that this is no longer an issue, I will close the PRs and related issue

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 1 above)
Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: Don't close too soon. I think the fix is necessary? In addition, have you tried the legacy case where the `response.giver` is student's email?

Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: I don't know how to try the legacy case. I verified using the sequence described in the original issue with the uat server, and team responses did not show as anonymous.

Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: You can:
- Modify the current submission logic temporally to achieve that.
- Modify the instructor demo data and create a new account

Comment (wkurniawan07) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: @xpdavid if we run the migration script now, would V6 still function correctly?

Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: Yes. Both V6 and V7 has the ability to handle both scenarios.

**Comment by madanalogy** [comment]
@xpdavid I tried the current system with the session result logic refactor and legacy data (without the changes in this PR), and can confirm that the issue is no longer relevant. 

However, an entirely new issue cropped up where the identity of the sender is revealed even though it should have been a "Team" submission. 

This is a response where the giver was an email instead of the team name:
Screenshot 2020-07-17 at 11 22 13 PM

This is a response where the giver was the team name:

Screenshot 2020-07-17 at 11 46 30 PM

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 1 above)
Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: I am trying to understand in the legacy case where `response.giver` is an email. There will be a bug here?

Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: It depends on how the legacy team name was formulated. If it's just the email of the giver then this line might return false for everyone else in the team (other than the original giver).

https://github.com/TEAMMATES/teammates/blob/faf15f9cc55f795550277b8ef7f4b8ce571ac07c/src/main/java/teammates/common/datatransfer/CourseRoster.java#L62-L72

Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: > It depends on how the legacy team name was formulated.

There is only one way if I am not wrong (The giver will be the email).

> If it's just the email of the giver then this line might return false 

Which is not correct? Should return `true`?

Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: > Which is not correct? Should return `true`?

Yeap that sounds about right. 

Given that this issue is no longer relevant (even with legacy data), any issues if I close it?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 3]
```diff
@@ -201,7 +201,7 @@ public boolean isNameVisibleToUser(
         // Early return if user is giver
         if (question.giverType == FeedbackParticipantType.TEAMS) {
             // if response is given by team, then anyone in the team can see the response
-            if (roster.isStudentsInSameTeam(response.giver, userEmail)) {
```
Comment (xpdavid) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: The old code works for legacy data for team response.

Does it work for the new data (where giver is the team name)? It looks like a `no` to me.

Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: Okay I think I get it now haha, have pushed new code to check for both current and legacy cases

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 4]
```diff
@@ -201,7 +201,8 @@ public boolean isNameVisibleToUser(
...
+            if (roster.isStudentInTeam(userEmail, response.giver)
+                    || roster.isStudentsInSameTeam(userEmail, response.giver)) {
```
Comment (xpdavid) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:205]: Remember to add comment explain the legacy case

File: src/test/resources/data/FeedbackSessionResultsTest.json (hunk 2 above)
Comment (xpdavid) [reply src/test/resources/data/FeedbackSessionResultsTest.json]: How does this get addresed?

**Comment by wkurniawan07** [comment]
@madanalogy I don't think you should change any of the test data. They're there to handle this case.

File: src/test/resources/data/FeedbackSessionResultsTest.json (hunk 2 above)
Comment (madanalogy) [reply src/test/resources/data/FeedbackSessionResultsTest.json]: Changes have been reverted

File: src/test/resources/data/FeedbackSessionResultsTest.json [hunk 5]
```diff
@@ -179,9 +179,9 @@
       "googleId": "FSRTest.student1InCourse1",
       "email": "FSRTest.student1InCourse1@gmail.tmt",
       "course": "FSRTest.idOfTypicalCourse1",
-      "name": "student1 In Course1</td></div>'\"",
+      "name": "student1 In Course1",
       "comments": "comment for student1InCourse1",
-      "team": "Team 1.1</td></div>'\"",
```
Comment (xpdavid) [inline src/test/resources/data/FeedbackSessionResultsTest.json:184]: Why do we need the change this?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 4 above)
Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:206]: If it is not too difficult, we can have a test for this

File: src/test/resources/data/FeedbackSessionResultsTest.json (hunk 5 above)
Comment (madanalogy) [reply src/test/resources/data/FeedbackSessionResultsTest.json:184]: I thought the HTML tags were just typos that never got fixed?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 4 above)
Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:206]: How would I go about writing tests for this exactly? I had thought it was not necessary since the current tests already check for visibility.

File: src/test/resources/data/FeedbackSessionResultsTest.json (hunk 5 above)
Comment (xpdavid) [reply src/test/resources/data/FeedbackSessionResultsTest.json:184]: Nope. There are there for some reasons:
- Text sanitization
- HTML code escape

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 4 above)
Comment (xpdavid) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:206]: The newly added condition is not covered right?

File: src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java [hunk 6]
```diff
@@ -423,6 +423,8 @@ public void testIsNameVisibleTo() {
 
         fr.giver = student.email;
         assertTrue(frLogic.isNameVisibleToUser(fq, fr, student.email, UserRole.STUDENT, false, roster));
+        fr.giver = student.team;
+        assertTrue(frLogic.isNameVisibleToUser(fq, fr, student.email, UserRole.STUDENT, false, roster));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java:427]: This test case is ineffective because the question's giver type here is `SELF`.

File: src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java [hunk 7]
```diff
@@ -451,6 +451,24 @@ public void testIsNameVisibleTo() {
         assertTrue(frLogic.isNameVisibleToUser(fq, fr, student3.email, UserRole.STUDENT, false, roster));
         assertFalse(frLogic.isNameVisibleToUser(fq, fr, student5.email, UserRole.STUDENT, false, roster));
 
+        fq.recipientType = FeedbackParticipantType.TEAMS;
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java:454]: Need a new `______TS` header here

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 8]
```diff
@@ -201,7 +201,9 @@ public boolean isNameVisibleToUser(
         // Early return if user is giver
         if (question.giverType == FeedbackParticipantType.TEAMS) {
             // if response is given by team, then anyone in the team can see the response
-            if (roster.isStudentsInSameTeam(response.giver, userEmail)) {
+            // The second check is used to accommodate legacy data where team giver is a student email
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: You meant the first check? The second check is the pre-existing one

Comment (madanalogy) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: Yea, the pre-existing one is the one that's catering to legacy data I think. That's why @xpdavid suggested going ahead with this PR even though the session logic refactor meant that the original issue is no longer relevant

Comment (wkurniawan07) [reply src/main/java/teammates/logic/core/FeedbackResponsesLogic.java:204]: I see, got it
