### PR TITLE
[#13586] Fix student edit form accepts whitespaces in team field

### LINKED ISSUE #13586: Student edit form accepts whitespaces in team field
- **Environment**: V9-clean-slate-sql staging website (Merged into master)

**Steps to reproduce**
1. Enrol a student as an instructor.
1. Access the student list and click on edit on the new student.
1. Delete the team field and add whitespaces.
1. Click save changes.
1. See the outcome.

**Expected behaviour**
System to reject whitespaces as it counts as empty team.

**Actual behaviour**
System accepts and the student now has a team name that is just whitespaces.

Image

### PR DESCRIPTION
**Pull request by ishani-das**
**Problem:** 
"Edit Student Details" page (instructor-view) allowed Team Names to be updated to whitespace-only characters.

**Our Approach:**
1. Frontend validation - Angular's Validator is used on the edit form logic input, but it allowed whitespace to pass, so we added a custom validator to check for whitespace in addition to the existing ones.
2. Backend validation - Updated server code to reject the "update student" request when just whitespace submitted for Team Name. We added this backend protect in case anyone submitted directly to backend bypassing frontend protection.

**Testing:**
1. Frontend validation - Verified that the error message “The field ‘Team Name’ should not be empty.” displayed when only whitespace in input box. Doesn't allow user to click "Save Changes".
2. Backend validation - Added a new test (`testExecute_whitespaceOnlyTeamName_throwsInvalidHttpRequestBodyException`) to `UpdateStudentAction.java` -> passed.

Fixes #13586

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/UpdateStudentAction.java [hunk 1]
```diff
@@ -76,10 +76,13 @@ public JsonResult execute() throws InvalidHttpRequestBodyException, InvalidOpera
 
         Course course = sqlLogic.getCourse(courseId);
         Section section = sqlLogic.getSectionOrCreate(courseId, updateRequest.getSection());
-        Team team = sqlLogic.getTeamOrCreate(section, updateRequest.getTeam());
+        String teamName = updateRequest.getTeam();
+        if (teamName == null || teamName.trim().isEmpty()) {
+            throw new InvalidHttpRequestBodyException("Team name should not be empty");
+        }
```
Comment (samuelfangjw) [inline src/main/java/teammates/ui/webapi/UpdateStudentAction.java]: Validation should be done within `src/main/java/teammates/ui/request/StudentUpdateRequest.java`. Validation for request body is handled at that layer.

File: src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts [hunk 2]
```diff
@@ -120,6 +120,17 @@ export class InstructorCourseStudentEditPageComponent implements OnInit, OnDestr
...
+  /**
+   * Custom validator to identify whitespace
+   */
+  private static noWhitespaceValidator(control: AbstractControl): { [key: string]: boolean } | null {
+  const value = control.value;
+  if (typeof value === 'string' && value.trim().length === 0) {
+    return { required: true };
+  }
+  return null;
+}
```
Comment (samuelfangjw) [inline src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts]: Let's move this to a new file dedicated to validators. You will have to find a suitable place for it. 

I would like it to be reusable across the system.  There are upcoming plans to rework forms and validation, but it hasn't been prioritised at the moment.

File: src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts [hunk 3]
```diff
@@ -120,6 +120,17 @@ export class InstructorCourseStudentEditPageComponent implements OnInit, OnDestr
     });
   }
 
+  /**
+   * Custom validator to identify whitespace
+   */
+  private static noWhitespaceValidator(control: AbstractControl): { [key: string]: boolean } | null {
```
Comment (samuelfangjw) [inline src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts]: return type should be `ValidationErrors`, follow reference at https://angular.dev/guide/forms/form-validation#defining-custom-validators

File: src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts [hunk 4]
```diff
@@ -120,6 +120,17 @@ export class InstructorCourseStudentEditPageComponent implements OnInit, OnDestr
...
+  const value = control.value;
+  if (typeof value === 'string' && value.trim().length === 0) {
+    return { required: true };
```
Comment (samuelfangjw) [inline src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts]: Shouldn't use the required as the validation key, that's already used by the required validator.

File: src/test/java/teammates/sqlui/webapi/UpdateStudentActionTest.java [hunk 5]
```diff
@@ -362,6 +364,31 @@ void testExecute_invalidUpdateAttributes_throwsInvalidHttpRequestBodyException()
...
+        verify(mockLogic, times(1)).getStudentForEmail(course.getId(), student.getEmail());
+        verify(mockLogic, times(1)).getCourse(course.getId());
+        verify(mockLogic, times(1)).getSectionOrCreate(course.getId(), studentUpdateRequest.getSection());
+
+        verify(mockLogic, never()).getTeamOrCreate(any(), anyString());
+        verify(mockLogic, never()).updateStudentCascade(any(Student.class));
+        verifyNoTasksAdded();
+        verifyNoEmailsSent();
+
+        verifyNoMoreInteractions(mockLogic, mockSqlEmailGenerator);
```
Comment (samuelfangjw) [inline src/test/java/teammates/sqlui/webapi/UpdateStudentActionTest.java]: Since we are testing that `InvalidHttpRequestBodyException` is thrown, these should not be necessary. Asserting that the exception is thrown is enough.

Ignore the pre-existing tests, they are not well written.

**Review by samuelfangjw — CHANGES_REQUESTED** [review]
This is great, just a bit of cleanup and it should be ready to be merged.

**Comment by ishani-das** [comment]
Thank you for the feedback @samuelfangjw! We made the following changes:
- moved backend validation into StudentUpdateRequest
- extracted the whitespace validator into a reusable file
- updated the frontend to handle the new validation key
- cleaned up the backend test

Let us know if anything else should be adjusted!!

**Comment by samuelfangjw** [comment]
Looks good, resolve the CI failures and should be good to go. Thank you for your contribution to TEAMMATES!

**Comment by ishani-das** [comment]
Thank you! Does it look alright now?

**Review by samuelfangjw — APPROVED** [review]
