### PR TITLE
Fix NoAlertPresentException in InstructorCourseStudentDetailsEditPageUiTest on Travis #5177

### LINKED ISSUE #5177: Fix NoAlertPresentException in InstructorCourseStudentDetailsEditPageUiTest on Travis

### PR DESCRIPTION
**Pull request by ashrayjain**
Fixes #5177 

~~Increases the wait timeout before interacting with alert, when the environment is detected as `TRAVIS`.~~
Adds wait for alert to be present.

### CODE REVIEW

**Comment by thyageshm** [comment]
@ashrayjain can you finish this by this release?

**Comment by ashrayjain** [comment]
@thyageshm sorry boss, gonna be difficult for this release. busy with my fyp report. should be done soon after that though.

**Comment by wkurniawan07** [comment]
Uh-oh, denied Travis green because of this...

**Comment by wkurniawan07** [comment]
@ashrayjain, any progress on this PR? Is it possible to finish by this release?

**Comment by wkurniawan07** [comment]
@ashrayjain I hate to break it, but the failure has nothing to do with timeout (although changing the `ThreadHelper.wait` to `waitForAlertPresence` is a good practice).

**Comment by ashrayjain** [comment]
@wkurniawan07 yup, i have realized that. After a LOT of testing, it looks like it only happens when a specific number of tests run in parallel. The base problem seems to be that there is a window on top of the window which triggers the alert. I have been able to replicate this on my local machine too. You can try by breaking before the check for the alert (the line ```browser.driver.switchTo().alert();```) and opening a new "window" from the same browser instance. Then the alert doesn't get detected. As of now, removing the parallelism from the testng suite seems to "fix" the problem. But I'm hesitant to consider it solved.

**Comment by wkurniawan07** [comment]
@ashrayjain I think you can stop the CI run, there're too many failures happening out there.
Also, non-active window is actually one of the things on my radar, but if it's really the cause why is this test the only one affected?

**Comment by ashrayjain** [comment]
@wkurniawan07 very curious indeed. why would reducing parallelism cause test failures?
As to this being the only test, I think it might be because of the order of the tests. Not completely sure though. According to me testing, removing some tests allows this test to pass. I have not yet figured out the exact pattern however.

**Comment by ashrayjain** [comment]
Reducing the parallelism did allow the test to pass in the first attempt!

File: src/test/java/teammates/test/pageobjects/Browser.java [hunk 1]
```diff
@@ -90,7 +91,13 @@ private WebDriver createWebDriver() {
...
                 System.setProperty("webdriver.firefox.bin",firefoxPath);
             }
-            return new FirefoxDriver();
+            FirefoxProfile profile = new FirefoxProfile();
+            profile.setPreference("browser.download.panel.shown", false);
+            profile.setPreference("browser.helperApps.neverAsk.openFile","text/csv,application/vnd.ms-excel");
+            profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv,application/vnd.ms-excel");
+            profile.setPreference("browser.download.folderList", 2);
+            profile.setPreference("browser.download.dir", System.getProperty("java.io.tmpdir"));
+            return new FirefoxDriver(profile);
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/Browser.java]: You might want to add comments explaining the purpose of these settings.

Comment (ashrayjain) [inline src/test/java/teammates/test/pageobjects/Browser.java]: Yup, will add. still WIP :-P

**Comment by ashrayjain** [comment]
@wkurniawan07 so it looks like the download dialog might be the culprit. This popup appears when we download a csv as part of another test. Changing the firefox profile to auto download the files to the "tmpdir" seems to fix the problem. I have run the last build a couple of times now and the test in question has passed on the first attempt in both the runs. your thoughts?

**Comment by wkurniawan07** [comment]
@ashrayjain if the download dialog's really the cause, see if interacting with it might be a simpler solution? Otherwise this looks great, with some explanatory comments :+1:

**Comment by damithc** [comment]
From what I remember, download dialog box is OS dependent and web driver cannot interact with it.

**Comment by ashrayjain** [comment]
@damithc @wkurniawan07 that is correct. from my research online, it looks like those dialogs are native and can't be controlled by selenium.

**Comment by wkurniawan07** [comment]
Ok then, go ahead with this. Remember to add comments to the `FirefoxProfile` section. Also mention that it is beyond Selenium's ability to interact with such.

**Comment by ashrayjain** [comment]
@wkurniawan07 ready for your review after the Travis build (should be green!)

File: src/test/java/teammates/test/pageobjects/Browser.java [hunk 2]
```diff
@@ -90,7 +91,22 @@ private WebDriver createWebDriver() {
...
+            // http://stackoverflow.com/questions/24852709
+            FirefoxProfile profile = new FirefoxProfile();
+            profile.setPreference("browser.download.panel.shown", false);
+            profile.setPreference("browser.helperApps.neverAsk.openFile",
+                                  "text/csv,application/vnd.ms-excel");
+            profile.setPreference("browser.helperApps.neverAsk.saveToDisk",
+                                  "text/csv,application/vnd.ms-excel");
+            profile.setPreference("browser.download.folderList", 2);
+            profile.setPreference("browser.download.dir",
+                                  System.getProperty("java.io.tmpdir"));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/Browser.java]: The previous one was better in terms of readability. Even though the line length limit might be slightly exceeded, it's much easier to comprehend when all the preferences are stacked this way:
```java
profile.setPreference("some.long.preference.1", "value");
profile.setPreference("some.long.preference.2", "some/very/very/very/long/value");
profile.setPreference("some.long.preference.3", value);
```

Comment (ashrayjain) [inline src/test/java/teammates/test/pageobjects/Browser.java]: sure, will revert it back! :)

**Comment by ashrayjain** [comment]
@wkurniawan07 ready for you!

**Comment by wkurniawan07** [comment]
Good to go!

File: src/test/java/teammates/test/pageobjects/Browser.java [hunk 3]
```diff
@@ -90,7 +91,19 @@ private WebDriver createWebDriver() {
                 System.out.println("Custom path: " + firefoxPath);
                 System.setProperty("webdriver.firefox.bin",firefoxPath);
             }
-            return new FirefoxDriver();
+
+            // Allow CSV files to be download automatically, without a download popup.
+            // This method is used because Selenium cannot directly interact
+            // with the download dialog.
+            // Reference:
+            // http://stackoverflow.com/questions/24852709
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/Browser.java]: This is tidier?
```java
// Allow CSV files to be download automatically, without a download popup.
// This method is used because Selenium cannot directly interact with the download dialog.
// Taken from http://stackoverflow.com/questions/24852709
```

**Comment by damithc** [comment]
Minor cosmetic change suggested. Can go ahead and merge after that.

File: src/test/java/teammates/test/pageobjects/Browser.java (hunk 3 above)
Comment (ashrayjain) [inline src/test/java/teammates/test/pageobjects/Browser.java]: updated
