### PR TITLE
[#10703] Fix warning when instructor change visibility of question

### LINKED ISSUE #10703: Instructor changing visibility of questions: incorrect warning
An instructor changing the visibility (when there are responses already) does not actually delete existing responses. However, the warning message state existing responses will be deleted. Instead, the warning message should only state that it is not recommended because the existing responses were submitted under a different visibility 'promise'.

However, changing the feedback path does result in the deletion of existing responses and users should be warned as such.

### PR DESCRIPTION
**Pull request by helloImHai**
Fixes #10703 

**Outline of Solution**

Similar to the outline in #10703 
> I think we should leave the isChanged variable as it is, and make it such that the visibility alone will not set this flag true. Instead, I'll make a isVisibilityChanged boolean that will be changed when visibility is changed, so that if only visibility is changed, we'll render a separate warning model so the user knows that responses will not be deleted. This is also for modularity so that the warning of deletion for feedback change can be done at a later date.

Set a new `isVisibilityChanged`, create `FILTER_PROPERTIES` and add them into `CLEAN_PROPERTIES` so that it will not set `isChanged` flag true. Based on the `isVisibilityChanged` variable, we will render the warning respectively.

Only visibility changes:
Screenshot 2020-09-19 at 12 49 23 AM

Only non-visibility changes (No change from before):
Screenshot 2020-09-19 at 12 58 27 AM

Both visibility and other changes (No change from before):
Screenshot 2020-09-19 at 12 58 42 AM

### CODE REVIEW

**Comment by damithc** [comment]
> Only visibility changes:
> Screenshot 2020-09-19 at 12 49 23 AM

How about this?

>You seem to have changed the visibility settings of this question. Please note that **the existing responses will remain but their visibility will be changed as per the new visibility settings**. Proceed?


> Only non-visibility changes (No change from before):
> Screenshot 2020-09-19 at 12 58 27 AM

How about this?
>Editing question settings in a way that potentially affects the validity of existing responses **may cause all the existing responses for this question to be deleted**. Proceed?

**Comment by helloImHai** [comment]
@damithc Yes that sounds a lot better, lemme make the changes and push again

**Comment by helloImHai** [comment]
Changes are made, here are the new warning messages:

**Only visibility changes:**
Screenshot 2020-09-19 at 4 23 10 PM

**Only non-visibility changes:**
Screenshot 2020-09-19 at 4 23 26 PM

**Both types of changes:**
Screenshot 2020-09-19 at 4 23 49 PM

**Comment by helloImHai** [comment]
Hi I think this PR is ready to be reviewed

**Comment by xpdavid** [comment]
You seems to miss the case: When feedback path is changed, responses are definitely deleted?

**Comment by helloImHai** [comment]
Hi XP, sorry there may have been some miscommunication, I thought that this #10703 was only about the changing visibility? Should I add in the feedback path in this PR too?

**Comment by xpdavid** [comment]
> Should I add in the feedback path in this PR too?

If not too hard. Please add so.

**Comment by helloImHai** [comment]
Correct warning for changing feedback path added:
Screenshot 2020-09-20 at 11 32 36 PM

**Comment by damithc** [comment]
@helloImHai Keep in mind that all three types of changes can happen at the same time. Is that situation handled?

**Comment by helloImHai** [comment]
@damithc Hi Prof, I took into account the case that the changes can be made at the same time. For the 3 flags, `isVisibilityChanged`, `isChanged`, and `isFeedbackChanged`, the priority of the warning follows:
1. All responses will be deleted when `isFeedbackChanged` is set to true, 
2. Responses may be deleted when `isChanged` is set to true,
3. And, responses will not be deleted when `isVisibilityChanged` is set to true.

The warning rendered will follow the highest priority flag that is set to true.

To illustrate: 
| `isVisibilityChanged`  | `isChanged` | `isFeedbackChanged` | Warning |
| - | - | - | - |
| T |  F | F | Responses **will not be** deleted |
| ? | T | F | Responses **may be** deleted |
| ? | ? | T | Responses **will be** deleted |

**Comment by helloImHai** [comment]
An improvement I do want to make is to rename the `isChanged` variable to be more specific ie. `isQuestionDetailsChanged` but I do not know whether I should change code already written.

**Comment by damithc** [comment]
> @damithc Hi Prof, I took into account the case that the changes can be made at the same time.

Noted. Thanks for the clarification @helloImHai

**Comment by helloImHai** [comment]
Hi I think this PR is ready to be reviewd

**Comment by niqiukun** [comment]
> An improvement I do want to make is to rename the `isChanged` variable to be more specific ie. `isQuestionDetailsChanged` but I do not know whether I should change code already written.

My personal opinion is that you should go ahead and change it to avoid confusion for other developers.

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 1]
```diff
@@ -15,7 +15,26 @@ import { SimpleModalType } from '../simple-modal/simple-modal-type';
...
 
-const CLEAN_PROPERTIES: Set<string> = new Set<string>(['isEditable', 'isCollapsed', 'isChanged']);
+const FEEDBACK_PATH_PROPERTIES: Set<string> = new Set<string>([
+  'giverType',
+  'recipientType',
+  'isUsingOtherFeedbackPath',
+  'numberOfEntitiesToGiveFeedbackToSetting',
+  'customNumberOfEntitiesToGiveFeedbackTo',
+]);
+const VISIBILITY_PROPTERIES: Set<string> = new Set<string>([
```
Comment (niqiukun) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts:25]: Typo

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 2]
```diff
@@ -15,7 +15,26 @@ import { SimpleModalType } from '../simple-modal/simple-modal-type';
...
+  'isUsingOtherVisibilitySetting',
+  'showResponsesTo',
+  'showGiverNameTo',
+  'showRecipientNameTo',
+  'commonVisibilitySettingName',
+]);
+const CLEAN_PROPERTIES: Set<string> = new Set<string>([
+  ...VISIBILITY_PROPTERIES,
```
Comment (niqiukun) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts:33]: I wouldn't put visibilities inside clean properties because clean properties represent UI properties that does not affect the question at the backend. Visibilities do change the question at the backend.

**Review by niqiukun — CHANGES_REQUESTED** [review]

**Comment by helloImHai** [comment]
@niqiukun 
> My personal opinion is that you should go ahead and change it to avoid confusion for other developers.

> I wouldn't put visibilities inside clean properties because clean properties represent UI properties

In that case, to solve these 2 problems together, I'll keep the `isChanged` flag as it is, without redefining `CLEAN_PROPERTIES` then add a new `isQuestionDetailsChanged` and render the warnings according to that

**Comment by helloImHai** [comment]
Resolved comments:
- Removed all changes to `isChanged`
- Flags depends on whether there are changes to these fields:

| `isVisibilityChanged`  | `isQuestionDetailsChanged` | `isFeedbackChanged`|
| - | - | - |
| `isUsingOtherVisibilitySetting`, `showResponsesTo`, `showGiverNameTo`, `showRecipientNameTo`, `commonVisibilitySettingName` | `questionBrief`, `questionDescription`, `questionDetails`, `questionNumber`, | `giverType`, `recipientType`, `isUsingOtherFeedbackPath`, `numberOfEntitiesToGiveFeedbackToSetting`, `customNumberOfEntitiesToGiveFeedbackTo` |
 
Then, the warning will be rendered according to the table above.
>The warning rendered will follow the highest priority flag that is set to true.

Please help me take a look!

File: src/web/app/components/question-edit-form/question-edit-form-model.ts [hunk 3]
```diff
@@ -54,4 +54,7 @@ export interface QuestionEditFormModel {
   isSaving: boolean;
   isCollapsed: boolean;
   isChanged: boolean;
```
Comment (xpdavid) [inline src/web/app/components/question-edit-form/question-edit-form-model.ts:56]: Can we remove `isChanged` then?

**Review by xpdavid — COMMENTED** [review]
Looks good. Just one question

**Comment by helloImHai** [comment]
>Can we remove isChanged then?

Yes we can, and yes I think we should too. I was afraid that it would change some logic in the instructor session but it seems like it won't, I will push that change soon.
Can I also check that there's no way to edit question type right? Ie. If the instructor wants to change the question type, he/she will actually have to create a new question altogether?

**Comment by xpdavid** [comment]
> Can I also check that there's no way to edit question type right? Ie. If the instructor wants to change the question type, he/she will actually have to create a new question altogether?

Yes. Thanks for the changes

File: src/web/app/components/question-edit-form/question-edit-form.component.ts [hunk 4]
```diff
@@ -15,7 +15,26 @@ import { SimpleModalType } from '../simple-modal/simple-modal-type';
 import { collapseAnim } from '../teammates-common/collapse-anim';
 import { QuestionEditFormMode, QuestionEditFormModel } from './question-edit-form-model';
 
-const CLEAN_PROPERTIES: Set<string> = new Set<string>(['isEditable', 'isCollapsed', 'isChanged']);
+const FEEDBACK_PATH_PROPERTIES: Set<string> = new Set<string>([
```
Comment (xpdavid) [inline src/web/app/components/question-edit-form/question-edit-form.component.ts:18]: We can use a more strict type here (and similarly below)
```suggestion
const FEEDBACK_PATH_PROPERTIES: Set<keyof QuestionEditFormModel> = new Set<string>([
```

**Review by xpdavid — APPROVED** [review]

**Review by niqiukun — APPROVED** [review]
LGTM

File: src/web/app/components/question-edit-form/question-edit-form.component.ts (hunk 4 above)
Comment (helloImHai) [reply src/web/app/components/question-edit-form/question-edit-form.component.ts:18]: I think this change would not be compatible with the way we use the keys below,
`Object.keys(obj).some((key: string) => VISIBILITY_PROPERTIES.has(key))`
Where `key` is expected to be of type `string`, and not `keyof QuestionEditFormModel`? Maybe it's possible but I can't seem to get it to work.
We can do this to ensure the keys added in do not have typos tho, do you want me to proceed with this change?
`const FEEDBACK_PATH_PROPERTIES: Set<string> = new Set<keyof QuestionEditFormModel>([...`

Comment (xpdavid) [reply src/web/app/components/question-edit-form/question-edit-form.component.ts:18]: It's fine if it is difficult to do so
