### PR TITLE
[#10397] Create API for receiving all responses of a feedback question

### LINKED ISSUE #10588: Numerical scale question issues
2 issues here

1. Question saving is still successful despite the frontend validation error.
    1. The question submission page displays incorrect valid values prompts as well

image
image

2. Floating points aren't handled well (even when the question is valid)
    1. Range from [1, 8] with steps of 0.7
image

### PR DESCRIPTION
**Pull request by wkurniawan07**
This is the more important part of #10397 

- Created a new `PUT /responses` endpoint which takes in the list of responses for a particular question ID. The back-end will know which responses to update, delete, and create based on the list of responses given and the list of responses already existing in the DB.
  - All previous individual response APIs, namely `POST /response`, `PUT /response`, `DELETE /response`, are decommissioned
- Added question-wide validation for rank recipient and const sum recipient questions
- Removed usage of `numOfConstSumOption` which is problematic/redundant
  - ~Also removed the field itself in one of the commits, but this can be kept for a while longer~ Delayed to later, when it's safe to do so

And some quality of life improvements:
- Allowed erasing of answers; this was not working/buggy in many question types before
- Fixed #10588; while this issue is independent, because the validation logic has been moved, we might as well fix it here

The following things still need to be done (in future PR):
- Writing API tests; not done yet as I still want some feedback on the API design
- Deciding how to organize the error messages; whether to show all or partial or ...

### CODE REVIEW

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 1]
```diff
@@ -547,84 +549,63 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
...
+                        recipientSubmissionFormModel.responseId = correspondingResp.feedbackResponseId;
+                        recipientSubmissionFormModel.responseDetails = correspondingResp.responseDetails;
+                        recipientSubmissionFormModel.recipientIdentifier = correspondingResp.recipientIdentifier;
+                      } else {
+                        recipientSubmissionFormModel.responseId = '';
+                        recipientSubmissionFormModel.commentByGiver = undefined;
+                      }
+                    });
+              }),
+              // switchMap(() =>
```
Comment (wkurniawan07) [inline src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:596]: I skipped this because I wasn't very sure how this is supposed to work. Will take some time to add this back, @xpdavid if you can help it will be great.

File: src/main/java/teammates/ui/webapi/request/FeedbackResponseSubmissionRequest.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+import teammates.common.datatransfer.questions.FeedbackResponseDetails;
+import teammates.common.util.JsonUtils;
+
+/**
+ * The basic request of modifying a feedback response.
+ */
+public class FeedbackResponseSubmissionRequest extends BasicRequest {
+
+    private FeedbackQuestionType questionType;
+    private Map<String, Map<String, Object>> responseDetailsPerRecipient = new HashMap<>();
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/request/FeedbackResponseSubmissionRequest.java:17]: I don't recommend to use map as API request. It is too abstract and there is no way to tell the structure immediately even looking at the class itself.

Instead, I think it should accept a list of `FeedbackResponseRequest` where there are two field `recipientIdentifier ` and `responseDetails`.

File: src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+                FeedbackResponseAttributes feedbackResponse = existingResponsesPerRecipient.get(recipient);
+                feedbackResponse.giver = giverIdentifier;
+                feedbackResponse.giverSection = giverSection;
+                feedbackResponse.recipient = recipient;
+                feedbackResponse.recipientSection =
+                        getRecipientSection(feedbackQuestion.getCourseId(), feedbackQuestion.getGiverType(),
+                                feedbackQuestion.getRecipientType(), recipient);
+                feedbackResponse.responseDetails = responseDetails;
+
+                feedbackResponsesToValidate.add(feedbackResponse);
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java:150]: The above lines can be written as
```java
FeedbackResponseAttributes.UpdateOptions options = XXXX (Line 148 - 154)
FeedbackResponseAttributes updatedResponse = new FeedbackResponseAttributes(feedbackResponse);
updatedResponse.update(options)
feedbackResponsesToValidate.add(updatedResponse)
```

File: src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java [hunk 4]
```diff
@@ -0,0 +1,221 @@
...
+        for (FeedbackResponseAttributes feedbackResponse : feedbackResponsesToDelete) {
+            logic.deleteFeedbackResponseCascade(feedbackResponse.getId());
+        }
+
+        List<FeedbackResponseAttributes> output = new ArrayList<>();
+
+        for (FeedbackResponseAttributes feedbackResponse : feedbackResponsesToAdd) {
+            try {
+                FeedbackResponseAttributes createdFeedbackResponse = logic.createFeedbackResponse(feedbackResponse);
+                createdFeedbackResponse.setId(
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java:207]: Why we need set the ID manually? The ID should be updated correctly in the returned response. I believe the previous API is written before my improvement on DB layer.

File: src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts [hunk 5]
```diff
@@ -48,7 +48,11 @@ export class RubricQuestionEditAnswerFormComponent extends QuestionEditAnswerFor
       newAnswer = Array(this.questionDetails.numOfRubricSubQuestions).fill(RUBRIC_ANSWER_NOT_CHOSEN);
     }
 
-    newAnswer[subQuestionIndex] = answerIndex;
+    if (newAnswer[subQuestionIndex] === answerIndex) {
+      newAnswer[subQuestionIndex] = RUBRIC_ANSWER_NOT_CHOSEN;
```
Comment (xpdavid) [inline src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts:52]: I would add comment
```suggestion
      // select the same answer, toggle as unselected
      newAnswer[subQuestionIndex] = RUBRIC_ANSWER_NOT_CHOSEN;
```
