### PR TITLE
InstructorFeedbackResultsPageUiTest view photo test unstable #7082

### LINKED ISSUE #7082: InstructorFeedbackResultsPageUiTest view photo test unstable
**Environment**
Dev server at 34fc3e6

Main causes of failure in `testViewPhotoAndAjaxForLargeScaledSession`:

1. Expected `profile_picture_default.png`; got `studentProfilePic?studentemail={*}&courseid={*}&user=CFResultsUiT.instr`
    - due to the wrong popover being validated (multiple popovers open at once e.g. previous popover not fully dismissed yet); popover selector too general

1. `StaleElementReferenceException`
    - due to image changing from `ajax-loader.gif` to actual image midway through validation (after getting element before getting attribute, as explained [here](http://darrellgrainger.blogspot.sg/2012/06/staleelementexception.html))

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7082

Pending stability measure (basically running the Travis build multiple times and counting successes and failures). Will update below.

**Outline of Solution**

- Use specific selectors for popovers (avoids validating the wrong popover)
- Don’t dismiss popovers (unnecessary due to usage of more specific selectors; can help prevent stale element exceptions)
- Retry once upon stale element exception (handles loading gif transforming into actual image)

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Looks like it's working. I hope none of them are green after restart?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 1]
```diff
@@ -341,66 +341,51 @@ public void clickAjaxNoResponsePanel() {
         click(ajaxPanels);
     }
 
+    // Build #10
+
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Remove these lines?

**Comment by whipermr5** [comment]
@wkurniawan07 Yup didn't have to restart anything :) Okay thanks! Will test it a few more times first just to be sure.

**Comment by basitsattar** [comment]
My[ travis ci build](https://travis-ci.org/TEAMMATES/teammates/builds/220344087) is failing for the same reason. Waiting for your solution to be merged.
