### PR TITLE
FieldValidator: fix error in message #7349

### LINKED ISSUE #7349: FieldValidator: fix error in message
The characters banned in `NON_HTML_FIELD_ERROR_MESSAGE` are `< > " / ' &` while backslash is allowed, so the backslash `\\` should be replaced with a double quote `\"` in the message.

### PR DESCRIPTION
**Pull request by sneachta96**
Fixes #7349

### CODE REVIEW

**Comment by leeyimin** [comment]
@sneachta96 Thank you for contributing to TEAMMATES! Seems like you have already made the right changes to FieldValidator. You would need to update the failing tests accordingly so that the build can pass :)

**Comment by sneachta96** [comment]
@leeyimin Okay. But could you elaborate a little bit on what i have to do?
thank you :)

**Comment by chowyb** [comment]
@sneachta96 you'll have to use [GodMode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) to update the failing tests.

**Comment by sneachta96** [comment]
hey @chowyb  , thank you :) i looked it up. But how can i enable/activate it ? Also does updating failing tests mean looking for the failing tests or working on already existing ones? 
Thank you in advance

**Comment by chowyb** [comment]
@sneachta96 you can activate it following the instructions [here](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md#how-do-we-use-godmode), but basically you can set a boolean value `isGodModeEnabled` in `BaseUiTestCase` to `true` to activate it, but remember to change it back later.

Updating failing tests would mean looking for the failing tests from the Travis log (which you can view by clicking the red 'x' beside your commits), and then running those tests on your own machine with GodMode enabled.

**Comment by sneachta96** [comment]
hey @chowyb :) Although i could enable it, i still haven't been able to figure out to run in this mode. Please help ..I am not able to go ahead with anything.
thank you :)

**Comment by leeyimin** [comment]
@sneachta96 Have you managed to set up the development server? You would need to start your development server, turn on godmode through BaseUiTestCase, and run the Ui tests which are failing on Travis.

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 1]
```diff
@@ -263,7 +263,7 @@ private void testCreateAndDeleteFeedbackSession() throws InvalidParametersExcept
         } catch (Exception e) {
             assertEquals("The provided feedback session name is not acceptable to TEAMMATES "
                              + "as it cannot contain the following special html characters in brackets: "
-                             + "(&lt; &gt; \\ &#x2f; &#39; &amp;)",
+                             + "(&lt; &gt; \" &#x2f; &#39; &amp;)",
```
Comment (chowyb) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: Replace `\"` with `&quot;` here.

File: src/test/java/teammates/test/cases/util/FieldValidatorTest.java [hunk 2]
```diff
@@ -96,12 +96,12 @@ public void testGetValidityInfoForNonHtmlField_sanitizedInput_returnEmptyString(
...
     @Test
     public void testGetValidityInfoForNonHtmlField_unsanitizedInput_returnErrorString() {
-        String unsanitizedInput = "Invalid unsanitized input <>\\/'&";
+        String unsanitizedInput = "Invalid unsanitized input <>\"/'&";
         String testFieldName = "Inconsequential test field name";
         String actual = validator.getValidityInfoForNonHtmlField(testFieldName, unsanitizedInput);
         assertEquals("Invalid unsanitized input should return error string",
                      "The provided Inconsequential test field name is not acceptable to TEAMMATES as it "
-                         + "cannot contain the following special html characters in brackets: (&lt; &gt; \\ "
+                         + "cannot contain the following special html characters in brackets: (&lt; &gt; \" "
```
Comment (chowyb) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: Replace `\"` with `&quot;` here too.

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 3]
```diff
@@ -263,7 +263,7 @@ private void testCreateAndDeleteFeedbackSession() throws InvalidParametersExcept
         } catch (Exception e) {
             assertEquals("The provided feedback session name is not acceptable to TEAMMATES "
                              + "as it cannot contain the following special html characters in brackets: "
-                             + "(&lt; &gt; \\ &#x2f; &#39; &amp;)",
+                             + "(&lt; &gt; &quot &#x2f; &#39; &amp;)",
```
Comment (chowyb) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: This has to be `&quot;` (with the semicolon); the same applies for the one in `FieldValidatorTest.java`

**Comment by chowyb** [comment]
@sneachta96 going back to the changes in 4d2df30 should be fine; the tests there are failing due to a separate issue (#7365).

**Comment by sneachta96** [comment]
@leeymin thank you so much . :) i did manage to do so .

**Comment by sneachta96** [comment]
hey :)
there is one problem i am facing while trying to run "./gradlew appengineRun"
i get
 FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to establish loopback connection
Could you help ?
Thank you

**Comment by sneachta96** [comment]
Hey :) 
Could you please guide me with the above mentioned problem ..? I have been trying to sort it out but can't . I can't run the application because of it. Please help so that I can go ahead .
Thank you

**Comment by whipermr5** [comment]
> java.io.IOException: Unable to establish loopback connection

Does your user have sufficient privileges to run a server that binds to port 8888?

**Comment by sneachta96** [comment]
@whipermr5  hey, i was trying this again but did not get the loopback connection issue. However, now it shows "http port 8888 already in use" when is try to 

> ./gradlew appengineRun

**Comment by whipermr5** [comment]
@sneachta96 Find out which other program is binding to that port, and terminate it.

**Comment by sneachta96** [comment]
@whipermr5  hey thanks. :) got it running finally.

**Comment by whipermr5** [comment]
@sneachta96 Any updates here? :)

**Comment by sneachta96** [comment]
@whipermr5  I had made the appropriate changes but the test cases were failing due to issue #7365 as mentioned by @chowyb in one of the previous replies. And that issue seemed to have closed. So what i need to do next ? 
Thank you .

**Comment by whipermr5** [comment]
@sneachta96 Pull in the latest master and re-run the test with GodMode :)

File: src/test/java/teammates/test/cases/util/FieldValidatorTest.java [hunk 4]
```diff
@@ -96,13 +96,13 @@ public void testGetValidityInfoForNonHtmlField_sanitizedInput_returnEmptyString(
...
-        String unsanitizedInput = "Invalid unsanitized input <>\\/'&";
+        String unsanitizedInput = "Invalid unsanitized input <>\"/'&";
         String testFieldName = "Inconsequential test field name";
         String actual = validator.getValidityInfoForNonHtmlField(testFieldName, unsanitizedInput);
         assertEquals("Invalid unsanitized input should return error string",
                      "The provided Inconsequential test field name is not acceptable to TEAMMATES as it "
-                         + "cannot contain the following special html characters in brackets: (&lt; &gt; \\ "
-                         + "&#x2f; &#39; &amp;)",
+                         + "cannot contain the following special html characters in brackets: (&lt; &gt; &quot;" +
+			 "&#x2f; &#39; &amp;)",
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: The `+` should be moved to this line.

File: src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java [hunk 5]
```diff
@@ -263,7 +263,7 @@ private void testCreateAndDeleteFeedbackSession() throws InvalidParametersExcept
         } catch (Exception e) {
             assertEquals("The provided feedback session name is not acceptable to TEAMMATES "
                              + "as it cannot contain the following special html characters in brackets: "
-                             + "(&lt; &gt; \\ &#x2f; &#39; &amp;)",
+                             + "(&lt; &gt; &quot;"+" &#x2f; &#39; &amp;)",
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java]: The `"+"` is unnecessary.

**Comment by whipermr5** [comment]
@sneachta96 Build is failing due to tabs and trailing spaces.

File: src/test/java/teammates/test/cases/util/FieldValidatorTest.java [hunk 6]
```diff
@@ -84,7 +84,8 @@ public void testGetValidityInfoForNonHtmlField_cleanInput_returnEmptyString() {
         String actual = validator.getValidityInfoForNonHtmlField(testFieldName, clean);
         assertEquals("Valid clean input with no special HTML characters should return empty string", "",
                      actual);
-    }
+    }:x
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: Compile error coming soon

File: src/test/java/teammates/test/cases/util/FieldValidatorTest.java [hunk 7]
```diff
@@ -96,12 +96,12 @@ public void testGetValidityInfoForNonHtmlField_sanitizedInput_returnEmptyString(
...
     @Test
     public void testGetValidityInfoForNonHtmlField_unsanitizedInput_returnErrorString() {
-        String unsanitizedInput = "Invalid unsanitized input <>\\/'&";
+        String unsanitizedInput = "Invalid unsanitized input <>\"/'&";
         String testFieldName = "Inconsequential test field name";
         String actual = validator.getValidityInfoForNonHtmlField(testFieldName, unsanitizedInput);
         assertEquals("Invalid unsanitized input should return error string",
-                     "The provided Inconsequential test field name is not acceptable to TEAMMATES as it "
-                         + "cannot contain the following special html characters in brackets: (&lt; &gt; \\ "
+                     "The provided Inconsequential test field name is not acceptable to TEAMMATES as it"
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: Space after `it` otherwise it'll show up as `itcannot`

File: src/test/java/teammates/test/cases/util/FieldValidatorTest.java [hunk 8]
```diff
@@ -96,12 +96,12 @@ public void testGetValidityInfoForNonHtmlField_sanitizedInput_returnEmptyString(
...
+                         + "cannot contain the following special html characters in brackets: (&lt; &gt; &quot;"
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: Same here: needs a space after `&quot;`

Comment (sneachta96) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: Can i modify the expected string using trim() to remove the trailing spaces?
Thank you :)

Comment (whipermr5) [inline src/test/java/teammates/test/cases/util/FieldValidatorTest.java]: No; that is an unrelated change. Also, it's not a trailing space - it's a space in between the `&quot;` and `&#x2f;`. When you `+` two strings together, it gets joined into one string without adding a space in between.

**Comment by whipermr5** [comment]
Thanks for your contribution, @sneachta96! Do note our PR title and branch name conventions for future PRs - there were some deviations but it's fine as this is your first time :)

**Comment by sneachta96** [comment]
@whipermr5 hey , thank you for the help. And I would take care about the conventions.
I have  a small thing to ask. I am not able to login as an admin locally. It shows "The page you are looking for is not there" . Also when i try to open admin/adminHomePage, it asks to add an instructor and then again can not go anywhere from there.
Could you help?
Thank you :)

**Comment by whipermr5** [comment]
@sneachta96 Take a look at the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) :)

**Comment by sneachta96** [comment]
@whipermr5  yes, i have . But opening the join link url (changed base)shows " you are not authorized to view this page" .

**Comment by whipermr5** [comment]
@sneachta96 You need to logout before opening the join link.

**Comment by sneachta96** [comment]
It does not help :( . the activity log shows "Action Failure : You have used an invalid join link: /page/instructorCourseJoin?key=F2AD69F8994BA92C8D605BAEDB35949A41E71A573721C8D60521776714DE0BF8B0860F12DD19C6B955F735D8FBD0D289 "

**Comment by whipermr5** [comment]
Try creating another instructor, copy the link, change the hostname, and open it in an incognito window (or in another browser).

**Comment by sneachta96** [comment]
I am sorry , but still no help. :(

**Comment by whipermr5** [comment]
Do take some screenshots and post them here :)

**Comment by sneachta96** [comment]
a
b

Hey, Sorry for such a late reply .
This is when i try to login directly.

**Comment by sneachta96** [comment]
On directly opening the admin home page, i get Add instructor page.
b

On adding the instructor and After logging out, i try to open the join link.
d

Get this.
a



Finally , when i click , This is my account.
c

Same thing happens when trying incognito .

**Comment by whipermr5** [comment]
The first one is not an issue as it's caused by going to an invalid URL (`/admin` was never meant to be a valid URL). For the second one, can you screenshot the add instructor success message with the course join link?

**Comment by sneachta96** [comment]
I did not get any such success message.

**Comment by whipermr5** [comment]
> On directly opening the admin home page, i get Add instructor page.

Please use the join link shown on this page after adding the instructor. The link shown in the documentation is an example.

**Comment by sneachta96** [comment]
No join link or success message appears after clicking "Add Instructor".

**Comment by whipermr5** [comment]
Have you run `npm run build`?

**Comment by sneachta96** [comment]
l

Hey, I tried setting up again ..and now i got it . I guess there was some problem in the set up.
Thank you so much for the help and being so patient , really appreciate it .:)

**Comment by thenaesh** [comment]
@sneachta96 May we know your name, so that we can add you into our list of contributors?

**Comment by sneachta96** [comment]
@thenaesh  hey, :) Sure ..its Jasmeet Kaur.
