### PR TITLE
[#12499] Flickering questions when loading session results

### LINKED ISSUE #12499: Flickering questions when loading sessions results
- **Environment**: master

**Steps to reproduce**

- Go to instructor home page
- Select the first session of the demo course
- Select "View results (from/to me)"

image

**Expected behaviour**
 
- There should be no flickering 

**Actual behaviour**

https://github.com/Zxun2/teammates/assets/63457492/1e5b68cc-5bec-4f07-aa57-e3837ec1847b

**Additional info**

- The questions defaults to `hasResponse: true` which causes the bug

### PR DESCRIPTION
**Pull request by blejkowski**
Fixes #12499

Changed the hasResponse field to be false by default. Now the questions won't show up briefly and then be hidden due to not having responses. 

Previous:
https://user-images.githubusercontent.com/63457492/247068301-1e5b68cc-5bec-4f07-aa57-e3837ec1847b.mp4

New:
https://github.com/TEAMMATES/teammates/assets/83157275/592b008d-9290-4ecb-b6dc-af993ee0f710

### CODE REVIEW

**Comment by blejkowski** [comment]
Ready for review.

**Review by cedricongjh — APPROVED** [review]
LGTM, thank you for your contribution to TEAMMATES!

File: src/web/app/components/question-response-panel/question-response-panel.component.ts [hunk 1]
```diff
@@ -104,13 +105,11 @@ export class QuestionResponsePanelComponent {
           question.responsesToSelf = responses.responsesToSelf;
           question.hasResponseButNotVisibleForPreview = responses.hasResponseButNotVisibleForPreview;
           question.hasCommentNotVisibleForPreview = responses.hasCommentNotVisibleForPreview;
-        } else {
-          question.hasResponse = false;
-          if (question.errorMessage) {
-            this.statusMessageService.showSuccessToast('Question '
-              .concat(question.feedbackQuestion.questionNumber.toString())
-              .concat(' has no responses.'));
-          }
```
Comment (jasonqiu212) [inline src/web/app/components/question-response-panel/question-response-panel.component.ts:113]: I think it will be best to keep this `else` statement for defensive coding practices. 

The original logic with the `else` ensures that if `responses` is truthy, `if (question.errorMessage) { ... }` will definitely not be evaluated and run. If we remove the `else`, it is possible to display the error message, even if `responses` is truthy, though it probably will not happen. However, let's avoid this situation completely by keeping the original logic.

Feel free to let me know what you think about this!

Comment (blejkowski) [reply src/web/app/components/question-response-panel/question-response-panel.component.ts:113]: That makes sense to me, thank you for the feedback.

**Review by jasonqiu212 — APPROVED** [review]
LGTM!
