### PR TITLE
[#10509] [#10524] [#10525] [#10535] Add loading indicators when fetching data

### LINKED ISSUE #10509: Instructor sessions page: Incorrect intermediate state shown while loading data
image

### LINKED ISSUE #10524: Instructor preview session as student: incorrect state shown while loading
image

After clicking this button, the next page shows incorrect intermediate state while waiting for the final state.

### LINKED ISSUE #10525: Instructor copy question: no loading indicator
There is no indication of work-in-progress after clicking on this button. As I have a lot of questions, the modal took about 5 seconds to appear.
image

In V6, the modal appears immediately and a spinner is shown inside the modal while waiting for the data.

### LINKED ISSUE #10535: Instructor moderate responses: incorrect state shown during loading
After clicking this button, the next page shows an incorrect state while loading data.
image

### PR DESCRIPTION
**Pull request by madanalogy**
Fixes #10509 
Fixes #10524 
Fixes #10525 
Fixes #10535 

For all mentioned issues, loading indicators were added to properly reflecting the fetching of data. Refer to commit history for indicators relating to the corresponding issues.

### CODE REVIEW

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 1]
```diff
@@ -251,65 +254,66 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
       key: this.regKey,
       moderatedPerson: this.moderatedPerson,
       previewAs: this.previewAsPerson,
-    }).subscribe((feedbackSession: FeedbackSession) => {
-      this.feedbackSessionInstructions = feedbackSession.instructions;
-      this.formattedSessionOpeningTime = this.timezoneService
+    }).pipe(finalize(() => this.hasFeedbackSessionLoaded = true))
```
Comment (t-cheepeng) [inline src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:257]: Just a minor thing:

Would `isFeedbackSessionLoading` be a better name? When i did the indicators, the variable naming for loading i adopted was `isSomethingLoading` since the directive is `tmIsLoading`

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts [hunk 2]
```diff
@@ -887,6 +888,7 @@ export class InstructorSessionEditPageComponent extends InstructorSessionBasePag
     ).subscribe((questionToCopyCandidate: QuestionToCopyCandidate[]) => {
       questionToCopyCandidates.push(...questionToCopyCandidate);
     }, (resp: ErrorMessageOutput) => { this.statusMessageService.showErrorToast(resp.error.message); }, () => {
+      this.isCopyingQuestion = false;
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:891]: Why `isCopyingQuestion` is set only when there is error message?

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 3]
```diff
@@ -391,6 +396,7 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
             responseId: '',
           });
         });
+        this.isFeedbackSessionQuestionResponsesLoading = false;
```
Comment (xpdavid) [inline src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:399]: You should set `isFeedbackSessionQuestionResponsesLoading` to `true` somewhere?

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts [hunk 4]
```diff
@@ -320,6 +324,7 @@ export class SessionSubmissionPageComponent implements OnInit, AfterViewInit {
       previewAs: this.previewAsPerson,
     }).pipe(finalize(() => this.isFeedbackSessionQuestionsLoading = false))
         .subscribe((response: FeedbackQuestionsResponse) => {
+          if (response.questions.length === 0) { this.isFeedbackSessionQuestionResponsesLoading = false; }
```
Comment (xpdavid) [inline src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:327]: Why it is set when the length is zero?

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts (hunk 2 above)
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:891]: Why `isCopyingQuestion` is set only when there is error message?

Comment (madanalogy) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:891]: It's not the error callback, it's in the `complete` callback. See https://angular.io/guide/observables#defining-observers

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts (hunk 4 above)
Comment (madanalogy) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:327]: Because then `this.loadFeedbackQuestionRecipientsForQuestion()` is never called

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts (hunk 3 above)
Comment (madanalogy) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:399]: It's initialised as `true`

File: src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts (hunk 2 above)
Comment (ccyccyccy) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:891]: I don't think `complete` will be called after `error`? https://stackoverflow.com/questions/33783967/rxjs-observable-doesnt-complete-when-an-error-occurs

Think `finalize` is better.

Comment (madanalogy) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:891]: But then we run into the problem you raised previously about there being additional loading before the modal pops up. That loading is the copying within the subscription and finalise is called at the end of the pipe instead of at the end of the subscription operation. 

You're also right though that complete won't be called on error, so I'll put in the toggle into the error block as well.

Comment (ccyccyccy) [reply src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts:894]: The additional loading I mentioned was due to the fetching of the intents. Your old implementation works, just that you need to put the `finalize` after `flatMap`. See https://stackoverflow.com/questions/54567073/finalize-with-flatmap-in-angular.

File: src/web/app/pages-session/session-submission-page/session-submission-page.component.ts (hunk 3 above)
Comment (xpdavid) [reply src/web/app/pages-session/session-submission-page/session-submission-page.component.ts:399]: We should not depends on the initial values of component. `true` need to set properly when the loading actually begins.
