### PR TITLE
FeedbackQuestionsLogic: Refactor methods with response rate check #4838

### LINKED ISSUE #4838: FeedbackQuestionsLogic: Refactor methods with response rate check
`updateFeedbackQuestion(FeedbackQuestionAttributes)` edits an existing feedback question without updating the response rate. It should be made private to prevent developers from using it incorrectly. `updateFeedbackQuestionWithResponseRateCheck(FeedbackQuestionAttributes)` is more suitable for updating a feedback question.

### PR DESCRIPTION
**Pull request by unyoungwax**
Fixes #4838

### CODE REVIEW

File: src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java [hunk 1]
```diff
@@ -607,18 +607,18 @@ private void adjustQuestionNumbers(int oldQuestionNumber,
...
+     * {@code newAttributes}, the existing value is preserved if the attribute
+     * is null (due to 'keep existing' policy). Existing responses for the
+     * question are automatically deleted if giverType/recipientType are
+     * changed, or if the response visibility is increased. However, the
+     * response rate of the feedback session is not updated.<br>
+     * Precondition: <br>
+     * {@code newAttributes} is not {@code null}
      */
-    public void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes)
+    private void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes)
```
Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: @unyoungwax, I propose that we rename this method to <code>updateFeedbackQuestionWithoutResponseRateUpdate</code>, and rename <code>updateFeedbackQuestionWithResponseRateCheck</code> to <code>updateFeedbackQuestion</code>. 

Updating the response rate so that it's actually correct seems to be what I would expect as default behaviour for a method to update the question. Not updating the response rate should be the exceptional behaviour. 

You may also need to add/modify the header comments for the public method, since the header comment here is fixed.

**Comment by unyoungwax** [comment]
I have renamed the methods and also removed unused method `updateFeedbackQuestionWithResponseRateCheck` in `Logic`.

File: src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java [hunk 2]
```diff
@@ -607,24 +607,34 @@ private void adjustQuestionNumbers(int oldQuestionNumber,
...
+     * {@code newAttributes}, the existing value is preserved if the attribute
+     * is null (due to 'keep existing' policy). Existing responses for the
+     * question are automatically deleted if giverType/recipientType are
+     * changed, or if the response visibility is increased. However, the
+     * response rate of the feedback session is not updated.<br>
+     * Precondition: <br>
+     * {@code newAttributes} is not {@code null}
      */
-    public void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes)
+    private void updateFeedbackQuestionWithoutResponseRateCheck(FeedbackQuestionAttributes newAttributes)
```
Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: @unyoungwax, is the name <code>updateFeedbackQuestionWithoutResponseRateCheck</code> accurate though? A <code>check</code> actually sounds like it doesn't result in a change in the database values.

Comment (unyoungwax) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: There are variables (e.g. `hasResponseRateCheck`) and also a method (`deleteFeedbackQuestionCascadeWithResponseRateCheck`) that are named similarly  in `FeedbackQuestionsLogic`, should I rename them as well?

Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: @unyoungwax, I think we can rename them in this issue. Perhaps we can change the issue name to reflect the slightly broader scope of the change. 

Alternatively, it could be made as a new issue, which can be labeled d.FirstTimers, if you think that will be better.

**Comment by unyoungwax** [comment]
I have made similar changes to `deleteFeedbackQuestion` so that the names of the methods in `FeedbackQuestionsLogic` are consistent.

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 3]
```diff
@@ -671,7 +671,7 @@ public void deleteFeedbackResponsesForQuestionAndCascade(
             emails.add(response.giverEmail);
         }
 
-        if(!hasResponseRateCheck){
+        if(!hasResponseRateUpdate){
```
Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java]: @unyoungwax, not related to your changes, but since you touched this line, let's fix the indentation here :P

File: src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java [hunk 4]
```diff
@@ -607,31 +607,41 @@ private void adjustQuestionNumbers(int oldQuestionNumber,
...
+     */
+    public void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes)
             throws InvalidParametersException, EntityDoesNotExistException {
 
         updateFeedbackQuestion(newAttributes, true);
     }
 
 
-    public void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes, boolean hasResponseRateCheck)
+    public void updateFeedbackQuestion(FeedbackQuestionAttributes newAttributes, boolean hasResponseRateUpdate)
```
Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: @unyoungwax, are we able to make this private too?

**Comment by kanghj** [comment]
@unyoungwax, added some minor comments. It should be fine after this

File: src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java (hunk 4 above)
Comment (unyoungwax) [inline src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java]: Yes, `updateFeedbackQuestion` and `deleteFeedbackQuestionCascade` with parameter `hasResponseRateUpdate` can be made private.

File: src/main/java/teammates/logic/api/Logic.java [hunk 5]
```diff
@@ -1825,17 +1825,9 @@ public void updateFeedbackQuestion(FeedbackQuestionAttributes updatedQuestion)
...
-        Assumption.assertNotNull(ERROR_NULL_PARAMETER, updatedQuestion);
-        feedbackQuestionsLogic.updateFeedbackQuestionWithResponseRateCheck(updatedQuestion);
-    }
-    
     /**
-     * Deletes the feedback session but not the questions and
-     * responses associated to it.
-     * Fails silently if no such feedback session. <br>
+     * Deletes the feedback question and the responses associated to it. Fails
+     * silently if there is no such feedback session. <br>
```
Comment (kanghj) [inline src/main/java/teammates/logic/api/Logic.java]: @unyoungwax, oops, minor change here: <code>...if there is no such feedback session</code> should be <code>...if there is no such feedback question</code>

**Comment by unyoungwax** [comment]
I have corrected the comment of `deleteFeedbackQuestion` in `Logic`.
