### PR TITLE
Replace raw exception throws in production code #7085

### LINKED ISSUE #7085: Replace raw exception throws in production code
> There is a rule in `PMD` named `AvoidThrowingRawExceptionTypes` and it indicates that throwing raw exception types is not a practice in software engineering. We may want to use `Assumption.assert*` rather than throwing raw exceptions in the production code. Therefore, we should change all RuntimeException to make use of `Assumption` class for production code.

image
For example, we should use `Assumption.assert*` here.

Three Tasks here.
1. Add `<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes"/>` to `teammates-pmdMain.xml`
2. Fix violations reported by PMD (Make use of `Assumption.assert` instead)
3. Remove `TODO` if it is necessary (Like the example above)

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #7085

@xpdavid Please have a look. 

**Outline of Solution**

- Added `<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes"/>` rule.
- Fixed violations using `Assumption.fail(message)` with `return null` ( dummy return, whenever necessary)
- Assumption.assert*(message, condition) whenever possible

Regarding the second point, I had a look at @AnaghHegde 's comment on his PR #7150 and realized that `fail(String)` calls `AssertionError()` which is infact better than throwing `RunTimeException()` as suggested through this [answer](https://stackoverflow.com/a/41324002/7877626)

Edit: Noticed after running the tests, using fail() might not be a good thing because there are tests which fail due to `AssertionErrors` now(Fixed the tests now by catching `AssertionErrors`)

### CODE REVIEW

**Comment by tshradheya** [comment]
Ready for Review @xpdavid

File: src/test/java/teammates/test/cases/action/InstructorHomePageActionTest.java [hunk 1]
```diff
@@ -142,8 +142,8 @@ public void testExecuteAndPostProcess() throws Exception {
         try {
             a = getAction(addUserIdToParams(instructorWithMultipleCourses, submissionParams));
             r = getShowPageResult(a);
-            signalFailureToDetectException("The run time exception is not thrown as expected");
-        } catch (RuntimeException e) {
+            signalFailureToDetectAssertionError("The run time exception is not thrown as expected");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/InstructorHomePageActionTest.java]: You need change the message :P

Should not be `The run time exception is not thrown as expected` anymore

File: src/test/java/teammates/test/cases/BaseTestCase.java [hunk 2]
```diff
@@ -75,6 +75,10 @@ protected void signalFailureToDetectException(String... messages) {
         throw new RuntimeException("Expected exception not detected." + Arrays.toString(messages));
     }
 
+    protected void signalFailureToDetectAssertionError(String... messages) {
+        throw new AssertionError("Expected exception not detected." + Arrays.toString(messages));
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCase.java]: Should be `RuntimeException` rather than `RuntimeException` (and therefore, there is no need to add this method)

If you still throw `AssertionError`, the catch block will catch it (and think it is the `AssertionError` thrown by the method under test) and the test won't fail.

File: src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java [hunk 3]
```diff
@@ -43,7 +44,7 @@ public void execute() {
         try {
             emailSender.sendEmail(email);
         } catch (Exception e) {
-            throw new RuntimeException("Unexpected error while sending email", e);
+            Assumption.fail("Unexpected error while sending email" + TeammatesException.toStringWithStackTrace(e));
```
Comment (xpdavid) [inline src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java]: Will this affect the exception stack? If an exception happens in the LIVE server, can we trace down to the root cause?

File: src/main/java/teammates/common/util/Config.java [hunk 4]
```diff
@@ -64,7 +64,7 @@
         try {
             properties.load(FileHelper.getResourceAsStream("build.properties"));
         } catch (IOException e) {
-            throw new RuntimeException(e);
+            Assumption.fail(e.toString());
```
Comment (xpdavid) [inline src/main/java/teammates/common/util/Config.java]: `e.toString()` sometimes cannot give you root cause

File: src/test/java/teammates/test/cases/BaseTestCase.java (hunk 2 above)
Comment (tshradheya) [reply src/test/java/teammates/test/cases/BaseTestCase.java]: >Should be RuntimeException rather than RuntimeException (and therefore, there is no need to add this method)

I don't get this?

File: src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java (hunk 3 above)
Comment (tshradheya) [reply src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java]: Is there anyway I can check this?

Assumption.fail() eventually throws `AssertionError`, so the exception stack will still be useful in tracing down the root cause. [ If there is a way to check, please let me know so that I can confirm ]

File: src/test/java/teammates/test/cases/BaseTestCase.java [hunk 5]
```diff
@@ -75,6 +75,10 @@ protected void signalFailureToDetectException(String... messages) {
         throw new RuntimeException("Expected exception not detected." + Arrays.toString(messages));
     }
 
+    protected void signalFailureToDetectAssertionError(String... messages) {
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/BaseTestCase.java]: Look at the existing method `signalFailureToDetectException`, your method is doing the same thing.

**Comment by tshradheya** [comment]
Removed the redundant function and gave more meaningful message to its calls.

Ready for Review

**Comment by tshradheya** [comment]
Failing tests due to throwing of `RuntimeException` in #8235 . 
On looking at the conversation in the PR as to why a regular exception is not thrown, it is apparently because of transactions. 
@whipermr5 Can I confirm that there is no other way than to throw RuntimeException? 

If there is no way, I can add the Supresswarning in the 4 places where this has been used due to transactions.

**Comment by xpdavid** [comment]
@tshradheya Go ahead and suppress them. Also, remember to indicate the reasons for suppressing them.

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 6]
```diff
@@ -184,6 +184,7 @@ public void addInstructorRespondent(String email, FeedbackSessionAttributes feed
         addInstructorRespondents(emails, feedbackSession);
     }
 
+    @SuppressWarnings("PMD.AvoidThrowingRawExceptionTypes") //Transactions do not support throwing checked exceptions
```
Comment (xpdavid) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: It is not transactions do not support. Should be `// The objectify library does not support throwing checked exceptions inside transactions`

**Comment by tshradheya** [comment]
Ready for Review
