### PR TITLE
Random test fail in *LogicTest.java recently #6777

### LINKED ISSUE #6777: Random test fail in *LogicTest.java recently
There are test failures on Travis or Appveyor for `*Logic` recently. This may be caused by #6655, which use `dependsOnGroup` to control the order of test cases.

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #6777

**Possible Reason**
I guess maybe testNG takes too much time to figure out the dependency (`dependsOnGroups = "..."`) and thus result in test case failures?

**Outline of Solution**

> 1. AdminActivityLogPageActionTest: change `dependsOnGroups` to `priority`
> 1. In testNG, `priority` starts from `0`, which is the highest priority. Note that I use `priority=2` instead of `priority=1` for better understanding as some developers may think it start from `1`. And actually, as long as the `manyLogs` group run separately from `typicalLogs` group. You can set any priority that bigger or equal to 1.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
The change looks good, but I need to re-run it 2-3 more times to make sure that the problem's indeed gone.
(and I see you've re-run it once, that's great!)

File: src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java [hunk 1]
```diff
@@ -379,7 +379,7 @@ public void removeAndRestoreManyLogs() {
                 today.getTime(), LOG_MESSAGE_INTERVAL_MANY_LOGS);
     }
 
-    @Test(groups = "manyLogs", dependsOnGroups = "typicalLogs")
+    @Test(groups = "manyLogs", priority = 2)
```
Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java]: Should we add a comment to explain why this is 2?

Comment (xpdavid) [inline src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java]: I would expect developers to know the `priority` in TestNG and thus they will quickly know that this test will fun after test without priority (default highest priority = 0).

In fact, `priority` is widely used for test cases in Teammates (action test, driver test, etc.).

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java]: @xpdavid you unknowingly just opened another can of worms :snake:

Comment (damithc) [inline src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java]: I didn't mean that. Rather, the fact that this needs to be `>1` to avoid {whatever you are trying to avoid}.
