### PR TITLE
instructorFeedbackResultsPage: "Collapse students" button does not work correctly when not grouped by question #5911

### LINKED ISSUE #5911: instructorFeedbackResultsPage: "Collapse students" button does not work correctly when not grouped by question
On a non-question view like 'Giver > Recipient > Question', and when the students are not grouped by teams, the "Collapse Students" button does not work correctly on participants who have not responded (the grey panels). The cause of this is code duplication in `instructorFeedbackResults.js` and the js files for ajax loading.

### PR DESCRIPTION
**Pull request by belyabl9**
Fixes #5911

### CODE REVIEW

**Comment by belyabl9** [comment]
Ready to review

File: src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js [hunk 1]
```diff
@@ -67,7 +67,9 @@ $(document).ready(function() {
                 $('a[id^="collapse-panels-button-section-"],a[id^="collapse-panels-button-team-"]').off('click');
                 $('a[id^="collapse-panels-button-section-"]').on('click', function() {
                     var isGroupByTeam = $('#frgroupbyteam').prop('checked');
-                    var childPanelType = isGroupByTeam ? 'div.panel.panel-warning' : 'div.panel.panel-primary';
```
Comment (kanghj) [inline src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js]: Instead of duplicating the fix to 4 different files, can you explore using delegated events in `instructorFeedbackResults.js`? Most of the duplicate code regarding this section button can be removed in this PR.

**Comment by kanghj** [comment]
Also, are we able to test this?

**Comment by belyabl9** [comment]
@kanghj , good idea, I'll try delegating events

**Comment by belyabl9** [comment]
@kanghj , I've added test for not grouped by team case.
Ready to review

File: src/main/webapp/js/instructorFeedbackResults.js [hunk 2]
```diff
@@ -291,7 +291,7 @@ $(document).ready(function() {
         toggleCollapse(this, panels);
     });
 
-    $('a[id^="collapse-panels-button-team-"]').on('click', function() {
+    $('.panel.panel-success').on('click', 'a[id^="collapse-panels-button-team-"]', function() {
```
Comment (kanghj) [inline src/main/webapp/js/instructorFeedbackResults.js]: Just to check, should line 279 (`$('a[id^="collapse-panels-button-section-"]').on('click',`) be modified too?

Comment (belyabl9) [inline src/main/webapp/js/instructorFeedbackResults.js]: No, it shouldn't, because those buttons are loaded with the page, while "collapse-panels-button-team-*" are loaded asynchronously
