### PR TITLE
 Instructor: Edit session : Distribute (Options) question : Points per option button stays hidden #8603

### LINKED ISSUE #8603: Instructor: Edit session : Distribute (Options) question : Points per option button stays hidden
**Environment**
`master` branch

**Steps to reproduce**
- Login as Instructor
- Create/Edit a sessioin
- Add a `Distribute points (among recipients) question` and cancel it
- Add a `Distribute points (among options) question` 

**Expected behaviour:**
The UI for `Distribute points (among options) question` should be consistent like this : 
screenshot 404

**Actual behaviour:**
screenshot 403

**Cause:** When we add the among recipient question we hide `constSumOption_Option` and show `constSumOption_Recipient` but while adding among options question we do not show `constSumOption_Option` again, so it stays hidden. (The same problem as #8463)

**Note:** I unintentionally reported this bug in https://github.com/TEAMMATES/teammates/issues/8463#issuecomment-366458152, but apparently all of us concentrated on the options only and ignored this.

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8603 

**Outline of Solution**

`constSumOption_Option` gets hidden if we call `Distribute points (among recipients) question` and stays that way,so set it to show whenever adding `Distribute points (among options) question`.

**UI before:**
output_1e0hqs

**UI after:**
output_slcrsh

### CODE REVIEW

**Comment by sukanta-27** [comment]
Ready for review.

**Comment by sukanta-27** [comment]
@tshradheya I guess that would be a good idea. Working on that.

File: src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java [hunk 1]
```diff
@@ -204,4 +206,21 @@ public void testDeleteQuestionAction() {
...
+
+        feedbackEditPage.clickNewQuestionButton();
+        feedbackEditPage.selectNewQuestionType("CONSTSUM_RECIPIENT");
+        feedbackEditPage.clickDiscardChangesLinkForNewQuestion();
+        feedbackEditPage.waitForConfirmationModalAndClickOk();
+        feedbackEditPage.clickNewQuestionButton();
+        feedbackEditPage.selectNewQuestionType("CONSTSUM_OPTION");
+
+        assertTrue(feedbackEditPage.isElementVisible(By.id("constSumPoints--1")));
+        assertTrue(feedbackEditPage.isElementVisible(By.id("constSumPointsForEachOption--1")));
```
Comment (tshradheya) [inline src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: The main bug was that the element of id `constSumOption_Option--1` is hidden so there **must** be an assertion check for that.
So add the most important assertion check, which is to see if `constSumOption_Option--1` is visible or not.

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: @tshradheya  I thought as the radio button and the number field both are hidden in the bug, checking one's visibility would mean that the other is present as they are in the same div?

Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: Yes I agree but the bug was because `constSumOption_option--1` is hidden so better to test for that.

Even if you look at the DOM, the `style="display:none"`  is a part of `constSumOption_option--1` which casue the whole thing to be hidden

image

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: Agree. So, should I just check the visibility for `constSumOption_option--1` or should I do that for all three radio buttons (that is checking the visibility for the first two and checking if the third is hidden or not), to make the test complete?

Comment (tshradheya) [reply src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: Doing for all three is good as it makes the tests complete. But make sure to have an assertion check for `constSumOption_Option--1` as that was the one hiding its child element

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: Noted. :+1:  I will make sure the element doesn't hide it's child from us.

**Comment by damithc** [comment]
This PR needs another review from a @TEAMMATES/seniordevs before it can go to the final review stage.

File: src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java [hunk 2]
```diff
@@ -204,4 +206,21 @@ public void testDeleteQuestionAction() {
         assertNull(BackDoor.getFeedbackQuestion(courseId, feedbackSessionName, 1));
     }
 
+    private void testUiConsistencyForNewQuestion() {
+        ______TS("CONSTSUM-option after CONSTSUM-recipient: Check ui consistency success case");
```
Comment (damithc) [inline src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java]: Add an explanatory comment? Neither the method name nor the `TS` seems self-explanatory. 🤔

**Comment by sukanta-27** [comment]
@wkurniawan07 comment added. Ready for review.
