### PR TITLE
SendgridService: fix successful request detection #8663

### LINKED ISSUE #8663: SendgridService: fix successful request detection
v6.4.0

This version started creating lot of `teammates.common.util.Logger severe: Email failed to send:  (Logger.java:52)` although emails seems to be going through.

I've rolled back to v6.3.0 for now.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8663

### CODE REVIEW

File: src/main/java/teammates/logic/core/EmailSenderService.java [hunk 1]
```diff
@@ -33,4 +31,8 @@ public void sendEmail(EmailWrapper wrapper) throws EmailSendingException {
     // accounts for the many different Exceptions from different email services
     protected abstract void sendEmailWithService(EmailWrapper wrapper) throws Exception;
 
+    static boolean isErrorStatus(int statusCode) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/EmailSenderService.java]: Very strictly speaking, not 2XX is `isNotSuccessfulStatus`, e.g. I won't really call 1XX or 3XX errors.
