### PR TITLE
Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type #6619

### LINKED ISSUE #6619: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type
v5.95
Found in log (and also reported by user). It's odd that the error message mentions two message types: CONTRIB and rubric

```
0. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: 
java.lang.reflect.InvocationTargetException
at com.google.appengine.runtime.Request.process-73b769498349bb3a(Request.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:42)
at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:129)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Contrib Qn Invalid visibility options
at teammates.common.util.Assumption.fail(Assumption.java:61)
at teammates.common.util.Assumption.assertTrue(Assumption.java:29)
at teammates.common.datatransfer.FeedbackContributionQuestionDetails.validateGiverRecipientVisibility(FeedbackContributionQuestionDetails.java:755)
... 34 more


1. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||synthese|||Unknown|||TEAMMATES (5.95.02): New System Exception: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
Show/Hide Details >>
Error Message 

        Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.

    



Actual user 

synthese 



Request Method 

POST 



User Agent 

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 



Request Url 

https://teammatesv4.appspot.com/page/instructorFeedbackQuestionAdd 



Request Path 

/page 



Request Parameters 

{showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, rubricNumRows::2, rubricChoice-3::Strongly Agree, numofrecipientstype::max, rubricChoice-0::Strongly Disagree, constSumToRecipients::false, constSumOption-1::, rubricDesc-0-3::Initiates discussions frequently, and engages the team., constSumOption-0::, rubricDesc-0-2::Takes part in discussions and sometimes initiates discussions., rubricChoice-2::Agree, rubricDesc-0-1::Occasionally responds, but never initiates discussions., rubricChoice-1::Disagree, rubricDesc-0-0::Rarely or never responds., generatedOptions::NONE//NONE//NONE, numscalestep::1, numofrecipients::1, recipienttype::OWN_TEAM_MEMBERS_INCLUDING_SELF, constSumPointsForEachOption::100, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::4, questiontext::L'étudiant démontre une capacité de synthèse lorsqu'il présente sa recherche lors des rencontres d’équipe., mcqOption-1::, questiondescription::

Identifier les informations nécessaires, ne pas s'éterniser sur des détails, sélectionner les informations utiles, formuler des hypothèses lors de l’analyse initiale du problème.

, showgiverto::INSTRUCTORS, mcqOption-0::, questionnum::1//1, rubricSubQn-0::This student participates well in online discussions., courseid::101-111-AH, recommendedlength::, rubricSubQn-1::This student completes assigned tasks on time., noofchoicecreated::2//2//2//2, constSumPointsForEachRecipient::100, rubricDesc-1-3::Tasks are always completed before the deadline., rubricWeight-3::0, rankOption-1::, rubricWeight-2::0, rubricDesc-1-0::Rarely or never completes tasks., rankOption-0::, rubricWeight-1::0, rubricDesc-1-1::Often misses deadlines., rubricWeight-0::0, rubricDesc-1-2::Occasionally misses deadlines., numscalemin::1, fsname::Évaluation par les pairs Étape 1, msqOption-0::, msqOption-1::, receiverLeaderCheckbox::RECEIVER, questiontype::CONTRIB, numscalemax::5, givertype::STUDENTS, user::synthese} 


Stack Trace 



java.lang.AssertionError: Failed to instantiate Feedback*QuestionDetails instance for CONTRIB question type.
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionEditAction.java:135)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.validateQuestionGiverRecipientVisibility(InstructorFeedbackQuestionAddAction.java:76)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:51)

	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:365)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)

```

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #6619

**Outline of Solution**

Hide invalid predefined visibility options; check relevant checkboxes for contrib questions upon selecting visibility option.

The only two valid options for contrib questions are:
1. Shown anonymously to recipient and team, visible to instructors (new option)
2. Visible to instructors only

When copying options from the previous question, the following rules are followed:
* New contrib question after non-contrib question:
  * Don't copy
* New non-contrib question after contrib question:
  * Copy
* New contrib question after contrib question:
  * Copy

**Todo:**
* ~~New predefined visibility option~~
* ~~Stricter handling in frontend to allow only these two visibility options~~:
  * ~~Hide invalid pre-defined and custom options~~
  * ~~Add tests~~
* ~~Handle copying problems~~
  * ~~Handle copying of previous visibility options correctly for cases involving contrib questions~~
  * ~~Add tests for copying of previous visibility options for contrib -> non-contrib, non-contrib -> contrib, contrib -> contrib cases~~
* ~~Show a meaningful error message to users when invalid visibility options are submitted anyway (instead of generic error page)~~
* ~~Remove workaround for #6665 after that PR is merged~~

### CODE REVIEW

**Comment by whipermr5** [comment]
@xpdavid raised the question whether existing contrib questions in the database with invalid options (e.g. instructors can only see responses but no names) can be copied. I've tested and it works fine. The backend allows such options (perhaps this will be changed in a future PR). This PR is mainly about fixing the frontend such that `OWN_TEAM_MEMBERS,RECEIVER_TEAM_MEMBERS` are always added to `RECEIVER`, which is the one restriction currently imposed by the backend causing the errors in #6619.

**Comment by xpdavid** [comment]
@whipermr5 So correct me if I am wrong. Basically, this is a bug. Back-end force some constrains but front-end doesn't force these constrains, thus error(#6619) is produced.

**Comment by whipermr5** [comment]
Yup correct! It only enforces one constraint though (`OWN_TEAM_MEMBERS,RECEIVER_TEAM_MEMBERS` must come with `RECEIVER`). It doesn't enforce other custom options like instructors cannot see names, which are now discouraged by the frontend (the only way to add them now is to copy a previous question).

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java [hunk 1]
```diff
@@ -176,9 +176,20 @@ private boolean isVisibilitySetToAnonymousToRecipientAndInstructors(FeedbackQues
     }
 
     private boolean isVisibilitySetToAnonymousToRecipientVisibleToInstructors(FeedbackQuestionAttributes question) {
-        boolean responsesVisibleOnlyToRecipientAndInstructors = question.showResponsesTo.size() == 2
-                && question.showResponsesTo.contains(FeedbackParticipantType.INSTRUCTORS)
-                && question.showResponsesTo.contains(FeedbackParticipantType.RECEIVER);
+        boolean responsesVisibleOnlyToRecipientAndInstructors;
+
+        if (question.questionType.equals(FeedbackQuestionType.CONTRIB)) {
```
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java]: I am not sure if we want to treat this as a special case for `AnonymousToRecipientVisibleToInstructors`.  @junhaoyap What do you think? Should we create another name for this case?

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 2]
```diff
@@ -722,17 +732,36 @@ function copyOptions() {
...
-    } else {
+
+    // Check for special case: the 'Shown anonymously to recipient, visible to instructors' visibility option
+    // in contrib questions should be interpreted as a custom visibility option in non-contrib questions
+    var isContribToNonContrib = prevType === 'CONTRIB' && newType !== 'CONTRIB';
+    var isSpecialOptionSelected = prevQuestionVisibilityOption.trim()
+                                === 'Shown anonymously to recipient, visible to instructors';
+    var isContribToNonContribAndSpecialOptionSelected = isContribToNonContrib && isSpecialOptionSelected;
+
+    if (isContribToNonContribAndSpecialOptionSelected) { // Handle special case
```
Comment (xpdavid) [inline src/main/webapp/js/instructorFeedbackEdit.js]: To continue, this will be the additional JS code to treat the special case.

File: src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java (hunk 1 above)
Comment (xpdavid) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java]: If we don't want to create a new common feedback visibility option, we can just disable the common visibility options like Prof Damith says for `CONTRIB` type question and enforce the constrains using JS code for custom visibility settings.

Comment (whipermr5) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java]: I feel it should be a common option for better user experience. Maybe I should make a new option `Shown anonymously to recipient and team members, visible to instructors`?

Comment (damithc) [inline src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java]: > I feel it should be a common option for better user experience. Maybe I should make a new option Shown anonymously to recipient and team members, visible to instructors?

Sure.

File: src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java [hunk 3]
```diff
@@ -71,12 +71,31 @@ public void testCustomizeOptions() {
...
+        assertFalse(feedbackEditPage
+                .isVisibilityDropdownOptionHiddenForNewQuestion("ANONYMOUS_TO_RECIPIENT_AND_TEAM_VISIBLE_TO_INSTRUCTORS"));
+        assertFalse(feedbackEditPage.isVisibilityDropdownOptionHiddenForNewQuestion("VISIBLE_TO_INSTRUCTORS_ONLY"));
+        assertTrue(feedbackEditPage.isVisibilityDropdownOptionHiddenForNewQuestion("VISIBLE_TO_RECIPIENT_AND_INSTRUCTORS"));
+        assertTrue(feedbackEditPage.isVisibilityDropdownSeparatorHiddenForNewQuestion());
+        assertTrue(feedbackEditPage.isVisibilityDropdownOptionHiddenForNewQuestion("OTHER"));
+
+        ______TS("CONTRIB: verify correct output params for selected visibility option");
+
+        // default (first option)
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: For better user experience, can we just select a option by default? (and I see here you say even the option is `Please select ....`, the option is still the first one)

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 4]
```diff
@@ -635,8 +636,10 @@ function prepareQuestionForm(type) {
 
         $('#contribForm').show();
         fixContribQnGiverRecipient(NEW_QUESTION);
-        setDefaultContribQnVisibility(NEW_QUESTION);
         setContribQnVisibilityFormat(NEW_QUESTION);
+        if (!didCopyOptions) {
```
Comment (whipermr5) [inline src/main/webapp/js/instructorFeedbackEdit.js]: There are some [exceptions](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html#specific-naming-conventions) (`has`, `can`, `should`), but I acknowledge that `did` is not one of them. Will change to `has`.

Comment (whipermr5) [inline src/main/webapp/js/instructorFeedbackEdit.js]: I found it necessary as `setDefaultContribQnVisibility` should be called from here, but there's no way to determine if the options were copied from here.

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 5]
```diff
@@ -669,10 +672,17 @@ function prepareQuestionForm(type) {
  * Copy options (Feedback giver, recipient, and all check boxes)
  * from the previous question
```
Comment (whipermr5) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Oops, missed the header comments!

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 6]
```diff
@@ -723,7 +733,7 @@ function copyOptions() {
         $(this).prop('checked', $prevTable.eq(index).prop('checked'));
     });
 
-    // Hide visibility options and update common visibility options dropdown text if a common option is selected
+ // Hide visibility options and update common visibility options dropdown text if a common option is selected
```
Comment (whipermr5) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Oops, my bad!

File: src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java (hunk 3 above)
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: I'm trying to follow the existing user experience when you create a new question in an empty session. This is the exact experience (`Please select ...` but default to first option); I think the developers' intention was to emphasise to the user the need to take a look? Over here it similarly gives a cue that the option was not copied from the previous question. If the user really does not want to take a look, it will default to the first option.

File: src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java [hunk 7]
```diff
@@ -133,23 +152,54 @@ public void testDeleteQuestionAction() {
      * has options invalid for contribution questions. This is to prevent invalid options
      * from being copied over to the contribution question.
      */
-    private void testAddContributionQuestionAsSecondQuestion() {
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: I found the previous name weird as we're not testing the adding per se, but the copying of the options under such a scenario. Will update the header comments!

**Comment by whipermr5** [comment]
@xpdavid Ready for review :)

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java [hunk 8]
```diff
@@ -1179,6 +1220,36 @@ public String getVisibilityMessage(int questionNumber) {
...
+        return getVisibilityParamShowGiverTo(NEW_QUESTION_NUM);
+    }
+
+    public String getVisibilityParamShowRecipientTo(int questionNumber) {
+        return browser.driver.findElement(By.id("form_editquestion-" + questionNumber))
+                             .findElement(By.cssSelector("input[name='showrecipientto']"))
+                             .getAttribute("value");
+    }
+
+    public String getVisibilityParamShowRecipientToForNewQuestion() {
```
Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: Unused method?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java [hunk 9]
```diff
@@ -1179,6 +1220,36 @@ public String getVisibilityMessage(int questionNumber) {
...
+        return getVisibilityParamShowResponsesTo(NEW_QUESTION_NUM);
+    }
+
+    public String getVisibilityParamShowGiverTo(int questionNumber) {
+        return browser.driver.findElement(By.id("form_editquestion-" + questionNumber))
+                             .findElement(By.cssSelector("input[name='showgiverto']"))
+                             .getAttribute("value");
+    }
+
+    public String getVisibilityParamShowGiverToForNewQuestion() {
```
Comment (xpdavid) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: Unused method?
I bet you want to use it in test cases but you forgot :P LOL

Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java]: Oops haha you're right!!

**Comment by whipermr5** [comment]
@xpdavid Changes made :)

**Comment by whipermr5** [comment]
@xpdavid Thanks for the thorough review! It's really good haha

**Comment by whipermr5** [comment]
@chowyb I did notice this, but it's an unrelated bug that exists in the master branch too. I feel it's outside the scope of this PR to address it.

**Comment by damithc** [comment]
> Bug discovered: discrepancy between the displayed selected option, and the actual selected option

Do we have an issue for this?

**Comment by whipermr5** [comment]
@damithc I think not yet 😅 Will create one soon!

File: src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java [hunk 10]
```diff
@@ -129,27 +154,66 @@ public void testDeleteQuestionAction() {
...
+        feedbackEditPage.clickAddQuestionButton();
+        feedbackEditPage.verifyStatus(Const.StatusMessages.FEEDBACK_QUESTION_ADDED);
+
+        ______TS("CONTRIB: copy visibility options contrib -> non-contrib");
+
+        feedbackEditPage.clickNewQuestionButton();
+        feedbackEditPage.selectNewQuestionType("TEXT");
+
+        assertEquals("Shown anonymously to recipient and team members, visible to instructors",
+                     feedbackEditPage.getVisibilityDropdownLabelForNewQuestion());
```
Comment (chowyb) [inline src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java]: Should keep this indented 8 spaces to be consistent with other changes

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 11]
```diff
@@ -668,13 +669,21 @@ function prepareQuestionForm(type) {
 /**
  * Copy options (Feedback giver, recipient, and all check boxes)
  * from the previous question
+ * @param newType
```
Comment (damithc) [inline src/main/webapp/js/instructorFeedbackEdit.js]: If there is nothing more to say, the entire line can be omitted.
