### PR TITLE
StudentCourseJoinConfirmationPageUiTest: fix Google login #8106

### LINKED ISSUE #8106: StudentCourseJoinConfirmationPageUiTest: fix Google login
I had to try more than 20 times (alternating between Firefox and Chorme) to get this test to pass once against the live server. 
v5.112

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8106

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/GoogleLoginPage.java [hunk 1]
```diff
@@ -84,24 +89,21 @@ private void handleApprovalPageIfAny() {
...
-        }
-
-        By noScriptBy = By.tagName("noscript");
-        if (isElementPresent(noScriptBy)) {
-            waitForTextContainedInElementAbsence(noScriptBy, "&lt;meta http-equiv=\"refresh\"");
-            waitForPageToLoad();
-        }
+        String loginRedirectUrl = Config.APP_URL + "/_";
+        WebDriverWait wait = new WebDriverWait(browser.driver, TestProperties.TEST_TIMEOUT);
+        wait.until((WebDriver d) -> {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: Just wanna say I like how I can finally see lambda arrow in TEAMMATES code base 😛

File: src/test/java/teammates/test/pageobjects/GoogleLoginPage.java [hunk 2]
```diff
@@ -84,24 +89,21 @@ private void handleApprovalPageIfAny() {
...
-            waitForElementToDisappear(metaRefreshBy);
-            waitForPageToLoad();
-        }
-
-        By noScriptBy = By.tagName("noscript");
-        if (isElementPresent(noScriptBy)) {
-            waitForTextContainedInElementAbsence(noScriptBy, "&lt;meta http-equiv=\"refresh\"");
-            waitForPageToLoad();
-        }
+        String loginRedirectUrl = Config.APP_URL + "/_";
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: Not sure if I get it right: can you possibly mean `TestProperties.TEAMMATES_URL`?

Comment (whipermr5) [reply src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: Oh yes oops 😅

**Comment by whipermr5** [comment]
The inconsistency lies in `waitForPageToLoad()` being an unreliable way to test if the page has finished redirecting - it checks the state of the old page instead of the new page. The only way to reliably wait for redirects is to keep checking periodically for something we expect in the new page - in this case, either the distinguishing snippet of the approval page, or else a TEAMMATES page handled by our application (must begin with `TEAMMATES_URL` but must not be an internal URL that the GAE runtime uses to handle login e.g. `https://teammatesv4.appspot.com/_ah/conflogin?continue=...`).

**Comment by wkurniawan07** [comment]
FWIW I finally remember where I get the current link from: http://acanda.github.io/eclipse-pmd/getting-started.html. In other words, nothing has changed.

File: src/test/java/teammates/test/pageobjects/GoogleLoginPage.java [hunk 3]
```diff
@@ -84,24 +88,21 @@ private void handleApprovalPageIfAny() {
...
-            waitForElementToDisappear(metaRefreshBy);
-            waitForPageToLoad();
-        }
-
-        By noScriptBy = By.tagName("noscript");
-        if (isElementPresent(noScriptBy)) {
-            waitForTextContainedInElementAbsence(noScriptBy, "&lt;meta http-equiv=\"refresh\"");
-            waitForPageToLoad();
-        }
+        String loginRedirectUrl = TestProperties.TEAMMATES_URL + "/_";
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/GoogleLoginPage.java]: In that case, can make the URL pattern stricter? e.g. `/_ah/conflogin`. The current one should work and unlikely to cause false positives, but if possible to make it stricter, it will be clearer as well.
