### PR TITLE
[#11284] Fix exception checking in CreateAccountActionTest

### LINKED ISSUE #11284: Fix exception checking in CreateAccountActionTest
https://github.com/TEAMMATES/teammates/blob/48b67bae03babf5a5e578aefce47f0285e8de8b4/src/test/java/teammates/ui/webapi/CreateAccountActionTest.java#L42-L62

https://github.com/TEAMMATES/teammates/blob/48b67bae03babf5a5e578aefce47f0285e8de8b4/src/test/java/teammates/ui/webapi/CreateAccountActionTest.java#L101-L110

This is the wrong way of checking whether an exception is thrown. The correct way is using `assertThrows`.

### PR DESCRIPTION
**Pull request by tjtanjin**
Fixes #11284 

**Outline of Solution**

Replace `assertEquals` with `assertThrows` for testing of exceptions instead.

### CODE REVIEW

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]
Need to check the message just like how it was done before

File: src/test/java/teammates/ui/webapi/CreateAccountActionTest.java [hunk 1]
```diff
@@ -39,27 +39,34 @@ protected void testExecute() {
...
+        String expectedError;
+        String actualError;
+
+        exception = assertThrows(InvalidHttpRequestBodyException.class,
+                () -> getAction(buildCreateRequest(null, institute, email)).execute());
+
+        expectedError = "name cannot be null";
+        actualError = exception.getMessage();
+
+        assertTrue(actualError.contains(expectedError));
```
Comment (wkurniawan07) [inline src/test/java/teammates/ui/webapi/CreateAccountActionTest.java:53]: - Any reason for `contains` while it could be a strict equality check?
- Nitpicking, but this entire construct is too verbose. You can shorten to the following without losing any readability:
   ```java
   exception = assertThrows(InvalidHttpRequestBodyException.class,
           () -> getAction(buildCreateRequest(name, null, email)).execute());
   assertEquals("name cannot be null", exception.getMessage());
   ```

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]

File: src/test/java/teammates/ui/webapi/CreateAccountActionTest.java (hunk 1 above)
Comment (tjtanjin) [reply src/test/java/teammates/ui/webapi/CreateAccountActionTest.java]: Thank you for the feedback, appreciate the much neater and shorter solution! I have modified the code following your advice!

File: src/test/java/teammates/ui/webapi/CreateAccountActionTest.java [hunk 2]
```diff
@@ -39,27 +39,20 @@ protected void testExecute() {
...
-        badRequest = buildCreateRequest(name, institute, null);
-        try {
-            getAction(badRequest).execute();
-        } catch (InvalidHttpRequestBodyException e) {
-            assertEquals("email cannot be null", e.getMessage());
-        }
+
+        Exception exception;
+
+        exception = assertThrows(InvalidHttpRequestBodyException.class,
```
Comment (wkurniawan07) [inline src/test/java/teammates/ui/webapi/CreateAccountActionTest.java:45]: - This can combine with two lines before this
- Again this is nitpicking, but the variable name need not be this long; `e` or `ex` are generally understood as exception variable. More descriptive names may be necessary if there are multiple of such variables around, but right now there is just one.

**Review by wkurniawan07 — CHANGES_REQUESTED** [review]

**Review by wkurniawan07 — APPROVED** [review]
LGTM
