### PR TITLE
[#9642] Feedback sessions with # or ? in their name can't be edited.

### LINKED ISSUE #9642: Feedback sessions with # or ? in their name can't be edited.
Other potential characters may cause this problem as well.

- **Environment**: `master` branch at commit 3455dda7e4e2d854471b1664548f76f002bfd4b9.

**Steps to reproduce**
1. Login as an instructor.
2. Create a new feedback session with # in the name (i.e. test #9642)
3. Click edit on the new feedback session.

**Expected behaviour**
The feedback session edit page loads

**Actual behaviour**
It doesn't load.
image

**Additional info**

This error occurs even after applying the fix from #9638 .
The server outputs the error log: 
`WARNING: UnauthorizedAccessException caught by WebApiServlet: Trying to access system using a non-existent feedback session entity`
The error appears to be from the frontend not sending the character `#` or `?` in the query (and anything after it)

### PR DESCRIPTION
**Pull request by hcwong**
Fixes #9642 

**Outline of Solution**

The issue was with session name containing special characters. The solution was to call `URIEncodeComponent` before calling the relevant functions.

However, I think we should just prevent people from using URI special characters in name (I had to manually search the codebase to find the calls, not friendly for new contributors), as it is quite troublesome to insert `encodeURIComponent` everytime we make a call with `fsname` param. Seems like we already do this for coursenames

### CODE REVIEW

**Comment by joanneong** [comment]
Hi @hcwong , before I take a closer look at this:
1. Can you ensure that Travis is passing first? It seems like your changes affected one of the tests for the student home page.
2. Update your pull request with the changes from `master`.
3. Try to write more [meaningful commit messages](https://chris.beams.io/posts/git-commit/) instead of something like "lint".

Thanks!

File: src/web/app/pages-instructor/instructor-session-base-page.component.ts [hunk 1]
```diff
@@ -201,16 +205,19 @@ export abstract class InstructorSessionBasePageComponent {
...
   }
 
   /**
    * Views the result of a feedback session.
    */
   viewSessionResult(model: SessionsTableRowModel): void {
     this.router.navigateByUrl('/web/instructor/sessions/result'
-        + `?courseid=${model.feedbackSession.courseId}&fsname=${model.feedbackSession.feedbackSessionName}`);
+        + `?courseid=${model.feedbackSession.courseId}`
+        + `&fsname=${encodeURIComponent(model.feedbackSession.feedbackSessionName)}`);
```
Comment (joanneong) [inline src/web/app/pages-instructor/instructor-session-base-page.component.ts]: Is there a reason why this is done using `encodeURIComponent` instead of `this.navigationService.navigateByURLWithParamEncoding`?

File: src/web/services/navigation.service.spec.ts [hunk 2]
```diff
@@ -14,4 +14,9 @@ describe('NavigationService', () => {
     const service: NavigationService = TestBed.get(NavigationService);
     expect(service).toBeTruthy();
   });
+
+  it('should return a encoded param string upon calling encodeParams', () => {
```
Comment (joanneong) [inline src/web/services/navigation.service.spec.ts]: Small grammatical error: should be `an encoded param string` rather than `a encoded param string`.

File: src/web/app/pages-instructor/instructor-session-base-page.component.ts (hunk 1 above)
Comment (hcwong) [reply src/web/app/pages-instructor/instructor-session-base-page.component.ts]: Hmm yes forgot to remove this sorry 😨

File: src/web/services/navigation.service.ts [hunk 3]
```diff
@@ -53,4 +74,11 @@ export class NavigationService {
     }
     window.open(url.toString());
   }
+
+  /**
+   * Opens a new browser window with URL Param encoding
+   */
+  openNewWindowWithParamEncoding(urlWithoutParams: string, params: {[key: string]: string}): void {
```
Comment (wkurniawan07) [inline src/web/services/navigation.service.ts]: `WithParamEncoding` should not be part of the name, as it kind of suggests that "param encoding" is some kind of isolated case. The fact is, param encoding should be expected especially when any kind of user input is involved.

Would suggest to combine this with the previous method and set `{}` to be the default value for `params`.

Comment (hcwong) [reply src/web/services/navigation.service.ts]: Should the same apply to `navigateWithSuccessMessage`?

Comment (wkurniawan07) [reply src/web/services/navigation.service.ts]: If possible.
