### PR TITLE
InstructorFeedbackResultsPageUiTest unstable on local dev server #7064

### LINKED ISSUE #7064: InstructorFeedbackResultsPageUiTest unstable on local dev server
**Environment**

`master` branch from commit 90b40c0e1 onwards

**Trace**
```
org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for visibility of [[FirefoxDriver: firefox on WINDOWS (c7774121-8c0c-4cec-9426-8ff7a40e4faa)] -> css selector: .panel-heading+.panel-collapse]
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-L2LIUI1', ip: '192.168.2.4', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_80'
Session ID: c7774121-8c0c-4cec-9426-8ff7a40e4faa
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0.1}]

	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
	at teammates.test.pageobjects.AppPage.waitForElementVisibility(AppPage.java:218)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.waitForPanelsToExpand(InstructorFeedbackResultsPage.java:282)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.waitForPageToLoad(InstructorFeedbackResultsPage.java:64)
	at teammates.test.pageobjects.InstructorFeedbackResultsPage.expandPanels(InstructorFeedbackResultsPage.java:152)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.loginToInstructorFeedbackResultsPage(InstructorFeedbackResultsPageUiTest.java:710)
	at teammates.test.cases.browsertests.InstructorFeedbackResultsPageUiTest.refreshTestData(InstructorFeedbackResultsPageUiTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:601)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
@leeyimin is encountering this as well.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7064 and the recent heightened failure CI rate that delayed #7033.

**Outline of Solution**

The recent build failures are mostly due to timing issues - popovers seem to disappear faster after 972a10f, leading to an error when trying to validate the popover's content. This solution optimises the `InstructorFeedbackResultsPage` page object to remove unnecessary waiting.

**Details**

Ideally, the popover's content should be validated as soon as it appears. However, in many places, the element is grabbed in a separate call to `findElement` after `waitForElementPresence` returns. This is unnecessary as the underlying Selenium methods in `waitForElementPresence` already return the element once it appears and can be used to do validation. This solution makes use of this to eliminate unnecessary calls to `findElement`, increasing the likelihood of validation without errors.

**Other improvements**

- replace `findElements(...).get(0)` with `findElement(...)`
- favour Selenium WebElement methods over executing JavaScript

### CODE REVIEW

**Comment by whipermr5** [comment]
It seems to work! Only coverage failing due to the failing master build

**Comment by whipermr5** [comment]
@samsontmr @leeyimin Does this resolve the issue?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 1]
```diff
@@ -348,57 +345,46 @@ public void clickAjaxNoResponsePanel() {
...
-                                            .findElement(By.className("profile-pic-icon-hover"));
-        executeScript("arguments[0].scrollIntoView(true);", photoDiv);
-        Actions actions = new Actions(browser.driver);
-        actions.moveToElement(photoDiv).perform();
-        waitForElementPresence(By.cssSelector(".popover-content"));
 
-        executeScript("document.getElementsByClassName('popover-content')[0]"
-                      + ".getElementsByTagName('a')[0].click();");
+        /*
+         * Execute JavaScript instead of using Selenium selectors to bypass bug
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Use multiple single-lines instead of multiline comment:
```java
// Execute ...
// regarding ...
```

Reason: when someone needs to comment out a certain part of code with `/* ... */` (because we're all lazy people right?), the multiline comment may unexpectedly break the flow.

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 2]
```diff
@@ -309,19 +309,16 @@ public void deleteFeedbackResponseComment(String commentIdSuffix) {
...
-        WebElement commentRow = browser.driver.findElement(commentRowSelector);
         assertTrue(commentRow.findElement(By.className("text-muted")).getText().contains(giverName)
                    || commentRow.findElement(By.className("text-muted")).getText().contains("you"));
     }
 
     public void verifyCommentFormErrorMessage(String commentTableIdSuffix, String errorMessage) {
-        WebElement commentRow = browser.driver.findElement(By.id("responseCommentTable" + commentTableIdSuffix));
-        waitForElementPresence(
+        WebElement errorMessageSpan = waitForElementPresence(
                 By.cssSelector("#responseCommentTable" + commentTableIdSuffix + " .col-sm-offset-5 #errorMessage"));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: Not your fault, but if the selector is this way, everything before `#errorMessage` looks obsolete?

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java (hunk 1 above)
Comment (whipermr5) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: This was [copied](https://github.com/TEAMMATES/teammates/blob/61839efa09d73ef906ba5985d6927d0d8a8c9b91/src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java#L411) haha, but I think I'll revert this part. Looks like the Selenium selectors do work on Travis.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 3]
```diff
@@ -305,9 +305,9 @@ private void waitForModalToDisappear() {
     /**
      * Waits for the element to appear in the page, up to the timeout specified.
      */
-    public void waitForElementPresence(By by) {
+    public WebElement waitForElementPresence(By by) {
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: `getElementWithWaitForPresence`?
