### PR TITLE
[#9704] Student: Upload/Edit Photo: Confusing error message shown when uploading empty photo

### LINKED ISSUE #9704: Student: Upload/Edit Photo: Confusing error message shown when uploading empty photo
- **Environment**: `master` branch

**Steps to reproduce**
1. log in as a student
2. go to the profile page
3. click Delete Photo if there is an existing photo
4. click Upload/Edit Photo
5. do not choose any photo and click Upload Image

**Expected behaviour**
Show the user an understandable error message

**Actual behaviour**
hunt

### PR DESCRIPTION
**Pull request by crizyli**
Fixes #9704 

add an additional check to make sure the profile photo uploaded is not empty before sending the request.

### CODE REVIEW

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 1]
```diff
@@ -124,20 +124,24 @@ export class StudentProfilePageComponent implements OnInit {
...
-          .subscribe(() => {
-            this.statusMessageService.showSuccessMessage('Your profile picture has been saved successfully');
-
-            // force reload
-            const timestamp: number = (new Date()).getTime();
-            this.profilePicLink = `${this.backendUrl}/webapi/student/profilePic?${timestamp}`;
-          }, (response: ErrorMessageOutput) => {
-            this.statusMessageService.showErrorMessage(response.error.message);
-          });
+      if (formData) {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Consider use guard clause.
```javascript
if (!formData) {
    return;
}
```

Comment (crizyli) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: I have updated it, could you have a review?

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 2]
```diff
@@ -124,6 +124,10 @@ export class StudentProfilePageComponent implements OnInit {
     const modalRef: NgbModalRef = this.ngbModal.open(UploadEditProfilePictureModalComponent);
     modalRef.componentInstance.profilePicLink = this.profilePicLink;
     modalRef.result.then((formData: FormData) => {
+      if (!formData) {
+        this.statusMessageService.showWarningMessage('No photo detected. You maybe uploaded an empty photo');
```
Comment (rrtheonlyone) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Could we improve on the error message here? What does it mean to say 'you maybe uploaded an empty photo'?

Why not something like 'No photo uploaded.'?

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 3]
```diff
@@ -138,7 +142,7 @@ export class StudentProfilePageComponent implements OnInit {
           }, (response: ErrorMessageOutput) => {
             this.statusMessageService.showErrorMessage(response.error.message);
           });
-    });
+    }).catch(() => {});
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: I think it is better to supply empty handler for `.then(onFullfill, onReject)` rather than use `.catch()`. `catch` is used for error-handling. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Comment (xpdavid) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: @crizyli Reminder :P

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 4]
```diff
@@ -138,7 +142,7 @@ export class StudentProfilePageComponent implements OnInit {
           }, (response: ErrorMessageOutput) => {
             this.statusMessageService.showErrorMessage(response.error.message);
           });
-    });
+    }).then(() => {});
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Nope. Promise does not work like that. You need to provide `onReject` handler as the second parameter of the first `.then`.
