### PR TITLE
admin accounts management page is not scalable #4837

### LINKED ISSUE #4837: admin accounts management page is not scalable
The page used to take a long time on the live server. Now it doesn't load at all (deadline exceeded exception).

### PR DESCRIPTION
**Pull request by bamboo3250**
Fixes #4837

As discussed on Wednesday, I temporarily removed Account Management Page from navbar and added an URL to redirect from Search Page to Account Management Page for each registered instructor.

screenshot 2016-03-06 04 45 24

I also disabled unit test for Account Management Page since we have to renovate it sooner or later anyway.

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java [hunk 1]
```diff
@@ -34,20 +34,22 @@
     
     @BeforeClass
     public static void classSetup() throws Exception {
-        printTestClassHeader();
+        // Temporarily disable unit test for Account Management Page.
```
Comment (kanghj) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java]: @bamboo3250, I think the comment should be explaining why the test is disabled. 

Instead of disabling everything, we should still have the test for the current functionality , where only one instructor appears on the account management page, can still work.

File: src/main/webapp/WEB-INF/tags/admin/navBar.tag [hunk 2]
```diff
@@ -22,9 +22,10 @@
                     <a href="<%=Const.ActionURIs.ADMIN_HOME_PAGE%>">Create Instructor</a>
                 </li>
                 
+                <!-- The link to Account Management Page will be hidden until it's scalable.
```
Comment (kanghj) [inline src/main/webapp/WEB-INF/tags/admin/navBar.tag]: @bamboo3250, let's just remove the link instead of just commenting it out. If the link isn't added back in the very near future, in all likelihood, when the person adds the link in future, he/she won't notice, or will just ignore, the commented out code.

File: src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag [hunk 3]
```diff
@@ -35,13 +35,21 @@
...
-                        class="btn btn-link btn-xs recentActionButton">
+                        class="btn btn-link btn-xs optionButton">
                         
                     <span class="glyphicon glyphicon-zoom-in"></span>View Recent Actions
                 </button>
                 <input type="hidden" name="filterQuery" value="${instructor.viewRecentActionsId}">
                 <input type="hidden" name="courseId" value="${instructor.courseId}">
             </form>
+            <c:if test="${not empty instructor.googleId}">
+                <form method="post" target="blank" action="<%=Const.ActionURIs.ADMIN_ACCOUNT_MANAGEMENT_PAGE%>">
```
Comment (kanghj) [inline src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag]: @bamboo3250, personally I think using GET instead of POST for this page is much more suitable, although that may result in this being inconsistent with the other links surrounding this.

File: src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java [hunk 4]
```diff
@@ -15,39 +15,40 @@
...
-        
-        boolean isToShowAll = this.getRequestParamAsBoolean("all");
+        String instructorGoogleId = this.getRequestParamValue("googleId");
         
         Map<String, ArrayList<InstructorAttributes>> instructorCoursesTable = new HashMap<String, ArrayList<InstructorAttributes>>();
         Map<String, AccountAttributes> instructorAccountsTable = new HashMap<String, AccountAttributes>();
         
-        for(AccountAttributes acc : allInstructorAccountsList){
-            instructorAccountsTable.put(acc.googleId, acc);
+        if (instructorGoogleId == null) {
```
Comment (kanghj) [inline src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java]: @bamboo3250, a minor point, but I guess we should also move this to right after instructorGoogleId is initialised

File: src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java [hunk 5]
```diff
@@ -15,39 +15,40 @@
...
+        AccountAttributes instructorAccount = logic.getAccount(instructorGoogleId);
         
-        for(InstructorAttributes instructor : allInstructorsList){
-            ArrayList<InstructorAttributes> courseList = instructorCoursesTable.get(instructor.googleId);
-            if (courseList == null){
-                courseList = new ArrayList<InstructorAttributes>();
-                instructorCoursesTable.put(instructor.googleId, courseList);
-            }
+        boolean isToShowAll = this.getRequestParamAsBoolean("all");
+        boolean isAccountExisting = instructorAccount != null && !instructorsList.isEmpty();
```
Comment (kanghj) [inline src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java]: @bamboo3250, Hmm, I wonder if the check that <code>!instructorsList.isEmpty();</code> is really needed? What will happen if the account exist in the database, but the account does not have any instructors with it?

File: src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java [hunk 6]
```diff
@@ -15,39 +15,40 @@
...
+        if (isAccountExisting) {
+            instructorAccountsTable.put(instructorAccount.googleId, instructorAccount);
             
-            courseList.add(instructor);
+            for(InstructorAttributes instructor : instructorsList){
```
Comment (kanghj) [inline src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java]: @bamboo3250, let's fix the whitespace here

File: src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag (hunk 3 above)
Comment (bamboo3250) [inline src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag]: Ah you're right. I didn't notice that. We should use GET here.

File: src/main/webapp/WEB-INF/tags/admin/navBar.tag (hunk 2 above)
Comment (bamboo3250) [inline src/main/webapp/WEB-INF/tags/admin/navBar.tag]: I think it won't be that far. Just for 2-3 weeks until I finish all pending PRs. So I want to keep the link there in order to recover it easier.

**Comment by damithc** [comment]
The link can be named 'Manage this account'?

**Comment by damithc** [comment]
And the icon can be an 'edit' icon.

**Comment by bamboo3250** [comment]
@damithc I updated the UI.
screenshot 2016-03-06 01 15 07

**Comment by bamboo3250** [comment]
@kanghj except for the comment in navbar, I have fixed all problems above.

**Comment by bamboo3250** [comment]
@damithc later could you create an issue about reconstructing Account Management Page as we discussed last week? Please specify the use case of the page. I will make it scalable.

**Comment by damithc** [comment]
@bamboo3250 new issue created.
