### PR TITLE
[#9564] Consolidate Student Profile Picture RESTFul API

### LINKED ISSUE #9574: Clicking Save Edited Photo does not close the modal in Student Profile page
- **Environment**: Environment: master branch, commit ba5b2ef

**Steps to reproduce**
- Go to Students Profile page
- Click `Upload/Edit Photo`, choose a new photo
- Click `Save Edited Photo`

**Expected behaviour**
The photo should be changed and the modal should be closed

**Actual behaviour**
The modal remains open although the photo is changed
image

### PR DESCRIPTION
**Pull request by rrtheonlyone**
Part of #9564
Part of #9573
Part of #9595
Resolves #9574

**Changes**:

| New endpoint        | Method           | 
| ------------- |:-------------:| 
| /student/profilePic   | DELETE | 
|                     | PUT      |   
|                      | GET      | 
 
The biggest change here is with regards to the GET profile picture. Previously we used a `blobKey` to retrieve the picture. It has now been updated to use the student ID / email instead.

The authentication for the profile picture is as follows:
- **student** can view his own profile picture and his teammates' one
- **instructor** can view the profile picture of students in his course if he has sufficient privileges to do so

Tests have been done for the above.

Other changes as a result of this:
- slight improvement to the course details page (view photo previously used to remove the router params)

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@rrtheonlyone You're going to find it difficult if you rely entirely on student email/course ID combination to get profile picture. Why not allow that in addition of still allowing usage of blob key?

**Comment by rrtheonlyone** [comment]
@wkurniawan07 

The initial reason I went for this is because @xpdavid mentioned that the Blobkey is not encrypted and hence, may be a security risk if we use that for authentication. It also seemed cleaner to use the ID /email instead of passing the BlobKey back and forth. 

Do you suggest we allow both blobkey / id + email as a way to get the picture? (if blobkey is still used, how should we do the access control check?)

**Comment by wkurniawan07** [comment]
> Blobkey is not encrypted and hence, may be a security risk if we use that for authentication

The security concern is valid; which is why, unless authorized (e.g. getting self's profile), the blob key should not even be returned as API response. You'd realize this is the same case for regkeys.

> It also seemed cleaner to use the ID /email instead of passing the BlobKey back and forth.

I could tell you at least one place where there is no course ID and student email information. See if you can find it.

> Do you suggest we allow both blobkey / id + email as a way to get the picture? (if blobkey is still used, how should we do the access control check?)

Another similarity with regkey: if you have it, no further access control check is necessary, and rightly so.

**Comment by rrtheonlyone** [comment]
Ready for review.

After some discussion, seems that the blobKey may not be needed (since there is sufficient information to retrieve picture). 

The authentication logic/flow needs to be looked into.

File: src/main/java/teammates/common/util/Const.java [hunk 1]
```diff
@@ -986,7 +986,7 @@ private Const() {
         public static final String INSTRUCTOR_STUDENTS = "/instructor/students";
         public static final String COURSE_STUDENT_DETAILS = "/courses/students/details";
         public static final String STUDENT_COURSE = "/student/course";
-        public static final String STUDENT_PROFILE_PICTURE = "/students/profilePic";
+        public static final String STUDENT_PROFILE_PICTURE = "/student/profilePic";
```
Comment (ChooJeremy) [inline src/main/java/teammates/common/util/Const.java]: Should probably standardize the name: `_` implies a `/`.
```suggestion
        public static final String STUDENT_PROFILEPIC = "/student/profilePic";
```

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java [hunk 2]
```diff
@@ -29,57 +26,195 @@ protected String getRequestMethod() {
...
+        loginAsStudent(student1InCourse1.googleId);
 
-        String[] submissionParams = new String[] {};
+        GetStudentProfilePictureAction action = getAction();
+        ImageResult imageResult = getImageResult(action);
 
-        GetStudentProfilePictureAction action = getAction(submissionParams);
-        assertThrows(NullHttpParameterException.class, () -> action.execute());
-    }
+        assertEquals(HttpStatus.SC_OK, imageResult.getStatusCode());
```
Comment (ChooJeremy) [inline src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: You should verify that the image result is correct instead of just the status code?
(Same scenarios for all of your other assertEquals)

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 3]
```diff
@@ -1,25 +1,73 @@
...
-        // Profile picture is available to everyone with the blob key
+        String courseId = getRequestParamValue(Const.ParamsNames.COURSE_ID);
+        String studentEmail = getRequestParamValue(Const.ParamsNames.STUDENT_EMAIL);
+
+        //viewing someone else's photo
+        if (studentEmail != null && courseId != null) {
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+
+            if (student == null) {
+                throw new UnauthorizedAccessException(UNAUTHORIZED_ACCESS);
```
Comment (junming403) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: This does not looks like `UnauthorizedAccessException` to me, should it be 404 instead?

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 4]
```diff
@@ -1,25 +1,73 @@
...
+        StudentProfileAttributes studentProfile = null;
+
+        if (studentEmail == null || courseId == null) {
+            if (!userInfo.isStudent) {
+                return new JsonResult(STUDENT_NOT_FOUND, HttpStatus.SC_NOT_FOUND);
+            }
+            studentProfile = logic.getStudentProfile(userInfo.id);
+        } else {
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+            if (student == null) {
```
Comment (junming403) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: This has already been checked in access control parts?

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 5]
```diff
@@ -1,25 +1,73 @@
...
+
+        //viewing someone else's photo
+        if (studentEmail != null && courseId != null) {
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+
+            if (student == null) {
+                throw new UnauthorizedAccessException(UNAUTHORIZED_ACCESS);
+            }
+
+            gateKeeper.verifyAccessibleForCurrentUserAsInstructorOrTeamMemberOrAdmin(logic.getAccount(userInfo.id),
```
Comment (junming403) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Does admin has privilege on this api as well?

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java [hunk 6]
```diff
@@ -29,57 +26,195 @@ protected String getRequestMethod() {
...
+
+        submissionParams = new String[] {
+                Const.ParamsNames.COURSE_ID, student1InCourse1.getCourse(),
+                Const.ParamsNames.STUDENT_EMAIL, student1InCourse1.getEmail(),
+        };
+
+        action = getAction(submissionParams);
+        imageResult = getImageResult(action);
+
+        assertEquals(HttpStatus.SC_OK, imageResult.getStatusCode());
```
Comment (junming403) [inline src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Is there a way to verify the image is correct as well?

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java (hunk 5 above)
Comment (xpdavid) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: We don't need to cater the case I think.

File: src/main/java/teammates/common/util/Const.java (hunk 1 above)
Comment (rrtheonlyone) [reply src/main/java/teammates/common/util/Const.java]: I really don't think this matters.

However, if the rest feel the same way I can change it :)

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java (hunk 2 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Yup done!

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java (hunk 3 above)
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Yes it is technically a 404. 

However, this is under the checkAccessControl method. This method checks access (it doesnt deal with action logic). By convention I have been throwing unauthorized access here.

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java (hunk 4 above)
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Agreed! Removed

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java (hunk 6 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Yup done!

**Comment by rrtheonlyone** [comment]
Ready for review.

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 7]
```diff
@@ -1,25 +1,70 @@
...
     public ActionResult execute() {
-        String blobKey = getNonNullRequestParamValue(Const.ParamsNames.BLOB_KEY);
-        return new ImageResult(blobKey);
+        String courseId = getRequestParamValue(Const.ParamsNames.COURSE_ID);
+        String studentEmail = getRequestParamValue(Const.ParamsNames.STUDENT_EMAIL);
+
+        StudentProfileAttributes studentProfile = null;
+
+        if (studentEmail == null || courseId == null) {
+            if (!userInfo.isStudent) {
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Yeap you are right! I have updated this.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html [hunk 8]
```diff
@@ -132,7 +132,8 @@ <h4 class="font-weight-bold">Teammates</h4>
     <div class="col-12">
       <div class="row">
         <div class="col-md-2 col-3">
-          <img src="{{getPictureUrl(teammateProfile.pictureKey)}}" class="profile-pic float-left">
+          <img src="{{getPictureUrl(teammateProfile.pictureKey, teammateProfile.email)}}"
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Yes you are right! We have to ensure this still works as intended.

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 9]
```diff
@@ -1,25 +1,71 @@
...
+            }
+        } else {
+            //viewing someone else's photo
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+
+            if (student == null) {
+                throw new UnauthorizedAccessException(UNAUTHORIZED_ACCESS);
+            }
+
+            gateKeeper.verifyAccessibleForCurrentUserAsInstructorOrTeamMemberOrAdmin(logic.getAccount(userInfo.id),
```
Comment (Adoby7) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: You can modify the `verifyAccessibleForCurrentUserAsInstructorOrTeamMemberOrAdmin` that takes a account id as a parameter. Since it only needs the id of account, there is no need to get the account attribute as we have already had the account id

Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Yeap, updated!

File: src/main/java/teammates/logic/api/GateKeeper.java [hunk 10]
```diff
@@ -396,19 +396,19 @@ private boolean isStudent() {
      * Verifies that the action is accessible when the user is either an instructor of the course, a student of the course
      * or his/her team member, or an admin.
      */
-    public void verifyAccessibleForCurrentUserAsInstructorOrTeamMemberOrAdmin(AccountAttributes account, String courseId,
+    public void verifyAccessibleForCurrentUserAsInstructorOrTeamMemberOrAdmin(String accountId, String courseId,
```
Comment (xpdavid) [inline src/main/java/teammates/logic/api/GateKeeper.java]: `accountId` -> googleId. This is a more suitable name.

Comment (rrtheonlyone) [reply src/main/java/teammates/logic/api/GateKeeper.java]: Yes it is! I have updated it.

**Comment by rrtheonlyone** [comment]
Ready for next stage of review.

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java [hunk 11]
```diff
@@ -29,57 +27,170 @@ protected String getRequestMethod() {
...
+        loginAsStudent(student2InCourse1.googleId);
+
+        submissionParams = new String[] {
+                Const.ParamsNames.COURSE_ID, student1InCourse1.getCourse(),
+                Const.ParamsNames.STUDENT_EMAIL, student1InCourse1.getEmail(),
+        };
+
+        verifyCanAccess(submissionParams);
+
+        ______TS("Success case: student can view his own photo but instructor or admin canno");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]:
```suggestion
        ______TS("Success case: student can view his own photo but instructor or admin cannot");
```

File: src/web/app/pages-instructor/student-list/student-list.component.ts [hunk 12]
```diff
@@ -62,23 +57,17 @@ export class StudentListComponent implements OnInit {
...
-    if (!pictureKey) {
-      return '/assets/images/profile_picture_default.png';
-    }
-    return `${this.backendUrl}/webapi/students/profilePic?blob-key=${pictureKey}`;
+    this.httpRequestService.get('/student/profilePic', paramMap)
+        .subscribe(() => {}, (resp: any) => {
+          student.photoUrl = (resp.status === 200)
+                ? `${this.backendUrl}/webapi/student/profilePic?courseid=${this.courseId}&studentemail=${student.email}`
+                : '/assets/images/profile_picture_default.png';
+        });
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-list/student-list.component.ts]:
```suggestion
        }, handlerFor404);
```
should be put here?

File: src/web/app/pages-instructor/student-profile/student-profile.component.html [hunk 13]
```diff
@@ -4,7 +4,7 @@
     <div class="col-12">
       <div class="row">
         <div class="col-md-2 col-3">
-          <img src="{{getPictureUrl(studentProfile?.pictureKey)}}" class="profile-pic float-right">
+          <img src="{{getPictureUrl(studentProfile.pictureKey)}}" class="profile-pic float-right">
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-profile/student-profile.component.html]: You should use `(error) => ()` handler to update the picture to `/assets/images/profile_picture_default.png`?

The current logic is a bit weird and there will be no more pictureKey returning for studentProfile.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html (hunk 8 above)
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Same here.

Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Done!

File: src/web/app/pages-instructor/student-profile/student-profile.component.html (hunk 13 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.html]: Yes you are right, I have made it better.

File: src/web/app/pages-instructor/student-list/student-list.component.ts (hunk 12 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-list/student-list.component.ts]: Done

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java (hunk 11 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Updated

**Comment by rrtheonlyone** [comment]
@xpdavid I have updated the frontend logic to load default picture if no picture is found.

Ready for review.

**Comment by rrtheonlyone** [comment]
Actually, I realised that the `student-profile` components still use the picture key (the box to upload/edit photos). Is it okay to leave it as is?

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 14]
```diff
@@ -1,25 +1,71 @@
...
+        String courseId = getRequestParamValue(Const.ParamsNames.COURSE_ID);
+        String studentEmail = getRequestParamValue(Const.ParamsNames.STUDENT_EMAIL);
+
+        StudentProfileAttributes studentProfile = null;
+
+        if (studentEmail == null || courseId == null) {
+            studentProfile = logic.getStudentProfile(userInfo.id);
+        } else {
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+            studentProfile = logic.getStudentProfile(student.googleId);
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: The googleId can be null for legacy data. Use `String#isEmpty` to check?

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java [hunk 15]
```diff
@@ -29,57 +27,170 @@ protected String getRequestMethod() {
...
+                Const.ParamsNames.STUDENT_EMAIL, student1InCourse1.getEmail(),
+        };
+
+        action = getAction(submissionParams);
+        imageResult = getImageResult(action);
+
+        assertEquals(HttpStatus.SC_OK, imageResult.getStatusCode());
+        assertEquals(student1Profile.pictureKey, imageResult.blobKey);
+
+        ______TS("Failure case: requested student has no profile picture");
```
Comment (xpdavid) [inline src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Let's add a case where unregistered student's profile is requested?

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts [hunk 16]
```diff
@@ -12,26 +13,29 @@ import { StudentProfile } from './student-profile';
   styleUrls: ['./student-profile.component.scss'],
 })
 export class StudentProfileComponent implements OnInit {
-
   Gender: typeof Gender = Gender; // enum
+  photoUrl?: string;
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-profile/student-profile.component.ts]: In this case, photoUrl can be an `@Input()` property?

An component should not have any assumption about the pages use them.

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 17]
```diff
@@ -87,8 +87,8 @@ export class StudentProfilePageComponent implements OnInit {
     if (!pictureKey) {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: pictureKey is still used here?

Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Updated

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts (hunk 16 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.ts]: Yup! I have made it have a default value instead of being an optional. This isnt exactly an `@Input()` since it is always there.

File: src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java (hunk 15 above)
Comment (rrtheonlyone) [reply src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java]: Done

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java (hunk 14 above)
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Done

**Comment by rrtheonlyone** [comment]
I have updated the API and also removed all use of `pictureKey` from the frontend.

Furthermore, I refactored the student profile component and profile picture upload modal. I removed unnecessary checks/methods and made the overall logic cleaner.

As a result, the user flow as a result has been improved (ref to #9573 and #9574). The process to upload a picture is now as follows:

picture_upload_sm

It is now more intuitive to upload a picture. There are lesser buttons to click and the saving of profile picture is only done upon clicking of the upload button.

**Comment by rrtheonlyone** [comment]
Unfortunately, it seems that this change in UX flow requires some change in the E2E tests as well (currently failing).

We can fix those if the new changes are approved.

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 18]
```diff
@@ -18,146 +13,115 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
   }
 
   /**
-   * Triggers the appropriate actions when the 'Save Edited Photo' button is clicked.
+   * Populates form data with the image blob.
    */
-  saveEditedPhoto(): void {
-    this.populateFormData(this.croppedImage);
-    this.uploadPicture();
+  populateFormData(file: File): void {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: I am not sure why you need to call `populateFormData` every time when something changes. It looks like you can just construct the new formData in `uploadPicture()`?

It is confusing (I have to say, compared to the original) that `croppedImage ` and `formData` contain "same" data.

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 19]
```diff
@@ -1,25 +1,74 @@
...
+        String studentEmail = getRequestParamValue(Const.ParamsNames.STUDENT_EMAIL);
+
+        StudentProfileAttributes studentProfile = null;
+
+        if (studentEmail == null || courseId == null) {
+            studentProfile = logic.getStudentProfile(userInfo.id);
+        } else {
+            StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
+
+            if (!student.googleId.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: I am not aware of `String.isEmpty()` method. Its what I have used above (from a non-static context) right? Or is there are a static method as well?

I have added an extra check here like this:
```
if (student.googleId != null && !student.googleId.isEmpty()) {
       studentProfile = logic.getStudentProfile(student.googleId);
}
```

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts [hunk 20]
```diff
@@ -12,26 +13,29 @@ import { StudentProfile } from './student-profile';
...
 
   @Input() studentProfile: StudentProfile | undefined;
 
   private backendUrl: string = environment.backendUrl;
 
-  constructor() { }
+  constructor(private route: ActivatedRoute) { }
 
   ngOnInit(): void {
+    this.route.queryParams.subscribe((queryParams: any) => {
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.ts]: Ahh sorry! You are right.

I have changed as per suggestion.

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts [hunk 21]
```diff
@@ -12,26 +13,29 @@ import { StudentProfile } from './student-profile';
   styleUrls: ['./student-profile.component.scss'],
 })
 export class StudentProfileComponent implements OnInit {
-
   Gender: typeof Gender = Gender; // enum
+  photoUrl: string = '/assets/images/profile_picture_default.png';
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.ts]: Yup done!

File: src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap [hunk 22]
```diff
@@ -333,7 +333,7 @@ exports[`StudentCourseDetailsPageComponent should snap with populated fields 1`]
           >
             <img
               class="profile-pic float-left"
-              src="http://localhost:8080/webapi/students/profilePic?blob-key=something.jpg"
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap]: I have modified the logic slightly. The one where you commented on the `inline`.

As a result of this change, the image src is also different!

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 23]
```diff
@@ -100,19 +101,30 @@ export class StudentCourseDetailsPageComponent implements OnInit {
...
   /**
-   * Construct the url for the profile picture from the given key.
+   * Sets the url for the profile picture from the given student details.
    */
-  getPictureUrl(pictureKey: string): string {
-    if (!pictureKey) {
-      return '/assets/images/profile_picture_default.png';
-    }
-    return `${this.backendUrl}/webapi/students/profilePic?blob-key=${pictureKey}`;
+  loadPictureUrl(teammateProfile: TeammateProfile, courseId: string): void {
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Yes your right! Updated.

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 24]
```diff
@@ -56,8 +56,8 @@ export class StudentProfilePageComponent implements OnInit {
   editForm!: FormGroup;
   nationalities?: string[];
 
+  defaultPictureLink: string = '/assets/images/profile_picture_default.png';
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: I have actually used this in some other places also. I will modify all accordingly!

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts [hunk 25]
```diff
@@ -76,19 +76,17 @@ export class StudentProfilePageComponent implements OnInit {
...
-   * Construct the url for the profile picture from the given key.
+   * Sets the profile picture of a student as the default image
    */
-  getProfilePictureUrl(pictureKey: string): string {
-    if (!pictureKey) {
-      return '/assets/images/profile_picture_default.png';
-    }
-    this.currentTime = (new Date()).getTime(); // forces image reload in HTML template
-    return `${this.backendUrl}/webapi/students/profilePic?blob-key=${pictureKey}&time=${this.currentTime}`;
+  setDefaultPic(): void {
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Done!

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 26]
```diff
@@ -18,146 +13,115 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
   /**
-   * Gets the profile picture as blob image.
+   * Uploads the picture that has been newly uploaded/edited.
    */
-  getProfilePicture(): Observable<Blob> {
-    const profilePicEndPoint: string =
-        this.profilePicLink.replace(`${this.backendUrl}/webapi`, '');
-    return this.httpRequestService.get(profilePicEndPoint, {}, 'blob');
+  uploadPicture(): void {
+    this.activeModal.dismiss();
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: Yes good point. I thought about this but just went with the `Output` initially for convenience.

I have updated accordingly to make use of the method!

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 27]
```diff
@@ -18,146 +13,115 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
 export class UploadEditProfilePictureModalComponent implements OnInit {
-
-  isImageLoaded: boolean = false;
-  user: string = '';
-  fileName: string = 'No File Selected';
-  isFileSelected: boolean = false;
+  imageChangedEvent: any = '';
+  croppedImage: any = '';
+  showCropper: boolean = false;
+  imageLoadFailed: boolean = false;
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: Correct. This was an experimental flag I was playing around with. Apologies, will remove it since it feels like it is really not needed at the moment.

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 28]
```diff
@@ -18,146 +13,115 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
 })
 export class UploadEditProfilePictureModalComponent implements OnInit {
-
-  isImageLoaded: boolean = false;
-  user: string = '';
-  fileName: string = 'No File Selected';
-  isFileSelected: boolean = false;
+  imageChangedEvent: any = '';
+  croppedImage: any = '';
+  showCropper: boolean = false;
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: Yup have removed this flag also.

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html [hunk 29]
```diff
@@ -6,70 +6,48 @@ <h4 class="modal-title">
...
+  </button>
+
+  <div>
+    <image-cropper
+      [imageChangedEvent]="imageChangedEvent"
+      [imageBase64]="croppedImage"
+      [maintainAspectRatio]="false"
+      (imageCropped)="imageCropped($event)"
+      (imageLoaded)="imageLoaded()"
+      [style.display]="showCropper ? null : 'none'"
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html]: This part seems to do nothing as well. So, have removed it.

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 30]
```diff
@@ -18,146 +13,115 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
   /**
    * Saves the latest cropped image.
    */
   imageCropped(event: ImageCroppedEvent): void {
-    this.croppedImage = event.file;
+    this.populateFormData(event.file as File);
+  }
+
+  /**
+   * Checks if image is loaded
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: Removed method

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.ts (hunk 25 above)
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.ts]: Done!

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts (hunk 18 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: You have a good point here. 

However, there is a reason for this:
1. If an Image is changed in any way, I need access to the form data to send out the POST request. Populating it this way allows me to do it.
2. `croppedImage` has only one purpose. It preloads an image into the cropper if the user already has a profile picture. Other than that, I do not have any use for it. The library is built as such.

Do let me know if there is a better way to do this.

**Comment by rrtheonlyone** [comment]
Ready for review. 

I have improved the logic and also updated the tests.

File: src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts [hunk 31]
```diff
@@ -21,18 +22,25 @@ interface StudentDetails {
   styleUrls: ['./instructor-course-student-details-page.component.scss'],
 })
 export class InstructorCourseStudentDetailsPageComponent implements OnInit {
-
   user: string = '';
   student?: StudentAttributes;
   studentProfile?: StudentProfile;
+  photoUrl: string = '';
+
+  private backendUrl: string = environment.backendUrl;
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts]: This can be a local variable?

File: src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts [hunk 32]
```diff
@@ -9,6 +9,9 @@ describe('StudentProfileComponent', () => {
   beforeEach(async(() => {
     TestBed.configureTestingModule({
       declarations: [StudentProfileComponent],
+      imports: [
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts]: I guess you don't need this?

File: src/web/app/pages-instructor/student-list/student-list.component.ts [hunk 33]
```diff
@@ -25,6 +20,8 @@ interface StudentDetails {
 })
 export class StudentListComponent implements OnInit {
 
+  readonly DEFAULT_PICTURE_LINK: string = '/assets/images/profile_picture_default.png';
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-list/student-list.component.ts]: Is `DEFAULT_PICTURE_LINK` used somewhere in the HTML template? I actually don't know which style do you want to follow:
1. export `DEFAULT_PICTURE_LINK ` to HTML template -> you don't need `setDefaultPic()` -> just use `(error)="student.photoUrl = DEFAULT_PICTURE_LINK;"`

2. Stick to `setDefaultPic()` -> delete export of `DEFAULT_PICTURE_LINK`

File: src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts (hunk 31 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts]: Yup updated. I have just used `environment.backendUrl` directly in the profile picture link.

I have also changed all unnecessary uses of this variable in other classes.

File: src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts (hunk 32 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts]: yes removed

File: src/web/app/pages-instructor/student-list/student-list.component.ts (hunk 33 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-list/student-list.component.ts]: As of now, I dont have a fixed style. I have changed my code to follow (2) now. I can change it to (1) also if that is the convention. I personally prefer (2) as the method can be extended if needed (perhaps you want to do more actions on error for picture)

**Comment by rrtheonlyone** [comment]
Made necessary changes - ready for review.

File: src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts [hunk 34]
```diff
@@ -1,5 +1,5 @@
 import { async, ComponentFixture, TestBed } from '@angular/core/testing';
-
+import { RouterTestingModule } from '@angular/router/testing';
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts]: I guess you can also remove this?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 35]
```diff
@@ -100,19 +98,23 @@ export class StudentCourseDetailsPageComponent implements OnInit {
       if (!this.teammateProfiles) {
         this.statusMessageService.showWarningMessage('You do not have any teammates yet.');
       }
+
+      if (this.teammateProfiles && this.course) {
+        const courseId: string = this.course.id;
+        this.teammateProfiles.forEach((teammateProfile: TeammateProfile) => teammateProfile.photoUrl
+          = `${environment.backendUrl}/webapi/student/profilePic?courseid=${courseId}
+          &studentemail=${teammateProfile.email}`);
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: The email is not the email in the teammteProfile. It is the email in `StudentAttributes`.

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.html [hunk 36]
```diff
@@ -8,7 +8,8 @@ <h1>{{ name }}</h1>
           <img
               src="{{ profilePicLink }}"
               class="profile-pic"
-              (click)="onUploadEdit()">
+              (click)="onUploadEdit()"
+              (error)="this.profilePicLink = this.DEFAULT_PICTURE_LINK">
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/student-profile-page.component.html]: `DEFAULT_PICTURE_LINK` is not defined?

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts [hunk 37]
```diff
@@ -18,146 +13,106 @@ import { StudentProfilePictureResults } from '../../../../types/api-output';
...
 export class UploadEditProfilePictureModalComponent implements OnInit {
-
-  isImageLoaded: boolean = false;
-  user: string = '';
-  fileName: string = 'No File Selected';
-  isFileSelected: boolean = false;
+  imageChangedEvent: any = '';
   formData?: FormData;
-  imageToShow: any;
   croppedImage: any;
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: You can remove this?

**Comment by xpdavid** [comment]
Please also check whether this PR resolve https://github.com/TEAMMATES/teammates/pull/9588 or not?

File: src/e2e/java/teammates/e2e/cases/e2e/StudentProfilePageE2ETest.java [hunk 38]
```diff
@@ -51,15 +42,14 @@ public void testAll() {
...
-        profilePage.ensureProfileContains("short.name", "e@email.tmt", "inst", "American",
-                StudentProfileAttributes.Gender.FEMALE, "this is enough!$%&*</>");
-        profilePage.verifyPhotoSize("295px", "295px");
+        profilePage.verifyPhotoSize("220px", "220px");
 
-        StudentProfileAttributes studentProfileAttributes =
-                BackDoor.getStudentProfile("SProfUiT.CS2104", "SProfUiT.student@gmail.tmt");
-        // checks that the pictureKey value is within the newly uploaded profile picture link
-        assertTrue(profilePage.getProfilePicLink().contains(studentProfileAttributes.pictureKey));
+        ______TS("Typical case: no picture");
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/e2e/java/teammates/e2e/cases/e2e/StudentProfilePageE2ETest.java]: Yup your right! Forgot to update the descriptions. Updated accordingly.

File: src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts (hunk 34 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.spec.ts]: Yup

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 35 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Ahh yess! Fixed.

File: src/web/app/pages-student/student-profile-page/student-profile-page.component.html (hunk 36 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/student-profile-page.component.html]: Oh yah, updated! I will thoroughly check all my changes and make sure everything is working now :P

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts (hunk 37 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts]: Yup removed

**Comment by rrtheonlyone** [comment]
@xpdavid made the necessary changes!

Yes it should resolve #9588 

I have looked through the issue box and realised there are a number of issues which this PR should help fix (or make progress with). I will updated my main PR description accordingly to reference those.

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts [hunk 39]
```diff
@@ -12,26 +11,20 @@ import { StudentProfile } from './student-profile';
...
-  private backendUrl: string = environment.backendUrl;
-
   constructor() { }
 
   ngOnInit(): void {
   }
 
   /**
-   * Construct the url for the profile picture from the given key.
+   * Sets the profile picture of a student as the default image
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-profile/student-profile.component.ts]:
```suggestion
   * Sets the profile picture of a student as the default image.
```

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 40]
```diff
@@ -100,19 +98,24 @@ export class StudentCourseDetailsPageComponent implements OnInit {
       if (!this.teammateProfiles) {
         this.statusMessageService.showWarningMessage('You do not have any teammates yet.');
       }
+
+      if (this.teammateProfiles && this.course && this.student) {
+        const courseId: string = this.course.id;
+        const studentEmail: string = this.student.email;
+        this.teammateProfiles.forEach((teammateProfile: TeammateProfile) => teammateProfile.photoUrl
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: The `photoUrl` is always the same?

I guess you should make use of the `/webapi/students` to get the student attributes of the team members.

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html [hunk 41]
```diff
@@ -6,70 +6,46 @@ <h4 class="modal-title">
...
+  </button>
+
+  <button class="btn btn-primary btn-space" (click)="rotateRight()">
+    <i class="fas fa-redo-alt"></i>
+  </button>
+
+  <div>
+    <image-cropper
+      [imageChangedEvent]="imageChangedEvent"
+      [imageBase64]="imageCropper.imageBase64"
```
Comment (xpdavid) [inline src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html]: Can this line be removed?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 40 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Yup updated

File: src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html (hunk 41 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html]: Yes it can! Removed

**Comment by rrtheonlyone** [comment]
I have refactored the course details page to use the new APIs. 

The page now makes a few API calls namely:
1. `/course` : to get course details
2. `/student`: to get user details
3. `/students:`: to fetch teammates
4. `/student/profile`: to get student profiles
5. `/instructors`: to load instructors

A few things to note:
- The page UI/UX could use some work. The tables are not consistent and its not very visual
- The profile is entirely up to the user to fill in. Hence some of the tables have no content (user has blank profile). Might need to look into a better way of rendering this
- Lazy load teammates + profile in future? (upon button press)
- The teammates includes the current user as well.


Ready for next stage of review.

File: src/web/services/student.service.ts [hunk 42]
```diff
@@ -23,4 +23,15 @@ export class StudentService {
     };
     return this.httpRequestService.get('/students', paramsMap);
   }
+
+  /**
+   * Gets all students in a course and team as an instructor by calling API.
```
Comment (xpdavid) [inline src/web/services/student.service.ts]:
```suggestion
   * Gets all students in a course and team as a student by calling API.
```
right?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 43]
```diff
@@ -1,46 +1,18 @@
...
-  gender: Gender;
-  pictureKey: string;
-}
-
-interface StudentCourseDetails {
-  student: StudentAttributes;
-  course: CourseAttributes;
-  instructorDetails: InstructorDetails[];
-  teammateProfiles?: TeammateProfile[];
+interface StudentProfileWithPicture extends StudentProfile {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Prefer composition over inheritance. i.e. It is better to put student profile as a field inside the interface rather than extending it.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 44]
```diff
@@ -52,67 +24,119 @@ interface StudentCourseDetails {
...
-  course?: CourseAttributes;
-  instructorDetails?: InstructorDetails[];
-  teammateProfiles?: TeammateProfile[];
-
-  private backendUrl: string = environment.backendUrl;
-
-  constructor(private route: ActivatedRoute, private httpRequestService: HttpRequestService,
+  student?: Student;
+  course?: Course;
+  instructorDetails?: Instructors;
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Can just use `Instructor[]`?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 45]
```diff
@@ -52,67 +24,119 @@ interface StudentCourseDetails {
...
+    this.courseService.getCourse(courseid).subscribe((course: Course) => {
+      this.course = course;
+    });
+  }
 
-      if (!resp.instructorDetails) {
-        this.statusMessageService.showErrorMessage('Error retrieving instructor details');
-      }
+  /**
+   * Loads the students of the course.
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]:
```suggestion
   * Loads the current logged-in student of the course.
```

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 46]
```diff
@@ -52,67 +24,119 @@ interface StudentCourseDetails {
...
+   * Loads the teammates of the current student.
+   * @param courseid: id of the course queried
+   * @param teamName: team of current student
+   */
+  loadTeammates(courseid: string, teamName: string): void {
+    this.studentService.getStudentsFromCourseAndTeam(courseid, teamName)
+        .subscribe((students: Students) => {
+          students.students.forEach((student: Student) => {
+            // filter away current user
+            if (this.student && student.email === this.student.email && student.name === this.student.name) {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: - Is this check necessary `this.student`?
- I think just checking email is enough.

File: src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap [hunk 47]
```diff
@@ -128,71 +133,6 @@ exports[`StudentCourseDetailsPageComponent should snap with populated fields 1`]
     </div>
   </div><div
     class="section"
-  >
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap]: I think you should modify the snapshot test accordingly?

Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap]: Done!

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 46 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Yup yourr right. Fixed

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 45 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Done

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 44 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Done

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts (hunk 43 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: Yupp changed

File: src/web/services/student.service.ts (hunk 42 above)
Comment (rrtheonlyone) [reply src/web/services/student.service.ts]: Yupp correct

**Comment by rrtheonlyone** [comment]
Ready for review.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 48]
```diff
@@ -1,46 +1,22 @@
...
-
-interface StudentCourseDetails {
-  student: StudentAttributes;
-  course: CourseAttributes;
-  instructorDetails: InstructorDetails[];
-  teammateProfiles?: TeammateProfile[];
+/**
+ * A student profile which also has the profile picture URL
+ */
+export interface StudentProfileWithPicture {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]: You don't need to `export` it?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts [hunk 49]
```diff
@@ -36,48 +37,55 @@ describe('StudentCourseDetailsPageComponent', () => {
...
-      id: 'CS3281',
-      name: 'Thematic Systems',
-      timeZone: 'Asia/Singapore',
+    const student: Student = {
+      courseId: '1.1.c-demo2',
+      email: '1@1.com',
+      lastName: '1',
+      name: '1',
+      comments: '',
+      requestId: '5cb7d3320000b3b0cb4e5208',
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts]: You don't need to have construct requestId?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts [hunk 50]
```diff
@@ -36,48 +37,55 @@ describe('StudentCourseDetailsPageComponent', () => {
...
-        pictureKey: 'something2.jpg',
+        photoUrl: '/assets/images/profile_picture_default.png',
+        studentProfile: {
+          email: 'iam2@hello.com',
+          gender: Gender.MALE,
+          institute: 'nus',
+          moreInfo: 'Misc',
+          name: '2',
+          nationality: 'Andorran',
+          pictureKey: '',
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts]: You should remove `pictureKey` in `StudentProfileData`?

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html [hunk 51]
```diff
@@ -111,60 +111,57 @@ <h4 class="font-weight-bold">Self</h4>
...
-                <span *ngIf="teammateProfile.institute">{{teammateProfile.institute}}</span>
+                <span *ngIf="teammateProfile.studentProfile.institute">{{teammateProfile.studentProfile
+                  .institute}}</span>
               </td>
             </tr>
             <tr>
               <td class="font-weight-bold">Nationality</td>
               <td>
-                <span *ngIf="teammateProfile.nationality">{{teammateProfile.nationality}}</span>
+                <span *ngIf="teammateProfile.studentProfile.nationality">{{teammateProfile.studentProfile
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: I think you can safely remove the `*ngIf`. Check other places also.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html [hunk 52]
```diff
@@ -111,60 +111,57 @@ <h4 class="font-weight-bold">Self</h4>
...
-            <span>{{student.googleId}}</span>
-          </div>
-        </div>
       </div>
     </div>
   </div>
 </div>
 
-<div class="section" *ngIf="teammateProfiles">
+<div class="section" *ngIf="teammateProfiles && teammateProfiles.length">
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: You don't need this check `teammateProfiles`?

I hope you know what the `teammateProfiles` in the condition is used for.

Same for other places.

Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Done! Yes I am aware. 

This was something I just reused from the current implementation. I have updated accordingly.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html (hunk 51 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Yup

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts (hunk 49 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts]: Yup removed.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts (hunk 50 above)
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts]: Removed and updated!

File: src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts [hunk 53]
```diff
@@ -21,18 +22,23 @@ interface StudentDetails {
   styleUrls: ['./instructor-course-student-details-page.component.scss'],
 })
 export class InstructorCourseStudentDetailsPageComponent implements OnInit {
-
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts]: Unrelated change here, most files do leave one line spacing before the declaration of variables so let's do that here as well :)

File: src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts [hunk 54]
```diff
@@ -27,21 +28,26 @@ interface Session {
   styleUrls: ['./instructor-student-records-page.component.scss'],
 })
 export class InstructorStudentRecordsPageComponent implements OnInit {
-
```
Comment (tanhengyeow) [inline src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts]: Same here.

File: src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts (hunk 53 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts]: Done

File: src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts (hunk 54 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts]: Done!

**Comment by rrtheonlyone** [comment]
@tanhengyeow thanks for the review!

With regards to your comments:

**1/2**: Good catch! This is due to regression. I had two ways to update the picture `onError` initially and removed one! Now it is fixed.

Now for points 3-5, they seem very UX specific. There is a reason why I went to refactor out the profile picture component and redesign it. One, the logic was pretty complicated with heavy reliance on `pictureKey`. I had to remove this key as part of my migration and this meant a revamp of the page. Two, the UX was def not user friendly (refer to #9573) - it was difficult to upload a picture; you had to click like three buttons and the saving felt odd.

I just simplified the picture upload and made it obvious how to use! There is of course room for improvement. However, I think that is best left to a new issue and another PR. This PR has already: 
- touched on multiple pages to update Profile Picture API
- refactored modal component (to simplify upload process and improve flow) + updated E2E + snapshot
- redid API calls to course details (to get the profile picture URL) + updated snapshot

However, since you brought them up:

**3**: A user will open this modal and will be greeted with a smaller window (with some buttons and a message). The chance he wont read the message is pretty small right :P . Furthermore, why the need to complicate the process and make the buttons appear later? I do not see a great hindrance if the buttons are already there! However, this is just my opinion (up for discussion separately)

**4**: Yes, we can look into a better placement for this. (If I was as a user, I wont be too shocked f the message is close to the buttons; looks fine to me)

**5**: Yup sure! We can separately look into a separate flow for this. User only sees upload -> buttons + sentence

**Comment by tanhengyeow** [comment]
Yup agree that the suggestions can be a new issue on its own as they are just some of my quick observations :smile: 

I can file one after this PR has been merged

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 55]
```diff
@@ -52,67 +28,132 @@ interface StudentCourseDetails {
...
-      if (!resp.instructorDetails) {
-        this.statusMessageService.showErrorMessage('Error retrieving instructor details');
-      }
-
-      if (!this.teammateProfiles) {
-        this.statusMessageService.showWarningMessage('You do not have any teammates yet.');
-      }
-    }, (resp: ErrorMessageOutput) => {
-      this.statusMessageService.showErrorMessage(resp.error.message);
+  loadCourse(courseid: string): void {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]:
```suggestion
  loadCourse(courseId: string): void {
```

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 56]
```diff
@@ -52,67 +28,132 @@ interface StudentCourseDetails {
...
+      this.course = course;
     });
   }
 
   /**
-   * Construct the url for the profile picture from the given key.
+   * Loads the current logged-in student of the course.
+   * @param courseid: id of the course queried
+   */
+  loadStudent(courseid: string): void {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]:
```suggestion
  loadStudent(courseId: string): void {
```

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts [hunk 57]
```diff
@@ -52,67 +28,132 @@ interface StudentCourseDetails {
...
+          this.statusMessageService.showErrorMessage(resp.error.message);
+        });
+  }
+
+  /**
+   * Loads the teammates of the current student.
+   * @param courseid: id of the course queried
+   * @param teamName: team of current student
+   */
+  loadTeammates(courseid: string, teamName: string): void {
```
Comment (xpdavid) [inline src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts]:
```suggestion
  loadTeammates(courseId: string, teamName: string): void {
```

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html [hunk 58]
```diff
@@ -36,15 +36,15 @@ <h4 class="font-weight-bold">Course</h4>
...
+            <span>{{course.creationDate}}</span>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
 
-<div class="section" *ngIf="instructorDetails">
+<div class="section" *ngIf="instructorDetails && instructorDetails.length">
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Actually, empty array is not regarded as false :O

Check this out: https://basarat.gitbooks.io/typescript/docs/javascript/truthy.html

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java [hunk 59]
```diff
@@ -1,25 +1,75 @@
...
  */
 public class GetStudentProfilePictureAction extends Action {
 
+    /** String indicating ACCESS is not given. */
+    public static final String UNAUTHORIZED_ACCESS = "You are not allowed to view this resource!";
+
+    /** String indicating student not found. */
+    public static final String STUDENT_NOT_FOUND = "No student found for given parameters";
+
+    /** String indicating profile picture not found. */
```
Comment (damithc) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Mentioning the type `String` in the comment is redundant?

Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Would `Message` be better?

Something like `/** Message indicating student not found. */`

Comment (damithc) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: `Indicates the student is not found`?

Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Yup that is better! I have updated accordingly.

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts [hunk 60]
```diff
@@ -12,26 +11,20 @@ import { StudentProfile } from './student-profile';
...
-   * Construct the url for the profile picture from the given key.
+   * Sets the profile picture of a student as the default image.
    */
-  getPictureUrl(pictureKey: string): string {
-    if (!pictureKey) {
-      return '/assets/images/profile_picture_default.png';
-    }
-    return `${this.backendUrl}/webapi/students/profilePic?blob-key=${pictureKey}`;
+  setDefaultPic(): void {
+    this.photoUrl = '/assets/images/profile_picture_default.png';
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/student-profile/student-profile.component.ts]: This strengthens what I said about extracting this as constant.

File: src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html (hunk 58 above)
[the remark this answers is not in the document]
Comment (wkurniawan07) [reply src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html]: Empty array (or empty object `{}`) is not `false`.

File: src/e2e/java/teammates/e2e/cases/e2e/StudentProfilePageE2ETest.java [hunk 61]
```diff
@@ -51,15 +42,14 @@ public void testAll() {
...
-        // checks that the pictureKey value is within the newly uploaded profile picture link
-        assertTrue(profilePage.getProfilePicLink().contains(studentProfileAttributes.pictureKey));
+        ______TS("Typical case: edit profile page");
+        profilePage.editProfileThroughUi("short.name", "e@email.tmt", "inst", "American",
+                StudentProfileAttributes.Gender.FEMALE, "this is enough!$%&*</>");
 
-        logout();
+        profilePage.ensureProfileContains("short.name", "e@email.tmt", "inst", "American",
+                StudentProfileAttributes.Gender.FEMALE, "this is enough!$%&*</>");
+        profilePage.verifyStatusMessage(Const.StatusMessages.STUDENT_PROFILE_EDITED);
```
Comment (wkurniawan07) [inline src/e2e/java/teammates/e2e/cases/e2e/StudentProfilePageE2ETest.java]: What are all the changes here?

Comment (rrtheonlyone) [reply src/e2e/java/teammates/e2e/cases/e2e/StudentProfilePageE2ETest.java]: These are not changes! Due to how selenium behaves, I had to reorder the test runner. 

The previous implementation was as follows:
1. Edit profile
2. Upload Picture
3. Edit picture
4. Ensure profile contains everything

However, with my redesign of this feature. This test repeatedly kept failing. The reason was due to the status bar verification. Once profile is edited, there will be a status bar message saying it is succesfully edited. After the profile picture is saved, due to Selenium's speed, the old status bar will still be around and it wont disappear for a couple of seconds. So this test will fail as instead of "Profile Picture Saved Succesfully", it is something like "Profile Picture edited succesfully.."

So my solution to fix (albeit hacky) this, was to reorder this process, I make it so that the profile picture is saved first, before the profile is edited. While the profile is being edited, there is enough time, for the status bar to disappear. Hence the changes.

File: src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java [hunk 62]
```diff
@@ -155,9 +151,6 @@ public void editProfilePhoto() {
         click(editPictureFlipHorizontal);
         click(editPictureFlipHorizontal);
         click(editPictureFlipHorizontal);
-
-        click(editPictureSubmit);
-        waitForPageToLoad();
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java]: I dont have that button anymore! My "save" button will close off the modal.

File: src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java [hunk 63]
```diff
@@ -177,12 +170,13 @@ public void showPictureEditor() {
     }
 
     public void verifyPhotoSize(String height, String width) {
-        assertEquals(height, browser.driver.findElement(By.className("cropper")).getCssValue("height"));
-        assertEquals(width, browser.driver.findElement(By.className("cropper")).getCssValue("width"));
+        assertEquals(height, browser.driver.findElement(By.className("profile-pic")).getCssValue("height"));
+        assertEquals(width, browser.driver.findElement(By.className("profile-pic")).getCssValue("width"));
+        click(uploadEditModal.findElement(By.className("close")));
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java]: Yes you are right! This is wrong. 

I will fix this. I think this was something I was experimenting with earlier while debugging the E2E test.

File: src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java (hunk 3 above)
Comment (rrtheonlyone) [reply src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java]: Even in the `checkSpecificAccessControl` method?

That method is of `void` type and hence you cant return a `new JsonResult(..., HttpStatus.SC_NOT_FOUND)` as we normally do in our `Action`. As a result, for almost all of the actions here, I have returned unauthorized access if I cant find the student/instructor.

File: src/web/app/pages-instructor/student-list/student-list.component.ts [hunk 64]
```diff
@@ -62,23 +54,15 @@ export class StudentListComponent implements OnInit {
...
-   * Construct the url for the profile picture from the given key.
+   * Sets the profile picture of a student as the default image
    */
-  getPictureUrl(pictureKey: string): string {
-    if (!pictureKey) {
-      return '/assets/images/profile_picture_default.png';
-    }
-    return `${this.backendUrl}/webapi/students/profilePic?blob-key=${pictureKey}`;
+  setDefaultPic(student: StudentListStudentData): void {
+    student.photoUrl = '/assets/images/profile_picture_default.png';
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-list/student-list.component.ts]: Yes exactly! Where though? I could not find any `const.ts` file to house constants like this.

File: src/web/app/pages-instructor/student-profile/student-profile.component.html [hunk 65]
```diff
@@ -4,7 +4,7 @@
     <div class="col-12">
       <div class="row">
         <div class="col-md-2 col-3">
-          <img src="{{getPictureUrl(studentProfile?.pictureKey)}}" class="profile-pic float-right">
+          <img src="{{this.photoUrl}}" class="profile-pic float-right" (error)="setDefaultPic()">
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.html]: Nope I dont. I will update this as well.

File: src/web/app/pages-instructor/student-profile/student-profile.component.ts (hunk 60 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/student-profile/student-profile.component.ts]: Yes correct (used in a couple of places)

File: src/web/app/pages-instructor/student-list/student-list.component.ts (hunk 64 above)
[the remark this answers is not in the document]
Comment (amrut-prabhu) [reply src/web/app/pages-instructor/student-list/student-list.component.ts]: How about [`config.ts`](https://github.com/TEAMMATES/teammates/blob/master/src/web/environments/config.template.ts)?
