### PR TITLE
Instructor: remind particular student: fix stray place holder in email text #8664

### LINKED ISSUE #8664: Instructor: remind particular student: fix stray place holder in email text
found in: v6.3.0, v6.4.0 (I didn't check earlier versions)

Steps:
* Add the instructor as a student
* Have a session that has questions for students as well as instructors
* Send a reminder using 'remind particular student' option in instructor home page

Actual: one of the emails sent has a placeholder text instead of actual content

image

### PR DESCRIPTION
**Pull request by sukanta-27**
Fixes #8664 

**Outline of Solution:** see https://github.com/TEAMMATES/teammates/issues/8664#issuecomment-373914123

### CODE REVIEW

**Comment by sukanta-27** [comment]
@damithc @whipermr5 
This bug should have never occurred in the first place. But apparently we don't check for the reminder email send to the instructor, just the **copy** of the reminder email send to the student (which is forwarded to the instructor) is checked. Which is why this bug slipped everyone's sight in the first place.

https://github.com/TEAMMATES/teammates/blob/8a974ee703c46f4b3280552f46b3e767eb561eab/src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java#L95-L99

I have added a test for the reminder emails send to the instructor, so that this type of error doesn't happen again.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 1]
```diff
@@ -519,4 +524,18 @@ private void verifyEmailReceivedCorrectly(
         assertTrue(hasReceivedEmailCorrectly);
     }
 
+    private void verifyEmailWithoutSpecifiedLineReceivedCorrectly(
```
Comment (sukanta-27) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: **To the reviewer:** I could not find a way to retrieve the reminder email sent to the instructor any other way, so Added this method, which checks for an email, which **does not** contain the specified line that is passed in the argument. (Trying to retrieve the email with using `verifyEmailReceivedCorrectly` retrieves the student email copy sent to the instructor, not the reminder email for the instructor )

Then searched for the email that does not have the line `=== Email message as seen by the students ===` (As this is the actual email the instructor receives to submit responses)

If there is any better way to retrieve this email, I will be happy to modify my logic accordingly.

**Comment by sukanta-27** [comment]
@wkurniawan07 Can you review it, as you reviewed #8182 and this is related?

**Comment by sukanta-27** [comment]
@wkurniawan07 A reminder.

**Comment by sukanta-27** [comment]
@wkurniawan07 A reminder :sweat_smile:

**Comment by sukanta-27** [comment]
@wkurniawan07 A gentle reminder.

**Comment by sukanta-27** [comment]
@wkurniawan07 A reminder.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java (hunk 1 above)
Comment (LuLechuan) [reply src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Hi @sukanta-27, since there is a `course` created for this test, you can try using `logic.getInstructorForEmail(String courseId, String email)` and check whether it returns you a null value. If it doesn't, that means the recipient of the email is an instructor.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 2]
```diff
@@ -93,8 +93,13 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
                                 course.getName(), session.getFeedbackSessionName());
 
         String lineInEmailCopyToInstructor = "The email below has been sent to students of course:";
+        //Verify the student reminder email
```
Comment (LuLechuan) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Minor change here, there is a space between "//" and the start of the sentence.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 3]
```diff
@@ -93,8 +93,13 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
         verifyEmailReceivedCorrectly(emails, student1.email, subject, "/sessionReminderEmailForStudent.html");
-        verifyEmailReceivedCorrectly(emails, instructor1.email, subject,
+        //Verify the Student email copy send to the instructor
```
Comment (LuLechuan) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Similar here and below

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java (hunk 1 above)
Comment (sukanta-27) [reply src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: @LuLechuan I have some confusion with your comment. And that is, there is no problem in getting the instructor's email. 

https://github.com/TEAMMATES/teammates/blob/968c58b351fce9c892a5c20ad0af5bc9713ec0a3/src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java#L62-L68

My problem is, there are two emails sent to the instructor, 
the first one is the copy of the student reminder email. [screenshot]
screenshot 473

And the second one is the reminder email that is sent to the instructor to remind him to complete the feedback session.
screenshot 474

The problem that I was facing is that, I could not retrieve the second email sent to the instructor. The first email is retrieved using the method 
`private void verifyEmailReceivedCorrectly(List<EmailWrapper> actualEmails, String recipient, String subject, String emailContentFilePath, String containsString)`
but the other `verifyEmailReceivedCorrectly` method also retrieves the first email. So that is why I added this method, to retrieve the second email.

Comment (LuLechuan) [reply src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: I see, misinterpreted your question.

**Comment by sukanta-27** [comment]
@LuLechuan @wkurniawan07 A gentle reminder. This is ready for review.

**Comment by whipermr5** [comment]
@wkurniawan07 Hoping to get this merged by the next release.

File: src/test/resources/emails/sessionReminderEmailCopyToInstructor.html [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+      </tr>
+
+      <tr>
+        <td style="padding:5px;">
+          <strong>
+            Deadline:
+          </strong>
+        </td>
+        <td style="padding:5px;">
+          Fri, 30 Apr 2027, 11:59 PM UTC+0200
```
Comment (whipermr5) [inline src/test/resources/emails/sessionReminderEmailCopyToInstructor.html]: The format has changed after #84.

Comment (sukanta-27) [reply src/test/resources/emails/sessionReminderEmailCopyToInstructor.html]: Oh! Thank you for pointing out. I was wondering why the build failures, and as I am currently working on the other PR, didn't run the tests. Will change it accordingly.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java (hunk 1 above)
Comment (wkurniawan07) [reply src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: This method should not be necessary. To hunt down the 2nd email, just look for that `/page/instructorFeedbackSubmissionEditPage?...` portion.

Comment (sukanta-27) [reply src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Right!!! :man_facepalming: What was I thinking! :sweat_smile:

**Comment by sukanta-27** [comment]
@whipermr5 @wkurniawan07 
I am getting this error repeatedly.
```
java.lang.AssertionError: expected:<2018-04-02T07:22:16.903Z> but was:<2018-04-02T07:22:16.907Z>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:143)
	at teammates.test.cases.datatransfer.StudentProfileAttributesTest.testToEntity(StudentProfileAttributesTest.java:187)
	...
```
with different times, everytime. I am not sure why this is happening in this PR, but not the other PRs, as I have not modified this file. Any help?

**Comment by sukanta-27** [comment]
@wkurniawan07 This is ready for review. I have made the necessary changes.

**Comment by tshradheya** [comment]
@sukanta-27 Regarding this https://github.com/TEAMMATES/teammates/pull/8665#issuecomment-377907700, I am guessing its 99% due to `Instant.now()` being used.
A similar problem was reported in #8709 and I am guessing more might be found later as slowly `java.time` is being used now.

For now, you can just re run the test and it should pass, also you can open an issue so that it can be solved.
