### PR TITLE
SearchManager: fix bug where documents are put multiple times #7688

### LINKED ISSUE #7688: SearchManager: fix bug where documents are put multiple times
As discovered by @leeyimin while reviewing #7682, `SearchManager`'s [`putDocument`](https://github.com/TEAMMATES/teammates/blob/a1bb20de04affcc0f4a029407b87f05b45de183f/src/main/java/teammates/storage/search/SearchManager.java#L46-L87) and [`putDocuments`](https://github.com/TEAMMATES/teammates/blob/a1bb20de04affcc0f4a029407b87f05b45de183f/src/main/java/teammates/storage/search/SearchManager.java#L92-L132) methods contain a bug where documents are put multiple times even when the put succeeds. The bug was caused by my oversight when improving `putDocument` in #6851 and later replicated in `putDocuments` in #6928.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7688

**Outline of Solution**
- Allow configuration of `RetryManager` maximum delay via constructor
- Move `retry` package from `test` to `main` to allow access in `SearchManager`
- Rewrite `SearchManager`'s `putDocument` and `putDocuments` methods to use `RetryManager`

All tests are passing on my staging server.

### CODE REVIEW

File: src/main/java/teammates/storage/search/SearchManager.java [hunk 1]
```diff
@@ -93,10 +94,11 @@ public static void putDocuments(String indexName, List<Document> documents) {
         Index index = getIndex(indexName);
 
         int delay = 2;
-        for (int attempts = 0; attempts < MAX_RETRIES; attempts++) {
+        boolean isSuccessful = false;
+        for (int attempts = 0; attempts < MAX_RETRIES && !isSuccessful; attempts++) {
             try {
                 List<Document> failedDocuments = putDocuments(index, documents);
```
Comment (leeyimin) [inline src/main/java/teammates/storage/search/SearchManager.java]: Should `documents` be reused here and later so that successfully put documents are not being put again?

Comment (whipermr5) [inline src/main/java/teammates/storage/search/SearchManager.java]: This is not as clear and would result in a checkstyle complaint (reassignment of parameter).

Comment (whipermr5) [inline src/main/java/teammates/storage/search/SearchManager.java]: I've rewritten the whole thing with `RetryManager` (and extended `RetryManager` with some new functionality in the process). The logic should be much clearer now :)

File: src/main/java/teammates/common/util/retry/RetryManager.java [hunk 2]
```diff
@@ -118,20 +124,20 @@ private RetryManager() {
     }
 
     @SafeVarargs
-    private static <C extends Throwable> boolean isThrowableTypeIn(Throwable e, Class<C>... exceptionTypes) {
-        for (Class<C> exceptionType : exceptionTypes) {
-            if (exceptionType.isInstance(e)) {
+    private static boolean isThrowableTypeIn(Throwable e, Class<? extends Throwable>... recognizedExceptionTypes) {
+        for (Class<?> recognizedExceptionType : recognizedExceptionTypes) {
```
Comment (leeyimin) [inline src/main/java/teammates/common/util/retry/RetryManager.java]: Just `Class` instead of `Class<?>`?

**Comment by leeyimin** [comment]
`E` for `Retryable` may need more description.

File: src/main/java/teammates/common/util/retry/RetryManager.java [hunk 3]
```diff
@@ -1,18 +1,25 @@
-package teammates.test.driver.retry;
+package teammates.common.util.retry;
 
 import teammates.common.util.Assumption;
+import teammates.common.util.Logger;
 import teammates.common.util.ThreadHelper;
-import teammates.test.driver.TestProperties;
 
 /**
  * Handles running and retrying of {@code Retryable} tasks.
```
Comment (leeyimin) [inline src/main/java/teammates/common/util/retry/RetryManager.java]: Can use a class reference for `Retryable` here.

File: src/main/java/teammates/storage/search/SearchManager.java [hunk 4]
```diff
@@ -44,108 +47,157 @@ private SearchManager() {
...
+
+        /**
+         * The GAE Search API signals put document failure in two ways: it either
+         * returns a {@link PutResponse} containing an {@link OperationResult} with a non-OK {@link StatusCode}, or
+         * throws a {@link PutException} that also contains an embedded {@link OperationResult}.
+         * We handle both ways by examining the {@link OperationResult} to determine what kind of error it is. If it is
+         * transient, we use {@link RetryManager} to retry the operation; if it is
+         * non-transient, we do not retry but throw a {@link TeammatesException} upwards instead.
+         */
+        RM.runUntilSuccessful(new RetryableTaskReturnsThrows<OperationResult, TeammatesException>("Put document") {
```
Comment (leeyimin) [inline src/main/java/teammates/storage/search/SearchManager.java]: Not sure if `TeammatesException` should be used here as it seems to denote some sort of logical error in the system, rather than failure with datastore or GAE.

File: src/main/java/teammates/common/util/retry/MaximumRetriesExceededException.java [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+
+    public MaximumRetriesExceededException(Retryable task) {
+        this(task, null);
+    }
+
+    public MaximumRetriesExceededException(Retryable task, Throwable cause) {
+        super(task.getName() + " failed after maximum retries" + task.finalMessage == null ? "" : ": " + task.finalMessage,
+                cause);
+        if (task instanceof RetryableTaskReturnsThrows) {
+            finalResult = ((RetryableTaskReturnsThrows) task).getResult();
```
Comment (leeyimin) [inline src/main/java/teammates/common/util/retry/MaximumRetriesExceededException.java]: Maybe use constructor for this?

Comment (whipermr5) [inline src/main/java/teammates/common/util/retry/MaximumRetriesExceededException.java]: I decided to simplify it altogether by just copying two optional protected fields from the `Retryable` - `finalMessage` and `finalData`. After all, upon failure the user might want to embed `finalData` that is not necessarily the result.

Ultimately, the result feature should only be used for returning data upon success, and not for anything else (whether it is embedding data in the `MaximumRetriesExceededException` or passing data around from `run` to `isSuccessful` etc. - as you very rightfully pointed out, we can simply declare private variables within the inner class if we want to pass data). With this in mind, the whole framework is simplified greatly.

The latest iteration of `SearchManager` doesn't even need the result feature, and is much cleaner and easier to understand than the previous iteration. Also, structure wise, `putDocumentWithRetry` and `putDocumentsWithRetry` are finally in sync. Thank you for your excellent inputs! :)

File: src/main/java/teammates/common/util/retry/Retryable.java [hunk 6]
```diff
@@ -1,14 +1,26 @@
...
+     * An optional final message to show in the {@link MaximumRetriesExceededException} thrown
+     * should the task fail after maximum retries.
+     */
+    protected String finalMessage;
+
+    /**
+     * An optional final object to embed in the {@link MaximumRetriesExceededException} thrown
+     * should the task fail after maximum retries.
+     */
+    protected Object finalData;
```
Comment (whipermr5) [inline src/main/java/teammates/common/util/retry/Retryable.java]: The user might want to embed other types of data in the exception than the return type. E.g. return an ID (string) of the put document if successful but embed the PutResponse in the exception if the operation fails after maximum retries.
