### PR TITLE
Instructor: download results: fix NullPointerException #7170

### LINKED ISSUE #7170: Instructor: download results: fix NullPointerException
Several users are facing this problem in the recent few days. Interestingly, the error does not appear if they choose a 'section' first.
In all the cases reported so far, it's always the `FeedbackContributionQuestionDetails.java`
```
0. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :
java.lang.NullPointerException
at teammates.common.datatransfer.questions.FeedbackContributionQuestionDetails.getQuestionResultStatisticsCsv(FeedbackContributionQuestionDetails.java:362)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionResultsForQuestionInCsvFormat(FeedbackSessionsLogic.java:923)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionResultsSummaryInSectionAsCsv(FeedbackSessionsLogic.java:887)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionResultsSummaryAsCsv(FeedbackSessionsLogic.java:831)
at teammates.logic.api.Logic.getFeedbackSessionResultSummaryAsCsv(Logic.java:1318)
at teammates.ui.controller.InstructorFeedbackResultsDownloadAction.execute(InstructorFeedbackResultsDownloadAction.java:45)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:361)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:635)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:595)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:565)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
at java.lang.Thread.run(Thread.java:745)
```

### LINKED ISSUE #7373: FeedbackContributionQuestionDetails: fix NullPointerException
Received from the live server
```
Error Message: teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :
java.lang.NullPointerException
at teammates.common.datatransfer.questions.FeedbackContributionQuestionDetails.getQuestionResultsStatisticsHtmlQuestionView(FeedbackContributionQuestionDetails.java:271)
at teammates.common.datatransfer.questions.FeedbackContributionQuestionDetails.getQuestionResultStatisticsHtml(FeedbackContributionQuestionDetails.java:152)
at teammates.ui.pagedata.InstructorFeedbackResultsPageData.buildQuestionTableAndResponseRows(InstructorFeedbackResultsPageData.java:923)
at teammates.ui.pagedata.InstructorFeedbackResultsPageData.buildQuestionTableWithoutResponseRows(InstructorFeedbackResultsPageData.java:868)
at teammates.ui.pagedata.InstructorFeedbackResultsPageData.initForViewByQuestion(InstructorFeedbackResultsPageData.java:121)
at teammates.ui.controller.InstructorFeedbackResultsPageAction.execute(InstructorFeedbackResultsPageAction.java:138)
at teammates.ui.controller.Action.executeAndPostProcess(Action.java:445)
at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:68)
at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:43)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:644)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:604)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:574)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #7170, fixes #7373

**Outline of Solution**

`FeedbackContributionQuestionDetails`: Skip results from "Instructors" team when building the (team name)-(team members' emails) map

**Details**

There seems to be an assumption throughout `FeedbackContributionQuestionDetails` that all team members' emails (provided by the method `getTeamMembersEmail`) are student emails. For example, the method `getStudentResults` assigns the name `studentEmail` when it iterates through the team members' emails ([link](https://github.com/TEAMMATES/teammates/blob/2a9b3988d59ea1ad33ba446aef7d8797aa72b7b1/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L484)):
```
for (String studentEmail : teamEmails) {
```
and the method `getTeamResults` has this assignment ([link](https://github.com/TEAMMATES/teammates/blob/2a9b3988d59ea1ad33ba446aef7d8797aa72b7b1/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L503)):
```
teamEvalResult.studentEmails = teamMembersEmail.get(team);
```

However, the method `getTeamMembersEmail` gets members from `FeedbackSessionResultsBundle`'s `rosterTeamNameMembersTable`. This table is populated by `getTeamNameToEmailsTableFromRoster`, a method in `FeedbackSessionResultsBundle` that adds both students as well as instructors to the table. The instructors are added to a team named "Instructors" ([link](https://github.com/TEAMMATES/teammates/blob/2a9b3988d59ea1ad33ba446aef7d8797aa72b7b1/src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java#L2081-L2088)):
```
List<InstructorAttributes> instructors = courseroster.getInstructors();
String instructorsTeam = Const.USER_TEAM_FOR_INSTRUCTOR;
Set<String> instructorEmails = new HashSet<>();

for (InstructorAttributes instructor : instructors) {
    instructorEmails.add(instructor.email);
    teamNameToEmails.put(instructorsTeam, instructorEmails);
}
```

This "instructors" team should be skipped when building the map in `getTeamMembersEmail`, since it is not relevant for contribution questions.

### CODE REVIEW

**Comment by damithc** [comment]
> It seems that getTeamMembersEmail was never meant to include only student team members. Hence, getStudentResults should not assume that all team members are students, but filter them first.

If a misleading name could have caused the previous developer to introduce this bug, we can also consider changing the method name to a more appropriate name.

**Comment by whipermr5** [comment]
I'm not sure how instructors are involved in contribution question results though. Only students can respond to contribution questions, right?

**Comment by damithc** [comment]
> I'm not sure how instructors are involved in contribution question results though. Only students can respond to contribution questions, right?

Yes, only students can be team members. However, note that the same person can be a student and an instructor at the same time. So an instructor can be a team member in his role as a student. I don't know to what extent this dual role scenario is handled correctly in the code.

**Comment by whipermr5** [comment]
> Yes, only students can be team members.

I've simplified my solution based on this.

**Comment by whipermr5** [comment]
@damithc Just tried; it already works fine with the existing code even without this change. Two instructors, one with a student role, one without.

File: src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java [hunk 1]
```diff
@@ -555,6 +555,9 @@ public String getQuestionResultStatisticsCsv(
             FeedbackSessionResultsBundle bundle, List<String> teamNames) {
         Map<String, List<String>> teamMembersEmail = new LinkedHashMap<>();
         for (String teamName : teamNames) {
+            if (Const.USER_TEAM_FOR_INSTRUCTOR.equals(teamName)) {
+                continue;
+            }
```
Comment (damithc) [inline src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java]: May be an explanatory comment? I'll leave it to up to you.
