### PR TITLE
[#9595] Migrate INSTRUCTOR_STUDENTS and INSTRUCTOR_STUDENTS_COURSES to new APIs

### LINKED ISSUE #9616: Keep course students card stationary when expanded in Instructor Student Page
- **Environment**: `master` branch at commit 9c97b9c3.

**Steps to reproduce**
1. Go to the `/web/instructor/students`page
1. Click on one of the courses

**Expected behaviour**
The course card should stay at the same position on the screen.

**Actual behaviour**
The course card generally moves down and is not at the same position on the screen.

20190324_13h06_19

**Additional info**
This occurs due to a list of details (like students) being added to the filter on the top of the page in a not so user-friendly way. If there are a lot of students in the course, the expanded card(s) will be moved way below the displayed screen.
This can also be problematic when differentiating between students that have the same email address across different courses .
image (1)

### PR DESCRIPTION
**Pull request by rrtheonlyone**
Part of #9595
Resolves #9616

This PR removes one use two old APIs : '/instructor/students/course' and '/instructor/students'. 

However, more than that this PR helps to refactor the instructor student list page. With discussion from core team and @damithc, it seems like the large filter box is unnecessary in this page. Hence, I have refactored this page and made it more user-friendly for an instructor.

In my opinion, the student list page has a few functions:
1. Let instructors have a single page to look at all the students in their courses
2. A page for instructors to view/edit/enrol students

With this in mind, the new page was done as follows:
Screenshot 2019-04-12 at 8 31 10 PM

Expanding the card:
Screenshot 2019-04-12 at 8 31 21 PM

The logic on the frontend is greatly simplified and many unnecessary functions were removed. The UI/UX is still up for discussion (primary objective was still to migrate out the APIs). @damithc / @wkurniawan07 / @xpdavid do also have a preliminary look when you guys have time and comment if the UI change is needed.

### CODE REVIEW

**Comment by damithc** [comment]
The stats shown at the top is costly because it requires to read all students of this instructor from the database, which could run into thousands. Most likely to hit the 60 sec deadline imposed by GAE. Perhaps we can omit that? For similar reasons, load the student list only when the course panel is expanded?

**Comment by rrtheonlyone** [comment]
That is true @damithc; I did not consider the GAE cost for such a set-up.

I have removed the overall statistics and made them as normal cards (similar to previous set-up without the filter box)
Screenshot 2019-04-13 at 6 00 48 AM

The API calls to `/students` and `/instructor/privilege` is only triggered upon clicking of the card. Following which it would look like this:

Screenshot 2019-04-13 at 6 01 01 AM

Screenshot 2019-04-13 at 6 01 07 AM

**Comment by rrtheonlyone** [comment]
Also, PR is ready for first round of review.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 1]
```diff
@@ -67,461 +25,122 @@ interface GetCourseDetailsResponse {
...
-    const paramMap: { [key: string]: string } = { user };
-    this.httpRequestService.get('/instructor/students/courses', paramMap)
-        .subscribe((resp: GetCourseResponse) => {
-          this.courses = resp.courses;
-
-          if (!this.courses) {
-            this.statusMessageService.showWarningMessage('You do not have any courses yet.');
-          }
+  loadCourses(): void {
+    this.httpRequestService.get('/courses', {
```
Comment (Adoby7) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Make use of courseService here? Same for other API calls

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 2]
```diff
@@ -67,461 +25,122 @@ interface GetCourseDetailsResponse {
...
   /**
-   * Change states of all courses.
+   * Toggles specific card and loads students if needed
    */
-  toggleAllPresentCoursesStateAtInput(defaultState: boolean): void {
-    this.allPresentCourses.forEach((course: Course) => {
-      if (course) {
-        this.toggleCourseStateAtInput(course, defaultState);
+  toggleCard(index: number, courseId: string): void {
+    if (this.viewStudent[index]) {
```
Comment (Adoby7) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: How about `this.viewStudent[index] = !this.viewStudent[index]`, and then load data if necessary

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 3]
```diff
@@ -67,461 +25,122 @@ interface GetCourseDetailsResponse {
...
-   * Get the list of students which need to be hidden on the StudentTable display.
-   */
-  getStudentsToHide(courseId: string): string[] {
-    return this.studentDetailsList
-        .filter((student: StudentDetails) => student.courseId === courseId && !student.isChecked)
-        .map((student: StudentDetails) => student.email);
-  }
+   * Loads students of a specified course.
+   */
+  loadStudents(courseId: string): void {
```
Comment (Adoby7) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: I am not sure, but do we need to make it `private`?

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 4]
```diff
@@ -67,461 +25,122 @@ interface GetCourseDetailsResponse {
...
-    courseDetails.sections.forEach((section: SectionDetails) => {
-      const sectionData: StudentListSectionData = this.mapSectionForStudentList(section);
-      sections.push(sectionData);
-    });
+  loadPrivilege(courseId: string, sectionName: string, students: StudentListStudentData[]): void {
+    this.httpRequestService.get('/instructor/privilege', {
+      courseid: courseId,
+      sectionname: sectionName,
+    }).subscribe((instructorPrivilege: InstructorPrivilege) => {
+      const temp: StudentListSectionData = {
```
Comment (Adoby7) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Avoid just naming it `temp`? It could make others confused

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html [hunk 5]
```diff
@@ -1,157 +1,75 @@
...
-    <div class="form-group">
-      <div class="input-group">
-        <input type="text" class="form-control" [(ngModel)]="searchQuery" (keyup.enter)="search()"
-               placeholder="Charlie Barnes">
-        <div class="input-group-append">
-          <button class="btn btn-primary" (click)="search()">Search</button>
-        </div>
+<h1>Student List</h1>
+<p>
+  This page gives the student details for all your courses. Expand the cards below to view your students. Use the search function if you need to filter for a specific student.
```
Comment (monmanuela) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: Maybe this is better? "...Use the [search function](...) if you need to find a specific student.", and then put a hyperlink from search function to the `Search` page

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html [hunk 6]
```diff
@@ -1,157 +1,47 @@
...
-                  [queryParams]="{courseid: course.id}">
-            Enroll
-          </button>
-          <i class="fas fa-chevron-up pl-3" [hidden]="!course.isChecked"></i>
-          <i class="fas fa-chevron-down pl-3" [hidden]="course.isChecked"></i>
         </div>
       </div>
-      <div class="card-body p-0">
+      <div class="card-body" *ngIf="viewStudent[idx]">
+        <button class="btn" style="background-color: #127c2b; color: white;"
```
Comment (monmanuela) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: After trying it out, I'd suggest against hardcoding the button style (versus using Bootstrap's default settings). In places that use Bootstrap buttons, when I hover over them, there's feedback to the user (button color gets darker), but not with this button.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 7]
```diff
@@ -67,461 +25,122 @@ interface GetCourseDetailsResponse {
...
-   */
-  getStudentsToHide(courseId: string): string[] {
-    return this.studentDetailsList
-        .filter((student: StudentDetails) => student.courseId === courseId && !student.isChecked)
-        .map((student: StudentDetails) => student.email);
-  }
+   * Loads students of a specified course.
+   */
+  loadStudents(courseId: string): void {
+    this.httpRequestService.get('/students', {
```
Comment (ChooJeremy) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: You should use StudentService.getStudentsFromCourse here.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 1 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Okay updated!

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 2 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Yes that is better

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 3 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Looking at out other front end components, I dont think we have enforced this.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 4 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Yes updated!

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html (hunk 5 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: Yes good point! Updated

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 7 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Done!

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html (hunk 6 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: Yes that is a good point. Let us stick with bootstrap colours for now then. (You could update the css to have a darker/lighter shade on hover if needed but thats pretty unnecessary)

**Comment by rrtheonlyone** [comment]
Thanks for review guys @monmanuela , @Adoby7 and @ChooJeremy !

I have made the necessary changes:

@monmanuela : Yes it def looks odd that the statistics are shown only for some cards. We should not make it too obvious that the data is lazy loaded. As per your suggestion I have moved the earlier cards below. It looks like this now:

Screenshot 2019-04-16 at 5 30 07 PM

@ChooJeremy : Good find! The button on the table indeed does not work. This is a reusable component called `<tm-student-list>` which is also used in the course details page. The sorting icons have been added into it. I am not too sure why this is so (perhaps sorting was a feature that is to be included sometime in the future?)

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 8]
```diff
@@ -67,461 +27,115 @@ interface GetCourseDetailsResponse {
...
-    return this.allPresentStudentDetails.filter((studentDetails: StudentDetails) => studentDetails.isChecked);
-  }
-
-  get isAllPresentCoursesChecked(): boolean {
-    return !!this.allPresentCourses.length && this.allPresentCourses.length === this.allCheckedCourses.length;
-  }
+  courseList!: Courses;
+  viewStudent!: boolean[];
+  courseInfo: {[key: string]: StudentListSectionData[]} = {};
+  courseStats: {[key: string]: Statistic} = {};
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: While this is optional. I would recommend you to create a model interface instead of using multiple array and map to track the status.
For example, you can define an interface call `CourseTab`;
```java
interface CourseTab {
    studentListSectionDataList: StudentListSectionData[],
    hasTabExpanded: boolean;
    hasStudentLoaded: boolean; // to track whether the data has been loaded for performance optimization,
    stats: Statistic
}
```

You would use a variable called `courseTabList: CourseTab[]` in the class to track it.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 9]
```diff
@@ -67,461 +27,115 @@ interface GetCourseDetailsResponse {
...
-  loadCourses(user: string): void {
-    const paramMap: { [key: string]: string } = { user };
-    this.httpRequestService.get('/instructor/students/courses', paramMap)
-        .subscribe((resp: GetCourseResponse) => {
-          this.courses = resp.courses;
-
-          if (!this.courses) {
-            this.statusMessageService.showWarningMessage('You do not have any courses yet.');
-          }
+  loadCourses(): void {
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: In this method, you would populate `courseTabList`.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 10]
```diff
@@ -67,461 +27,115 @@ interface GetCourseDetailsResponse {
...
-    });
-  }
-
-  /**
-   * Trigger getting CourseDetails data for a course from backend.
-   */
-  toggleCourseStateAtInput(course: Course, designatedState?: boolean): void {
-    if (course.isChecked === undefined) {
-      course.isChecked = false;
+  toggleCard(index: number, courseId: string): void {
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Now, you can get rid of the index and mapping and change the signature to
```suggestion
  toggleCard(courseTab: CourseTab): void {
```
and manipulate the data inside the tab directly.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 11]
```diff
@@ -1,61 +1,21 @@
...
 import { StudentListSectionData, StudentListStudentData } from '../student-list/student-list-section-data';
 
-interface Course {
-  id: string;
-  name: string;
-  isArchived: boolean;
-  isInstructorAllowedToModify: boolean;
-  isChecked?: boolean;
+interface Statistic {
+  students: number;
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Done

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 12]
```diff
@@ -1,61 +1,21 @@
...
+  sections: number;
+  teams: number;
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Done

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 13]
```diff
@@ -67,461 +27,115 @@ interface GetCourseDetailsResponse {
...
-  }
-
-  get allCheckedStudentDetails(): StudentDetails[] {
-    return this.allPresentStudentDetails.filter((studentDetails: StudentDetails) => studentDetails.isChecked);
-  }
-
-  get isAllPresentCoursesChecked(): boolean {
-    return !!this.allPresentCourses.length && this.allPresentCourses.length === this.allCheckedCourses.length;
-  }
+  courseList!: Courses;
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Yup removed this as per your other suggestion!

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 14]
```diff
@@ -67,461 +27,115 @@ interface GetCourseDetailsResponse {
...
+  viewStudent!: boolean[];
```
[the remark this answers is not in the document]
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Removed this as well.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 9 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Done.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 10 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Done!

**Comment by rrtheonlyone** [comment]
Ready for review.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html [hunk 15]
```diff
@@ -1,157 +1,69 @@
...
 
-<div class="card bg-light mb-4 pb-3">
-  <div class="card-body">
-    <div class="form-group">
-      <div class="input-group">
-        <input type="text" class="form-control" [(ngModel)]="searchQuery" (keyup.enter)="search()"
-               placeholder="Charlie Barnes">
-        <div class="input-group-append">
-          <button class="btn btn-primary" (click)="search()">Search</button>
+<ng-container *ngIf="courseTabList">
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: There is no way that courseTabList can be undefined right?

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 16]
```diff
@@ -67,461 +35,116 @@ interface GetCourseDetailsResponse {
...
+
+            this.loadPrivilege(courseTab, key, data);
+          });
+        }, (resp: ErrorMessageOutput) => { this.statusMessageService.showErrorMessage(resp.error.message); });
+  }
+
+  /**
+   * Loads privilege of an instructor for a specified course and section.
+   */
+  loadPrivilege(courseTab: CourseTab, sectionName: string, students: StudentListStudentData[]): void {
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: This is a bit expensive? Consider using a cache?

File: src/web/services/course.service.ts [hunk 17]
```diff
@@ -25,6 +25,17 @@ export class CourseService {
     return this.httpRequestService.get('/course', paramMap);
   }
 
+  /**
+   * Gets all course data for an instructor by calling API.
+   */
+  getCoursesForInstructor(entityType: string, courseStatus: string): Observable<Courses> {
```
Comment (xpdavid) [inline src/web/services/course.service.ts]: If it is for instructor, the entityType would always be `instructor` right?

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts [hunk 18]
```diff
@@ -67,461 +35,116 @@ interface GetCourseDetailsResponse {
...
+    this.httpRequestService.get('/instructor/privilege', {
```
Comment (xpdavid) [inline src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: Actually, you can generate a new instructors service using `ng g s`.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html (hunk 15 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html]: Yup updated

File: src/web/services/course.service.ts (hunk 17 above)
Comment (rrtheonlyone) [reply src/web/services/course.service.ts]: Yup realised. I have changed the function and made it more general. Both students and instructors can now use this to get all courses.

File: src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts (hunk 16 above)
Comment (rrtheonlyone) [reply src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts]: A cache is useful if Im repeatedly calling this function for the same states. However, it does not seem to be the case here right?

I break down a course into its sections and call this API for each section.

File: src/web/services/course.service.ts [hunk 19]
```diff
@@ -25,6 +25,17 @@ export class CourseService {
     return this.httpRequestService.get('/course', paramMap);
   }
 
+  /**
+   * Gets all course data for an instructor/student by calling API.
+   */
+  getAllCourses(entityType: string, courseStatus: string): Observable<Courses> {
```
Comment (xpdavid) [inline src/web/services/course.service.ts]: Can change or not.

I prefer to hide the entityType in the service. A string type of entityType gives me a sense of nondeterministic :P.

Maybe just `getAllCoursesAsStudent`, `getAllCoursesAsInstructor`.

Comment (xpdavid) [reply src/web/services/course.service.ts]: Actually, those methods already exist in the service. So please change them :P

Comment (rrtheonlyone) [reply src/web/services/course.service.ts]: Updated accordingly!

**Comment by rrtheonlyone** [comment]
Removed old endpoints and made necessary changes.

Ready for final review.
