### PR TITLE
Data Migration: Able to resume/restart from where it fails/stops #9044

### LINKED ISSUE #9044: Data Migration: Able to resume/restart from where it fails/stops
Quote from damith:

> What we need w.r.t. abort/resume is something like this:
Say we need to process 200k entities which takes about 2 hrs but app engine disconnects after 1 hour (i.e., after processing 100k entities). We should be able to run the script again and process the remaining 100k in one more more hour i.e., second run should take 1 hour, not 2 hours. If the script takes one hour to go through the first 100k entities again, we will never be able to finish the migration as everytime we'll get disconnected after processing the first 100k entities.

- Most likely we will need https://github.com/objectify/objectify/wiki/Queries#cursors. 

- Or store all key locally and record the position

Please discuss here before implementation.

### PR DESCRIPTION
**Pull request by xpdavid**
Fixes #9044 

**Outline of Solution**

- In the script, data is fetch in batch (default to 100 entities each round) (so no chance to have `OutOfMemoryError`). In addition, the cursor position will also be printed after each batch. 

- By copying the cursor position printed on the console and paste it into the code, the script will start from the position specified instead of staring the query again.

<hr>

I have provided a sample script for #9060 

In order to create orphaned student profile. The following java code can be used:

```java
package teammates.client.scripts;

import java.io.IOException;
import java.lang.reflect.Field;

import teammates.client.remoteapi.RemoteApiClient;
import teammates.storage.entity.StudentProfile;

public class CreateOrphanedStudentProfile extends RemoteApiClient {
    public static void main(String[] args) throws IOException {
        new CreateOrphanedStudentProfile().doOperationRemotely();
    }

    @Override
    protected void doOperation() {
        try {
            StudentProfile sp = new StudentProfile("sp.test");
            Field accountField = sp.getClass().getDeclaredField("account");
            accountField.setAccessible(true);
            accountField.set(sp, null);
            ofy().save().entity(sp).now();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

``` 

<hr>

Here is the sample output when it is run

```
--- Starting remote operation ---
Going to connect to:6-10-2-dot-teammates-xiaopu.appspot.com:443
Running DataMigrationForOrphanedStudentProfile...
Preview: false
Start from the beginning, you may want to record the cursor position
in order to start from the last stopped position when re-run the script.
Cursor Position: Cm0SZ2oSc350ZWFtbWF0ZXMteGlhb3B1clELEgdBY2NvdW50IhhJQ0pDb25maXJtYXRpb25VaVQuaW5zdHIMCxIOU3R1ZGVudFByb2ZpbGUiGElDSkNvbmZpcm1hdGlvblVpVC5pbnN0cgwYACAA
Number Of Entity Key Scanned: 100
Number Of Entity affected: 0
Number Of Entity updated: 0
Deleting orphaned StudentProfile now! Key<?>(StudentProfile("xp.test"))
Deleting orphaned StudentProfile now! Key<?>(StudentProfile("xp1.test"))
Cursor Position: CjgSMmoSc350ZWFtbWF0ZXMteGlhb3B1chwLEg5TdHVkZW50UHJvZmlsZSIIeHAxLnRlc3QMGAAgAA
Number Of Entity Key Scanned: 198
Number Of Entity affected: 2
Number Of Entity updated: 2
Migration Completed!
Total number of StudentProfiles: 198
Number of affected StudentProfiles: 2
Number of updated StudentProfiles: 2
--- Remote operation completed ---
```

For example `Cm0SZ2oSc350ZWFtbWF0ZXMteGlhb3B1clELEgdBY2NvdW50IhhJQ0pDb25maXJtYXRpb25VaVQuaW5zdHIMCxIOU3R1ZGVudFByb2ZpbGUiGElDSkNvbmZpcm1hdGlvblVpVC5pbnN0cgwYACAA` should be pasted to `getLastPositionOfCursor()` if the administrator want to skip the first 100 entities.

### CODE REVIEW

**Comment by xpdavid** [comment]
@tran-tien-dat Can have a look? XD

File: src/client/java/teammates/client/scripts/DataMigrationWithCheckpointForEntities.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+                filterQueryKeys = filterQueryKeys.startAt(cursor);
+            }
+            QueryResultIterator<Key<T>> iterator = filterQueryKeys.keys().iterator();
+
+            while (iterator.hasNext()) {
+                shouldContinue = true;
+                Key<T> keyOfEntityToMigrate = iterator.next();
+
+                // get entity type
+                if (entityType.isEmpty()) {
```
Comment (tran-tien-dat) [inline src/client/java/teammates/client/scripts/DataMigrationWithCheckpointForEntities.java]: `entityType` is initialized to `"Unknown"` above, not an empty string.

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    }
+
+    @Override
+    protected String getLastPositionOfCursor() {
+        return "";
+    }
+
+    @Override
+    protected boolean isPreview() {
+        return true;
```
Comment (tran-tien-dat) [inline src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: Should `isPreview` and `lastPositionOfCursor` be passed in as command line arguments instead so that we don't need to change the source code and recompile?

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+ */
+public class DataMigrationForOrphanedStudentProfile extends DataMigrationWithCheckpointForEntities<StudentProfile> {
+
+    public static void main(String[] args) throws IOException {
+        new DataMigrationForOrphanedStudentProfile().doOperationRemotely();
+    }
+
+    @Override
+    protected Query<StudentProfile> getFilterQuery() {
+        return ofy().load().type(StudentProfile.class);
```
Comment (tran-tien-dat) [inline src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: Should this be the default `getFilterQuery`?

**Comment by tran-tien-dat** [comment]
```
Total number of StudentProfiles: 198
Number of affected StudentProfiles: 2
Number of updated StudentProfiles: 2
```

Is it a coincidence that 198 + 2 = 200?

I think this is a good idea. We just need to try on a server with a lot of data to optimize the batch size.

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 3 above)
Comment (xpdavid) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: This method is an abstract method the framework is designed to be used in other migration script (such as `DataMigrationForSessions`, we don't have a chance to run it as the data size is too big).

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 2 above)
Comment (xpdavid) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: I think the script is always run in IDE and it is the way [recommended](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#running-client-scripts)?

**Comment by xpdavid** [comment]
> Is it a coincidence that 198 + 2 = 200?

Yes

> We just need to try on a server with a lot of data to optimize the batch size.

Yes. I need to take a look at the LIVE datastore to determine the batch size.

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 3 above)
Comment (tran-tien-dat) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: I mean using the generic T instead of `StudentProfile`but then there's the problem of figuring out the runtime class of T to pass to this function

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 2 above)
Comment (tran-tien-dat) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: You can still pass command line arguments when running in the IDE. My point is to eliminate the recompilation of the program. For this simple program it doesn't make a difference

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 3 above)
Comment (xpdavid) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: And we may want to have addition filtering instead of just loading of all entities.

e.g.
```
ofy()
    .load()
    .type(Account.class)
    .filter('isInsturctor =', true)
```

although still doable if we want to auto-detect the generic class.

The [detection](https://stackoverflow.com/questions/1004022/java-generic-class-determine-type) is doable although but will introduce unnecessary complication I think.

File: src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java (hunk 2 above)
Comment (xpdavid) [reply src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java]: I agree that by right such parameter should be in command line or configuration file. But consider we usually run the script in IDE, it would be more convenient for the Admin to change the code than to change the run configuration.

**Comment by xpdavid** [comment]
@damithc How many entities do we have for StudentProfile in LIVE?

https://console.cloud.google.com/datastore/stats?&kind=StudentProfile

**Comment by damithc** [comment]
> @damithc How many entities do we have for StudentProfile in LIVE?

61363
