### PR TITLE
[#9689] Fix broken LNP test of put /students

### LINKED ISSUE #9689: LNP test of put /students is broken
After API consolidation #9647, the LNP test of the endpoint fails.

### PR DESCRIPTION
**Pull request by Adoby7**
Fixes #9689 

Modify the LNP test for the put '/students' after consolidation

### CODE REVIEW

File: src/e2e/java/teammates/e2e/cases/lnp/InstructorStudentEnrollmentLNPTest.java [hunk 1]
```diff
@@ -108,25 +110,25 @@ protected LNPTestData getTestData() {
...
+                        enrollRequests.add(
+                                new StudentsEnrollRequest.StudentEnrollRequest(name, email, team, section, comment));
                     }
-                    enrollData.append('\"');
-                    csvRow.add(enrollData.toString());
+                    StudentsEnrollRequest requestBody = new StudentsEnrollRequest(enrollRequests);
+
+                    // Sanitize the data for CSV entry.
+                    String enrollData = String.format("\"%s\"",
+                            JsonUtils.toJson(requestBody).replace("\n", "").replace("\"", "\"\""));
```
Comment (wkurniawan07) [inline src/e2e/java/teammates/e2e/cases/lnp/InstructorStudentEnrollmentLNPTest.java]: Let's extract this out somewhere? This operation will be necessary for all requests which have request body.

File: src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java [hunk 2]
```diff
@@ -234,4 +234,11 @@ protected void deleteDataFiles() throws IOException {
         Files.delete(Paths.get(pathToCsvFile));
     }
 
+    /**
+     * Sanitize the JSON string to be CSV data.
+     */
+    protected String sanitizeJsonString(String json) {
+        return String.format("\"%s\"", json.replace("\n", "").replace("\"", "\"\""));
```
Comment (wkurniawan07) [inline src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java]: - The method name should be `sanitizeForCsv` because (1) it needs not be JSON and (2) the sanitization policy is specifically for CSV
- You may want to use `System.lineSeparator()` instead of hard-coded `\n`

File: src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java [hunk 3]
```diff
@@ -234,4 +234,11 @@ protected void deleteDataFiles() throws IOException {
         Files.delete(Paths.get(pathToCsvFile));
     }
 
+    /**
+     * Sanitize the data to be CSV data.
```
Comment (wkurniawan07) [inline src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java]: - ~data~ string, because the purpose of the string is not relevant
- CSV<b>-safe</b> ~data~ string

Comment (amrut-prabhu) [reply src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java]: Also, change to `Sanitizes`
