### PR TITLE
[#9791] Instructor Student Page: `Send Invite` button show error message

### LINKED ISSUE #9791: Instructor Student Page: `Send Invite` button show error message
- **Environment**: `master` branch at commit 30f56ffea3016decff6026cc46bb03e346ab7ffd

**Steps to reproduce**
1. log in as an instructor
2. go to student page and find a yet to join student
3. click the `Send Invite` button for that student

**Expected behaviour**
navigate to the course detail page and show email is sent success message

**Actual behaviour**
erroe

**Additional info**
the navigation does not receive the correct params. i.e. courseid

### PR DESCRIPTION
**Pull request by crizyli**
Fixes #9791 

Ready for review

### CODE REVIEW

**Comment by erjillsison** [comment]
LGTM

File: src/web/app/pages-instructor/student-list/student-list.component.ts [hunk 1]
```diff
@@ -81,8 +81,9 @@ export class StudentListComponent implements OnInit {
   remindStudentFromCourse(studentEmail: string): void {
     this.courseService.remindStudentForJoin(this.courseId, studentEmail)
       .subscribe((resp: MessageOutput) => {
-        this.navigationService.navigateWithSuccessMessagePreservingParams(this.router,
-            '/web/instructor/courses/details', resp.message);
+        const params: { [key: string]: string } = { courseid: this.courseId };
+        this.navigationService.navigateWithSuccessMessageNewParams(this.router,
+            '/web/instructor/courses/details', resp.message, params);
```
Comment (xpdavid) [inline src/web/app/pages-instructor/student-list/student-list.component.ts]: Why not just do
```javascript
`/web/instructor/courses/details?courseid={this.courseId}`
```
