### PR TITLE
Submission confirmation email: the time stamp given in the email is incorrect #6101

### LINKED ISSUE #6101: Submission confirmation email: the time stamp given in the email is incorrect
The time should be based on user's time zone, not the server's time zone.
image

### PR DESCRIPTION
**Pull request by sznicci**
Fixes #6101

It is an alternative solution for the PR #6140 .

### CODE REVIEW

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 1]
```diff
@@ -205,22 +205,56 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
         email = new EmailGenerator().generateFeedbackSubmissionConfirmationEmailForInstructor(session,
-                instructor1, TimeHelper.formatTime12H(time.getTime()));
+                instructor1, timeForInstructor);
         subject = String.format(EmailType.FEEDBACK_SUBMISSION_CONFIRMATION.getSubject(), course.getName(),
                                 session.getFeedbackSessionName());
         verifyEmail(email, instructor1.email, subject, "/sessionSubmissionConfirmationEmailForInstructor.html");
+        
+        ______TS("feedback session submission email with Singapore timezone");
+
+        session.setTimeZone(12.75);
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Prior to this, `session` has a timezone value of +2 (you can look at the changes of two of the email results), which is also a positive value. You should try a negative value and a zero value for complete coverage.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 2]
```diff
@@ -205,22 +205,56 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
+        timeForStudent.set(Calendar.HOUR_OF_DAY, 5);
+        timeForStudent.set(Calendar.MINUTE, 30);
         EmailWrapper email = new EmailGenerator().generateFeedbackSubmissionConfirmationEmailForStudent(
-                session, student1, TimeHelper.formatTime12H(time.getTime()));
+                session, student1, timeForStudent);
         subject = String.format(EmailType.FEEDBACK_SUBMISSION_CONFIRMATION.getSubject(), course.getName(),
                                 session.getFeedbackSessionName());
         verifyEmail(email, student1.email, subject, "/sessionSubmissionConfirmationEmailForStudent.html");
 
+        Calendar timeForInstructor = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Just use one `Calendar` instance, like how it is done before. It makes manual checking easier: keep the time in the `Calendar` instance in memory and work out the timestamp in the email using the session's timezone.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 3]
```diff
@@ -205,22 +205,56 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
-                instructor1, TimeHelper.formatTime12H(time.getTime()));
+                instructor1, timeForInstructor);
         subject = String.format(EmailType.FEEDBACK_SUBMISSION_CONFIRMATION.getSubject(), course.getName(),
                                 session.getFeedbackSessionName());
         verifyEmail(email, instructor1.email, subject, "/sessionSubmissionConfirmationEmailForInstructor.html");
+        
+        ______TS("feedback session submission email with Singapore timezone");
+
+        session.setTimeZone(12.75);
+        Calendar timeForStudentSingapore = Calendar.getInstance(TimeZone.getTimeZone("GMT+08:00"));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: Although this would have been removed due to one of the previous comments, using "GMT+08:00" is not recommended because the `TimeHelper` utility is pre-set to UTC.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 4]
```diff
@@ -205,22 +205,56 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
+        timeForStudentSingapore.set(Calendar.MONTH, 8);
+        timeForStudentSingapore.set(Calendar.HOUR_OF_DAY, 10);
+        timeForStudentSingapore.set(Calendar.MINUTE, 30);
+        EmailWrapper emailSingapore = new EmailGenerator()
+                .generateFeedbackSubmissionConfirmationEmailForStudent(
+                        session, student1, timeForStudentSingapore);
+        subject = String.format(EmailType.FEEDBACK_SUBMISSION_CONFIRMATION.getSubject(), course.getName(),
+                session.getFeedbackSessionName());
+        verifyEmail(emailSingapore, student1.email, subject,
+                "/sessionSubmissionConfirmationEmailForStudentServerSingapore.html");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: You do not need to duplicate the emails because it's the same for both student and instructor; earlier it was done for coverage purpose. Now since there are multiple test case, we can do it this way:
- Test case 1: for student in positive timezone
- Test case 2: for instructor in negative timezone
- Test case 3: for student/instructor (free to choose) in zero timezone

You may need to rename the email result files.

**Comment by sznicci** [comment]
Hi @wkurniawan07 I have made the changes you requested. It is ready for review again.

File: src/test/resources/emails/sessionSubmissionConfirmationEmailNegativeTimeZone.html [hunk 5]
```diff
@@ -1,7 +1,7 @@
 Hello Instructor1 Course1,
 
 <p/>
-The feedback responses for the following feedback session has been successfully submitted by you on Sun, 04 Sep 2016, 05:30 AM.
+The feedback responses for the following feedback session has been successfully submitted by you on Sat, 03 Sep 2016, 10:00 PM.
```
Comment (wkurniawan07) [inline src/test/resources/emails/sessionSubmissionConfirmationEmailNegativeTimeZone.html]: This should be 8:00 PM (by manual checking).

File: src/test/resources/emails/sessionSubmissionConfirmationEmailZeroTimeZone.html [hunk 6]
```diff
@@ -0,0 +1,17 @@
+Hello Instructor1 Course1,
+
+<p/>
+The feedback responses for the following feedback session has been successfully submitted by you on Sat, 03 Sep 2016, 10:00 PM.
```
Comment (wkurniawan07) [inline src/test/resources/emails/sessionSubmissionConfirmationEmailZeroTimeZone.html]: Similarly, this should be 4 Sep 2016 5:30AM because it is at zero timezone.

File: src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java [hunk 7]
```diff
@@ -205,22 +205,33 @@ public void testGenerateFeedbackSessionEmails() throws IOException {
...
+        verifyEmail(email, instructor1.email, subject,
+                "/sessionSubmissionConfirmationEmailNegativeTimeZone.html");
+
+        session.setTimeZone(0.0);
+        email = new EmailGenerator().generateFeedbackSubmissionConfirmationEmailForInstructor(session,
+                instructor1, time);
+        subject = String.format(EmailType.FEEDBACK_SUBMISSION_CONFIRMATION.getSubject(), course.getName(),
+                session.getFeedbackSessionName());
+        verifyEmail(email, instructor1.email, subject,
+                "/sessionSubmissionConfirmationEmailZeroTimeZone.html");
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java]: This is aesthetic and you can ignore if you want, but you may consider:
- Aligning `[s]ession` with `[E]mailType`
- Moving this line to the line before since it does not exceed the line length limit

Applies also to the other instances of this routine. Essentially, look at the changes introduced in lines 216-218 and try to do it such that the change is minimized.

**Comment by sznicci** [comment]
Hi @wkurniawan07 I have made the changes you requested. It is ready for review again.
