### PR TITLE
[#9542] Cannot load any public page

### LINKED ISSUE #9542: Cannot load any public page
**Environment**: 061f8456b51553e16b905811d2ecc7531c9a3140

**Steps to reproduce**

Visit `/web/sessions/result` or `/web/sessions/submission`

**Expected behaviour**

There should be something showing up even there is no URL parameter.

**Actual behaviour**

image

Empty page.

**Additional info**

Regression from https://github.com/TEAMMATES/teammates/pull/9527 @monmanuela  :P `PublicPageComponent` will always have `isFetchingAuthDetails` === `true`. Actually, setting this value to `true` by default is problematic. We cannot assume every single page to be initialised with a fetching auth details request. It should be `false` by default and setting it to `true` when a page is actually sending the request.

### PR DESCRIPTION
**Pull request by monmanuela**
Fixes #9542

**Outline of Solution**
Now `isFetchingAuthDetails` is set to `false` by default, only set to `true` just before the request is sent, and set back to `false` when the result is returned.

The public page is correctly shown:
`/web/sessions/result`
image

`/web/sessions/submission`
image

### CODE REVIEW

File: src/web/app/pages-instructor/instructor-page.component.ts [hunk 1]
```diff
@@ -44,14 +44,15 @@ export class InstructorPageComponent implements OnInit {
...
-  isFetchingAuthDetails: boolean = true;
+  isFetchingAuthDetails: boolean = false;
 
   private backendUrl: string = environment.backendUrl;
 
   constructor(private route: ActivatedRoute, private authService: AuthService) {}
 
   ngOnInit(): void {
     this.route.queryParams.subscribe((queryParams: any) => {
+      this.isFetchingAuthDetails = true;
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-page.component.ts]: This should be set outside the `this.route.queryParams.subscribe` block? Same for the others where applicable.
