### PR TITLE
Subtle bugs introduced by too many .parent() #3874

### LINKED ISSUE #3874: Subtle bugs introduced by too many .parent()
The following code and / or other variants are duplicated (sometimes with changes) in many places.

screen shot 2015-07-03 at 4 37 25 pm

.parent().parent().parent().... is never recommended because a small DOM tree change can cause subtle bugs.

screen shot 2015-07-03 at 4 34 40 pm
screen shot 2015-07-03 at 4 34 36 pm

From the above, the variable form actually selects the entire HTML when it meant to select the form above.

.parentsUntil() coupled with a CSS selector, class or id is more maintainable and recommended.

The following bug was introduced ->

screen shot 2015-07-03 at 4 42 24 pm

and it was also not being checked by our tests and the values were thus being removed unintentionally.

It will be added back in #3822 because the DOM tree has changed but it is not a permanent fix.

All the code with multiple chains of .parent().parent().... should be changed.

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #3874

### CODE REVIEW

**Comment by JosephineKwa** [comment]
@junhaoyap hope you don't mind reviewing this :)

**Comment by junhaoyap** [comment]
@JosephineKwa sure :)

File: src/main/webapp/js/adminSearch.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ function submitResetGoogleIdAjaxRequest(studentCourseId, studentEmail, wrongGoog
                  + '&courseid=' + studentCourseId
                  + '&googleid=' + wrongGoogleId;
     
-    var googleIdEntry = $(button).parent().parent().children().find('.homePageLink');
+    var googleIdEntry = $(button).closest('.studentRow').find('.homePageLink');
```
Comment (junhaoyap) [inline src/main/webapp/js/adminSearch.js]: Good one here, confused me for a moment because ```.find('.homePageLink')``` was chained onto ```.children()``` 👍

File: src/main/webapp/js/omniComment.js [hunk 2]
```diff
@@ -223,19 +223,19 @@ $(document).ready(function() {
...
-                var commentListRegionForFeedbackResponse = $(comment).parent().parent().parent();
+                var commentListRegionForFeedbackResponse = $(comment).closest('tr');
                 // a fbResponse in instructorCommentsPage (html) is made up of 4 rows as the followings
                 commentListRegionForFeedbackResponse.show();
                 commentListRegionForFeedbackResponse.prev().show();
                 commentListRegionForFeedbackResponse.prev().prev().show();
                 commentListRegionForFeedbackResponse.prev().prev().prev().show();
                 
-                var feedbackQuestion = commentListRegionForFeedbackResponse.parent().parent().parent();
+                var feedbackQuestion = commentListRegionForFeedbackResponse.closest('.panel');
```
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: For this and the rest below, is there an ID that we can select instead?

File: src/main/webapp/js/omniComment.js [hunk 3]
```diff
@@ -223,19 +223,19 @@ $(document).ready(function() {
         // if not all list elements are hidden within fbResponse, then show fbResponse
         if ($(comment).prop('class').toString().includes(classNameForCommentsInFeedbackResponse)) {
             if ($(comment).parent().find('li[style*="display: none"]').length !== $(comment).parent().find('li').length) {
-                var commentListRegionForFeedbackResponse = $(comment).parent().parent().parent();
+                var commentListRegionForFeedbackResponse = $(comment).closest('tr');
```
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: Unrelated to your changes - this whole portion seems to need a good revamp some day, the comment object is constantly being rewrapped into a jQuery object unnecessarily (once is enough) and the code below reminds me of what we are fixing in this PR ```.parent().parent()...``` and ```.prev().prev().prev()...``` :D

File: src/main/webapp/js/omniComment.js [hunk 4]
```diff
@@ -86,16 +86,16 @@ $(document).ready(function() {
             $('#no-comment-panel').show();
             // if all is checked, show giver and status for better user experience
             if (!$('#panel_all').prop('checked')) {
-                $('#giver_all').parent().parent().hide();
-                $('#status_all').parent().parent().hide();
+                $('#giver_all').closest('.col-sm-4').hide();
```
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: Same here, for these and the rest below do we have a better class or an ID to select? It's not that safe to select based on a bootstrap class as future HTML changes can easily break this selection since column classes in CSS libraries are often used for layout

File: src/main/webapp/js/feedbackResponseComments.js [hunk 5]
```diff
@@ -5,8 +5,8 @@ function isInCommentsPage() {
 var addCommentHandler = function(e) {
     var submitButton = $(this);
     var cancelButton = $(this).next("input[value='Cancel']");
-    var formObject = $(this).parent().parent();
-    var addFormRow = $(this).parent().parent().parent();
+    var formObject = $(this).closest('form');
+    var addFormRow = formObject.parent();
```
Comment (junhaoyap) [inline src/main/webapp/js/feedbackResponseComments.js]: Is there a class or ID that we can select and reuse ```.closest``` ?

File: src/main/webapp/js/feedbackResponseComments.js [hunk 6]
```diff
@@ -66,8 +66,8 @@ var addCommentHandler = function(e) {
 var editCommentHandler = function(e) {
     var submitButton = $(this);
     var cancelButton = $(this).next("input[value='Cancel']");
-    var formObject = $(this).parent().parent();
-    var displayedText = $(this).parent().parent().prev();
+    var formObject = $(this).closest('form');
+    var displayedText = formObject.prev();
```
Comment (junhaoyap) [inline src/main/webapp/js/feedbackResponseComments.js]: Same here, if we can, that'll be better and it helps us be more flexible in future HTML changes

**Comment by junhaoyap** [comment]
Great work here @JosephineKwa, let me know based on my questions and ping me again, mostly just  about making it more flexible for future HTML changes if possible, if not we can leave it as it is :)

File: src/main/webapp/js/omniComment.js (hunk 2 above)
Comment (JosephineKwa) [inline src/main/webapp/js/omniComment.js]: This doesn't have an id, only `<div class="panel panel-info">` :open_mouth:

File: src/main/webapp/js/omniComment.js (hunk 4 above)
Comment (JosephineKwa) [inline src/main/webapp/js/omniComment.js]: This doesn't have an id either. Only, `<div class="col-sm-4">`. I had originally wanted to add a class to the div to get `<div class="col-sm-4 filter-options">` but I removed it to avoid godmode changes. Would doing adding the `filter-options` class be preferred?

File: src/main/webapp/js/feedbackResponseComments.js (hunk 5 above)
Comment (JosephineKwa) [inline src/main/webapp/js/feedbackResponseComments.js]: Yup:), I will edit to use the ID instead

File: src/main/webapp/js/omniComment.js (hunk 3 above)
Comment (JosephineKwa) [inline src/main/webapp/js/omniComment.js]: I will create an issue for this, I was tempted to fix the `.prev()`s in this PR :stuck_out_tongue:

File: src/main/webapp/js/omniComment.js (hunk 2 above)
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: Is it a commonly used class? If not then I suppose we can leave it as it is

File: src/main/webapp/js/omniComment.js (hunk 3 above)
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: Tempting indeed 😛

File: src/main/webapp/js/omniComment.js (hunk 4 above)
Comment (junhaoyap) [inline src/main/webapp/js/omniComment.js]: I would really prefer adding something like that than selecting a commonly used bootstrap class 👍

File: src/main/webapp/js/feedbackResponseComments.js (hunk 5 above)
Comment (junhaoyap) [inline src/main/webapp/js/feedbackResponseComments.js]: 👍  Great

**Comment by JosephineKwa** [comment]
Ready for review!

**Comment by junhaoyap** [comment]
@damithc same question :D looks great to merge @JosephineKwa
