### PR TITLE
[#9423] Links in the Instructor help page to other questions cards do not work

### LINKED ISSUE #9423: Links in the Instructor help page to other questions cards do not work
To recreate:- Open Instructor Help Page and try to click on any links that should lead to a section on the same page. These include the links to the question sections at the top, as well as the links in answers to other answers.

### PR DESCRIPTION
**Pull request by aishaadambek**
Fixes #9423.

**A bit of context**
None of the links to other question cards on the same page worked because:

- they referred to the yet non-existing ids,

- passive links used `hrefs` when they should be using `routerLinks` instead (see a similar issue for Angular 5 or above discussed on [StackOverflow](https://stackoverflow.com/questions/35639174/passive-link-in-angular-2-a-href-equivalent)).

Desired behavior is to jump to the specific question card once the link is pressed. The question card's content (i.e. answer to the question) should be collapsed. Otherwise, the behavior may be confusing to the user.

**Outline of Solution**
Thus, the solution was carried out as follows:
1. All the missing ids of the template elements were added;
2. 'Jumping' to questions was implemented with a method that scrolls into the specified question (as, unfortunately, using `data-target` attributes for anchor tags turned out to be non-working or buggy/messy for Angular 8. Correct me if I am wrong);
3. Passive links were built using `RouterModule`'s `routerLink` attribute;
4. Collapsing question contents was implemented with simply toggling corresponding boolean values for `NgbCollapse` directive;
5. Toggling boolean values from other components was implemented with a simple data sharing service;
6. A simple test was added for a data sharing service.

I must admit that in some places this solution is not the most elegant and quite 'hacky'. In particular, see items 4 and 5 that describe how 'collapsing question contents' was implemented. Nonetheless, as far as I could see from a quite through web/documentation search, these are the best alternatives available. I am just a beginner in Angular development, though, so, if anyone can give hints/advice/ideas on a better workaround, I would be thankful.

### CODE REVIEW

**Comment by aishaadambek** [comment]
Hi team! :)

I am leaving this comment because as specified in the [Development Workflow document](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-5-following-up) if a PR is not assigned to a reviewer in 24 hours, a PR author/contributor can leave a comment to remind about the open PR.

Looking forward to working on this!

File: src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts [hunk 1]
```diff
@@ -14,11 +15,54 @@ export class InstructorHelpCoursesSectionComponent extends InstructorHelpSection
...
+  isCollapsed10: boolean = false;
+  isCollapsed11: boolean = false;
+  isCollapsed12: boolean = false;
+  isCollapsed13: boolean = false;
+  isCollapsed14: boolean = false;
+  isCollapsed15: boolean = false;
+  isCollapsed16: boolean = false;
+  isCollapsed17: boolean = false;
+  isCollapsed18: boolean = false;
+  isCollapsed19: boolean = false;
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts]: Can we improve the naming?

File: src/web/services/instructor-help-data-sharing.service.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
+import { Injectable } from '@angular/core';
+import { BehaviorSubject, Observable } from 'rxjs';
+
+/**
+ * Handles sharing data to manage elements to be collapsed when following anchor tags.
```
Comment (xpdavid) [inline src/web/services/instructor-help-data-sharing.service.ts]: Why we need service to handle collapse event?

File: src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts (hunk 1 above)
Comment (xpdavid) [reply src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts]: Same for multiple places

Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts]: Sorry, sure. I was hesitant to modify the variable names that had been there before. 

Changes now made, please see the last commits below. I will be happy to work further on naming if needed.

File: src/web/services/instructor-help-data-sharing.service.ts (hunk 2 above)
Comment (aishaadambek) [reply src/web/services/instructor-help-data-sharing.service.ts:5]: Yes, it also looks a bit like overkill to me. 

However, the instructor help page consists of several components and, as I mentioned in the PR description, I did not manage to find a better way to handle/trigger collapse event in component Y from component X. I am a beginner in Angular development, though, and I will be happy to try alternative approaches if any!

Comment (xpdavid) [reply src/web/services/instructor-help-data-sharing.service.ts:5]: Why not trying `componentA -(event)-> parentComponent -(update)-> componentB`

Comment (aishaadambek) [reply src/web/services/instructor-help-data-sharing.service.ts]: Ah yes, makes sense!

Changes made, please see the last commits below.

File: src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts [hunk 3]
```diff
@@ -12,6 +12,18 @@ import { InstructorHelpSectionComponent } from '../instructor-help-section.compo
...
+  isEssayQsCollapsed: boolean = false;
+  isMCQSingleCollapsed: boolean = false;
+  isMCQMultCollapsed: boolean = false;
+  isNumScaleCollapsed: boolean = false;
+  isPtsOptionsCollapsed: boolean = false;
+  isPtsRecipientsCollapsed: boolean = false;
+  isContribQsCollapsed: boolean = false;
+  isRubricQsCollapsed: boolean = false;
+  isRankOptsCollapsed: boolean = false;
+  isRankRcptsCollapsed: boolean = false;
```
Comment (madanalogy) [inline src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts:24]:
```suggestion
  isRankOptionsCollapsed: boolean = false;
  isRankRecipientsCollapsed: boolean = false;
```

Might be worthwhile to make these more verbose, could  easily be misread considering that you utilised "Pts" to mean "Points" earlier.

File: src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts [hunk 4]
```diff
@@ -106,11 +107,21 @@ export class InstructorHelpStudentsSectionComponent extends InstructorHelpSectio
...
   }];
 
+  @Input() collapseStudentEditDetailsInChild: Subject<boolean> = new Subject<boolean>();
+  isEditDetailsCollapsed: boolean = false;
+  isViewProfileCollapsed: boolean = false;
+  isViewAllRespCollapsed: boolean = false;
+  isStudSearchCollapsed: boolean = false;
+  isStudEmailCollapsed: boolean = false;
+  isGoogleAccCollapsed: boolean = false;
+  isChangeGoogleIDCollapsed: boolean = false;
```
Comment (madanalogy) [inline src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts:117]:
```suggestion
  isChangeGoogleIdCollapsed: boolean = false;
```

Just a nit to adhere to camelCase

File: src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts [hunk 5]
```diff
@@ -11,11 +12,42 @@ import { InstructorHelpSectionComponent } from '../instructor-help-section.compo
...
+  isPreviewCollapsed: boolean = false;
+  isCannotSubmitCollapsed: boolean = false;
+  isViewResCollapsed: boolean = false;
+  isViewAllRespCollapsed: boolean = false;
+  isAddCmntCollapsed: boolean = false;
+  isEditDelCmntCollapsed: boolean = false;
+  isSearchCollapsed: boolean = false;
+  isViewDelCollapsed: boolean = false;
+  isRestoreSnCollapsed: boolean = false;
+  isDelSnCollapsed: boolean = false;
```
Comment (madanalogy) [inline src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts:28]:
```suggestion
  isRestoreSessionCollapsed: boolean = false;
  isDelSessionCollapsed: boolean = false;
```

File: src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts [hunk 6]
```diff
@@ -11,11 +12,42 @@ import { InstructorHelpSectionComponent } from '../instructor-help-section.compo
 })
 export class InstructorHelpSessionsSectionComponent extends InstructorHelpSectionComponent implements OnInit {
 
+  @Input() collapsePeerEvalTipsInChild: Subject<boolean> = new Subject<boolean>();
+  isPeerEvalTipsCollapsed: boolean = false;
+  isNewFSessionCollapsed: boolean = false;
```
Comment (madanalogy) [inline src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts:17]:
```suggestion
  isNewFeedbackSessionCollapsed: boolean = false;
```

Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts]: Done.

File: src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts (hunk 5 above)
Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts]: Done.

File: src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts (hunk 4 above)
Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts]: Done.

File: src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts (hunk 3 above)
Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts]: Done.

**Comment by aishaadambek** [comment]
> I believe that the names could afford to be more verbose for clarity. It will greatly help future programmers who might need to refer to the code you wrote (might be you). The cost of that extra effort will go a long way down the road :)
> 
> That being said, my review comments are only targeted at specific names that I feel are likely to cause confusion. I'll leave discretion of the remaining names to you.

Yes, it makes sense to me! I was hesitant about whether the verbosity of the variable names is worth it. Thank for the tips! :)

Changes are made now. Please see the last commits.

File: src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts [hunk 7]
```diff
@@ -14,11 +14,48 @@ export class InstructorHelpCoursesSectionComponent extends InstructorHelpSection
...
     super();
   }
 
   ngOnInit(): void {
+  }
 
+  /**
+   * To scroll to a specific HTML id
+   */
+  jumpTo(target: string): boolean {
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts:49]: I think there is a `pageScrollService` integrated in the code base. Can you try to integrate that?

File: src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts [hunk 8]
```diff
@@ -11,11 +12,42 @@ import { InstructorHelpSectionComponent } from '../instructor-help-section.compo
...
 
   ngOnInit(): void {
+    this.collapsePeerEvalTipsInChild.subscribe(
+        (isPeerEvalTipsCollapsed: boolean) => this.isPeerEvalTipsCollapsed = isPeerEvalTipsCollapsed);
+  }
+
+  /**
+   * To scroll to a specific HTML id
+   */
+  jumpTo(target: string): boolean {
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts:43]: Same here

File: src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts [hunk 9]
```diff
@@ -26,4 +38,19 @@ export class InstructorHelpQuestionsSectionComponent extends InstructorHelpSecti
   ngOnInit(): void {
   }
 
+  /**
+   * To scroll to a specific HTML id
+   */
+  jumpTo(target: string): boolean {
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts:44]: Same here

File: src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts [hunk 10]
```diff
@@ -17,6 +18,8 @@ export class InstructorHelpPageComponent implements OnInit, AfterViewInit {
   readonly supportEmail: string = environment.supportEmail;
   searchTerm: String = '';
   key: String = '';
+  collapseStudentEditDetailsInChild: Subject<boolean> = new Subject<boolean>();
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts:21]: I think this can just be
```suggestion
  collapseStudentEditDetailsInChild: boolean = false;
```

File: src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts [hunk 11]
```diff
@@ -63,4 +66,18 @@ export class InstructorHelpPageComponent implements OnInit, AfterViewInit {
     this.searchTerm = '';
     this.key = '';
   }
+
+  /**
+   * Collapses question card on student edit details in Students section.
+   */
+  collapseStudentEditDetails(event: boolean): void {
+    this.collapseStudentEditDetailsInChild.next(event);
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts:74]: So here can just be
```suggestion
    collapseStudentEditDetailsInChild = event;
```

File: src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts [hunk 12]
```diff
@@ -106,11 +107,21 @@ export class InstructorHelpStudentsSectionComponent extends InstructorHelpSectio
     ],
   }];
 
+  @Input() collapseStudentEditDetailsInChild: Subject<boolean> = new Subject<boolean>();
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts:110]: There is no need to have this `@Input`.

Instead we can add `@Input` to `isEditDetailsCollapsed`.

We can directly pass the attribute: `<tm-instructor-help-students-section isEditDetailsCollapsed='collapseStudentEditDetailsInChild'></tm-instructor-help-students-section>`

File: src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts (hunk 7 above)
Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts:52]: Sure, done. Please see the last commits below.

File: src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts (hunk 10 above)
Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts:21]: I have tried this approach but it looks like it works only on the first trigger of the collapse event. If `collapseStudentEditDetailsInChild` in the parent (`instructor-help-page.component.ts`) is a boolean value and there is no 
`collapseStudentEditDetailsInChild: Subject<boolean>` in the child (`instructor-help-students-section.component.ts`), the child takes the value passed from the parent only once.

That is, with this configuration, in the following scenario the behavior is buggy:
1.  Upon the first trigger event, `collapseStudentEditDetailsInChild` is set to true in the parent and, thus, `isEditDetailsCollapsed` is set to true in the child. So, _Student-Edit-Details card_ is collapsed;
2. Then, suppose that user manually de-collapses this card and `isEditDetailsCollapsed` in the child becomes false;
3. Upon another trigger event, `collapseStudentEditDetailsInChild` is set to true in the parent but `isEditDetailsCollapsed` is not set to true in the child. So, _Student-Edit-Details card_ does not get collapsed though it should.

See:
Screen-Recording-2020-04-11-at-1

In contrast, in the current configuration, the child keeps listening to values from parent and the behavior is as expected.

Please correct me if I am missing anything. 
Thanks!

Comment (xpdavid) [reply src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts:21]: I think the main reason here is that "you have two points of truth" (One `collapseStudentEditDetailsInChild` and one `isEditDetailsCollapsed`, there are not synced properly). It is possible to only have "single points of truth"? (i.e. All child components fetch their corresponding values from the source. If the parent wants to change the source, the child component will respond correspondingly. If any child component (not necessary the child component that use them) want to change the sources, they fire event and ask parents to change it.)

Comment (aishaadambek) [reply src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts]: Hi @xpdavid,

sorry for a delay, I had a busy last week with school assignments.
I have now attempted to have "single points of truth". Please see the last commits below. 

However, I still have one thing I am not quite sure about.

- As stated in the [Angular documentation](https://angular.io/guide/lifecycle-hooks#onchanges), the OnChanges lifecycle hook is triggered by Angular _only when the @Input property value changes_. This seems to explain why the @Input variables in the child components were not updating the values (as set by parent) when the @Input property value was not changing (this is the issue I addressed in the previous comment). 

- One suggested workaround is to ensure that Angular triggers the OnChanges hook by setting a new object reference with `Object.assign()` after modifying the property values. This is what I've done in the parent component.

Again, correct me if I am missing anything!
And thanks for your patience and guidance! :)

File: src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts [hunk 13]
```diff
@@ -14,11 +16,48 @@ export class InstructorHelpCoursesSectionComponent extends InstructorHelpSection
...
     super();
   }
 
   ngOnInit(): void {
+  }
 
+  /**
+   * Scrolls to an HTML element with a given target id.
+   */
+  jumpTo(target: string): boolean {
```
Comment (xpdavid) [inline src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts:52]: For better code quality, I think you can create a parent to do code sharing for `jumpTo`
