### PR TITLE
AdminEmailLogPage and AdminActivityLogPage fails when there is a patch version #4417

### LINKED ISSUE #4417: AdminEmailLogPage and AdminActivityLogPage fails when there is a patch version
Due to line 119 in `AdminEmailLogPageAction`:
`double curVersionAsDouble = Double.parseDouble(currentVersion);`
If the current version is in the format `major.minor.patch`, the parsing function will fail.

Two reasons I didn't resolve this in #4409:
- This is not a testing defect but an app defect
- The above is part of a function `getDefaultVersionIdsForQuery()`. I (or whoever's going to fix this) need to know the policy to use if there are patch versions.

Background: the currently used policy is like this:
- current version is an `rc` version: only include that version
- current version is a `major.minor` version: that version, along with 3 other before, e.g if the current version is 5.01, will include 5.00, 4.99, 4.98. This also I think is problematic because of bad assumptions that the minor version won't reach 3 digits (we have 4.100) and the last minor version before reaching a new major version is 99.
- current version is a `major.minor.patch` version: unhandled!

### PR DESCRIPTION
**Pull request by bamboo3250**
Fix #4417
@damithc @wkurniawan07 
My solution is using `getVersions()` method of `ModuleService` to get the list of available versions and select the current version together with its preceding versions (at most three). The only problem now is that I'm not sure about automated testing this function on both local and staging server.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Can you revert the header comments to unrelated methods? Sure it's great to have them, but this PR is never about those.

**Comment by bamboo3250** [comment]
@wkurniawan07 okay, no problem. Done.

**Comment by thyageshm** [comment]
@wkurniawan07 @bamboo3250 do you guys think this one can be merged this release? If yes, please add the milestone to the PR and the issue :-)

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 1]
```diff
@@ -225,64 +228,49 @@ private LogQuery buildQuery(AdminActivityLogPageData data) {
         return query;
     }
     
+    /**
+     * Selects versions for query.
+     * @param versions
+     * @return
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Can be simplified these three lines into one sentence `Returns ... for versions ...`

Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: I don't think the current comment is a complete description of the method though.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 2]
```diff
@@ -225,64 +228,49 @@ private LogQuery buildQuery(AdminActivityLogPageData data) {
...
+            if (version.equals(currentVersion)) {
+                isCurrentVersionFound = true;
+            } else {
+                if (isCurrentVersionFound) {
+                    if (defaultVersions.size() < MAX_DEFAULT_VERSION_NUMBER) {
+                        defaultVersions.add(version);
+                    } else {
+                        return defaultVersions;
+                    }
+                }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: This `for` look looks like it has too many nesting levels for such a short code block. See if you can simplify.

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 3]
```diff
@@ -23,7 +25,8 @@
     private boolean includeAppLogs = true;
     private static final int LOGS_PER_PAGE = 50;
     private static final int MAX_LOGSEARCH_LIMIT = 15000;
-
+    private static final int MAX_DEFAULT_VERSION_NUMBER = 6;        // 6 default versions for query.
+                                                                    // include the current version and its 5 preceding versions.
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Write a proper javadoc comment instead?

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 4]
```diff
@@ -81,59 +82,47 @@ private LogQuery buildQuery(String offset, boolean includeAppLogs, List<String>
...
+            } else {
+                if (isCurrentVersionFound) {
+                    if (defaultVersions.size() < MAX_DEFAULT_VERSION_NUMBER) {
+                        defaultVersions.add(version);
+                    } else {
+                        return defaultVersions;
+                    }
+                }
             }
         }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: This `for` loop looks familiar. can reuse?

Comment (bamboo3250) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Yes, this is what I proposed in #4773. I'll refactor it there, maybe not in this PR.

**Comment by bamboo3250** [comment]
@damithc I fixed the comments and simplified the logic in the for-loop. Please check if they look good to you or not.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 5]
```diff
@@ -33,11 +35,15 @@
     private static final int SEARCH_TIME_INCREMENT = 2*60*60*1000;  // two hours in millisecond
     private static final int MAX_SEARCH_TIMES = 12;                 // maximum 1 day
     
+    /**
+     * 6 default versions for query, including the current version and its 5 preceding versions.
+     */
+    private static final int MAX_DEFAULT_VERSION_NUMBER = 6;
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: A more meaningful name, such as `MAX_PAST_VERSIONS_TO_QUERY`?

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 6]
```diff
@@ -225,64 +231,45 @@ private LogQuery buildQuery(AdminActivityLogPageData data) {
...
+        // Find the current version then get at most 5 versions below it.
+        for(String version : versionList) {
+            if (version.equals(currentVersion)) {
+                isCurrentVersionFound = true;
+            }
+            if (isCurrentVersionFound) {
+                defaultVersions.add(version);
+                if (defaultVersions.size() >= MAX_DEFAULT_VERSION_NUMBER) {
+                    return defaultVersions;
+                }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Seems like the code is doing two things. It is more efficient that way, but less readable.
Can you break this down to two steps? e.g.
```java
int currentVersionIndex = getCurrentVersionIndex(versionList, currentVersion);
return getNextFewVersions(versionList, currentVersionIndex, MAX_DEFAULT_VERSION_NUMBER);
```
BTW, you are using a `Set` as it it is a sorted list. Is that correct?

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 7]
```diff
@@ -23,7 +25,12 @@
     private boolean includeAppLogs = true;
     private static final int LOGS_PER_PAGE = 50;
     private static final int MAX_LOGSEARCH_LIMIT = 15000;
-
+    
+    /**
+     * 6 default versions for query, including the current version and its 5 preceding versions.
+     */
+    private static final int MAX_DEFAULT_VERSION_NUMBER = 6;
+
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Can we avoid this duplication?

Comment (bamboo3250) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: It could be better if we move it to Const class.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java (hunk 6 above)
Comment (bamboo3250) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: A `Set` is not necessarily a `SortedSet`. It is what `getVersions()` of `ModulesService` returns. I can change it to `String[]` so that we can have more control of the list.

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java (hunk 7 above)
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Or create a `Version` class?. `Const` class cannot absorb duplicated methods.

Comment (bamboo3250) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Then I would like to resolve #4773 in this PR as well since they are closely related. Is that fine?

File: src/main/java/teammates/common/util/LogHelper.java [hunk 8]
```diff
@@ -0,0 +1,117 @@
...
+            if (result.size() >= MAX_PAST_VERSIONS_TO_QUERY) {
+                return result;
+            }
+        }
+        return result;
+    }
+
+    /**
+     * Finds the index of the current version in the given list.
+     * Returns the size of the list if the current version is not found. This is not supposed to happen!
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: If it is not supposed to happen either put an `Assumption` or throw a runtime exception?

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 9]
```diff
@@ -155,15 +147,16 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
...
-        totalLogsSearched = 0;
         while ((numberOfSearchTimes < MAX_SEARCH_TIMES) && (appLogs.size() < RELEVANT_LOGS_PER_PAGE)) {
             // set fromDate is two-hour away from toDate
             long nextTwoHour = data.getToDate() - SEARCH_TIME_INCREMENT;
             data.setFromDate(nextTwoHour);
             numberOfSearchTimes++;
             
-            LogQuery query = buildQuery(data);
-            List<ActivityLogEntry> searchResult = searchLogsByQuery(query, data);
+            //LogQuery query = buildQuery(data);
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: commented line

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 10]
```diff
@@ -173,116 +166,36 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
...
-                            activityLogEntry.setFirstRow();
-                            isFirstRow = false;
-                        }
-                        appLogs.add(activityLogEntry);
+        List<AppLogLine> appLogLines = logHelper.fetchLogs();
+        totalLogsSearched = appLogLines.size();
+        
+        for (AppLogLine appLog : appLogLines) {
+            String logMsg = appLog.getLogMessage();
+            if (logMsg.contains("TEAMMATESLOG") && !logMsg.contains("adminActivityLogPage")) {
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Introduce variable to explain meaning of condition?

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 11]
```diff
@@ -173,116 +166,36 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
...
+                activityLogEntry = data.filterLogs(activityLogEntry);
+                if (activityLogEntry.toShow() && ((!activityLogEntry.isTestingData()) || data.getIfShowTestData())) {
+                    if (isFirstRow ) {
+                        activityLogEntry.setFirstRow();
+                        isFirstRow = false;
                     }
+                    appLogs.add(activityLogEntry);
                 }
-            }    
+            }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: you can get rid of most of this nesting by reversing the condition and using an early termination. e.g.
```java
if(!condition){
    continue;
}
```

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 12]
```diff
@@ -59,123 +52,29 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
-                    }
+            String logMsg = appLog.getLogMessage();
+            if (logMsg.contains("TEAMMATESEMAILLOG")) {
+                EmailLogEntry emailLogEntry = new EmailLogEntry(appLog);    
+                if(data.shouldShowLog(emailLogEntry)){
+                    emailLogs.add(emailLogEntry);
+                    currentLogsInPage ++;
                 }
-            }    
+            }
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Another place where reversing the condition can reduce nesting?

**Comment by damithc** [comment]
Added some comments. Once done, I'll wait for `toMerge` for final review.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 13]
```diff
@@ -0,0 +1,128 @@
...
+import com.google.appengine.api.log.RequestLogs;
+import com.google.appengine.api.log.LogService.LogLevel;
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+public class LogHelper {
+    /**
+     * 6 past versions to query, including the current version and its 5 preceding versions.
+     */
+    public static final int MAX_PAST_VERSIONS_TO_QUERY = 6;
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: If it includes the current version, maybe a better name is `MAX_VERSIONS_TO_QUERY`?

File: src/main/java/teammates/common/util/LogHelper.java [hunk 14]
```diff
@@ -0,0 +1,128 @@
...
+     * 
+     * @param versionsToQuery 
+     * @param startTime
+     * @param endTime
+     * @param offset
+     */
+    public void setQuery(List<String> versionsToQuery, Long startTime, Long endTime, String offset) {
+        query.includeAppLogs(true);
+        query.batchSize(1000);
+        query.minLogLevel(LogLevel.INFO);
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Consider making `1000` and `LogLevel.INFO` a private constant, along with explanation of what they are. Perhaps the `true` in `includeAppLogs` also.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 15]
```diff
@@ -0,0 +1,128 @@
...
+     */
+    private List<String> getDefaultVersionIdsForQuery() {
+        ModulesService modulesService = ModulesServiceFactory.getModulesService();
+        String[] versionList = (String[]) modulesService.getVersions(null).toArray(); // null == default module
+        String currentVersion = modulesService.getCurrentVersion();
+        int currentVersionIndex;
+        List<String> defaultVersions = new ArrayList<String>();
+        try {
+            currentVersionIndex = getCurrentVersionIndex(versionList, currentVersion);
+            defaultVersions = getNextFewVersions(versionList, currentVersionIndex);
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: I think it's safe for `currentVersionIndex` to be declared here instead.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 16]
```diff
@@ -0,0 +1,128 @@
...
+        } catch (InvalidParametersException e) {
+            defaultVersions.add(currentVersion);
+            e.printStackTrace();
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: `e.printStackTrace()` is hardly helpful. We can either don't have it, or do a `log.*` instead, although I'm not sure which log level is appropriate here.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 17]
```diff
@@ -0,0 +1,128 @@
...
+     * Finds the index of the current version in the given list.
+     * @throws InvalidParametersException when the current version is not found
+     */
+    private int getCurrentVersionIndex(String[] versionList, String currentVersion) 
+                    throws InvalidParametersException {
+        for(int i = 0; i < versionList.length; i++) {
+            if (versionList[i].equals(currentVersion)) return i;
+        }
+        throw new InvalidParametersException("The current version is not found!");
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Doesn't `List<String> versionList` have a built-in function to achieve this?
To convert from `Set<String>` you just need to do this:
```java
Set<String> set = ... // get the set
List<String> list = new ArrayList<String>(set);
```

File: src/main/java/teammates/common/util/LogHelper.java [hunk 18]
```diff
@@ -0,0 +1,128 @@
...
+    private List<String> getNextFewVersions(String[] versionList, int currentVersionIndex) {
+        List<String> result = new ArrayList<String>();
+        for(int i = currentVersionIndex; i < versionList.length; i++) {
+            result.add(versionList[i]);
+            if (result.size() >= MAX_PAST_VERSIONS_TO_QUERY) {
+                return result;
+            }
+        }
+        return result;
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Again, if you used `List<String>`, this is achieveable by `list.subList(fromIndex, toIndex)`.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 19]
```diff
@@ -173,116 +165,39 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
     }
     
     private List<ActivityLogEntry> searchLogsWithExactTimePeriod(AdminActivityLogPageData data) {
-        totalLogsSearched = 0;
-        LogQuery query = buildQuery(data);
-        List<ActivityLogEntry> appLogs = searchLogsByQuery(query, data);
+        LogHelper logHelper = new LogHelper();
+        logHelper.setQuery(data.getVersions(), data.getFromDate(), data.getToDate(), null);
+        
+        //LogQuery query = buildQuery(data);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Don't forget to remove this.

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 20]
```diff
@@ -59,123 +52,28 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
         
-        //fetch request log
-        Iterable<RequestLogs> records = LogServiceFactory.getLogService().fetch(query);
-        for (RequestLogs record : records) {
-            
-            totalLogsSearched ++;
-            lastOffset = record.getOffset();
+        List<AppLogLine> appLogLines = logHelper.fetchLogs();
+        for (AppLogLine appLog : appLogLines) {
+            if (currentLogsInPage >= LOGS_PER_PAGE) break;
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]:
```java
if (condition) {
    break;
}
```

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 21]
```diff
@@ -59,123 +52,28 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
+            String logMsg = appLog.getLogMessage();
+            boolean isNotEmailLog = (!logMsg.contains("TEAMMATESEMAILLOG"));
+            if (isNotEmailLog) continue;
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Ditto here.

**Comment by bamboo3250** [comment]
@wkurniawan07 I did a few major changes.

1. Introduced VersionHelper and LogHelper.
2. Added another function to query logs with time increment in LogHelper. 
3. Changed logic in EmailLogPageAction. Previously it retrieved logs based on `offset` of the log. Now I changed it to query by time to make it similar with ActivityLogPage, which is more updated.
4. Added 2 more lines in the statusMessage of AdminActivityLogPage to keep track of all available versions and versions used to query.

screenshot 2016-02-20 10 02 26

**Comment by damithc** [comment]
When  introducing an `AbcHelper` class, see if you can have a `Abc` class instead and those helper methods can go as static methods in the `Abc' class. The latter is more OOP.

**Comment by bamboo3250** [comment]
I renamed `VersionHelper` to `Version` and added instance methods for `Version` class. 
Ready for review.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 22]
```diff
@@ -0,0 +1,195 @@
...
+
+import com.google.appengine.api.log.AppLogLine;
+import com.google.appengine.api.log.LogQuery;
+import com.google.appengine.api.log.LogServiceFactory;
+import com.google.appengine.api.log.RequestLogs;
+import com.google.appengine.api.log.LogService.LogLevel;
+
+public class LogHelper {
+    /**
+     * 6 past versions to query, including the current version and its 5 preceding versions.
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: 6 ~~past~~ versions

File: src/main/java/teammates/common/util/LogHelper.java [hunk 23]
```diff
@@ -0,0 +1,195 @@
...
+     * If versionsToQuery is null or empty, the current version with its 5 preceding versions will be used instead.
+     * 
+     * @param versionsToQuery 
+     * @param startTime
+     * @param endTime
+     */
+    public void setQuery(List<String> versionsToQuery, Long startTime, Long endTime) {
+        query.includeAppLogs(INCLUDE_APP_LOG);
+        query.batchSize(BATCH_SIZE);
+        query.minLogLevel(MIN_LOG_LEVEL);
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Will it be sensible to remove all these settings to the constructor?

File: src/main/java/teammates/common/util/LogHelper.java [hunk 24]
```diff
@@ -0,0 +1,195 @@
...
+            query.endTimeMillis(endTime);
+        }
+    }
+    
+    /**
+     * Sets end time of the query.
+     */
+    public void setEndTime(Long endTime) {
+        this.endTime = endTime;
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Consider making this private?
Otherwise you might as well make the field `endTime` public.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 25]
```diff
@@ -0,0 +1,195 @@
...
+        Version currentVersion = Version.getCurrentVersion();
+        
+        List<String> defaultVersions = new ArrayList<String>();
+        try {
+            int currentVersionIndex = getCurrentVersionIndex(versionList, currentVersion);
+            defaultVersions = getNextFewVersions(versionList, currentVersionIndex);
+        } catch (InvalidParametersException e) {
+            defaultVersions.add(currentVersion.toStringForQuery());
+            Utils.getLogger().severe("The current version is not found: " + e.getMessage());
+            e.printStackTrace();
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/LogHelper.java]: Two issues:
- Don't include `e.printStackTrace()`.
- The message "The current version is not found" is almost identical to what is set in the Exception. `.severe(e.getMessage())` should be sufficient.

File: src/main/java/teammates/common/util/Version.java [hunk 26]
```diff
@@ -0,0 +1,167 @@
...
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+public class Version {
+    private static ModulesService modulesService = ModulesServiceFactory.getModulesService();
+    private Integer major;  //  the first number
+    private Integer minor;  //  the second number
+    private String patch;   //  the rest of version
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: Must this be `String`?

File: src/main/java/teammates/common/util/Version.java [hunk 27]
```diff
@@ -0,0 +1,167 @@
...
+     * Creates a new instance of Version from string.
+     * It accepts either XX-XX-XXXXX or XX.XX.XXXX format.
+     */
+    public Version(String versionInString) {
+        String[] list;
+        if (versionInString.contains("-")) {
+            list = versionInString.split("-", 3);   // split into at most 3 parts
+        } else {
+            list = versionInString.split(".", 3);
+        }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]:
```java
} else if (versionInString.contains(".")) {
    ...
} else {
    // throw some Exception/log.severe/Assumption.fail/...
}
```

File: src/main/java/teammates/common/util/Version.java [hunk 28]
```diff
@@ -0,0 +1,167 @@
...
+            patch = list[2];
+        }
+    }
+    
+    /**
+     * Compares by string representation.
+     */
+    public boolean equals(Object anotherVersion) {
+        return toString().equals(anotherVersion.toString());
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: Just a practice in Java, if you override `equals` you would've to override `hashCode` as well so consider doing that.

File: src/main/java/teammates/common/util/Version.java [hunk 29]
```diff
@@ -0,0 +1,167 @@
...
+            if (patch1 == null && patch2 == null) {
+                return 0;
+            }
+            if (patch1 == null) {
+                return 1;
+            }
+            if (patch2 == null) {
+                return -1;
+            }
+            return -patch1.compareTo(patch2);
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: Looks very repetitive. Can the component-wise comparison be abstracted out into a common function?

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 30]
```diff
@@ -11,33 +10,29 @@
...
-import com.google.appengine.api.log.LogService.LogLevel;
 
 public class AdminActivityLogPageAction extends Action {
     
-    //We want to pull out the application logs
-    private boolean includeAppLogs = true;
     private static final int RELEVANT_LOGS_PER_PAGE = 50;
-    private static final int SEARCH_TIME_INCREMENT = 2*60*60*1000;  // two hours in millisecond
-    private static final int MAX_SEARCH_TIMES = 12;                 // maximum 1 day
+    private static final int MAX_SEARCH_TIMES = 12; // search maximum 12 times with time increment
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Rather than hard-coding 12, consider `(24 * 60 * 60 * 1000) / LogHelper.SEARCH_TIME_INCREMENT`. It would be resilient should you need to change the latter value as well.

**Comment by wkurniawan07** [comment]
Added some suggestions.

File: src/main/java/teammates/common/util/Version.java (hunk 27 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: What if the version only has 1 number, i.e. only major version number?

File: src/main/java/teammates/common/util/Version.java (hunk 26 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: Yes, to cover the case when more than 3 numbers may be used to present version. For example 11.05.01.01, etc.

File: src/main/java/teammates/common/util/Version.java (hunk 28 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: `hashCode` function added below.

**Comment by bamboo3250** [comment]
I accepted most of suggestions. Ready for review again.

File: src/main/java/teammates/common/util/Version.java (hunk 27 above)
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: Ah ok, I always thought our convention is there's at least two numbers.

**Comment by wkurniawan07** [comment]
Looks good now :+1:
Anyway, as a follow up to this, I suggest you take a look at `CompileLogs`, `CompileLogsServlet`, and `EntityModifiedLogsServlet`. `LogHelper` might be used in those classes too.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 31]
```diff
@@ -0,0 +1,192 @@
...
+
+import teammates.common.exception.InvalidParametersException;
+
+import com.google.appengine.api.log.AppLogLine;
+import com.google.appengine.api.log.LogQuery;
+import com.google.appengine.api.log.LogServiceFactory;
+import com.google.appengine.api.log.RequestLogs;
+import com.google.appengine.api.log.LogService.LogLevel;
+
+public class LogHelper {
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: Add header comment.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 32]
```diff
@@ -0,0 +1,192 @@
...
+    /**
+     * 6 versions to query, including the current version and its 5 preceding versions.
+     */
+    private static final int MAX_VERSIONS_TO_QUERY = 6;
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: This comment should be a description of the variable rather than the value. But you can value as an example to explain the variable.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 33]
```diff
@@ -0,0 +1,192 @@
...
+    
+    /**
+     * Always includes application logs
+     */
+    private static final boolean INCLUDE_APP_LOG = true;
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: Same here.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 34]
```diff
@@ -0,0 +1,192 @@
...
+    
+    /**
+     * Affects the internal strategy to get logs. It doesn't affect the result.
+     */
+    private static final int BATCH_SIZE = 1000;
+    private static final LogLevel MIN_LOG_LEVEL = LogLevel.INFO;
+    public static final int SEARCH_TIME_INCREMENT = 2*60*60*1000;  // two hours in millisecond
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: This one needs to be public?

Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: `milliseconds`

File: src/main/java/teammates/common/util/LogHelper.java [hunk 35]
```diff
@@ -0,0 +1,192 @@
...
+    private LogQuery query;
+    private Long endTime;
+    private List<String> versionList;
+    
+    public LogHelper() {
+        query = LogQuery.Builder.withDefaults();
+        query.includeAppLogs(INCLUDE_APP_LOG);
+        query.batchSize(BATCH_SIZE);
+        query.minLogLevel(MIN_LOG_LEVEL);
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: Um, what does this class actually represents? A Log query result? A log reader? If it is a pure helper class, one doesn't expect to see a constructor.

File: src/main/java/teammates/common/util/Version.java [hunk 36]
```diff
@@ -0,0 +1,171 @@
...
+
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.Comparator;
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+public class Version {
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Header comment?

File: src/main/java/teammates/common/util/LogHelper.java (hunk 34 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/LogHelper.java]: This constant is used in AdminActivityLogPage and AdminEmailLogPage to calculate `MAX_SEARCH_TIMES` so I leave it public.

File: src/main/java/teammates/common/util/Version.java [hunk 37]
```diff
@@ -0,0 +1,171 @@
...
+    private static ModulesService modulesService = ModulesServiceFactory.getModulesService();
+    private Integer major;  //  the first number
+    private Integer minor;  //  the second number
+    /**
+     * The rest of version. It should be String to cover versions with more than 3 numbers.
+     * For example: 15.56.01.01
+     */
+    private String patch;
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Perhaps you can write one detailed comment to explain all three variables?

File: src/main/java/teammates/common/util/LogHelper.java (hunk 35 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/LogHelper.java]: It is more like a log reader so I think it should have a constructor with those default parameters for the query.

**Comment by bamboo3250** [comment]
@damithc comments added. Ready for your review.

File: src/main/java/teammates/common/util/Version.java [hunk 38]
```diff
@@ -0,0 +1,193 @@
...
+     */
+    public String toString() {
+        String version = "";
+        if (major != null) {
+            version += String.valueOf(major);
+        }
+        if (minor != null) {
+            String minorInString = String.valueOf(minor);
+            if (minorInString.length() < 2) {
+                minorInString = "0" + minorInString;
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: This means `new Version("1-1").toString()` gives `1.01`? That's a bit odd isn't it? May be you should keep the three parts as strings (in fact the entire string) and convert to numbers on demand? Alternatively, can store the original string in addition to the three numbers?

File: src/main/java/teammates/common/util/Version.java [hunk 39]
```diff
@@ -0,0 +1,193 @@
...
+                return majorComparisonResult;
+            }
+            int minorComparisonResult = compareVersionNumber(v1.getMinorVersion(), v2.getMinorVersion());
+            if (minorComparisonResult != 0) {
+                return minorComparisonResult;
+            }
+            int patchComparisonResult = compareVersionString(v1.getPatchVersion(), v2.getPatchVersion());
+            return patchComparisonResult;
+        }
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Shouldn't this be in the `Version` class?

File: src/main/java/teammates/common/util/Version.java [hunk 40]
```diff
@@ -0,0 +1,193 @@
...
+    private Integer getMinorVersion() {
+        return minor;
+    }
+    
+    /**
+     * Gets the patch part of the version.
+     */
+    private String getPatchVersion() {
+        return patch;
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Why do we have private getters?

File: src/main/java/teammates/common/util/Version.java (hunk 39 above)
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Never mind. my mistake.

File: src/main/java/teammates/common/util/Version.java [hunk 41]
```diff
@@ -0,0 +1,193 @@
...
+     */
+    public static List<Version> getAvailableVersions() {
+        List<String> versionListInString = new ArrayList<String>(modulesService.getVersions(null)); // null == default module
+        List<Version> versionList = new ArrayList<Version>();
+        for(String versionInString : versionListInString) {
+            versionList.add(new Version(versionInString));
+        }
+        Collections.sort(versionList, new VersionComparator());
+        return versionList;
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: This method looks like it belongs in a `LogReader` class or a `GaeApi` class. It's fine to do the processing of the version info in this class but reading it from GAE doesn't belong in this class.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 42]
```diff
@@ -0,0 +1,196 @@
...
+     * @param endTime
+     */
+    private void setTimePeriodForQuery(Long startTime, Long endTime) {
+        if (startTime != null) {
+            query.startTimeMillis(startTime);
+        }
+        if (endTime != null) {
+            query.endTimeMillis(endTime);
+        }
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: 1. Why this method checks for null but `setEndTime` method below doesn't?
2. Shouldn't this method call the `setEndTime` method?

File: src/main/java/teammates/common/util/LogHelper.java (hunk 35 above)
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: I think you have two classes here: a `AdminLogReader` and `AdminLogQuery`. What do you think?

File: src/main/java/teammates/common/util/LogHelper.java [hunk 43]
```diff
@@ -0,0 +1,196 @@
...
+            logs.addAll(appLogLines);
+        }
+        return logs;
+    }
+    
+    /**
+     * Retrieves all logs within 2 hours before the endTime.
+     * We can use it again to get logs from the next 2 hours.
+     * @return logs within 2 hours before endTime
+     */
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: There is no mention of `2 hours` in the code but the comment mentions `2 hours`

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 44]
```diff
@@ -151,138 +174,71 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
...
-        //Eg. 5.05rc
-        if (currentVersion.matches(".*[A-z.*]")) {
-            //if current version contains alphatet,
-            //by default just prepare current version as a single element for the query
-            defaultVersions.add(currentVersion.replace(".", "-"));
+    /**
+     * Filters logs that should be shown on Admin Activity Log Page.
+     */
+    private List<ActivityLogEntry> filterLogsForActivityLogPage(List<AppLogLine> appLogLines,
+                                                             AdminActivityLogPageData data) {
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Indent three more spaces to align with `List` above?

File: src/main/webapp/jsp/adminEmailLog.jsp [hunk 45]
```diff
@@ -14,7 +14,7 @@
     
     <%-- this form is used to store parameters for ajaxloader only --%>
     <form id="ajaxLoaderDataForm">
-        <input type="hidden" name="offset" value="${data.offset}">
+        <input type="hidden" name="offset" value="">
```
Comment (damithc) [inline src/main/webapp/jsp/adminEmailLog.jsp]: Is this change intentional?

**Comment by damithc** [comment]
Added some more comments. I'll review again after you've revised accordingly. Coaxing out the right classes might need a few iterations.

File: src/main/webapp/jsp/adminEmailLog.jsp (hunk 45 above)
Comment (bamboo3250) [inline src/main/webapp/jsp/adminEmailLog.jsp]: Yes, now `offset` is not a part of `AdminEmailLogPageData` anymore (its value will be assigned via javascript) so I removed it.

**Comment by bamboo3250** [comment]
Now we have `GaeApi` class to retrieve the current version and all available versions of the app. 
I also added `Comparable` interface for `Version` class based on the previous Comparator and refactored the code according to your suggestions.
Ready for review.

File: src/main/java/teammates/common/util/LogHelper.java (hunk 35 above)
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: What about this comment?

**Comment by damithc** [comment]
There is another major comment about splitting the `LogHelper` class.

File: src/main/java/teammates/common/util/LogHelper.java (hunk 35 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/LogHelper.java]: I saw it just a few minutes ago and I'm still thinking about it. I look at this class as an entity, which I can provide with `versions`, ` startTime` and `endTime` then I can fetch the logs from GAE server without touching to the `LogQuery` inside. If you want to separate the LogQuery from it, the `AdminLogQuery` may be just the same as `LogQuery` with different default values. I think it's fine to include the query inside this class.

File: src/main/java/teammates/common/util/GaeApi.java [hunk 46]
```diff
@@ -0,0 +1,36 @@
...
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * Calls API functions of Google AppEngine
+ */
+public class GaeApi {
+    private static ModulesService modulesService = ModulesServiceFactory.getModulesService();
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/GaeApi.java]: If this is intended to be non-modifiable, make it `final`.

File: src/main/java/teammates/common/util/Version.java [hunk 47]
```diff
@@ -0,0 +1,152 @@
...
+ * Represents a version by 3 parts: major version, minor version and patch version.
+ */
+public class Version implements Comparable<Version> {
+    /**
+     * The original String of the version. It could be either XX-XX-XXXXX or XX.XX.XXXX format.
+     */
+    private String originalRepresentation;
+    private Integer major;
+    private Integer minor;
+    private String patch;
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: I just thought something: what if all the components are left as String? Saves the trouble of having to parse.

File: src/main/java/teammates/common/util/Version.java [hunk 48]
```diff
@@ -0,0 +1,152 @@
...
+            return 0;
+        }
+        if (num1 == null) {
+            return 1;
+        }
+        if (num2 == null) {
+            return -1;
+        }
+        return -num1.compareTo(num2);
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: And also saves the trouble of having duplicate comparators here.

File: src/main/java/teammates/common/util/Version.java [hunk 49]
```diff
@@ -0,0 +1,152 @@
...
+    public Integer getMinorVersion() {
+        return minor;
+    }
+    
+    /**
+     * Gets the patch part of the version.
+     */
+    public String getPatchVersion() {
+        return patch;
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: Are the getters used outside the class? If they're not, I don't really see the need for getters because you can very simply call `version.major/minor/patch`.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 50]
```diff
@@ -11,33 +10,34 @@
...
-    //We want to pull out the application logs
-    private boolean includeAppLogs = true;
     private static final int RELEVANT_LOGS_PER_PAGE = 50;
-    private static final int SEARCH_TIME_INCREMENT = 2*60*60*1000;  // two hours in millisecond
-    private static final int MAX_SEARCH_TIMES = 12;                 // maximum 1 day
+    /**
+     * The maximum number of times to retrieve logs with time increment.
+     * The current value will search up to 24h.
+     */
+    private static final int MAX_SEARCH_TIMES = 24 * 60 * 60 * 1000 / LogHelper.SEARCH_TIME_INCREMENT;
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: One thing you can do is also separate the 24-hr value to another private var, something like:
```java
private static final int MAX_SEARCH_PERIOD = 24 * 60 * 60 * 1000; // 24 hrs in milliseconds
private static final int MAX_SEARCH_TIMES = MAX_SEARCH_PERIOD / LogHelper.SEARCH_TIME_INCREMENT;
```

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 51]
```diff
@@ -151,138 +175,71 @@ private void generateStatusMessage(AdminActivityLogPageData data, List<ActivityL
         statusToUser.add(new StatusMessage(status, StatusMessageColor.INFO));
     }
 
+    /**
+     * Retrieves enough logs within 24 hour.
+     */
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: That way you don't have to hard-code 24 hours here. You can make it refer to the variable that stores the 24 hours (or whatever value it is, if going to be changed).

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 52]
```diff
@@ -46,154 +53,63 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
-        String status="&nbsp;&nbsp;Total Logs gone through in last search: " + totalLogsSearched + "<br>";
-        //link for Next button, will fetch older logs
-        if (totalLogsSearched >= MAX_LOGSEARCH_LIMIT){
-            status += "<br><span class=\"red\">&nbsp;&nbsp;Maximum amount of logs per requst have been searched.</span><br>";
-            status += "<button class=\"btn-link\" id=\"button_older\" onclick=\"submitFormAjax('" + lastOffset + "');\">Search More</button>";           
-        }
-        
-        if (currentLogsInPage >= LOGS_PER_PAGE) {   
-            status += "<button class=\"btn-link\" id=\"button_older\" onclick=\"submitFormAjax('" + lastOffset + "');\">Older Logs </button>";              
+            emailLogs.add(emailLogEntry);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: This would look logically clearer:
```java
if (data.shouldShowLog(emailLogEntry)) {
    emailLogs.add(emailLogEntry);
}
```

File: src/main/java/teammates/common/util/Version.java (hunk 47 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: then the version 4.44 will come before 10.44 but it should be 10.44 that goes first. The major part at least should be Integer because the length of the number may not be the same.

File: src/main/java/teammates/common/util/Version.java (hunk 49 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: I think we may need them later. No harm to have them anyway.

File: src/main/java/teammates/common/util/GaeApi.java [hunk 53]
```diff
@@ -0,0 +1,36 @@
...
+import java.util.Collections;
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * Calls API functions of Google AppEngine
+ */
+public class GaeApi {
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/GaeApi.java]: Actually, `GaeApi` might be too broad a term is the functions only involve versioning. Consider renaming it to something else that captures the versioning functionality?

File: src/main/java/teammates/common/util/Version.java [hunk 54]
```diff
@@ -0,0 +1,168 @@
...
+    /**
+     * Creates a new instance of Version from string.
+     * It accepts either XX-XX-XXXXX or XX.XX.XXXX format.
+     */
+    public Version(String versionInString) {
+        originalRepresentation = versionInString;
+        
+        if (versionInString.contains("rc")) {
+            int rcIndex = versionInString.indexOf("rc");
+            versionInString = versionInString.substring(0, rcIndex);
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: `versionInString.replace("rc", "")` will do the job

File: src/main/java/teammates/common/util/Version.java (hunk 49 above)
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/Version.java]: No harm, but no need also. Your call :p

File: src/main/java/teammates/common/util/Version.java (hunk 54 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: (y)

File: src/main/java/teammates/common/util/GaeApi.java (hunk 53 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/GaeApi.java]: I think there is no need to rename it. We might need to other API functions to it later. Who know :stuck_out_tongue:

File: src/main/java/teammates/common/util/Version.java (hunk 47 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/Version.java]: Okay, I have a solution to make them String.

**Comment by bamboo3250** [comment]
@damithc I removed the constructor for `LogHelper` and converted all of its instance methods to class method. Is this good enough? 
@wkurniawan07 Now `major` and `minor` are also String. I changed the logic to compare two versions a bit. Please check my solution.

File: src/main/java/teammates/common/util/GaeApi.java (hunk 53 above)
Comment (damithc) [inline src/main/java/teammates/common/util/GaeApi.java]: `GaeAdminApi`?
Description: `A wrapper class for GAE application admin API. e.g. version management`

File: src/main/java/teammates/common/util/Version.java [hunk 55]
```diff
@@ -0,0 +1,144 @@
+package teammates.common.util;
+
+/**
+ * Represents a version by 3 parts: major version, minor version and patch version.
+ */
+public class Version implements Comparable<Version> {
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Write unit tests for this class.

File: src/main/java/teammates/common/util/LogHelper.java [hunk 56]
```diff
@@ -0,0 +1,193 @@
...
+    /**
+     * Affects the internal strategy to get logs. It doesn't affect the result.
+     */
+    private static final int BATCH_SIZE = 1000;
+    private static final LogLevel MIN_LOG_LEVEL = LogLevel.INFO;
+    public static final int SEARCH_TIME_INCREMENT = 2 * 60 * 60 * 1000;  // two hours in milliseconds
+    
+    private static LogQuery query;
+    private static Long endTime;
+    private static List<String> versionList;
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogHelper.java]: Non-final variables in a fully static class indicates a design smell. In other words, this is a singleton class, implemented as a fully static class (not recommended). 
I still think you need a `LogReader` class that can take a `AdminLogQuery` object, execute it, and return the result. Alternatively, you can move the `LogReader` stuff (i.e. methods that depend on GAE api) into `GaeAdminApi` class. What's left would be the `AdminLogQuery` class.

File: src/main/java/teammates/common/util/GaeAdminApi.java [hunk 57]
```diff
@@ -0,0 +1,36 @@
...
+    }
+    
+    /**
+     * Gets the current version of the application.
+     */
+    public static Version getCurrentVersion() {
+        return new Version(modulesService.getCurrentVersion());
+    }
+    
+}
```
Comment (damithc) [inline src/main/java/teammates/common/util/GaeAdminApi.java]: If you make the methods non-static, the GaeAdminApi object can be replaced using a stub (i.e. dependency injection) which is better for testability. Fully static classes gets in the way of dependency injection.

Comment (bamboo3250) [inline src/main/java/teammates/common/util/GaeAdminApi.java]: Should I create a `inst()` function in this case?

Comment (damithc) [inline src/main/java/teammates/common/util/GaeAdminApi.java]: No, we don't want singleton either. Singleton too is not a very good pattern.

Comment (damithc) [inline src/main/java/teammates/common/util/GaeAdminApi.java]: Just make it a normal class with an empty constructor.

**Comment by bamboo3250** [comment]
@damithc I separated the LogQuery from the LogHelper and created a wrapper class for it and also converted functions in `GaeAdminApi` to non-static functions.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 58]
```diff
@@ -0,0 +1,155 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+import teammates.common.exception.InvalidParametersException;
+
+import com.google.appengine.api.log.LogQuery;
+import com.google.appengine.api.log.LogService.LogLevel;
+
+public class AdminLogQuery {
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Header comment?

File: src/main/java/teammates/common/util/LogReader.java [hunk 59]
```diff
@@ -0,0 +1,56 @@
...
+        Iterable<RequestLogs> records = LogServiceFactory.getLogService().fetch(query.getQuery());
+        for (RequestLogs record : records) {
+            record.getOffset();
+            List<AppLogLine> appLogLines = record.getAppLogLines();
+            logs.addAll(appLogLines);
+        }
+        query.setEndTime(startTime - 1);
+        return logs;
+    }
+}
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogReader.java]: I think you can move these into `GaeAdminApi`. Alternatively, have two classes: `GaeVersionApi` and `GaeLogApi`. Also, make the methods non-static.

File: src/main/java/teammates/common/util/LogReader.java [hunk 60]
```diff
@@ -0,0 +1,56 @@
...
+     * @return logs within the amount of hours defined by SEARCH_TIME_INCREMENT before endTime.
+     */
+    public static List<AppLogLine> fetchLogsInNextHours(AdminLogQuery query) {
+        List<AppLogLine> logs = new LinkedList<AppLogLine>();
+        
+        if (query.getEndTime() == null) {
+            query.setEndTime(TimeHelper.now(0.0).getTimeInMillis());
+        }
+        Long startTime = query.getEndTime() - SEARCH_TIME_INCREMENT;
+        query.setTimePeriodForQuery(startTime, query.getEndTime());
```
Comment (damithc) [inline src/main/java/teammates/common/util/LogReader.java]: The five lines above looks like it belongs in the `AdminLogQuery` class.

You can have only one `fetchLogs` method (instead of the current two), but manipulate the query object before calling the method. e.g.
```java
fetchLogs(query);
...
query.setQueryWindowBack(1); //set back by one hour
reader.fetchLogs(query);
```
Is that feasible?

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 61]
```diff
@@ -0,0 +1,158 @@
...
+     * 
+     * @param versionsToQuery 
+     * @param startTime
+     * @param endTime
+     */
+    public void setQuery(List<String> versionsToQuery, Long startTime, Long endTime) {
+        setTimePeriodForQuery(startTime, endTime);
+        versionList = getVersionIdsForQuery(versionsToQuery);
+        query.majorVersionIds(versionList);
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Merge with constructor?

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 62]
```diff
@@ -0,0 +1,158 @@
...
+
+import teammates.common.exception.InvalidParametersException;
+
+import com.google.appengine.api.log.LogQuery;
+import com.google.appengine.api.log.LogService.LogLevel;
+
+/**
+ * A wrapper class for LogQuery to retrieve logs from GAE server.
+ */
+public class AdminLogQuery {
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Write unit tests for non-trivial methods.

**Comment by bamboo3250** [comment]
I added unit test for `AdminLogQuery` and remove `fetchLogsInNextHours` in `GaeLogApi`.Ready for review.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 63]
```diff
@@ -0,0 +1,175 @@
...
+    
+    /**
+     * Default constructor.
+     */
+    public AdminLogQuery() {
+        query = LogQuery.Builder.withDefaults();
+        query.includeAppLogs(INCLUDE_APP_LOG);
+        query.batchSize(BATCH_SIZE);
+        query.minLogLevel(MIN_LOG_LEVEL);
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: No need for this?

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 64]
```diff
@@ -0,0 +1,175 @@
...
+            query.startTimeMillis(startTime);
+        }
+        if (endTime != null) {
+            query.endTimeMillis(endTime);
+            setEndTime(endTime);
+        }
+    }
+    
+    /**
+     * Sets time period to query logs then moves endTime back by the same amount.
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: This comment is not clear.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 65]
```diff
@@ -0,0 +1,175 @@
...
+    public AdminLogQuery() {
+        query = LogQuery.Builder.withDefaults();
+        query.includeAppLogs(INCLUDE_APP_LOG);
+        query.batchSize(BATCH_SIZE);
+        query.minLogLevel(MIN_LOG_LEVEL);
+    }
+    
+    /**
+     * Sets values for query.
+     * If versionsToQuery is null or empty, default versions will be used instead.
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Is there a specific behavior if any of the times are null?

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 66]
```diff
@@ -0,0 +1,175 @@
...
+    }
+    
+    /**
+     * Sets time period to query logs then moves endTime back by the same amount.
+     * @param timeInMillis milliseconds before endTime
+     */
+    public void setQueryWindowBackward(long timeInMillis) {
+        if (getEndTime() == null) {
+            setEndTime(TimeHelper.now(0.0).getTimeInMillis());
+        }
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Is there any need to keep the end time as null? If there isn't, it can be set in the constructor.

File: src/main/java/teammates/common/util/AdminLogQuery.java (hunk 65 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: If startTime is null, all logs until endTime will be retrieved.
If endTime is null, all logs from startTime will be retrieved.
If both are null, all logs will be retrieved.
This is behaviour of LogQuery.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 67]
```diff
@@ -0,0 +1,175 @@
...
+        return getDefaultVersionIdsForQuery();
+    }
+    
+    /**
+     * Gets a list of versions, including the current version and 5 preceding versions (if available).
+     * @return a list of default versions for query.
+     */
+    private List<String> getDefaultVersionIdsForQuery() {
+        GaeVersionApi adminApi = new GaeVersionApi();
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: This dependency doesn't feel right. This class has no business knowing the `GaeVersionApi` class. The call site (i.e. probably the `Action` class) should get the relevant stuff from the api and pass to this class. 
In fact, this whole method feels like it should be in `GaeVersionApi` class.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 68]
```diff
@@ -0,0 +1,175 @@
...
+     */
+    private List<String> getNextFewVersions(List<Version> versionList, int currentVersionIndex) {
+        int endIndex = Math.min(currentVersionIndex + MAX_VERSIONS_TO_QUERY, versionList.size());
+        List<Version> versionSubList = versionList.subList(currentVersionIndex, endIndex);
+        List<String> versionListInString = new ArrayList<String>();
+        for(Version version : versionSubList) {
+            versionListInString.add(version.toStringForQuery());
+        }
+        return versionListInString;
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Move to `Version' class?

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 69]
```diff
@@ -0,0 +1,175 @@
...
+     * @throws InvalidParametersException when the current version is not found
+     */
+    private int getCurrentVersionIndex(List<Version> versionList, Version currentVersion) 
+                    throws InvalidParametersException {
+        int versionIndex = versionList.indexOf(currentVersion);
+        if (versionIndex != -1) {
+            return versionIndex;
+        }
+        throw new InvalidParametersException("The current version is not found!");
+    }
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: This too can go to `Version` class?. It's dealing with versions and not accessing internal data of this class.

**Comment by damithc** [comment]
Added some more comments. Mostly to ensure classes are cohesive and code appears where they belong.

**Comment by bamboo3250** [comment]
Changes made. I'm ready for review.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 70]
```diff
@@ -0,0 +1,116 @@
...
+    /**
+     * Selects versions for query. If versions are not specified, it will return 
+     * default versions used for query.
+     */
+    private List<String> getVersionIdsForQuery(List<String> versions) {
+        boolean isVersionSpecifiedInRequest = (versions != null && !versions.isEmpty());
+        if (isVersionSpecifiedInRequest) {
+            return versions;
+        }
+        GaeVersionApi versionApi = new GaeVersionApi();
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Remove this dependency. May be default versions can be fed as a parameter in the constructor and stored inside from that point.

File: src/main/java/teammates/common/util/GaeVersionApi.java [hunk 71]
```diff
@@ -0,0 +1,80 @@
...
+    public Version getCurrentVersion() {
+        ModulesService modulesService = ModulesServiceFactory.getModulesService();
+        return new Version(modulesService.getCurrentVersion());
+    }
+    
+    /**
+     * Gets a few recent versions for log query.
+     * @return a list of default versions for query.
+     */
+    public List<String> getDefaultVersionIdsForLogQuery() {
```
Comment (damithc) [inline src/main/java/teammates/common/util/GaeVersionApi.java]: A method should not be named based on the caller. A method can be called by any other class. Name it based on what the method does.

File: src/main/java/teammates/common/util/Version.java [hunk 72]
```diff
@@ -0,0 +1,144 @@
...
+     * Converts Version to String in format XX.XX.XXXX
+     */
+    public String toString() {
+        return originalRepresentation.replace('-', '.');
+    }
+    
+    /**
+     * Converts to String in format XX-XX-XXXX
+     */
+    public String toStringForQuery() {
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: `toStringWithDashes`? (to avoid naming method based on usage)

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 73]
```diff
@@ -82,16 +86,21 @@ protected ActionResult execute() throws EntityDoesNotExistException{
         //This is used to parse the filterQuery. If the query is not parsed, the filter function would ignore the query
         data.generateQueryParameters(filterQuery);
         
+        boolean ifContinueFromPreviousSearch = (!data.isFromDateSpecifiedInQuery()) && (!searchTimeOffset.isEmpty());
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: `ifContinueFromPreviousSearch` --> `isContinueFromPreviousSearch`?

File: src/test/java/teammates/test/cases/common/VersionTest.java [hunk 74]
```diff
@@ -0,0 +1,43 @@
...
+        
+        version1 = new Version("15.09");
+        version2 = new Version("1.09");
+        System.out.println(version1.compareTo(version2));
+        assertTrue(version1.compareTo(version2) < 0);
+        assertTrue(version2.compareTo(version1) > 0);
+        
+        version1 = new Version("15.09");
+        version2 = new Version("15.09.01");
+        assertTrue(version1.compareTo(version2) > 0);
```
Comment (damithc) [inline src/test/java/teammates/test/cases/common/VersionTest.java]: I remember some special handling was done for `rc` but I can't see any test cases for that.

**Comment by bamboo3250** [comment]
I have addressed above issues.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 75]
```diff
@@ -0,0 +1,93 @@
...
+        if (endTime == null) {
+            endTime = TimeHelper.now(0.0).getTimeInMillis();
+        }
+        query.endTimeMillis(endTime);
+        setEndTime(endTime);
+    }
+    
+    /**
+     * Sets the time period to query logs from endTime back to endTime - timeInMillis
+     * then moves endTime to right before the query's start time.
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: What's the intention of this method? It's not clear.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 76]
```diff
@@ -0,0 +1,93 @@
...
+    private static final int BATCH_SIZE = 1000;
+    private static final LogLevel MIN_LOG_LEVEL = LogLevel.INFO;
+    
+    private LogQuery query;
+    private long endTime;
+    
+    /**
+     * Sets values for query.
+     * 
+     * @param versionsToQuery
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: This param needs more explanations.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 77]
```diff
@@ -0,0 +1,93 @@
...
+    
+    private LogQuery query;
+    private long endTime;
+    
+    /**
+     * Sets values for query.
+     * 
+     * @param versionsToQuery 
+     * @param startTime
+     * @param endTime
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Can any param be null? If not, add assumptions?

File: src/main/java/teammates/common/util/Version.java [hunk 78]
```diff
@@ -0,0 +1,144 @@
...
+     * 
+     * version = 15.01.03
+     * major = "15", minor = "01" and patch = "03"
+     * 
+     * version = 15.01.03.01
+     * major = "15", minor = "01" and patch = "03.01"
+     * 
+     * It also support RC versions, which has "rc" appended at the end of the string.
+     * For example: 5rc, 4.55rc, 5.55.01rc
+     */
```
Comment (damithc) [inline src/main/java/teammates/common/util/Version.java]: Good comment. Merge it with class header comment or constructor header comment.

File: src/main/java/teammates/common/util/GaeVersionApi.java [hunk 79]
```diff
@@ -0,0 +1,75 @@
...
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * A wrapper class for GAE application admin API. e.g. version management
+ */
+public class GaeVersionApi {
+    /**
+     * Default constructor.
+     */
```
Comment (damithc) [inline src/main/java/teammates/common/util/GaeVersionApi.java]: Redundant comment

**Comment by damithc** [comment]
In much better shape now. Only a few small things to tidy up.
Even the two action classes are no longer ugly, although not ideal yet. 
In a separate issue, you may want to take another pass at each of the action classes to refactor them and ensure good test coverage.

File: src/main/java/teammates/common/util/AdminLogQuery.java (hunk 75 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Probably I will remove this function and move its code outside.

**Comment by bamboo3250** [comment]
I removed `setQueryWindowBackward()` function and manipulated the time period in action classes instead.

**Comment by damithc** [comment]
I think the code belongs in the adminLogQuery class, but needs to be
packaged correctly.
>
>

-- 
Sent from a mobile device.

**Comment by bamboo3250** [comment]
Okay, I will try to bring it back.

**Comment by bamboo3250** [comment]
I bought it back and renamed it to `moveTimePeriodBackward()`.

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 80]
```diff
@@ -0,0 +1,114 @@
...
+    private static final int BATCH_SIZE = 1000;
+    private static final LogLevel MIN_LOG_LEVEL = LogLevel.INFO;
+    
+    private LogQuery query;
+    private long startTime;
+    private long endTime;
+    
+    /**
+     * Sets values for query.
+     * If startTime is null, it will be considered as 0.
```
Comment (damithc) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: What does 0 mean? forever?

File: src/main/java/teammates/common/util/GaeVersionApi.java [hunk 81]
```diff
@@ -0,0 +1,72 @@
...
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * A wrapper class for GAE application admin API. e.g. version management
+ */
+public class GaeVersionApi {
+    public GaeVersionApi() {
```
Comment (damithc) [inline src/main/java/teammates/common/util/GaeVersionApi.java]: Add blank line above this?

**Comment by damithc** [comment]
@wkurniawan07 anything more to add?

File: src/main/java/teammates/common/util/AdminLogQuery.java (hunk 80 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: The time used in LogQuery is Unix time. https://en.wikipedia.org/wiki/Unix_time
0 means it will take logs after Thursday, 1 January 1970 (since forever).

Comment (bamboo3250) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: I will add comment for this

File: src/main/java/teammates/common/util/AdminLogQuery.java [hunk 82]
```diff
@@ -0,0 +1,118 @@
...
+    public void setEndTime(Long endTimeParam) {
+        endTime = endTimeParam;
+    }
+    
+    /**
+     * Sets start time of the query.
+     */
+    public void setStartTime(Long startTimeParam) {
+        startTime = startTimeParam;
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Do the setters need to be public?

File: src/main/java/teammates/common/util/GaeVersionApi.java [hunk 83]
```diff
@@ -0,0 +1,73 @@
...
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * A wrapper class for GAE application admin API. e.g. version management
+ */
+public class GaeVersionApi {
+    
+    public GaeVersionApi() {
+    }
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/GaeVersionApi.java]: I don't think empty constructors need to be defined

File: src/main/java/teammates/common/util/GaeVersionApi.java [hunk 84]
```diff
@@ -0,0 +1,73 @@
...
+
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+
+import com.google.appengine.api.modules.ModulesService;
+import com.google.appengine.api.modules.ModulesServiceFactory;
+
+/**
+ * A wrapper class for GAE application admin API. e.g. version management
```
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/GaeVersionApi.java]: No longer accurate, since the function is already narrowed down to version management.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 85]
```diff
@@ -11,33 +10,43 @@
...
+    private static final int SEARCH_TIME_INCREMENT = 2 * 60 * 60 * 1000;  // two hours in milliseconds
+    /**
+     * The maximum number of times to retrieve logs with time increment.
+     */
+    private static final int MAX_SEARCH_TIMES = MAX_SEARCH_PERIOD / SEARCH_TIME_INCREMENT;
+    /**
+     * Maximum number of versions to query.
+     * The current value will include the current version and its 5 preceding versions.
+     */
+    private static final int MAX_VERSIONS_TO_QUERY = 6;
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: Consider representing the value as `1 + 5`; redundancy aside, it's in line with the explanation.

File: src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java [hunk 86]
```diff
@@ -101,7 +116,20 @@ protected ActionResult execute() throws EntityDoesNotExistException{
...
+    private List<String> getVersionsForQuery(List<String> versions) {
+        boolean isVersionSpecifiedInRequest = (versions != null && !versions.isEmpty());
+        if (isVersionSpecifiedInRequest) {
+            return versions;
+        }
+        GaeVersionApi versionApi = new GaeVersionApi();
+        return versionApi.getMostRecentVersions(MAX_VERSIONS_TO_QUERY);
+    }
+    
+    private void generateStatusMessage(List<String> versionToQuery, AdminLogQuery query, AdminActivityLogPageData data, List<ActivityLogEntry> logs, String courseId) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java]: A line break here would be good.

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 87]
```diff
@@ -1,42 +1,59 @@
...
+        Long endTimeToSearch;
+        if ((timeOffset != null) && (!timeOffset.isEmpty())) {
+            endTimeToSearch = Long.parseLong(timeOffset);
+        } else {
+            endTimeToSearch = TimeHelper.now(0.0).getTimeInMillis();
+        }
         
-        AdminEmailLogPageData data = new AdminEmailLogPageData(account, getRequestParamValue("offset"),
-                                        getRequestParamValue("filterQuery"), getRequestParamAsBoolean("all"));
+        AdminEmailLogPageData data = new AdminEmailLogPageData(account, getRequestParamValue("filterQuery"), getRequestParamAsBoolean("all"));
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: Line break here too.

File: src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java [hunk 88]
```diff
@@ -46,154 +63,82 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
+            emailLogs.addAll(filteredLogs);
+            totalLogsSearched += searchResult.size();
+            query.moveTimePeriodBackward(SEARCH_TIME_INCREMENT);;
         }
+        nextEndTimeToSearch = query.getEndTime();
         
-        return recentVersions;
+        String status="&nbsp;&nbsp;Total Logs gone through in last search: " + totalLogsSearched + "<br>";
+        //link for Next button, will fetch older logs
+        status += "<button class=\"btn-link\" id=\"button_older\" onclick=\"submitFormAjax('" + nextEndTimeToSearch + "');\">Search More</button>";
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java]: And here.

**Comment by wkurniawan07** [comment]
Added some comments, mostly cosmetic changes.

File: src/main/java/teammates/common/util/AdminLogQuery.java (hunk 82 above)
Comment (bamboo3250) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: But it also doesn't make sense to have private a setter. I created it just in case we need it later.

**Comment by bamboo3250** [comment]
Cosmetic changes made. Ready for review.

File: src/main/java/teammates/common/util/AdminLogQuery.java (hunk 82 above)
Comment (wkurniawan07) [inline src/main/java/teammates/common/util/AdminLogQuery.java]: Private setter is actually not uncommon (in public getter-private setter combo). Also, "just in case we need it later" [is not a good reason to implement it now](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

**Comment by bamboo3250** [comment]
Okay, 2 setters are removed

**Comment by wkurniawan07** [comment]
Looks good now :+1:
Again, as a follow up to this, I suggest you take a look at `CompileLogs`, `CompileLogsServlet`, and `EntityModifiedLogsServlet` (all in `logic.automated`). The new classes defined here might be reusable in those places.
