### PR TITLE
Fix typos in CourseRoster, TeamEvalResult and FieldValidator #6983

### LINKED ISSUE #6983: Typos in CourseRoster, TeamEvalResult and FieldValidator
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

CourseRoster.java
Stuent is not a word according to provided dictionary
``` java
    public CourseRoster(List<StudentAttributes> students, List<InstructorAttributes> instructors) {
        populateStuentListByEmail(students);
        populateInstructorListByEmail(instructors);
    }
```

TeamEvalResult.java
Should be camel case sumOfPerceived
``` java
        double sumOfperceived = sum(filteredPerceived);
        double sumOfActual = sum(filteredSanitizedActual);
```

FieldValidator.java
Invalidty is not a word according to provided dictionary
``` java
    public String getInvalidityInfoForTimeForVisibilityStartAndResultsPublish(Date visibilityStart,
                                                                              Date resultsPublish) {
        return getInvalidtyInfoForFirstTimeIsBeforeSecondTime(visibilityStart, resultsPublish,
                SESSION_VISIBLE_TIME_FIELD_NAME, RESULTS_VISIBLE_TIME_FIELD_NAME);
    }
```

### PR DESCRIPTION
**Pull request by Bedol**
Fixes #6983

### CODE REVIEW

File: src/main/java/teammates/common/util/FieldValidator.java [hunk 1]
```diff
@@ -621,12 +621,12 @@ public String getInvalidityInfoForTimeForVisibilityStartAndSessionStart(Date vis
...
                                                                               Date resultsPublish) {
-        return getInvalidtyInfoForFirstTimeIsBeforeSecondTime(visibilityStart, resultsPublish,
+        return getInvalidityInfoForFirstTimeIsBeforeSecondTime(visibilityStart, resultsPublish,
                 SESSION_VISIBLE_TIME_FIELD_NAME, RESULTS_VISIBLE_TIME_FIELD_NAME);
     }
 
-    private String getInvalidtyInfoForFirstTimeIsBeforeSecondTime(Date earlierTime, Date laterTime,
-            String earlierTimeFieldName, String laterTimeFieldName) {
+    private String getInvalidityInfoForFirstTimeIsBeforeSecondTime(Date earlierTime, Date laterTime,
+                                                                   String earlierTimeFieldName, String laterTimeFieldName) {
```
Comment (damithc) [inline src/main/java/teammates/common/util/FieldValidator.java]: @leeyimin should we use 8 space indentation here? Perhaps like this?
```java
private String getInvalidityInfoForFirstTimeIsBeforeSecondTime(
        Date earlierTime, Date laterTime, String earlierTimeFieldName, String laterTimeFieldName) {
```

Comment (leeyimin) [inline src/main/java/teammates/common/util/FieldValidator.java]: @damithc I agree. It looks fine on Github but it looks cramped on IDE :joy:

Comment (junhaoyap) [inline src/main/java/teammates/common/util/FieldValidator.java]: I think that means @Bedol needs to relook at things, setting it back ongoing for now
