### PR TITLE
[#8011] Improve scalability of student cascade delete

### LINKED ISSUE #8011: Instructor: edit students: improve efficiency of 'delete all students'
v5.110

I noticed that an instructor is trying to 'delete all students' of a course with 500+ students and constantly running into a 'task cancelled' error.

```
teammates.common.util.Logger severe: Unexpected exception caught by ControllerServlet :  (Logger.java:52)
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1170)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:492)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:402)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:89)
	at com.google.appengine.tools.development.TimedFuture.get(TimedFuture.java:42)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:20)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$7.get(AsyncDatastoreServiceImpl.java:406)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$7.get(AsyncDatastoreServiceImpl.java:402)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.googlecode.objectify.impl.ResultAdapter.now(ResultAdapter.java:34)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
	at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at teammates.storage.api.EntitiesDb.deleteEntity(EntitiesDb.java:216)
	at teammates.logic.core.FeedbackResponsesLogic.deleteFeedbackResponseAndCascade(FeedbackResponsesLogic.java:682)
	at teammates.logic.core.FeedbackResponsesLogic.deleteFeedbackResponsesForStudentAndCascade(FeedbackResponsesLogic.java:746)
	at teammates.logic.core.StudentsLogic.deleteStudentCascade(StudentsLogic.java:476)
	at teammates.logic.core.StudentsLogic.deleteStudentCascade(StudentsLogic.java:467)
	at teammates.logic.core.StudentsLogic.deleteAllStudentsInCourse(StudentsLogic.java:462)
	at teammates.logic.api.Logic.deleteAllStudentsInCourse(Logic.java:1033)
	at teammates.ui.controller.InstructorCourseStudentDeleteAllAction.execute(InstructorCourseStudentDeleteAllAction.java:21)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:474)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:75)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at teammates.ui.controller.AppstatsFilter.doFilter(AppstatsFilter.java:41)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:657)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:619)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:589)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:263)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by jianhandev**
Fixes #8011 

When an instructor tries to delete all students from a course with a sufficiently large number of students, the backend will timeout before it even gets to complete all the deletion. This is due to the cascade delete of responses and comments belonging to the student, on top of the deletion of the student entities themselves. 

**Outline of Solution**
* Limit the number of students to delete per request, using the `limit` query parameter to allow the frontend to control the maximum number of students to delete cascade in one request.
* For the deletion of a large number of students in a course, issue multiple delete requests until all the students in the course are successfully deleted
* Partial deletion is possible in cases where a request is unsuccessful or when user aborts, but user should be able to continue the deletion upon retry

**UX Improvements**
* Display delete progress modal with progress bar while the deletion is being processed

https://user-images.githubusercontent.com/59337195/154885188-0f412a56-12bb-4d6c-bd41-d873ea31ba07.mov

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/DeleteStudentsAction.java [hunk 1]
```diff
@@ -27,9 +27,10 @@ void checkSpecificAccessControl() throws UnauthorizedAccessException {
     @Override
     public JsonResult execute() {
         String courseId = getNonNullRequestParamValue(Const.ParamsNames.COURSE_ID);
+        String limit = getNonNullRequestParamValue(Const.ParamsNames.LIMIT);
```
Comment (moziliar) [inline src/main/java/teammates/ui/webapi/DeleteStudentsAction.java:30]: Can we make it Nullable so that we can still delete student without limit?

File: src/main/java/teammates/common/util/Const.java [hunk 2]
```diff
@@ -170,6 +170,8 @@ private Const() {
         public static final String QUERY_LOGS_VERSION = "version";
         public static final String QUERY_LOGS_EXTRA_FILTERS = "extrafilters";
         public static final String QUERY_LOGS_ORDER = "order";
+
+        public static final String LIMIT = "limit";
```
Comment (moziliar) [inline src/main/java/teammates/common/util/Const.java:174]: I feel like this name can get more descriptive, say `DELETE_STUDENTS_BATCH_LIMIT`

Comment (jianhandev) [reply src/main/java/teammates/common/util/Const.java:174]: That was what I did initially, but I reasoned that there might be chances we use the limit param for other purposes/endpoints in the future, limit feels more like a general parameter than one that is specific to our delete all endpoint.

File: src/main/java/teammates/ui/webapi/DeleteStudentsAction.java (hunk 1 above)
Comment (jianhandev) [reply src/main/java/teammates/ui/webapi/DeleteStudentsAction.java:30]: Good point, but for now I do not see any place where deleting student without limit is beneficial 🤔

**Comment by hhdqirui** [comment]
@wkurniawan07 @madanalogy @rrtheonlyone please help to review this PR when convenient. Thanks!

File: src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts [hunk 3]
```diff
@@ -212,22 +216,68 @@ export class InstructorCourseDetailsPageComponent implements OnInit {
...
+        this may take a while...`;
+    const loadingModal: NgbModalRef = this.simpleModalService.openLoadingModal(
+        'Delete Progress', SimpleModalType.LOAD, modalContent);
+
+    loadingModal.result.then(() => {
+      // Modal is closed
+      this.isDeleting = false;
+
+      if (numOfRequestsCompleted === totalNumOfRequests) {
+        this.statusMessageService.showErrorToast('All the students have been removed from the course');
```
Comment (moziliar) [inline src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts:236]: `showErrorToast`?

Comment (moziliar) [reply src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts:236]: Should it be `this.statusMessageService.showSuccessToast`

File: src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts [hunk 4]
```diff
@@ -123,4 +148,94 @@ describe('InstructorCourseDetailsPageComponent', () => {
...
+    };
+    component.courseDetails = courseDetails;
+    fixture.detectChanges();
+
+    const spyStudentService: SpyInstance = jest.spyOn(studentService, 'batchDeleteStudentsFromCourse')
+        .mockReturnValue(of({ message: 'Successful' }));
+
+    jest.spyOn(statusMessageService, 'showErrorToast')
+        .mockImplementation((args: string) => {
+          expect(args).toEqual('All the students have been removed from the course');
```
Comment (moziliar) [inline src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts:204]: Ditto

**Review by moziliar — CHANGES_REQUESTED** [review]
LGTM! Perhaps the showError can be showSuccess

File: src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts [hunk 5]
```diff
@@ -57,9 +82,9 @@ describe('InstructorCourseDetailsPageComponent', () => {
 
   it('should snap with a course with one co-owner and no students, and populated course student list', () => {
     const stats: any = {
```
Comment (wkurniawan07) [inline src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts:84]: The fact that you know that `*Total` are not the right fields means that this should not be `any`. Need to add the right typing for this.

**Review by moziliar — APPROVED** [review]
LGTM!

**Review by wkurniawan07 — APPROVED** [review]
LGTM
