### PR TITLE
Instructor results: fix unreliable respondents list #8097

### LINKED ISSUE #8097: Instructor results: fix unreliable respondents list
reporting at v5.110 but was present even before

When an instructor view the results page, sometimes the 'Unsbumitted' list at the bottom contains students that have actually submitted. There were several cases of this and I was able to fix by clicking on the 'submit responses' button (which takes me to the submission page of the student where the form is already filled with existing values) and submitting again.

### PR DESCRIPTION
**Pull request by whipermr5**
Fixes #8097

**Outline of Solution**
- Use transactions to avoid race condition
- Use task queues to limit the impact of failing transactions

### CODE REVIEW

**Comment by LiHaoTan** [comment]
I'm curious, why not transactions?

**Comment by wkurniawan07** [comment]
@LiHaoTan https://github.com/TEAMMATES/teammates/blob/master/docs/design.md#policies-1

That decision was made way back then (even before I joined the team) and this are is never under my portfolio, so if you want to relook into it, by all means.

**Comment by damithc** [comment]
Back then transactions could not be applied across objects of different groups.

**Comment by whipermr5** [comment]
@LiHaoTan My own reasoning was that feedback submissions would become even slower if we use transactions within the main action. But actually transactions within the task queue sounds good; that way it doesn't have to be single-threaded.

**Comment by LiHaoTan** [comment]
@whipermr5 I don't quite catch why feedback submissions would become even slower if we use transactions. Is it because submissions nowadays are so frequently submitted at the same time so using transactions to retry can be slow?

> But actually transactions within the task queue sounds good; that way it doesn't have to be single-threaded. 

I actually didn't think of this, but one reason why I did not really like task queues is that the status of the submission then becomes invisible and sent to a queue (and if we do hit scaling issues like this I think a redesign of UX would be necessary). 

So I was thinking that it may be better for a submission to take a little longer unless it takes too long then I think it's probably time for at least this part of the schema to be re-designed and maybe a temporary solution like task queue would be good?

At the end of the day, my intuition tells me that good schema design along with transactions should be more than scalable enough, I doubt we will hit the limits ever for TEAMMATES if we do it that way.

Definitely, I think a temporary solution needs to be quickly put out though, like task queues as you proposed but if we can use transactions I think it is a lot cleaner.

File: src/main/java/teammates/ui/automated/FeedbackSessionUpdateRespondentWorkerAction.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+            } else {
+                if (isToBeRemoved) {
+                    logic.deleteStudentRespondent(email, feedbackSessionName, courseId);
+                } else {
+                    logic.addStudentRespondent(email, feedbackSessionName, courseId);
+                }
+            }
+        } catch (InvalidParametersException | EntityDoesNotExistException e) {
+            log.severe("Failed to " + (isToBeRemoved ? "remove" : "append") + " "
+                    + (isInstructor ? "instructor" : "student") + " respondent");
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/automated/FeedbackSessionUpdateRespondentWorkerAction.java]: Let's not swallow the stack trace here.

**Comment by wkurniawan07** [comment]
@whipermr5 Before I/anyone review this, can I check that transactions don't give problem anymore (like it did pre-2014)?

**Comment by whipermr5** [comment]
@wkurniawan07 This time, we're only using transactions for a small, specific operation - updating the respondent list in a `FeedbackSession` entity. The limitation (a transaction cannot be applied across entities of different groups) doesn't apply for this use case.

File: src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java [hunk 2]
```diff
@@ -117,22 +116,12 @@ private void checkSessionQuestionAccessPermission(InstructorAttributes instructo
 
     @Override
     protected void appendRespondent() {
-        try {
-            logic.addInstructorRespondent(getUserEmailForCourse(), feedbackSessionName, courseId);
-        } catch (InvalidParametersException | EntityDoesNotExistException e) {
-            log.severe("Failed to append instructor respondent. "
-                       + "Feedback Session [" + feedbackSessionName + "] of Course ID [" + courseId + "]");
-        }
+        taskQueuer.scheduleUpdateRespondentForSession(courseId, feedbackSessionName, getUserEmailForCourse(), true, false);
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java]: Should test in action level that there is a task queued.

**Comment by whipermr5** [comment]
@wkurniawan07 Reminder 😅

File: src/main/java/teammates/storage/api/FeedbackSessionsDb.java [hunk 3]
```diff
@@ -194,14 +195,27 @@ public void addInstructorRespondents(List<String> emails, FeedbackSessionAttribu
...
+                        throw new RuntimeException(new EntityDoesNotExistException(
+                                ERROR_UPDATE_NON_EXISTENT + feedbackSession.toString()));
+                    }
+
+                    fs.getRespondingInstructorList().addAll(emails);
+
+                    saveEntity(fs, feedbackSession);
+                }
+            });
+        } catch (RuntimeException e) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: This looks dangerous. Why catch a `RuntimeException` here?

Comment (whipermr5) [reply src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: This is the only way to throw a checked exception from within the block of code to be run in a transaction: https://groups.google.com/d/msg/objectify-appengine/0NcX0KLNIDo/6ljC6M9-x98J

Comment (wkurniawan07) [reply src/main/java/teammates/storage/api/FeedbackSessionsDb.java]: Can't say I like this method, but we don't really have a say since this is a library restriction.
