### PR TITLE
Instructor: edit question: fix erratic behavior when editing followed by deleting #8333

### LINKED ISSUE #8333: Instructor: edit question: fix erratic behavior when editing followed by deleting
**Environment**
`master` branch at 1c43cce but possibly has existed long before.

**Steps to reproduce**
1. Edit a feedback question
2. Clear the textarea of the question name
3. Click "save", and validation message "Please enter a valid question. The question text cannot be empty"will show up.
4. Retry saving.
5. Click the "delete" button, press "yes" for the warning box. Validation message "Please enter a valid question. The question text cannot be empty" shows up again.
6. Add a valid name for the name of the question so that it is no longer empty.
7. Click "save", and now the question is deleted. 

**Expected behaviour**
When deleting question after failing to edit it, the question should be deleted.
Correcting and saving the question after failing to delete it should still save the question.

**Actual behaviour**
When deleting question after failing to edit it, validation message "Please enter a valid question. The question text cannot be empty" popped out.
Correcting and saving the question after failing to delete it eventually delete the question.

### PR DESCRIPTION
**Pull request by LuLechuan**
Fixes #8333

**Outline of Solution**

In the okCallback of the delete question method, restore the original question before deletion. In this way, even if previously the edition is not successful, deletion can succeed as the original question is restored first before the actual deletion.
In addition, since the question can be deleted successfully, there would not be a situation whereby saving a question results in a deletion of the question.

The error as described from the issue will no longer be reproduced.

### CODE REVIEW

**Comment by LuLechuan** [comment]
Adding test cases now

**Comment by wkurniawan07** [comment]
@LuLechuan is this ready for review?

**Comment by LuLechuan** [comment]
Hi @wkurniawan07, the bug is already fixed. However, I am trying to add a JS test case for this bug but I still encounter a problem on how to come up with the test.

**Comment by LuLechuan** [comment]
@wkurniawan07 Ready to be reviewed

**Comment by LuLechuan** [comment]
@LiHaoTan ready to be reviewed

File: src/main/webapp/dev/js/main/instructorFeedbackEdit.js [hunk 1]
```diff
@@ -302,6 +309,7 @@ function bindFeedbackSessionEditFormSubmission() {
  * @param questionNum
  */
 function disableQuestion(questionNum) {
+    $(`#${ParamsNames.FEEDBACK_QUESTION_EDITTYPE}-${questionNum}`).val('edit');
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/main/instructorFeedbackEdit.js]: Hmm? What is the purpose of changing the edit type to `edit` here? Was your intention to make the state as consistent as possible?

But we can't account for new functions and I'm not sure if we have missed any other cases where it should have been `edit` rather than `delete`.

That's why it's easier to just set the edit type to `edit` when submitting.

File: src/main/webapp/dev/js/main/instructorFeedbackEdit.js [hunk 2]
```diff
@@ -561,26 +569,6 @@ function enableNewQuestion() {
     hideInvalidRankRecipientFeedbackPaths(NEW_QUESTION);
 }
 
-/**
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/main/instructorFeedbackEdit.js]: Is there still a need to move this function?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 3]
```diff
@@ -104,7 +104,7 @@ private void testGeneralQuestionOperations() throws Exception {
         testAjaxOnVisibilityMessageButton();
 
         testDeleteQuestionAction(2);
-        testDeleteQuestionAction(1);
+        testEditThenDeleteQuestionAction(1);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Nice way of combining tests so we don't spend (too much) more resources!

Good workaround since it is too difficult at this point in time to test this at the Javascript level (which we should actually).

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 4]
```diff
@@ -876,7 +876,18 @@ private void testDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceede
...
         feedbackEditPage.verifyStatus(Const.StatusMessages.FEEDBACK_QUESTION_DELETED);
         assertNull(getFeedbackQuestion(courseId, feedbackSessionName, qnNumber));
+    }
+
+    private void testEditThenDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceededException {
+        ______TS("qn " + qnNumber + " edit the question with invalid input then delete question");
 
+        feedbackEditPage.clickEditQuestionButton(qnNumber);
+        feedbackEditPage.fillQuestionTextBox("", qnNumber);
+        feedbackEditPage.clickSaveExistingQuestionButton(qnNumber);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Let's add a verify status to make this clearer and to make sure there's an error first?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 5]
```diff
@@ -876,7 +876,18 @@ private void testDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceede
...
+        feedbackEditPage.clickDeleteQuestionLink(qnNumber);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Separate this with a newline?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 6]
```diff
@@ -876,7 +876,18 @@ private void testDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceede
         feedbackEditPage.waitForConfirmationModalAndClickOk();
         feedbackEditPage.verifyStatus(Const.StatusMessages.FEEDBACK_QUESTION_DELETED);
         assertNull(getFeedbackQuestion(courseId, feedbackSessionName, qnNumber));
+    }
+
+    private void testEditThenDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceededException {
+        ______TS("qn " + qnNumber + " edit the question with invalid input then delete question");
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Suggestion: `... with empty question text then ...`

**Comment by LuLechuan** [comment]
@LiHaoTan Thanks for the comments. Changes made as requested.

File: src/main/webapp/dev/js/main/instructorFeedbackEdit.js [hunk 7]
```diff
@@ -1104,8 +1110,15 @@ function readyFeedbackEditPage() {
     });
 
     $('form.form_question').submit(function () {
+        // Submission and deletion logic are coupled and determined by the global state.
+        // However, validating the form does not make sense when deleting.
+        const questionNum = $(this).data('qnnumber');
+        const editType = $(`#${ParamsNames.FEEDBACK_QUESTION_EDITTYPE}-${questionNum}`).val();
         addLoadingIndicator($('#button_submit_add'), 'Saving ');
-        const formStatus = checkFeedbackQuestion(this);
+        let formStatus = checkFeedbackQuestion(this);
```
Comment (LiHaoTan) [inline src/main/webapp/dev/js/main/instructorFeedbackEdit.js]: We should not even validate if the `editType` is `delete`?

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 8]
```diff
@@ -876,7 +876,22 @@ private void testDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceede
...
+
+    private void testEditWithEmptyQuestionTextThenDeleteQuestionAction(int qnNumber)
+            throws MaximumRetriesExceededException {
+        ______TS("qn " + qnNumber + " edit the question with invalid input then delete question");
+
+        feedbackEditPage.clickEditQuestionButton(qnNumber);
+        feedbackEditPage.fillQuestionTextBox("", qnNumber);
+        feedbackEditPage.clickSaveExistingQuestionButton(qnNumber);
+        String expectedString = "Please enter a valid question. The question text cannot be empty.";
+        feedbackEditPage.verifyStatus(expectedString);
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Use `Const#FEEDBACK_QUESTION_TEXTINVALID`?  And can you rename it to use underscores?

Optionally, you can also move that constant to the appropriate test page because it is only used in tests.

**Comment by LuLechuan** [comment]
@LiHaoTan Ok, I had a misunderstanding for the Legacy Implementation. Thanks for the clarification!

**Comment by LuLechuan** [comment]
@LiHaoTan Changes made as requested

File: src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java [hunk 9]
```diff
@@ -876,7 +876,22 @@ private void testDeleteQuestionAction(int qnNumber) throws MaximumRetriesExceede
...
+    }
+
+    private void testEditWithEmptyQuestionTextThenDeleteQuestionAction(int qnNumber)
+            throws MaximumRetriesExceededException {
+        ______TS("qn " + qnNumber + " edit the question with invalid input then delete question");
+
+        feedbackEditPage.clickEditQuestionButton(qnNumber);
+        feedbackEditPage.fillQuestionTextBox("", qnNumber);
+        feedbackEditPage.clickSaveExistingQuestionButton(qnNumber);
+        String expectedString = Const.StatusMessages.FEEDBACK_QUESTION_TEXTINVALID;
```
Comment (LiHaoTan) [inline src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Just a query: Why not rename this to use underscores as well?

And can't we just inline `expectedString`, doesn't seem to be useful to have a separate local variable here?

Comment (LuLechuan) [reply src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java]: Opps, that's just because previous I did not use Const. Yes I feel inline is better

**Comment by LuLechuan** [comment]
@LiHaoTan Thanks for the comments! Ready to be reviewed.

**Comment by LuLechuan** [comment]
@LiHaoTan Changes made as requested
