### PR TITLE
[#10574] [#10575] [#10576] Fix back-end related issues

### LINKED ISSUE #10574: Student Home Page: Cannot view team with unregistered student
- **Environment**: `V7.0.2`

**Steps to reproduce**
1) Enroll students in the same team and send invite to one of them
2) Join course with one student
3) Click view team on student home page

V7:
view teams

V6:
view teams 2

### LINKED ISSUE #10575: Encoded symbols in error messages
- **Environment**: `V7.0.2`

**Steps to reproduce**
Try to create course or session with symbols "<>&/"

V7:
Symbols

V6:
Symbols2

### LINKED ISSUE #10576: Admin sessions page: filter not working
- **Environment**: `master` branch at commit 8125949fc1d2372648f520e4afb495deeef29f1f

**Steps to reproduce**
Filter ongoing sessions in admin sessions page

**Expected behaviour**
Only sessions between date should be shown

**Actual behaviour**
All ongoing sessions are shown

**Additional info**
filter

### PR DESCRIPTION
**Pull request by wkurniawan07**
This fixes some back-end operations:
- Fixes #10574 
  - Change `404` to `200` (cannot use `204` because the response body will be stripped) and return empty student profile if the student has not registered. `404` is appropriate when the target student is not found.
- Fixes #10575 
  - This was due to HTML sanitization when constructing error message. HTML sanitization in the back-end is no longer necessary and in fact should not be done. The only place where HTML sanitization is still relevant is email content generation.
- Fixes #10576 
  - This was due to the sessions queried via start time and end time are combined with OR operation, not AND.

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java [hunk 1]
```diff
@@ -52,32 +50,38 @@ public ActionResult execute() {
...
             studentId = student.getGoogleId();
+            studentName = student.getName();
         }
 
+        StudentProfileAttributes studentProfile;
+
         if (StringHelper.isEmpty(studentId)) {
-            // The student has not registered.
-            return new JsonResult(MESSAGE_STUDENT_NOT_REGISTERED, HttpStatus.SC_NOT_FOUND);
+            studentProfile = StudentProfileAttributes.builder("placeholderId").build();
```
Comment (xpdavid) [inline src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java:71]: Can we just use empty string here?
