### PR TITLE
Attributes tests: avoid passing in an empty Google ID for student profiles #7645

### LINKED ISSUE #7645: Attributes tests: avoid passing in an empty Google ID for student profiles
The Objectify code constructs a key for the `Ref` object in linking `Account` and `StudentProfile` entities in a parent-child relationship. The key construction fails if the `StudentProfile` ID (the Google ID) is empty. Currently, the code adds an ugly workaround just to get existing tests to pass: https://github.com/TEAMMATES/teammates/pull/7338#discussion_r122919378

The tests should be fixed and the workaround, removed.

### PR DESCRIPTION
**Pull request by craaaa**
Fixes #7645 

**Outline of Solution**
- Tests currently don't contain `StudentProfile`s without google IDs. So removing workaround code is immediately possible
- To ensure this doesn't get broken again, changed `StudentProfileAttributes` to require google IDs on construction

### CODE REVIEW

**Comment by craaaa** [comment]
Noticed while doing this that 
- `StudentProfileAttributes` contains public attributes that continue to be referenced
- Builder class isn't used when building sometimes (e.g. `teammates/ui/controller/StudentProfileEditSaveAction.java`)

**Comment by whipermr5** [comment]
@craaaa You'll need to fix the failing tests; I believe they're the reason the workaround was introduced.

**Comment by craaaa** [comment]
Figured out the problem: although Objectify keys are now being created, the actual `StudentProfile` the keys refer to aren't stored in the datastore, and so cannot be retrieved when we try to create a new `AcountAttributes` instance using `toEntity()`. Two possible solutions:
- Allow `AccountAttributesTest` to extend `BaseTestCaseWithDatastoreAccess` or `BaseComponentTestCase` -- this will test the full implementation of the method as used in production -- a more complete solution; however, kind of overkill to bring in the whole of the datastore for a single call?
- Compare whether `Ref<StudentProfile>` objects are equal instead of attempting to retrieve the (nonexistent) StudentProfile -- equality of the Ref equates to shallow equality of StudentProfiles, since that one key retrieves a unique item. Moreover, since the method tests the `toEntity()` method, datastore access is arguably out of scope, and would perhaps be better off tested in `ProfilesDbTest`.

I'm leaning towards the second solution, but wonder what you think @whipermr5 !

**Comment by whipermr5** [comment]
> Figured out the problem: although Objectify keys are now being created, the actual StudentProfile the keys refer to aren't stored in the datastore, and so cannot be retrieved when we try to create a new AcountAttributes instance using toEntity().

Does the call to `toEntity()` really try to retrieve the entity from the database? I don't think anything is retrieved without a call to `ofy().load()` (though I might be wrong).

**Comment by craaaa** [comment]
Since `Account` keeps a `Ref` while `AccountAttributes` wants an actual StudentProfile, the `AccountAttributes` constructor `new AccountAttributes(expectedAccount)` tries to retrieve a StudentProfile from the database.

Solved by saving the expected `StudentProfile` to the datastore so that it can be retrieved in later `get()` calls (by constructor + asserts that try to `getStudentProfile()`).

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 1]
```diff
@@ -71,9 +72,12 @@ public void testGetEntityTypeAsString() {
...
     public void testToEntity() {
         AccountAttributes account = createValidAccountAttributesObject();
-        Account expectedAccount = new Account(account.googleId, account.name, account.isInstructor,
-                account.email, account.institute, StudentProfileAttributes.builder().build().toEntity());
+        Account expectedAccount = new Account(account.googleId, account.name,
+                account.isInstructor, account.email, account.institute,
+                StudentProfileAttributes.builder(account.googleId).build().toEntity());
 
+        // save studentProfile to datastore so that it can be retrieved later
+        new ProfilesDb().saveEntity(account.studentProfile.toEntity());
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: I realised this isn't actually necessary. There's a much simpler way to construct `actualAccount` that doesn't try to retrieve the student profile entity from the database.

Comment (craaaa) [reply src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Hm, I'm not sure that the problem lies only with the `actualAccount` constructor (although using `Account actualAccount = account.toEntity()` is probably better; will make the necessary changes!). Checking for equality between `expectedAccount` and `actualAccount` requires calling `getStudentProfile()` which in turn uses `get()` which looks in the datastore since we're no longer storing `studentProfile`s locally in the `Account`.

Comment (whipermr5) [reply src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Well `account.toEntity()` passes. Might be because the student profile is null?

**Comment by whipermr5** [comment]
Also, can you rebase your changes onto the latest master and force push? Some unrelated commits are showing up here.

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java (hunk 1 above)
Comment (craaaa) [reply src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: `account.toEntity()` works because it constructs the Account entity from an `AccountAttributes` object which stores a `StudentProfileAttributes` object so no datastore references are needed. But `actualAccount.toEntity()` creates an `Account` object that stores a `Ref<StudentProfile>` instead of saving the actual `StudentProfile` or `StudentProfileAttributes`, so when the test tries to compare the StudentProfileAttributes later there's a null pointer error (around line 85).

**Comment by craaaa** [comment]
OK, I think I've isolated the problem! We do need to add `account.studentProfile` to the datastore for it to be retrieved by `getStudentProfile()`. On a clean datastore, `getStudentProfile()` returns null unless the StudentProfile is saved, hence the failing Travis test. But if you do this:
1) Run test with a call to save `account.studentProfile` to a `profilesDB`
2) Run the test again

Then it passes because the `account.studentProfile` from the first run is still in the datastore, and shares the same googleID (i.e. datastore key) as the second run's `account.studentProfile`. That might explain why our local tests appear to pass!

**Comment by whipermr5** [comment]
The conflicts need to be resolved before the build can run.

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 2]
```diff
@@ -70,20 +71,24 @@ public void testGetEntityTypeAsString() {
     @Override
     @Test
     public void testToEntity() {
+        ProfilesDb profileDb = new ProfilesDb();
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Can move this to just above where it's called? Also rename to `profilesDb`.

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 3]
```diff
@@ -71,19 +72,23 @@ public void testGetEntityTypeAsString() {
...
 
-        Account actualAccount = AccountAttributes.valueOf(expectedAccount).toEntity();
+        Account actualAccount = account.toEntity();
 
         assertEquals(expectedAccount.getGoogleId(), actualAccount.getGoogleId());
         assertEquals(expectedAccount.getName(), actualAccount.getName());
         assertEquals(expectedAccount.getEmail(), actualAccount.getEmail());
         assertEquals(expectedAccount.getInstitute(), actualAccount.getInstitute());
         assertEquals(expectedAccount.isInstructor(), actualAccount.isInstructor());
+        ProfilesDb profilesDb = new ProfilesDb();
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Add a blank line above this?

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 4]
```diff
@@ -71,19 +72,23 @@ public void testGetEntityTypeAsString() {
...
+        profilesDb.saveEntity(account.studentProfile.toEntity());
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Add a blank line below this?

File: src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java [hunk 5]
```diff
@@ -71,19 +72,23 @@ public void testGetEntityTypeAsString() {
...
         String expectedProfile = StudentProfileAttributes.valueOf(expectedAccount.getStudentProfile()).toString();
         String actualProfile = StudentProfileAttributes.valueOf(actualAccount.getStudentProfile()).toString();
         assertEquals(expectedProfile, actualProfile);
+        profilesDb.deleteEntity(account.studentProfile);
```
Comment (whipermr5) [inline src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java]: Add a blank line above this?

**Comment by craaaa** [comment]
@whipermr5 Ready for review!

File: src/main/java/teammates/storage/entity/Account.java [hunk 6]
```diff
@@ -152,10 +145,6 @@ public void setStudentProfile(StudentProfile studentProfile) {
             return;
         }
         setIsStudentProfileEnabled(true);
-        if (studentProfile.getGoogleId().isEmpty()) { // only in local attribute tests
```
Comment (whipermr5) [inline src/main/java/teammates/storage/entity/Account.java]: Just realised while working on another PR that the javadoc for this method was not updated.
