### PR TITLE
[#9730] Student Enroll: Error when enrolling students with empty Section Name

### LINKED ISSUE #9730: Student Enroll: Error when enrolling students with empty Section Name
- **Environment**: 
`master` branch at commit 5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4

**Steps to reproduce**
1. Go to /web/instructor/courses/enroll?courseid=ANY_VALID_COURSE_ID
2. Try to add a student with valid input under **Team**, **Name** and **Email** but leave the **Section** empty.
3. Observe the error message.
longmessage

**Expected behaviour**
Since the error message states that **Section** and **Comments** are optional, either enrollment should have succeeded or error message should not mention that **Section** is optional.

**Actual behaviour**
An error message will be shown and the student will not be enrolled.

**Additional info**
error

### PR DESCRIPTION
**Pull request by erjillsison**
Fixes #9730

### CODE REVIEW

**Comment by erjillsison** [comment]
Will put on hold until #9753 is merged as both deal with enrollment

File: src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java [hunk 1]
```diff
@@ -318,7 +318,7 @@ public void update(UpdateOptions updateOptions) {
         updateOptions.commentOption.ifPresent(s -> comments = s);
         updateOptions.googleIdOption.ifPresent(s -> googleId = s);
         updateOptions.teamNameOption.ifPresent(s -> team = s);
-        updateOptions.sectionNameOption.ifPresent(s -> section = s);
+        updateOptions.sectionNameOption.ifPresent(s -> section = s.isEmpty() ? Const.DEFAULT_SECTION : s);
```
Comment (Adoby7) [inline src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: Here you only change the logic of updating student. The problem may still exist when you enroll a new student. Although previously I said to modify the DB layer (but note that this `StudentAttributes` actually is not DB layer), to isolate this issue, it is better to fix this problem in API layer. i.e. change the `studentEnrollRequest` to settle default section name if empty

Comment (erjillsison) [reply src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: Although it's not apparent, the change does cover both Enroll and Update actions because the `update()` method is used by `build()` which is used by both actions. 

But if it's better to do it in the API layer should I remove this from the `StudentAttributes`? or have both

Comment (Adoby7) [reply src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: Yes, it's better to remove the `StudentAttributes` change, and test it manually after you finish the API change.

Comment (erjillsison) [reply src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: I couldn't find a good way to place it in`StudentsEnrollRequest` so instead placed it in `EnrollStudentsAction` and `UpdateStudentAction`

Comment (Adoby7) [reply src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: A good way is to place it in `getter method` of `StudentEnrollRequest`. In addition, you may also want to add comment about this change, and make it covered by test

Comment (erjillsison) [reply src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java]: Updated. Moved the changes to `StudentEnrollRequest` and `StudentUpdateRequest`

File: src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java [hunk 2]
```diff
@@ -63,7 +95,8 @@ public void testExecute_withExistingStudent_shouldBeUpdatedToDatabase() {
         List<StudentData> enrolledStudents = executeActionAndReturnResults(courseId, req);
 
         assertEquals(1, enrolledStudents.size());
-        verifyStudentInDatabase(studentToUpdate, enrolledStudents.get(0).getCourseId(), enrolledStudents.get(0).getEmail());
+        verifyStudentInDatabase(
```
Comment (Adoby7) [inline src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java]: Why add a new line here? Does this line contain too many characters?

Comment (erjillsison) [reply src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java]: My bad. I thought the max char limit was 120. Reverted the change.
Anyway, yes, already manually tested. 

Thanks for reviewing!

File: src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java [hunk 3]
```diff
@@ -86,7 +118,8 @@ public void testExecute_withSectionFieldChanged_shouldBeUpdatedToDatabase() {
...
```
Comment (Adoby7) [inline src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java]: Well, there is the same new line character problem here

Comment (erjillsison) [reply src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java]: My bad. Fixed
