### PR TITLE
[#9405] Show default picture as profile photo for student who is yet to join

### LINKED ISSUE #9405: Show default picture as profile photo for student who is yet to join
- **Environment**: local server at `V7.0.0`, `master` branch at commit `ede259e`.

**Steps to reproduce**
Go to student search page and search for a yet to join student.

**Expected behaviour**
Logically, a student with `yet to join` tag should have a default profile picture or not clickable profile picture. It should not be the error message as shown in the current behaviour below when clicked on `View Photo`.
image

**Actual behaviour**
In `V6.0` a student profile with `yet to join` tag generates a default picture when clicked on the `View Photo`.
image

**Additional info**
Consider showing a default picture when clicked on or disable the ability to click `View Photo` for `yet to join` students.

### LINKED ISSUE #9416: Error in showing student detail of a yet to join student
**Environment**: Local server at `V7.0.0`, `master` branch at commit `3bc7b6a`

**Steps to reproduce**
- Login as an instructor
- Search for a student who is yet to join
- Under `Action(s)`, click the `View` button

**Expected behaviour**
image
In V6, the page shows a warning and the enrollment details of the student

**Actual behaviour**
image
Error in fetching the student detail

### PR DESCRIPTION
**Pull request by monmanuela**
Fixes #9405, fixes #9416 

**Outline of Solution**

For a student who is `yet to join`, clicking `View Photo` will show the default picture
image

### CODE REVIEW

File: src/main/java/teammates/ui/webapi/action/GetCourseStudentDetailsAction.java [hunk 1]
```diff
@@ -60,7 +60,10 @@ public ActionResult execute() {
             return new JsonResult("No course with given id.", HttpStatus.SC_NOT_FOUND);
         }
 
-        StudentProfileAttributes studentProfile = logic.getStudentProfile(student.googleId);
+        StudentProfileAttributes studentProfile = null;
+        if (!"".equals(student.googleId)) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/webapi/action/GetCourseStudentDetailsAction.java]: You can change this condition to `student.isRegistered()`.

Comment (monmanuela) [reply src/main/java/teammates/ui/webapi/action/GetCourseStudentDetailsAction.java]: Done!
