### PR TITLE
InstructorCourseRemindAction: extractUserName may not return username correctly #6513

### LINKED ISSUE #6513: InstructorCourseRemindAction: extractUserName may not return username correctly
The current implementation extracts the username from the email content and cuts off at the first comma, possibly returning the names of students incorrectly. If sanization is applied to the username in the email, eg. in #6454, desanitization would be required, which is additional work.

### PR DESCRIPTION
**Pull request by leeyimin**
Fixes #6513

**Outline of Solution**

Originally, the emails are generated just to extract username and registration key. This process is removed and the data for logging is captured from the *Attribute objects directly. 

- [x] Extract from *Attribute directly
- [x] Update tests

### CODE REVIEW

File: src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java [hunk 1]
```diff
@@ -105,20 +104,20 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
         
-        Iterator<Entry<String, JoinEmailData>> extractedEmailIterator =
-                extractEmailDataForLogging(emailsSent).entrySet().iterator();
+        Iterator<Entry<String, JoinEmailData>> emailIterator =
+                emailDataMap.entrySet().iterator();
         
-        while (extractedEmailIterator.hasNext()) {
-            Entry<String, JoinEmailData> extractedEmail = extractedEmailIterator.next();
+        while (emailIterator.hasNext()) {
+            Entry<String, JoinEmailData> email = emailIterator.next();
```
Comment (Neurrone) [inline src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java]: Is it possible to use an enhanced for loop for the iteration?

**Comment by leeyimin** [comment]
@wkurniawan07 Ready for review.

File: src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java [hunk 2]
```diff
@@ -105,54 +104,31 @@ public ActionResult execute() throws EntityDoesNotExistException {
...
-    private String extractRegistrationKey(String emailContent) {
-        int startIndex = emailContent.indexOf("key=") + "key=".length();
-        int endIndex = emailContent.indexOf("\">http://");
-        if (endIndex < 0) {
-            endIndex = emailContent.indexOf("\">https://");
-        }
-        return emailContent.substring(startIndex, endIndex);
+    private String extractStudentRegistrationKey(StudentAttributes student) {
+        String joinLink = Config.getAppUrl(student.getRegistrationUrl()).toAbsoluteString();
+        int startIndex = joinLink.indexOf("key=") + "key=".length();
```
Comment (chowyb) [inline src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java]: This could be changed to use a constant from the `Const` class instead of keeping the old magic string.

**Comment by leeyimin** [comment]
@chowyb Ready for review.
