### PR TITLE
Java: Use Java 7 try-with-resources for AutoCloseable resources #8213

### LINKED ISSUE #8213: Java: Use Java 7 try-with-resources for AutoCloseable resources
Stuffs like [this](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/FileHelper.java#L23-L32):
```java
BufferedReader br = new BufferedReader(new FileReader(filePath));
Scanner sc = new Scanner(br);
try {
    return sc.useDelimiter("\\Z").next();
} finally {
    sc.close();
    br.close();
}
```
can be modified to use the [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html):
```java
try (Scanner sc = new Scanner(new BufferedReader(new FileReader(filePath)))) {
    return sc.useDelimiter("\\Z").next();
}
```
The benefit is two-fold: makes the code shorter and also closes the linked resources without fail, although admittedly I cannot say for sure what will happen if the resources do leak.

There are more than 10 places in the code base where this can be applied. Some common [`AutoCloseable`](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) resources are `FileWriter`, `BufferedWriter`, `PrintWriter`, `FileOutputStream`, `OutputStreamWriter`, `Scanner`, `FileReader`, `BufferedReader`, `FileInputStream`, `InputStreamReader`.

### PR DESCRIPTION
**Pull request by elaborateruse**
Fixes #8213.

**Outline of Solution**

Enhanced the usage of various `AutoCloseable` implementing objects to a `try-with-resources` form.  This will ensure these resources get closed and don't leak.  In keeping with good practice about running in an app server, I didn't close the `HttpServletReponse` output writer instances used to write response objects.

### CODE REVIEW

File: src/test/java/teammates/test/cases/logic/EmailSenderTest.java [hunk 1]
```diff
@@ -82,15 +85,18 @@ public void testConvertToSendgrid() {
...
+
+            assertEquals(wrapper.getSenderName() + " <" + wrapper.getSenderEmail() + ">",
+                    formData.getField("from").getValue());
+            assertEquals(wrapper.getRecipient(), formData.getField("to").getValue());
+            assertEquals(wrapper.getBcc(), formData.getField("bcc").getValue());
+            assertEquals(wrapper.getReplyTo(), formData.getField("h:Reply-To").getValue());
+            assertEquals(wrapper.getSubject(), formData.getField("subject").getValue());
+            assertEquals(wrapper.getContent(), formData.getField("html").getValue());
+        } catch (IOException e) {
+            fail("Could not close email wrapper stream: " + TeammatesException.toStringWithStackTrace(e));
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/logic/EmailSenderTest.java]: Instead of catching the Exception and failing the test anyway, just throw the Exception as part of the method.

**Comment by elaborateruse** [comment]
Thanks, I will take a look at `GmailServiceMaker`.  As for the response Writer instance, however, I did not close them because it is maintained by some that the app server is responsible for closing these resources since the app server opens them and the consuming code is just `get`ting it and not responsible for it (Reference: https://stackoverflow.com/questions/1159168/should-one-call-close-on-httpservletresponse-getoutputstream-getwriter ).  If you feel like they should be closed, I am totally ok with that too; just explaining why I didn’t close them in the initial PR.  :-)

Thanks again for the review!

**Comment by wkurniawan07** [comment]
@elaborateruse it seems you're right about the `resp.getWriter()`; let's keep them intact.
On another note, take note that you're now including changes from other commits in this PR, possibly due to improper merging. Try your best to clean them.

**Comment by elaborateruse** [comment]
@wkurniawan07: Oops, sorry about that. I thought I was supposed to keep my branch even with `teammates/master`, but that doesn’t make sense in retrospect. I will clean it up.  Thanks!

**Comment by wkurniawan07** [comment]
@elaborateruse indeed you're encouraged to, but cherry-picking the commits one by one is not the way to.

**Comment by elaborateruse** [comment]
@wkurniawan07 Ok, I think we got it this time.  Let me know what else I need to do.  Thanks!

**Comment by elaborateruse** [comment]
@wkurniawan07 Thanks for your patience!

**Comment by whipermr5** [comment]
@elaborateruse Thanks for your contribution! May we have your full name for inclusion into the contributors' list? :)
