### PR TITLE
Fix next url parameter workaround not being handled when using regkey in Action class #7318

### LINKED ISSUE #7318: Fix next url parameter workaround not being handled when using regkey in Action class
Found a handful of warnings like this in the log (key slightly modified for security reasons). Is this something expected?
```
teammates.common.util.Logger warning: Attempted to decrypt invalid ciphertext: AAAAF55E70A28263651B92CF00929CB24FC88CCDB5C3434BA20D26C7719E6C335E2807905A5CD8BB44D25FD57B8AF3D1F23F1878E07284055CBD811ED5C412B1CD31C8B3FE141F2DA79D3F90B5A88981${amp}next=/page/studentFeedbackSubmissionEditPage?courseid=2017-ModC-BusinessGlobalSociety-BB${amp}fsname=Bay Bridge B.G.S. Peer Feedback${amp}key=AAAAF55E70A28263651B92CF00929CB24FC88CCDB5C3434BA20D26C7719E6C335E2807905A5CD8BB44D25FD57B8AF3D1F23F1878E07284055CBD811ED5C412B1CD31C8B3FE141F2DA79D3F90B5A88981${amp}studentemail=aaaa@student.hult.edu 
```

### PR DESCRIPTION
**Pull request by Neurrone**
Fixes #7318 

**Outline of Solution**

This issue is caused by regkey parameter containing info about the next url, and methods in the Action classes not accounting for that.

Moved the special handling of the regkey parameter in requests introduced in #4575 up from StudentCourseJoinAuthenticatedAction to Action. 

A better long-term solution is to introduce another parameter such as nextUrlForRegkey so that this workaround isn't necessary.

### CODE REVIEW

File: src/main/java/teammates/ui/controller/Action.java [hunk 1]
```diff
@@ -101,11 +104,33 @@ protected void initialiseAttributes(HttpServletRequest req) {
...
         // Set error status forwarded from the previous action
         isError = getRequestParamAsBoolean(Const.ParamsNames.ERROR);
     }
 
+    /**
+     * Parses and initializes the regkey from the http request.
+     *
+     */
+    private void parseAndInitializeRegkeyFromRequest() {
+        String regkeyFromRequest = getRequestParamValue(Const.ParamsNames.REGKEY);
```
Comment (thenaesh) [inline src/main/java/teammates/ui/controller/Action.java]: Maybe you can use `getRegKeyFromRequest` here.

File: src/main/java/teammates/ui/controller/StudentCourseJoinAuthenticatedAction.java [hunk 2]
```diff
@@ -30,20 +30,7 @@
...
-             * next parameter, nextUrl, is treated as part of the "regkey".
-             * TODO move this process to Action class is possible.
-             */
-            String[] split = regkey.split("\\$\\{amp\\}" + Const.ParamsNames.NEXT_URL + "=");
-            regkey = split[0];
-            nextUrl = split[1];
-        } else {
-            nextUrl = getRequestParamValue(Const.ParamsNames.NEXT_URL);
-        }
+        String nextUrl = nextUrlFromRegkey == null ? getRequestParamValue(Const.ParamsNames.NEXT_URL) : nextUrlFromRegkey;
```
Comment (thenaesh) [inline src/main/java/teammates/ui/controller/StudentCourseJoinAuthenticatedAction.java]: I think comments should be added here too to explain why this is being done. Otherwise someone looking at this file may be lost. You could link to `parseAndInitializeRegkeyFromRequest` in the comment.

**Comment by whipermr5** [comment]
@thenaesh Reminder :)

File: src/main/java/teammates/ui/controller/Action.java [hunk 3]
```diff
@@ -106,10 +109,32 @@ protected void initialiseAttributes(HttpServletRequest req) {
...
         isError = getRequestParamAsBoolean(Const.ParamsNames.ERROR);
     }
 
+    /**
+     * Parses and initializes the regkey from the http request.
+     *
+     */
+    private void parseAndInitializeRegkeyFromRequest() {
+        String regkeyFromRequest = getRegkeyFromRequest();
+        if (regkeyFromRequest != null && regkeyFromRequest.contains("${amp}" + Const.ParamsNames.NEXT_URL + "=")) {
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/Action.java]: Extract the condition `regkeyFromRequest != null && regkeyFromRequest.contains("${amp}" + Const.ParamsNames.NEXT_URL + "=")` to a self-explanatory variable?

File: src/main/java/teammates/ui/controller/Action.java [hunk 4]
```diff
@@ -106,10 +109,32 @@ protected void initialiseAttributes(HttpServletRequest req) {
...
         session = request.getSession();
         sessionToken = CryptoHelper.computeSessionToken(session.getId());
+        parseAndInitializeRegkeyFromRequest();
         // Set error status forwarded from the previous action
         isError = getRequestParamAsBoolean(Const.ParamsNames.ERROR);
     }
 
+    /**
+     * Parses and initializes the regkey from the http request.
+     *
```
Comment (damithc) [inline src/main/java/teammates/ui/controller/Action.java]: Line 119 can be removed?

**Comment by Neurrone** [comment]
@damithc fixing it properly will still require this workaround so that existing links continue to work.

**Comment by damithc** [comment]
> @damithc fixing it properly will still require this workaround so that existing links continue to work.

Noted. It's fine to keep the workaround for a while for legacy reasons as long as a proper fix is applied. The longer we keep generating incorrect links, the harder it will be to eventually get rid of the workaround.

**Comment by wkurniawan07** [comment]
@damithc this issue could be traced as far back as #4575.
I'd still go by the opinion I made back then: the only sure way to prevent this is to encrypt the `next` URL.

**Comment by damithc** [comment]
> @damithc this issue could be traced as far back as #4575.
> I'd still go by the opinion I made back then: the only sure way to prevent this is to encrypt the next URL.

I see. I guess we should create an issue with the suggested solution and links to past issues (like this one)?

**Comment by Neurrone** [comment]
@damithc changes made.
